ANIMA: animaT2EPGRelaxometryEstimation.cxx File Reference
animaT2EPGRelaxometryEstimation.cxx File Reference
#include <iostream>
#include <tclap/CmdLine.h>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <animaT2EPGRelaxometryEstimationImageFilter.h>
#include <animaReadWriteFunctions.h>
#include <itkTimeProbe.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char **argv)
Function Documentation
eventCallback()
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 11 of file animaT2EPGRelaxometryEstimation.cxx.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 17 of file animaT2EPGRelaxometryEstimation.cxx.
References eventCallback(), and anima::readImage().