ANIMA: animaNLMeansPatientToGroupComparison.cxx File Reference
animaNLMeansPatientToGroupComparison.cxx File Reference
#include <iostream>
#include <tclap/CmdLine.h>
#include <animaReadWriteFunctions.h>
#include <animaNLMeansPatientToGroupComparisonImageFilter.h>
#include <itkTimeProbe.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char **argv)
Function Documentation
eventCallback()
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 9 of file animaNLMeansPatientToGroupComparison.cxx.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 15 of file animaNLMeansPatientToGroupComparison.cxx.
References eventCallback(), anima::readImage(), and anima::writeImage().