ANIMA: animaApplyTransformSerie.cxx File Reference
animaApplyTransformSerie.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkResampleImageFilter.h>
#include <itkNearestNeighborInterpolateImageFunction.h>
#include <itkLinearInterpolateImageFunction.h>
#include <itkBSplineInterpolateImageFunction.h>
#include <itkWindowedSincInterpolateImageFunction.h>
#include <itkConstantBoundaryCondition.h>
#include <itkImageRegionIterator.h>
#include <itkExtractImageFilter.h>
#include <animaResampleImageFilter.h>
#include <animaTransformSeriesReader.h>
#include <animaReadWriteFunctions.h>
#include <animaRetrieveImageTypeMacros.h>
#include <animaGradientFileReader.h>
#include <itkTransformToDisplacementFieldFilter.h>
Classes
struct arguments
Functions
template<class ImageType >
void applyScalarTransfo (itk::ImageIOBase::Pointer geometryImageIO, const arguments &args)
template<class ImageType >
void applyScalarTransfo4D (itk::ImageIOBase::Pointer geometryImageIO, const arguments &args)
void applyTransformationToGradients (std::string &inputGradientsFileName, std::string &outputGradientsFileName, const arguments &args)
template<class ImageType >
void applyVectorTransfo (itk::ImageIOBase::Pointer geometryImageIO, const arguments &args)
template<class ComponentType , int Dimension>
void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer inputImageIO, itk::ImageIOBase::Pointer geometryImageIO, const arguments &args)
int main (int ac, const char **av)
template<class ComponentType >
void retrieveNbDimensions (itk::ImageIOBase::Pointer inputImageIO, itk::ImageIOBase::Pointer geometryImageIO, const arguments &args)
Function Documentation
applyScalarTransfo()
template<class ImageType > void applyScalarTransfo (itk::ImageIOBase::Pointer geometryImageIO, const arguments & args)
Definition at line 316 of file animaApplyTransformSerie.cxx.
References arguments::exponentiationOrder, arguments::input, arguments::interpolation, arguments::invert, arguments::origin, arguments::output, arguments::pthread, anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput(), arguments::spacing, and arguments::transfo.
applyScalarTransfo4D()
template<class ImageType > void applyScalarTransfo4D (itk::ImageIOBase::Pointer geometryImageIO, const arguments & args)
Definition at line 173 of file animaApplyTransformSerie.cxx.
References arguments::exponentiationOrder, arguments::input, arguments::interpolation, arguments::invert, arguments::origin, arguments::output, arguments::pthread, anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput(), arguments::spacing, and arguments::transfo.
applyTransformationToGradients()
void applyTransformationToGradients (std::string & inputGradientsFileName, std::string & outputGradientsFileName, const arguments & args)
Definition at line 30 of file animaApplyTransformSerie.cxx.
References arguments::exponentiationOrder, arguments::invert, arguments::pthread, anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName(), anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput(), and arguments::transfo.
Referenced by main().
applyVectorTransfo()
template<class ImageType > void applyVectorTransfo (itk::ImageIOBase::Pointer geometryImageIO, const arguments & args)
Definition at line 99 of file animaApplyTransformSerie.cxx.
References arguments::exponentiationOrder, arguments::input, arguments::interpolation, arguments::invert, arguments::origin, arguments::output, arguments::pthread, anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput(), arguments::spacing, and arguments::transfo.
checkIfComponentsAreVectors()
template<class ComponentType , int Dimension> void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer inputImageIO, itk::ImageIOBase::Pointer geometryImageIO, const arguments & args)
Definition at line 392 of file animaApplyTransformSerie.cxx.
main()
int main (int ac, const char ** av)
Definition at line 424 of file animaApplyTransformSerie.cxx.
References ANIMA_RETRIEVE_COMPONENT_TYPE, applyTransformationToGradients(), arguments::exponentiationOrder, arguments::geometry, arguments::input, arguments::interpolation, arguments::invert, arguments::output, arguments::pthread, retrieveNbDimensions(), anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput(), and arguments::transfo.
retrieveNbDimensions()
template<class ComponentType > void retrieveNbDimensions (itk::ImageIOBase::Pointer inputImageIO, itk::ImageIOBase::Pointer geometryImageIO, const arguments & args)
Definition at line 412 of file animaApplyTransformSerie.cxx.
Referenced by main().