ANIMA: animaLocalPatchMeanDistance.cxx File Reference
animaLocalPatchMeanDistance.cxx File Reference
#include <iostream>
#include <tclap/CmdLine.h>
#include <animaReadWriteFunctions.h>
#include <animaLocalPatchMeanDistanceImageFilter.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char **argv)
Function Documentation
eventCallback()
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 8 of file animaLocalPatchMeanDistance.cxx.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 14 of file animaLocalPatchMeanDistance.cxx.
References eventCallback(), anima::readImage(), and anima::writeImage().