ANIMA: animaCollapseImage.cxx File Reference
animaCollapseImage.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkImage.h>
#include <itkVectorImage.h>
#include <itkCommand.h>
#include <itkExtractImageFilter.h>
#include <animaReadWriteFunctions.h>
#include <animaRetrieveImageTypeMacros.h>
Classes
struct arguments
Functions
template<class ComponentType , unsigned int InputDim>
void collapse (itk::ImageIOBase::Pointer imageIO, const arguments &args)
int main (int ac, const char **av)
template<class ComponentType >
void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments &args)
Function Documentation
collapse()
template<class ComponentType , unsigned int InputDim> void collapse (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 19 of file animaCollapseImage.cxx.
References arguments::input, arguments::origin, arguments::output, and arguments::spacing.
Referenced by retrieveNbDimensions().
main()
int main (int ac, const char ** av)
Definition at line 100 of file animaCollapseImage.cxx.
References ANIMA_RETRIEVE_COMPONENT_TYPE, arguments::input, arguments::origin, arguments::output, retrieveNbDimensions(), and arguments::spacing.
retrieveNbDimensions()
template<class ComponentType > void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 94 of file animaCollapseImage.cxx.
References ANIMA_RETRIEVE_NUMBER_OF_DIMENSIONS, and collapse().
Referenced by main().