ANIMA: animaConvertImage.cxx File Reference
animaConvertImage.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkImage.h>
#include <itkOrientImageFilter.h>
#include <animaReorientation.h>
#include <animaReadWriteFunctions.h>
#include <animaRetrieveImageTypeMacros.h>
Classes
struct arguments
Functions
template<class ComponentType , int dimension>
void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer imageIO, const arguments &args)
template<class ImageType >
void convert (const arguments &args)
int main (int ac, const char **av)
template<class ComponentType >
void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments &args)
Function Documentation
checkIfComponentsAreVectors()
template<class ComponentType , int dimension> void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 99 of file animaConvertImage.cxx.
References ANIMA_CHECK_IF_COMPONENTS_ARE_VECTORS, and convert().
Referenced by retrieveNbDimensions().
convert()
template<class ImageType > void convert (const arguments & args)
Definition at line 19 of file animaConvertImage.cxx.
References arguments::gradientFileName, arguments::input, arguments::output, arguments::reorient, anima::reorientGradients(), anima::reorientImage(), anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName(), and arguments::space.
Referenced by checkIfComponentsAreVectors().
main()
int main (int ac, const char ** av)
Definition at line 111 of file animaConvertImage.cxx.
References ANIMA_RETRIEVE_COMPONENT_TYPE, arguments::displayInfo, arguments::gradientFileName, arguments::input, arguments::output, arguments::reorient, retrieveNbDimensions(), and arguments::space.
retrieveNbDimensions()
template<class ComponentType > void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 106 of file animaConvertImage.cxx.
References ANIMA_RETRIEVE_NUMBER_OF_DIMENSIONS, and checkIfComponentsAreVectors().
Referenced by main().