ANIMA: animaDTITractography.cxx File Reference
animaDTITractography.cxx File Reference
#include <animaDTITractographyImageFilter.h>
#include <itkTimeProbe.h>
#include <animaReadWriteFunctions.h>
#include <animaLogTensorImageFilter.h>
#include <itkMultiThreader.h>
#include <itkCommand.h>
#include <tclap/CmdLine.h>
#include <animaShapesWriter.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char *argv[])
Function Documentation
eventCallback()
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 14 of file animaDTITractography.cxx.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 20 of file animaDTITractography.cxx.
References eventCallback(), anima::ShapesWriter::SetFileName(), anima::ShapesWriter::SetInputData(), and anima::ShapesWriter::Update().