ANIMA: animaN4BiasCorrection.cxx File Reference
animaN4BiasCorrection.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkN4BiasFieldCorrectionImageFilter.h>
#include <animaReadWriteFunctions.h>
#include <itkConstantPadImageFilter.h>
#include <itkOtsuThresholdImageFilter.h>
#include <itkShrinkImageFilter.h>
#include <itkCommand.h>
#include <itkTimeProbe.h>
Functions
void checkIterationArg (std::string &sIterations)
template<typename T >
T convertStringToNumber (std::string const &pi_rsValue)
template<typename T >
std::vector< T > ConvertVector (std::string &pi_rsVector)
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
std::vector< unsigned int > extractMaxNumberOfIterationsVector (std::string pi_rsIterations)
int main (int argc, char *argv[])
Function Documentation
checkIterationArg()
void checkIterationArg (std::string & sIterations)
Definition at line 62 of file animaN4BiasCorrection.cxx.
Referenced by extractMaxNumberOfIterationsVector().
convertStringToNumber()
template<typename T > T convertStringToNumber (std::string const & pi_rsValue)
Definition at line 18 of file animaN4BiasCorrection.cxx.
ConvertVector()
template<typename T > std::vector<T> ConvertVector (std::string & pi_rsVector)
Definition at line 28 of file animaN4BiasCorrection.cxx.
eventCallback()
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 11 of file animaN4BiasCorrection.cxx.
Referenced by main().
extractMaxNumberOfIterationsVector()
std::vector<unsigned int> extractMaxNumberOfIterationsVector (std::string pi_rsIterations)
Definition at line 75 of file animaN4BiasCorrection.cxx.
References checkIterationArg().
Referenced by main().
main()
int main (int argc, char * argv[])
Reconstruct the bias field at full image resolution. Divide the original input image by the bias field to get the final corrected image.
Definition at line 81 of file animaN4BiasCorrection.cxx.
References eventCallback(), and extractMaxNumberOfIterationsVector().