ANIMA: animaCropImage.cxx File Reference
animaCropImage.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkImage.h>
#include <itkCommand.h>
#include <itkExtractImageFilter.h>
#include <itkImageRegionIteratorWithIndex.h>
#include <animaReadWriteFunctions.h>
#include <animaRetrieveImageTypeMacros.h>
Classes
struct arguments
Functions
template<class ComponentType , int dimension>
void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer imageIO, const arguments &args)
template<class InputImageType >
void evaluateOutputType (const arguments &args)
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
template<class InputImageType , unsigned int OutputDimension>
void extract (const arguments &args)
int main (int ac, const char **av)
template<class ComponentType >
void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments &args)
Function Documentation
checkIfComponentsAreVectors()
template<class ComponentType , int dimension> void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 187 of file animaCropImage.cxx.
References ANIMA_CHECK_IF_COMPONENTS_ARE_VECTORS, and evaluateOutputType().
Referenced by retrieveNbDimensions().
evaluateOutputType()
template<class InputImageType > void evaluateOutputType (const arguments & args)
Definition at line 101 of file animaCropImage.cxx.
References arguments::tsize, arguments::xsize, arguments::ysize, and arguments::zsize.
Referenced by checkIfComponentsAreVectors().
eventCallback()
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 13 of file animaCropImage.cxx.
Referenced by extract().
extract()
template<class InputImageType , unsigned int OutputDimension> void extract (const arguments & args)
Definition at line 27 of file animaCropImage.cxx.
References eventCallback(), arguments::input, arguments::output, arguments::tindex, arguments::tsize, arguments::xindex, arguments::xsize, arguments::yindex, arguments::ysize, arguments::zindex, and arguments::zsize.
main()
int main (int ac, const char ** av)
Definition at line 200 of file animaCropImage.cxx.
References ANIMA_RETRIEVE_COMPONENT_TYPE, arguments::input, arguments::output, retrieveNbDimensions(), arguments::tindex, arguments::tsize, arguments::xindex, arguments::xsize, arguments::yindex, arguments::ysize, arguments::zindex, and arguments::zsize.
retrieveNbDimensions()
template<class ComponentType > void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 195 of file animaCropImage.cxx.
References ANIMA_RETRIEVE_NUMBER_OF_DIMENSIONS, and checkIfComponentsAreVectors().
Referenced by main().