ANIMA: animaFibersApplyTransformSerie.cxx File Reference
animaFibersApplyTransformSerie.cxx File Reference
#include <tclap/CmdLine.h>
#include <animaTransformSeriesReader.h>
#include <animaShapesReader.h>
#include <animaShapesWriter.h>
#include <vtkPolyData.h>
Functions
void ApplyTransformToTracks (vtkPoints *dataPoints, anima::TransformSeriesReader< double, 3 >::OutputTransformType *transform)
int main (int ac, const char **av)
Function Documentation
ApplyTransformToTracks()
void ApplyTransformToTracks (vtkPoints * dataPoints, anima::TransformSeriesReader< double, 3 >::OutputTransformType * transform)
Definition at line 8 of file animaFibersApplyTransformSerie.cxx.
Referenced by main().
main()
int main (int ac, const char ** av)
Definition at line 28 of file animaFibersApplyTransformSerie.cxx.
References ApplyTransformToTracks(), anima::ShapesReader::GetOutput(), anima::ShapesReader::SetFileName(), anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput(), anima::ShapesWriter::SetInputData(), and anima::ShapesReader::Update().