ANIMA: animaMCMEstimator.cxx File Reference
animaMCMEstimator.cxx File Reference
#include <fstream>
#include <itkTimeProbe.h>
#include <tclap/CmdLine.h>
#include <animaMCMEstimatorImageFilter.h>
#include <animaGradientFileReader.h>
#include <animaVectorOperations.h>
#include <animaReadWriteFunctions.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int argc, char **argv)
Function Documentation
eventCallback()
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 12 of file animaMCMEstimator.cxx.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 18 of file animaMCMEstimator.cxx.
References anima::DiffusionBigDelta, anima::DiffusionSmallDelta, eventCallback(), anima::NODDI, anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName(), anima::Stick, anima::Tensor, anima::writeImage(), and anima::Zeppelin.