ANIMA: animaVectorizeImages.cxx File Reference
animaVectorizeImages.cxx File Reference
#include <tclap/CmdLine.h>
#include <animaReadWriteFunctions.h>
#include <animaRetrieveImageTypeMacros.h>
#include <itkComposeImageFilter.h>
Classes
struct arguments
Functions
template<class ComponentType , int dimension>
void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer imageIO, const arguments &args)
int main (int ac, const char **av)
template<class ComponentType >
void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments &args)
template<class InputImageType >
void vectorize (const arguments &args)
Function Documentation
checkIfComponentsAreVectors()
template<class ComponentType , int dimension> void checkIfComponentsAreVectors (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 43 of file animaVectorizeImages.cxx.
Referenced by retrieveNbDimensions().
main()
int main (int ac, const char ** av)
Definition at line 64 of file animaVectorizeImages.cxx.
References ANIMA_RETRIEVE_COMPONENT_TYPE, arguments::fileList, and retrieveNbDimensions().
retrieveNbDimensions()
template<class ComponentType > void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 59 of file animaVectorizeImages.cxx.
References ANIMA_RETRIEVE_NUMBER_OF_DIMENSIONS, and checkIfComponentsAreVectors().
Referenced by main().
vectorize()
template<class InputImageType > void vectorize (const arguments & args)
Definition at line 17 of file animaVectorizeImages.cxx.
References arguments::fileList, arguments::inputs, arguments::nbComponents, and arguments::output.