ANIMA: animaSphereAverageTest.cxx File Reference
animaSphereAverageTest.cxx File Reference
#include <animaLogExpMapsUnitSphere.h>
#include <tclap/CmdLine.h>
#include <animaDistributionSampling.h>
#include <itkVariableLengthVector.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 8 of file animaSphereAverageTest.cxx.
References anima::ComputeSphericalCentroid(), anima::SampleFromUniformDistribution(), and anima::SampleFromUniformDistributionOn2Sphere().