ANIMA: animaFibersFilterer.cxx File Reference
animaFibersFilterer.cxx File Reference
#include <tclap/CmdLine.h>
#include <animaReadWriteFunctions.h>
#include <animaShapesWriter.h>
#include <animaShapesReader.h>
#include <vtkSmartPointer.h>
#include <vtkPoints.h>
#include <vtkPointData.h>
#include <vtkPolyData.h>
#include <vtkCleanPolyData.h>
#include <vtkGenericCell.h>
#include <itkNearestNeighborInterpolateImageFunction.h>
#include <itkMultiThreader.h>
Classes
struct ThreaderArguments
Functions
void FilterTracks (vtkPolyData *tracks, unsigned int startIndex, unsigned int endIndex, itk::NearestNeighborInterpolateImageFunction< itk::Image< unsigned short, 3 > > *interpolator, const std::vector< unsigned int > &touchLabels, const std::vector< unsigned int > &forbiddenLabels)
int main (int argc, char **argv)
ITK_THREAD_RETURN_TYPE ThreadFilterer (void *arg)
Function Documentation
FilterTracks()
void FilterTracks (vtkPolyData * tracks, unsigned int startIndex, unsigned int endIndex, itk::NearestNeighborInterpolateImageFunction< itk::Image< unsigned short, 3 > > * interpolator, const std::vector< unsigned int > & touchLabels, const std::vector< unsigned int > & forbiddenLabels)
Definition at line 17 of file animaFibersFilterer.cxx.
Referenced by ThreadFilterer().
main()
int main (int argc, char ** argv)
Definition at line 118 of file animaFibersFilterer.cxx.
References ThreaderArguments::forbiddenLabels, anima::ShapesReader::GetOutput(), ThreaderArguments::interpolator, anima::ShapesReader::SetFileName(), anima::ShapesWriter::SetFileName(), anima::ShapesWriter::SetInputData(), ThreadFilterer(), ThreaderArguments::touchLabels, ThreaderArguments::tracks, anima::ShapesReader::Update(), and anima::ShapesWriter::Update().
ThreadFilterer()
ITK_THREAD_RETURN_TYPE ThreadFilterer (void * arg)
Definition at line 97 of file animaFibersFilterer.cxx.
References FilterTracks(), ThreaderArguments::forbiddenLabels, ThreaderArguments::interpolator, ThreaderArguments::touchLabels, and ThreaderArguments::tracks.
Referenced by main().