ANIMA: animaConvertShape.cxx File Reference
animaConvertShape.cxx File Reference
#include <tclap/CmdLine.h>
#include <animaShapesReader.h>
#include <animaShapesWriter.h>
Functions
int main (int ac, const char **av)
Function Documentation
main()
int main (int ac, const char ** av)
Definition at line 6 of file animaConvertShape.cxx.
References anima::ShapesReader::GetOutput(), anima::ShapesReader::SetFileName(), anima::ShapesWriter::SetFileName(), anima::ShapesWriter::SetInputData(), anima::ShapesReader::Update(), and anima::ShapesWriter::Update().