ANIMA: animaDenseMCMSVFBMRegistration.cxx File Reference
animaDenseMCMSVFBMRegistration.cxx File Reference
#include <animaPyramidalDenseMCMSVFMatchingBridge.h>
#include <animaMCMFileReader.h>
#include <animaGradientFileReader.h>
#include <tclap/CmdLine.h>
#include <itkTimeProbe.h>
#include <animaMCMConstants.h>
Functions
int main (int ac, const char **av)
Function Documentation
main()
int main (int ac, const char ** av)
Definition at line 9 of file animaDenseMCMSVFBMRegistration.cxx.
References anima::DiffusionBigDelta, anima::DiffusionSmallDelta, anima::MCMFileReader< PixelType, ImageDimension >::GetModelVectorImage(), anima::MCMFileReader< PixelType, ImageDimension >::SetFileName(), anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName(), and anima::MCMFileReader< PixelType, ImageDimension >::Update().