ANIMA: animaMCMApplyTransformSerie.cxx File Reference
animaMCMApplyTransformSerie.cxx File Reference
#include <tclap/CmdLine.h>
#include <animaMCMFileReader.h>
#include <animaMCMFileWriter.h>
#include <animaMultiCompartmentModelCreator.h>
#include <itkImageFileReader.h>
#include <animaTransformSeriesReader.h>
#include <itkNearestNeighborInterpolateImageFunction.h>
#include <animaMCMLinearInterpolateImageFunction.h>
#include <animaMCMResampleImageFilter.h>
Functions
int main (int ac, const char **av)
Function Documentation
main()
int main (int ac, const char ** av)
Definition at line 14 of file animaMCMApplyTransformSerie.cxx.
References anima::FreeWater, anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::IsotropicRestrictedWater, anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::New(), anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MCMFileWriter< PixelType, ImageDimension >::SetFileName(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetReferenceOutputModel(), anima::StationaryWater, and anima::Tensor.