ANIMA: animaNyulStandardization.cxx File Reference
animaNyulStandardization.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkHistogramMatchingImageFilter.h>
#include <animaReadWriteFunctions.h>
#include <animaRetrieveImageTypeMacros.h>
Classes
struct arguments
Functions
int main (int argc, char **argv)
template<class ComponentType >
void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments &args)
template<class ComponentType , unsigned int InputDim>
void standardize (itk::ImageIOBase::Pointer imageIO, const arguments &args)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 40 of file animaNyulStandardization.cxx.
References ANIMA_RETRIEVE_COMPONENT_TYPE, arguments::moving, arguments::nlevels, arguments::npoints, arguments::nthreads, arguments::output, arguments::reference, and retrieveNbDimensions().
retrieveNbDimensions()
template<class ComponentType > void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 35 of file animaNyulStandardization.cxx.
References ANIMA_RETRIEVE_NUMBER_OF_DIMENSIONS, and standardize().
Referenced by main().
standardize()
template<class ComponentType , unsigned int InputDim> void standardize (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 16 of file animaNyulStandardization.cxx.
References arguments::moving, arguments::nlevels, arguments::npoints, arguments::nthreads, arguments::output, and arguments::reference.
Referenced by retrieveNbDimensions().