ANIMA: anima::AsymmetricBMRegistrationMethod< TInputImageType > Class Template Reference
anima::AsymmetricBMRegistrationMethod< TInputImageType > Class Template Reference
#include <animaAsymmetricBMRegistrationMethod.h>
Public Types
typedef Superclass::AgregatorType AgregatorType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageType InputImageType
typedef itk::SmartPointer< Self > Pointer
typedef AsymmetricBMRegistrationMethod Self
typedef BaseBMRegistrationMethod< TInputImageType > Superclass
typedef Superclass::TransformPointer TransformPointer
Public Types inherited from anima::BaseBMRegistrationMethod< TInputImageType >
typedef AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform< typename AgregatorType::ScalarType, TInputImageType::ImageDimension > AffineTransformType
typedef AgregatorType::ScalarType AgregatorScalarType
typedef anima::BaseTransformAgregator< TInputImageType::ImageDimension > AgregatorType
typedef AgregatorType::BaseInputTransformType BaseInputTransformType
typedef AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef anima::BaseBlockMatcher< TInputImageType > BlockMatcherType
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef rpi::DisplacementFieldTransform< AgregatorScalarType, TInputImageType::ImageDimension > DisplacementFieldTransformType
typedef TInputImageType::IOPixelType ImageScalarType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImageType InputImageType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TInputImageType::ImageDimension > MaskImageType
typedef itk::SmartPointer< Self > Pointer
typedef ResamplerFilterType::Pointer ResamplerFilterPointer
typedef itk::ImageToImageFilter< InputImageType, InputImageType > ResamplerFilterType
typedef BaseBMRegistrationMethod Self
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef itk::StationaryVelocityFieldTransform< AgregatorScalarType, TInputImageType::ImageDimension > SVFTransformType
typedef TransformOutputType::Pointer TransformOutputPointer
typedef itk::DataObjectDecorator< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Public Member Functions inherited from anima::BaseBMRegistrationMethod< TInputImageType >
void Abort ()
virtual AgregatorType * GetAgregator ()
virtual unsigned int GetBCHCompositionOrder ()
BlockMatcherType * GetBlockMatcher ()
virtual unsigned int GetExponentiationOrder ()
virtual InputImageType * GetFixedImage ()
TransformPointer & GetInitialTransform ()
virtual unsigned int GetMaximumIterations ()
virtual double GetMinimalTransformError ()
virtual InputImageType * GetMovingImage ()
ResamplerFilterPointer & GetMovingImageResampler ()
TransformOutputType * GetOutput ()
ResamplerFilterPointer & GetReferenceImageResampler ()
virtual double GetSVFElasticRegSigma ()
virtual bool GetVerboseProgression ()
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx) ITK_OVERRIDE
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetBCHCompositionOrder (unsigned int _arg)
void SetBlockMatcher (BlockMatcherType *matcher)
virtual void SetExponentiationOrder (unsigned int _arg)
virtual void SetFixedImage (InputImageType *_arg)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMinimalTransformError (double _arg)
virtual void SetMovingImage (InputImageType *_arg)
void SetMovingImageResampler (ResamplerFilterType *filter)
void SetReferenceImageResampler (ResamplerFilterType *filter)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
AsymmetricBMRegistrationMethod ()
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn) ITK_OVERRIDE
virtual ~AsymmetricBMRegistrationMethod ()
Protected Member Functions inherited from anima::BaseBMRegistrationMethod< TInputImageType >
BaseBMRegistrationMethod ()
virtual bool ComposeAddOnWithTransform (TransformPointer &computedTransform, TransformType *addOn)
void GenerateData () ITK_OVERRIDE
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &movingImage)
virtual void SetupTransform (TransformPointer &optimizedTransform)
void StartOptimization ()
virtual ~BaseBMRegistrationMethod ()
Detailed Description
template<typename TInputImageType>
class anima::AsymmetricBMRegistrationMethod< TInputImageType >
Definition at line 8 of file animaAsymmetricBMRegistrationMethod.h.
Member Typedef Documentation
AgregatorType
template<typename TInputImageType > typedef Superclass::AgregatorType anima::AsymmetricBMRegistrationMethod< TInputImageType >::AgregatorType
Definition at line 19 of file animaAsymmetricBMRegistrationMethod.h.
ConstPointer
template<typename TInputImageType > typedef itk::SmartPointer<const Self> anima::AsymmetricBMRegistrationMethod< TInputImageType >::ConstPointer
Definition at line 15 of file animaAsymmetricBMRegistrationMethod.h.
InputImageType
template<typename TInputImageType > typedef Superclass::InputImageType anima::AsymmetricBMRegistrationMethod< TInputImageType >::InputImageType
Definition at line 17 of file animaAsymmetricBMRegistrationMethod.h.
Pointer
template<typename TInputImageType > typedef itk::SmartPointer<Self> anima::AsymmetricBMRegistrationMethod< TInputImageType >::Pointer
Definition at line 14 of file animaAsymmetricBMRegistrationMethod.h.
Self
template<typename TInputImageType > typedef AsymmetricBMRegistrationMethod anima::AsymmetricBMRegistrationMethod< TInputImageType >::Self
Standard class typedefs.
Definition at line 12 of file animaAsymmetricBMRegistrationMethod.h.
Superclass
template<typename TInputImageType > typedef BaseBMRegistrationMethod<TInputImageType> anima::AsymmetricBMRegistrationMethod< TInputImageType >::Superclass
Definition at line 13 of file animaAsymmetricBMRegistrationMethod.h.
TransformPointer
template<typename TInputImageType > typedef Superclass::TransformPointer anima::AsymmetricBMRegistrationMethod< TInputImageType >::TransformPointer
Definition at line 18 of file animaAsymmetricBMRegistrationMethod.h.
Constructor & Destructor Documentation
AsymmetricBMRegistrationMethod()
template<typename TInputImageType > anima::AsymmetricBMRegistrationMethod< TInputImageType >::AsymmetricBMRegistrationMethod () inline protected
Definition at line 27 of file animaAsymmetricBMRegistrationMethod.h.
Referenced by anima::AsymmetricBMRegistrationMethod< TInputImageType >::~AsymmetricBMRegistrationMethod().
~AsymmetricBMRegistrationMethod()
template<typename TInputImageType > virtual anima::AsymmetricBMRegistrationMethod< TInputImageType >::~AsymmetricBMRegistrationMethod () inline protected virtual
Definition at line 28 of file animaAsymmetricBMRegistrationMethod.h.
References anima::AsymmetricBMRegistrationMethod< TInputImageType >::AsymmetricBMRegistrationMethod(), and anima::AsymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration().
Member Function Documentation
CreateAnother()
template<typename TInputImageType > virtual::itk::LightObject::Pointer anima::AsymmetricBMRegistrationMethod< TInputImageType >::CreateAnother (void) const
GetNameOfClass()
template<typename TInputImageType > virtual const char* anima::AsymmetricBMRegistrationMethod< TInputImageType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
New()
template<typename TInputImageType > static Pointer anima::AsymmetricBMRegistrationMethod< TInputImageType >::New () static
PerformOneIteration()
template<typename TInputImageType > void anima::AsymmetricBMRegistrationMethod< TInputImageType >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) protected virtual
Implements anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 13 of file animaAsymmetricBMRegistrationMethod.hxx.
Referenced by anima::AsymmetricBMRegistrationMethod< TInputImageType >::~AsymmetricBMRegistrationMethod().
The documentation for this class was generated from the following files:
animaAsymmetricBMRegistrationMethod.h
animaAsymmetricBMRegistrationMethod.hxx