ANIMA: anima::SegPerfApp Class Reference
anima::SegPerfApp Class Reference
Main class to structure application and handle command line options.
#include <animaSegPerfApp.h>
Public Member Functions
void checkOutputCoherence ()
This method define an output way if none are defined by command line.
bool checkParamsCoherence ()
This method check if command line arguments are coherent between us.
bool init (int argc, char *argv[])
This method set the application behavior thanks to command line arguments parsing.
void play ()
This method execute images filter to obtain desired measures, marks and scores.
void prepareOutput ()
This method define the base file name for output way.
SegPerfApp (void)
~SegPerfApp (void)
Static Public Member Functions
static void about ()
This method display information about SegPerfAnalyzer results.
Protected Member Functions
void processAnalyze (SegPerfCAnalyzer &pi_oAnalyzer, int pi_iIndex)
This method provides computing metrics, marks and scores for desired label.
void storeMetricsAndMarks (SegPerfResults &pi_roRes)
This method store results into SegPerfResults class instance.
long writeStoredMetricsAndMarks (SegPerfResults &pi_roRes)
This method flush SegPerfResults class instance.
Detailed Description
Main class to structure application and handle command line options.
Definition at line 13 of file animaSegPerfApp.h.
Constructor & Destructor Documentation
SegPerfApp()
anima::SegPerfApp::SegPerfApp (void)
Definition at line 11 of file animaSegPerfApp.cxx.
~SegPerfApp()
anima::SegPerfApp::~SegPerfApp (void)
Definition at line 61 of file animaSegPerfApp.cxx.
Member Function Documentation
about()
void anima::SegPerfApp::about () static
This method display information about SegPerfAnalyzer results.
Definition at line 419 of file animaSegPerfApp.cxx.
References anima::SegPerfResults::eMesureLast, and anima::SegPerfResults::getMeasureNameTable().
Referenced by init().
checkOutputCoherence()
void anima::SegPerfApp::checkOutputCoherence ()
This method define an output way if none are defined by command line.
For the moment the default output way is text file.
Definition at line 215 of file animaSegPerfApp.cxx.
Referenced by main().
checkParamsCoherence()
bool anima::SegPerfApp::checkParamsCoherence ()
This method check if command line arguments are coherent between us.
If an incoherence is detected into command line arguments a message will be displayed to user and in better cases consistency will be restored.
Definition at line 160 of file animaSegPerfApp.cxx.
Referenced by main().
init()
bool anima::SegPerfApp::init (int argc, char * argv[])
This method set the application behavior thanks to command line arguments parsing.
Parameters
[in] argc is the number of command line arguments.
[in] argv is the table of command line arguments.
The main function must delegate to it command line arguments. this method will parse and set different option values.
Definition at line 71 of file animaSegPerfApp.cxx.
References about().
Referenced by main().
play()
void anima::SegPerfApp::play ()
This method execute images filter to obtain desired measures, marks and scores.
Definition at line 263 of file animaSegPerfApp.cxx.
References anima::SegPerfCAnalyzer::checkImagesMatrixAndVolumes(), anima::SegPerfCAnalyzer::getNumberOfClusters(), processAnalyze(), anima::SegPerfCAnalyzer::setNbThreads(), storeMetricsAndMarks(), and writeStoredMetricsAndMarks().
Referenced by main().
prepareOutput()
void anima::SegPerfApp::prepareOutput ()
This method define the base file name for output way.
Definition at line 226 of file animaSegPerfApp.cxx.
Referenced by main().
processAnalyze()
void anima::SegPerfApp::processAnalyze (SegPerfCAnalyzer & pi_roAnalyzer, int pi_iIndex) protected
This method provides computing metrics, marks and scores for desired label.
Parameters
[in] pi_roAnalyzer is the reference on the image analyzer class instance.
[in] pi_iIndex is label index.
This method is called by play method.
Definition at line 312 of file animaSegPerfApp.cxx.
References anima::SegPerfCAnalyzer::computeAverageSurfaceDistance(), anima::SegPerfCAnalyzer::computeHausdorffDist(), anima::SegPerfCAnalyzer::computeITKMeasures(), anima::SegPerfCAnalyzer::computeMeanDist(), anima::SegPerfCAnalyzer::getDetectionMarks(), anima::SegPerfCAnalyzer::getDiceCoefficient(), anima::SegPerfCAnalyzer::getJaccardCoefficient(), anima::SegPerfCAnalyzer::getNPV(), anima::SegPerfCAnalyzer::getPPV(), anima::SegPerfCAnalyzer::getRelativeVolumeError(), anima::SegPerfCAnalyzer::getSensitivity(), anima::SegPerfCAnalyzer::getSpecificity(), anima::SegPerfCAnalyzer::selectCluster(), anima::SegPerfCAnalyzer::setDetectionThresholdAlpha(), anima::SegPerfCAnalyzer::setDetectionThresholdBeta(), anima::SegPerfCAnalyzer::setDetectionThresholdGamma(), and anima::SegPerfCAnalyzer::setMinLesionVolumeDetection().
Referenced by play().
storeMetricsAndMarks()
void anima::SegPerfApp::storeMetricsAndMarks (SegPerfResults & pi_roRes) protected
This method store results into SegPerfResults class instance.
Parameters
[in] pi_roRes is the reference output writer class instance.
This method is called by play method after processAnalyze method.
Definition at line 353 of file animaSegPerfApp.cxx.
References anima::SegPerfResults::activeMeasurementOutput(), anima::SegPerfResults::eMesureDice, anima::SegPerfResults::eMesureDistAverage, anima::SegPerfResults::eMesureDistHausdorff, anima::SegPerfResults::eMesureDistMean, anima::SegPerfResults::eMesureF1Test, anima::SegPerfResults::eMesureJaccard, anima::SegPerfResults::eMesureNPV, anima::SegPerfResults::eMesurePPV, anima::SegPerfResults::eMesurePPVL, anima::SegPerfResults::eMesureRelativeVolumeError, anima::SegPerfResults::eMesureSensibility, anima::SegPerfResults::eMesureSensL, anima::SegPerfResults::eMesureSpecificity, anima::SegPerfResults::setAverageSurfaceDist(), anima::SegPerfResults::setContourMeanDist(), anima::SegPerfResults::setDice(), anima::SegPerfResults::setF1test(), anima::SegPerfResults::setHausdorffDist(), anima::SegPerfResults::setJaccard(), anima::SegPerfResults::setNPV(), anima::SegPerfResults::setPPV(), anima::SegPerfResults::setPPVL(), anima::SegPerfResults::setRVE(), anima::SegPerfResults::setScreen(), anima::SegPerfResults::setSensibility(), anima::SegPerfResults::setSensL(), anima::SegPerfResults::setSpecificity(), anima::SegPerfResults::setTxt(), and anima::SegPerfResults::setXml().
Referenced by play().
writeStoredMetricsAndMarks()
long anima::SegPerfApp::writeStoredMetricsAndMarks (SegPerfResults & pi_roRes) protected
This method flush SegPerfResults class instance.
Parameters
[in] pi_roRes is the reference output writer class instance.
This method is called by play method after storeMetricsAndMarks method.
Definition at line 410 of file animaSegPerfApp.cxx.
References anima::SegPerfResults::save().
Referenced by play().
The documentation for this class was generated from the following files:
animaSegPerfApp.h
animaSegPerfApp.cxx