ANIMA: anima::StickCompartment Class Reference
anima::StickCompartment Class Reference
#include <animaStickCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef StickCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType & GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType & GetParametersAsVector () ITK_OVERRIDE
virtual ListType & GetParameterUpperBounds () ITK_OVERRIDE
virtual ListType & GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
virtual bool GetTensorCompatible ()
virtual double GetTissueRadius ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-2, double absoluteTolerance=1.0e-8)
Tests equality to another compartment up to a constant (relative and absolute tolerances)
virtual void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform)
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
virtual void SetAxialDiffusivity (double num)
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
virtual void SetTissueRadius (double num)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
StickCompartment ()
virtual ~StickCompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
ListType m_JacobianVector
Vector holding current jacobian value.
ListType m_ParametersLowerBoundsVector
Vector holding current parameters lower bounds.
ListType m_ParametersUpperBoundsVector
Vector holding current parameters upper bounds.
ListType m_ParametersVector
Vector holding current parameters vector.
Static Protected Attributes inherited from anima::BaseCompartment
static const unsigned int m_SpaceDimension = 3
Detailed Description
Definition at line 9 of file animaStickCompartment.h.
Member Typedef Documentation
BasePointer
typedef Superclass::Pointer anima::StickCompartment::BasePointer
Definition at line 15 of file animaStickCompartment.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::StickCompartment::ConstPointer
Definition at line 17 of file animaStickCompartment.h.
Matrix3DType
typedef Superclass::Matrix3DType anima::StickCompartment::Matrix3DType
Definition at line 20 of file animaStickCompartment.h.
ModelOutputVectorType
typedef Superclass::ModelOutputVectorType anima::StickCompartment::ModelOutputVectorType
Definition at line 18 of file animaStickCompartment.h.
Pointer
typedef itk::SmartPointer<Self> anima::StickCompartment::Pointer
Definition at line 16 of file animaStickCompartment.h.
Self
typedef StickCompartment anima::StickCompartment::Self
Definition at line 13 of file animaStickCompartment.h.
Superclass
typedef BaseCompartment anima::StickCompartment::Superclass
Definition at line 14 of file animaStickCompartment.h.
Vector3DType
typedef Superclass::Vector3DType anima::StickCompartment::Vector3DType
Definition at line 19 of file animaStickCompartment.h.
Constructor & Destructor Documentation
StickCompartment()
anima::StickCompartment::StickCompartment () inline protected
Definition at line 52 of file animaStickCompartment.h.
~StickCompartment()
virtual anima::StickCompartment::~StickCompartment () inline protected virtual
Definition at line 59 of file animaStickCompartment.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::StickCompartment::CreateAnother (void) const
GetCompartmentSize()
unsigned int anima::StickCompartment::GetCompartmentSize () virtual
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implements anima::BaseCompartment.
Definition at line 158 of file animaStickCompartment.cxx.
Referenced by GetCompartmentVector(), and SetCompartmentVector().
GetCompartmentType()
DiffusionModelCompartmentType anima::StickCompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 28 of file animaStickCompartment.h.
References anima::Stick.
GetCompartmentVector()
StickCompartment::ModelOutputVectorType & anima::StickCompartment::GetCompartmentVector () virtual
Get compartment overall description vector, mainly for writing, should be self-contained.
Implements anima::BaseCompartment.
Definition at line 178 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetCompartmentSize(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::m_CompartmentVector, anima::BaseCompartment::m_SpaceDimension, and anima::TransformSphericalToCartesianCoordinates().
GetDiffusionTensor()
const StickCompartment::Matrix3DType & anima::StickCompartment::GetDiffusionTensor () virtual
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented from anima::BaseCompartment.
Definition at line 203 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::m_DiffusionTensor, anima::BaseCompartment::m_SpaceDimension, and anima::TransformSphericalToCartesianCoordinates().
GetFourierTransformedDiffusionProfile()
double anima::StickCompartment::GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 10 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::GetBValueFromAcquisitionParameters(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), and anima::BaseCompartment::GetRadialDiffusivity1().
Referenced by GetSignalAttenuationJacobian().
GetFractionalAnisotropy()
double anima::StickCompartment::GetFractionalAnisotropy () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 224 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::GetRadialDiffusivity1().
GetLogDiffusionProfile()
double anima::StickCompartment::GetLogDiffusionProfile (const Vector3DType & sample) virtual
Implements anima::BaseCompartment.
Definition at line 48 of file animaStickCompartment.cxx.
References anima::ComputeScalarProduct(), anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), and anima::TransformSphericalToCartesianCoordinates().
GetNameOfClass()
virtual const char* anima::StickCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseCompartment.
GetNumberOfParameters()
unsigned int anima::StickCompartment::GetNumberOfParameters () virtual
Number of optimized parameters: smaller than total number of parameters.
Implements anima::BaseCompartment.
Definition at line 163 of file animaStickCompartment.cxx.
Referenced by GetParameterLowerBounds(), GetParametersAsVector(), GetParameterUpperBounds(), GetSignalAttenuationJacobian(), and SetParametersFromVector().
GetParameterLowerBounds()
StickCompartment::ListType & anima::StickCompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 87 of file animaStickCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_ParametersLowerBoundsVector, anima::MCMAxialDiffusivityAddonLowerBound, and anima::MCMZeroLowerBound.
GetParametersAsVector()
StickCompartment::ListType & anima::StickCompartment::GetParametersAsVector () virtual
Implements anima::BaseCompartment.
Definition at line 74 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), and anima::BaseCompartment::m_ParametersVector.
GetParameterUpperBounds()
StickCompartment::ListType & anima::StickCompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 98 of file animaStickCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_ParametersUpperBoundsVector, anima::MCMAzimuthAngleUpperBound, anima::MCMDiffusivityUpperBound, and anima::MCMPolarAngleUpperBound.
GetSignalAttenuationJacobian()
StickCompartment::ListType & anima::StickCompartment::GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 21 of file animaStickCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::GetBValueFromAcquisitionParameters(), GetFourierTransformedDiffusionProfile(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::GetRadialDiffusivity1(), and anima::BaseCompartment::m_JacobianVector.
New()
static Pointer anima::StickCompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
SetCompartmentVector()
void anima::StickCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) virtual
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implements anima::BaseCompartment.
Definition at line 120 of file animaStickCompartment.cxx.
References GetCompartmentSize(), anima::BaseCompartment::m_SpaceDimension, anima::BaseCompartment::SetAxialDiffusivity(), anima::BaseCompartment::SetOrientationPhi(), anima::BaseCompartment::SetOrientationTheta(), anima::BaseCompartment::SetRadialDiffusivity1(), and anima::TransformCartesianToSphericalCoordinates().
SetEstimateAxialDiffusivity()
void anima::StickCompartment::SetEstimateAxialDiffusivity (bool arg)
Definition at line 111 of file animaStickCompartment.cxx.
SetParametersFromVector()
void anima::StickCompartment::SetParametersFromVector (const ListType & params) virtual
Various methods for optimization parameters setting and getting.
Implements anima::BaseCompartment.
Definition at line 62 of file animaStickCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::GetRadialDiffusivity1(), anima::BaseCompartment::SetAxialDiffusivity(), anima::BaseCompartment::SetOrientationPhi(), and anima::BaseCompartment::SetOrientationTheta().
The documentation for this class was generated from the following files:
animaStickCompartment.h
animaStickCompartment.cxx