ANIMA: anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom > Class Template Reference
anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom > Class Template Reference
Class to compute many log-vectors in a multi-threaded way.
#include <animaMatrixLogExp.h>
Classes
struct ThreadedLogData
Public Types
typedef itk::MatrixOffsetTransformBase< TInputScalarType, NDimensions, NDimensions > BaseInputMatrixTransformType
typedef itk::Transform< TInputScalarType, NDimensions, NDimensions > BaseInputTransformType
typedef std::vector< typename BaseInputTransformType::Pointer > InputType
typedef std::vector< OutputVectorType > OutputType
typedef itk::Vector< TOutputScalarType, NDegreesOfFreedom > OutputVectorType
typedef MatrixLoggerFilter Self
Public Member Functions
OutputType & GetOutput ()
MatrixLoggerFilter ()
void SetInput (InputType &input)
void SetNumberOfThreads (unsigned int &numThreads)
void SetUseRigidTransforms (bool rigTrsfs)
void Update ()
~MatrixLoggerFilter ()
Protected Member Functions
void InternalLogger (unsigned int threadId, unsigned int numThreads)
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadedLogging (void *arg)
Detailed Description
template<class TInputScalarType, class TOutputScalarType, unsigned int NDimensions, unsigned int NDegreesOfFreedom>
class anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >
Class to compute many log-vectors in a multi-threaded way.
Definition at line 35 of file animaMatrixLogExp.h.
Member Typedef Documentation
BaseInputMatrixTransformType
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> typedef itk::MatrixOffsetTransformBase<TInputScalarType,NDimensions,NDimensions> anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::BaseInputMatrixTransformType
Definition at line 45 of file animaMatrixLogExp.h.
BaseInputTransformType
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> typedef itk::Transform<TInputScalarType,NDimensions,NDimensions> anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::BaseInputTransformType
Definition at line 43 of file animaMatrixLogExp.h.
InputType
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> typedef std::vector<typename BaseInputTransformType::Pointer> anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::InputType
Definition at line 44 of file animaMatrixLogExp.h.
OutputType
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> typedef std::vector<OutputVectorType> anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::OutputType
Definition at line 41 of file animaMatrixLogExp.h.
OutputVectorType
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> typedef itk::Vector<TOutputScalarType, NDegreesOfFreedom> anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::OutputVectorType
Definition at line 40 of file animaMatrixLogExp.h.
Self
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> typedef MatrixLoggerFilter anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::Self
Definition at line 38 of file animaMatrixLogExp.h.
Constructor & Destructor Documentation
MatrixLoggerFilter()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::MatrixLoggerFilter () inline
Definition at line 47 of file animaMatrixLogExp.h.
~MatrixLoggerFilter()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::~MatrixLoggerFilter () inline
Definition at line 57 of file animaMatrixLogExp.h.
Member Function Documentation
GetOutput()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> OutputType& anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::GetOutput () inline
Definition at line 71 of file animaMatrixLogExp.h.
References anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::Update().
InternalLogger()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> void anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::InternalLogger (unsigned int threadId, unsigned int numThreads) protected
Definition at line 397 of file animaMatrixLogExp.hxx.
References anima::GetLogarithm().
Referenced by anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::ThreadedLogging().
SetInput()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> void anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::SetInput (InputType & input) inline
Definition at line 59 of file animaMatrixLogExp.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
SetNumberOfThreads()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> void anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::SetNumberOfThreads (unsigned int & numThreads) inline
Definition at line 60 of file animaMatrixLogExp.h.
Referenced by anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::Update().
SetUseRigidTransforms()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> void anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::SetUseRigidTransforms (bool rigTrsfs) inline
Definition at line 61 of file animaMatrixLogExp.h.
References anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::Update().
ThreadedLogging()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> ITK_THREAD_RETURN_TYPE anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::ThreadedLogging (void * arg) static protected
Definition at line 380 of file animaMatrixLogExp.hxx.
References anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::InternalLogger(), and anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::ThreadedLogData::loggerFilter.
Referenced by anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::Update().
Update()
template<class TInputScalarType , class TOutputScalarType , unsigned int NDimensions, unsigned int NDegreesOfFreedom> void anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::Update ()
Definition at line 354 of file animaMatrixLogExp.hxx.
References anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::ThreadedLogData::loggerFilter, anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::SetNumberOfThreads(), and anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::ThreadedLogging().
Referenced by anima::Get3DRotationExponential(), anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::GetOutput(), and anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::SetUseRigidTransforms().
The documentation for this class was generated from the following files:
animaMatrixLogExp.h
animaMatrixLogExp.hxx