ANIMA: anima::DenseSVFTransformAgregator< NDimensions > Class Template Reference
anima::DenseSVFTransformAgregator< NDimensions > Class Template Reference
#include <animaDenseSVFTransformAgregator.h>
Public Types
typedef Superclass::BaseInputTransformType BaseInputTransformType
typedef itk::MatrixOffsetTransformBase< InternalScalarType, NDimensions, NDimensions > BaseMatrixTransformType
typedef itk::StationaryVelocityFieldTransform< ScalarType, NDimensions > BaseOutputTransformType
typedef WeightImageType::IndexType IndexType
typedef Superclass::InternalScalarType InternalScalarType
typedef BaseMatrixTransformType::ParametersType ParametersType
typedef Superclass::PointType PointType
typedef Superclass::ScalarType ScalarType
typedef BaseTransformAgregator< NDimensions > Superclass
typedef VelocityFieldType::DirectionType VelocityFieldDirectionType
typedef VelocityFieldType::IndexType VelocityFieldIndexType
typedef VelocityFieldType::PixelType VelocityFieldPixelType
typedef VelocityFieldType::Pointer VelocityFieldPointer
typedef VelocityFieldType::PointType VelocityFieldPointType
typedef VelocityFieldType::RegionType VelocityFieldRegionType
typedef VelocityFieldType::SpacingType VelocityFieldSpacingType
typedef BaseOutputTransformType::VectorFieldType VelocityFieldType
typedef WeightImageType::Pointer WeightImagePointer
typedef itk::Image< ScalarType, NDimensions > WeightImageType
Public Types inherited from anima::BaseTransformAgregator< NDimensions >
typedef BaseInputTransformType::Pointer BaseInputTransformPointer
typedef itk::Transform< InternalScalarType, NDimensions, NDimensions > BaseInputTransformType
typedef itk::Transform< ScalarType, NDimensions, NDimensions > BaseOutputTransformType
typedef double InternalScalarType
typedef itk::Matrix< ScalarType, NDimensions, NDimensions > MatrixType
typedef itk::Point< InternalScalarType, NDimensions > PointType
typedef itk::ImageRegion< NDimensions > RegionType
typedef double ScalarType
enum TRANSFORM_TYPE {
TRANSLATION,
RIGID,
ANISOTROPIC_SIM,
AFFINE,
DIRECTIONAL_AFFINE,
SVF
}
Public Member Functions
DenseSVFTransformAgregator ()
void SetDistanceBoundary (double num)
void SetExtrapolationSigma (double sigma)
template<class TInputImageType >
void SetGeometryInformation (const TInputImageType *geomImage)
void SetMEstimateConvergenceThreshold (double num)
void SetNeighborhoodHalfSize (unsigned int num)
void SetNumberOfThreads (unsigned int num)
void SetOutlierRejectionSigma (double sigma)
virtual bool Update ()
virtual ~DenseSVFTransformAgregator ()
Public Member Functions inherited from anima::BaseTransformAgregator< NDimensions >
BaseTransformAgregator ()
BaseInputTransformPointer & GetCurrentLinearTransform ()
virtual PointType GetEstimationBarycenter ()
PointType & GetInputOrigin (unsigned int i)
std::vector< PointType > & GetInputOrigins ()
std::vector< RegionType > & GetInputRegions ()
BaseInputTransformType * GetInputTransform (unsigned int i)
std::vector< BaseInputTransformPointer > & GetInputTransforms ()
TRANSFORM_TYPE GetInputTransformType ()
InternalScalarType GetInputWeight (unsigned int i)
std::vector< InternalScalarType > & GetInputWeights ()
MatrixType & GetOrthogonalDirectionMatrix ()
BaseOutputTransformType * GetOutput ()
TRANSFORM_TYPE GetOutputTransformType ()
bool GetVerboseAgregation ()
void SetCurrentLinearTransform (BaseInputTransformPointer &inputTransforms)
void SetInputOrigins (const std::vector< PointType > &inputOrigins)
void SetInputRegions (const std::vector< RegionType > &inputRegions)
void SetInputTransforms (std::vector< BaseInputTransformPointer > &inputTransforms)
void SetInputTransformType (TRANSFORM_TYPE name)
void SetInputWeight (unsigned int i, double w)
void SetInputWeights (const std::vector< InternalScalarType > &weights)
void SetOrthogonalDirectionMatrix (const MatrixType &inputTransforms)
void SetOutputTransformType (TRANSFORM_TYPE name)
void SetUpToDate (bool value)
void SetVerboseAgregation (bool value)
virtual ~BaseTransformAgregator ()
Protected Attributes
VelocityFieldDirectionType m_Direction
double m_DistanceBoundary
double m_ExtrapolationSigma
VelocityFieldRegionType m_LargestRegion
double m_MEstimateConvergenceThreshold
unsigned int m_NeighborhoodHalfSize
unsigned int m_NumberOfThreads
VelocityFieldPointType m_Origin
double m_OutlierRejectionSigma
VelocityFieldSpacingType m_Spacing
Additional Inherited Members
Protected Member Functions inherited from anima::BaseTransformAgregator< NDimensions >
void SetOutput (BaseOutputTransformType *output)
Detailed Description
template<unsigned int NDimensions = 3>
class anima::DenseSVFTransformAgregator< NDimensions >
Definition at line 10 of file animaDenseSVFTransformAgregator.h.
Member Typedef Documentation
BaseInputTransformType
template<unsigned int NDimensions = 3> typedef Superclass::BaseInputTransformType anima::DenseSVFTransformAgregator< NDimensions >::BaseInputTransformType
Definition at line 16 of file animaDenseSVFTransformAgregator.h.
BaseMatrixTransformType
template<unsigned int NDimensions = 3> typedef itk::MatrixOffsetTransformBase<InternalScalarType, NDimensions, NDimensions> anima::DenseSVFTransformAgregator< NDimensions >::BaseMatrixTransformType
Definition at line 25 of file animaDenseSVFTransformAgregator.h.
BaseOutputTransformType
template<unsigned int NDimensions = 3> typedef itk::StationaryVelocityFieldTransform<ScalarType,NDimensions> anima::DenseSVFTransformAgregator< NDimensions >::BaseOutputTransformType
Definition at line 18 of file animaDenseSVFTransformAgregator.h.
IndexType
template<unsigned int NDimensions = 3> typedef WeightImageType::IndexType anima::DenseSVFTransformAgregator< NDimensions >::IndexType
Definition at line 22 of file animaDenseSVFTransformAgregator.h.
InternalScalarType
template<unsigned int NDimensions = 3> typedef Superclass::InternalScalarType anima::DenseSVFTransformAgregator< NDimensions >::InternalScalarType
Definition at line 19 of file animaDenseSVFTransformAgregator.h.
ParametersType
template<unsigned int NDimensions = 3> typedef BaseMatrixTransformType::ParametersType anima::DenseSVFTransformAgregator< NDimensions >::ParametersType
Definition at line 26 of file animaDenseSVFTransformAgregator.h.
PointType
template<unsigned int NDimensions = 3> typedef Superclass::PointType anima::DenseSVFTransformAgregator< NDimensions >::PointType
Definition at line 15 of file animaDenseSVFTransformAgregator.h.
ScalarType
template<unsigned int NDimensions = 3> typedef Superclass::ScalarType anima::DenseSVFTransformAgregator< NDimensions >::ScalarType
Definition at line 17 of file animaDenseSVFTransformAgregator.h.
Superclass
template<unsigned int NDimensions = 3> typedef BaseTransformAgregator<NDimensions> anima::DenseSVFTransformAgregator< NDimensions >::Superclass
Definition at line 14 of file animaDenseSVFTransformAgregator.h.
VelocityFieldDirectionType
template<unsigned int NDimensions = 3> typedef VelocityFieldType::DirectionType anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldDirectionType
Definition at line 35 of file animaDenseSVFTransformAgregator.h.
VelocityFieldIndexType
template<unsigned int NDimensions = 3> typedef VelocityFieldType::IndexType anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldIndexType
Definition at line 30 of file animaDenseSVFTransformAgregator.h.
VelocityFieldPixelType
template<unsigned int NDimensions = 3> typedef VelocityFieldType::PixelType anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldPixelType
Definition at line 31 of file animaDenseSVFTransformAgregator.h.
VelocityFieldPointer
template<unsigned int NDimensions = 3> typedef VelocityFieldType::Pointer anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldPointer
Definition at line 29 of file animaDenseSVFTransformAgregator.h.
VelocityFieldPointType
template<unsigned int NDimensions = 3> typedef VelocityFieldType::PointType anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldPointType
Definition at line 32 of file animaDenseSVFTransformAgregator.h.
VelocityFieldRegionType
template<unsigned int NDimensions = 3> typedef VelocityFieldType::RegionType anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldRegionType
Definition at line 33 of file animaDenseSVFTransformAgregator.h.
VelocityFieldSpacingType
template<unsigned int NDimensions = 3> typedef VelocityFieldType::SpacingType anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldSpacingType
Definition at line 34 of file animaDenseSVFTransformAgregator.h.
VelocityFieldType
template<unsigned int NDimensions = 3> typedef BaseOutputTransformType::VectorFieldType anima::DenseSVFTransformAgregator< NDimensions >::VelocityFieldType
Definition at line 28 of file animaDenseSVFTransformAgregator.h.
WeightImagePointer
template<unsigned int NDimensions = 3> typedef WeightImageType::Pointer anima::DenseSVFTransformAgregator< NDimensions >::WeightImagePointer
Definition at line 23 of file animaDenseSVFTransformAgregator.h.
WeightImageType
template<unsigned int NDimensions = 3> typedef itk::Image<ScalarType,NDimensions> anima::DenseSVFTransformAgregator< NDimensions >::WeightImageType
Definition at line 21 of file animaDenseSVFTransformAgregator.h.
Constructor & Destructor Documentation
DenseSVFTransformAgregator()
template<unsigned int NDimensions> anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator ()
Definition at line 17 of file animaDenseSVFTransformAgregator.hxx.
References anima::DenseSVFTransformAgregator< NDimensions >::m_DistanceBoundary, anima::DenseSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma, anima::DenseSVFTransformAgregator< NDimensions >::m_MEstimateConvergenceThreshold, anima::DenseSVFTransformAgregator< NDimensions >::m_NeighborhoodHalfSize, anima::DenseSVFTransformAgregator< NDimensions >::m_NumberOfThreads, anima::DenseSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma, and anima::DenseSVFTransformAgregator< NDimensions >::Update().
~DenseSVFTransformAgregator()
template<unsigned int NDimensions = 3> virtual anima::DenseSVFTransformAgregator< NDimensions >::~DenseSVFTransformAgregator () inline virtual
Definition at line 38 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::Update().
Member Function Documentation
SetDistanceBoundary()
template<unsigned int NDimensions = 3> void anima::DenseSVFTransformAgregator< NDimensions >::SetDistanceBoundary (double num) inline
Definition at line 48 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::m_DistanceBoundary.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetExtrapolationSigma()
template<unsigned int NDimensions = 3> void anima::DenseSVFTransformAgregator< NDimensions >::SetExtrapolationSigma (double sigma) inline
Definition at line 42 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetGeometryInformation()
template<unsigned int NDimensions = 3> template<class TInputImageType > void anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation (const TInputImageType * geomImage) inline
Definition at line 51 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::m_Direction, anima::DenseSVFTransformAgregator< NDimensions >::m_LargestRegion, anima::DenseSVFTransformAgregator< NDimensions >::m_Origin, and anima::DenseSVFTransformAgregator< NDimensions >::m_Spacing.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetMEstimateConvergenceThreshold()
template<unsigned int NDimensions = 3> void anima::DenseSVFTransformAgregator< NDimensions >::SetMEstimateConvergenceThreshold (double num) inline
Definition at line 49 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::m_MEstimateConvergenceThreshold.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetNeighborhoodHalfSize()
template<unsigned int NDimensions = 3> void anima::DenseSVFTransformAgregator< NDimensions >::SetNeighborhoodHalfSize (unsigned int num) inline
Definition at line 47 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::m_NeighborhoodHalfSize.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetNumberOfThreads()
template<unsigned int NDimensions = 3> void anima::DenseSVFTransformAgregator< NDimensions >::SetNumberOfThreads (unsigned int num) inline
Definition at line 45 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::m_NumberOfThreads.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetOutlierRejectionSigma()
template<unsigned int NDimensions = 3> void anima::DenseSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma (double sigma) inline
Definition at line 43 of file animaDenseSVFTransformAgregator.h.
References anima::DenseSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
Update()
template<unsigned int NDimensions> bool anima::DenseSVFTransformAgregator< NDimensions >::Update () virtual
Implements anima::BaseTransformAgregator< NDimensions >.
Definition at line 32 of file animaDenseSVFTransformAgregator.hxx.
References anima::BaseTransformAgregator< NDimensions >::AFFINE, anima::BaseTransformAgregator< NDimensions >::DIRECTIONAL_AFFINE, anima::BaseTransformAgregator< NDimensions >::GetInputOrigin(), anima::BaseTransformAgregator< NDimensions >::GetInputRegions(), anima::BaseTransformAgregator< NDimensions >::GetInputTransform(), anima::BaseTransformAgregator< NDimensions >::GetInputTransforms(), anima::BaseTransformAgregator< NDimensions >::GetInputTransformType(), anima::BaseTransformAgregator< NDimensions >::GetInputWeight(), anima::BaseTransformAgregator< NDimensions >::GetInputWeights(), anima::BaseTransformAgregator< NDimensions >::GetOutputTransformType(), anima::BaseTransformAgregator< NDimensions >::GetVerboseAgregation(), anima::DenseSVFTransformAgregator< NDimensions >::m_Direction, anima::DenseSVFTransformAgregator< NDimensions >::m_DistanceBoundary, anima::DenseSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma, anima::DenseSVFTransformAgregator< NDimensions >::m_LargestRegion, anima::DenseSVFTransformAgregator< NDimensions >::m_MEstimateConvergenceThreshold, anima::DenseSVFTransformAgregator< NDimensions >::m_NumberOfThreads, anima::DenseSVFTransformAgregator< NDimensions >::m_Origin, anima::DenseSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma, anima::DenseSVFTransformAgregator< NDimensions >::m_Spacing, anima::BaseTransformAgregator< NDimensions >::RIGID, anima::MatrixLoggerFilter< TInputScalarType, TOutputScalarType, NDimensions, NDegreesOfFreedom >::SetInput(), anima::BaseTransformAgregator< NDimensions >::SetOutput(), anima::BaseTransformAgregator< NDimensions >::SetUpToDate(), anima::BaseTransformAgregator< NDimensions >::SVF, and anima::BaseTransformAgregator< NDimensions >::TRANSLATION.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator(), and anima::DenseSVFTransformAgregator< NDimensions >::~DenseSVFTransformAgregator().
Member Data Documentation
m_Direction
template<unsigned int NDimensions = 3> VelocityFieldDirectionType anima::DenseSVFTransformAgregator< NDimensions >::m_Direction protected
Definition at line 73 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_DistanceBoundary
template<unsigned int NDimensions = 3> double anima::DenseSVFTransformAgregator< NDimensions >::m_DistanceBoundary protected
Definition at line 67 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator(), anima::DenseSVFTransformAgregator< NDimensions >::SetDistanceBoundary(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_ExtrapolationSigma
template<unsigned int NDimensions = 3> double anima::DenseSVFTransformAgregator< NDimensions >::m_ExtrapolationSigma protected
Definition at line 63 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator(), anima::DenseSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_LargestRegion
template<unsigned int NDimensions = 3> VelocityFieldRegionType anima::DenseSVFTransformAgregator< NDimensions >::m_LargestRegion protected
Definition at line 71 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_MEstimateConvergenceThreshold
template<unsigned int NDimensions = 3> double anima::DenseSVFTransformAgregator< NDimensions >::m_MEstimateConvergenceThreshold protected
Definition at line 68 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator(), anima::DenseSVFTransformAgregator< NDimensions >::SetMEstimateConvergenceThreshold(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_NeighborhoodHalfSize
template<unsigned int NDimensions = 3> unsigned int anima::DenseSVFTransformAgregator< NDimensions >::m_NeighborhoodHalfSize protected
Definition at line 66 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator(), and anima::DenseSVFTransformAgregator< NDimensions >::SetNeighborhoodHalfSize().
m_NumberOfThreads
template<unsigned int NDimensions = 3> unsigned int anima::DenseSVFTransformAgregator< NDimensions >::m_NumberOfThreads protected
Definition at line 75 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator(), anima::DenseSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_Origin
template<unsigned int NDimensions = 3> VelocityFieldPointType anima::DenseSVFTransformAgregator< NDimensions >::m_Origin protected
Definition at line 70 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_OutlierRejectionSigma
template<unsigned int NDimensions = 3> double anima::DenseSVFTransformAgregator< NDimensions >::m_OutlierRejectionSigma protected
Definition at line 64 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::DenseSVFTransformAgregator(), anima::DenseSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
m_Spacing
template<unsigned int NDimensions = 3> VelocityFieldSpacingType anima::DenseSVFTransformAgregator< NDimensions >::m_Spacing protected
Definition at line 72 of file animaDenseSVFTransformAgregator.h.
Referenced by anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
The documentation for this class was generated from the following files:
animaDenseSVFTransformAgregator.h
animaDenseSVFTransformAgregator.hxx