ANIMA: anima::FlipTensorImageFilter< TPixelType, TImageDimension > Class Template Reference
anima::FlipTensorImageFilter< TPixelType, TImageDimension > Class Template Reference
#include <animaFlipTensorImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef itk::VectorImage< TPixelType, TImageDimension > InputImageType
typedef InputImageType::PixelType InputPixelType
typedef InputImageType::Pointer InputPointerType
typedef Superclass::MaskImageType MaskImageType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::VectorImage< TPixelType, TImageDimension > OutputImageType
typedef OutputImageType::PixelType OutputPixelType
typedef OutputImageType::Pointer OutputPointerType
typedef itk::SmartPointer< Self > Pointer
typedef FlipTensorImageFilter Self
typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Types inherited from anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::VectorImage< TPixelType, TImageDimension > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > > Superclass
typedef itk::ImageSource< itk::VectorImage< TPixelType, TImageDimension > >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetFlippedAxis (std::string _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >
static Pointer New ()
Protected Member Functions
FlipTensorImageFilter ()
void GenerateOutputInformation () ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~FlipTensorImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::VectorImage< TPixelType, TImageDimension > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::VectorImage< TPixelType, TImageDimension > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class TPixelType, unsigned int TImageDimension = 3>
class anima::FlipTensorImageFilter< TPixelType, TImageDimension >
Definition at line 10 of file animaFlipTensorImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TPixelType , unsigned int TImageDimension = 3> typedef itk::SmartPointer<const Self> anima::FlipTensorImageFilter< TPixelType, TImageDimension >::ConstPointer
Definition at line 27 of file animaFlipTensorImageFilter.h.
InputImageRegionType
template<class TPixelType , unsigned int TImageDimension = 3> typedef Superclass::InputImageRegionType anima::FlipTensorImageFilter< TPixelType, TImageDimension >::InputImageRegionType
Superclass typedefs.
Definition at line 36 of file animaFlipTensorImageFilter.h.
InputImageType
template<class TPixelType , unsigned int TImageDimension = 3> typedef itk::VectorImage<TPixelType,TImageDimension> anima::FlipTensorImageFilter< TPixelType, TImageDimension >::InputImageType
Definition at line 18 of file animaFlipTensorImageFilter.h.
InputPixelType
template<class TPixelType , unsigned int TImageDimension = 3> typedef InputImageType::PixelType anima::FlipTensorImageFilter< TPixelType, TImageDimension >::InputPixelType
Definition at line 19 of file animaFlipTensorImageFilter.h.
InputPointerType
template<class TPixelType , unsigned int TImageDimension = 3> typedef InputImageType::Pointer anima::FlipTensorImageFilter< TPixelType, TImageDimension >::InputPointerType
Definition at line 40 of file animaFlipTensorImageFilter.h.
MaskImageType
template<class TPixelType , unsigned int TImageDimension = 3> typedef Superclass::MaskImageType anima::FlipTensorImageFilter< TPixelType, TImageDimension >::MaskImageType
Definition at line 38 of file animaFlipTensorImageFilter.h.
OutputImageRegionType
template<class TPixelType , unsigned int TImageDimension = 3> typedef Superclass::OutputImageRegionType anima::FlipTensorImageFilter< TPixelType, TImageDimension >::OutputImageRegionType
Definition at line 37 of file animaFlipTensorImageFilter.h.
OutputImageType
template<class TPixelType , unsigned int TImageDimension = 3> typedef itk::VectorImage<TPixelType,TImageDimension> anima::FlipTensorImageFilter< TPixelType, TImageDimension >::OutputImageType
Definition at line 21 of file animaFlipTensorImageFilter.h.
OutputPixelType
template<class TPixelType , unsigned int TImageDimension = 3> typedef OutputImageType::PixelType anima::FlipTensorImageFilter< TPixelType, TImageDimension >::OutputPixelType
Definition at line 22 of file animaFlipTensorImageFilter.h.
OutputPointerType
template<class TPixelType , unsigned int TImageDimension = 3> typedef OutputImageType::Pointer anima::FlipTensorImageFilter< TPixelType, TImageDimension >::OutputPointerType
Definition at line 41 of file animaFlipTensorImageFilter.h.
Pointer
template<class TPixelType , unsigned int TImageDimension = 3> typedef itk::SmartPointer<Self> anima::FlipTensorImageFilter< TPixelType, TImageDimension >::Pointer
Definition at line 26 of file animaFlipTensorImageFilter.h.
Self
template<class TPixelType , unsigned int TImageDimension = 3> typedef FlipTensorImageFilter anima::FlipTensorImageFilter< TPixelType, TImageDimension >::Self
Standard class typedefs.
Definition at line 16 of file animaFlipTensorImageFilter.h.
Superclass
template<class TPixelType , unsigned int TImageDimension = 3> typedef anima::MaskedImageToImageFilter<InputImageType, OutputImageType> anima::FlipTensorImageFilter< TPixelType, TImageDimension >::Superclass
Definition at line 24 of file animaFlipTensorImageFilter.h.
Constructor & Destructor Documentation
FlipTensorImageFilter()
template<class TPixelType , unsigned int TImageDimension = 3> anima::FlipTensorImageFilter< TPixelType, TImageDimension >::FlipTensorImageFilter () inline protected
Definition at line 46 of file animaFlipTensorImageFilter.h.
~FlipTensorImageFilter()
template<class TPixelType , unsigned int TImageDimension = 3> virtual anima::FlipTensorImageFilter< TPixelType, TImageDimension >::~FlipTensorImageFilter () inline protected virtual
Definition at line 51 of file animaFlipTensorImageFilter.h.
References anima::FlipTensorImageFilter< TPixelType, TImageDimension >::GenerateOutputInformation(), and anima::FlipTensorImageFilter< TPixelType, TImageDimension >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<class TPixelType , unsigned int TImageDimension = 3> virtual::itk::LightObject::Pointer anima::FlipTensorImageFilter< TPixelType, TImageDimension >::CreateAnother (void) const
GenerateOutputInformation()
template<class TPixelType , unsigned int TImageDimension> void anima::FlipTensorImageFilter< TPixelType, TImageDimension >::GenerateOutputInformation () protected
Definition at line 12 of file animaFlipTensorImageFilter.hxx.
References anima::FlipTensorImageFilter< TPixelType, TImageDimension >::ThreadedGenerateData().
Referenced by anima::FlipTensorImageFilter< TPixelType, TImageDimension >::~FlipTensorImageFilter().
GetNameOfClass()
template<class TPixelType , unsigned int TImageDimension = 3> virtual const char* anima::FlipTensorImageFilter< TPixelType, TImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >.
New()
template<class TPixelType , unsigned int TImageDimension = 3> static Pointer anima::FlipTensorImageFilter< TPixelType, TImageDimension >::New () static
Method for creation through the object factory.
SetFlippedAxis()
template<class TPixelType , unsigned int TImageDimension = 3> virtual void anima::FlipTensorImageFilter< TPixelType, TImageDimension >::SetFlippedAxis (std::string _arg) virtual
ThreadedGenerateData()
template<class TPixelType , unsigned int TImageDimension> void anima::FlipTensorImageFilter< TPixelType, TImageDimension >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 26 of file animaFlipTensorImageFilter.hxx.
Referenced by anima::FlipTensorImageFilter< TPixelType, TImageDimension >::GenerateOutputInformation(), and anima::FlipTensorImageFilter< TPixelType, TImageDimension >::~FlipTensorImageFilter().
The documentation for this class was generated from the following files:
animaFlipTensorImageFilter.h
animaFlipTensorImageFilter.hxx