ANIMA: anima::BoundedLevenbergMarquardtOptimizer Class Reference
anima::BoundedLevenbergMarquardtOptimizer Class Reference
Levenberg-Marquardt optimizer with lower and upper bounds on parameters Implementation of the original algorithmm, very well described in K. Madsen, H.B. Nielsen and O. Tingleff. Methods for non-linear least squares problems. 2004 http://www2.imm.dtu.dk/pubdb/views/edoc_download.php/3215/pdf/imm3215.pdf Bounded version by projection as suggested by Kanzow et al. C. Kanzow, N. Yamashita and M. Fukushima. Levenberg-Marquardt methods with strong local convergence properties for solving nonlinear equations with convex constraints. Journal of computational and applied mathematics. 172:375-397, 2004.
#include <animaBoundedLevenbergMarquardtOptimizer.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::CostFunctionType CostFunctionType
typedef Superclass::MeasureType MeasureType
typedef itk::SmartPointer< Self > Pointer
typedef BoundedLevenbergMarquardtOptimizer Self
typedef itk::MultipleValuedNonLinearOptimizer Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetCurrentValue ()
virtual const char * GetNameOfClass () const
virtual void SetGradientTolerance (double _arg)
virtual void SetLambdaParameter (double _arg)
virtual void SetLowerBounds (ParametersType _arg)
virtual void SetNumberOfIterations (unsigned int _arg)
virtual void SetUpperBounds (ParametersType _arg)
virtual void SetValueTolerance (double _arg)
void StartOptimization () ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Protected Member Functions
BoundedLevenbergMarquardtOptimizer ()
bool CheckConditions (unsigned int numIterations, ParametersType &lastTestedParams, ParametersType &newParams, DerivativeType &newDerivative)
double EvaluateCostFunctionAtParameters (ParametersType &parameters, ParametersType &scaledParameters, MeasureType &residualValues)
void GetDerivativeSquared (DerivativeType &derivativeMatrix, DerivativeType &derivativeSquared)
virtual ~BoundedLevenbergMarquardtOptimizer () ITK_OVERRIDE
Detailed Description
Levenberg-Marquardt optimizer with lower and upper bounds on parameters Implementation of the original algorithmm, very well described in K. Madsen, H.B. Nielsen and O. Tingleff. Methods for non-linear least squares problems. 2004 http://www2.imm.dtu.dk/pubdb/views/edoc_download.php/3215/pdf/imm3215.pdf Bounded version by projection as suggested by Kanzow et al. C. Kanzow, N. Yamashita and M. Fukushima. Levenberg-Marquardt methods with strong local convergence properties for solving nonlinear equations with convex constraints. Journal of computational and applied mathematics. 172:375-397, 2004.
Definition at line 22 of file animaBoundedLevenbergMarquardtOptimizer.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::BoundedLevenbergMarquardtOptimizer::ConstPointer
Definition at line 30 of file animaBoundedLevenbergMarquardtOptimizer.h.
CostFunctionType
typedef Superclass::CostFunctionType anima::BoundedLevenbergMarquardtOptimizer::CostFunctionType
Definition at line 35 of file animaBoundedLevenbergMarquardtOptimizer.h.
MeasureType
typedef Superclass::MeasureType anima::BoundedLevenbergMarquardtOptimizer::MeasureType
Definition at line 36 of file animaBoundedLevenbergMarquardtOptimizer.h.
Pointer
typedef itk::SmartPointer<Self> anima::BoundedLevenbergMarquardtOptimizer::Pointer
Definition at line 29 of file animaBoundedLevenbergMarquardtOptimizer.h.
Self
typedef BoundedLevenbergMarquardtOptimizer anima::BoundedLevenbergMarquardtOptimizer::Self
Standard class typedefs.
Definition at line 27 of file animaBoundedLevenbergMarquardtOptimizer.h.
Superclass
typedef itk::MultipleValuedNonLinearOptimizer anima::BoundedLevenbergMarquardtOptimizer::Superclass
Definition at line 28 of file animaBoundedLevenbergMarquardtOptimizer.h.
Constructor & Destructor Documentation
BoundedLevenbergMarquardtOptimizer()
anima::BoundedLevenbergMarquardtOptimizer::BoundedLevenbergMarquardtOptimizer () inline protected
Definition at line 55 of file animaBoundedLevenbergMarquardtOptimizer.h.
~BoundedLevenbergMarquardtOptimizer()
virtual anima::BoundedLevenbergMarquardtOptimizer::~BoundedLevenbergMarquardtOptimizer () inline protected virtual
Definition at line 65 of file animaBoundedLevenbergMarquardtOptimizer.h.
Member Function Documentation
CheckConditions()
bool anima::BoundedLevenbergMarquardtOptimizer::CheckConditions (unsigned int numIterations, ParametersType & lastTestedParams, ParametersType & newParams, DerivativeType & newDerivative) protected
Definition at line 242 of file animaBoundedLevenbergMarquardtOptimizer.cxx.
Referenced by StartOptimization().
CreateAnother()
virtual::itk::LightObject::Pointer anima::BoundedLevenbergMarquardtOptimizer::CreateAnother (void) const
EvaluateCostFunctionAtParameters()
double anima::BoundedLevenbergMarquardtOptimizer::EvaluateCostFunctionAtParameters (ParametersType & parameters, ParametersType & scaledParameters, MeasureType & residualValues) protected
Definition at line 220 of file animaBoundedLevenbergMarquardtOptimizer.cxx.
Referenced by StartOptimization().
GetCurrentValue()
virtual double anima::BoundedLevenbergMarquardtOptimizer::GetCurrentValue () virtual
GetDerivativeSquared()
void anima::BoundedLevenbergMarquardtOptimizer::GetDerivativeSquared (DerivativeType & derivativeMatrix, DerivativeType & derivativeSquared) protected
Definition at line 200 of file animaBoundedLevenbergMarquardtOptimizer.cxx.
Referenced by StartOptimization().
GetNameOfClass()
virtual const char* anima::BoundedLevenbergMarquardtOptimizer::GetNameOfClass () const virtual
Run-time type information (and related methods).
New()
static Pointer anima::BoundedLevenbergMarquardtOptimizer::New () static
Method for creation through the object factory.
SetGradientTolerance()
virtual void anima::BoundedLevenbergMarquardtOptimizer::SetGradientTolerance (double _arg) virtual
SetLambdaParameter()
virtual void anima::BoundedLevenbergMarquardtOptimizer::SetLambdaParameter (double _arg) virtual
SetLowerBounds()
virtual void anima::BoundedLevenbergMarquardtOptimizer::SetLowerBounds (ParametersType _arg) virtual
SetNumberOfIterations()
virtual void anima::BoundedLevenbergMarquardtOptimizer::SetNumberOfIterations (unsigned int _arg) virtual
SetUpperBounds()
virtual void anima::BoundedLevenbergMarquardtOptimizer::SetUpperBounds (ParametersType _arg) virtual
SetValueTolerance()
virtual void anima::BoundedLevenbergMarquardtOptimizer::SetValueTolerance (double _arg) virtual
StartOptimization()
void anima::BoundedLevenbergMarquardtOptimizer::StartOptimization ()
Start optimization
Definition at line 9 of file animaBoundedLevenbergMarquardtOptimizer.cxx.
References CheckConditions(), EvaluateCostFunctionAtParameters(), GetDerivativeSquared(), anima::CholeskyDecomposition::PerformDecomposition(), anima::CholeskyDecomposition::SetInputMatrix(), and anima::CholeskyDecomposition::SolveLinearSystem().
The documentation for this class was generated from the following files:
animaBoundedLevenbergMarquardtOptimizer.h
animaBoundedLevenbergMarquardtOptimizer.cxx