ANIMA: anima::LowMemoryLocalPatchCovarianceDistanceBridge Class Reference
anima::LowMemoryLocalPatchCovarianceDistanceBridge Class Reference
#include <animaLowMemLocalPatchCovarianceDistanceBridge.h>
Public Types
typedef anima::ImageDataSplitter< InputImageType > ImageSplitterType
typedef LocalPatchCovarianceDistanceImageFilter< double >::InputImageType InputImageType
typedef anima::LocalPatchCovarianceDistanceImageFilter< double > MainFilterType
typedef itk::Image< unsigned char, 3 > MaskImageType
typedef LocalPatchCovarianceDistanceImageFilter< double >::OutputImageRegionType OutputImageRegionType
typedef LocalPatchCovarianceDistanceImageFilter< double >::OutputImageType OutputImageType
Public Member Functions
void BuildAndWrite (OutputImageType *tmpIm, std::string resName, OutputImageType::RegionType finalROI)
std::string GetNameOfClass ()
LowMemoryLocalPatchCovarianceDistanceBridge ()
void SetComputationMask (std::string &cMask)
void SetDatabaseNames (std::string &fileList)
void SetNbSplits (unsigned int nbSplits)
void SetNumberOfThreads (unsigned int nbT)
void SetOutputMeanName (std::string &pref)
void SetOutputStdName (std::string &pref)
void SetPatchHalfSize (unsigned int patchHalf)
void Update (int specificSplitToDo=-1, bool genOutputDescriptionData=false)
~LowMemoryLocalPatchCovarianceDistanceBridge ()
Detailed Description
Definition at line 9 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
Member Typedef Documentation
ImageSplitterType
typedef anima::ImageDataSplitter< InputImageType > anima::LowMemoryLocalPatchCovarianceDistanceBridge::ImageSplitterType
Definition at line 16 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
InputImageType
typedef LocalPatchCovarianceDistanceImageFilter<double>::InputImageType anima::LowMemoryLocalPatchCovarianceDistanceBridge::InputImageType
Definition at line 12 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
MainFilterType
typedef anima::LocalPatchCovarianceDistanceImageFilter<double> anima::LowMemoryLocalPatchCovarianceDistanceBridge::MainFilterType
Definition at line 17 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
MaskImageType
typedef itk::Image<unsigned char,3> anima::LowMemoryLocalPatchCovarianceDistanceBridge::MaskImageType
Definition at line 18 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
OutputImageRegionType
typedef LocalPatchCovarianceDistanceImageFilter<double>::OutputImageRegionType anima::LowMemoryLocalPatchCovarianceDistanceBridge::OutputImageRegionType
Definition at line 14 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
OutputImageType
typedef LocalPatchCovarianceDistanceImageFilter<double>::OutputImageType anima::LowMemoryLocalPatchCovarianceDistanceBridge::OutputImageType
Definition at line 13 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
Constructor & Destructor Documentation
LowMemoryLocalPatchCovarianceDistanceBridge()
anima::LowMemoryLocalPatchCovarianceDistanceBridge::LowMemoryLocalPatchCovarianceDistanceBridge ()
Definition at line 8 of file animaLowMemLocalPatchCovarianceDistanceBridge.cxx.
~LowMemoryLocalPatchCovarianceDistanceBridge()
anima::LowMemoryLocalPatchCovarianceDistanceBridge::~LowMemoryLocalPatchCovarianceDistanceBridge ()
Definition at line 19 of file animaLowMemLocalPatchCovarianceDistanceBridge.cxx.
Member Function Documentation
BuildAndWrite()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::BuildAndWrite (OutputImageType * tmpIm, std::string resName, OutputImageType::RegionType finalROI)
Definition at line 172 of file animaLowMemLocalPatchCovarianceDistanceBridge.cxx.
Referenced by SetPatchHalfSize(), and Update().
GetNameOfClass()
std::string anima::LowMemoryLocalPatchCovarianceDistanceBridge::GetNameOfClass () inline
Definition at line 23 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
References SetComputationMask().
SetComputationMask()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetComputationMask (std::string & cMask)
Definition at line 25 of file animaLowMemLocalPatchCovarianceDistanceBridge.cxx.
References anima::ImageDataSplitter< TInputImage >::SetComputationMask().
Referenced by GetNameOfClass(), and main().
SetDatabaseNames()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetDatabaseNames (std::string & fileList) inline
Definition at line 27 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetFileNames().
SetNbSplits()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetNbSplits (unsigned int nbSplits) inline
Definition at line 35 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
SetNumberOfThreads()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetNumberOfThreads (unsigned int nbT) inline
Definition at line 36 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
SetOutputMeanName()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetOutputMeanName (std::string & pref) inline
Definition at line 32 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
SetOutputStdName()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetOutputStdName (std::string & pref) inline
Definition at line 33 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
SetPatchHalfSize()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::SetPatchHalfSize (unsigned int patchHalf) inline
Definition at line 38 of file animaLowMemLocalPatchCovarianceDistanceBridge.h.
References BuildAndWrite(), and Update().
Update()
void anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update (int specificSplitToDo = -1, bool genOutputDescriptionData = false)
Definition at line 36 of file animaLowMemLocalPatchCovarianceDistanceBridge.cxx.
References BuildAndWrite(), anima::ImageDataSplitter< TInputImage >::EmptyMask(), anima::ImageDataSplitter< TInputImage >::GetBlockRegionInsideMargin(), anima::ImageDataSplitter< TInputImage >::GetNbImages(), anima::ImageDataSplitter< TInputImage >::GetOutput(), anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin(), anima::ImageDataSplitter< TInputImage >::GetSpecificBlockRegion(), anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::New(), anima::ImageDataSplitter< TInputImage >::SetBlockIndex(), anima::ImageDataSplitter< TInputImage >::SetBlockMargin(), anima::ImageDataSplitter< TInputImage >::SetNumberOfBlocks(), and anima::ImageDataSplitter< TInputImage >::Update().
Referenced by SetPatchHalfSize().
The documentation for this class was generated from the following files:
animaLowMemLocalPatchCovarianceDistanceBridge.h
animaLowMemLocalPatchCovarianceDistanceBridge.cxx