ANIMA: anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType > Class Template Reference
anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType > Class Template Reference
#include <animaNLMeansPatientToGroupComparisonImageFilter.h>
Classes
struct SampleIdentifier
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef vnl_matrix< double > CovarianceType
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::Pointer InputImagePointer
typedef itk::VectorImage< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef NLMeansPatientToGroupComparisonImageFilter< PixelScalarType > Self
typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > Superclass
typedef InputImageType::PixelType VectorType
Public Types inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::VectorImage< PixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< PixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
void AddDatabaseInput (InputImageType *tmpIm)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetBetaParameter (double _arg)
virtual void SetDatabaseCovarianceDistanceAverage (OutputImagePointer _arg)
virtual void SetDatabaseCovarianceDistanceStd (OutputImagePointer _arg)
virtual void SetDatabaseMeanDistanceAverage (OutputImagePointer _arg)
virtual void SetDatabaseMeanDistanceStd (OutputImagePointer _arg)
virtual void SetMeanThreshold (double _arg)
virtual void SetPatchHalfSize (unsigned int _arg)
virtual void SetSearchNeighborhood (unsigned int _arg)
virtual void SetSearchStepSize (unsigned int _arg)
virtual void SetVarianceThreshold (double _arg)
virtual void SetWeightThreshold (double _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
NLMeansPatientToGroupComparisonImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~NLMeansPatientToGroupComparisonImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class PixelScalarType>
class anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >
Definition at line 14 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class PixelScalarType> typedef itk::SmartPointer<const Self> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ConstPointer
Definition at line 21 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
CovarianceType
template<class PixelScalarType> typedef vnl_matrix<double> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::CovarianceType
Definition at line 35 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
InputImageIndexType
template<class PixelScalarType> typedef InputImageType::IndexType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::InputImageIndexType
Definition at line 38 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
InputImagePointer
template<class PixelScalarType> typedef InputImageType::Pointer anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::InputImagePointer
Definition at line 37 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
InputImageType
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType, 3> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::InputImageType
Image typedef support
Definition at line 30 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
MaskImageType
template<class PixelScalarType> typedef Superclass::MaskImageType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::MaskImageType
Definition at line 44 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
OutputImagePointer
template<class PixelScalarType> typedef OutputImageType::Pointer anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 39 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
OutputImageRegionType
template<class PixelScalarType> typedef Superclass::OutputImageRegionType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 43 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
OutputImageType
template<class PixelScalarType> typedef itk::Image<PixelScalarType, 3> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::OutputImageType
Definition at line 31 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Pointer
template<class PixelScalarType> typedef itk::SmartPointer<Self> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::Pointer
Definition at line 20 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Self
template<class PixelScalarType> typedef NLMeansPatientToGroupComparisonImageFilter<PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 19 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Superclass
template<class PixelScalarType> typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::Superclass
Superclass typedefs.
Definition at line 42 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
VectorType
template<class PixelScalarType> typedef InputImageType::PixelType anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::VectorType
Definition at line 33 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
Constructor & Destructor Documentation
NLMeansPatientToGroupComparisonImageFilter()
template<class PixelScalarType> anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::NLMeansPatientToGroupComparisonImageFilter () inline protected
Definition at line 72 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
~NLMeansPatientToGroupComparisonImageFilter()
template<class PixelScalarType> virtual anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::~NLMeansPatientToGroupComparisonImageFilter () inline protected virtual
Definition at line 97 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
References anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
Member Function Documentation
AddDatabaseInput()
template<class PixelScalarType> void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::AddDatabaseInput (InputImageType * tmpIm) inline
Definition at line 53 of file animaNLMeansPatientToGroupComparisonImageFilter.h.
BeforeThreadedGenerateData()
template<class PixelScalarType > void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
Definition at line 19 of file animaNLMeansPatientToGroupComparisonImageFilter.hxx.
References anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
Referenced by anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::~NLMeansPatientToGroupComparisonImageFilter().
CreateAnother()
template<class PixelScalarType> virtual::itk::LightObject::Pointer anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::CreateAnother (void) const
GetNameOfClass()
template<class PixelScalarType> virtual const char* anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
New()
template<class PixelScalarType> static Pointer anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
Referenced by anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update().
SetBetaParameter()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetBetaParameter (double _arg) virtual
SetDatabaseCovarianceDistanceAverage()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetDatabaseCovarianceDistanceAverage (OutputImagePointer _arg) virtual
SetDatabaseCovarianceDistanceStd()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetDatabaseCovarianceDistanceStd (OutputImagePointer _arg) virtual
SetDatabaseMeanDistanceAverage()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetDatabaseMeanDistanceAverage (OutputImagePointer _arg) virtual
SetDatabaseMeanDistanceStd()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetDatabaseMeanDistanceStd (OutputImagePointer _arg) virtual
SetMeanThreshold()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetMeanThreshold (double _arg) virtual
SetPatchHalfSize()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetPatchHalfSize (unsigned int _arg) virtual
SetSearchNeighborhood()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetSearchNeighborhood (unsigned int _arg) virtual
SetSearchStepSize()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetSearchStepSize (unsigned int _arg) virtual
SetVarianceThreshold()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetVarianceThreshold (double _arg) virtual
SetWeightThreshold()
template<class PixelScalarType> virtual void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::SetWeightThreshold (double _arg) virtual
ThreadedGenerateData()
template<class PixelScalarType > void anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 33 of file animaNLMeansPatientToGroupComparisonImageFilter.hxx.
References anima::NonLocalPatchBaseSearcher< ImageType >::SetPatchHalfSize().
Referenced by anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::~NLMeansPatientToGroupComparisonImageFilter().
The documentation for this class was generated from the following files:
animaNLMeansPatientToGroupComparisonImageFilter.h
animaNLMeansPatientToGroupComparisonImageFilter.hxx