ANIMA: anima::B1T2RelaxometryDistributionCostFunction Class Reference
anima::B1T2RelaxometryDistributionCostFunction Class Reference
Cost function for estimating B1 from T2 relaxometry acquisition, following a multi-T2 EPG decay model.
#include <animaB1T2RelaxometryDistributionCostFunction.h>
Public Types
typedef std::vector< std::complex< double > > ComplexVectorType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef std::vector< ComplexVectorType > MatrixType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef B1T2RelaxometryDistributionCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetB1OnExcitationAngle (bool _arg)
void SetDistributionSamplesT2Correspondences (std::vector< std::vector< unsigned int > > &values)
virtual void SetEchoSpacing (double _arg)
virtual void SetExcitationFlipAngle (double _arg)
void SetLowerT2Bound (double value)
virtual void SetM0Value (double _arg)
virtual void SetT1Value (double _arg)
void SetT2DistributionSamples (std::vector< std::vector< double > > &values)
void SetT2FlipAngles (std::vector< double > &flipAngles)
void SetT2IntegrationStep (double value)
void SetT2RelaxometrySignals (ParametersType &relaxoSignals)
void SetT2Weights (ParametersType &weights)
void SetT2WorkingValues (std::vector< double > &values)
void SetUpperT2Bound (double value)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
B1T2RelaxometryDistributionCostFunction ()
virtual ~B1T2RelaxometryDistributionCostFunction ()
Detailed Description
Cost function for estimating B1 from T2 relaxometry acquisition, following a multi-T2 EPG decay model.
Definition at line 15 of file animaB1T2RelaxometryDistributionCostFunction.h.
Member Typedef Documentation
ComplexVectorType
typedef std::vector< std::complex <double> > anima::B1T2RelaxometryDistributionCostFunction::ComplexVectorType
Definition at line 33 of file animaB1T2RelaxometryDistributionCostFunction.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::B1T2RelaxometryDistributionCostFunction::ConstPointer
Definition at line 23 of file animaB1T2RelaxometryDistributionCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::B1T2RelaxometryDistributionCostFunction::DerivativeType
Definition at line 31 of file animaB1T2RelaxometryDistributionCostFunction.h.
MatrixType
typedef std::vector<ComplexVectorType> anima::B1T2RelaxometryDistributionCostFunction::MatrixType
Definition at line 34 of file animaB1T2RelaxometryDistributionCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::B1T2RelaxometryDistributionCostFunction::MeasureType
Definition at line 30 of file animaB1T2RelaxometryDistributionCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::B1T2RelaxometryDistributionCostFunction::ParametersType
Definition at line 32 of file animaB1T2RelaxometryDistributionCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::B1T2RelaxometryDistributionCostFunction::Pointer
Definition at line 22 of file animaB1T2RelaxometryDistributionCostFunction.h.
Self
typedef B1T2RelaxometryDistributionCostFunction anima::B1T2RelaxometryDistributionCostFunction::Self
Standard class typedefs.
Definition at line 20 of file animaB1T2RelaxometryDistributionCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::B1T2RelaxometryDistributionCostFunction::Superclass
Definition at line 21 of file animaB1T2RelaxometryDistributionCostFunction.h.
Constructor & Destructor Documentation
B1T2RelaxometryDistributionCostFunction()
anima::B1T2RelaxometryDistributionCostFunction::B1T2RelaxometryDistributionCostFunction () inline protected
Definition at line 66 of file animaB1T2RelaxometryDistributionCostFunction.h.
~B1T2RelaxometryDistributionCostFunction()
virtual anima::B1T2RelaxometryDistributionCostFunction::~B1T2RelaxometryDistributionCostFunction () inline protected virtual
Definition at line 80 of file animaB1T2RelaxometryDistributionCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::B1T2RelaxometryDistributionCostFunction::CreateAnother (void) const
GetDerivative()
virtual void anima::B1T2RelaxometryDistributionCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const inline virtual
Definition at line 37 of file animaB1T2RelaxometryDistributionCostFunction.h.
GetNameOfClass()
virtual const char* anima::B1T2RelaxometryDistributionCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::B1T2RelaxometryDistributionCostFunction::GetNumberOfParameters () const inline
Definition at line 60 of file animaB1T2RelaxometryDistributionCostFunction.h.
GetValue()
B1T2RelaxometryDistributionCostFunction::MeasureType anima::B1T2RelaxometryDistributionCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 7 of file animaB1T2RelaxometryDistributionCostFunction.cxx.
References anima::EPGSignalSimulator::GetValue(), anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), and anima::EPGSignalSimulator::SetNumberOfEchoes().
New()
static Pointer anima::B1T2RelaxometryDistributionCostFunction::New () static
SetB1OnExcitationAngle()
virtual void anima::B1T2RelaxometryDistributionCostFunction::SetB1OnExcitationAngle (bool _arg) virtual
SetDistributionSamplesT2Correspondences()
void anima::B1T2RelaxometryDistributionCostFunction::SetDistributionSamplesT2Correspondences (std::vector< std::vector< unsigned int > > & values) inline
Definition at line 58 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetEchoSpacing()
virtual void anima::B1T2RelaxometryDistributionCostFunction::SetEchoSpacing (double _arg) virtual
SetExcitationFlipAngle()
virtual void anima::B1T2RelaxometryDistributionCostFunction::SetExcitationFlipAngle (double _arg) virtual
SetLowerT2Bound()
void anima::B1T2RelaxometryDistributionCostFunction::SetLowerT2Bound (double value) inline
Definition at line 49 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetM0Value()
virtual void anima::B1T2RelaxometryDistributionCostFunction::SetM0Value (double _arg) virtual
SetT1Value()
virtual void anima::B1T2RelaxometryDistributionCostFunction::SetT1Value (double _arg) virtual
SetT2DistributionSamples()
void anima::B1T2RelaxometryDistributionCostFunction::SetT2DistributionSamples (std::vector< std::vector< double > > & values) inline
Definition at line 48 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetT2FlipAngles()
void anima::B1T2RelaxometryDistributionCostFunction::SetT2FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 43 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetT2IntegrationStep()
void anima::B1T2RelaxometryDistributionCostFunction::SetT2IntegrationStep (double value) inline
Definition at line 51 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetT2RelaxometrySignals()
void anima::B1T2RelaxometryDistributionCostFunction::SetT2RelaxometrySignals (ParametersType & relaxoSignals) inline
Definition at line 42 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetT2Weights()
void anima::B1T2RelaxometryDistributionCostFunction::SetT2Weights (ParametersType & weights) inline
Definition at line 53 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetT2WorkingValues()
void anima::B1T2RelaxometryDistributionCostFunction::SetT2WorkingValues (std::vector< double > & values) inline
Definition at line 57 of file animaB1T2RelaxometryDistributionCostFunction.h.
SetUpperT2Bound()
void anima::B1T2RelaxometryDistributionCostFunction::SetUpperT2Bound (double value) inline
Definition at line 50 of file animaB1T2RelaxometryDistributionCostFunction.h.
The documentation for this class was generated from the following files:
animaB1T2RelaxometryDistributionCostFunction.h
animaB1T2RelaxometryDistributionCostFunction.cxx