ANIMA: anima::MultiTensorSmoothingCostFunction Class Reference
anima::MultiTensorSmoothingCostFunction Class Reference
#include <animaMultiTensorSmoothingCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef anima::MultiCompartmentModel MCModelType
typedef MCModelType::Pointer MCMPointer
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef MultiTensorSmoothingCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
typedef anima::BaseCompartment::Matrix3DType TensorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetLowPassGaussianSigma (double _arg)
void SetMovingModels (const std::vector< MCMPointer > &movingModels)
void SetReferenceModels (const std::vector< MCMPointer > &refModels)
virtual void SetTensorsScale (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void ComputeMatrixTraces (const TensorType &matrix, double &matrixTrace, double &squaredMatrixTrace) const
MultiTensorSmoothingCostFunction ()
void UpdateDeterminants () const
virtual ~MultiTensorSmoothingCostFunction ()
Detailed Description
Definition at line 10 of file animaMultiTensorSmoothingCostFunction.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::MultiTensorSmoothingCostFunction::ConstPointer
Definition at line 17 of file animaMultiTensorSmoothingCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::MultiTensorSmoothingCostFunction::DerivativeType
Definition at line 26 of file animaMultiTensorSmoothingCostFunction.h.
MCModelType
typedef anima::MultiCompartmentModel anima::MultiTensorSmoothingCostFunction::MCModelType
Definition at line 28 of file animaMultiTensorSmoothingCostFunction.h.
MCMPointer
typedef MCModelType::Pointer anima::MultiTensorSmoothingCostFunction::MCMPointer
Definition at line 29 of file animaMultiTensorSmoothingCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::MultiTensorSmoothingCostFunction::MeasureType
Definition at line 24 of file animaMultiTensorSmoothingCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::MultiTensorSmoothingCostFunction::ParametersType
Definition at line 25 of file animaMultiTensorSmoothingCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::MultiTensorSmoothingCostFunction::Pointer
Definition at line 16 of file animaMultiTensorSmoothingCostFunction.h.
Self
typedef MultiTensorSmoothingCostFunction anima::MultiTensorSmoothingCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaMultiTensorSmoothingCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::MultiTensorSmoothingCostFunction::Superclass
Definition at line 15 of file animaMultiTensorSmoothingCostFunction.h.
TensorType
typedef anima::BaseCompartment::Matrix3DType anima::MultiTensorSmoothingCostFunction::TensorType
Definition at line 30 of file animaMultiTensorSmoothingCostFunction.h.
Constructor & Destructor Documentation
MultiTensorSmoothingCostFunction()
anima::MultiTensorSmoothingCostFunction::MultiTensorSmoothingCostFunction () inline protected
Definition at line 44 of file animaMultiTensorSmoothingCostFunction.h.
~MultiTensorSmoothingCostFunction()
virtual anima::MultiTensorSmoothingCostFunction::~MultiTensorSmoothingCostFunction () inline protected virtual
Definition at line 55 of file animaMultiTensorSmoothingCostFunction.h.
Member Function Documentation
ComputeMatrixTraces()
void anima::MultiTensorSmoothingCostFunction::ComputeMatrixTraces (const TensorType & matrix, double & matrixTrace, double & squaredMatrixTrace) const protected
Definition at line 322 of file animaMultiTensorSmoothingCostFunction.cxx.
References GetDerivative().
Referenced by UpdateDeterminants().
CreateAnother()
virtual::itk::LightObject::Pointer anima::MultiTensorSmoothingCostFunction::CreateAnother (void) const
GetDerivative()
void anima::MultiTensorSmoothingCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 343 of file animaMultiTensorSmoothingCostFunction.cxx.
Referenced by ComputeMatrixTraces().
GetNameOfClass()
virtual const char* anima::MultiTensorSmoothingCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::MultiTensorSmoothingCostFunction::GetNumberOfParameters (void) const inline
Definition at line 41 of file animaMultiTensorSmoothingCostFunction.h.
GetValue()
MultiTensorSmoothingCostFunction::MeasureType anima::MultiTensorSmoothingCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 86 of file animaMultiTensorSmoothingCostFunction.cxx.
References UpdateDeterminants().
Referenced by SetMovingModels().
New()
static Pointer anima::MultiTensorSmoothingCostFunction::New () static
SetLowPassGaussianSigma()
virtual void anima::MultiTensorSmoothingCostFunction::SetLowPassGaussianSigma (double _arg) virtual
SetMovingModels()
void anima::MultiTensorSmoothingCostFunction::SetMovingModels (const std::vector< MCMPointer > & movingModels)
Definition at line 50 of file animaMultiTensorSmoothingCostFunction.cxx.
References GetValue().
Referenced by SetReferenceModels().
SetReferenceModels()
void anima::MultiTensorSmoothingCostFunction::SetReferenceModels (const std::vector< MCMPointer > & refModels)
Definition at line 9 of file animaMultiTensorSmoothingCostFunction.cxx.
References SetMovingModels().
SetTensorsScale()
virtual void anima::MultiTensorSmoothingCostFunction::SetTensorsScale (double _arg) virtual
UpdateDeterminants()
void anima::MultiTensorSmoothingCostFunction::UpdateDeterminants () const protected
Definition at line 205 of file animaMultiTensorSmoothingCostFunction.cxx.
References ComputeMatrixTraces().
Referenced by GetValue().
The documentation for this class was generated from the following files:
animaMultiTensorSmoothingCostFunction.h
animaMultiTensorSmoothingCostFunction.cxx