ANIMA: anima::MultiCompartmentModelCreator Class Reference
anima::MultiCompartmentModelCreator Class Reference
Really this class is some simplified factory that creates the MCM that it knows.
#include <animaMultiCompartmentModelCreator.h>
Public Types
typedef BaseCompartmentType::Pointer BaseCompartmentPointer
typedef anima::BaseCompartment BaseCompartmentType
typedef anima::DiffusionModelCompartmentType CompartmentType
typedef MCMType::Pointer MCMPointer
typedef anima::MultiCompartmentModel MCMType
Public Member Functions
double GetAxialDiffusivity ()
double GetExtraAxonalFraction ()
MCMPointer GetNewMultiCompartmentModel ()
double GetOrientationConcentration ()
double GetRadialDiffusivity1 ()
double GetRadialDiffusivity2 ()
bool GetUseCommonConcentrations ()
bool GetUseCommonDiffusivities ()
bool GetUseCommonExtraAxonalFractions ()
bool GetUseConstrainedDiffusivity ()
bool GetUseConstrainedExtraAxonalFraction ()
bool GetUseConstrainedOrientationConcentration ()
MultiCompartmentModelCreator ()
void SetAxialDiffusivityValue (double arg)
void SetCompartmentType (CompartmentType arg)
void SetFreeWaterDiffusivityValue (double arg)
void SetIRWDiffusivityValue (double arg)
void SetModelWithFreeWaterComponent (bool arg)
void SetModelWithRestrictedWaterComponent (bool arg)
void SetModelWithStaniszComponent (bool arg)
void SetModelWithStationaryWaterComponent (bool arg)
void SetNumberOfCompartments (unsigned int num)
void SetRadialDiffusivity1Value (double arg)
void SetRadialDiffusivity2Value (double arg)
void SetStaniszDiffusivityValue (double arg)
void SetUseCommonConcentrations (bool arg)
void SetUseCommonDiffusivities (bool arg)
void SetUseCommonExtraAxonalFractions (bool arg)
void SetUseConstrainedDiffusivity (bool arg)
void SetUseConstrainedExtraAxonalFraction (bool arg)
void SetUseConstrainedFreeWaterDiffusivity (bool arg)
void SetUseConstrainedIRWDiffusivity (bool arg)
void SetUseConstrainedOrientationConcentration (bool arg)
void SetUseConstrainedStaniszDiffusivity (bool arg)
void SetUseConstrainedStaniszRadius (bool arg)
void SetVariableProjectionEstimationMode (bool arg)
virtual ~MultiCompartmentModelCreator ()
Detailed Description
Really this class is some simplified factory that creates the MCM that it knows.
Definition at line 12 of file animaMultiCompartmentModelCreator.h.
Member Typedef Documentation
BaseCompartmentPointer
typedef BaseCompartmentType::Pointer anima::MultiCompartmentModelCreator::BaseCompartmentPointer
Definition at line 22 of file animaMultiCompartmentModelCreator.h.
BaseCompartmentType
typedef anima::BaseCompartment anima::MultiCompartmentModelCreator::BaseCompartmentType
Definition at line 21 of file animaMultiCompartmentModelCreator.h.
CompartmentType
typedef anima::DiffusionModelCompartmentType anima::MultiCompartmentModelCreator::CompartmentType
Definition at line 23 of file animaMultiCompartmentModelCreator.h.
MCMPointer
typedef MCMType::Pointer anima::MultiCompartmentModelCreator::MCMPointer
Definition at line 19 of file animaMultiCompartmentModelCreator.h.
MCMType
typedef anima::MultiCompartmentModel anima::MultiCompartmentModelCreator::MCMType
Definition at line 18 of file animaMultiCompartmentModelCreator.h.
Constructor & Destructor Documentation
MultiCompartmentModelCreator()
anima::MultiCompartmentModelCreator::MultiCompartmentModelCreator ()
Definition at line 15 of file animaMultiCompartmentModelCreator.cxx.
References anima::Tensor.
~MultiCompartmentModelCreator()
virtual anima::MultiCompartmentModelCreator::~MultiCompartmentModelCreator () inline virtual
Definition at line 16 of file animaMultiCompartmentModelCreator.h.
Member Function Documentation
GetAxialDiffusivity()
double anima::MultiCompartmentModelCreator::GetAxialDiffusivity () inline
Definition at line 63 of file animaMultiCompartmentModelCreator.h.
GetExtraAxonalFraction()
double anima::MultiCompartmentModelCreator::GetExtraAxonalFraction () inline
Definition at line 66 of file animaMultiCompartmentModelCreator.h.
GetNewMultiCompartmentModel()
MultiCompartmentModelCreator::MCMPointer anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel ()
Definition at line 48 of file animaMultiCompartmentModelCreator.cxx.
References anima::DDI, GetUseCommonConcentrations(), GetUseCommonExtraAxonalFractions(), anima::MultiCompartmentModel::New(), anima::NODDI, anima::Stick, anima::Tensor, and anima::Zeppelin.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), main(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMCorrelationImageToImageMetric(), anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric(), anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMPairingMeanSquaresImageToImageMetric(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation(), anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MTPairingCorrelationImageToImageMetric(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks().
GetOrientationConcentration()
double anima::MultiCompartmentModelCreator::GetOrientationConcentration () inline
Definition at line 62 of file animaMultiCompartmentModelCreator.h.
GetRadialDiffusivity1()
double anima::MultiCompartmentModelCreator::GetRadialDiffusivity1 () inline
Definition at line 64 of file animaMultiCompartmentModelCreator.h.
GetRadialDiffusivity2()
double anima::MultiCompartmentModelCreator::GetRadialDiffusivity2 () inline
Definition at line 65 of file animaMultiCompartmentModelCreator.h.
GetUseCommonConcentrations()
bool anima::MultiCompartmentModelCreator::GetUseCommonConcentrations () inline
Definition at line 52 of file animaMultiCompartmentModelCreator.h.
Referenced by GetNewMultiCompartmentModel().
GetUseCommonDiffusivities()
bool anima::MultiCompartmentModelCreator::GetUseCommonDiffusivities () inline
Definition at line 51 of file animaMultiCompartmentModelCreator.h.
GetUseCommonExtraAxonalFractions()
bool anima::MultiCompartmentModelCreator::GetUseCommonExtraAxonalFractions () inline
Definition at line 53 of file animaMultiCompartmentModelCreator.h.
Referenced by GetNewMultiCompartmentModel().
GetUseConstrainedDiffusivity()
bool anima::MultiCompartmentModelCreator::GetUseConstrainedDiffusivity () inline
Definition at line 43 of file animaMultiCompartmentModelCreator.h.
GetUseConstrainedExtraAxonalFraction()
bool anima::MultiCompartmentModelCreator::GetUseConstrainedExtraAxonalFraction () inline
Definition at line 45 of file animaMultiCompartmentModelCreator.h.
GetUseConstrainedOrientationConcentration()
bool anima::MultiCompartmentModelCreator::GetUseConstrainedOrientationConcentration () inline
Definition at line 44 of file animaMultiCompartmentModelCreator.h.
SetAxialDiffusivityValue()
void anima::MultiCompartmentModelCreator::SetAxialDiffusivityValue (double arg) inline
Definition at line 58 of file animaMultiCompartmentModelCreator.h.
SetCompartmentType()
void anima::MultiCompartmentModelCreator::SetCompartmentType (CompartmentType arg) inline
Definition at line 31 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), main(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation().
SetFreeWaterDiffusivityValue()
void anima::MultiCompartmentModelCreator::SetFreeWaterDiffusivityValue (double arg) inline
Definition at line 55 of file animaMultiCompartmentModelCreator.h.
SetIRWDiffusivityValue()
void anima::MultiCompartmentModelCreator::SetIRWDiffusivityValue (double arg) inline
Definition at line 56 of file animaMultiCompartmentModelCreator.h.
SetModelWithFreeWaterComponent()
void anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent (bool arg) inline
Definition at line 26 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), main(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMCorrelationImageToImageMetric(), anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric(), anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMPairingMeanSquaresImageToImageMetric(), and anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MTPairingCorrelationImageToImageMetric().
SetModelWithRestrictedWaterComponent()
void anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent (bool arg) inline
Definition at line 28 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), and main().
SetModelWithStaniszComponent()
void anima::MultiCompartmentModelCreator::SetModelWithStaniszComponent (bool arg) inline
Definition at line 29 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
SetModelWithStationaryWaterComponent()
void anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent (bool arg) inline
Definition at line 27 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), main(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMCorrelationImageToImageMetric(), anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric(), anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMPairingMeanSquaresImageToImageMetric(), and anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MTPairingCorrelationImageToImageMetric().
SetNumberOfCompartments()
void anima::MultiCompartmentModelCreator::SetNumberOfCompartments (unsigned int num) inline
Definition at line 32 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), main(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMCorrelationImageToImageMetric(), anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric(), anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMPairingMeanSquaresImageToImageMetric(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation(), anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MTPairingCorrelationImageToImageMetric(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks().
SetRadialDiffusivity1Value()
void anima::MultiCompartmentModelCreator::SetRadialDiffusivity1Value (double arg) inline
Definition at line 59 of file animaMultiCompartmentModelCreator.h.
SetRadialDiffusivity2Value()
void anima::MultiCompartmentModelCreator::SetRadialDiffusivity2Value (double arg) inline
Definition at line 60 of file animaMultiCompartmentModelCreator.h.
SetStaniszDiffusivityValue()
void anima::MultiCompartmentModelCreator::SetStaniszDiffusivityValue (double arg) inline
Definition at line 57 of file animaMultiCompartmentModelCreator.h.
SetUseCommonConcentrations()
void anima::MultiCompartmentModelCreator::SetUseCommonConcentrations (bool arg) inline
Definition at line 48 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation().
SetUseCommonDiffusivities()
void anima::MultiCompartmentModelCreator::SetUseCommonDiffusivities (bool arg) inline
Definition at line 47 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
SetUseCommonExtraAxonalFractions()
void anima::MultiCompartmentModelCreator::SetUseCommonExtraAxonalFractions (bool arg) inline
Definition at line 49 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation().
SetUseConstrainedDiffusivity()
void anima::MultiCompartmentModelCreator::SetUseConstrainedDiffusivity (bool arg) inline
Definition at line 35 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation().
SetUseConstrainedExtraAxonalFraction()
void anima::MultiCompartmentModelCreator::SetUseConstrainedExtraAxonalFraction (bool arg) inline
Definition at line 37 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation().
SetUseConstrainedFreeWaterDiffusivity()
void anima::MultiCompartmentModelCreator::SetUseConstrainedFreeWaterDiffusivity (bool arg) inline
Definition at line 38 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
SetUseConstrainedIRWDiffusivity()
void anima::MultiCompartmentModelCreator::SetUseConstrainedIRWDiffusivity (bool arg) inline
Definition at line 39 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
SetUseConstrainedOrientationConcentration()
void anima::MultiCompartmentModelCreator::SetUseConstrainedOrientationConcentration (bool arg) inline
Definition at line 36 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation().
SetUseConstrainedStaniszDiffusivity()
void anima::MultiCompartmentModelCreator::SetUseConstrainedStaniszDiffusivity (bool arg) inline
Definition at line 40 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
SetUseConstrainedStaniszRadius()
void anima::MultiCompartmentModelCreator::SetUseConstrainedStaniszRadius (bool arg) inline
Definition at line 41 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
SetVariableProjectionEstimationMode()
void anima::MultiCompartmentModelCreator::SetVariableProjectionEstimationMode (bool arg) inline
Definition at line 33 of file animaMultiCompartmentModelCreator.h.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation().
The documentation for this class was generated from the following files:
animaMultiCompartmentModelCreator.h
animaMultiCompartmentModelCreator.cxx