ANIMA: anima::SVFExponentialImageFilter< TPixelType, Dimension > Class Template Reference
anima::SVFExponentialImageFilter< TPixelType, Dimension > Class Template Reference
Computes the exponentiation of a stationary velocity field using sclaing and squaring and approximated exponential integrators.
#include <animaSVFExponentialImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Image< itk::Vector< TPixelType, Dimension >, Dimension > InputImageType
typedef InputImageType::PixelType InputPixelType
typedef JacobianImageType::Pointer JacobianImagePointer
typedef itk::Image< itk::Vector< TPixelType, Dimension *Dimension >, Dimension > JacobianImageType
typedef JacobianImageType::PixelType JacobianPixelType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image< itk::Vector< TPixelType, Dimension >, Dimension > OutputImageType
typedef OutputImageType::PixelType OutputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef SVFExponentialImageFilter Self
typedef itk::ImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetExponentiationOrder (unsigned int _arg)
virtual void SetMaximalDisplacementAmplitude (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void AfterThreadedGenerateData () ITK_OVERRIDE
void BeforeThreadedGenerateData () ITK_OVERRIDE
SVFExponentialImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~SVFExponentialImageFilter ()
Detailed Description
template<typename TPixelType, unsigned int Dimension>
class anima::SVFExponentialImageFilter< TPixelType, Dimension >
Computes the exponentiation of a stationary velocity field using sclaing and squaring and approximated exponential integrators.
Depending on the order set (0 or 1), the approximated exponentiation for a small enough field is performed using Ferraris et al. ss_aei or Arsigny et al. original approach
S. Ferraris et al. Accurate small deformation exponential approximant to integrate large velocity fields: Application to image registration. WBIR 2016 V. Arsigny et al. A Log-Euclidean Framework for Statistics on Diffeomorphisms. MICCAI 2006.
Definition at line 19 of file animaSVFExponentialImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TPixelType , unsigned int Dimension> typedef itk::SmartPointer<const Self> anima::SVFExponentialImageFilter< TPixelType, Dimension >::ConstPointer
Definition at line 30 of file animaSVFExponentialImageFilter.h.
InputImageType
template<typename TPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TPixelType, Dimension>, Dimension> anima::SVFExponentialImageFilter< TPixelType, Dimension >::InputImageType
Definition at line 25 of file animaSVFExponentialImageFilter.h.
InputPixelType
template<typename TPixelType , unsigned int Dimension> typedef InputImageType::PixelType anima::SVFExponentialImageFilter< TPixelType, Dimension >::InputPixelType
Definition at line 36 of file animaSVFExponentialImageFilter.h.
JacobianImagePointer
template<typename TPixelType , unsigned int Dimension> typedef JacobianImageType::Pointer anima::SVFExponentialImageFilter< TPixelType, Dimension >::JacobianImagePointer
Definition at line 38 of file animaSVFExponentialImageFilter.h.
JacobianImageType
template<typename TPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TPixelType, Dimension * Dimension>, Dimension> anima::SVFExponentialImageFilter< TPixelType, Dimension >::JacobianImageType
Definition at line 26 of file animaSVFExponentialImageFilter.h.
JacobianPixelType
template<typename TPixelType , unsigned int Dimension> typedef JacobianImageType::PixelType anima::SVFExponentialImageFilter< TPixelType, Dimension >::JacobianPixelType
Definition at line 39 of file animaSVFExponentialImageFilter.h.
OutputImageRegionType
template<typename TPixelType , unsigned int Dimension> typedef Superclass::OutputImageRegionType anima::SVFExponentialImageFilter< TPixelType, Dimension >::OutputImageRegionType
Definition at line 41 of file animaSVFExponentialImageFilter.h.
OutputImageType
template<typename TPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TPixelType, Dimension>, Dimension> anima::SVFExponentialImageFilter< TPixelType, Dimension >::OutputImageType
Definition at line 27 of file animaSVFExponentialImageFilter.h.
OutputPixelType
template<typename TPixelType , unsigned int Dimension> typedef OutputImageType::PixelType anima::SVFExponentialImageFilter< TPixelType, Dimension >::OutputPixelType
Definition at line 37 of file animaSVFExponentialImageFilter.h.
Pointer
template<typename TPixelType , unsigned int Dimension> typedef itk::SmartPointer<Self> anima::SVFExponentialImageFilter< TPixelType, Dimension >::Pointer
Definition at line 29 of file animaSVFExponentialImageFilter.h.
Self
template<typename TPixelType , unsigned int Dimension> typedef SVFExponentialImageFilter anima::SVFExponentialImageFilter< TPixelType, Dimension >::Self
Definition at line 24 of file animaSVFExponentialImageFilter.h.
Superclass
template<typename TPixelType , unsigned int Dimension> typedef itk::ImageToImageFilter<InputImageType, OutputImageType> anima::SVFExponentialImageFilter< TPixelType, Dimension >::Superclass
Definition at line 28 of file animaSVFExponentialImageFilter.h.
Constructor & Destructor Documentation
SVFExponentialImageFilter()
template<typename TPixelType , unsigned int Dimension> anima::SVFExponentialImageFilter< TPixelType, Dimension >::SVFExponentialImageFilter () inline protected
Definition at line 47 of file animaSVFExponentialImageFilter.h.
~SVFExponentialImageFilter()
template<typename TPixelType , unsigned int Dimension> virtual anima::SVFExponentialImageFilter< TPixelType, Dimension >::~SVFExponentialImageFilter () inline protected virtual
Definition at line 54 of file animaSVFExponentialImageFilter.h.
References anima::SVFExponentialImageFilter< TPixelType, Dimension >::AfterThreadedGenerateData(), anima::SVFExponentialImageFilter< TPixelType, Dimension >::BeforeThreadedGenerateData(), and anima::SVFExponentialImageFilter< TPixelType, Dimension >::ThreadedGenerateData().
Member Function Documentation
AfterThreadedGenerateData()
template<typename TPixelType , unsigned int Dimension> void anima::SVFExponentialImageFilter< TPixelType, Dimension >::AfterThreadedGenerateData () protected
Definition at line 127 of file animaSVFExponentialImageFilter.hxx.
Referenced by anima::SVFExponentialImageFilter< TPixelType, Dimension >::~SVFExponentialImageFilter().
BeforeThreadedGenerateData()
template<typename TPixelType , unsigned int Dimension> void anima::SVFExponentialImageFilter< TPixelType, Dimension >::BeforeThreadedGenerateData () protected
Definition at line 17 of file animaSVFExponentialImageFilter.hxx.
Referenced by anima::SVFExponentialImageFilter< TPixelType, Dimension >::~SVFExponentialImageFilter().
CreateAnother()
template<typename TPixelType , unsigned int Dimension> virtual::itk::LightObject::Pointer anima::SVFExponentialImageFilter< TPixelType, Dimension >::CreateAnother (void) const
GetNameOfClass()
template<typename TPixelType , unsigned int Dimension> virtual const char* anima::SVFExponentialImageFilter< TPixelType, Dimension >::GetNameOfClass () const virtual
New()
template<typename TPixelType , unsigned int Dimension> static Pointer anima::SVFExponentialImageFilter< TPixelType, Dimension >::New () static
SetExponentiationOrder()
template<typename TPixelType , unsigned int Dimension> virtual void anima::SVFExponentialImageFilter< TPixelType, Dimension >::SetExponentiationOrder (unsigned int _arg) virtual
SetMaximalDisplacementAmplitude()
template<typename TPixelType , unsigned int Dimension> virtual void anima::SVFExponentialImageFilter< TPixelType, Dimension >::SetMaximalDisplacementAmplitude (double _arg) virtual
ThreadedGenerateData()
template<typename TPixelType , unsigned int Dimension> void anima::SVFExponentialImageFilter< TPixelType, Dimension >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 81 of file animaSVFExponentialImageFilter.hxx.
Referenced by anima::SVFExponentialImageFilter< TPixelType, Dimension >::~SVFExponentialImageFilter().
The documentation for this class was generated from the following files:
animaSVFExponentialImageFilter.h
animaSVFExponentialImageFilter.hxx