ANIMA: anima::IsotropicRestrictedWaterCompartment Class Reference
anima::IsotropicRestrictedWaterCompartment Class Reference
#include <animaIsotropicRestrictedWaterCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::SmartPointer< Self > Pointer
typedef IsotropicRestrictedWaterCompartment Self
typedef BaseIsotropicCompartment Superclass
Public Types inherited from anima::BaseIsotropicCompartment
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseIsotropicCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
virtual const char * GetNameOfClass () const
virtual ListType & GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType & GetParameterUpperBounds () ITK_OVERRIDE
Public Member Functions inherited from anima::BaseIsotropicCompartment
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
bool GetEstimateAxialDiffusivity ()
virtual double GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType & GetParametersAsVector () ITK_OVERRIDE
virtual ListType & GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform) ITK_OVERRIDE
Reimplements re-orientation, useless in isotropic water compartment.
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
virtual bool GetTensorCompatible ()
virtual double GetTissueRadius ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-2, double absoluteTolerance=1.0e-8)
Tests equality to another compartment up to a constant (relative and absolute tolerances)
virtual void SetAxialDiffusivity (double num)
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
virtual void SetTissueRadius (double num)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
IsotropicRestrictedWaterCompartment ()
virtual ~IsotropicRestrictedWaterCompartment ()
Protected Member Functions inherited from anima::BaseIsotropicCompartment
BaseIsotropicCompartment ()
virtual ~BaseIsotropicCompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
ListType m_JacobianVector
Vector holding current jacobian value.
ListType m_ParametersLowerBoundsVector
Vector holding current parameters lower bounds.
ListType m_ParametersUpperBoundsVector
Vector holding current parameters upper bounds.
ListType m_ParametersVector
Vector holding current parameters vector.
Static Protected Attributes inherited from anima::BaseCompartment
static const unsigned int m_SpaceDimension = 3
Detailed Description
Definition at line 9 of file animaIsotropicRestrictedWaterCompartment.h.
Member Typedef Documentation
BasePointer
typedef Superclass::Pointer anima::IsotropicRestrictedWaterCompartment::BasePointer
Definition at line 15 of file animaIsotropicRestrictedWaterCompartment.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::IsotropicRestrictedWaterCompartment::ConstPointer
Definition at line 17 of file animaIsotropicRestrictedWaterCompartment.h.
Pointer
typedef itk::SmartPointer<Self> anima::IsotropicRestrictedWaterCompartment::Pointer
Definition at line 16 of file animaIsotropicRestrictedWaterCompartment.h.
Self
typedef IsotropicRestrictedWaterCompartment anima::IsotropicRestrictedWaterCompartment::Self
Definition at line 13 of file animaIsotropicRestrictedWaterCompartment.h.
Superclass
typedef BaseIsotropicCompartment anima::IsotropicRestrictedWaterCompartment::Superclass
Definition at line 14 of file animaIsotropicRestrictedWaterCompartment.h.
Constructor & Destructor Documentation
IsotropicRestrictedWaterCompartment()
anima::IsotropicRestrictedWaterCompartment::IsotropicRestrictedWaterCompartment () inline protected
Definition at line 31 of file animaIsotropicRestrictedWaterCompartment.h.
~IsotropicRestrictedWaterCompartment()
virtual anima::IsotropicRestrictedWaterCompartment::~IsotropicRestrictedWaterCompartment () inline protected virtual
Definition at line 36 of file animaIsotropicRestrictedWaterCompartment.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::IsotropicRestrictedWaterCompartment::CreateAnother (void) const
GetCompartmentType()
DiffusionModelCompartmentType anima::IsotropicRestrictedWaterCompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 25 of file animaIsotropicRestrictedWaterCompartment.h.
References anima::IsotropicRestrictedWater.
GetNameOfClass()
virtual const char* anima::IsotropicRestrictedWaterCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseIsotropicCompartment.
GetParameterLowerBounds()
IsotropicRestrictedWaterCompartment::ListType & anima::IsotropicRestrictedWaterCompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 7 of file animaIsotropicRestrictedWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), anima::BaseIsotropicCompartment::GetNumberOfParameters(), anima::BaseCompartment::m_ParametersLowerBoundsVector, and anima::MCMIsotropicRestrictedWaterDiffusivityLowerBound.
GetParameterUpperBounds()
IsotropicRestrictedWaterCompartment::ListType & anima::IsotropicRestrictedWaterCompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 17 of file animaIsotropicRestrictedWaterCompartment.cxx.
References anima::BaseIsotropicCompartment::GetEstimateAxialDiffusivity(), anima::BaseIsotropicCompartment::GetNumberOfParameters(), anima::BaseCompartment::m_ParametersUpperBoundsVector, and anima::MCMIsotropicRestrictedWaterDiffusivityUpperBound.
New()
static Pointer anima::IsotropicRestrictedWaterCompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
The documentation for this class was generated from the following files:
animaIsotropicRestrictedWaterCompartment.h
animaIsotropicRestrictedWaterCompartment.cxx