ANIMA: anima::DTIScalarMapsImageFilter< ImageDimension > Class Template Reference
anima::DTIScalarMapsImageFilter< ImageDimension > Class Template Reference
Applies an variance filter to an image.
#include <animaDTIScalarMapsImageFilter.h>
Public Types
typedef OutputImageType ADCImageType
typedef itk::SmartPointer< const Self > ConstPointer
typedef OutputImageType FAImageType
typedef itk::VectorImage< float, ImageDimension > InputImageType
typedef OutputImageType::RegionType OutputImageRegionType
typedef itk::Image< float, ImageDimension > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef DTIScalarMapsImageFilter Self
typedef itk::ImageToImageFilter< InputImageType, OutputImageType > Superclass
typedef TensorImageType::RegionType TensorImageRegionType
typedef TensorImageType::SizeType TensorImageSizeType
typedef InputImageType TensorImageType
typedef TensorImageType::PixelType TensorVectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
OutputImageType::Pointer GetADCImage ()
OutputImageType::Pointer GetAxialDiffusivityImage ()
OutputImageType::Pointer GetFAImage ()
virtual const char * GetNameOfClass () const
OutputImageType::Pointer GetRadialDiffusivityImage ()
itk::DataObject::Pointer MakeOutput (itk::ProcessObject::DataObjectPointerArraySizeType idx) ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int InputImageDimension = InputImageType::ImageDimension
static const unsigned int OutputImageDimension = OutputImageType::ImageDimension
Protected Member Functions
DTIScalarMapsImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~DTIScalarMapsImageFilter ()
Detailed Description
template<unsigned int ImageDimension = 3>
class anima::DTIScalarMapsImageFilter< ImageDimension >
Applies an variance filter to an image.
Computes tow image where a given pixel is the FA or ADC value of the tensor of the corresponding input pixel.
Definition at line 23 of file animaDTIScalarMapsImageFilter.h.
Member Typedef Documentation
ADCImageType
template<unsigned int ImageDimension = 3> typedef OutputImageType anima::DTIScalarMapsImageFilter< ImageDimension >::ADCImageType
Definition at line 34 of file animaDTIScalarMapsImageFilter.h.
ConstPointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<const Self> anima::DTIScalarMapsImageFilter< ImageDimension >::ConstPointer
Definition at line 47 of file animaDTIScalarMapsImageFilter.h.
FAImageType
template<unsigned int ImageDimension = 3> typedef OutputImageType anima::DTIScalarMapsImageFilter< ImageDimension >::FAImageType
Definition at line 33 of file animaDTIScalarMapsImageFilter.h.
InputImageType
template<unsigned int ImageDimension = 3> typedef itk::VectorImage<float, ImageDimension> anima::DTIScalarMapsImageFilter< ImageDimension >::InputImageType
Convenient typedefs for simplifying declarations.
Definition at line 30 of file animaDTIScalarMapsImageFilter.h.
OutputImageRegionType
template<unsigned int ImageDimension = 3> typedef OutputImageType::RegionType anima::DTIScalarMapsImageFilter< ImageDimension >::OutputImageRegionType
Definition at line 59 of file animaDTIScalarMapsImageFilter.h.
OutputImageType
template<unsigned int ImageDimension = 3> typedef itk::Image< float, ImageDimension> anima::DTIScalarMapsImageFilter< ImageDimension >::OutputImageType
Definition at line 31 of file animaDTIScalarMapsImageFilter.h.
Pointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<Self> anima::DTIScalarMapsImageFilter< ImageDimension >::Pointer
Definition at line 46 of file animaDTIScalarMapsImageFilter.h.
Self
template<unsigned int ImageDimension = 3> typedef DTIScalarMapsImageFilter anima::DTIScalarMapsImageFilter< ImageDimension >::Self
Standard class typedefs.
Definition at line 44 of file animaDTIScalarMapsImageFilter.h.
Superclass
template<unsigned int ImageDimension = 3> typedef itk::ImageToImageFilter< InputImageType, OutputImageType> anima::DTIScalarMapsImageFilter< ImageDimension >::Superclass
Definition at line 45 of file animaDTIScalarMapsImageFilter.h.
TensorImageRegionType
template<unsigned int ImageDimension = 3> typedef TensorImageType::RegionType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorImageRegionType
Definition at line 58 of file animaDTIScalarMapsImageFilter.h.
TensorImageSizeType
template<unsigned int ImageDimension = 3> typedef TensorImageType::SizeType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorImageSizeType
Definition at line 60 of file animaDTIScalarMapsImageFilter.h.
TensorImageType
template<unsigned int ImageDimension = 3> typedef InputImageType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorImageType
Definition at line 32 of file animaDTIScalarMapsImageFilter.h.
TensorVectorType
template<unsigned int ImageDimension = 3> typedef TensorImageType::PixelType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorVectorType
Image typedef support.
Definition at line 56 of file animaDTIScalarMapsImageFilter.h.
Constructor & Destructor Documentation
DTIScalarMapsImageFilter()
template<unsigned int ImageDimension> anima::DTIScalarMapsImageFilter< ImageDimension >::DTIScalarMapsImageFilter () protected
Definition at line 21 of file animaDTIScalarMapsImageFilter.hxx.
Referenced by anima::DTIScalarMapsImageFilter< ImageDimension >::GetRadialDiffusivityImage().
~DTIScalarMapsImageFilter()
template<unsigned int ImageDimension = 3> virtual anima::DTIScalarMapsImageFilter< ImageDimension >::~DTIScalarMapsImageFilter () inline protected virtual
Definition at line 72 of file animaDTIScalarMapsImageFilter.h.
References anima::DTIScalarMapsImageFilter< ImageDimension >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<unsigned int ImageDimension = 3> virtual::itk::LightObject::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::CreateAnother (void) const
GetADCImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetADCImage () inline
Definition at line 65 of file animaDTIScalarMapsImageFilter.h.
GetAxialDiffusivityImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetAxialDiffusivityImage () inline
Definition at line 67 of file animaDTIScalarMapsImageFilter.h.
GetFAImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetFAImage () inline
Definition at line 66 of file animaDTIScalarMapsImageFilter.h.
GetNameOfClass()
template<unsigned int ImageDimension = 3> virtual const char* anima::DTIScalarMapsImageFilter< ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetRadialDiffusivityImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetRadialDiffusivityImage () inline
Definition at line 68 of file animaDTIScalarMapsImageFilter.h.
References anima::DTIScalarMapsImageFilter< ImageDimension >::DTIScalarMapsImageFilter().
MakeOutput()
template<unsigned int ImageDimension> itk::DataObject::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::MakeOutput (itk::ProcessObject::DataObjectPointerArraySizeType idx)
Create the Output
Make Ouput
Definition at line 37 of file animaDTIScalarMapsImageFilter.hxx.
New()
template<unsigned int ImageDimension = 3> static Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::New () static
Method for creation through the object factory.
ThreadedGenerateData()
template<unsigned int ImageDimension> void anima::DTIScalarMapsImageFilter< ImageDimension >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
DTIScalarMapsImageFilter can be implemented as a multithreaded filter. Therefore, this implementation provides a ThreadedGenerateData() routine which is called for each processing thread. The output image data is allocated automatically by the superclass prior to calling ThreadedGenerateData(). ThreadedGenerateData can only write to the portion of the output image specified by the parameter "outputRegionForThread"
See also
ImageToImageFilter::ThreadedGenerateData(), ImageToImageFilter::GenerateData()
Definition at line 44 of file animaDTIScalarMapsImageFilter.hxx.
References anima::GetTensorFromVectorRepresentation().
Referenced by anima::DTIScalarMapsImageFilter< ImageDimension >::~DTIScalarMapsImageFilter().
Member Data Documentation
InputImageDimension
template<unsigned int ImageDimension = 3> const unsigned int anima::DTIScalarMapsImageFilter< ImageDimension >::InputImageDimension = InputImageType::ImageDimension static
Extract dimension from input and output image.
Definition at line 38 of file animaDTIScalarMapsImageFilter.h.
OutputImageDimension
template<unsigned int ImageDimension = 3> const unsigned int anima::DTIScalarMapsImageFilter< ImageDimension >::OutputImageDimension = OutputImageType::ImageDimension static
Definition at line 40 of file animaDTIScalarMapsImageFilter.h.
The documentation for this class was generated from the following files:
animaDTIScalarMapsImageFilter.h
animaDTIScalarMapsImageFilter.hxx