ANIMA: anima::BaseTransformAgregator< NDimensions > Class Template Reference
anima::BaseTransformAgregator< NDimensions > Class Template Reference abstract
#include <animaBaseTransformAgregator.h>
Public Types
typedef BaseInputTransformType::Pointer BaseInputTransformPointer
typedef itk::Transform< InternalScalarType, NDimensions, NDimensions > BaseInputTransformType
typedef itk::Transform< ScalarType, NDimensions, NDimensions > BaseOutputTransformType
typedef double InternalScalarType
typedef itk::Matrix< ScalarType, NDimensions, NDimensions > MatrixType
typedef itk::Point< InternalScalarType, NDimensions > PointType
typedef itk::ImageRegion< NDimensions > RegionType
typedef double ScalarType
enum TRANSFORM_TYPE {
TRANSLATION,
RIGID,
ANISOTROPIC_SIM,
AFFINE,
DIRECTIONAL_AFFINE,
SVF
}
Public Member Functions
BaseTransformAgregator ()
BaseInputTransformPointer & GetCurrentLinearTransform ()
virtual PointType GetEstimationBarycenter ()
PointType & GetInputOrigin (unsigned int i)
std::vector< PointType > & GetInputOrigins ()
std::vector< RegionType > & GetInputRegions ()
BaseInputTransformType * GetInputTransform (unsigned int i)
std::vector< BaseInputTransformPointer > & GetInputTransforms ()
TRANSFORM_TYPE GetInputTransformType ()
InternalScalarType GetInputWeight (unsigned int i)
std::vector< InternalScalarType > & GetInputWeights ()
MatrixType & GetOrthogonalDirectionMatrix ()
BaseOutputTransformType * GetOutput ()
TRANSFORM_TYPE GetOutputTransformType ()
bool GetVerboseAgregation ()
void SetCurrentLinearTransform (BaseInputTransformPointer &inputTransforms)
void SetInputOrigins (const std::vector< PointType > &inputOrigins)
void SetInputRegions (const std::vector< RegionType > &inputRegions)
void SetInputTransforms (std::vector< BaseInputTransformPointer > &inputTransforms)
void SetInputTransformType (TRANSFORM_TYPE name)
void SetInputWeight (unsigned int i, double w)
void SetInputWeights (const std::vector< InternalScalarType > &weights)
void SetOrthogonalDirectionMatrix (const MatrixType &inputTransforms)
void SetOutputTransformType (TRANSFORM_TYPE name)
void SetUpToDate (bool value)
void SetVerboseAgregation (bool value)
virtual bool Update ()=0
virtual ~BaseTransformAgregator ()
Protected Member Functions
void SetOutput (BaseOutputTransformType *output)
Detailed Description
template<unsigned int NDimensions = 3>
class anima::BaseTransformAgregator< NDimensions >
Definition at line 16 of file animaBaseTransformAgregator.h.
Member Typedef Documentation
BaseInputTransformPointer
template<unsigned int NDimensions = 3> typedef BaseInputTransformType::Pointer anima::BaseTransformAgregator< NDimensions >::BaseInputTransformPointer
Definition at line 22 of file animaBaseTransformAgregator.h.
BaseInputTransformType
template<unsigned int NDimensions = 3> typedef itk::Transform<InternalScalarType,NDimensions,NDimensions> anima::BaseTransformAgregator< NDimensions >::BaseInputTransformType
Definition at line 21 of file animaBaseTransformAgregator.h.
BaseOutputTransformType
template<unsigned int NDimensions = 3> typedef itk::Transform<ScalarType,NDimensions,NDimensions> anima::BaseTransformAgregator< NDimensions >::BaseOutputTransformType
Definition at line 23 of file animaBaseTransformAgregator.h.
InternalScalarType
template<unsigned int NDimensions = 3> typedef double anima::BaseTransformAgregator< NDimensions >::InternalScalarType
Definition at line 20 of file animaBaseTransformAgregator.h.
MatrixType
template<unsigned int NDimensions = 3> typedef itk::Matrix<ScalarType,NDimensions,NDimensions> anima::BaseTransformAgregator< NDimensions >::MatrixType
Definition at line 26 of file animaBaseTransformAgregator.h.
PointType
template<unsigned int NDimensions = 3> typedef itk::Point<InternalScalarType,NDimensions> anima::BaseTransformAgregator< NDimensions >::PointType
Definition at line 24 of file animaBaseTransformAgregator.h.
RegionType
template<unsigned int NDimensions = 3> typedef itk::ImageRegion<NDimensions> anima::BaseTransformAgregator< NDimensions >::RegionType
Definition at line 25 of file animaBaseTransformAgregator.h.
ScalarType
template<unsigned int NDimensions = 3> typedef double anima::BaseTransformAgregator< NDimensions >::ScalarType
Definition at line 19 of file animaBaseTransformAgregator.h.
Member Enumeration Documentation
TRANSFORM_TYPE
template<unsigned int NDimensions = 3> enum anima::BaseTransformAgregator::TRANSFORM_TYPE
Enumerator
TRANSLATION
RIGID
ANISOTROPIC_SIM
AFFINE
DIRECTIONAL_AFFINE
SVF
Definition at line 28 of file animaBaseTransformAgregator.h.
Constructor & Destructor Documentation
BaseTransformAgregator()
template<unsigned int NDimensions> anima::BaseTransformAgregator< NDimensions >::BaseTransformAgregator ()
Definition at line 9 of file animaBaseTransformAgregator.hxx.
~BaseTransformAgregator()
template<unsigned int NDimensions> anima::BaseTransformAgregator< NDimensions >::~BaseTransformAgregator () virtual
Definition at line 26 of file animaBaseTransformAgregator.hxx.
Member Function Documentation
GetCurrentLinearTransform()
template<unsigned int NDimensions = 3> BaseInputTransformPointer& anima::BaseTransformAgregator< NDimensions >::GetCurrentLinearTransform () inline
Definition at line 47 of file animaBaseTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::SetOrthogonalDirectionMatrix().
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), and anima::LTSWTransformAgregator< NDimensions >::Update().
GetEstimationBarycenter()
template<unsigned int NDimensions = 3> virtual PointType anima::BaseTransformAgregator< NDimensions >::GetEstimationBarycenter () inline virtual
Reimplemented in anima::LTSWTransformAgregator< NDimensions >, anima::LSWTransformAgregator< NDimensions >, and anima::MEstTransformAgregator< NDimensions >.
Definition at line 91 of file animaBaseTransformAgregator.h.
GetInputOrigin()
template<unsigned int NDimensions = 3> PointType& anima::BaseTransformAgregator< NDimensions >::GetInputOrigin (unsigned int i) inline
Definition at line 67 of file animaBaseTransformAgregator.h.
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetInputOrigins()
template<unsigned int NDimensions = 3> std::vector<PointType>& anima::BaseTransformAgregator< NDimensions >::GetInputOrigins () inline
Definition at line 66 of file animaBaseTransformAgregator.h.
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), and anima::LTSWTransformAgregator< NDimensions >::Update().
GetInputRegions()
template<unsigned int NDimensions = 3> std::vector<RegionType>& anima::BaseTransformAgregator< NDimensions >::GetInputRegions () inline
Definition at line 65 of file animaBaseTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetInputTransform()
template<unsigned int NDimensions = 3> BaseInputTransformType* anima::BaseTransformAgregator< NDimensions >::GetInputTransform (unsigned int i) inline
Definition at line 43 of file animaBaseTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::SetCurrentLinearTransform().
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetInputTransforms()
template<unsigned int NDimensions = 3> std::vector<BaseInputTransformPointer>& anima::BaseTransformAgregator< NDimensions >::GetInputTransforms () inline
Definition at line 42 of file animaBaseTransformAgregator.h.
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetInputTransformType()
template<unsigned int NDimensions = 3> TRANSFORM_TYPE anima::BaseTransformAgregator< NDimensions >::GetInputTransformType () inline
Definition at line 93 of file animaBaseTransformAgregator.h.
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetInputWeight()
template<unsigned int NDimensions = 3> InternalScalarType anima::BaseTransformAgregator< NDimensions >::GetInputWeight (unsigned int i) inline
Definition at line 76 of file animaBaseTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetInputWeights()
template<unsigned int NDimensions = 3> std::vector<InternalScalarType>& anima::BaseTransformAgregator< NDimensions >::GetInputWeights () inline
Definition at line 75 of file animaBaseTransformAgregator.h.
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetOrthogonalDirectionMatrix()
template<unsigned int NDimensions = 3> MatrixType& anima::BaseTransformAgregator< NDimensions >::GetOrthogonalDirectionMatrix () inline
Definition at line 51 of file animaBaseTransformAgregator.h.
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), and anima::LTSWTransformAgregator< NDimensions >::Update().
GetOutput()
template<unsigned int NDimensions> BaseTransformAgregator< NDimensions >::BaseOutputTransformType * anima::BaseTransformAgregator< NDimensions >::GetOutput ()
Definition at line 67 of file animaBaseTransformAgregator.hxx.
Referenced by anima::BaseTransformAgregator< NDimensions >::GetOutputTransformType().
GetOutputTransformType()
template<unsigned int NDimensions = 3> TRANSFORM_TYPE anima::BaseTransformAgregator< NDimensions >::GetOutputTransformType () inline
Definition at line 94 of file animaBaseTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::GetOutput(), anima::BaseTransformAgregator< NDimensions >::SetOutput(), and anima::BaseTransformAgregator< NDimensions >::Update().
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
GetVerboseAgregation()
template<unsigned int NDimensions = 3> bool anima::BaseTransformAgregator< NDimensions >::GetVerboseAgregation () inline
Definition at line 89 of file animaBaseTransformAgregator.h.
Referenced by anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
SetCurrentLinearTransform()
template<unsigned int NDimensions> void anima::BaseTransformAgregator< NDimensions >::SetCurrentLinearTransform (BaseInputTransformPointer & inputTransforms)
Definition at line 101 of file animaBaseTransformAgregator.hxx.
Referenced by anima::BaseTransformAgregator< NDimensions >::GetInputTransform().
SetInputOrigins()
template<unsigned int NDimensions = 3> void anima::BaseTransformAgregator< NDimensions >::SetInputOrigins (const std::vector< PointType > & inputOrigins) inline
Definition at line 53 of file animaBaseTransformAgregator.h.
SetInputRegions()
template<unsigned int NDimensions = 3> void anima::BaseTransformAgregator< NDimensions >::SetInputRegions (const std::vector< RegionType > & inputRegions) inline
Definition at line 59 of file animaBaseTransformAgregator.h.
SetInputTransforms()
template<unsigned int NDimensions> void anima::BaseTransformAgregator< NDimensions >::SetInputTransforms (std::vector< BaseInputTransformPointer > & inputTransforms)
Definition at line 90 of file animaBaseTransformAgregator.hxx.
SetInputTransformType()
template<unsigned int NDimensions> void anima::BaseTransformAgregator< NDimensions >::SetInputTransformType (TRANSFORM_TYPE name)
Definition at line 33 of file animaBaseTransformAgregator.hxx.
Referenced by anima::BaseTransformAgregator< NDimensions >::SetInputWeight().
SetInputWeight()
template<unsigned int NDimensions = 3> void anima::BaseTransformAgregator< NDimensions >::SetInputWeight (unsigned int i, double w) inline
Definition at line 77 of file animaBaseTransformAgregator.h.
References anima::BaseTransformAgregator< NDimensions >::SetInputTransformType(), and anima::BaseTransformAgregator< NDimensions >::SetOutputTransformType().
Referenced by anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), and anima::LTSWTransformAgregator< NDimensions >::Update().
SetInputWeights()
template<unsigned int NDimensions = 3> void anima::BaseTransformAgregator< NDimensions >::SetInputWeights (const std::vector< InternalScalarType > & weights) inline
Definition at line 69 of file animaBaseTransformAgregator.h.
SetOrthogonalDirectionMatrix()
template<unsigned int NDimensions> void anima::BaseTransformAgregator< NDimensions >::SetOrthogonalDirectionMatrix (const MatrixType & inputTransforms)
Definition at line 111 of file animaBaseTransformAgregator.hxx.
Referenced by anima::BaseTransformAgregator< NDimensions >::GetCurrentLinearTransform().
SetOutput()
template<unsigned int NDimensions> void anima::BaseTransformAgregator< NDimensions >::SetOutput (BaseOutputTransformType * output) protected
Definition at line 82 of file animaBaseTransformAgregator.hxx.
Referenced by anima::BaseTransformAgregator< NDimensions >::GetOutputTransformType(), anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
SetOutputTransformType()
template<unsigned int NDimensions> void anima::BaseTransformAgregator< NDimensions >::SetOutputTransformType (TRANSFORM_TYPE name)
Definition at line 50 of file animaBaseTransformAgregator.hxx.
Referenced by anima::BaseTransformAgregator< NDimensions >::SetInputWeight(), anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetUpToDate()
template<unsigned int NDimensions = 3> void anima::BaseTransformAgregator< NDimensions >::SetUpToDate (bool value) inline
Definition at line 86 of file animaBaseTransformAgregator.h.
Referenced by anima::MEstTransformAgregator< NDimensions >::SeStoppingThreshold(), anima::MEstTransformAgregator< NDimensions >::SetMEstimateFactor(), anima::LSWTransformAgregator< NDimensions >::Update(), anima::MEstTransformAgregator< NDimensions >::Update(), anima::LTSWTransformAgregator< NDimensions >::Update(), anima::BalooSVFTransformAgregator< NDimensions >::Update(), and anima::DenseSVFTransformAgregator< NDimensions >::Update().
SetVerboseAgregation()
template<unsigned int NDimensions = 3> void anima::BaseTransformAgregator< NDimensions >::SetVerboseAgregation (bool value) inline
Definition at line 88 of file animaBaseTransformAgregator.h.
Referenced by anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update().
Update()
template<unsigned int NDimensions = 3> virtual bool anima::BaseTransformAgregator< NDimensions >::Update () pure virtual
Implemented in anima::DenseSVFTransformAgregator< NDimensions >, anima::BalooSVFTransformAgregator< NDimensions >, anima::LTSWTransformAgregator< NDimensions >, anima::LSWTransformAgregator< NDimensions >, and anima::MEstTransformAgregator< NDimensions >.
Referenced by anima::BaseTransformAgregator< NDimensions >::GetOutputTransformType().
The documentation for this class was generated from the following files:
animaBaseTransformAgregator.h
animaBaseTransformAgregator.hxx