ANIMA: anima::ShapesReader Class Reference
anima::ShapesReader Class Reference
#include <animaShapesReader.h>
Public Member Functions
vtkPolyData * GetOutput ()
void SetFileName (std::string &name)
ShapesReader ()
void Update ()
~ShapesReader ()
Protected Member Functions
void ReadFileAsCSV ()
void ReadFileAsMedinriaFibers ()
void ReadFileAsVTKAscii ()
void ReadFileAsVTKXML ()
Detailed Description
Definition at line 11 of file animaShapesReader.h.
Constructor & Destructor Documentation
ShapesReader()
anima::ShapesReader::ShapesReader () inline
Definition at line 14 of file animaShapesReader.h.
~ShapesReader()
anima::ShapesReader::~ShapesReader () inline
Definition at line 20 of file animaShapesReader.h.
Member Function Documentation
GetOutput()
vtkPolyData* anima::ShapesReader::GetOutput () inline
Definition at line 25 of file animaShapesReader.h.
Referenced by main().
ReadFileAsCSV()
void anima::ShapesReader::ReadFileAsCSV () protected
Definition at line 108 of file animaShapesReader.cxx.
Referenced by Update().
ReadFileAsMedinriaFibers()
void anima::ShapesReader::ReadFileAsMedinriaFibers () protected
Definition at line 58 of file animaShapesReader.cxx.
Referenced by Update().
ReadFileAsVTKAscii()
void anima::ShapesReader::ReadFileAsVTKAscii () protected
Definition at line 38 of file animaShapesReader.cxx.
Referenced by Update().
ReadFileAsVTKXML()
void anima::ShapesReader::ReadFileAsVTKXML () protected
Definition at line 48 of file animaShapesReader.cxx.
Referenced by Update().
SetFileName()
void anima::ShapesReader::SetFileName (std::string & name) inline
Definition at line 22 of file animaShapesReader.h.
Referenced by main().
Update()
void anima::ShapesReader::Update ()
Definition at line 18 of file animaShapesReader.cxx.
References ReadFileAsCSV(), ReadFileAsMedinriaFibers(), ReadFileAsVTKAscii(), and ReadFileAsVTKXML().
Referenced by main().
The documentation for this class was generated from the following files:
animaShapesReader.h
animaShapesReader.cxx