ANIMA: anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep > Class Template Reference
anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep > Class Template Reference
#include <animaMCMLinearInterpolateImageFunction.h>
Public Types
typedef AveragerType::Pointer AveragerPointer
typedef anima::MCMWeightedAverager AveragerType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ContinuousIndexType ContinuousIndexType
typedef Superclass::IndexType IndexType
typedef Superclass::IndexValueType IndexValueType
typedef Superclass::InputImageType InputImageType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef Superclass::OutputType OutputType
typedef TInputImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::RealType RealType
typedef MCMLinearInterpolateImageFunction Self
typedef itk::InterpolateImageFunction< TInputImage, TCoordRep > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual OutputType EvaluateAtContinuousIndex (const ContinuousIndexType &index) const ITK_OVERRIDE
std::vector< AveragerPointer > & GetAveragers () const
virtual const char * GetNameOfClass () const
virtual void SetInputImage (const InputImageType *ptr) ITK_OVERRIDE
void SetReferenceOutputModel (MCModelPointer &model)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = Superclass::ImageDimension
Protected Member Functions
virtual bool CheckModelCompatibility (MCModelPointer &model)
Check if model can actually be interpolated.
unsigned int GetFreeWorkIndex () const
template<class T >
bool isZero (const itk::VariableLengthVector< T > &value) const
template<class T >
bool isZero (T &data) const
MCMLinearInterpolateImageFunction ()
virtual void ResetAveragePointers (MCModelPointer &model)
Resets averager pointers, can be overloaded to handle more models.
virtual void SetSpecificAveragerParameters (unsigned int threadIndex) const
Sets averager specific parameters if sub-classes are derived.
void TestModelsAdequation (MCModelPointer &inputModel, MCModelPointer &outputModel)
Tests if input and output models of the interpolator are compatible.
void UnlockWorkIndex (unsigned int index) const
virtual ~MCMLinearInterpolateImageFunction ()
Detailed Description
template<class TInputImage, class TCoordRep = double>
class anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >
Definition at line 12 of file animaMCMLinearInterpolateImageFunction.h.
Member Typedef Documentation
AveragerPointer
template<class TInputImage, class TCoordRep = double> typedef AveragerType::Pointer anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::AveragerPointer
Definition at line 51 of file animaMCMLinearInterpolateImageFunction.h.
AveragerType
template<class TInputImage, class TCoordRep = double> typedef anima::MCMWeightedAverager anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::AveragerType
Definition at line 50 of file animaMCMLinearInterpolateImageFunction.h.
ConstPointer
template<class TInputImage, class TCoordRep = double> typedef itk::SmartPointer<const Self> anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::ConstPointer
Definition at line 20 of file animaMCMLinearInterpolateImageFunction.h.
ContinuousIndexType
template<class TInputImage, class TCoordRep = double> typedef Superclass::ContinuousIndexType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::ContinuousIndexType
ContinuousIndex typedef support.
Definition at line 42 of file animaMCMLinearInterpolateImageFunction.h.
IndexType
template<class TInputImage, class TCoordRep = double> typedef Superclass::IndexType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::IndexType
Index typedef support.
Definition at line 38 of file animaMCMLinearInterpolateImageFunction.h.
IndexValueType
template<class TInputImage, class TCoordRep = double> typedef Superclass::IndexValueType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::IndexValueType
Definition at line 39 of file animaMCMLinearInterpolateImageFunction.h.
InputImageType
template<class TInputImage, class TCoordRep = double> typedef Superclass::InputImageType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::InputImageType
InputImageType typedef support.
Definition at line 30 of file animaMCMLinearInterpolateImageFunction.h.
MCModelPointer
template<class TInputImage, class TCoordRep = double> typedef MCModelType::Pointer anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::MCModelPointer
Definition at line 48 of file animaMCMLinearInterpolateImageFunction.h.
MCModelType
template<class TInputImage, class TCoordRep = double> typedef anima::MultiCompartmentModel anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::MCModelType
Definition at line 47 of file animaMCMLinearInterpolateImageFunction.h.
OutputType
template<class TInputImage, class TCoordRep = double> typedef Superclass::OutputType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::OutputType
Definition at line 44 of file animaMCMLinearInterpolateImageFunction.h.
PixelType
template<class TInputImage, class TCoordRep = double> typedef TInputImage::PixelType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::PixelType
Definition at line 31 of file animaMCMLinearInterpolateImageFunction.h.
Pointer
template<class TInputImage, class TCoordRep = double> typedef itk::SmartPointer<Self> anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::Pointer
Definition at line 19 of file animaMCMLinearInterpolateImageFunction.h.
RealType
template<class TInputImage, class TCoordRep = double> typedef Superclass::RealType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::RealType
Definition at line 32 of file animaMCMLinearInterpolateImageFunction.h.
Self
template<class TInputImage, class TCoordRep = double> typedef MCMLinearInterpolateImageFunction anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::Self
Standard class typedefs.
Definition at line 17 of file animaMCMLinearInterpolateImageFunction.h.
Superclass
template<class TInputImage, class TCoordRep = double> typedef itk::InterpolateImageFunction<TInputImage,TCoordRep> anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::Superclass
Definition at line 18 of file animaMCMLinearInterpolateImageFunction.h.
Constructor & Destructor Documentation
MCMLinearInterpolateImageFunction()
template<class TInputImage , class TCoordRep > anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::MCMLinearInterpolateImageFunction () protected
Constructor
Definition at line 20 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetInputImage().
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::GetAveragers(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetSpecificAveragerParameters().
~MCMLinearInterpolateImageFunction()
template<class TInputImage, class TCoordRep = double> virtual anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::~MCMLinearInterpolateImageFunction () inline protected virtual
Definition at line 71 of file animaMCMLinearInterpolateImageFunction.h.
Member Function Documentation
CheckModelCompatibility()
template<class TInputImage , class TCoordRep > bool anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::CheckModelCompatibility (MCModelPointer & model) protected virtual
Check if model can actually be interpolated.
Definition at line 82 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::Tensor, and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::TestModelsAdequation().
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::isZero(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::ResetAveragePointers().
CreateAnother()
template<class TInputImage, class TCoordRep = double> virtual::itk::LightObject::Pointer anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::CreateAnother (void) const
EvaluateAtContinuousIndex()
template<class TInputImage , class TCoordRep > MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::OutputType anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::EvaluateAtContinuousIndex (const ContinuousIndexType & index) const virtual
Evaluate the function at a ContinuousIndex position
Returns the linearly interpolated image intensity at a specified point position. No bounds checking is done. The point is assumed to lie within the image buffer.
ImageFunction::IsInsideBuffer() can be used to check bounds before calling the method.
Evaluate at image index position
Definition at line 178 of file animaMCMLinearInterpolateImageFunction.hxx.
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::UnlockWorkIndex().
GetAveragers()
template<class TInputImage, class TCoordRep = double> std::vector<AveragerPointer>& anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::GetAveragers () const inline
Definition at line 67 of file animaMCMLinearInterpolateImageFunction.h.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::MCMLinearInterpolateImageFunction().
GetFreeWorkIndex()
template<class TInputImage , class TCoordRep > unsigned int anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::GetFreeWorkIndex () const protected
Definition at line 123 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::UnlockWorkIndex().
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetSpecificAveragerParameters(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::TestModelsAdequation().
GetNameOfClass()
template<class TInputImage, class TCoordRep = double> virtual const char* anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::GetNameOfClass () const virtual
Run-time type information (and related methods).
isZero() [1/2]
template<class TInputImage, class TCoordRep = double> template<class T > bool anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::isZero (const itk::VariableLengthVector< T > & value) const inline protected
Definition at line 73 of file animaMCMLinearInterpolateImageFunction.h.
isZero() [2/2]
template<class TInputImage, class TCoordRep = double> template<class T > bool anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::isZero (T & data) const inline protected
Definition at line 85 of file animaMCMLinearInterpolateImageFunction.h.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::CheckModelCompatibility(), anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::ResetAveragePointers(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::TestModelsAdequation().
New()
template<class TInputImage, class TCoordRep = double> static Pointer anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::New () static
Method for creation through the object factory.
Referenced by main().
ResetAveragePointers()
template<class TInputImage , class TCoordRep > void anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::ResetAveragePointers (MCModelPointer & model) protected virtual
Resets averager pointers, can be overloaded to handle more models.
Definition at line 67 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::CheckModelCompatibility().
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::isZero(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetReferenceOutputModel().
SetInputImage()
template<class TInputImage , class TCoordRep > void anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetInputImage (const InputImageType * ptr) virtual
Definition at line 27 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetReferenceOutputModel().
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::MCMLinearInterpolateImageFunction().
SetReferenceOutputModel()
template<class TInputImage , class TCoordRep > void anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetReferenceOutputModel (MCModelPointer & model)
Definition at line 56 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::ResetAveragePointers().
Referenced by main(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetInputImage().
SetSpecificAveragerParameters()
template<class TInputImage, class TCoordRep = double> virtual void anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetSpecificAveragerParameters (unsigned int threadIndex) const inline protected virtual
Sets averager specific parameters if sub-classes are derived.
Definition at line 101 of file animaMCMLinearInterpolateImageFunction.h.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::GetFreeWorkIndex(), anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::MCMLinearInterpolateImageFunction(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::UnlockWorkIndex().
TestModelsAdequation()
template<class TInputImage , class TCoordRep > void anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::TestModelsAdequation (MCModelPointer & inputModel, MCModelPointer & outputModel) protected
Tests if input and output models of the interpolator are compatible.
Definition at line 94 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::GetFreeWorkIndex().
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::CheckModelCompatibility(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::isZero().
UnlockWorkIndex()
template<class TInputImage , class TCoordRep > void anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::UnlockWorkIndex (unsigned int index) const protected
Definition at line 155 of file animaMCMLinearInterpolateImageFunction.hxx.
References anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::EvaluateAtContinuousIndex().
Referenced by anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::GetFreeWorkIndex(), and anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::SetSpecificAveragerParameters().
Member Data Documentation
ImageDimension
template<class TInputImage, class TCoordRep = double> const unsigned int anima::MCMLinearInterpolateImageFunction< TInputImage, TCoordRep >::ImageDimension = Superclass::ImageDimension static
Dimension underlying input image.
Definition at line 35 of file animaMCMLinearInterpolateImageFunction.h.
The documentation for this class was generated from the following files:
animaMCMLinearInterpolateImageFunction.h
animaMCMLinearInterpolateImageFunction.hxx