ANIMA: anima::MCMFileWriter< PixelType, ImageDimension > Class Template Reference
anima::MCMFileWriter< PixelType, ImageDimension > Class Template Reference
#include <animaMCMFileWriter.h>
Public Types
typedef BaseOutputImageType::Pointer BaseOutputImagePointer
typedef itk::VectorImage< PixelType, ImageDimension > BaseOutputImageType
typedef InputImageType::Pointer InputImagePointer
typedef anima::MCMImage< PixelType, ImageDimension > InputImageType
typedef ModelType::Pointer ModelPointer
typedef anima::MultiCompartmentModel ModelType
Public Member Functions
MCMFileWriter ()
void SetFileName (std::string fileName)
void SetInputImage (InputImageType *input)
void Update ()
~MCMFileWriter ()
Detailed Description
template<class PixelType, unsigned int ImageDimension>
class anima::MCMFileWriter< PixelType, ImageDimension >
Definition at line 10 of file animaMCMFileWriter.h.
Member Typedef Documentation
BaseOutputImagePointer
template<class PixelType, unsigned int ImageDimension> typedef BaseOutputImageType::Pointer anima::MCMFileWriter< PixelType, ImageDimension >::BaseOutputImagePointer
Definition at line 19 of file animaMCMFileWriter.h.
BaseOutputImageType
template<class PixelType, unsigned int ImageDimension> typedef itk::VectorImage<PixelType, ImageDimension> anima::MCMFileWriter< PixelType, ImageDimension >::BaseOutputImageType
Definition at line 18 of file animaMCMFileWriter.h.
InputImagePointer
template<class PixelType, unsigned int ImageDimension> typedef InputImageType::Pointer anima::MCMFileWriter< PixelType, ImageDimension >::InputImagePointer
Definition at line 16 of file animaMCMFileWriter.h.
InputImageType
template<class PixelType, unsigned int ImageDimension> typedef anima::MCMImage<PixelType, ImageDimension> anima::MCMFileWriter< PixelType, ImageDimension >::InputImageType
Definition at line 15 of file animaMCMFileWriter.h.
ModelPointer
template<class PixelType, unsigned int ImageDimension> typedef ModelType::Pointer anima::MCMFileWriter< PixelType, ImageDimension >::ModelPointer
Definition at line 14 of file animaMCMFileWriter.h.
ModelType
template<class PixelType, unsigned int ImageDimension> typedef anima::MultiCompartmentModel anima::MCMFileWriter< PixelType, ImageDimension >::ModelType
Definition at line 13 of file animaMCMFileWriter.h.
Constructor & Destructor Documentation
MCMFileWriter()
template<class PixelType , unsigned int ImageDimension> anima::MCMFileWriter< PixelType, ImageDimension >::MCMFileWriter ()
Definition at line 13 of file animaMCMFileWriter.hxx.
~MCMFileWriter()
template<class PixelType , unsigned int ImageDimension> anima::MCMFileWriter< PixelType, ImageDimension >::~MCMFileWriter ()
Definition at line 20 of file animaMCMFileWriter.hxx.
Member Function Documentation
SetFileName()
template<class PixelType , unsigned int ImageDimension> void anima::MCMFileWriter< PixelType, ImageDimension >::SetFileName (std::string fileName)
Definition at line 27 of file animaMCMFileWriter.hxx.
Referenced by main(), anima::MCMFileWriter< PixelType, ImageDimension >::SetInputImage(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::WriteOutputs().
SetInputImage()
template<class PixelType, unsigned int ImageDimension> void anima::MCMFileWriter< PixelType, ImageDimension >::SetInputImage (InputImageType * input) inline
Definition at line 24 of file animaMCMFileWriter.h.
References anima::MCMFileWriter< PixelType, ImageDimension >::SetFileName(), and anima::MCMFileWriter< PixelType, ImageDimension >::Update().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::WriteOutputs().
Update()
template<class PixelType , unsigned int ImageDimension> void anima::MCMFileWriter< PixelType, ImageDimension >::Update ()
Definition at line 37 of file animaMCMFileWriter.hxx.
References anima::DDI, anima::FreeWater, anima::IsotropicRestrictedWater, anima::NODDI, anima::Stanisz, anima::StationaryWater, anima::Stick, anima::Tensor, and anima::Zeppelin.
Referenced by anima::MCMFileWriter< PixelType, ImageDimension >::SetInputImage(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::WriteOutputs().
The documentation for this class was generated from the following files:
animaMCMFileWriter.h
animaMCMFileWriter.hxx