ANIMA: anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
Multi-tensor correlation similarity measure as defined by Taquet et al, based on pairing of the individual compartments.
#include <animaMTPairingCorrelationImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, ImageDimension > ContinuousIndexType
typedef Superclass::CoordinateRepresentationType CoordinateRepresentationType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef MCModelType::Vector3DType GradientType
typedef Superclass::InputPointType InputPointType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef TFixedImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef MTPairingCorrelationImageToImageMetric Self
typedef BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > TFixedImage
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > TMovingImage
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ParametersValueType CoordinateRepresentationType
typedef Superclass::DerivativeType DerivativeType
typedef FixedImageType::ConstPointer FixedImageConstPointer
typedef FixedImageMaskType::ConstPointer FixedImageMaskConstPointer
typedef FixedImageMaskType::Pointer FixedImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(FixedImageDimension) > FixedImageMaskType
typedef FixedImageType::RegionType FixedImageRegionType
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > FixedImageType
typedef TransformType::InputPointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< MovingImageType, CoordinateRepresentationType > InterpolatorType
typedef Superclass::MeasureType MeasureType
enum ModelReorientationType
typedef MovingImageType::ConstPointer MovingImageConstPointer
typedef MovingImageMaskType::ConstPointer MovingImageMaskConstPointer
typedef MovingImageMaskType::Pointer MovingImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(MovingImageDimension) > MovingImageMaskType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > ::PixelType MovingImagePixelType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > MovingImageType
typedef TransformType::OutputPointType OutputPointType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef double RealType
typedef BaseOrientedModelImageToImageMetric Self
typedef itk::SingleValuedCostFunction Superclass
typedef TransformType::JacobianType TransformJacobianType
typedef TransformType::ParametersType TransformParametersType
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< CoordinateRepresentationType, itkGetStaticConstMacro(MovingImageDimension), itkGetStaticConstMacro(FixedImageDimension)> TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void PreComputeFixedValues ()
Public Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
Should not be used.
virtual const FixedImageType * GetFixedImage () const
virtual const FixedImageMaskType * GetFixedImageMask () const
virtual const FixedImageRegionType & GetFixedImageRegion () const
virtual const InterpolatorType * GetInterpolator () const
virtual ModelReorientationType GetModelRotation () const
virtual const MovingImageType * GetMovingImage () const
virtual const MovingImageMaskType * GetMovingImageMask () const
unsigned int GetNumberOfParameters (void) const ITK_OVERRIDE
virtual const unsigned long & GetNumberOfPixelsCounted () const
virtual const TransformType * GetTransform () const
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &value, DerivativeType &derivative) const ITK_OVERRIDE
virtual void Initialize ()
virtual void SetFixedImage (const FixedImageType *_arg)
virtual void SetFixedImageMask (FixedImageMaskType *_arg)
virtual void SetFixedImageMask (const FixedImageMaskType *_arg)
virtual void SetFixedImageRegion (FixedImageRegionType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetModelRotation (ModelReorientationType _arg)
virtual void SetMovingImage (const MovingImageType *_arg)
virtual void SetMovingImageMask (MovingImageMaskType *_arg)
virtual void SetMovingImageMask (const MovingImageMaskType *_arg)
virtual void SetTransform (TransformType *_arg)
void SetTransformParameters (const ParametersType &parameters) const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
bool CheckTensorCompatibility () const
double ComputeMapping (const std::vector< std::vector< double > > &refImageCompartmentWeights, const std::vector< std::vector< PixelType > > &refImageLogTensors, const std::vector< std::vector< double > > &movingImageCompartmentWeights, const std::vector< std::vector< PixelType > > &movingImageLogTensors) const
bool isZero (PixelType &vector) const
MTPairingCorrelationImageToImageMetric ()
virtual ~MTPairingCorrelationImageToImageMetric ()
Protected Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
BaseOrientedModelImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~BaseOrientedModelImageToImageMetric ()
Additional Inherited Members
Static Public Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
static const unsigned int FixedImageDimension
static const unsigned int MovingImageDimension
Protected Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
FixedImageConstPointer m_FixedImage
FixedImageMaskConstPointer m_FixedImageMask
InterpolatorPointer m_Interpolator
MovingImageConstPointer m_MovingImage
MovingImageMaskConstPointer m_MovingImageMask
unsigned long m_NumberOfPixelsCounted
vnl_matrix< double > m_OrientationMatrix
TransformPointer m_Transform
Detailed Description
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension>
class anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >
Multi-tensor correlation similarity measure as defined by Taquet et al, based on pairing of the individual compartments.
M. Taquet et al. "A Mathematical Framework for the Registration and Analysis of Multi-Fascicle Models for Population Studies of the Brain Microstructure". IEEE TMI 2014.
Definition at line 18 of file animaMTPairingCorrelationImageToImageMetric.h.
Member Typedef Documentation
ConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<const Self> anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ConstPointer
Definition at line 29 of file animaMTPairingCorrelationImageToImageMetric.h.
ContinuousIndexType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::ContinuousIndex<double, ImageDimension> anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ContinuousIndexType
Definition at line 49 of file animaMTPairingCorrelationImageToImageMetric.h.
CoordinateRepresentationType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::CoordinateRepresentationType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CoordinateRepresentationType
Definition at line 51 of file animaMTPairingCorrelationImageToImageMetric.h.
FixedImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageConstPointer anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageConstPointer
Definition at line 56 of file animaMTPairingCorrelationImageToImageMetric.h.
FixedImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageType
Definition at line 54 of file animaMTPairingCorrelationImageToImageMetric.h.
GradientType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Vector3DType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GradientType
Definition at line 33 of file animaMTPairingCorrelationImageToImageMetric.h.
InputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::InputPointType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::InputPointType
Definition at line 48 of file animaMTPairingCorrelationImageToImageMetric.h.
MCModelPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Pointer anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelPointer
Definition at line 32 of file animaMTPairingCorrelationImageToImageMetric.h.
MCModelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MultiCompartmentModel anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelType
Definition at line 31 of file animaMTPairingCorrelationImageToImageMetric.h.
MeasureType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MeasureType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType
Definition at line 53 of file animaMTPairingCorrelationImageToImageMetric.h.
MovingImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageConstPointer anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageConstPointer
Definition at line 57 of file animaMTPairingCorrelationImageToImageMetric.h.
MovingImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageType
Definition at line 55 of file animaMTPairingCorrelationImageToImageMetric.h.
OutputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::OutputPointType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::OutputPointType
Definition at line 47 of file animaMTPairingCorrelationImageToImageMetric.h.
PixelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef TFixedImage::PixelType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PixelType
Types transferred from the base class
Definition at line 42 of file animaMTPairingCorrelationImageToImageMetric.h.
Pointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<Self> anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Pointer
Definition at line 28 of file animaMTPairingCorrelationImageToImageMetric.h.
Self
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MTPairingCorrelationImageToImageMetric anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Self
Definition at line 26 of file animaMTPairingCorrelationImageToImageMetric.h.
Superclass
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef BaseOrientedModelImageToImageMetric<TFixedImage, TMovingImage > anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Superclass
Definition at line 27 of file animaMTPairingCorrelationImageToImageMetric.h.
TFixedImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TFixedImage
Standard class typedefs.
Definition at line 23 of file animaMTPairingCorrelationImageToImageMetric.h.
TMovingImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TMovingImage
Definition at line 24 of file animaMTPairingCorrelationImageToImageMetric.h.
TransformParametersType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformParametersType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformParametersType
Definition at line 46 of file animaMTPairingCorrelationImageToImageMetric.h.
TransformPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformPointer anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformPointer
Definition at line 45 of file animaMTPairingCorrelationImageToImageMetric.h.
TransformType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformType
Definition at line 44 of file animaMTPairingCorrelationImageToImageMetric.h.
Constructor & Destructor Documentation
MTPairingCorrelationImageToImageMetric()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MTPairingCorrelationImageToImageMetric () protected
Definition at line 16 of file animaMTPairingCorrelationImageToImageMetric.hxx.
References anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), and anima::MultiCompartmentModelCreator::SetNumberOfCompartments().
Referenced by anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MTPairingCorrelationImageToImageMetric().
~MTPairingCorrelationImageToImageMetric()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MTPairingCorrelationImageToImageMetric () inline protected virtual
Definition at line 66 of file animaMTPairingCorrelationImageToImageMetric.h.
References anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeMapping(), anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero(), and anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MTPairingCorrelationImageToImageMetric().
Member Function Documentation
CheckTensorCompatibility()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility () const protected
Definition at line 34 of file animaMTPairingCorrelationImageToImageMetric.hxx.
References anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
Referenced by anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MTPairingCorrelationImageToImageMetric(), and anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MTPairingCorrelationImageToImageMetric().
ComputeMapping()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> double anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeMapping (const std::vector< std::vector< double > > & refImageCompartmentWeights, const std::vector< std::vector< PixelType > > & refImageLogTensors, const std::vector< std::vector< double > > & movingImageCompartmentWeights, const std::vector< std::vector< PixelType > > & movingImageLogTensors) const protected
Definition at line 190 of file animaMTPairingCorrelationImageToImageMetric.hxx.
References anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
Referenced by anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), and anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MTPairingCorrelationImageToImageMetric().
CreateAnother()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual::itk::LightObject::Pointer anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CreateAnother (void) const
GetNameOfClass()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual const char* anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >.
GetValue()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Definition at line 58 of file animaMTPairingCorrelationImageToImageMetric.hxx.
References anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeMapping(), anima::GetTensorLogarithm(), anima::GetVectorRepresentation(), and PPD.
Referenced by anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility().
isZero()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero (PixelType & vector) const protected
Definition at line 262 of file animaMTPairingCorrelationImageToImageMetric.hxx.
References anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues().
Referenced by anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeMapping(), and anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MTPairingCorrelationImageToImageMetric().
New()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> static Pointer anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::New () static
Method for creation through the object factory.
PreComputeFixedValues()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues ()
Definition at line 278 of file animaMTPairingCorrelationImageToImageMetric.hxx.
References anima::GetTensorLogarithm(), and anima::GetVectorRepresentation().
Referenced by anima::MTPairingCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
The documentation for this class was generated from the following files:
animaMTPairingCorrelationImageToImageMetric.h
animaMTPairingCorrelationImageToImageMetric.hxx