ANIMA: anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput > Class Template Reference
anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput > Class Template Reference
Compute the mahalanobis images from the NABT model.
#include <animaComputeMahalanobisImagesFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > GaussianFunctionType
typedef itk::ImageRegionConstIterator< ImageTypeUC > ImageConstIteratorTypeUC
typedef ImageTypeUC::Pointer ImagePointerUC
typedef itk::Image< PixelTypeUC, 3 > ImageTypeUC
typedef itk::ImageRegionConstIterator< InputImageType > InputConstIteratorType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef TInputImage InputImageType
typedef itk::ImageRegionConstIterator< MaskImageType > MaskConstIteratorType
typedef TMaskImage MaskImageType
typedef itk::VariableLengthVector< double > MeasurementVectorType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutput OutputImageType
typedef itk::ImageRegionIterator< OutputImageType > OutputIteratorType
typedef OutputImageType::PixelType OutputPixelType
typedef unsigned char PixelTypeUC
typedef itk::SmartPointer< Self > Pointer
typedef itk::RescaleIntensityImageFilter< TInputImage, ImageTypeUC > RescaleFilterType
typedef ComputeMahalanobisImagesFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutput > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
OutputImagePointer GetOutputMahaCSF ()
OutputImagePointer GetOutputMahaGM ()
OutputImagePointer GetOutputMahaMaximum ()
OutputImagePointer GetOutputMahaMinimum ()
OutputImagePointer GetOutputMahaWM ()
std::vector< GaussianFunctionType::Pointer > GetSolutionGM ()
virtual bool GetVerbose ()
void SetGaussianModel (std::vector< GaussianFunctionType::Pointer > solution)
void SetInputImage1 (const InputImageType *image)
void SetInputImage2 (const InputImageType *image)
void SetInputImage3 (const InputImageType *image)
void SetMask (const TMaskImage *mask)
void SetOutputMahaCSFFilename (std::string filename)
void SetOutputMahaGMFilename (std::string filename)
void SetOutputMahaMaximumFilename (std::string filename)
void SetOutputMahaMinimumFilename (std::string filename)
void SetOutputMahaWMFilename (std::string filename)
void SetSolutionReadFilename (std::string filename)
void SetTol (const double tol)
virtual void SetVerbose (bool _arg)
void WriteOutputs ()
Static Public Member Functions
static void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
ComputeMahalanobisImagesFilter ()
InputImageType::ConstPointer GetInputImage1 ()
InputImageType::ConstPointer GetInputImage2 ()
InputImageType::ConstPointer GetInputImage3 ()
TMaskImage::ConstPointer GetMask ()
itk::DataObject::Pointer MakeOutput (unsigned int idx)
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~ComputeMahalanobisImagesFilter ()
Detailed Description
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage>
class anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >
Compute the mahalanobis images from the NABT model.
Definition at line 19 of file animaComputeMahalanobisImagesFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::SmartPointer<const Self> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ConstPointer
Definition at line 27 of file animaComputeMahalanobisImagesFilter.h.
GaussianFunctionType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GaussianFunctionType
Definition at line 62 of file animaComputeMahalanobisImagesFilter.h.
ImageConstIteratorTypeUC
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::ImageRegionConstIterator<ImageTypeUC> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ImageConstIteratorTypeUC
Definition at line 56 of file animaComputeMahalanobisImagesFilter.h.
ImagePointerUC
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef ImageTypeUC::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ImagePointerUC
Definition at line 55 of file animaComputeMahalanobisImagesFilter.h.
ImageTypeUC
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::Image<PixelTypeUC,3> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ImageTypeUC
Definition at line 54 of file animaComputeMahalanobisImagesFilter.h.
InputConstIteratorType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::ImageRegionConstIterator< InputImageType > anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::InputConstIteratorType
Definition at line 38 of file animaComputeMahalanobisImagesFilter.h.
InputImageConstPointer
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef InputImageType::ConstPointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::InputImageConstPointer
Definition at line 37 of file animaComputeMahalanobisImagesFilter.h.
InputImageType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef TInputImage anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::InputImageType
Type of the input image.
Definition at line 36 of file animaComputeMahalanobisImagesFilter.h.
MaskConstIteratorType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::ImageRegionConstIterator< MaskImageType > anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::MaskConstIteratorType
Definition at line 42 of file animaComputeMahalanobisImagesFilter.h.
MaskImageType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef TMaskImage anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::MaskImageType
Type of the mask image.
Definition at line 41 of file animaComputeMahalanobisImagesFilter.h.
MeasurementVectorType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::VariableLengthVector<double> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::MeasurementVectorType
Definition at line 61 of file animaComputeMahalanobisImagesFilter.h.
OutputImagePointer
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef OutputImageType::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::OutputImagePointer
Definition at line 46 of file animaComputeMahalanobisImagesFilter.h.
OutputImageRegionType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef Superclass::OutputImageRegionType anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 51 of file animaComputeMahalanobisImagesFilter.h.
OutputImageType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef TOutput anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::OutputImageType
Type of the output images.
Definition at line 45 of file animaComputeMahalanobisImagesFilter.h.
OutputIteratorType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::ImageRegionIterator< OutputImageType > anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::OutputIteratorType
Definition at line 47 of file animaComputeMahalanobisImagesFilter.h.
OutputPixelType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef OutputImageType::PixelType anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::OutputPixelType
Definition at line 48 of file animaComputeMahalanobisImagesFilter.h.
PixelTypeUC
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef unsigned char anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::PixelTypeUC
Definition at line 53 of file animaComputeMahalanobisImagesFilter.h.
Pointer
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::SmartPointer<Self> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::Pointer
Definition at line 26 of file animaComputeMahalanobisImagesFilter.h.
RescaleFilterType
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::RescaleIntensityImageFilter<TInputImage,ImageTypeUC> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::RescaleFilterType
Define filter types.
Definition at line 59 of file animaComputeMahalanobisImagesFilter.h.
Self
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef ComputeMahalanobisImagesFilter anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::Self
Standard class typedefs.
Definition at line 24 of file animaComputeMahalanobisImagesFilter.h.
Superclass
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> typedef itk::ImageToImageFilter< TInputImage, TOutput > anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::Superclass
Definition at line 25 of file animaComputeMahalanobisImagesFilter.h.
Constructor & Destructor Documentation
ComputeMahalanobisImagesFilter()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ComputeMahalanobisImagesFilter () inline protected
Definition at line 114 of file animaComputeMahalanobisImagesFilter.h.
References anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::MakeOutput().
~ComputeMahalanobisImagesFilter()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> virtual anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter () inline protected virtual
Definition at line 136 of file animaComputeMahalanobisImagesFilter.h.
References anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::BeforeThreadedGenerateData(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetInputImage1(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetInputImage2(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetInputImage3(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetMask(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::MakeOutput(), and anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TInputImage , typename TMaskImage , typename TOutput > void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::BeforeThreadedGenerateData () protected
Definition at line 151 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter().
CreateAnother()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> virtual::itk::LightObject::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::CreateAnother (void) const
eventCallback()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> static void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData) inline static
Definition at line 104 of file animaComputeMahalanobisImagesFilter.h.
GetInputImage1()
template<typename TInputImage , typename TMaskImage , typename TOutput > TInputImage::ConstPointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetInputImage1 () protected
Definition at line 33 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter().
GetInputImage2()
template<typename TInputImage , typename TMaskImage , typename TOutput > TInputImage::ConstPointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetInputImage2 () protected
Definition at line 40 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter().
GetInputImage3()
template<typename TInputImage , typename TMaskImage , typename TOutput > TInputImage::ConstPointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetInputImage3 () protected
Definition at line 47 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter().
GetMask()
template<typename TInputImage , typename TMaskImage , typename TOutput > TMaskImage::ConstPointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetMask () protected
Definition at line 54 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter().
GetNameOfClass()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> virtual const char* anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetOutputMahaCSF()
template<typename TInputImage , typename TMaskImage , typename TOutput > TOutput::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaCSF ()
Definition at line 92 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetSolutionGM().
GetOutputMahaGM()
template<typename TInputImage , typename TMaskImage , typename TOutput > TOutput::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaGM ()
Definition at line 97 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetSolutionGM().
GetOutputMahaMaximum()
template<typename TInputImage , typename TMaskImage , typename TOutput > TOutput::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaMaximum ()
Definition at line 112 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetSolutionGM().
GetOutputMahaMinimum()
template<typename TInputImage , typename TMaskImage , typename TOutput > TOutput::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaMinimum ()
Definition at line 107 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetSolutionGM().
GetOutputMahaWM()
template<typename TInputImage , typename TMaskImage , typename TOutput > TOutput::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaWM ()
Definition at line 102 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetSolutionGM().
GetSolutionGM()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> std::vector<GaussianFunctionType::Pointer> anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetSolutionGM () inline
Definition at line 87 of file animaComputeMahalanobisImagesFilter.h.
References anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaCSF(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaGM(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaMaximum(), anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaMinimum(), and anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetOutputMahaWM().
GetVerbose()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> virtual bool anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::GetVerbose () virtual
MakeOutput()
template<typename TInputImage , typename TMaskImage , typename TOutput > itk::DataObject::Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::MakeOutput (unsigned int idx) protected
Create the Output
Definition at line 62 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ComputeMahalanobisImagesFilter(), and anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter().
New()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> static Pointer anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::New () static
Method for creation through the object factory.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
SetGaussianModel()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetGaussianModel (std::vector< GaussianFunctionType::Pointer > solution) inline
Definition at line 86 of file animaComputeMahalanobisImagesFilter.h.
SetInputImage1()
template<typename TInputImage , typename TMaskImage , typename TOutput > void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetInputImage1 (const InputImageType * image)
The mri images.
Definition at line 9 of file animaComputeMahalanobisImagesFilter.hxx.
SetInputImage2()
template<typename TInputImage , typename TMaskImage , typename TOutput > void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetInputImage2 (const InputImageType * image)
Definition at line 15 of file animaComputeMahalanobisImagesFilter.hxx.
SetInputImage3()
template<typename TInputImage , typename TMaskImage , typename TOutput > void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetInputImage3 (const InputImageType * image)
Definition at line 21 of file animaComputeMahalanobisImagesFilter.hxx.
SetMask()
template<typename TInputImage , typename TMaskImage , typename TOutput > void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetMask (const TMaskImage * mask)
mask in which the segmentation will be performed
Definition at line 27 of file animaComputeMahalanobisImagesFilter.hxx.
SetOutputMahaCSFFilename()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetOutputMahaCSFFilename (std::string filename) inline
Definition at line 77 of file animaComputeMahalanobisImagesFilter.h.
SetOutputMahaGMFilename()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetOutputMahaGMFilename (std::string filename) inline
Definition at line 78 of file animaComputeMahalanobisImagesFilter.h.
SetOutputMahaMaximumFilename()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetOutputMahaMaximumFilename (std::string filename) inline
Definition at line 81 of file animaComputeMahalanobisImagesFilter.h.
SetOutputMahaMinimumFilename()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetOutputMahaMinimumFilename (std::string filename) inline
Definition at line 82 of file animaComputeMahalanobisImagesFilter.h.
References anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::WriteOutputs().
SetOutputMahaWMFilename()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetOutputMahaWMFilename (std::string filename) inline
Definition at line 79 of file animaComputeMahalanobisImagesFilter.h.
SetSolutionReadFilename()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetSolutionReadFilename (std::string filename) inline
Images for atlas initialisation
Definition at line 75 of file animaComputeMahalanobisImagesFilter.h.
SetTol()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetTol (const double tol) inline
Definition at line 96 of file animaComputeMahalanobisImagesFilter.h.
SetVerbose()
template<typename TInputImage, typename TMaskImage, typename TOutput = TInputImage> virtual void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetVerbose (bool _arg) virtual
ThreadedGenerateData()
template<typename TInputImage , typename TMaskImage , typename TOutput > void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 200 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::~ComputeMahalanobisImagesFilter().
WriteOutputs()
template<typename TInputImage , typename TMaskImage , typename TOutput > void anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::WriteOutputs ()
Definition at line 119 of file animaComputeMahalanobisImagesFilter.hxx.
Referenced by anima::ComputeMahalanobisImagesFilter< TInputImage, TMaskImage, TOutput >::SetOutputMahaMinimumFilename().
The documentation for this class was generated from the following files:
animaComputeMahalanobisImagesFilter.h
animaComputeMahalanobisImagesFilter.hxx