ANIMA: anima::ClassificationStrategy< TInputImage, TMaskImage > Class Template Reference
anima::ClassificationStrategy< TInputImage, TMaskImage > Class Template Reference
#include <animaClassificationStrategy.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > GaussianFunctionType
typedef GaussianREMEstimatorType::Pointer GaussianREMEstimatorPointerType
typedef GaussianREMEstimator< InputImageType, MaskImageType > GaussianREMEstimatorType
typedef TInputImage InputImageType
typedef TMaskImage MaskImageType
typedef itk::VariableLengthVector< double > MeasurementVectorType
typedef itk::SmartPointer< Self > Pointer
typedef ClassificationStrategy Self
typedef itk::ProcessObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual bool GetEM_Mode ()
RandomInitializer * getInitializer ()
return m_RandomInitializer object
virtual const char * GetNameOfClass () const
std::vector< unsigned int > GetNumberOfEstimators () const
std::vector< unsigned int > GetNumberOfIterations () const
bool GetSolutionMap (std::map< double, std::vector< GaussianFunctionType::Pointer > > &solution, std::map< double, std::vector< double > > &solutionAlpha, int step=-1)
return the solutions map for each step
virtual void SetEM_Mode (bool _arg)
void SetEstimator (GaussianREMEstimatorPointerType theValue)
set the estimation algorithm to use The algorithm must be already configured with the joint histogram
void SetInitializer (RandomInitializer::Pointer theValue)
set the m_RandomInitializer method
void SetNumberOfEstimators (std::vector< unsigned int > NumberOfEstimators)
void SetNumberOfIterations (std::vector< unsigned int > NumberOfIterations)
void SetStrategy (std::vector< unsigned int > &ems, std::vector< unsigned int > &iters)
void Update () ITK_OVERRIDE
executes the strategy
Static Public Member Functions
static Pointer New ()
Protected Member Functions
ClassificationStrategy (const Self &)
ClassificationStrategy ()
void operator= (const Self &)
bool sameModel (std::vector< GaussianFunctionType::Pointer > &mod1, std::vector< GaussianFunctionType::Pointer > &mod2)
compare two models
virtual ~ClassificationStrategy ()
Protected Attributes
bool m_EM_Mode
modification of processing if an em is being used
GaussianREMEstimatorPointerType m_Estimator
estimation algorithm object
std::vector< std::map< double, std::vector< double > > > m_ListAlphas
std::vector< std::map< double, std::vector< GaussianFunctionType::Pointer > > > m_ListGaussianModels
vector with all the solutions found in each step For EM's the double value stores the -likelihood, otherwise the cost function
std::vector< unsigned int > m_NumberOfEstimators
vector with the number of random estimations for each step
std::vector< unsigned int > m_NumberOfIterations
vector with the iterations for each step
RandomInitializer::Pointer m_RandomInitializer
Initialization object.
Detailed Description
template<typename TInputImage, typename TMaskImage>
class anima::ClassificationStrategy< TInputImage, TMaskImage >
Class classifying using a strategy for selecting best random intializations
See also
animaHierarchicalInitializer
Definition at line 15 of file animaClassificationStrategy.h.
Member Typedef Documentation
ConstPointer
template<typename TInputImage , typename TMaskImage > typedef itk::SmartPointer<const Self> anima::ClassificationStrategy< TInputImage, TMaskImage >::ConstPointer
Definition at line 23 of file animaClassificationStrategy.h.
GaussianFunctionType
template<typename TInputImage , typename TMaskImage > typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > anima::ClassificationStrategy< TInputImage, TMaskImage >::GaussianFunctionType
Definition at line 41 of file animaClassificationStrategy.h.
GaussianREMEstimatorPointerType
template<typename TInputImage , typename TMaskImage > typedef GaussianREMEstimatorType::Pointer anima::ClassificationStrategy< TInputImage, TMaskImage >::GaussianREMEstimatorPointerType
Definition at line 38 of file animaClassificationStrategy.h.
GaussianREMEstimatorType
template<typename TInputImage , typename TMaskImage > typedef GaussianREMEstimator<InputImageType,MaskImageType> anima::ClassificationStrategy< TInputImage, TMaskImage >::GaussianREMEstimatorType
Definition at line 37 of file animaClassificationStrategy.h.
InputImageType
template<typename TInputImage , typename TMaskImage > typedef TInputImage anima::ClassificationStrategy< TInputImage, TMaskImage >::InputImageType
Type of the input image.
Definition at line 29 of file animaClassificationStrategy.h.
MaskImageType
template<typename TInputImage , typename TMaskImage > typedef TMaskImage anima::ClassificationStrategy< TInputImage, TMaskImage >::MaskImageType
Type of the mask image.
Definition at line 35 of file animaClassificationStrategy.h.
MeasurementVectorType
template<typename TInputImage , typename TMaskImage > typedef itk::VariableLengthVector<double> anima::ClassificationStrategy< TInputImage, TMaskImage >::MeasurementVectorType
Definition at line 40 of file animaClassificationStrategy.h.
Pointer
template<typename TInputImage , typename TMaskImage > typedef itk::SmartPointer<Self> anima::ClassificationStrategy< TInputImage, TMaskImage >::Pointer
Definition at line 22 of file animaClassificationStrategy.h.
Self
template<typename TInputImage , typename TMaskImage > typedef ClassificationStrategy anima::ClassificationStrategy< TInputImage, TMaskImage >::Self
Standard class typedefs.
Definition at line 20 of file animaClassificationStrategy.h.
Superclass
template<typename TInputImage , typename TMaskImage > typedef itk::ProcessObject anima::ClassificationStrategy< TInputImage, TMaskImage >::Superclass
Definition at line 21 of file animaClassificationStrategy.h.
Constructor & Destructor Documentation
ClassificationStrategy() [1/2]
template<typename TInputImage , typename TMaskImage > anima::ClassificationStrategy< TInputImage, TMaskImage >::ClassificationStrategy (const Self &) protected
ClassificationStrategy() [2/2]
template<typename TInputImage , typename TMaskImage > anima::ClassificationStrategy< TInputImage, TMaskImage >::ClassificationStrategy () inline protected
Definition at line 88 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::m_EM_Mode, anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfEstimators, and anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfIterations.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::GetNumberOfEstimators().
~ClassificationStrategy()
template<typename TInputImage , typename TMaskImage > virtual anima::ClassificationStrategy< TInputImage, TMaskImage >::~ClassificationStrategy () inline protected virtual
Definition at line 95 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::sameModel().
Member Function Documentation
CreateAnother()
template<typename TInputImage , typename TMaskImage > virtual::itk::LightObject::Pointer anima::ClassificationStrategy< TInputImage, TMaskImage >::CreateAnother (void) const
GetEM_Mode()
template<typename TInputImage , typename TMaskImage > virtual bool anima::ClassificationStrategy< TInputImage, TMaskImage >::GetEM_Mode () virtual
getInitializer()
template<typename TInputImage , typename TMaskImage > RandomInitializer* anima::ClassificationStrategy< TInputImage, TMaskImage >::getInitializer () inline
return m_RandomInitializer object
Definition at line 63 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::GetSolutionMap(), anima::ClassificationStrategy< TInputImage, TMaskImage >::m_RandomInitializer, and anima::ClassificationStrategy< TInputImage, TMaskImage >::SetStrategy().
GetNameOfClass()
template<typename TInputImage , typename TMaskImage > virtual const char* anima::ClassificationStrategy< TInputImage, TMaskImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfEstimators()
template<typename TInputImage , typename TMaskImage > std::vector<unsigned int> anima::ClassificationStrategy< TInputImage, TMaskImage >::GetNumberOfEstimators () const inline
Definition at line 80 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::ClassificationStrategy(), anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfEstimators, and anima::ClassificationStrategy< TInputImage, TMaskImage >::operator=().
GetNumberOfIterations()
template<typename TInputImage , typename TMaskImage > std::vector<unsigned int> anima::ClassificationStrategy< TInputImage, TMaskImage >::GetNumberOfIterations () const inline
Definition at line 77 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfIterations.
GetSolutionMap()
template<typename TInputImage , typename TMaskImage > bool anima::ClassificationStrategy< TInputImage, TMaskImage >::GetSolutionMap (std::map< double, std::vector< GaussianFunctionType::Pointer > > & solution, std::map< double, std::vector< double > > & solutionAlpha, int step = -1)
return the solutions map for each step
Parameters
step solutions of the step we want to get if step is set to -1, the last step will be returned
Definition at line 133 of file animaClassificationStrategy.hxx.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::getInitializer().
New()
template<typename TInputImage , typename TMaskImage > static Pointer anima::ClassificationStrategy< TInputImage, TMaskImage >::New () static
Method for creation through the object factory.
operator=()
template<typename TInputImage , typename TMaskImage > void anima::ClassificationStrategy< TInputImage, TMaskImage >::operator= (const Self &) protected
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::GetNumberOfEstimators().
sameModel()
template<typename TInputImage , typename TMaskImage > bool anima::ClassificationStrategy< TInputImage, TMaskImage >::sameModel (std::vector< GaussianFunctionType::Pointer > & mod1, std::vector< GaussianFunctionType::Pointer > & mod2) protected
compare two models
Returns
false if differents
Definition at line 174 of file animaClassificationStrategy.hxx.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::~ClassificationStrategy().
SetEM_Mode()
template<typename TInputImage , typename TMaskImage > virtual void anima::ClassificationStrategy< TInputImage, TMaskImage >::SetEM_Mode (bool _arg) virtual
SetEstimator()
template<typename TInputImage , typename TMaskImage > void anima::ClassificationStrategy< TInputImage, TMaskImage >::SetEstimator (GaussianREMEstimatorPointerType theValue) inline
set the estimation algorithm to use The algorithm must be already configured with the joint histogram
Definition at line 52 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::m_Estimator.
SetInitializer()
template<typename TInputImage , typename TMaskImage > void anima::ClassificationStrategy< TInputImage, TMaskImage >::SetInitializer (RandomInitializer::Pointer theValue) inline
set the m_RandomInitializer method
Warning
this object won't be recopied so don't delete it
Definition at line 58 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::m_RandomInitializer.
SetNumberOfEstimators()
template<typename TInputImage , typename TMaskImage > void anima::ClassificationStrategy< TInputImage, TMaskImage >::SetNumberOfEstimators (std::vector< unsigned int > NumberOfEstimators) inline
Definition at line 79 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfEstimators.
SetNumberOfIterations()
template<typename TInputImage , typename TMaskImage > void anima::ClassificationStrategy< TInputImage, TMaskImage >::SetNumberOfIterations (std::vector< unsigned int > NumberOfIterations) inline
Definition at line 76 of file animaClassificationStrategy.h.
References anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfIterations.
SetStrategy()
template<typename TInputImage , typename TMaskImage > void anima::ClassificationStrategy< TInputImage, TMaskImage >::SetStrategy (std::vector< unsigned int > & ems, std::vector< unsigned int > & iters)
Definition at line 154 of file animaClassificationStrategy.hxx.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::getInitializer().
Update()
template<typename TInputImage , typename TMaskImage > void anima::ClassificationStrategy< TInputImage, TMaskImage >::Update ()
executes the strategy
Returns
false if error
Definition at line 7 of file animaClassificationStrategy.hxx.
Member Data Documentation
m_EM_Mode
template<typename TInputImage , typename TMaskImage > bool anima::ClassificationStrategy< TInputImage, TMaskImage >::m_EM_Mode protected
modification of processing if an em is being used
Definition at line 127 of file animaClassificationStrategy.h.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::ClassificationStrategy().
m_Estimator
template<typename TInputImage , typename TMaskImage > GaussianREMEstimatorPointerType anima::ClassificationStrategy< TInputImage, TMaskImage >::m_Estimator protected
estimation algorithm object
Definition at line 105 of file animaClassificationStrategy.h.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::SetEstimator().
m_ListAlphas
template<typename TInputImage , typename TMaskImage > std::vector< std::map<double, std::vector<double> > > anima::ClassificationStrategy< TInputImage, TMaskImage >::m_ListAlphas protected
Definition at line 115 of file animaClassificationStrategy.h.
m_ListGaussianModels
template<typename TInputImage , typename TMaskImage > std::vector< std::map<double, std::vector<GaussianFunctionType::Pointer> > > anima::ClassificationStrategy< TInputImage, TMaskImage >::m_ListGaussianModels protected
vector with all the solutions found in each step For EM's the double value stores the -likelihood, otherwise the cost function
Definition at line 114 of file animaClassificationStrategy.h.
m_NumberOfEstimators
template<typename TInputImage , typename TMaskImage > std::vector<unsigned int> anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfEstimators protected
vector with the number of random estimations for each step
Definition at line 123 of file animaClassificationStrategy.h.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::ClassificationStrategy(), anima::ClassificationStrategy< TInputImage, TMaskImage >::GetNumberOfEstimators(), and anima::ClassificationStrategy< TInputImage, TMaskImage >::SetNumberOfEstimators().
m_NumberOfIterations
template<typename TInputImage , typename TMaskImage > std::vector<unsigned int> anima::ClassificationStrategy< TInputImage, TMaskImage >::m_NumberOfIterations protected
vector with the iterations for each step
Definition at line 119 of file animaClassificationStrategy.h.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::ClassificationStrategy(), anima::ClassificationStrategy< TInputImage, TMaskImage >::GetNumberOfIterations(), and anima::ClassificationStrategy< TInputImage, TMaskImage >::SetNumberOfIterations().
m_RandomInitializer
template<typename TInputImage , typename TMaskImage > RandomInitializer::Pointer anima::ClassificationStrategy< TInputImage, TMaskImage >::m_RandomInitializer protected
Initialization object.
Definition at line 109 of file animaClassificationStrategy.h.
Referenced by anima::ClassificationStrategy< TInputImage, TMaskImage >::getInitializer(), and anima::ClassificationStrategy< TInputImage, TMaskImage >::SetInitializer().
The documentation for this class was generated from the following files:
animaClassificationStrategy.h
animaClassificationStrategy.hxx