ANIMA: anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference
anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference
#include <animaODFResampleImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageType InputImageType
typedef Superclass::InputPixelType InputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef ODFResampleImageFilter Self
typedef OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType > Superclass
Public Types inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
typedef itk::SmartPointer< const Self > ConstPointer
typedef InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef TOutputImage::DirectionType DirectionType
typedef GeometryImageType::Pointer GeometryImagePointer
typedef itk::Image< unsigned char, itkGetStaticConstMacro(ImageDimension)> GeometryImageType
typedef InputImageType::Pointer InputImagePointer
typedef TImageType InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::PixelType InputPixelType
typedef InputImageType::PointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< InputImageType, TInterpolatorPrecisionType > InterpolatorType
typedef TOutputImage::PointType OriginPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef TOutputImage::RegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef InterpolatorType::PointType PointType
typedef TOutputImage::RegionType RegionType
typedef OrientedModelBaseResampleImageFilter Self
typedef TOutputImage::SpacingType SpacingType
typedef anima::MaskedImageToImageFilter< TImageType, TImageType > Superclass
typedef TImageType TOutputImage
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> TransformType
Public Types inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TImageType ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< TImageType, TImageType > Superclass
typedef itk::ImageSource< TImageType >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Public Member Functions inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
virtual bool GetFiniteStrainReorientation ()
virtual InterpolatorType * GetInterpolator ()
virtual const DirectionType & GetOutputDirection () const
virtual const RegionType & GetOutputLargestPossibleRegion () const
virtual const OriginPointType & GetOutputOrigin () const
virtual const SpacingType & GetOutputSpacing () const
itkGetObjectMacro (Transform, TransformType) virtual void SetInterpolator(InterpolatorPointer _arg)
virtual void SetFiniteStrainReorientation (bool _arg)
virtual void SetOutputDirection (DirectionType _arg)
virtual void SetOutputLargestPossibleRegion (RegionType _arg)
virtual void SetOutputOrigin (OriginPointType _arg)
virtual void SetOutputSpacing (SpacingType _arg)
virtual void SetTransform (TransformType *_arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = InputImageType::ImageDimension
Static Public Attributes inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
static const unsigned int ImageDimension = InputImageType::ImageDimension
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
ODFResampleImageFilter ()
virtual void ReorientInterpolatedModel (const InputPixelType &interpolatedModel, vnl_matrix< double > &modelOrientationMatrix, InputPixelType &rotatedModel, itk::ThreadIdType threadId) ITK_OVERRIDE
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
virtual ~ODFResampleImageFilter ()
Protected Member Functions inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
vnl_matrix< double > ComputeLinearJacobianMatrix ()
void ComputeLocalJacobianMatrix (InputIndexType &index, vnl_matrix< double > &reorientationMatrix)
virtual void ComputeRotationParametersFromReorientationMatrix (vnl_matrix< double > &reorientationMatrix, vnl_matrix< double > &modelOrientationMatrix)
virtual void GenerateInputRequestedRegion () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
virtual unsigned int GetOutputVectorLength ()
virtual void InitializeInterpolator ()
Initializes the default interpolator, might change in derived classes.
template<class T >
void InitializeZeroPixel (itk::VariableLengthVector< T > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<class T >
void InitializeZeroPixel (T &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
template<class T >
bool isZero (itk::VariableLengthVector< T > &dataVec)
template<class T >
bool isZero (T &data)
void LinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
void NonLinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
OrientedModelBaseResampleImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~OrientedModelBaseResampleImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (TImageType *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (TImageType *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TImageType, typename TInterpolatorPrecisionType = float>
class anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >
Definition at line 11 of file animaODFResampleImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<const Self> anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ConstPointer
Definition at line 20 of file animaODFResampleImageFilter.h.
InputImageType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef Superclass::InputImageType anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputImageType
Definition at line 23 of file animaODFResampleImageFilter.h.
InputPixelType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef Superclass::InputPixelType anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputPixelType
Definition at line 22 of file animaODFResampleImageFilter.h.
Pointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<Self> anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Pointer
Definition at line 19 of file animaODFResampleImageFilter.h.
Self
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef ODFResampleImageFilter anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Self
Standard class typedefs.
Definition at line 16 of file animaODFResampleImageFilter.h.
Superclass
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef OrientedModelBaseResampleImageFilter<TImageType,TInterpolatorPrecisionType> anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Superclass
Definition at line 18 of file animaODFResampleImageFilter.h.
Constructor & Destructor Documentation
ODFResampleImageFilter()
template<typename TImageType , typename TInterpolatorPrecisionType = float> anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ODFResampleImageFilter () inline protected
Definition at line 33 of file animaODFResampleImageFilter.h.
~ODFResampleImageFilter()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~ODFResampleImageFilter () inline protected virtual
Definition at line 38 of file animaODFResampleImageFilter.h.
References anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData(), and anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 12 of file animaODFResampleImageFilter.hxx.
References anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
Referenced by anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~ODFResampleImageFilter().
CreateAnother()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual::itk::LightObject::Pointer anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::CreateAnother (void) const
GetNameOfClass()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const char* anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
New()
template<typename TImageType , typename TInterpolatorPrecisionType = float> static Pointer anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::New () static
Method for creation through the object factory.
ReorientInterpolatedModel()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel (const InputPixelType & interpolatedModel, vnl_matrix< double > & modelOrientationMatrix, InputPixelType & orientedModel, itk::ThreadIdType threadId) protected virtual
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
Implements anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 32 of file animaODFResampleImageFilter.hxx.
References anima::EstimateLocalODFRotationMatrix(), and anima::GetEulerAnglesFromRotationMatrix().
Referenced by anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData(), and anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~ODFResampleImageFilter().
Member Data Documentation
ImageDimension
template<typename TImageType , typename TInterpolatorPrecisionType = float> const unsigned int anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ImageDimension = InputImageType::ImageDimension static
Definition at line 24 of file animaODFResampleImageFilter.h.
The documentation for this class was generated from the following files:
animaODFResampleImageFilter.h
animaODFResampleImageFilter.hxx