ANIMA: anima::NODDICompartment Class Reference
anima::NODDICompartment Class Reference
#include <animaNODDICompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef NODDICompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
const Matrix3DType & GetDiffusionTensor () ITK_OVERRIDE
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType & GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType & GetParametersAsVector () ITK_OVERRIDE
virtual ListType & GetParameterUpperBounds () ITK_OVERRIDE
virtual ListType & GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
bool GetTensorCompatible () ITK_OVERRIDE
void SetAxialDiffusivity (double num) ITK_OVERRIDE
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
void SetEstimateExtraAxonalFraction (bool arg)
void SetEstimateOrientationConcentration (bool arg)
void SetExtraAxonalFraction (double num) ITK_OVERRIDE
void SetOrientationConcentration (double num) ITK_OVERRIDE
void SetOrientationPhi (double num) ITK_OVERRIDE
void SetOrientationTheta (double num) ITK_OVERRIDE
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
virtual double GetTissueRadius ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-2, double absoluteTolerance=1.0e-8)
Tests equality to another compartment up to a constant (relative and absolute tolerances)
virtual void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform)
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
virtual void SetTissueRadius (double num)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
NODDICompartment ()
void UpdateKappaValues ()
Update quantities that depend on kappa.
void UpdateSignals (double bValue, const Vector3DType &gradient)
Compute intra- and extra-axonal signals and useful signals for derivatives.
virtual ~NODDICompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
ListType m_JacobianVector
Vector holding current jacobian value.
ListType m_ParametersLowerBoundsVector
Vector holding current parameters lower bounds.
ListType m_ParametersUpperBoundsVector
Vector holding current parameters upper bounds.
ListType m_ParametersVector
Vector holding current parameters vector.
Static Protected Attributes inherited from anima::BaseCompartment
static const unsigned int m_SpaceDimension = 3
Detailed Description
Definition at line 9 of file animaNODDICompartment.h.
Member Typedef Documentation
BasePointer
typedef Superclass::Pointer anima::NODDICompartment::BasePointer
Definition at line 15 of file animaNODDICompartment.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::NODDICompartment::ConstPointer
Definition at line 17 of file animaNODDICompartment.h.
Matrix3DType
typedef Superclass::Matrix3DType anima::NODDICompartment::Matrix3DType
Definition at line 20 of file animaNODDICompartment.h.
ModelOutputVectorType
typedef Superclass::ModelOutputVectorType anima::NODDICompartment::ModelOutputVectorType
Definition at line 18 of file animaNODDICompartment.h.
Pointer
typedef itk::SmartPointer<Self> anima::NODDICompartment::Pointer
Definition at line 16 of file animaNODDICompartment.h.
Self
typedef NODDICompartment anima::NODDICompartment::Self
Definition at line 13 of file animaNODDICompartment.h.
Superclass
typedef BaseCompartment anima::NODDICompartment::Superclass
Definition at line 14 of file animaNODDICompartment.h.
Vector3DType
typedef Superclass::Vector3DType anima::NODDICompartment::Vector3DType
Definition at line 19 of file animaNODDICompartment.h.
Constructor & Destructor Documentation
NODDICompartment()
anima::NODDICompartment::NODDICompartment () inline protected
Definition at line 63 of file animaNODDICompartment.h.
~NODDICompartment()
virtual anima::NODDICompartment::~NODDICompartment () inline protected virtual
Definition at line 89 of file animaNODDICompartment.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::NODDICompartment::CreateAnother (void) const
GetCompartmentSize()
unsigned int anima::NODDICompartment::GetCompartmentSize () virtual
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implements anima::BaseCompartment.
Definition at line 406 of file animaNODDICompartment.cxx.
Referenced by GetCompartmentVector(), and SetCompartmentVector().
GetCompartmentType()
DiffusionModelCompartmentType anima::NODDICompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 28 of file animaNODDICompartment.h.
References anima::NODDI.
GetCompartmentVector()
NODDICompartment::ModelOutputVectorType & anima::NODDICompartment::GetCompartmentVector () virtual
Get compartment overall description vector, mainly for writing, should be self-contained.
Implements anima::BaseCompartment.
Definition at line 431 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetCompartmentSize(), anima::BaseCompartment::GetExtraAxonalFraction(), anima::BaseCompartment::GetOrientationConcentration(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::m_CompartmentVector, anima::BaseCompartment::m_SpaceDimension, and anima::TransformSphericalToCartesianCoordinates().
GetDiffusionTensor()
const NODDICompartment::Matrix3DType & anima::NODDICompartment::GetDiffusionTensor () virtual
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented from anima::BaseCompartment.
Definition at line 459 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetExtraAxonalFraction(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::m_DiffusionTensor, anima::BaseCompartment::m_SpaceDimension, anima::TransformSphericalToCartesianCoordinates(), and UpdateKappaValues().
GetFourierTransformedDiffusionProfile()
double anima::NODDICompartment::GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 94 of file animaNODDICompartment.cxx.
References anima::GetBValueFromAcquisitionParameters(), anima::BaseCompartment::GetExtraAxonalFraction(), and UpdateSignals().
GetFractionalAnisotropy()
double anima::NODDICompartment::GetFractionalAnisotropy () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 502 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::GetExtraAxonalFraction().
GetLogDiffusionProfile()
double anima::NODDICompartment::GetLogDiffusionProfile (const Vector3DType & sample) virtual
Implements anima::BaseCompartment.
Definition at line 186 of file animaNODDICompartment.cxx.
References anima::ComputeScalarProduct(), anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetExtraAxonalFraction(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::TransformSphericalToCartesianCoordinates(), and UpdateKappaValues().
GetNameOfClass()
virtual const char* anima::NODDICompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseCompartment.
GetNumberOfParameters()
unsigned int anima::NODDICompartment::GetNumberOfParameters () virtual
Number of optimized parameters: smaller than total number of parameters.
Implements anima::BaseCompartment.
Definition at line 411 of file animaNODDICompartment.cxx.
Referenced by GetParameterLowerBounds(), GetParametersAsVector(), GetParameterUpperBounds(), GetSignalAttenuationJacobian(), and SetParametersFromVector().
GetParameterLowerBounds()
NODDICompartment::ListType & anima::NODDICompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 307 of file animaNODDICompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_ParametersLowerBoundsVector, anima::MCMDiffusivityLowerBound, and anima::MCMZeroLowerBound.
GetParametersAsVector()
NODDICompartment::ListType & anima::NODDICompartment::GetParametersAsVector () virtual
Implements anima::BaseCompartment.
Definition at line 281 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetExtraAxonalFraction(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationConcentration(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), and anima::BaseCompartment::m_ParametersVector.
GetParameterUpperBounds()
NODDICompartment::ListType & anima::NODDICompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 319 of file animaNODDICompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_ParametersUpperBoundsVector, anima::MCMAzimuthAngleUpperBound, anima::MCMConcentrationUpperBound, anima::MCMDiffusivityUpperBound, anima::MCMFractionUpperBound, and anima::MCMPolarAngleUpperBound.
GetSignalAttenuationJacobian()
NODDICompartment::ListType & anima::NODDICompartment::GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 103 of file animaNODDICompartment.cxx.
References anima::ComputeScalarProduct(), anima::BaseCompartment::GetAxialDiffusivity(), anima::GetBValueFromAcquisitionParameters(), anima::BaseCompartment::GetExtraAxonalFraction(), GetNumberOfParameters(), anima::BaseCompartment::GetOrientationConcentration(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::BaseCompartment::m_JacobianVector, anima::TransformSphericalToCartesianCoordinates(), and UpdateSignals().
GetTensorCompatible()
bool anima::NODDICompartment::GetTensorCompatible () inline virtual
Reimplemented from anima::BaseCompartment.
Definition at line 58 of file animaNODDICompartment.h.
New()
static Pointer anima::NODDICompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
SetAxialDiffusivity()
void anima::NODDICompartment::SetAxialDiffusivity (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 247 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::SetAxialDiffusivity().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
SetCompartmentVector()
void anima::NODDICompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) virtual
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implements anima::BaseCompartment.
Definition at line 373 of file animaNODDICompartment.cxx.
References GetCompartmentSize(), anima::BaseCompartment::m_SpaceDimension, SetAxialDiffusivity(), SetExtraAxonalFraction(), SetOrientationConcentration(), SetOrientationPhi(), SetOrientationTheta(), and anima::TransformCartesianToSphericalCoordinates().
SetEstimateAxialDiffusivity()
void anima::NODDICompartment::SetEstimateAxialDiffusivity (bool arg)
Definition at line 355 of file animaNODDICompartment.cxx.
SetEstimateExtraAxonalFraction()
void anima::NODDICompartment::SetEstimateExtraAxonalFraction (bool arg)
Definition at line 364 of file animaNODDICompartment.cxx.
SetEstimateOrientationConcentration()
void anima::NODDICompartment::SetEstimateOrientationConcentration (bool arg)
Definition at line 346 of file animaNODDICompartment.cxx.
SetExtraAxonalFraction()
void anima::NODDICompartment::SetExtraAxonalFraction (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 238 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetExtraAxonalFraction(), and anima::BaseCompartment::SetExtraAxonalFraction().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
SetOrientationConcentration()
void anima::NODDICompartment::SetOrientationConcentration (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 228 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetOrientationConcentration(), and anima::BaseCompartment::SetOrientationConcentration().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
SetOrientationPhi()
void anima::NODDICompartment::SetOrientationPhi (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 219 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetOrientationPhi(), and anima::BaseCompartment::SetOrientationPhi().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
SetOrientationTheta()
void anima::NODDICompartment::SetOrientationTheta (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 210 of file animaNODDICompartment.cxx.
References anima::BaseCompartment::GetOrientationTheta(), and anima::BaseCompartment::SetOrientationTheta().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
SetParametersFromVector()
void anima::NODDICompartment::SetParametersFromVector (const ListType & params) virtual
Various methods for optimization parameters setting and getting.
Implements anima::BaseCompartment.
Definition at line 256 of file animaNODDICompartment.cxx.
References GetNumberOfParameters(), SetAxialDiffusivity(), SetExtraAxonalFraction(), SetOrientationConcentration(), SetOrientationPhi(), and SetOrientationTheta().
UpdateKappaValues()
void anima::NODDICompartment::UpdateKappaValues () protected
Update quantities that depend on kappa.
Definition at line 488 of file animaNODDICompartment.cxx.
References anima::EvaluateDawsonIntegral(), anima::BaseCompartment::GetOrientationConcentration(), and anima::GetStandardWatsonSHCoefficients().
Referenced by GetDiffusionTensor(), GetLogDiffusionProfile(), and UpdateSignals().
UpdateSignals()
void anima::NODDICompartment::UpdateSignals (double bValue, const Vector3DType & gradient) protected
Compute intra- and extra-axonal signals and useful signals for derivatives.
Definition at line 12 of file animaNODDICompartment.cxx.
References anima::ComputeNorm(), anima::ComputeScalarProduct(), anima::BaseCompartment::GetAxialDiffusivity(), anima::BaseCompartment::GetExtraAxonalFraction(), anima::BaseCompartment::GetOrientationConcentration(), anima::BaseCompartment::GetOrientationPhi(), anima::BaseCompartment::GetOrientationTheta(), anima::KummerFunction(), anima::TransformSphericalToCartesianCoordinates(), and UpdateKappaValues().
Referenced by GetFourierTransformedDiffusionProfile(), and GetSignalAttenuationJacobian().
The documentation for this class was generated from the following files:
animaNODDICompartment.h
animaNODDICompartment.cxx