ANIMA: anima::PyramidImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::PyramidImageFilter< TInputImage, TOutputImage > Class Template Reference
Computes a pyramid of images using the provided resampler to perform resampling.
#include <animaPyramidImageFilter.h>
Public Types
typedef BaseResamplerType::Pointer BaseResamplerPointer
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > BaseResamplerType
typedef itk::SmartPointer< const Self > ConstPointer
typedef TInputImage InputImageType
typedef InputImageType::IOPixelType InputInternalScalarType
typedef OutputImageType::Pointer OutputImagePointer
typedef TOutputImage OutputImageType
typedef OutputImageType::IOPixelType OutputInternalScalarType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::RegionType RegionType
typedef itk::Image< typename TInputImage::IOPixelType, TInputImage::ImageDimension > ScalarInputImageType
typedef ScalarOutputImageType::Pointer ScalarOutputImagePointer
typedef itk::Image< typename TInputImage::IOPixelType, TInputImage::ImageDimension > ScalarOutputImageType
typedef PyramidImageFilter Self
typedef InputImageType::SpacingType SpacingType
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::VectorImage< typename TInputImage::IOPixelType, TInputImage::ImageDimension > VectorInputImageType
typedef VectorOutputImageType::Pointer VectorOutputImagePointer
typedef itk::VectorImage< typename TInputImage::IOPixelType, TInputImage::ImageDimension > VectorOutputImageType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfLevels () const
virtual void SetImageResampler (BaseResamplerType *_arg)
virtual void SetNumberOfLevels (unsigned int _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
double AnisotropyMeasure (SpacingType &sp, std::vector< bool > &changeableSizes)
void CheckNumberOfLevels ()
void CreateLevelImage (unsigned int level)
void CreateLevelVectorImage (unsigned int level)
void GenerateData () ITK_OVERRIDE
PyramidImageFilter ()
virtual ~PyramidImageFilter ()
Detailed Description
template<class TInputImage, class TOutputImage>
class anima::PyramidImageFilter< TInputImage, TOutputImage >
Computes a pyramid of images using the provided resampler to perform resampling.
Computes a pyramid of images, taking into account voxel anisotropy when dividing dimensions. Requires an external image resampler provided by the user to resample images
Definition at line 17 of file animaPyramidImageFilter.h.
Member Typedef Documentation
BaseResamplerPointer
template<class TInputImage , class TOutputImage > typedef BaseResamplerType::Pointer anima::PyramidImageFilter< TInputImage, TOutputImage >::BaseResamplerPointer
Definition at line 52 of file animaPyramidImageFilter.h.
BaseResamplerType
template<class TInputImage , class TOutputImage > typedef itk::ImageToImageFilter<TInputImage,TOutputImage> anima::PyramidImageFilter< TInputImage, TOutputImage >::BaseResamplerType
Definition at line 51 of file animaPyramidImageFilter.h.
ConstPointer
template<class TInputImage , class TOutputImage > typedef itk::SmartPointer<const Self> anima::PyramidImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 25 of file animaPyramidImageFilter.h.
InputImageType
template<class TInputImage , class TOutputImage > typedef TInputImage anima::PyramidImageFilter< TInputImage, TOutputImage >::InputImageType
Definition at line 33 of file animaPyramidImageFilter.h.
InputInternalScalarType
template<class TInputImage , class TOutputImage > typedef InputImageType::IOPixelType anima::PyramidImageFilter< TInputImage, TOutputImage >::InputInternalScalarType
Definition at line 34 of file animaPyramidImageFilter.h.
OutputImagePointer
template<class TInputImage , class TOutputImage > typedef OutputImageType::Pointer anima::PyramidImageFilter< TInputImage, TOutputImage >::OutputImagePointer
Definition at line 39 of file animaPyramidImageFilter.h.
OutputImageType
template<class TInputImage , class TOutputImage > typedef TOutputImage anima::PyramidImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 38 of file animaPyramidImageFilter.h.
OutputInternalScalarType
template<class TInputImage , class TOutputImage > typedef OutputImageType::IOPixelType anima::PyramidImageFilter< TInputImage, TOutputImage >::OutputInternalScalarType
Definition at line 40 of file animaPyramidImageFilter.h.
Pointer
template<class TInputImage , class TOutputImage > typedef itk::SmartPointer<Self> anima::PyramidImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 24 of file animaPyramidImageFilter.h.
RegionType
template<class TInputImage , class TOutputImage > typedef InputImageType::RegionType anima::PyramidImageFilter< TInputImage, TOutputImage >::RegionType
Definition at line 35 of file animaPyramidImageFilter.h.
ScalarInputImageType
template<class TInputImage , class TOutputImage > typedef itk::Image<typename TInputImage::IOPixelType,TInputImage::ImageDimension> anima::PyramidImageFilter< TInputImage, TOutputImage >::ScalarInputImageType
Definition at line 42 of file animaPyramidImageFilter.h.
ScalarOutputImagePointer
template<class TInputImage , class TOutputImage > typedef ScalarOutputImageType::Pointer anima::PyramidImageFilter< TInputImage, TOutputImage >::ScalarOutputImagePointer
Definition at line 46 of file animaPyramidImageFilter.h.
ScalarOutputImageType
template<class TInputImage , class TOutputImage > typedef itk::Image<typename TInputImage::IOPixelType,TInputImage::ImageDimension> anima::PyramidImageFilter< TInputImage, TOutputImage >::ScalarOutputImageType
Definition at line 45 of file animaPyramidImageFilter.h.
Self
template<class TInputImage , class TOutputImage > typedef PyramidImageFilter anima::PyramidImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 22 of file animaPyramidImageFilter.h.
SpacingType
template<class TInputImage , class TOutputImage > typedef InputImageType::SpacingType anima::PyramidImageFilter< TInputImage, TOutputImage >::SpacingType
Definition at line 36 of file animaPyramidImageFilter.h.
Superclass
template<class TInputImage , class TOutputImage > typedef itk::ImageToImageFilter<TInputImage,TOutputImage> anima::PyramidImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 23 of file animaPyramidImageFilter.h.
VectorInputImageType
template<class TInputImage , class TOutputImage > typedef itk::VectorImage<typename TInputImage::IOPixelType,TInputImage::ImageDimension> anima::PyramidImageFilter< TInputImage, TOutputImage >::VectorInputImageType
Definition at line 43 of file animaPyramidImageFilter.h.
VectorOutputImagePointer
template<class TInputImage , class TOutputImage > typedef VectorOutputImageType::Pointer anima::PyramidImageFilter< TInputImage, TOutputImage >::VectorOutputImagePointer
Definition at line 49 of file animaPyramidImageFilter.h.
VectorOutputImageType
template<class TInputImage , class TOutputImage > typedef itk::VectorImage<typename TInputImage::IOPixelType,TInputImage::ImageDimension> anima::PyramidImageFilter< TInputImage, TOutputImage >::VectorOutputImageType
Definition at line 48 of file animaPyramidImageFilter.h.
Constructor & Destructor Documentation
PyramidImageFilter()
template<class TInputImage , class TOutputImage > anima::PyramidImageFilter< TInputImage, TOutputImage >::PyramidImageFilter () protected
Definition at line 16 of file animaPyramidImageFilter.hxx.
References anima::PyramidImageFilter< TInputImage, TOutputImage >::AnisotropyMeasure().
~PyramidImageFilter()
template<class TInputImage , class TOutputImage > virtual anima::PyramidImageFilter< TInputImage, TOutputImage >::~PyramidImageFilter () inline protected virtual
Definition at line 62 of file animaPyramidImageFilter.h.
References anima::PyramidImageFilter< TInputImage, TOutputImage >::AnisotropyMeasure(), anima::PyramidImageFilter< TInputImage, TOutputImage >::CheckNumberOfLevels(), anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelImage(), anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelVectorImage(), and anima::PyramidImageFilter< TInputImage, TOutputImage >::GenerateData().
Member Function Documentation
AnisotropyMeasure()
template<class TInputImage , class TOutputImage > double anima::PyramidImageFilter< TInputImage, TOutputImage >::AnisotropyMeasure (SpacingType & sp, std::vector< bool > & changeableSizes) protected
Definition at line 25 of file animaPyramidImageFilter.hxx.
References anima::PyramidImageFilter< TInputImage, TOutputImage >::CheckNumberOfLevels().
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::PyramidImageFilter(), and anima::PyramidImageFilter< TInputImage, TOutputImage >::~PyramidImageFilter().
CheckNumberOfLevels()
template<class TInputImage , class TOutputImage > void anima::PyramidImageFilter< TInputImage, TOutputImage >::CheckNumberOfLevels () protected
Definition at line 56 of file animaPyramidImageFilter.hxx.
References anima::PyramidImageFilter< TInputImage, TOutputImage >::GenerateData().
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::AnisotropyMeasure(), and anima::PyramidImageFilter< TInputImage, TOutputImage >::~PyramidImageFilter().
CreateAnother()
template<class TInputImage , class TOutputImage > virtual::itk::LightObject::Pointer anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
CreateLevelImage()
template<class TInputImage , class TOutputImage > void anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelImage (unsigned int level) protected
Definition at line 273 of file animaPyramidImageFilter.hxx.
References anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetTransform().
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelVectorImage(), and anima::PyramidImageFilter< TInputImage, TOutputImage >::~PyramidImageFilter().
CreateLevelVectorImage()
template<class TInputImage , class TOutputImage > void anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelVectorImage (unsigned int level) protected
Definition at line 210 of file animaPyramidImageFilter.hxx.
References anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelImage(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetOutputOrigin().
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::GenerateData(), and anima::PyramidImageFilter< TInputImage, TOutputImage >::~PyramidImageFilter().
GenerateData()
template<class TInputImage , class TOutputImage > void anima::PyramidImageFilter< TInputImage, TOutputImage >::GenerateData () protected
Definition at line 185 of file animaPyramidImageFilter.hxx.
References anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelVectorImage().
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::CheckNumberOfLevels(), and anima::PyramidImageFilter< TInputImage, TOutputImage >::~PyramidImageFilter().
GetNameOfClass()
template<class TInputImage , class TOutputImage > virtual const char* anima::PyramidImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfLevels()
template<class TInputImage , class TOutputImage > virtual unsigned int anima::PyramidImageFilter< TInputImage, TOutputImage >::GetNumberOfLevels () const virtual
New()
template<class TInputImage , class TOutputImage > static Pointer anima::PyramidImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
SetImageResampler()
template<class TInputImage , class TOutputImage > virtual void anima::PyramidImageFilter< TInputImage, TOutputImage >::SetImageResampler (BaseResamplerType * _arg) virtual
SetNumberOfLevels()
template<class TInputImage , class TOutputImage > virtual void anima::PyramidImageFilter< TInputImage, TOutputImage >::SetNumberOfLevels (unsigned int _arg) virtual
Set/Get the number of multi-resolution levels.
The documentation for this class was generated from the following files:
animaPyramidImageFilter.h
animaPyramidImageFilter.hxx