ANIMA: anima::GammaMixtureT2RelaxometryCostFunction Class Reference
anima::GammaMixtureT2RelaxometryCostFunction Class Reference
#include <animaGammaMixtureT2RelaxometryCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef GammaMixtureT2RelaxometryCostFunction Self
typedef SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
vnl_matrix< double > & GetLambda_pinv ()
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetConstrainedParameters (bool _arg)
void SetEPGSignalValues (std::vector< std::vector< double > > &input)
void SetMeanParam (std::vector< double > &input)
virtual void SetNEchoes (int _arg)
virtual void SetNumSteps (unsigned int _arg)
void SetSignalValues (std::vector< double > &input)
void SetT2WorkingValues (std::vector< double > &input)
void SetVarParam (std::vector< double > &input)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
GammaMixtureT2RelaxometryCostFunction ()
virtual ~GammaMixtureT2RelaxometryCostFunction ()
Detailed Description
Definition at line 9 of file animaGammaMixtureT2RelaxometryCostFunction.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::GammaMixtureT2RelaxometryCostFunction::ConstPointer
Definition at line 17 of file animaGammaMixtureT2RelaxometryCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::GammaMixtureT2RelaxometryCostFunction::DerivativeType
Definition at line 25 of file animaGammaMixtureT2RelaxometryCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::GammaMixtureT2RelaxometryCostFunction::MeasureType
Definition at line 24 of file animaGammaMixtureT2RelaxometryCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::GammaMixtureT2RelaxometryCostFunction::ParametersType
Definition at line 26 of file animaGammaMixtureT2RelaxometryCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::GammaMixtureT2RelaxometryCostFunction::Pointer
Definition at line 16 of file animaGammaMixtureT2RelaxometryCostFunction.h.
Self
typedef GammaMixtureT2RelaxometryCostFunction anima::GammaMixtureT2RelaxometryCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaGammaMixtureT2RelaxometryCostFunction.h.
Superclass
typedef SingleValuedCostFunction anima::GammaMixtureT2RelaxometryCostFunction::Superclass
Definition at line 15 of file animaGammaMixtureT2RelaxometryCostFunction.h.
Constructor & Destructor Documentation
GammaMixtureT2RelaxometryCostFunction()
anima::GammaMixtureT2RelaxometryCostFunction::GammaMixtureT2RelaxometryCostFunction () protected
Definition at line 16 of file animaGammaMixtureT2RelaxometryCostFunction.cxx.
~GammaMixtureT2RelaxometryCostFunction()
virtual anima::GammaMixtureT2RelaxometryCostFunction::~GammaMixtureT2RelaxometryCostFunction () inline protected virtual
Definition at line 60 of file animaGammaMixtureT2RelaxometryCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::GammaMixtureT2RelaxometryCostFunction::CreateAnother (void) const
GetDerivative()
void anima::GammaMixtureT2RelaxometryCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 116 of file animaGammaMixtureT2RelaxometryCostFunction.cxx.
References GetNumberOfParameters().
GetLambda_pinv()
vnl_matrix<double>& anima::GammaMixtureT2RelaxometryCostFunction::GetLambda_pinv () inline
Definition at line 56 of file animaGammaMixtureT2RelaxometryCostFunction.h.
GetNameOfClass()
virtual const char* anima::GammaMixtureT2RelaxometryCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::GammaMixtureT2RelaxometryCostFunction::GetNumberOfParameters () const inline
Definition at line 46 of file animaGammaMixtureT2RelaxometryCostFunction.h.
Referenced by GetDerivative().
GetValue()
GammaMixtureT2RelaxometryCostFunction::MeasureType anima::GammaMixtureT2RelaxometryCostFunction::GetValue (const ParametersType & parameters) const virtual
The measure type shall be used for computing the cost function value to observe convergence Parameters are set as {theta_1,theta_2,theta_3} for unconstrained estimation Or {theta_2} for constrained
Definition at line 20 of file animaGammaMixtureT2RelaxometryCostFunction.cxx.
New()
static Pointer anima::GammaMixtureT2RelaxometryCostFunction::New () static
Referenced by anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
SetConstrainedParameters()
virtual void anima::GammaMixtureT2RelaxometryCostFunction::SetConstrainedParameters (bool _arg) virtual
SetEPGSignalValues()
void anima::GammaMixtureT2RelaxometryCostFunction::SetEPGSignalValues (std::vector< std::vector< double > > & input) inline
Definition at line 43 of file animaGammaMixtureT2RelaxometryCostFunction.h.
SetMeanParam()
void anima::GammaMixtureT2RelaxometryCostFunction::SetMeanParam (std::vector< double > & input) inline
Definition at line 39 of file animaGammaMixtureT2RelaxometryCostFunction.h.
SetNEchoes()
virtual void anima::GammaMixtureT2RelaxometryCostFunction::SetNEchoes (int _arg) virtual
SetNumSteps()
virtual void anima::GammaMixtureT2RelaxometryCostFunction::SetNumSteps (unsigned int _arg) virtual
SetSignalValues()
void anima::GammaMixtureT2RelaxometryCostFunction::SetSignalValues (std::vector< double > & input) inline
Definition at line 44 of file animaGammaMixtureT2RelaxometryCostFunction.h.
SetT2WorkingValues()
void anima::GammaMixtureT2RelaxometryCostFunction::SetT2WorkingValues (std::vector< double > & input) inline
Definition at line 42 of file animaGammaMixtureT2RelaxometryCostFunction.h.
SetVarParam()
void anima::GammaMixtureT2RelaxometryCostFunction::SetVarParam (std::vector< double > & input) inline
Definition at line 40 of file animaGammaMixtureT2RelaxometryCostFunction.h.
The documentation for this class was generated from the following files:
animaGammaMixtureT2RelaxometryCostFunction.h
animaGammaMixtureT2RelaxometryCostFunction.cxx