ANIMA: anima::DistortionCorrectionBMRegistrationMethod< TInputImageType > Class Template Reference
anima::DistortionCorrectionBMRegistrationMethod< TInputImageType > Class Template Reference
#include <animaDistortionCorrectionBMRegistrationMethod.h>
Public Types
typedef Superclass::AffineTransformType AffineTransformType
typedef Superclass::AgregatorScalarType AgregatorScalarType
typedef Superclass::AgregatorType AgregatorType
typedef Superclass::BlockMatcherType BlockMatcherType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DisplacementFieldTransformPointer DisplacementFieldTransformPointer
typedef Superclass::DisplacementFieldTransformType DisplacementFieldTransformType
typedef Superclass::ImageScalarType ImageScalarType
typedef Superclass::InputImagePointer InputImagePointer
typedef Superclass::InputImageType InputImageType
typedef itk::SmartPointer< Self > Pointer
typedef DistortionCorrectionBMRegistrationMethod Self
typedef BaseBMRegistrationMethod< TInputImageType > Superclass
typedef Superclass::SVFTransformType SVFTransformType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BaseBMRegistrationMethod< TInputImageType >
typedef AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform< typename AgregatorType::ScalarType, TInputImageType::ImageDimension > AffineTransformType
typedef AgregatorType::ScalarType AgregatorScalarType
typedef anima::BaseTransformAgregator< TInputImageType::ImageDimension > AgregatorType
typedef AgregatorType::BaseInputTransformType BaseInputTransformType
typedef AgregatorType::BaseOutputTransformType BaseOutputTransformType
typedef anima::BaseBlockMatcher< TInputImageType > BlockMatcherType
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ProcessObject::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef rpi::DisplacementFieldTransform< AgregatorScalarType, TInputImageType::ImageDimension > DisplacementFieldTransformType
typedef TInputImageType::IOPixelType ImageScalarType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImageType InputImageType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TInputImageType::ImageDimension > MaskImageType
typedef itk::SmartPointer< Self > Pointer
typedef ResamplerFilterType::Pointer ResamplerFilterPointer
typedef itk::ImageToImageFilter< InputImageType, InputImageType > ResamplerFilterType
typedef BaseBMRegistrationMethod Self
typedef itk::ProcessObject Superclass
typedef SVFTransformType::Pointer SVFTransformPointer
typedef itk::StationaryVelocityFieldTransform< AgregatorScalarType, TInputImageType::ImageDimension > SVFTransformType
typedef TransformOutputType::Pointer TransformOutputPointer
typedef itk::DataObjectDecorator< TransformType > TransformOutputType
typedef TransformType::Pointer TransformPointer
typedef AgregatorType::BaseOutputTransformType TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetCurrentTransform (TransformPointer _arg)
Public Member Functions inherited from anima::BaseBMRegistrationMethod< TInputImageType >
void Abort ()
virtual AgregatorType * GetAgregator ()
virtual unsigned int GetBCHCompositionOrder ()
BlockMatcherType * GetBlockMatcher ()
virtual unsigned int GetExponentiationOrder ()
virtual InputImageType * GetFixedImage ()
TransformPointer & GetInitialTransform ()
virtual unsigned int GetMaximumIterations ()
virtual double GetMinimalTransformError ()
virtual InputImageType * GetMovingImage ()
ResamplerFilterPointer & GetMovingImageResampler ()
TransformOutputType * GetOutput ()
ResamplerFilterPointer & GetReferenceImageResampler ()
virtual double GetSVFElasticRegSigma ()
virtual bool GetVerboseProgression ()
virtual DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx) ITK_OVERRIDE
virtual void SetAgregator (AgregatorType *_arg)
virtual void SetBCHCompositionOrder (unsigned int _arg)
void SetBlockMatcher (BlockMatcherType *matcher)
virtual void SetExponentiationOrder (unsigned int _arg)
virtual void SetFixedImage (InputImageType *_arg)
virtual void SetInitialTransform (TransformPointer _arg)
virtual void SetMaximumIterations (unsigned int _arg)
virtual void SetMinimalTransformError (double _arg)
virtual void SetMovingImage (InputImageType *_arg)
void SetMovingImageResampler (ResamplerFilterType *filter)
void SetReferenceImageResampler (ResamplerFilterType *filter)
virtual void SetSVFElasticRegSigma (double _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual bool ComposeAddOnWithTransform (TransformPointer &computedTransform, TransformType *addOn) ITK_OVERRIDE
DistortionCorrectionBMRegistrationMethod ()
virtual void PerformOneIteration (InputImageType *refImage, InputImageType *movingImage, TransformPointer &addOn) ITK_OVERRIDE
virtual void ResampleImages (TransformType *currentTransform, InputImagePointer &refImage, InputImagePointer &movingImage) ITK_OVERRIDE
virtual void SetupTransform (TransformPointer &optimizedTransform) ITK_OVERRIDE
virtual ~DistortionCorrectionBMRegistrationMethod ()
Protected Member Functions inherited from anima::BaseBMRegistrationMethod< TInputImageType >
BaseBMRegistrationMethod ()
void GenerateData () ITK_OVERRIDE
virtual void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
void StartOptimization ()
virtual ~BaseBMRegistrationMethod ()
Detailed Description
template<typename TInputImageType>
class anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >
Definition at line 8 of file animaDistortionCorrectionBMRegistrationMethod.h.
Member Typedef Documentation
AffineTransformType
template<typename TInputImageType > typedef Superclass::AffineTransformType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::AffineTransformType
Definition at line 25 of file animaDistortionCorrectionBMRegistrationMethod.h.
AgregatorScalarType
template<typename TInputImageType > typedef Superclass::AgregatorScalarType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::AgregatorScalarType
Definition at line 24 of file animaDistortionCorrectionBMRegistrationMethod.h.
AgregatorType
template<typename TInputImageType > typedef Superclass::AgregatorType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::AgregatorType
Definition at line 23 of file animaDistortionCorrectionBMRegistrationMethod.h.
BlockMatcherType
template<typename TInputImageType > typedef Superclass::BlockMatcherType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::BlockMatcherType
Definition at line 22 of file animaDistortionCorrectionBMRegistrationMethod.h.
ConstPointer
template<typename TInputImageType > typedef itk::SmartPointer<const Self> anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ConstPointer
Definition at line 15 of file animaDistortionCorrectionBMRegistrationMethod.h.
DisplacementFieldTransformPointer
template<typename TInputImageType > typedef Superclass::DisplacementFieldTransformPointer anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::DisplacementFieldTransformPointer
Definition at line 28 of file animaDistortionCorrectionBMRegistrationMethod.h.
DisplacementFieldTransformType
template<typename TInputImageType > typedef Superclass::DisplacementFieldTransformType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::DisplacementFieldTransformType
Definition at line 27 of file animaDistortionCorrectionBMRegistrationMethod.h.
ImageScalarType
template<typename TInputImageType > typedef Superclass::ImageScalarType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ImageScalarType
Definition at line 17 of file animaDistortionCorrectionBMRegistrationMethod.h.
InputImagePointer
template<typename TInputImageType > typedef Superclass::InputImagePointer anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::InputImagePointer
Definition at line 19 of file animaDistortionCorrectionBMRegistrationMethod.h.
InputImageType
template<typename TInputImageType > typedef Superclass::InputImageType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::InputImageType
Definition at line 18 of file animaDistortionCorrectionBMRegistrationMethod.h.
Pointer
template<typename TInputImageType > typedef itk::SmartPointer<Self> anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::Pointer
Definition at line 14 of file animaDistortionCorrectionBMRegistrationMethod.h.
Self
template<typename TInputImageType > typedef DistortionCorrectionBMRegistrationMethod anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::Self
Standard class typedefs.
Definition at line 12 of file animaDistortionCorrectionBMRegistrationMethod.h.
Superclass
template<typename TInputImageType > typedef BaseBMRegistrationMethod<TInputImageType> anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::Superclass
Definition at line 13 of file animaDistortionCorrectionBMRegistrationMethod.h.
SVFTransformType
template<typename TInputImageType > typedef Superclass::SVFTransformType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::SVFTransformType
Definition at line 26 of file animaDistortionCorrectionBMRegistrationMethod.h.
TransformPointer
template<typename TInputImageType > typedef Superclass::TransformPointer anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::TransformPointer
Definition at line 21 of file animaDistortionCorrectionBMRegistrationMethod.h.
TransformType
template<typename TInputImageType > typedef Superclass::TransformType anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::TransformType
Definition at line 20 of file animaDistortionCorrectionBMRegistrationMethod.h.
Constructor & Destructor Documentation
DistortionCorrectionBMRegistrationMethod()
template<typename TInputImageType > anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::DistortionCorrectionBMRegistrationMethod () inline protected
Definition at line 38 of file animaDistortionCorrectionBMRegistrationMethod.h.
Referenced by anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::~DistortionCorrectionBMRegistrationMethod().
~DistortionCorrectionBMRegistrationMethod()
template<typename TInputImageType > virtual anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::~DistortionCorrectionBMRegistrationMethod () inline protected virtual
Definition at line 39 of file animaDistortionCorrectionBMRegistrationMethod.h.
References anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ComposeAddOnWithTransform(), anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::DistortionCorrectionBMRegistrationMethod(), anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::PerformOneIteration(), anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ResampleImages(), and anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::SetupTransform().
Member Function Documentation
ComposeAddOnWithTransform()
template<typename TInputImageType > bool anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ComposeAddOnWithTransform (TransformPointer & computedTransform, TransformType * addOn) protected virtual
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 156 of file animaDistortionCorrectionBMRegistrationMethod.hxx.
References anima::GetSVFExponential().
Referenced by anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::~DistortionCorrectionBMRegistrationMethod().
CreateAnother()
template<typename TInputImageType > virtual::itk::LightObject::Pointer anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::CreateAnother (void) const
GetNameOfClass()
template<typename TInputImageType > virtual const char* anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
New()
template<typename TInputImageType > static Pointer anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::New () static
PerformOneIteration()
template<typename TInputImageType > void anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::PerformOneIteration (InputImageType * refImage, InputImageType * movingImage, TransformPointer & addOn) protected virtual
Implements anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 198 of file animaDistortionCorrectionBMRegistrationMethod.hxx.
References anima::BaseBMRegistrationMethod< TInputImageType >::SetMovingImage().
Referenced by anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::~DistortionCorrectionBMRegistrationMethod().
ResampleImages()
template<typename TInputImageType > void anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::ResampleImages (TransformType * currentTransform, InputImagePointer & refImage, InputImagePointer & movingImage) protected virtual
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 36 of file animaDistortionCorrectionBMRegistrationMethod.hxx.
References anima::ResampleImageFilter< TInputImage, TOutputImage, TInterpolatorPrecisionType >::SetTransform().
Referenced by anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::~DistortionCorrectionBMRegistrationMethod().
SetCurrentTransform()
template<typename TInputImageType > virtual void anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::SetCurrentTransform (TransformPointer _arg) virtual
SetupTransform()
template<typename TInputImageType > void anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::SetupTransform (TransformPointer & optimizedTransform) protected virtual
Reimplemented from anima::BaseBMRegistrationMethod< TInputImageType >.
Definition at line 21 of file animaDistortionCorrectionBMRegistrationMethod.hxx.
Referenced by anima::DistortionCorrectionBMRegistrationMethod< TInputImageType >::~DistortionCorrectionBMRegistrationMethod().
The documentation for this class was generated from the following files:
animaDistortionCorrectionBMRegistrationMethod.h
animaDistortionCorrectionBMRegistrationMethod.hxx