ANIMA: anima::Graph3DFilter< TInput, TOutput > Class Template Reference
anima::Graph3DFilter< TInput, TOutput > Class Template Reference
Class allowing the decimation of the images if necessary (if 3D graph size causes memory problems). This class just launchs NLinksFilter with appropriate image sizes.
#include <animaGraph3DFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::VariableSizeMatrix< NumericType > FloatVariableSizeMatrixType
typedef Graph< double, double, double > GraphType
typedef itk::ImageRegionIterator< TSeedProba > ImageIteratorTypeProba
typedef TSeedProba::Pointer ImagePointerProba
typedef TInput::ConstPointer InputImageConstPointer
typedef TInput::Pointer InputImagePointer
typedef TInput::PixelType InputPixelType
typedef itk::ImageRegionConstIterator< TInput > InRegionConstIteratorType
typedef itk::ImageRegionIterator< TInput > InRegionIteratorType
typedef itk::ImageRegionConstIterator< TMask > MaskRegionConstIteratorType
typedef itk::ImageRegionIterator< TMask > MaskRegionIteratorType
typedef double NumericType
typedef TOutput::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::ImageRegionIterator< TOutput > OutputIteratorType
typedef TOutput::PixelType OutputPixelType
typedef double PixelTypeD
typedef unsigned char PixelTypeUC
typedef itk::SmartPointer< Self > Pointer
typedef itk::ResampleImageFilter< TSeedProba, TSeedProba > ResampleImageFilterFloatType
typedef itk::ResampleImageFilter< TMask, TMask > ResampleImageFilterMaskType
typedef itk::ResampleImageFilter< TInput, TInput > ResampleImageFilterType
typedef TSeedProba::PixelType SeedProbaPixelType
typedef Graph3DFilter Self
typedef itk::ImageToImageFilter< TInput, TOutput > Superclass
typedef itk::Image< PixelTypeUC, 3 > TMask
typedef TMask::Pointer TMaskPointer
typedef itk::IdentityTransform< double, 3 > TransformType
typedef itk::Image< PixelTypeD, 3 > TSeedProba
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
TMask::Pointer Dilate (const TMask *input, const TMask *mask)
virtual const char * GetNameOfClass () const
OutputImagePointer GetOutput ()
OutputImagePointer GetOutputBackground ()
virtual float GetSigma ()
virtual bool GetUseSpectralGradient ()
virtual bool GetVerbose ()
void SetInputImage (unsigned int i, const TInput *image)
void SetInputSeedProbaSinks (const TSeedProba *mask)
void SetInputSeedProbaSources (const TSeedProba *mask)
void SetMask (const TMask *mask)
void SetMatFilename (std::string mat)
void SetMatrix (FloatVariableSizeMatrixType mat)
virtual void SetSigma (float _arg)
void SetTol (const double tol)
virtual void SetUseSpectralGradient (bool _arg)
virtual void SetVerbose (bool _arg)
TMask::Pointer Upsample (const TMask *input, TMask::SizeType upSize, TMask::DirectionType outputDirection, TMask::PointType outputOrigin)
Static Public Member Functions
static Pointer New ()
Protected Types
typedef NLinksFilter< TInput, TMask > NLinksFilterType
Protected Member Functions
bool CheckMemory ()
void FindDownsampleFactor ()
void GenerateData () ITK_OVERRIDE
TInput::ConstPointer GetInputImage1 ()
TInput::ConstPointer GetInputImage2 ()
TInput::ConstPointer GetInputImage3 ()
TInput::ConstPointer GetInputImage4 ()
TInput::ConstPointer GetInputImage5 ()
TSeedProba::ConstPointer GetInputSeedProbaSinks ()
TSeedProba::ConstPointer GetInputSeedProbaSources ()
TMask::ConstPointer GetMask ()
std::string GetMatFilename (void)
FloatVariableSizeMatrixType GetMatrix (void)
Graph3DFilter ()
void InitResampleFilters ()
itk::DataObject::Pointer MakeOutput (unsigned int idx)
void ProcessDownsampledGraphCut (int current_count)
void ProcessGraphCut ()
virtual ~Graph3DFilter ()
Protected Attributes
NLinksFilterType::Pointer m_NLinksFilter
NLinksFilterType::Pointer m_NLinksFilterDecim
ResampleImageFilterType::Pointer m_Resample1
ResampleImageFilterType::Pointer m_Resample2
ResampleImageFilterType::Pointer m_Resample3
ResampleImageFilterType::Pointer m_Resample4
ResampleImageFilterType::Pointer m_Resample5
ResampleImageFilterMaskType::Pointer m_ResampleMask
ResampleImageFilterFloatType::Pointer m_ResampleSinks
ResampleImageFilterFloatType::Pointer m_ResampleSources
Detailed Description
template<typename TInput, typename TOutput>
class anima::Graph3DFilter< TInput, TOutput >
Class allowing the decimation of the images if necessary (if 3D graph size causes memory problems). This class just launchs NLinksFilter with appropriate image sizes.
Definition at line 23 of file animaGraph3DFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<const Self> anima::Graph3DFilter< TInput, TOutput >::ConstPointer
Definition at line 31 of file animaGraph3DFilter.h.
FloatVariableSizeMatrixType
template<typename TInput , typename TOutput > typedef itk::VariableSizeMatrix<NumericType> anima::Graph3DFilter< TInput, TOutput >::FloatVariableSizeMatrixType
Definition at line 65 of file animaGraph3DFilter.h.
GraphType
template<typename TInput , typename TOutput > typedef Graph<double,double,double> anima::Graph3DFilter< TInput, TOutput >::GraphType
Definition at line 62 of file animaGraph3DFilter.h.
ImageIteratorTypeProba
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator<TSeedProba> anima::Graph3DFilter< TInput, TOutput >::ImageIteratorTypeProba
Definition at line 49 of file animaGraph3DFilter.h.
ImagePointerProba
template<typename TInput , typename TOutput > typedef TSeedProba::Pointer anima::Graph3DFilter< TInput, TOutput >::ImagePointerProba
Definition at line 48 of file animaGraph3DFilter.h.
InputImageConstPointer
template<typename TInput , typename TOutput > typedef TInput::ConstPointer anima::Graph3DFilter< TInput, TOutput >::InputImageConstPointer
Definition at line 41 of file animaGraph3DFilter.h.
InputImagePointer
template<typename TInput , typename TOutput > typedef TInput::Pointer anima::Graph3DFilter< TInput, TOutput >::InputImagePointer
Image typedef support
Definition at line 40 of file animaGraph3DFilter.h.
InputPixelType
template<typename TInput , typename TOutput > typedef TInput::PixelType anima::Graph3DFilter< TInput, TOutput >::InputPixelType
Definition at line 44 of file animaGraph3DFilter.h.
InRegionConstIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionConstIterator< TInput > anima::Graph3DFilter< TInput, TOutput >::InRegionConstIteratorType
Definition at line 42 of file animaGraph3DFilter.h.
InRegionIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TInput > anima::Graph3DFilter< TInput, TOutput >::InRegionIteratorType
Definition at line 43 of file animaGraph3DFilter.h.
MaskRegionConstIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionConstIterator< TMask > anima::Graph3DFilter< TInput, TOutput >::MaskRegionConstIteratorType
Definition at line 60 of file animaGraph3DFilter.h.
MaskRegionIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TMask > anima::Graph3DFilter< TInput, TOutput >::MaskRegionIteratorType
Definition at line 59 of file animaGraph3DFilter.h.
NLinksFilterType
template<typename TInput , typename TOutput > typedef NLinksFilter< TInput,TMask> anima::Graph3DFilter< TInput, TOutput >::NLinksFilterType protected
Definition at line 114 of file animaGraph3DFilter.h.
NumericType
template<typename TInput , typename TOutput > typedef double anima::Graph3DFilter< TInput, TOutput >::NumericType
Definition at line 64 of file animaGraph3DFilter.h.
OutputImagePointer
template<typename TInput , typename TOutput > typedef TOutput::Pointer anima::Graph3DFilter< TInput, TOutput >::OutputImagePointer
Definition at line 52 of file animaGraph3DFilter.h.
OutputImageRegionType
template<typename TInput , typename TOutput > typedef Superclass::OutputImageRegionType anima::Graph3DFilter< TInput, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 94 of file animaGraph3DFilter.h.
OutputIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TOutput > anima::Graph3DFilter< TInput, TOutput >::OutputIteratorType
Definition at line 54 of file animaGraph3DFilter.h.
OutputPixelType
template<typename TInput , typename TOutput > typedef TOutput::PixelType anima::Graph3DFilter< TInput, TOutput >::OutputPixelType
Definition at line 53 of file animaGraph3DFilter.h.
PixelTypeD
template<typename TInput , typename TOutput > typedef double anima::Graph3DFilter< TInput, TOutput >::PixelTypeD
Definition at line 46 of file animaGraph3DFilter.h.
PixelTypeUC
template<typename TInput , typename TOutput > typedef unsigned char anima::Graph3DFilter< TInput, TOutput >::PixelTypeUC
Definition at line 56 of file animaGraph3DFilter.h.
Pointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<Self> anima::Graph3DFilter< TInput, TOutput >::Pointer
Definition at line 30 of file animaGraph3DFilter.h.
ResampleImageFilterFloatType
template<typename TInput , typename TOutput > typedef itk::ResampleImageFilter<TSeedProba, TSeedProba> anima::Graph3DFilter< TInput, TOutput >::ResampleImageFilterFloatType
Definition at line 70 of file animaGraph3DFilter.h.
ResampleImageFilterMaskType
template<typename TInput , typename TOutput > typedef itk::ResampleImageFilter<TMask, TMask> anima::Graph3DFilter< TInput, TOutput >::ResampleImageFilterMaskType
Definition at line 69 of file animaGraph3DFilter.h.
ResampleImageFilterType
template<typename TInput , typename TOutput > typedef itk::ResampleImageFilter<TInput, TInput> anima::Graph3DFilter< TInput, TOutput >::ResampleImageFilterType
Definition at line 68 of file animaGraph3DFilter.h.
SeedProbaPixelType
template<typename TInput , typename TOutput > typedef TSeedProba::PixelType anima::Graph3DFilter< TInput, TOutput >::SeedProbaPixelType
Definition at line 50 of file animaGraph3DFilter.h.
Self
template<typename TInput , typename TOutput > typedef Graph3DFilter anima::Graph3DFilter< TInput, TOutput >::Self
Standard class typedefs.
Definition at line 28 of file animaGraph3DFilter.h.
Superclass
template<typename TInput , typename TOutput > typedef itk::ImageToImageFilter< TInput , TOutput> anima::Graph3DFilter< TInput, TOutput >::Superclass
Definition at line 29 of file animaGraph3DFilter.h.
TMask
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeUC,3> anima::Graph3DFilter< TInput, TOutput >::TMask
Definition at line 57 of file animaGraph3DFilter.h.
TMaskPointer
template<typename TInput , typename TOutput > typedef TMask::Pointer anima::Graph3DFilter< TInput, TOutput >::TMaskPointer
Definition at line 58 of file animaGraph3DFilter.h.
TransformType
template<typename TInput , typename TOutput > typedef itk::IdentityTransform<double, 3> anima::Graph3DFilter< TInput, TOutput >::TransformType
Definition at line 67 of file animaGraph3DFilter.h.
TSeedProba
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeD,3> anima::Graph3DFilter< TInput, TOutput >::TSeedProba
Definition at line 47 of file animaGraph3DFilter.h.
Constructor & Destructor Documentation
Graph3DFilter()
template<typename TInput , typename TOutput > anima::Graph3DFilter< TInput, TOutput >::Graph3DFilter () inline protected
Definition at line 126 of file animaGraph3DFilter.h.
References anima::Graph3DFilter< TInput, TOutput >::MakeOutput(), and anima::NLinksFilter< TInput, TOutput >::New().
~Graph3DFilter()
template<typename TInput , typename TOutput > virtual anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter () inline protected virtual
Definition at line 146 of file animaGraph3DFilter.h.
References anima::Graph3DFilter< TInput, TOutput >::GetInputImage1(), anima::Graph3DFilter< TInput, TOutput >::GetInputImage2(), anima::Graph3DFilter< TInput, TOutput >::GetInputImage3(), anima::Graph3DFilter< TInput, TOutput >::GetInputImage4(), anima::Graph3DFilter< TInput, TOutput >::GetInputImage5(), anima::Graph3DFilter< TInput, TOutput >::GetInputSeedProbaSinks(), anima::Graph3DFilter< TInput, TOutput >::GetInputSeedProbaSources(), anima::Graph3DFilter< TInput, TOutput >::GetMask(), and anima::Graph3DFilter< TInput, TOutput >::MakeOutput().
Member Function Documentation
CheckMemory()
template<typename TInput , typename TOutput > bool anima::Graph3DFilter< TInput, TOutput >::CheckMemory () protected
Definition at line 254 of file animaGraph3DFilter.hxx.
References anima::Graph3DFilter< TInput, TOutput >::ProcessGraphCut().
Referenced by anima::Graph3DFilter< TInput, TOutput >::GenerateData(), and anima::Graph3DFilter< TInput, TOutput >::GetMatFilename().
CreateAnother()
template<typename TInput , typename TOutput > virtual::itk::LightObject::Pointer anima::Graph3DFilter< TInput, TOutput >::CreateAnother (void) const
Dilate()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::Pointer anima::Graph3DFilter< TInput, TOutput >::Dilate (const TMask * input, const TMask * mask)
Definition at line 529 of file animaGraph3DFilter.hxx.
References anima::Graph3DFilter< TInput, TOutput >::Upsample().
Referenced by anima::Graph3DFilter< TInput, TOutput >::ProcessDownsampledGraphCut(), and anima::Graph3DFilter< TInput, TOutput >::SetMatrix().
FindDownsampleFactor()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::FindDownsampleFactor () protected
Definition at line 330 of file animaGraph3DFilter.hxx.
References anima::Graph3DFilter< TInput, TOutput >::InitResampleFilters().
Referenced by anima::Graph3DFilter< TInput, TOutput >::GetMatFilename().
GenerateData()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::GenerateData () protected
Definition at line 154 of file animaGraph3DFilter.hxx.
References anima::Graph3DFilter< TInput, TOutput >::CheckMemory().
Referenced by anima::Graph3DFilter< TInput, TOutput >::GetMatFilename(), and anima::Graph3DFilter< TInput, TOutput >::GetOutputBackground().
GetInputImage1()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetInputImage1 () protected
Definition at line 63 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetInputImage2()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetInputImage2 () protected
Definition at line 91 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetInputImage3()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetInputImage3 () protected
Definition at line 98 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetInputImage4()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetInputImage4 () protected
Definition at line 105 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetInputImage5()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetInputImage5 () protected
Definition at line 112 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetInputSeedProbaSinks()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetInputSeedProbaSinks () protected
Definition at line 77 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetInputSeedProbaSources()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetInputSeedProbaSources () protected
Definition at line 70 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetMask()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::ConstPointer anima::Graph3DFilter< TInput, TOutput >::GetMask () protected
Definition at line 84 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
GetMatFilename()
template<typename TInput , typename TOutput > std::string anima::Graph3DFilter< TInput, TOutput >::GetMatFilename (void) inline protected
Definition at line 165 of file animaGraph3DFilter.h.
References anima::Graph3DFilter< TInput, TOutput >::CheckMemory(), anima::Graph3DFilter< TInput, TOutput >::FindDownsampleFactor(), anima::Graph3DFilter< TInput, TOutput >::GenerateData(), anima::Graph3DFilter< TInput, TOutput >::InitResampleFilters(), anima::Graph3DFilter< TInput, TOutput >::ProcessDownsampledGraphCut(), and anima::Graph3DFilter< TInput, TOutput >::ProcessGraphCut().
GetMatrix()
template<typename TInput , typename TOutput > FloatVariableSizeMatrixType anima::Graph3DFilter< TInput, TOutput >::GetMatrix (void) inline protected
Definition at line 164 of file animaGraph3DFilter.h.
GetNameOfClass()
template<typename TInput , typename TOutput > virtual const char* anima::Graph3DFilter< TInput, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetOutput()
template<typename TInputImage , typename TOutput > TOutput::Pointer anima::Graph3DFilter< TInputImage, TOutput >::GetOutput ()
Definition at line 140 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::SetMatrix().
GetOutputBackground()
template<typename TInputImage , typename TOutput > TOutput::Pointer anima::Graph3DFilter< TInputImage, TOutput >::GetOutputBackground ()
Definition at line 145 of file animaGraph3DFilter.hxx.
References anima::Graph3DFilter< TInput, TOutput >::GenerateData().
Referenced by anima::Graph3DFilter< TInput, TOutput >::SetMatrix().
GetSigma()
template<typename TInput , typename TOutput > virtual float anima::Graph3DFilter< TInput, TOutput >::GetSigma () virtual
GetUseSpectralGradient()
template<typename TInput , typename TOutput > virtual bool anima::Graph3DFilter< TInput, TOutput >::GetUseSpectralGradient () virtual
GetVerbose()
template<typename TInput , typename TOutput > virtual bool anima::Graph3DFilter< TInput, TOutput >::GetVerbose () virtual
InitResampleFilters()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::InitResampleFilters () protected
Definition at line 400 of file animaGraph3DFilter.hxx.
References anima::Graph3DFilter< TInput, TOutput >::ProcessDownsampledGraphCut().
Referenced by anima::Graph3DFilter< TInput, TOutput >::FindDownsampleFactor(), and anima::Graph3DFilter< TInput, TOutput >::GetMatFilename().
MakeOutput()
template<typename TInputImage , typename TOutput > itk::DataObject::Pointer anima::Graph3DFilter< TInputImage, TOutput >::MakeOutput (unsigned int idx) protected
Create the Output
Definition at line 119 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::Graph3DFilter(), and anima::Graph3DFilter< TInput, TOutput >::~Graph3DFilter().
New()
template<typename TInput , typename TOutput > static Pointer anima::Graph3DFilter< TInput, TOutput >::New () static
Method for creation through the object factory.
Referenced by anima::GraphCutFilter< TInput, TOutput >::GraphCutFilter().
ProcessDownsampledGraphCut()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::ProcessDownsampledGraphCut (int current_count) protected
Definition at line 482 of file animaGraph3DFilter.hxx.
References anima::Graph3DFilter< TInput, TOutput >::Dilate().
Referenced by anima::Graph3DFilter< TInput, TOutput >::GetMatFilename(), and anima::Graph3DFilter< TInput, TOutput >::InitResampleFilters().
ProcessGraphCut()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::ProcessGraphCut () protected
Definition at line 291 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::CheckMemory(), and anima::Graph3DFilter< TInput, TOutput >::GetMatFilename().
SetInputImage()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::SetInputImage (unsigned int i, const TInput * image)
The mri images.
Definition at line 9 of file animaGraph3DFilter.hxx.
SetInputSeedProbaSinks()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::SetInputSeedProbaSinks (const TSeedProba * mask)
Definition at line 51 of file animaGraph3DFilter.hxx.
SetInputSeedProbaSources()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::SetInputSeedProbaSources (const TSeedProba * mask)
probabilities of the object and the background, respectively
Definition at line 45 of file animaGraph3DFilter.hxx.
SetMask()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::SetMask (const TMask * mask)
mask in which the segmentation will be performed
Definition at line 57 of file animaGraph3DFilter.hxx.
SetMatFilename()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::SetMatFilename (std::string mat) inline
Definition at line 84 of file animaGraph3DFilter.h.
SetMatrix()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::SetMatrix (FloatVariableSizeMatrixType mat) inline
Definition at line 85 of file animaGraph3DFilter.h.
References anima::Graph3DFilter< TInput, TOutput >::Dilate(), anima::Graph3DFilter< TInput, TOutput >::GetOutput(), anima::Graph3DFilter< TInput, TOutput >::GetOutputBackground(), and anima::Graph3DFilter< TInput, TOutput >::Upsample().
SetSigma()
template<typename TInput , typename TOutput > virtual void anima::Graph3DFilter< TInput, TOutput >::SetSigma (float _arg) virtual
SetTol()
template<typename TInput , typename TOutput > void anima::Graph3DFilter< TInput, TOutput >::SetTol (const double tol) inline
Definition at line 96 of file animaGraph3DFilter.h.
SetUseSpectralGradient()
template<typename TInput , typename TOutput > virtual void anima::Graph3DFilter< TInput, TOutput >::SetUseSpectralGradient (bool _arg) virtual
SetVerbose()
template<typename TInput , typename TOutput > virtual void anima::Graph3DFilter< TInput, TOutput >::SetVerbose (bool _arg) virtual
Upsample()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::Pointer anima::Graph3DFilter< TInput, TOutput >::Upsample (const TMask * input, TMask::SizeType upSize, TMask::DirectionType outputDirection, TMask::PointType outputOrigin)
Definition at line 558 of file animaGraph3DFilter.hxx.
Referenced by anima::Graph3DFilter< TInput, TOutput >::Dilate(), and anima::Graph3DFilter< TInput, TOutput >::SetMatrix().
Member Data Documentation
m_NLinksFilter
template<typename TInput , typename TOutput > NLinksFilterType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_NLinksFilter protected
Definition at line 115 of file animaGraph3DFilter.h.
m_NLinksFilterDecim
template<typename TInput , typename TOutput > NLinksFilterType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_NLinksFilterDecim protected
Definition at line 116 of file animaGraph3DFilter.h.
m_Resample1
template<typename TInput , typename TOutput > ResampleImageFilterType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_Resample1 protected
Definition at line 117 of file animaGraph3DFilter.h.
m_Resample2
template<typename TInput , typename TOutput > ResampleImageFilterType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_Resample2 protected
Definition at line 118 of file animaGraph3DFilter.h.
m_Resample3
template<typename TInput , typename TOutput > ResampleImageFilterType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_Resample3 protected
Definition at line 119 of file animaGraph3DFilter.h.
m_Resample4
template<typename TInput , typename TOutput > ResampleImageFilterType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_Resample4 protected
Definition at line 120 of file animaGraph3DFilter.h.
m_Resample5
template<typename TInput , typename TOutput > ResampleImageFilterType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_Resample5 protected
Definition at line 121 of file animaGraph3DFilter.h.
m_ResampleMask
template<typename TInput , typename TOutput > ResampleImageFilterMaskType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_ResampleMask protected
Definition at line 122 of file animaGraph3DFilter.h.
m_ResampleSinks
template<typename TInput , typename TOutput > ResampleImageFilterFloatType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_ResampleSinks protected
Definition at line 124 of file animaGraph3DFilter.h.
m_ResampleSources
template<typename TInput , typename TOutput > ResampleImageFilterFloatType::Pointer anima::Graph3DFilter< TInput, TOutput >::m_ResampleSources protected
Definition at line 123 of file animaGraph3DFilter.h.
The documentation for this class was generated from the following files:
animaGraph3DFilter.h
animaGraph3DFilter.hxx