ANIMA: anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension > Class Template Reference
anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension > Class Template Reference
#include <animaPyramidalDenseTensorSVFMatchingBridge.h>
Public Types
typedef AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform< typename BaseAgregatorType::InternalScalarType, ImageDimension > AffineTransformType
typedef BalooSVFTransformAgregator< ImageDimension > BalooAgregatorType
typedef BaseTransformAgregator< ImageDimension > BaseAgregatorType
typedef BaseBlockMatchRegistrationType::Pointer BaseBlockMatchRegistrationPointer
typedef anima::BaseBMRegistrationMethod< InputImageType > BaseBlockMatchRegistrationType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MEstimateAgregatorType::BaseOutputTransformType BaseTransformType
typedef itk::SmartPointer< const Self > ConstPointer
typedef DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef rpi::DisplacementFieldTransform< typename BaseAgregatorType::ScalarType, ImageDimension > DisplacementFieldTransformType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef itk::VectorImage< float, ImageDimension > InputImageType
typedef InputImageType::InternalPixelType InputInternalPixelType
typedef InputImageType::IOPixelType InputPixelType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, ImageDimension > MaskImageType
typedef MaskPyramidType::Pointer MaskPyramidPointer
typedef anima::PyramidImageFilter< MaskImageType, MaskImageType > MaskPyramidType
typedef DenseSVFTransformAgregator< ImageDimension > MEstimateAgregatorType
typedef itk::SmartPointer< Self > Pointer
typedef PyramidType::Pointer PyramidPointer
typedef anima::PyramidImageFilter< InputImageType, InputImageType > PyramidType
typedef PyramidalDenseTensorSVFMatchingBridge Self
typedef itk::ProcessObject Superclass
typedef VelocityFieldType::PixelType VectorType
typedef BaseTransformType::VectorFieldType VelocityFieldType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
Agregator GetAgregator ()
double GetAngleUpperBound ()
unsigned int GetBCHCompositionOrder ()
unsigned int GetBlockSize ()
unsigned int GetBlockSpacing ()
double GetElasticSigma ()
unsigned int GetExponentiationOrder ()
double GetExtrapolationSigma ()
double GetFinalRadius ()
bool GetFiniteStrainImageReorientation ()
InputImageType * GetFloatingImage ()
unsigned int GetLastPyramidLevel ()
unsigned int GetMaximumIterations ()
double GetMEstimateConvergenceThreshold ()
Metric GetMetric ()
MetricOrientationType GetMetricOrientation ()
float GetMinimalTransformError ()
virtual const char * GetNameOfClass () const
double GetNeighborhoodApproximation ()
unsigned int GetNumberOfPyramidLevels ()
Optimizer GetOptimizer ()
unsigned int GetOptimizerMaximumIterations ()
double GetOutlierSigma ()
InputImagePointer GetOutputImage ()
BaseTransformPointer GetOutputTransform ()
std::string GetOutputTransformFile ()
double GetPercentageKept ()
InputImageType * GetReferenceImage ()
std::string GetResultFile ()
double GetScaleUpperBound ()
double GetSearchAngleRadius ()
double GetSearchRadius ()
double GetSearchScaleRadius ()
float GetStDevThreshold ()
double GetStepSize ()
SymmetryType GetSymmetryType ()
Transform GetTransform ()
double GetTranslateUpperBound ()
void SetAgregator (Agregator agregator)
void SetAngleUpperBound (double AngleUpperBound)
void SetBCHCompositionOrder (unsigned int order)
void SetBlockGenerationMask (MaskImageType *mask)
void SetBlockSize (int blockSize)
void SetBlockSpacing (unsigned int blockSpacing)
void SetElasticSigma (double elasticSigma)
void SetExponentiationOrder (unsigned int order)
void SetExtrapolationSigma (double extrapolationSigma)
void SetFinalRadius (double FinalRadius)
void SetFiniteStrainImageReorientation (bool reor)
void SetFloatingImage (InputImageConstPointer floatingImage)
void SetLastPyramidLevel (unsigned int LastPyramidLevel)
void SetMaximumIterations (unsigned int MaximumIterations)
void SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold)
void SetMetric (Metric metric)
void SetMetricOrientation (MetricOrientationType metricOr)
void SetMinimalTransformError (float MinimalTransformError)
void SetNeighborhoodApproximation (double neighborhoodApproximation)
void SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels)
void SetOptimizer (Optimizer optimizer)
void SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations)
void SetOutlierSigma (double outlierSigma)
void SetOutputTransformFile (std::string outputTransformFile)
void SetPercentageKept (double PercentageKept)
void SetReferenceImage (InputImageConstPointer referenceImage)
void SetResultFile (std::string resultFile)
void SetScaleUpperBound (double ScaleUpperBound)
void SetSearchAngleRadius (double SearchAngleRadius)
void SetSearchRadius (double SearchRadius)
void SetSearchScaleRadius (double SearchScaleRadius)
void SetStDevThreshold (float StDevThreshold)
void SetStepSize (double StepSize)
void SetSymmetryType (SymmetryType sym)
void SetTransform (Transform transform)
void SetTranslateUpperBound (double TranslateUpperBound)
void Update () ITK_OVERRIDE
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
PyramidalDenseTensorSVFMatchingBridge ()
void SetupPyramids ()
virtual ~PyramidalDenseTensorSVFMatchingBridge ()
Detailed Description
template<unsigned int ImageDimension = 3>
class anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >
Definition at line 56 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
Member Typedef Documentation
AffineTransformPointer
template<unsigned int ImageDimension = 3> typedef AffineTransformType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::AffineTransformPointer
Definition at line 80 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
AffineTransformType
template<unsigned int ImageDimension = 3> typedef itk::AffineTransform<typename BaseAgregatorType::InternalScalarType,ImageDimension> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::AffineTransformType
Definition at line 79 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
BalooAgregatorType
template<unsigned int ImageDimension = 3> typedef BalooSVFTransformAgregator< ImageDimension > anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::BalooAgregatorType
Definition at line 72 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
BaseAgregatorType
template<unsigned int ImageDimension = 3> typedef BaseTransformAgregator< ImageDimension > anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::BaseAgregatorType
Definition at line 70 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
BaseBlockMatchRegistrationPointer
template<unsigned int ImageDimension = 3> typedef BaseBlockMatchRegistrationType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationPointer
Definition at line 89 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
BaseBlockMatchRegistrationType
template<unsigned int ImageDimension = 3> typedef anima::BaseBMRegistrationMethod<InputImageType> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationType
Definition at line 88 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
BaseTransformPointer
template<unsigned int ImageDimension = 3> typedef BaseTransformType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::BaseTransformPointer
Definition at line 75 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
BaseTransformType
template<unsigned int ImageDimension = 3> typedef MEstimateAgregatorType::BaseOutputTransformType anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::BaseTransformType
Definition at line 74 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
ConstPointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<const Self> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::ConstPointer
Definition at line 96 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
DisplacementFieldTransformPointer
template<unsigned int ImageDimension = 3> typedef DisplacementFieldTransformType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::DisplacementFieldTransformPointer
Definition at line 83 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
DisplacementFieldTransformType
template<unsigned int ImageDimension = 3> typedef rpi::DisplacementFieldTransform<typename BaseAgregatorType::ScalarType, ImageDimension> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::DisplacementFieldTransformType
Definition at line 82 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
InputImageConstPointer
template<unsigned int ImageDimension = 3> typedef InputImageType::ConstPointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::InputImageConstPointer
Definition at line 62 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
InputImagePointer
template<unsigned int ImageDimension = 3> typedef InputImageType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::InputImagePointer
Definition at line 61 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
InputImageType
template<unsigned int ImageDimension = 3> typedef itk::VectorImage<float,ImageDimension> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::InputImageType
Definition at line 59 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
InputInternalPixelType
template<unsigned int ImageDimension = 3> typedef InputImageType::InternalPixelType anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::InputInternalPixelType
Definition at line 63 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
InputPixelType
template<unsigned int ImageDimension = 3> typedef InputImageType::IOPixelType anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::InputPixelType
Definition at line 60 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
MaskImagePointer
template<unsigned int ImageDimension = 3> typedef MaskImageType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::MaskImagePointer
Definition at line 66 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
MaskImageType
template<unsigned int ImageDimension = 3> typedef itk::Image<unsigned char, ImageDimension> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::MaskImageType
Definition at line 65 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
MaskPyramidPointer
template<unsigned int ImageDimension = 3> typedef MaskPyramidType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::MaskPyramidPointer
Definition at line 68 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
MaskPyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<MaskImageType,MaskImageType> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::MaskPyramidType
Definition at line 67 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
MEstimateAgregatorType
template<unsigned int ImageDimension = 3> typedef DenseSVFTransformAgregator< ImageDimension > anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::MEstimateAgregatorType
Definition at line 71 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
Pointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<Self> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Pointer
Definition at line 95 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
PyramidPointer
template<unsigned int ImageDimension = 3> typedef PyramidType::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::PyramidPointer
Definition at line 86 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
PyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<InputImageType,InputImageType> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::PyramidType
Definition at line 85 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
Self
template<unsigned int ImageDimension = 3> typedef PyramidalDenseTensorSVFMatchingBridge anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Self
SmartPointer typedef support
Definition at line 92 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
Superclass
template<unsigned int ImageDimension = 3> typedef itk::ProcessObject anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Superclass
Definition at line 93 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
VectorType
template<unsigned int ImageDimension = 3> typedef VelocityFieldType::PixelType anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::VectorType
Definition at line 77 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
VelocityFieldType
template<unsigned int ImageDimension = 3> typedef BaseTransformType::VectorFieldType anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::VelocityFieldType
Definition at line 76 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
Constructor & Destructor Documentation
PyramidalDenseTensorSVFMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::PyramidalDenseTensorSVFMatchingBridge () protected
Definition at line 22 of file animaPyramidalDenseTensorSVFMatchingBridge.hxx.
References Asymmetric, Baloo, Bobyqa, FiniteStrain, TensorOrientedGeneralizedCorrelation, and Translation.
Referenced by anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetBlockGenerationMask().
~PyramidalDenseTensorSVFMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::~PyramidalDenseTensorSVFMatchingBridge () protected virtual
Definition at line 71 of file animaPyramidalDenseTensorSVFMatchingBridge.hxx.
Referenced by anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetBlockGenerationMask().
Member Function Documentation
CreateAnother()
template<unsigned int ImageDimension = 3> virtual::itk::LightObject::Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::CreateAnother (void) const
GetAgregator()
template<unsigned int ImageDimension = 3> Agregator anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetAgregator () inline
Definition at line 192 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetAngleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetAngleUpperBound () inline
Definition at line 186 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetBCHCompositionOrder()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetBCHCompositionOrder () inline
Definition at line 210 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetBlockSize()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetBlockSize () inline
Definition at line 132 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetBlockSpacing()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetBlockSpacing () inline
Definition at line 135 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetElasticSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetElasticSigma () inline
Definition at line 198 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetExponentiationOrder()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetExponentiationOrder () inline
Definition at line 213 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetExtrapolationSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetExtrapolationSigma () inline
Definition at line 195 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetFinalRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetFinalRadius () inline
Definition at line 177 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetFiniteStrainImageReorientation()
template<unsigned int ImageDimension = 3> bool anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetFiniteStrainImageReorientation () inline
Definition at line 153 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetFloatingImage()
template<unsigned int ImageDimension = 3> InputImageType* anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetFloatingImage () inline
Definition at line 113 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetLastPyramidLevel()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetLastPyramidLevel () inline
Definition at line 219 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetMaximumIterations () inline
Definition at line 159 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetMEstimateConvergenceThreshold () inline
Definition at line 204 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetMetric()
template<unsigned int ImageDimension = 3> Metric anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetMetric () inline
Definition at line 147 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetMetricOrientation()
template<unsigned int ImageDimension = 3> MetricOrientationType anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetMetricOrientation () inline
Definition at line 150 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetMinimalTransformError()
template<unsigned int ImageDimension = 3> float anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetMinimalTransformError () inline
Definition at line 162 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetNameOfClass()
template<unsigned int ImageDimension = 3> virtual const char* anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetNameOfClass () const virtual
GetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetNeighborhoodApproximation () inline
Definition at line 207 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetNumberOfPyramidLevels () inline
Definition at line 216 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetOptimizer()
template<unsigned int ImageDimension = 3> Optimizer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetOptimizer () inline
Definition at line 156 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetOptimizerMaximumIterations () inline
Definition at line 165 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetOutlierSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetOutlierSigma () inline
Definition at line 201 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetOutputImage()
template<unsigned int ImageDimension = 3> InputImagePointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetOutputImage () inline
Definition at line 115 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetOutputTransform()
template<unsigned int ImageDimension = 3> BaseTransformPointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetOutputTransform () inline
Getter for transform
Definition at line 120 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetOutputTransformFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetOutputTransformFile () inline
Definition at line 129 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetPercentageKept()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetPercentageKept () inline
Definition at line 222 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetReferenceImage()
template<unsigned int ImageDimension = 3> InputImageType* anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetReferenceImage () inline
Definition at line 112 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetResultFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetResultFile () inline
Setter/Getter for parameters
Definition at line 126 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetScaleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetScaleUpperBound () inline
Definition at line 189 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetSearchAngleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetSearchAngleRadius () inline
Definition at line 171 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetSearchRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetSearchRadius () inline
Definition at line 168 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetSearchScaleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetSearchScaleRadius () inline
Definition at line 174 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetStDevThreshold()
template<unsigned int ImageDimension = 3> float anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetStDevThreshold () inline
Definition at line 138 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetStepSize()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetStepSize () inline
Definition at line 180 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetSymmetryType()
template<unsigned int ImageDimension = 3> SymmetryType anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetSymmetryType () inline
Definition at line 141 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetTransform()
template<unsigned int ImageDimension = 3> Transform anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetTransform () inline
Definition at line 144 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
GetTranslateUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::GetTranslateUpperBound () inline
Definition at line 183 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
New()
template<unsigned int ImageDimension = 3> static Pointer anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::New () static
SetAgregator()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetAgregator (Agregator agregator) inline
Definition at line 193 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetAngleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetAngleUpperBound (double AngleUpperBound) inline
Definition at line 187 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetBCHCompositionOrder()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetBCHCompositionOrder (unsigned int order) inline
Definition at line 211 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetBlockGenerationMask()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetBlockGenerationMask (MaskImageType * mask) inline
Definition at line 225 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
References anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::PyramidalDenseTensorSVFMatchingBridge(), anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetupPyramids(), and anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::~PyramidalDenseTensorSVFMatchingBridge().
SetBlockSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetBlockSize (int blockSize) inline
Definition at line 133 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetBlockSpacing()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetBlockSpacing (unsigned int blockSpacing) inline
Definition at line 136 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetElasticSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetElasticSigma (double elasticSigma) inline
Definition at line 199 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetExponentiationOrder()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetExponentiationOrder (unsigned int order) inline
Definition at line 214 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetExtrapolationSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetExtrapolationSigma (double extrapolationSigma) inline
Definition at line 196 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetFinalRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetFinalRadius (double FinalRadius) inline
Definition at line 178 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetFiniteStrainImageReorientation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetFiniteStrainImageReorientation (bool reor) inline
Definition at line 154 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetFloatingImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetFloatingImage (InputImageConstPointer floatingImage) inline
Definition at line 110 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetLastPyramidLevel()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetLastPyramidLevel (unsigned int LastPyramidLevel) inline
Definition at line 220 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetMaximumIterations (unsigned int MaximumIterations) inline
Definition at line 160 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold) inline
Definition at line 205 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetMetric()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetMetric (Metric metric) inline
Definition at line 148 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetMetricOrientation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetMetricOrientation (MetricOrientationType metricOr) inline
Definition at line 151 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetMinimalTransformError()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetMinimalTransformError (float MinimalTransformError) inline
Definition at line 163 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetNeighborhoodApproximation (double neighborhoodApproximation) inline
Definition at line 208 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels) inline
Definition at line 217 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetOptimizer()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetOptimizer (Optimizer optimizer) inline
Definition at line 157 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations) inline
Definition at line 166 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetOutlierSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetOutlierSigma (double outlierSigma) inline
Definition at line 202 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetOutputTransformFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetOutputTransformFile (std::string outputTransformFile) inline
Definition at line 130 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetPercentageKept()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetPercentageKept (double PercentageKept) inline
Definition at line 223 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetReferenceImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetReferenceImage (InputImageConstPointer referenceImage) inline
Setter for images
Definition at line 109 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetResultFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetResultFile (std::string resultFile) inline
Definition at line 127 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetScaleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetScaleUpperBound (double ScaleUpperBound) inline
Definition at line 190 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetSearchAngleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetSearchAngleRadius (double SearchAngleRadius) inline
Definition at line 172 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetSearchRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetSearchRadius (double SearchRadius) inline
Definition at line 169 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetSearchScaleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetSearchScaleRadius (double SearchScaleRadius) inline
Definition at line 175 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetStDevThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetStDevThreshold (float StDevThreshold) inline
Definition at line 139 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetStepSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetStepSize (double StepSize) inline
Definition at line 181 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetSymmetryType()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetSymmetryType (SymmetryType sym) inline
Definition at line 142 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetTransform()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetTransform (Transform transform) inline
Definition at line 145 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetTranslateUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetTranslateUpperBound (double TranslateUpperBound) inline
Definition at line 184 of file animaPyramidalDenseTensorSVFMatchingBridge.h.
SetupPyramids()
template<unsigned int ImageDimension> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetupPyramids () protected
Definition at line 464 of file animaPyramidalDenseTensorSVFMatchingBridge.hxx.
Referenced by anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::SetBlockGenerationMask().
Update()
template<unsigned int ImageDimension> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::Update ()
Definition at line 77 of file animaPyramidalDenseTensorSVFMatchingBridge.hxx.
References Affine, Asymmetric, Bobyqa, Exhaustive, FiniteStrain, anima::GetSVFExponential(), Kissing, MSmoother, None, PPD, Rigid, anima::BaseBlockMatcher< TInputImageType >::SetBlockPercentageKept(), anima::DenseSVFTransformAgregator< NDimensions >::SetDistanceBoundary(), anima::BalooSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::DenseSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::DenseSVFTransformAgregator< NDimensions >::SetMEstimateConvergenceThreshold(), anima::DenseSVFTransformAgregator< NDimensions >::SetNeighborhoodHalfSize(), anima::DenseSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::BalooSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::DenseSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), anima::BalooSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), anima::BaseTransformAgregator< NDimensions >::SetOutputTransformType(), Symmetric, TensorCorrelation, TensorGeneralizedCorrelation, TensorMeanSquares, TensorOrientedGeneralizedCorrelation, and Translation.
WriteOutputs()
template<unsigned int ImageDimension> void anima::PyramidalDenseTensorSVFMatchingBridge< ImageDimension >::WriteOutputs ()
Definition at line 449 of file animaPyramidalDenseTensorSVFMatchingBridge.hxx.
The documentation for this class was generated from the following files:
animaPyramidalDenseTensorSVFMatchingBridge.h
animaPyramidalDenseTensorSVFMatchingBridge.hxx