ANIMA: anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
#include <animaMCMCorrelationImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, ImageDimension > ContinuousIndexType
typedef Superclass::CoordinateRepresentationType CoordinateRepresentationType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef MCModelType::Vector3DType GradientType
typedef Superclass::InputPointType InputPointType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef TFixedImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMCorrelationImageToImageMetric Self
typedef BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > TFixedImage
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > TMovingImage
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ParametersValueType CoordinateRepresentationType
typedef Superclass::DerivativeType DerivativeType
typedef FixedImageType::ConstPointer FixedImageConstPointer
typedef FixedImageMaskType::ConstPointer FixedImageMaskConstPointer
typedef FixedImageMaskType::Pointer FixedImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(FixedImageDimension) > FixedImageMaskType
typedef FixedImageType::RegionType FixedImageRegionType
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > FixedImageType
typedef TransformType::InputPointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< MovingImageType, CoordinateRepresentationType > InterpolatorType
typedef Superclass::MeasureType MeasureType
enum ModelReorientationType
typedef MovingImageType::ConstPointer MovingImageConstPointer
typedef MovingImageMaskType::ConstPointer MovingImageMaskConstPointer
typedef MovingImageMaskType::Pointer MovingImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(MovingImageDimension) > MovingImageMaskType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > ::PixelType MovingImagePixelType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > MovingImageType
typedef TransformType::OutputPointType OutputPointType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef double RealType
typedef BaseOrientedModelImageToImageMetric Self
typedef itk::SingleValuedCostFunction Superclass
typedef TransformType::JacobianType TransformJacobianType
typedef TransformType::ParametersType TransformParametersType
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< CoordinateRepresentationType, itkGetStaticConstMacro(MovingImageDimension), itkGetStaticConstMacro(FixedImageDimension)> TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void PreComputeFixedValues ()
void SetBigDelta (double val)
virtual void SetForceApproximation (bool _arg)
void SetGradientDirections (std::vector< GradientType > &val)
void SetGradientStrengths (std::vector< double > &val)
virtual void SetLowerBoundGaussianSigma (double _arg)
void SetSmallDelta (double val)
virtual void SetUpperBoundGaussianSigma (double _arg)
Public Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
Should not be used.
virtual const FixedImageType * GetFixedImage () const
virtual const FixedImageMaskType * GetFixedImageMask () const
virtual const FixedImageRegionType & GetFixedImageRegion () const
virtual const InterpolatorType * GetInterpolator () const
virtual ModelReorientationType GetModelRotation () const
virtual const MovingImageType * GetMovingImage () const
virtual const MovingImageMaskType * GetMovingImageMask () const
unsigned int GetNumberOfParameters (void) const ITK_OVERRIDE
virtual const unsigned long & GetNumberOfPixelsCounted () const
virtual const TransformType * GetTransform () const
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &value, DerivativeType &derivative) const ITK_OVERRIDE
virtual void Initialize ()
virtual void SetFixedImage (const FixedImageType *_arg)
virtual void SetFixedImageMask (FixedImageMaskType *_arg)
virtual void SetFixedImageMask (const FixedImageMaskType *_arg)
virtual void SetFixedImageRegion (FixedImageRegionType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetModelRotation (ModelReorientationType _arg)
virtual void SetMovingImage (const MovingImageType *_arg)
virtual void SetMovingImageMask (MovingImageMaskType *_arg)
virtual void SetMovingImageMask (const MovingImageMaskType *_arg)
virtual void SetTransform (TransformType *_arg)
void SetTransformParameters (const ParametersType &parameters) const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
bool CheckTensorCompatibility () const
double ComputeNonTensorBasedMetric (const std::vector< MCModelPointer > &movingValues) const
double ComputeTensorBasedMetric (const std::vector< MCModelPointer > &movingValues) const
bool isZero (PixelType &vector) const
MCMCorrelationImageToImageMetric ()
void UpdateSphereWeights ()
Compute base integration weights for non tensor integration.
virtual ~MCMCorrelationImageToImageMetric ()
Protected Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
BaseOrientedModelImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~BaseOrientedModelImageToImageMetric ()
Additional Inherited Members
Static Public Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
static const unsigned int FixedImageDimension
static const unsigned int MovingImageDimension
Protected Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
FixedImageConstPointer m_FixedImage
FixedImageMaskConstPointer m_FixedImageMask
InterpolatorPointer m_Interpolator
MovingImageConstPointer m_MovingImage
MovingImageMaskConstPointer m_MovingImageMask
unsigned long m_NumberOfPixelsCounted
vnl_matrix< double > m_OrientationMatrix
TransformPointer m_Transform
Detailed Description
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension>
class anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >
Definition at line 11 of file animaMCMCorrelationImageToImageMetric.h.
Member Typedef Documentation
ConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<const Self> anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ConstPointer
Definition at line 22 of file animaMCMCorrelationImageToImageMetric.h.
ContinuousIndexType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::ContinuousIndex<double, ImageDimension> anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ContinuousIndexType
Definition at line 42 of file animaMCMCorrelationImageToImageMetric.h.
CoordinateRepresentationType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::CoordinateRepresentationType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CoordinateRepresentationType
Definition at line 44 of file animaMCMCorrelationImageToImageMetric.h.
FixedImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageConstPointer anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageConstPointer
Definition at line 49 of file animaMCMCorrelationImageToImageMetric.h.
FixedImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageType
Definition at line 47 of file animaMCMCorrelationImageToImageMetric.h.
GradientType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Vector3DType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GradientType
Definition at line 26 of file animaMCMCorrelationImageToImageMetric.h.
InputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::InputPointType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::InputPointType
Definition at line 41 of file animaMCMCorrelationImageToImageMetric.h.
MCModelPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Pointer anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelPointer
Definition at line 25 of file animaMCMCorrelationImageToImageMetric.h.
MCModelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MultiCompartmentModel anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelType
Definition at line 24 of file animaMCMCorrelationImageToImageMetric.h.
MeasureType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MeasureType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType
Definition at line 46 of file animaMCMCorrelationImageToImageMetric.h.
MovingImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageConstPointer anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageConstPointer
Definition at line 50 of file animaMCMCorrelationImageToImageMetric.h.
MovingImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageType
Definition at line 48 of file animaMCMCorrelationImageToImageMetric.h.
OutputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::OutputPointType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::OutputPointType
Definition at line 40 of file animaMCMCorrelationImageToImageMetric.h.
PixelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef TFixedImage::PixelType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PixelType
Types transferred from the base class
Definition at line 35 of file animaMCMCorrelationImageToImageMetric.h.
Pointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<Self> anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Pointer
Definition at line 21 of file animaMCMCorrelationImageToImageMetric.h.
Self
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCMCorrelationImageToImageMetric anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Self
Definition at line 19 of file animaMCMCorrelationImageToImageMetric.h.
Superclass
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef BaseOrientedModelImageToImageMetric<TFixedImage, TMovingImage > anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Superclass
Definition at line 20 of file animaMCMCorrelationImageToImageMetric.h.
TFixedImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TFixedImage
Standard class typedefs.
Definition at line 16 of file animaMCMCorrelationImageToImageMetric.h.
TMovingImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TMovingImage
Definition at line 17 of file animaMCMCorrelationImageToImageMetric.h.
TransformParametersType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformParametersType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformParametersType
Definition at line 39 of file animaMCMCorrelationImageToImageMetric.h.
TransformPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformPointer anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformPointer
Definition at line 38 of file animaMCMCorrelationImageToImageMetric.h.
TransformType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformType
Definition at line 37 of file animaMCMCorrelationImageToImageMetric.h.
Constructor & Destructor Documentation
MCMCorrelationImageToImageMetric()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMCorrelationImageToImageMetric () protected
Definition at line 19 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::DiffusionBigDelta, anima::DiffusionSmallDelta, anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), and anima::MultiCompartmentModelCreator::SetNumberOfCompartments().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMCorrelationImageToImageMetric().
~MCMCorrelationImageToImageMetric()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMCorrelationImageToImageMetric () inline protected virtual
Definition at line 68 of file animaMCMCorrelationImageToImageMetric.h.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetric(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetric(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero(), anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMCorrelationImageToImageMetric(), and anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::UpdateSphereWeights().
Member Function Documentation
CheckTensorCompatibility()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility () const protected
Definition at line 46 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMCorrelationImageToImageMetric(), and anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMCorrelationImageToImageMetric().
ComputeNonTensorBasedMetric()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> double anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetric (const std::vector< MCModelPointer > & movingValues) const protected
Definition at line 169 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetSmallDelta().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetric(), and anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMCorrelationImageToImageMetric().
ComputeTensorBasedMetric()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> double anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetric (const std::vector< MCModelPointer > & movingValues) const protected
Definition at line 130 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetric().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), and anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMCorrelationImageToImageMetric().
CreateAnother()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual::itk::LightObject::Pointer anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CreateAnother (void) const
GetNameOfClass()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual const char* anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >.
GetValue()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Definition at line 73 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetric(), and PPD.
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility().
isZero()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero (PixelType & vector) const protected
Definition at line 336 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::UpdateSphereWeights(), and anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMCorrelationImageToImageMetric().
New()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> static Pointer anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::New () static
Method for creation through the object factory.
PreComputeFixedValues()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues ()
Definition at line 352 of file animaMCMCorrelationImageToImageMetric.hxx.
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
SetBigDelta()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetBigDelta (double val)
Definition at line 228 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientStrengths().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetSmallDelta().
SetForceApproximation()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetForceApproximation (bool _arg) virtual
SetGradientDirections()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientDirections (std::vector< GradientType > & val)
Definition at line 251 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::UpdateSphereWeights().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientStrengths().
SetGradientStrengths()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientStrengths (std::vector< double > & val)
Definition at line 240 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientDirections().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetBigDelta().
SetLowerBoundGaussianSigma()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetLowerBoundGaussianSigma (double _arg) virtual
SetSmallDelta()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetSmallDelta (double val)
Definition at line 216 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetBigDelta().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetric().
SetUpperBoundGaussianSigma()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetUpperBoundGaussianSigma (double _arg) virtual
UpdateSphereWeights()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::UpdateSphereWeights () protected
Compute base integration weights for non tensor integration.
Definition at line 262 of file animaMCMCorrelationImageToImageMetric.hxx.
References anima::GetBValueFromAcquisitionParameters(), and anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
Referenced by anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientDirections(), and anima::MCMCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMCorrelationImageToImageMetric().
The documentation for this class was generated from the following files:
animaMCMCorrelationImageToImageMetric.h
animaMCMCorrelationImageToImageMetric.hxx