ANIMA: anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <animaSmoothingRecursiveYvvGaussianImageFilter.h>
Public Types
typedef CastingFilterType::Pointer CastingFilterPointer
typedef itk::CastImageFilter< RealImageType, OutputImageType > CastingFilterType
typedef itk::SmartPointer< const Self > ConstPointer
typedef FirstGaussianFilterType::Pointer FirstGaussianFilterPointer
typedef anima::RecursiveLineYvvGaussianImageFilter< InputImageType, RealImageType > FirstGaussianFilterType
typedef TInputImage InputImageType
typedef InternalGaussianFilterType::Pointer InternalGaussianFilterPointer
typedef anima::RecursiveLineYvvGaussianImageFilter< RealImageType, RealImageType > InternalGaussianFilterType
typedef itk::NumericTraits< PixelType >::FloatType InternalRealType
typedef OutputImageType::Pointer OutputImagePointer
typedef TOutputImage OutputImageType
typedef TInputImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::template Rebind< InternalRealType >::Type RealImageType
typedef itk::NumericTraits< PixelType >::RealType RealType
typedef itk::NumericTraits< PixelType >::ScalarRealType ScalarRealType
typedef SmoothingRecursiveYvvGaussianImageFilter Self
typedef itk::FixedArray< ScalarRealType, itkGetStaticConstMacro(ImageDimension) > SigmaArrayType
typedef itk::InPlaceImageFilter< TInputImage, TOutputImage > Superclass
Public Member Functions
virtual bool CanRunInPlace () const ITK_OVERRIDE
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual bool GetNormalizeAcrossScale () const
ScalarRealType GetSigma () const
SigmaArrayType GetSigmaArray () const
void SetNormalizeAcrossScale (bool normalizeInScaleSpace)
void SetNumberOfThreads (itk::ThreadIdType nb) ITK_OVERRIDE
void SetSigma (ScalarRealType sigma)
void SetSigmaArray (const SigmaArrayType &sigmas)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = TInputImage::ImageDimension
Protected Member Functions
void EnlargeOutputRequestedRegion (itk::DataObject *output) ITK_OVERRIDE
void GenerateData () ITK_OVERRIDE
virtual void GenerateInputRequestedRegion () ITK_OVERRIDE
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
SmoothingRecursiveYvvGaussianImageFilter ()
virtual ~SmoothingRecursiveYvvGaussianImageFilter ()
Detailed Description
template<typename TInputImage, typename TOutputImage = TInputImage>
class anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >
Definition at line 15 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
Member Typedef Documentation
CastingFilterPointer
template<typename TInputImage, typename TOutputImage = TInputImage> typedef CastingFilterType::Pointer anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::CastingFilterPointer
Pointer to the last filter, casting
Definition at line 76 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
CastingFilterType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::CastImageFilter< RealImageType, OutputImageType > anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::CastingFilterType
The last in the pipeline
Definition at line 67 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
ConstPointer
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::SmartPointer<const Self> anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 23 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
FirstGaussianFilterPointer
template<typename TInputImage, typename TOutputImage = TInputImage> typedef FirstGaussianFilterType::Pointer anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::FirstGaussianFilterPointer
Pointer to the first gaussian filter.
Definition at line 73 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
FirstGaussianFilterType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef anima::RecursiveLineYvvGaussianImageFilter< InputImageType, RealImageType > anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::FirstGaussianFilterType
The first in the pipeline
Definition at line 55 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
InputImageType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef TInputImage anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::InputImageType
Pixel Type of the input image
Definition at line 26 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
InternalGaussianFilterPointer
template<typename TInputImage, typename TOutputImage = TInputImage> typedef InternalGaussianFilterType::Pointer anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::InternalGaussianFilterPointer
Pointer to a gaussian filter.
Definition at line 70 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
InternalGaussianFilterType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef anima::RecursiveLineYvvGaussianImageFilter< RealImageType, RealImageType > anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::InternalGaussianFilterType
Smoothing filter type
Definition at line 61 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
InternalRealType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::NumericTraits< PixelType >::FloatType anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::InternalRealType
Define the image type for internal computations RealType is usually 'double' in NumericTraits. Here we prefer float in order to save memory.
Definition at line 48 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
OutputImagePointer
template<typename TInputImage, typename TOutputImage = TInputImage> typedef OutputImageType::Pointer anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::OutputImagePointer
Pointer to the Output Image
Definition at line 79 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
OutputImageType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef TOutputImage anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 27 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
PixelType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef TInputImage::PixelType anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::PixelType
Definition at line 28 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
Pointer
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::SmartPointer<Self> anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 22 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
RealImageType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef InputImageType::template Rebind<InternalRealType>::Type anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::RealImageType
Definition at line 49 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
RealType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::NumericTraits<PixelType>::RealType anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::RealType
Definition at line 29 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
ScalarRealType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::NumericTraits<PixelType>::ScalarRealType anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::ScalarRealType
Definition at line 30 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
Self
template<typename TInputImage, typename TOutputImage = TInputImage> typedef SmoothingRecursiveYvvGaussianImageFilter anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 20 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
SigmaArrayType
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::FixedArray< ScalarRealType, itkGetStaticConstMacro(ImageDimension) > anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SigmaArrayType
Define the type for the sigma array
Definition at line 42 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
Superclass
template<typename TInputImage, typename TOutputImage = TInputImage> typedef itk::InPlaceImageFilter<TInputImage,TOutputImage> anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 21 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
Constructor & Destructor Documentation
SmoothingRecursiveYvvGaussianImageFilter()
template<typename TInputImage , typename TOutputImage > anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SmoothingRecursiveYvvGaussianImageFilter () protected
Constructor
Definition at line 15 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetNumberOfThreads().
~SmoothingRecursiveYvvGaussianImageFilter()
template<typename TInputImage, typename TOutputImage = TInputImage> virtual anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::~SmoothingRecursiveYvvGaussianImageFilter () inline protected virtual
Definition at line 106 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::EnlargeOutputRequestedRegion(), anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateData(), anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateInputRequestedRegion(), anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::ImageDimension, and anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::PrintSelf().
Member Function Documentation
CanRunInPlace()
template<typename TInputImage , typename TOutputImage > bool anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::CanRunInPlace () const virtual
Definition at line 72 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetSigma().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetNumberOfThreads().
CreateAnother()
template<typename TInputImage, typename TOutputImage = TInputImage> virtual::itk::LightObject::Pointer anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
EnlargeOutputRequestedRegion()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::EnlargeOutputRequestedRegion (itk::DataObject * output) protected
Definition at line 184 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateData().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateInputRequestedRegion(), and anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::~SmoothingRecursiveYvvGaussianImageFilter().
GenerateData()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateData () protected
Generate Data
Compute filter for Gaussian kernel
Definition at line 200 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::PrintSelf().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::EnlargeOutputRequestedRegion(), and anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::~SmoothingRecursiveYvvGaussianImageFilter().
GenerateInputRequestedRegion()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateInputRequestedRegion () protected virtual
SmoothingRecursiveYvvGaussianImageFilter needs all of the input to produce an output. Therefore, SmoothingRecursiveYvvGaussianImageFilter needs to provide an implementation for GenerateInputRequestedRegion in order to inform the pipeline execution model.
See also
ImageToImageFilter::GenerateInputRequestedRegion()
Definition at line 167 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::EnlargeOutputRequestedRegion().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetNormalizeAcrossScale(), and anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::~SmoothingRecursiveYvvGaussianImageFilter().
GetNameOfClass()
template<typename TInputImage, typename TOutputImage = TInputImage> virtual const char* anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Runtime information support.
GetNormalizeAcrossScale()
template<typename TInputImage, typename TOutputImage = TInputImage> virtual bool anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetNormalizeAcrossScale () const virtual
GetSigma()
template<typename TInputImage , typename TOutputImage > SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::ScalarRealType anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetSigma () const
Definition at line 139 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetNormalizeAcrossScale().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetSigmaArray().
GetSigmaArray()
template<typename TInputImage , typename TOutputImage > SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SigmaArrayType anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetSigmaArray () const
Definition at line 128 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetSigma().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetSigmaArray().
New()
template<typename TInputImage, typename TOutputImage = TInputImage> static Pointer anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
PrintSelf()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
Definition at line 266 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateData(), and anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::~SmoothingRecursiveYvvGaussianImageFilter().
SetNormalizeAcrossScale()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetNormalizeAcrossScale (bool normalize)
Define which normalization factor will be used for the Gaussian
Set Normalize Across Scale Space
Definition at line 151 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GenerateInputRequestedRegion().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetSigma().
SetNumberOfThreads()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetNumberOfThreads (itk::ThreadIdType nb)
Definition at line 58 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::CanRunInPlace().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SmoothingRecursiveYvvGaussianImageFilter().
SetSigma()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetSigma (ScalarRealType sigma)
Definition at line 96 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetSigmaArray().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::CanRunInPlace().
SetSigmaArray()
template<typename TInputImage , typename TOutputImage > void anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetSigmaArray (const SigmaArrayType & sigmas)
Set Sigma value. Sigma is measured in the units of image spacing. You may use the method SetSigma to set the same value across each axis or use the method SetSigmaArray if you need different values along each axis.
Definition at line 108 of file animaSmoothingRecursiveYvvGaussianImageFilter.hxx.
References anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::GetSigmaArray().
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::SetSigma().
Member Data Documentation
ImageDimension
template<typename TInputImage, typename TOutputImage = TInputImage> const unsigned int anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::ImageDimension = TInputImage::ImageDimension static
Image dimension.
Definition at line 38 of file animaSmoothingRecursiveYvvGaussianImageFilter.h.
Referenced by anima::SmoothingRecursiveYvvGaussianImageFilter< TInputImage, TOutputImage >::~SmoothingRecursiveYvvGaussianImageFilter().
The documentation for this class was generated from the following files:
animaSmoothingRecursiveYvvGaussianImageFilter.h
animaSmoothingRecursiveYvvGaussianImageFilter.hxx