ANIMA: anima::BaseCompartment Class Reference
anima::BaseCompartment Class Reference abstract
#include <animaBaseCompartment.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
virtual unsigned int GetCompartmentSize ()=0
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
virtual DiffusionModelCompartmentType GetCompartmentType ()=0
Utility function to return compartment type without needing dynamic casts.
virtual ModelOutputVectorType & GetCompartmentVector ()=0
Get compartment overall description vector, mainly for writing, should be self-contained.
virtual const Matrix3DType & GetDiffusionTensor ()
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetExtraAxonalFraction ()
virtual double GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient)=0
virtual double GetFractionalAnisotropy ()
virtual double GetLogDiffusionProfile (const Vector3DType &sample)=0
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfParameters ()=0
Number of optimized parameters: smaller than total number of parameters.
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual ListType & GetParameterLowerBounds ()=0
virtual ListType & GetParametersAsVector ()=0
virtual ListType & GetParameterUpperBounds ()=0
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
virtual ListType & GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient)=0
virtual bool GetTensorCompatible ()
virtual double GetTissueRadius ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-2, double absoluteTolerance=1.0e-8)
Tests equality to another compartment up to a constant (relative and absolute tolerances)
virtual void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform)
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
virtual void SetAxialDiffusivity (double num)
virtual void SetCompartmentVector (ModelOutputVectorType &compartmentVector)=0
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetParametersFromVector (const ListType &params)=0
Various methods for optimization parameters setting and getting.
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
virtual void SetTissueRadius (double num)
Protected Member Functions
BaseCompartment ()
virtual ~BaseCompartment ()
Protected Attributes
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
ListType m_JacobianVector
Vector holding current jacobian value.
ListType m_ParametersLowerBoundsVector
Vector holding current parameters lower bounds.
ListType m_ParametersUpperBoundsVector
Vector holding current parameters upper bounds.
ListType m_ParametersVector
Vector holding current parameters vector.
Static Protected Attributes
static const unsigned int m_SpaceDimension = 3
Detailed Description
Definition at line 30 of file animaBaseCompartment.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::BaseCompartment::ConstPointer
Definition at line 37 of file animaBaseCompartment.h.
ListType
typedef std::vector<double> anima::BaseCompartment::ListType
Definition at line 47 of file animaBaseCompartment.h.
Matrix3DType
typedef itk::Matrix<double, 3, 3> anima::BaseCompartment::Matrix3DType
Definition at line 38 of file animaBaseCompartment.h.
ModelOutputVectorType
typedef itk::VariableLengthVector<double> anima::BaseCompartment::ModelOutputVectorType
Definition at line 48 of file animaBaseCompartment.h.
Pointer
typedef itk::SmartPointer<Self> anima::BaseCompartment::Pointer
Definition at line 36 of file animaBaseCompartment.h.
Self
typedef BaseCompartment anima::BaseCompartment::Self
Definition at line 34 of file animaBaseCompartment.h.
Superclass
typedef itk::LightObject anima::BaseCompartment::Superclass
Definition at line 35 of file animaBaseCompartment.h.
Vector3DType
typedef vnl_vector_fixed<double,3> anima::BaseCompartment::Vector3DType
Definition at line 46 of file animaBaseCompartment.h.
Constructor & Destructor Documentation
BaseCompartment()
anima::BaseCompartment::BaseCompartment () inline protected
Definition at line 111 of file animaBaseCompartment.h.
References anima::MCMAzimuthAngleUpperBound.
~BaseCompartment()
virtual anima::BaseCompartment::~BaseCompartment () inline protected virtual
Definition at line 126 of file animaBaseCompartment.h.
Member Function Documentation
CopyFromOther()
void anima::BaseCompartment::CopyFromOther (Self * rhs) virtual
Copy internal parameters from another compartment, faster than a set/get compartment vector.
Definition at line 86 of file animaBaseCompartment.cxx.
References GetAxialDiffusivity(), GetExtraAxonalFraction(), GetOrientationConcentration(), GetOrientationPhi(), GetOrientationTheta(), GetPerpendicularAngle(), GetRadialDiffusivity1(), GetRadialDiffusivity2(), GetTissueRadius(), SetAxialDiffusivity(), SetExtraAxonalFraction(), SetOrientationConcentration(), SetOrientationPhi(), SetOrientationTheta(), SetPerpendicularAngle(), SetRadialDiffusivity1(), SetRadialDiffusivity2(), and SetTissueRadius().
GetAxialDiffusivity()
virtual double anima::BaseCompartment::GetAxialDiffusivity () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 85 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::TensorCompartment::GetAxialDiffusivity(), anima::BaseIsotropicCompartment::GetCompartmentVector(), anima::StickCompartment::GetCompartmentVector(), anima::StaniszCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::NODDICompartment::GetCompartmentVector(), anima::BaseIsotropicCompartment::GetDiffusionTensor(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::NODDICompartment::GetDiffusionTensor(), anima::BaseIsotropicCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetFractionalAnisotropy(), anima::ZeppelinCompartment::GetFractionalAnisotropy(), anima::NODDICompartment::GetFractionalAnisotropy(), anima::BaseIsotropicCompartment::GetLogDiffusionProfile(), anima::NODDICompartment::GetLogDiffusionProfile(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::BaseIsotropicCompartment::GetParametersAsVector(), anima::NODDICompartment::GetParametersAsVector(), anima::StickCompartment::GetParametersAsVector(), anima::StaniszCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::NODDICompartment::GetSignalAttenuationJacobian(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::StaniszCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), IsEqual(), anima::StaniszCompartment::SetAxialDiffusivity(), anima::NODDICompartment::SetAxialDiffusivity(), anima::StaniszCompartment::UpdateSignals(), and anima::NODDICompartment::UpdateSignals().
GetCompartmentSize()
virtual unsigned int anima::BaseCompartment::GetCompartmentSize () pure virtual
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implemented in anima::NODDICompartment, anima::TensorCompartment, anima::StaniszCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
GetCompartmentType()
virtual DiffusionModelCompartmentType anima::BaseCompartment::GetCompartmentType () pure virtual
Utility function to return compartment type without needing dynamic casts.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
Referenced by anima::MultiCompartmentModel::AddCompartment().
GetCompartmentVector()
virtual ModelOutputVectorType& anima::BaseCompartment::GetCompartmentVector () pure virtual
Get compartment overall description vector, mainly for writing, should be self-contained.
Implemented in anima::NODDICompartment, anima::TensorCompartment, anima::StaniszCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
GetDiffusionTensor()
const BaseCompartment::Matrix3DType & anima::BaseCompartment::GetDiffusionTensor () virtual
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
Reimplemented in anima::TensorCompartment, anima::NODDICompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
Definition at line 120 of file animaBaseCompartment.cxx.
Referenced by IsEqual().
GetExtraAxonalFraction()
virtual double anima::BaseCompartment::GetExtraAxonalFraction () inline virtual
Definition at line 89 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::NODDICompartment::GetCompartmentVector(), anima::NODDICompartment::GetDiffusionTensor(), anima::NODDICompartment::GetFourierTransformedDiffusionProfile(), anima::NODDICompartment::GetFractionalAnisotropy(), anima::NODDICompartment::GetLogDiffusionProfile(), anima::NODDICompartment::GetParametersAsVector(), anima::NODDICompartment::GetSignalAttenuationJacobian(), IsEqual(), anima::NODDICompartment::SetExtraAxonalFraction(), and anima::NODDICompartment::UpdateSignals().
GetFourierTransformedDiffusionProfile()
virtual double anima::BaseCompartment::GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
Referenced by GetPredictedSignal().
GetFractionalAnisotropy()
double anima::BaseCompartment::GetFractionalAnisotropy () virtual
Reimplemented in anima::TensorCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
Definition at line 125 of file animaBaseCompartment.cxx.
GetLogDiffusionProfile()
virtual double anima::BaseCompartment::GetLogDiffusionProfile (const Vector3DType & sample) pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
GetNameOfClass()
virtual const char* anima::BaseCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, anima::StationaryWaterCompartment, and anima::BaseIsotropicCompartment.
GetNumberOfParameters()
virtual unsigned int anima::BaseCompartment::GetNumberOfParameters () pure virtual
Number of optimized parameters: smaller than total number of parameters.
Implemented in anima::NODDICompartment, anima::TensorCompartment, anima::StaniszCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
GetOrientationConcentration()
virtual double anima::BaseCompartment::GetOrientationConcentration () inline virtual
Definition at line 88 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::NODDICompartment::GetCompartmentVector(), anima::NODDICompartment::GetParametersAsVector(), anima::NODDICompartment::GetSignalAttenuationJacobian(), IsEqual(), anima::NODDICompartment::SetOrientationConcentration(), anima::NODDICompartment::UpdateKappaValues(), and anima::NODDICompartment::UpdateSignals().
GetOrientationPhi()
virtual double anima::BaseCompartment::GetOrientationPhi () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 83 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::NODDICompartment::GetCompartmentVector(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::NODDICompartment::GetDiffusionTensor(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetLogDiffusionProfile(), anima::NODDICompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::TensorCompartment::GetOrientationPhi(), anima::NODDICompartment::GetParametersAsVector(), anima::StickCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::NODDICompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), IsEqual(), Reorient(), anima::NODDICompartment::SetOrientationPhi(), and anima::NODDICompartment::UpdateSignals().
GetOrientationTheta()
virtual double anima::BaseCompartment::GetOrientationTheta () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 82 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::NODDICompartment::GetCompartmentVector(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::NODDICompartment::GetDiffusionTensor(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetLogDiffusionProfile(), anima::NODDICompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::TensorCompartment::GetOrientationTheta(), anima::NODDICompartment::GetParametersAsVector(), anima::StickCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::NODDICompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), IsEqual(), Reorient(), anima::NODDICompartment::SetOrientationTheta(), and anima::NODDICompartment::UpdateSignals().
GetParameterLowerBounds()
virtual ListType& anima::BaseCompartment::GetParameterLowerBounds () pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
GetParametersAsVector()
virtual ListType& anima::BaseCompartment::GetParametersAsVector () pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
GetParameterUpperBounds()
virtual ListType& anima::BaseCompartment::GetParameterUpperBounds () pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, anima::FreeWaterCompartment, anima::IsotropicRestrictedWaterCompartment, and anima::StationaryWaterCompartment.
GetPerpendicularAngle()
virtual double anima::BaseCompartment::GetPerpendicularAngle () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 84 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::TensorCompartment::GetPerpendicularAngle(), and IsEqual().
GetPredictedSignal()
double anima::BaseCompartment::GetPredictedSignal (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient)
Definition at line 9 of file animaBaseCompartment.cxx.
References GetFourierTransformedDiffusionProfile().
GetRadialDiffusivity1()
virtual double anima::BaseCompartment::GetRadialDiffusivity1 () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 86 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::StickCompartment::GetFourierTransformedDiffusionProfile(), anima::ZeppelinCompartment::GetFourierTransformedDiffusionProfile(), anima::StickCompartment::GetFractionalAnisotropy(), anima::ZeppelinCompartment::GetFractionalAnisotropy(), anima::StickCompartment::GetLogDiffusionProfile(), anima::ZeppelinCompartment::GetLogDiffusionProfile(), anima::StickCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), anima::TensorCompartment::GetRadialDiffusivity1(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), IsEqual(), and anima::StickCompartment::SetParametersFromVector().
GetRadialDiffusivity2()
virtual double anima::BaseCompartment::GetRadialDiffusivity2 () inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 87 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::TensorCompartment::GetRadialDiffusivity2(), and IsEqual().
GetSignalAttenuationJacobian()
virtual ListType& anima::BaseCompartment::GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) pure virtual
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
GetTensorCompatible()
virtual bool anima::BaseCompartment::GetTensorCompatible () inline virtual
Reimplemented in anima::NODDICompartment, and anima::StaniszCompartment.
Definition at line 105 of file animaBaseCompartment.h.
Referenced by IsEqual().
GetTissueRadius()
virtual double anima::BaseCompartment::GetTissueRadius () inline virtual
Definition at line 90 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StaniszCompartment::GetCompartmentVector(), anima::StaniszCompartment::GetFourierTransformedDiffusionProfile(), anima::StaniszCompartment::GetLogDiffusionProfile(), anima::StaniszCompartment::GetParametersAsVector(), anima::StaniszCompartment::GetSignalAttenuationJacobian(), IsEqual(), anima::StaniszCompartment::SetTissueRadius(), and anima::StaniszCompartment::UpdateSignals().
IsEqual()
bool anima::BaseCompartment::IsEqual (Self * rhs, double tolerance = 1.0e-2, double absoluteTolerance = 1.0e-8) virtual
Tests equality to another compartment up to a constant (relative and absolute tolerances)
Definition at line 16 of file animaBaseCompartment.cxx.
References anima::ComputeScalarProduct(), GetAxialDiffusivity(), GetDiffusionTensor(), GetExtraAxonalFraction(), GetOrientationConcentration(), GetOrientationPhi(), GetOrientationTheta(), GetPerpendicularAngle(), GetRadialDiffusivity1(), GetRadialDiffusivity2(), GetTensorCompatible(), GetTissueRadius(), and anima::TransformSphericalToCartesianCoordinates().
Reorient()
void anima::BaseCompartment::Reorient (vnl_matrix< double > & orientationMatrix, bool affineTransform) virtual
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
Reimplemented in anima::TensorCompartment, and anima::BaseIsotropicCompartment.
Definition at line 99 of file animaBaseCompartment.cxx.
References GetOrientationPhi(), GetOrientationTheta(), SetOrientationPhi(), SetOrientationTheta(), anima::TransformCartesianToSphericalCoordinates(), and anima::TransformSphericalToCartesianCoordinates().
SetAxialDiffusivity()
virtual void anima::BaseCompartment::SetAxialDiffusivity (double num) inline virtual
Reimplemented in anima::TensorCompartment, anima::NODDICompartment, and anima::StaniszCompartment.
Definition at line 96 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StaniszCompartment::SetAxialDiffusivity(), anima::NODDICompartment::SetAxialDiffusivity(), anima::TensorCompartment::SetAxialDiffusivity(), anima::BaseIsotropicCompartment::SetCompartmentVector(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::BaseIsotropicCompartment::SetParametersFromVector(), anima::StickCompartment::SetParametersFromVector(), and anima::ZeppelinCompartment::SetParametersFromVector().
SetCompartmentVector()
virtual void anima::BaseCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) pure virtual
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implemented in anima::NODDICompartment, anima::TensorCompartment, anima::StaniszCompartment, anima::ZeppelinCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
Referenced by anima::MCMWeightedAverager::ComputeOutputTensorModel().
SetExtraAxonalFraction()
virtual void anima::BaseCompartment::SetExtraAxonalFraction (double num) inline virtual
Reimplemented in anima::NODDICompartment.
Definition at line 100 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), and anima::NODDICompartment::SetExtraAxonalFraction().
SetOrientationConcentration()
virtual void anima::BaseCompartment::SetOrientationConcentration (double num) inline virtual
Reimplemented in anima::NODDICompartment.
Definition at line 99 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), and anima::NODDICompartment::SetOrientationConcentration().
SetOrientationPhi()
virtual void anima::BaseCompartment::SetOrientationPhi (double num) inline virtual
Reimplemented in anima::TensorCompartment, and anima::NODDICompartment.
Definition at line 94 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), Reorient(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::NODDICompartment::SetOrientationPhi(), anima::TensorCompartment::SetOrientationPhi(), anima::StickCompartment::SetParametersFromVector(), anima::ZeppelinCompartment::SetParametersFromVector(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks().
SetOrientationTheta()
virtual void anima::BaseCompartment::SetOrientationTheta (double num) inline virtual
Reimplemented in anima::TensorCompartment, and anima::NODDICompartment.
Definition at line 93 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), Reorient(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::NODDICompartment::SetOrientationTheta(), anima::TensorCompartment::SetOrientationTheta(), anima::StickCompartment::SetParametersFromVector(), anima::ZeppelinCompartment::SetParametersFromVector(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks().
SetParametersFromVector()
virtual void anima::BaseCompartment::SetParametersFromVector (const ListType & params) pure virtual
Various methods for optimization parameters setting and getting.
Implemented in anima::TensorCompartment, anima::ZeppelinCompartment, anima::NODDICompartment, anima::StaniszCompartment, anima::StickCompartment, and anima::BaseIsotropicCompartment.
SetPerpendicularAngle()
virtual void anima::BaseCompartment::SetPerpendicularAngle (double num) inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 95 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), and anima::TensorCompartment::SetPerpendicularAngle().
SetRadialDiffusivity1()
virtual void anima::BaseCompartment::SetRadialDiffusivity1 (double num) inline virtual
Reimplemented in anima::TensorCompartment, and anima::ZeppelinCompartment.
Definition at line 97 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetRadialDiffusivity1(), and anima::TensorCompartment::SetRadialDiffusivity1().
SetRadialDiffusivity2()
virtual void anima::BaseCompartment::SetRadialDiffusivity2 (double num) inline virtual
Reimplemented in anima::TensorCompartment.
Definition at line 98 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), anima::ZeppelinCompartment::SetRadialDiffusivity1(), and anima::TensorCompartment::SetRadialDiffusivity2().
SetTissueRadius()
virtual void anima::BaseCompartment::SetTissueRadius (double num) inline virtual
Reimplemented in anima::StaniszCompartment.
Definition at line 101 of file animaBaseCompartment.h.
Referenced by CopyFromOther(), and anima::StaniszCompartment::SetTissueRadius().
Member Data Documentation
m_CompartmentVector
ModelOutputVectorType anima::BaseCompartment::m_CompartmentVector protected
Vector to hold working value of compartment vector.
Definition at line 146 of file animaBaseCompartment.h.
Referenced by anima::BaseIsotropicCompartment::GetCompartmentVector(), anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::StaniszCompartment::GetCompartmentVector(), anima::NODDICompartment::GetCompartmentVector(), and anima::TensorCompartment::GetCompartmentVector().
m_DiffusionTensor
Matrix3DType anima::BaseCompartment::m_DiffusionTensor protected
Matrix to hold working value of diffusion tensor approximation to the model.
Definition at line 131 of file animaBaseCompartment.h.
Referenced by anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), and anima::NODDICompartment::GetDiffusionTensor().
m_JacobianVector
ListType anima::BaseCompartment::m_JacobianVector protected
Vector holding current jacobian value.
Definition at line 134 of file animaBaseCompartment.h.
Referenced by anima::BaseIsotropicCompartment::GetSignalAttenuationJacobian(), anima::NODDICompartment::GetSignalAttenuationJacobian(), anima::StickCompartment::GetSignalAttenuationJacobian(), anima::StaniszCompartment::GetSignalAttenuationJacobian(), anima::ZeppelinCompartment::GetSignalAttenuationJacobian(), and anima::TensorCompartment::GetSignalAttenuationJacobian().
m_ParametersLowerBoundsVector
ListType anima::BaseCompartment::m_ParametersLowerBoundsVector protected
Vector holding current parameters lower bounds.
Definition at line 140 of file animaBaseCompartment.h.
Referenced by anima::FreeWaterCompartment::GetParameterLowerBounds(), anima::IsotropicRestrictedWaterCompartment::GetParameterLowerBounds(), anima::StationaryWaterCompartment::GetParameterLowerBounds(), anima::StickCompartment::GetParameterLowerBounds(), anima::StaniszCompartment::GetParameterLowerBounds(), anima::NODDICompartment::GetParameterLowerBounds(), anima::TensorCompartment::GetParameterLowerBounds(), and anima::ZeppelinCompartment::GetParameterLowerBounds().
m_ParametersUpperBoundsVector
ListType anima::BaseCompartment::m_ParametersUpperBoundsVector protected
Vector holding current parameters upper bounds.
Definition at line 143 of file animaBaseCompartment.h.
Referenced by anima::FreeWaterCompartment::GetParameterUpperBounds(), anima::IsotropicRestrictedWaterCompartment::GetParameterUpperBounds(), anima::StationaryWaterCompartment::GetParameterUpperBounds(), anima::StickCompartment::GetParameterUpperBounds(), anima::StaniszCompartment::GetParameterUpperBounds(), anima::NODDICompartment::GetParameterUpperBounds(), anima::TensorCompartment::GetParameterUpperBounds(), and anima::ZeppelinCompartment::GetParameterUpperBounds().
m_ParametersVector
ListType anima::BaseCompartment::m_ParametersVector protected
Vector holding current parameters vector.
Definition at line 137 of file animaBaseCompartment.h.
Referenced by anima::BaseIsotropicCompartment::GetParametersAsVector(), anima::NODDICompartment::GetParametersAsVector(), anima::StickCompartment::GetParametersAsVector(), anima::StaniszCompartment::GetParametersAsVector(), anima::ZeppelinCompartment::GetParametersAsVector(), and anima::TensorCompartment::GetParametersAsVector().
m_SpaceDimension
const unsigned int anima::BaseCompartment::m_SpaceDimension = 3 static protected
Definition at line 128 of file animaBaseCompartment.h.
Referenced by anima::StickCompartment::GetCompartmentVector(), anima::ZeppelinCompartment::GetCompartmentVector(), anima::NODDICompartment::GetCompartmentVector(), anima::BaseIsotropicCompartment::GetDiffusionTensor(), anima::StickCompartment::GetDiffusionTensor(), anima::ZeppelinCompartment::GetDiffusionTensor(), anima::NODDICompartment::GetDiffusionTensor(), anima::TensorCompartment::GetFourierTransformedDiffusionProfile(), anima::TensorCompartment::GetLogDiffusionProfile(), anima::StickCompartment::SetCompartmentVector(), anima::ZeppelinCompartment::SetCompartmentVector(), anima::TensorCompartment::SetCompartmentVector(), anima::NODDICompartment::SetCompartmentVector(), anima::TensorCompartment::UpdateDiffusionTensor(), anima::TensorCompartment::UpdateInverseDiffusionTensor(), and anima::TensorCompartment::UpdateParametersFromTensor().
The documentation for this class was generated from the following files:
animaBaseCompartment.h
animaBaseCompartment.cxx