ANIMA: anima::SimuBlochSE< TImage > Class Template Reference
anima::SimuBlochSE< TImage > Class Template Reference
#include <animaSimuBlochSE.h>
Public Types
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef SimuBlochSE Self
typedef itk::ImageToImageFilter< TImage, TImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual float GetTE ()
virtual float GetTR ()
void SetInputM0 (const TImage *M0)
void SetInputT1 (const TImage *T1)
void SetInputT2 (const TImage *T2)
virtual void SetTE (float _arg)
virtual void SetTR (float _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
SimuBlochSE ()
virtual void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~SimuBlochSE ()
Detailed Description
template<class TImage>
class anima::SimuBlochSE< TImage >
Definition at line 9 of file animaSimuBlochSE.h.
Member Typedef Documentation
OutputImageRegionType
template<class TImage > typedef Superclass::OutputImageRegionType anima::SimuBlochSE< TImage >::OutputImageRegionType
Definition at line 17 of file animaSimuBlochSE.h.
Pointer
template<class TImage > typedef itk::SmartPointer<Self> anima::SimuBlochSE< TImage >::Pointer
Definition at line 15 of file animaSimuBlochSE.h.
Self
template<class TImage > typedef SimuBlochSE anima::SimuBlochSE< TImage >::Self
Standard class typedefs.
Definition at line 13 of file animaSimuBlochSE.h.
Superclass
template<class TImage > typedef itk::ImageToImageFilter<TImage, TImage> anima::SimuBlochSE< TImage >::Superclass
Definition at line 14 of file animaSimuBlochSE.h.
Constructor & Destructor Documentation
SimuBlochSE()
template<class TImage > anima::SimuBlochSE< TImage >::SimuBlochSE () protected
Definition at line 46 of file animaSimuBlochSE.hxx.
~SimuBlochSE()
template<class TImage > virtual anima::SimuBlochSE< TImage >::~SimuBlochSE () inline protected virtual
Definition at line 42 of file animaSimuBlochSE.h.
References anima::SimuBlochSE< TImage >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<class TImage > virtual::itk::LightObject::Pointer anima::SimuBlochSE< TImage >::CreateAnother (void) const
GetNameOfClass()
template<class TImage > virtual const char* anima::SimuBlochSE< TImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetTE()
template<class TImage > virtual float anima::SimuBlochSE< TImage >::GetTE () virtual
GetTR()
template<class TImage > virtual float anima::SimuBlochSE< TImage >::GetTR () virtual
New()
template<class TImage > static Pointer anima::SimuBlochSE< TImage >::New () static
Method for creation through the object factory.
SetInputM0()
template<class TImage > void anima::SimuBlochSE< TImage >::SetInputM0 (const TImage * M0)
M0 image / Rho map
Definition at line 64 of file animaSimuBlochSE.hxx.
References anima::SimuBlochSE< TImage >::ThreadedGenerateData().
SetInputT1()
template<class TImage > void anima::SimuBlochSE< TImage >::SetInputT1 (const TImage * T1)
T1 map
Definition at line 52 of file animaSimuBlochSE.hxx.
SetInputT2()
template<class TImage > void anima::SimuBlochSE< TImage >::SetInputT2 (const TImage * T2)
T2 map
Definition at line 58 of file animaSimuBlochSE.hxx.
SetTE()
template<class TImage > virtual void anima::SimuBlochSE< TImage >::SetTE (float _arg) virtual
SetTR()
template<class TImage > virtual void anima::SimuBlochSE< TImage >::SetTR (float _arg) virtual
ThreadedGenerateData()
template<class TImage > void anima::SimuBlochSE< TImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected virtual
Does the real work.
Definition at line 71 of file animaSimuBlochSE.hxx.
Referenced by anima::SimuBlochSE< TImage >::SetInputM0(), and anima::SimuBlochSE< TImage >::~SimuBlochSE().
The documentation for this class was generated from the following files:
animaSimuBlochSE.h
animaSimuBlochSE.hxx