ANIMA: anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType > Class Template Reference
anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType > Class Template Reference
#include <animaGammaMixtureT2RelaxometryEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef NNLSOptimizerType::MatrixType DataMatrixType
typedef InputImageType::IndexType IndexType
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef NNLSOptimizerType::Pointer NNLSOptimizerPointer
typedef anima::NNLSOptimizer NNLSOptimizerType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef VectorOutputImageType::PixelType OutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef GammaMixtureT2RelaxometryEstimationImageFilter Self
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef NNLSOptimizerType::ParametersType T2VectorType
typedef itk::Image< TPixelScalarType, 3 > TInputImage
typedef itk::Image< TPixelScalarType, 3 > TOutputImage
typedef VectorOutputImageType::Pointer VectorOutputImagePointer
typedef itk::VectorImage< TPixelScalarType, 3 > VectorOutputImageType
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::Image< TPixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< TPixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
InputImageType * GetB1OutputImage ()
InputImageType * GetM0OutputImage ()
VectorOutputImageType * GetMeanParamImage ()
InputImageType * GetMWFOutputImage ()
virtual const char * GetNameOfClass () const
InputImageType * GetT1Map ()
VectorOutputImageType * GetWeightsImage ()
virtual void SetAverageSignalThreshold (double _arg)
virtual void SetB1OnExcitationAngle (bool _arg)
virtual void SetB1Tolerance (double _arg)
virtual void SetConstrainedParameters (bool _arg)
virtual void SetCostTolerance (double _arg)
virtual void SetEchoSpacing (double _arg)
virtual void SetLowerT2Bound (double _arg)
void SetT1Map (InputImageType *map)
virtual void SetT2ExcitationFlipAngle (double _arg)
void SetT2FlipAngles (std::vector< double > &flipAngles)
void SetT2FlipAngles (double singleAngle, unsigned int numAngles)
virtual void SetT2IntegrationStep (double _arg)
virtual void SetUpperT2Bound (double _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
bool endConditionReached (double b1Value, double previousB1Value, double costValue, double previousCostValue)
GammaMixtureT2RelaxometryEstimationImageFilter ()
void PrepareGammaValues (std::vector< std::vector< double > > &sampledGammaValues, std::vector< std::vector< unsigned int > > &sampledGammaT2Correspondences, std::vector< double > &t2WorkingValues, std::vector< double > &optimizedGamParams, std::vector< double > &gammaVariance)
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~GammaMixtureT2RelaxometryEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::Image< TPixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< TPixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class TPixelScalarType>
class anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >
Definition at line 15 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TPixelScalarType > typedef itk::SmartPointer<const Self> anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ConstPointer
Definition at line 25 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
DataMatrixType
template<class TPixelScalarType > typedef NNLSOptimizerType::MatrixType anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::DataMatrixType
Definition at line 50 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
IndexType
template<class TPixelScalarType > typedef InputImageType::IndexType anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::IndexType
Definition at line 35 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
InputImagePointer
template<class TPixelScalarType > typedef InputImageType::Pointer anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImagePointer
Definition at line 39 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
InputImageRegionType
template<class TPixelScalarType > typedef Superclass::InputImageRegionType anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImageRegionType
Definition at line 45 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
InputImageType
template<class TPixelScalarType > typedef TInputImage anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImageType
Image typedef support
Definition at line 34 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
MaskImageType
template<class TPixelScalarType > typedef Superclass::MaskImageType anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::MaskImageType
Superclass typedefs.
Definition at line 44 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
NNLSOptimizerPointer
template<class TPixelScalarType > typedef NNLSOptimizerType::Pointer anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::NNLSOptimizerPointer
Definition at line 49 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
NNLSOptimizerType
template<class TPixelScalarType > typedef anima::NNLSOptimizer anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::NNLSOptimizerType
Definition at line 48 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
OutputImagePointer
template<class TPixelScalarType > typedef OutputImageType::Pointer anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImagePointer
Definition at line 40 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
OutputImageRegionType
template<class TPixelScalarType > typedef Superclass::OutputImageRegionType anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImageRegionType
Definition at line 46 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
OutputImageType
template<class TPixelScalarType > typedef TOutputImage anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImageType
Definition at line 36 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
OutputVectorType
template<class TPixelScalarType > typedef VectorOutputImageType::PixelType anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputVectorType
Definition at line 38 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
Pointer
template<class TPixelScalarType > typedef itk::SmartPointer<Self> anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::Pointer
Definition at line 24 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
Self
template<class TPixelScalarType > typedef GammaMixtureT2RelaxometryEstimationImageFilter anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::Self
Standard class typedefs.
Definition at line 20 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
Superclass
template<class TPixelScalarType > typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::Superclass
Definition at line 23 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
T2VectorType
template<class TPixelScalarType > typedef NNLSOptimizerType::ParametersType anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::T2VectorType
Definition at line 51 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
TInputImage
template<class TPixelScalarType > typedef itk::Image<TPixelScalarType, 3> anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::TInputImage
Definition at line 21 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
TOutputImage
template<class TPixelScalarType > typedef itk::Image<TPixelScalarType, 3> anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::TOutputImage
Definition at line 22 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
VectorOutputImagePointer
template<class TPixelScalarType > typedef VectorOutputImageType::Pointer anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::VectorOutputImagePointer
Definition at line 41 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
VectorOutputImageType
template<class TPixelScalarType > typedef itk::VectorImage<TPixelScalarType, 3> anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::VectorOutputImageType
Definition at line 37 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
Constructor & Destructor Documentation
GammaMixtureT2RelaxometryEstimationImageFilter()
template<class TPixelScalarType > anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GammaMixtureT2RelaxometryEstimationImageFilter () inline protected
Definition at line 80 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
Referenced by anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GammaMixtureT2RelaxometryEstimationImageFilter().
~GammaMixtureT2RelaxometryEstimationImageFilter()
template<class TPixelScalarType > virtual anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GammaMixtureT2RelaxometryEstimationImageFilter () inline protected virtual
Definition at line 116 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
References anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::BeforeThreadedGenerateData(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::CheckComputationMask(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::endConditionReached(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GammaMixtureT2RelaxometryEstimationImageFilter(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::PrepareGammaValues(), and anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class TPixelScalarType > void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
Definition at line 24 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GammaMixtureT2RelaxometryEstimationImageFilter().
CheckComputationMask()
template<class TPixelScalarType > void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
Definition at line 58 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GammaMixtureT2RelaxometryEstimationImageFilter().
CreateAnother()
template<class TPixelScalarType > virtual::itk::LightObject::Pointer anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::CreateAnother (void) const
endConditionReached()
template<class TPixelScalarType > bool anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::endConditionReached (double b1Value, double previousB1Value, double costValue, double previousCostValue) protected
Definition at line 400 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GammaMixtureT2RelaxometryEstimationImageFilter().
GetB1OutputImage()
template<class TPixelScalarType > InputImageType* anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetB1OutputImage () inline
Definition at line 64 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
GetM0OutputImage()
template<class TPixelScalarType > InputImageType* anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetM0OutputImage () inline
Definition at line 62 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
GetMeanParamImage()
template<class TPixelScalarType > VectorOutputImageType* anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetMeanParamImage () inline
Definition at line 66 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
GetMWFOutputImage()
template<class TPixelScalarType > InputImageType* anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetMWFOutputImage () inline
Definition at line 63 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
GetNameOfClass()
template<class TPixelScalarType > virtual const char* anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
GetT1Map()
template<class TPixelScalarType > InputImageType* anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetT1Map () inline
Definition at line 58 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
GetWeightsImage()
template<class TPixelScalarType > VectorOutputImageType* anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetWeightsImage () inline
Definition at line 65 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
New()
template<class TPixelScalarType > static Pointer anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::New () static
Method for creation through the object factory.
PrepareGammaValues()
template<class TPixelScalarType > void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::PrepareGammaValues (std::vector< std::vector< double > > & sampledGammaValues, std::vector< std::vector< unsigned int > > & sampledGammaT2Correspondences, std::vector< double > & t2WorkingValues, std::vector< double > & optimizedGamParams, std::vector< double > & gammaVariance) protected
Definition at line 415 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GammaMixtureT2RelaxometryEstimationImageFilter().
SetAverageSignalThreshold()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetAverageSignalThreshold (double _arg) virtual
SetB1OnExcitationAngle()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1OnExcitationAngle (bool _arg) virtual
SetB1Tolerance()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1Tolerance (double _arg) virtual
SetConstrainedParameters()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetConstrainedParameters (bool _arg) virtual
SetCostTolerance()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetCostTolerance (double _arg) virtual
SetEchoSpacing()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetEchoSpacing (double _arg) virtual
SetLowerT2Bound()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetLowerT2Bound (double _arg) virtual
SetT1Map()
template<class TPixelScalarType > void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT1Map (InputImageType * map) inline
Definition at line 57 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
SetT2ExcitationFlipAngle()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2ExcitationFlipAngle (double _arg) virtual
SetT2FlipAngles() [1/2]
template<class TPixelScalarType > void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 76 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
SetT2FlipAngles() [2/2]
template<class TPixelScalarType > void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2FlipAngles (double singleAngle, unsigned int numAngles) inline
Definition at line 77 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.h.
SetT2IntegrationStep()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2IntegrationStep (double _arg) virtual
SetUpperT2Bound()
template<class TPixelScalarType > virtual void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetUpperT2Bound (double _arg) virtual
ThreadedGenerateData()
template<class TPixelScalarType > void anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 106 of file animaGammaMixtureT2RelaxometryEstimationImageFilter.hxx.
References anima::EPGSignalSimulator::GetValue(), anima::GammaMixtureT2RelaxometryCostFunction::New(), anima::NLOPTOptimizers::New(), anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), and anima::EPGSignalSimulator::SetNumberOfEchoes().
Referenced by anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GammaMixtureT2RelaxometryEstimationImageFilter().
The documentation for this class was generated from the following files:
animaGammaMixtureT2RelaxometryEstimationImageFilter.h
animaGammaMixtureT2RelaxometryEstimationImageFilter.hxx