ANIMA: anima::EPGSignalSimulator Class Reference
anima::EPGSignalSimulator Class Reference
#include <animaEPGSignalSimulator.h>
Public Types
typedef std::vector< double > RealVectorType
Public Member Functions
EPGSignalSimulator ()
RealVectorType & GetValue (double t1Value, double t2Value, double b1Value, double m0Value)
void SetB1OnExcitationAngle (bool val)
void SetEchoSpacing (double val)
void SetExcitationFlipAngle (double val)
void SetFlipAngle (double val)
void SetNumberOfEchoes (unsigned int val)
virtual ~EPGSignalSimulator ()
Protected Member Functions
void ComputeT2SignalMatrixElements (double t1Value, double t2Value, double b1Value)
Detailed Description
Definition at line 10 of file animaEPGSignalSimulator.h.
Member Typedef Documentation
RealVectorType
typedef std::vector<double> anima::EPGSignalSimulator::RealVectorType
Definition at line 16 of file animaEPGSignalSimulator.h.
Constructor & Destructor Documentation
EPGSignalSimulator()
anima::EPGSignalSimulator::EPGSignalSimulator ()
Definition at line 9 of file animaEPGSignalSimulator.cxx.
~EPGSignalSimulator()
virtual anima::EPGSignalSimulator::~EPGSignalSimulator () inline virtual
Definition at line 14 of file animaEPGSignalSimulator.h.
Member Function Documentation
ComputeT2SignalMatrixElements()
void anima::EPGSignalSimulator::ComputeT2SignalMatrixElements (double t1Value, double t2Value, double b1Value) protected
Definition at line 109 of file animaEPGSignalSimulator.cxx.
Referenced by GetValue().
GetValue()
EPGSignalSimulator::RealVectorType & anima::EPGSignalSimulator::GetValue (double t1Value, double t2Value, double b1Value, double m0Value)
Definition at line 26 of file animaEPGSignalSimulator.cxx.
References ComputeT2SignalMatrixElements().
Referenced by anima::T2EPGRelaxometryCostFunction::GetValue(), anima::MultiT2EPGRelaxometryCostFunction::GetValue(), anima::B1T2RelaxometryDistributionCostFunction::GetValue(), anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), and anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
SetB1OnExcitationAngle()
void anima::EPGSignalSimulator::SetB1OnExcitationAngle (bool val) inline
Definition at line 27 of file animaEPGSignalSimulator.h.
Referenced by anima::T2EPGRelaxometryCostFunction::GetValue(), anima::MultiT2EPGRelaxometryCostFunction::GetValue(), anima::B1T2RelaxometryDistributionCostFunction::GetValue(), anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), and anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
SetEchoSpacing()
void anima::EPGSignalSimulator::SetEchoSpacing (double val) inline
Definition at line 21 of file animaEPGSignalSimulator.h.
Referenced by anima::T2EPGRelaxometryCostFunction::GetValue(), anima::MultiT2EPGRelaxometryCostFunction::GetValue(), anima::B1T2RelaxometryDistributionCostFunction::GetValue(), anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), and anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
SetExcitationFlipAngle()
void anima::EPGSignalSimulator::SetExcitationFlipAngle (double val) inline
Definition at line 22 of file animaEPGSignalSimulator.h.
Referenced by anima::T2EPGRelaxometryCostFunction::GetValue(), anima::MultiT2EPGRelaxometryCostFunction::GetValue(), anima::B1T2RelaxometryDistributionCostFunction::GetValue(), anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), and anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
SetFlipAngle()
void anima::EPGSignalSimulator::SetFlipAngle (double val) inline
Definition at line 23 of file animaEPGSignalSimulator.h.
Referenced by anima::T2EPGRelaxometryCostFunction::GetValue(), anima::MultiT2EPGRelaxometryCostFunction::GetValue(), anima::B1T2RelaxometryDistributionCostFunction::GetValue(), anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), and anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
SetNumberOfEchoes()
void anima::EPGSignalSimulator::SetNumberOfEchoes (unsigned int val) inline
Definition at line 25 of file animaEPGSignalSimulator.h.
Referenced by anima::T2EPGRelaxometryCostFunction::GetValue(), anima::MultiT2EPGRelaxometryCostFunction::GetValue(), anima::B1T2RelaxometryDistributionCostFunction::GetValue(), anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData(), and anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
The documentation for this class was generated from the following files:
animaEPGSignalSimulator.h
animaEPGSignalSimulator.cxx