ANIMA: anima::TLinksFilter< TInput, TOutput > Class Template Reference
anima::TLinksFilter< TInput, TOutput > Class Template Reference
Class computing the probability maps that are used to create the t-links.
#include <animaTLinksFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::VariableSizeMatrix< NumericType > DoubleVariableSizeMatrixType
typedef itk::ImageRegionConstIterator< TInput > InConstIteratorType
typedef itk::ImageRegionIterator< TInput > InIteratorType
typedef TInput::ConstPointer InputImageConstPointer
typedef TInput::Pointer InputImagePointer
typedef TInput::PixelType InputPixelType
typedef itk::Matrix< double, 1, 1 > MatrixTypeRes
typedef double NumericType
typedef TOutput::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutput::PixelType OutputPixelType
typedef itk::ImageRegionIterator< TOutput > OutRegionIteratorType
typedef double PixelTypeD
typedef unsigned char PixelTypeUC
typedef itk::SmartPointer< Self > Pointer
typedef itk::ImageRegionConstIterator< TSeedMask > SeedMaskRegionConstIteratorType
typedef itk::ImageRegionIterator< TSeedMask > SeedMaskRegionIteratorType
typedef itk::ImageRegionConstIterator< TSeedProba > SeedProbaRegionConstIteratorType
typedef TLinksFilter Self
typedef itk::ImageToImageFilter< TInput,TOutput > Superclass
typedef itk::Image< PixelTypeUC, 3 > TSeedMask
typedef TSeedMask::Pointer TSeedMaskPointer
typedef itk::Image< PixelTypeD, 3 > TSeedProba
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual float GetAlpha ()
virtual float GetMultiVarSinks ()
virtual float GetMultiVarSources ()
virtual const char * GetNameOfClass () const
virtual unsigned int GetNbModalities ()
TOutput * GetOutputSinks ()
TOutput * GetOutputSources ()
TLinkMode GetTLinkMode ()
virtual bool GetVerbose ()
virtual void SetAlpha (float _arg)
void SetInputImage (unsigned int i, const TInput *image)
void SetInputSeedSinksMask (const TSeedMask *mask)
void SetInputSeedSinksProba (const TSeedProba *mask)
void SetInputSeedSourcesMask (const TSeedMask *mask)
void SetInputSeedSourcesProba (const TSeedProba *mask)
virtual void SetMultiVarSinks (float _arg)
virtual void SetMultiVarSources (float _arg)
virtual void SetNbModalities (unsigned int _arg)
void SetTLinkMode (TLinkMode m)
void SetTol (const double tol)
virtual void SetVerbose (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void computeSingleGaussian ()
void computeSingleGaussianSeeds (TSeedMask::ConstPointer seedMask, OutputImagePointer output, float multiVar, TSeedMask::ConstPointer seedMaskOpp=NULL)
void computeStrem ()
void GenerateData () ITK_OVERRIDE
TSeedMask::ConstPointer GetInputSeedSinksMask ()
TSeedProba::ConstPointer GetInputSeedSinksProba ()
TSeedMask::ConstPointer GetInputSeedSourcesMask ()
TSeedProba::ConstPointer GetInputSeedSourcesProba ()
itk::DataObject::Pointer MakeOutput (unsigned int idx)
TLinksFilter ()
virtual ~TLinksFilter ()
Detailed Description
template<typename TInput, typename TOutput>
class anima::TLinksFilter< TInput, TOutput >
Class computing the probability maps that are used to create the t-links.
single gaussian method computes probability maps using binary masks as input.
Definition at line 22 of file animaTLinksFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<const Self> anima::TLinksFilter< TInput, TOutput >::ConstPointer
Definition at line 30 of file animaTLinksFilter.h.
DoubleVariableSizeMatrixType
template<typename TInput , typename TOutput > typedef itk::VariableSizeMatrix<NumericType> anima::TLinksFilter< TInput, TOutput >::DoubleVariableSizeMatrixType
Definition at line 60 of file animaTLinksFilter.h.
InConstIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionConstIterator< TInput > anima::TLinksFilter< TInput, TOutput >::InConstIteratorType
Definition at line 42 of file animaTLinksFilter.h.
InIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TInput > anima::TLinksFilter< TInput, TOutput >::InIteratorType
Definition at line 43 of file animaTLinksFilter.h.
InputImageConstPointer
template<typename TInput , typename TOutput > typedef TInput::ConstPointer anima::TLinksFilter< TInput, TOutput >::InputImageConstPointer
Definition at line 41 of file animaTLinksFilter.h.
InputImagePointer
template<typename TInput , typename TOutput > typedef TInput::Pointer anima::TLinksFilter< TInput, TOutput >::InputImagePointer
Definition at line 40 of file animaTLinksFilter.h.
InputPixelType
template<typename TInput , typename TOutput > typedef TInput::PixelType anima::TLinksFilter< TInput, TOutput >::InputPixelType
Image typedef support
Definition at line 39 of file animaTLinksFilter.h.
MatrixTypeRes
template<typename TInput , typename TOutput > typedef itk::Matrix<double, 1, 1> anima::TLinksFilter< TInput, TOutput >::MatrixTypeRes
Definition at line 61 of file animaTLinksFilter.h.
NumericType
template<typename TInput , typename TOutput > typedef double anima::TLinksFilter< TInput, TOutput >::NumericType
Definition at line 59 of file animaTLinksFilter.h.
OutputImagePointer
template<typename TInput , typename TOutput > typedef TOutput::Pointer anima::TLinksFilter< TInput, TOutput >::OutputImagePointer
Definition at line 46 of file animaTLinksFilter.h.
OutputImageRegionType
template<typename TInput , typename TOutput > typedef Superclass::OutputImageRegionType anima::TLinksFilter< TInput, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 87 of file animaTLinksFilter.h.
OutputPixelType
template<typename TInput , typename TOutput > typedef TOutput::PixelType anima::TLinksFilter< TInput, TOutput >::OutputPixelType
Definition at line 45 of file animaTLinksFilter.h.
OutRegionIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TOutput > anima::TLinksFilter< TInput, TOutput >::OutRegionIteratorType
Definition at line 47 of file animaTLinksFilter.h.
PixelTypeD
template<typename TInput , typename TOutput > typedef double anima::TLinksFilter< TInput, TOutput >::PixelTypeD
Definition at line 49 of file animaTLinksFilter.h.
PixelTypeUC
template<typename TInput , typename TOutput > typedef unsigned char anima::TLinksFilter< TInput, TOutput >::PixelTypeUC
Definition at line 53 of file animaTLinksFilter.h.
Pointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<Self> anima::TLinksFilter< TInput, TOutput >::Pointer
Definition at line 29 of file animaTLinksFilter.h.
SeedMaskRegionConstIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionConstIterator< TSeedMask > anima::TLinksFilter< TInput, TOutput >::SeedMaskRegionConstIteratorType
Definition at line 57 of file animaTLinksFilter.h.
SeedMaskRegionIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TSeedMask > anima::TLinksFilter< TInput, TOutput >::SeedMaskRegionIteratorType
Definition at line 56 of file animaTLinksFilter.h.
SeedProbaRegionConstIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionConstIterator< TSeedProba > anima::TLinksFilter< TInput, TOutput >::SeedProbaRegionConstIteratorType
Definition at line 51 of file animaTLinksFilter.h.
Self
template<typename TInput , typename TOutput > typedef TLinksFilter anima::TLinksFilter< TInput, TOutput >::Self
Standard class typedefs.
Definition at line 27 of file animaTLinksFilter.h.
Superclass
template<typename TInput , typename TOutput > typedef itk::ImageToImageFilter< TInput ,TOutput > anima::TLinksFilter< TInput, TOutput >::Superclass
Definition at line 28 of file animaTLinksFilter.h.
TSeedMask
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeUC,3> anima::TLinksFilter< TInput, TOutput >::TSeedMask
Definition at line 54 of file animaTLinksFilter.h.
TSeedMaskPointer
template<typename TInput , typename TOutput > typedef TSeedMask::Pointer anima::TLinksFilter< TInput, TOutput >::TSeedMaskPointer
Definition at line 55 of file animaTLinksFilter.h.
TSeedProba
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeD,3> anima::TLinksFilter< TInput, TOutput >::TSeedProba
Definition at line 50 of file animaTLinksFilter.h.
Constructor & Destructor Documentation
TLinksFilter()
template<typename TInput , typename TOutput > anima::TLinksFilter< TInput, TOutput >::TLinksFilter () inline protected
Definition at line 105 of file animaTLinksFilter.h.
References anima::TLinksFilter< TInput, TOutput >::MakeOutput(), and singleGaussianTLink.
~TLinksFilter()
template<typename TInput , typename TOutput > virtual anima::TLinksFilter< TInput, TOutput >::~TLinksFilter () inline protected virtual
Definition at line 125 of file animaTLinksFilter.h.
References anima::TLinksFilter< TInput, TOutput >::computeSingleGaussian(), anima::TLinksFilter< TInput, TOutput >::computeSingleGaussianSeeds(), anima::TLinksFilter< TInput, TOutput >::computeStrem(), anima::TLinksFilter< TInput, TOutput >::GenerateData(), anima::TLinksFilter< TInput, TOutput >::GetInputSeedSinksMask(), anima::TLinksFilter< TInput, TOutput >::GetInputSeedSinksProba(), anima::TLinksFilter< TInput, TOutput >::GetInputSeedSourcesMask(), anima::TLinksFilter< TInput, TOutput >::GetInputSeedSourcesProba(), and anima::TLinksFilter< TInput, TOutput >::MakeOutput().
Member Function Documentation
computeSingleGaussian()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::computeSingleGaussian () protected
Definition at line 208 of file animaTLinksFilter.hxx.
References anima::TLinksFilter< TInput, TOutput >::computeSingleGaussianSeeds().
Referenced by anima::TLinksFilter< TInput, TOutput >::computeStrem(), and anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
computeSingleGaussianSeeds()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::computeSingleGaussianSeeds (TSeedMask::ConstPointer seedMask, OutputImagePointer output, float multiVar, TSeedMask::ConstPointer seedMaskOpp = NULL) protected
Definition at line 225 of file animaTLinksFilter.hxx.
Referenced by anima::TLinksFilter< TInput, TOutput >::computeSingleGaussian(), and anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
computeStrem()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::computeStrem () protected
Definition at line 183 of file animaTLinksFilter.hxx.
References anima::TLinksFilter< TInput, TOutput >::computeSingleGaussian().
Referenced by anima::TLinksFilter< TInput, TOutput >::GenerateData(), and anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
CreateAnother()
template<typename TInput , typename TOutput > virtual::itk::LightObject::Pointer anima::TLinksFilter< TInput, TOutput >::CreateAnother (void) const
GenerateData()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::GenerateData () protected
Definition at line 123 of file animaTLinksFilter.hxx.
References anima::TLinksFilter< TInput, TOutput >::computeStrem(), singleGaussianTLink, and stremTLink.
Referenced by anima::TLinksFilter< TInput, TOutput >::GetOutputSinks(), and anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
GetAlpha()
template<typename TInput , typename TOutput > virtual float anima::TLinksFilter< TInput, TOutput >::GetAlpha () virtual
GetInputSeedSinksMask()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::ConstPointer anima::TLinksFilter< TInput, TOutput >::GetInputSeedSinksMask () protected
Definition at line 66 of file animaTLinksFilter.hxx.
Referenced by anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
GetInputSeedSinksProba()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::TLinksFilter< TInput, TOutput >::GetInputSeedSinksProba () protected
Definition at line 80 of file animaTLinksFilter.hxx.
Referenced by anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
GetInputSeedSourcesMask()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::ConstPointer anima::TLinksFilter< TInput, TOutput >::GetInputSeedSourcesMask () protected
Definition at line 59 of file animaTLinksFilter.hxx.
Referenced by anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
GetInputSeedSourcesProba()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::TLinksFilter< TInput, TOutput >::GetInputSeedSourcesProba () protected
Definition at line 73 of file animaTLinksFilter.hxx.
Referenced by anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
GetMultiVarSinks()
template<typename TInput , typename TOutput > virtual float anima::TLinksFilter< TInput, TOutput >::GetMultiVarSinks () virtual
GetMultiVarSources()
template<typename TInput , typename TOutput > virtual float anima::TLinksFilter< TInput, TOutput >::GetMultiVarSources () virtual
GetNameOfClass()
template<typename TInput , typename TOutput > virtual const char* anima::TLinksFilter< TInput, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetNbModalities()
template<typename TInput , typename TOutput > virtual unsigned int anima::TLinksFilter< TInput, TOutput >::GetNbModalities () virtual
GetOutputSinks()
template<typename TInput , typename TOutput > TOutput * anima::TLinksFilter< TInput, TOutput >::GetOutputSinks ()
Definition at line 114 of file animaTLinksFilter.hxx.
References anima::TLinksFilter< TInput, TOutput >::GenerateData().
Referenced by anima::TLinksFilter< TInput, TOutput >::SetTLinkMode().
GetOutputSources()
template<typename TInput , typename TOutput > TOutput * anima::TLinksFilter< TInput, TOutput >::GetOutputSources ()
Definition at line 108 of file animaTLinksFilter.hxx.
Referenced by anima::TLinksFilter< TInput, TOutput >::SetTLinkMode().
GetTLinkMode()
template<typename TInput , typename TOutput > TLinkMode anima::TLinksFilter< TInput, TOutput >::GetTLinkMode () inline
Definition at line 74 of file animaTLinksFilter.h.
GetVerbose()
template<typename TInput , typename TOutput > virtual bool anima::TLinksFilter< TInput, TOutput >::GetVerbose () virtual
MakeOutput()
template<typename TInput , typename TOutput > itk::DataObject::Pointer anima::TLinksFilter< TInput, TOutput >::MakeOutput (unsigned int idx) protected
Create the Output
Definition at line 87 of file animaTLinksFilter.hxx.
Referenced by anima::TLinksFilter< TInput, TOutput >::TLinksFilter(), and anima::TLinksFilter< TInput, TOutput >::~TLinksFilter().
New()
template<typename TInput , typename TOutput > static Pointer anima::TLinksFilter< TInput, TOutput >::New () static
Method for creation through the object factory.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter(), and anima::GraphCutFilter< TInput, TOutput >::GraphCutFilter().
SetAlpha()
template<typename TInput , typename TOutput > virtual void anima::TLinksFilter< TInput, TOutput >::SetAlpha (float _arg) virtual
SetInputImage()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::SetInputImage (unsigned int i, const TInput * image)
The mri images.
Definition at line 10 of file animaTLinksFilter.hxx.
SetInputSeedSinksMask()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::SetInputSeedSinksMask (const TSeedMask * mask)
Definition at line 35 of file animaTLinksFilter.hxx.
SetInputSeedSinksProba()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::SetInputSeedSinksProba (const TSeedProba * mask)
Definition at line 51 of file animaTLinksFilter.hxx.
SetInputSeedSourcesMask()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::SetInputSeedSourcesMask (const TSeedMask * mask)
probabilities containing the seeds for the object and the background or binary masks containing the seeds for the object and the background
Definition at line 27 of file animaTLinksFilter.hxx.
SetInputSeedSourcesProba()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::SetInputSeedSourcesProba (const TSeedProba * mask)
Definition at line 43 of file animaTLinksFilter.hxx.
SetMultiVarSinks()
template<typename TInput , typename TOutput > virtual void anima::TLinksFilter< TInput, TOutput >::SetMultiVarSinks (float _arg) virtual
SetMultiVarSources()
template<typename TInput , typename TOutput > virtual void anima::TLinksFilter< TInput, TOutput >::SetMultiVarSources (float _arg) virtual
SetNbModalities()
template<typename TInput , typename TOutput > virtual void anima::TLinksFilter< TInput, TOutput >::SetNbModalities (unsigned int _arg) virtual
SetTLinkMode()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::SetTLinkMode (TLinkMode m) inline
Definition at line 75 of file animaTLinksFilter.h.
References anima::TLinksFilter< TInput, TOutput >::GetOutputSinks(), and anima::TLinksFilter< TInput, TOutput >::GetOutputSources().
SetTol()
template<typename TInput , typename TOutput > void anima::TLinksFilter< TInput, TOutput >::SetTol (const double tol) inline
Definition at line 80 of file animaTLinksFilter.h.
SetVerbose()
template<typename TInput , typename TOutput > virtual void anima::TLinksFilter< TInput, TOutput >::SetVerbose (bool _arg) virtual
The documentation for this class was generated from the following files:
animaTLinksFilter.h
animaTLinksFilter.hxx