ANIMA: anima::GaussianMCMVariableProjectionSingleValuedCostFunction Class Reference
anima::GaussianMCMVariableProjectionSingleValuedCostFunction Class Reference
#include <animaGaussianMCMVariableProjectionSingleValuedCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef InternalCostType::Pointer InternalCostPointer
typedef anima::GaussianMCMVariableProjectionCost InternalCostType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef GaussianMCMVariableProjectionSingleValuedCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
std::vector< double > & GetOptimalWeights ()
double GetSigmaSquare ()
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetInternalCost (InternalCostPointer _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
GaussianMCMVariableProjectionSingleValuedCostFunction ()
virtual ~GaussianMCMVariableProjectionSingleValuedCostFunction () ITK_OVERRIDE
Detailed Description
Definition at line 10 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::GaussianMCMVariableProjectionSingleValuedCostFunction::ConstPointer
Definition at line 17 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::GaussianMCMVariableProjectionSingleValuedCostFunction::DerivativeType
Definition at line 25 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
InternalCostPointer
typedef InternalCostType::Pointer anima::GaussianMCMVariableProjectionSingleValuedCostFunction::InternalCostPointer
Definition at line 29 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
InternalCostType
typedef anima::GaussianMCMVariableProjectionCost anima::GaussianMCMVariableProjectionSingleValuedCostFunction::InternalCostType
Definition at line 28 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::GaussianMCMVariableProjectionSingleValuedCostFunction::MeasureType
Definition at line 24 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::GaussianMCMVariableProjectionSingleValuedCostFunction::ParametersType
Definition at line 26 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::GaussianMCMVariableProjectionSingleValuedCostFunction::Pointer
Definition at line 16 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
Self
typedef GaussianMCMVariableProjectionSingleValuedCostFunction anima::GaussianMCMVariableProjectionSingleValuedCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::GaussianMCMVariableProjectionSingleValuedCostFunction::Superclass
Definition at line 15 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
Constructor & Destructor Documentation
GaussianMCMVariableProjectionSingleValuedCostFunction()
anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GaussianMCMVariableProjectionSingleValuedCostFunction () inline protected
Definition at line 42 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
~GaussianMCMVariableProjectionSingleValuedCostFunction()
virtual anima::GaussianMCMVariableProjectionSingleValuedCostFunction::~GaussianMCMVariableProjectionSingleValuedCostFunction () inline protected virtual
Definition at line 47 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::GaussianMCMVariableProjectionSingleValuedCostFunction::CreateAnother (void) const
GetDerivative()
void anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 31 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.cxx.
References GetSigmaSquare().
Referenced by GetValue().
GetNameOfClass()
virtual const char* anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetNumberOfParameters () const
Definition at line 8 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.cxx.
References GetValue().
GetOptimalWeights()
std::vector< double > & anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetOptimalWeights ()
Definition at line 51 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.cxx.
Referenced by GetSigmaSquare().
GetSigmaSquare()
double anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetSigmaSquare ()
Definition at line 44 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.cxx.
References GetOptimalWeights().
Referenced by GetDerivative().
GetValue()
GaussianMCMVariableProjectionSingleValuedCostFunction::MeasureType anima::GaussianMCMVariableProjectionSingleValuedCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 18 of file animaGaussianMCMVariableProjectionSingleValuedCostFunction.cxx.
References GetDerivative().
Referenced by GetNumberOfParameters().
New()
static Pointer anima::GaussianMCMVariableProjectionSingleValuedCostFunction::New () static
SetInternalCost()
virtual void anima::GaussianMCMVariableProjectionSingleValuedCostFunction::SetInternalCost (InternalCostPointer _arg) virtual
The documentation for this class was generated from the following files:
animaGaussianMCMVariableProjectionSingleValuedCostFunction.h
animaGaussianMCMVariableProjectionSingleValuedCostFunction.cxx