ANIMA: anima::SimuBlochCoherentGRE< TImage > Class Template Reference
anima::SimuBlochCoherentGRE< TImage > Class Template Reference
#include <animaSimuBlochCoherentGRE.h>
Public Types
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef SimuBlochCoherentGRE Self
typedef itk::ImageToImageFilter< TImage, TImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual float GetFA ()
virtual const char * GetNameOfClass () const
virtual float GetTE ()
virtual float GetTR ()
virtual void SetFA (float _arg)
void SetInputM0 (const TImage *M0)
void SetInputT1 (const TImage *T1)
void SetInputT2 (const TImage *T2)
void SetInputT2s (const TImage *T2s)
virtual void SetTE (float _arg)
virtual void SetTR (float _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
SimuBlochCoherentGRE ()
virtual void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~SimuBlochCoherentGRE ()
Detailed Description
template<class TImage>
class anima::SimuBlochCoherentGRE< TImage >
Definition at line 9 of file animaSimuBlochCoherentGRE.h.
Member Typedef Documentation
OutputImageRegionType
template<class TImage > typedef Superclass::OutputImageRegionType anima::SimuBlochCoherentGRE< TImage >::OutputImageRegionType
Definition at line 17 of file animaSimuBlochCoherentGRE.h.
Pointer
template<class TImage > typedef itk::SmartPointer<Self> anima::SimuBlochCoherentGRE< TImage >::Pointer
Definition at line 15 of file animaSimuBlochCoherentGRE.h.
Self
template<class TImage > typedef SimuBlochCoherentGRE anima::SimuBlochCoherentGRE< TImage >::Self
Standard class typedefs.
Definition at line 13 of file animaSimuBlochCoherentGRE.h.
Superclass
template<class TImage > typedef itk::ImageToImageFilter<TImage, TImage> anima::SimuBlochCoherentGRE< TImage >::Superclass
Definition at line 14 of file animaSimuBlochCoherentGRE.h.
Constructor & Destructor Documentation
SimuBlochCoherentGRE()
template<class TImage > anima::SimuBlochCoherentGRE< TImage >::SimuBlochCoherentGRE () protected
Definition at line 46 of file animaSimuBlochCoherentGRE.hxx.
~SimuBlochCoherentGRE()
template<class TImage > virtual anima::SimuBlochCoherentGRE< TImage >::~SimuBlochCoherentGRE () inline protected virtual
Definition at line 49 of file animaSimuBlochCoherentGRE.h.
References anima::SimuBlochCoherentGRE< TImage >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<class TImage > virtual::itk::LightObject::Pointer anima::SimuBlochCoherentGRE< TImage >::CreateAnother (void) const
GetFA()
template<class TImage > virtual float anima::SimuBlochCoherentGRE< TImage >::GetFA () virtual
GetNameOfClass()
template<class TImage > virtual const char* anima::SimuBlochCoherentGRE< TImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetTE()
template<class TImage > virtual float anima::SimuBlochCoherentGRE< TImage >::GetTE () virtual
GetTR()
template<class TImage > virtual float anima::SimuBlochCoherentGRE< TImage >::GetTR () virtual
New()
template<class TImage > static Pointer anima::SimuBlochCoherentGRE< TImage >::New () static
Method for creation through the object factory.
SetFA()
template<class TImage > virtual void anima::SimuBlochCoherentGRE< TImage >::SetFA (float _arg) virtual
SetInputM0()
template<class TImage > void anima::SimuBlochCoherentGRE< TImage >::SetInputM0 (const TImage * M0)
M0 image / Rho map
Definition at line 64 of file animaSimuBlochCoherentGRE.hxx.
SetInputT1()
template<class TImage > void anima::SimuBlochCoherentGRE< TImage >::SetInputT1 (const TImage * T1)
T1 map
Definition at line 52 of file animaSimuBlochCoherentGRE.hxx.
SetInputT2()
template<class TImage > void anima::SimuBlochCoherentGRE< TImage >::SetInputT2 (const TImage * T2)
T2 map
Definition at line 70 of file animaSimuBlochCoherentGRE.hxx.
References anima::SimuBlochCoherentGRE< TImage >::ThreadedGenerateData().
SetInputT2s()
template<class TImage > void anima::SimuBlochCoherentGRE< TImage >::SetInputT2s (const TImage * T2s)
T2s map
Definition at line 58 of file animaSimuBlochCoherentGRE.hxx.
SetTE()
template<class TImage > virtual void anima::SimuBlochCoherentGRE< TImage >::SetTE (float _arg) virtual
SetTR()
template<class TImage > virtual void anima::SimuBlochCoherentGRE< TImage >::SetTR (float _arg) virtual
ThreadedGenerateData()
template<class TImage > void anima::SimuBlochCoherentGRE< TImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected virtual
Does the real work.
Definition at line 78 of file animaSimuBlochCoherentGRE.hxx.
Referenced by anima::SimuBlochCoherentGRE< TImage >::SetInputT2(), and anima::SimuBlochCoherentGRE< TImage >::~SimuBlochCoherentGRE().
The documentation for this class was generated from the following files:
animaSimuBlochCoherentGRE.h
animaSimuBlochCoherentGRE.hxx