ANIMA: anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType > Class Template Reference
anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType > Class Template Reference
#include <animaGMMT2RelaxometryEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef NNLSOptimizerType::MatrixType DataMatrixType
typedef InputImageType::IndexType IndexType
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef NNLSOptimizerType::Pointer NNLSOptimizerPointer
typedef anima::NNLSOptimizer NNLSOptimizerType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef VectorOutputImageType::PixelType OutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef GMMT2RelaxometryEstimationImageFilter Self
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef NNLSOptimizerType::ParametersType T2VectorType
typedef itk::Image< TPixelScalarType, 3 > TInputImage
typedef itk::Image< TPixelScalarType, 3 > TOutputImage
typedef VectorOutputImageType::Pointer VectorOutputImagePointer
typedef itk::VectorImage< TPixelScalarType, 3 > VectorOutputImageType
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::Image< TPixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< TPixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
InputImageType * GetB1OutputImage ()
InputImageType * GetM0OutputImage ()
InputImageType * GetMWFOutputImage ()
virtual const char * GetNameOfClass () const
InputImageType * GetT1Map ()
VectorOutputImageType * GetWeightsImage ()
virtual void SetAverageSignalThreshold (double _arg)
virtual void SetB1OnExcitationAngle (bool _arg)
virtual void SetB1Tolerance (double _arg)
virtual void SetEchoSpacing (double _arg)
virtual void SetGaussianIntegralTolerance (double _arg)
void SetGaussianMeans (std::string fileName)
void SetGaussianVariances (std::string fileName)
virtual void SetLowerT2Bound (double _arg)
void SetT1Map (InputImageType *map)
virtual void SetT2ExcitationFlipAngle (double _arg)
void SetT2FlipAngles (std::vector< double > &flipAngles)
void SetT2FlipAngles (double singleAngle, unsigned int numAngles)
virtual void SetT2IntegrationStep (double _arg)
virtual void SetUpperT2Bound (double _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
bool endConditionReached (double b1Value, double previousB1Value)
GMMT2RelaxometryEstimationImageFilter ()
void PrepareGaussianValues ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~GMMT2RelaxometryEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::Image< TPixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< TPixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class TPixelScalarType>
class anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >
Definition at line 13 of file animaGMMT2RelaxometryEstimationImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TPixelScalarType > typedef itk::SmartPointer<const Self> anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ConstPointer
Definition at line 23 of file animaGMMT2RelaxometryEstimationImageFilter.h.
DataMatrixType
template<class TPixelScalarType > typedef NNLSOptimizerType::MatrixType anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::DataMatrixType
Definition at line 48 of file animaGMMT2RelaxometryEstimationImageFilter.h.
IndexType
template<class TPixelScalarType > typedef InputImageType::IndexType anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::IndexType
Definition at line 33 of file animaGMMT2RelaxometryEstimationImageFilter.h.
InputImagePointer
template<class TPixelScalarType > typedef InputImageType::Pointer anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImagePointer
Definition at line 37 of file animaGMMT2RelaxometryEstimationImageFilter.h.
InputImageRegionType
template<class TPixelScalarType > typedef Superclass::InputImageRegionType anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImageRegionType
Definition at line 43 of file animaGMMT2RelaxometryEstimationImageFilter.h.
InputImageType
template<class TPixelScalarType > typedef TInputImage anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImageType
Image typedef support
Definition at line 32 of file animaGMMT2RelaxometryEstimationImageFilter.h.
MaskImageType
template<class TPixelScalarType > typedef Superclass::MaskImageType anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::MaskImageType
Superclass typedefs.
Definition at line 42 of file animaGMMT2RelaxometryEstimationImageFilter.h.
NNLSOptimizerPointer
template<class TPixelScalarType > typedef NNLSOptimizerType::Pointer anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::NNLSOptimizerPointer
Definition at line 47 of file animaGMMT2RelaxometryEstimationImageFilter.h.
NNLSOptimizerType
template<class TPixelScalarType > typedef anima::NNLSOptimizer anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::NNLSOptimizerType
Definition at line 46 of file animaGMMT2RelaxometryEstimationImageFilter.h.
OutputImagePointer
template<class TPixelScalarType > typedef OutputImageType::Pointer anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImagePointer
Definition at line 38 of file animaGMMT2RelaxometryEstimationImageFilter.h.
OutputImageRegionType
template<class TPixelScalarType > typedef Superclass::OutputImageRegionType anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImageRegionType
Definition at line 44 of file animaGMMT2RelaxometryEstimationImageFilter.h.
OutputImageType
template<class TPixelScalarType > typedef TOutputImage anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImageType
Definition at line 34 of file animaGMMT2RelaxometryEstimationImageFilter.h.
OutputVectorType
template<class TPixelScalarType > typedef VectorOutputImageType::PixelType anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputVectorType
Definition at line 36 of file animaGMMT2RelaxometryEstimationImageFilter.h.
Pointer
template<class TPixelScalarType > typedef itk::SmartPointer<Self> anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::Pointer
Definition at line 22 of file animaGMMT2RelaxometryEstimationImageFilter.h.
Self
template<class TPixelScalarType > typedef GMMT2RelaxometryEstimationImageFilter anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::Self
Standard class typedefs.
Definition at line 18 of file animaGMMT2RelaxometryEstimationImageFilter.h.
Superclass
template<class TPixelScalarType > typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::Superclass
Definition at line 21 of file animaGMMT2RelaxometryEstimationImageFilter.h.
T2VectorType
template<class TPixelScalarType > typedef NNLSOptimizerType::ParametersType anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::T2VectorType
Definition at line 49 of file animaGMMT2RelaxometryEstimationImageFilter.h.
TInputImage
template<class TPixelScalarType > typedef itk::Image<TPixelScalarType, 3> anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::TInputImage
Definition at line 19 of file animaGMMT2RelaxometryEstimationImageFilter.h.
TOutputImage
template<class TPixelScalarType > typedef itk::Image<TPixelScalarType, 3> anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::TOutputImage
Definition at line 20 of file animaGMMT2RelaxometryEstimationImageFilter.h.
VectorOutputImagePointer
template<class TPixelScalarType > typedef VectorOutputImageType::Pointer anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::VectorOutputImagePointer
Definition at line 39 of file animaGMMT2RelaxometryEstimationImageFilter.h.
VectorOutputImageType
template<class TPixelScalarType > typedef itk::VectorImage<TPixelScalarType, 3> anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::VectorOutputImageType
Definition at line 35 of file animaGMMT2RelaxometryEstimationImageFilter.h.
Constructor & Destructor Documentation
GMMT2RelaxometryEstimationImageFilter()
template<class TPixelScalarType > anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GMMT2RelaxometryEstimationImageFilter () inline protected
Definition at line 79 of file animaGMMT2RelaxometryEstimationImageFilter.h.
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GMMT2RelaxometryEstimationImageFilter().
~GMMT2RelaxometryEstimationImageFilter()
template<class TPixelScalarType > virtual anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GMMT2RelaxometryEstimationImageFilter () inline protected virtual
Definition at line 113 of file animaGMMT2RelaxometryEstimationImageFilter.h.
References anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::BeforeThreadedGenerateData(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::CheckComputationMask(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::endConditionReached(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GMMT2RelaxometryEstimationImageFilter(), anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::PrepareGaussianValues(), and anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
Definition at line 92 of file animaGMMT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GMMT2RelaxometryEstimationImageFilter().
CheckComputationMask()
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
Definition at line 120 of file animaGMMT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GMMT2RelaxometryEstimationImageFilter().
CreateAnother()
template<class TPixelScalarType > virtual::itk::LightObject::Pointer anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::CreateAnother (void) const
endConditionReached()
template<class TPixelScalarType > bool anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::endConditionReached (double b1Value, double previousB1Value) protected
Definition at line 363 of file animaGMMT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GMMT2RelaxometryEstimationImageFilter().
GetB1OutputImage()
template<class TPixelScalarType > InputImageType* anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetB1OutputImage () inline
Definition at line 62 of file animaGMMT2RelaxometryEstimationImageFilter.h.
GetM0OutputImage()
template<class TPixelScalarType > InputImageType* anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetM0OutputImage () inline
Definition at line 60 of file animaGMMT2RelaxometryEstimationImageFilter.h.
GetMWFOutputImage()
template<class TPixelScalarType > InputImageType* anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetMWFOutputImage () inline
Definition at line 61 of file animaGMMT2RelaxometryEstimationImageFilter.h.
GetNameOfClass()
template<class TPixelScalarType > virtual const char* anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
GetT1Map()
template<class TPixelScalarType > InputImageType* anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetT1Map () inline
Definition at line 56 of file animaGMMT2RelaxometryEstimationImageFilter.h.
GetWeightsImage()
template<class TPixelScalarType > VectorOutputImageType* anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetWeightsImage () inline
Definition at line 63 of file animaGMMT2RelaxometryEstimationImageFilter.h.
References anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetGaussianMeans(), and anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetGaussianVariances().
New()
template<class TPixelScalarType > static Pointer anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::New () static
Method for creation through the object factory.
PrepareGaussianValues()
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::PrepareGaussianValues () protected
Definition at line 374 of file animaGMMT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GMMT2RelaxometryEstimationImageFilter().
SetAverageSignalThreshold()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetAverageSignalThreshold (double _arg) virtual
SetB1OnExcitationAngle()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1OnExcitationAngle (bool _arg) virtual
SetB1Tolerance()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1Tolerance (double _arg) virtual
SetEchoSpacing()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetEchoSpacing (double _arg) virtual
SetGaussianIntegralTolerance()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetGaussianIntegralTolerance (double _arg) virtual
SetGaussianMeans()
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetGaussianMeans (std::string fileName)
Definition at line 22 of file animaGMMT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetWeightsImage().
SetGaussianVariances()
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetGaussianVariances (std::string fileName)
Definition at line 57 of file animaGMMT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetWeightsImage().
SetLowerT2Bound()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetLowerT2Bound (double _arg) virtual
SetT1Map()
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT1Map (InputImageType * map) inline
Definition at line 55 of file animaGMMT2RelaxometryEstimationImageFilter.h.
SetT2ExcitationFlipAngle()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2ExcitationFlipAngle (double _arg) virtual
SetT2FlipAngles() [1/2]
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 75 of file animaGMMT2RelaxometryEstimationImageFilter.h.
SetT2FlipAngles() [2/2]
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2FlipAngles (double singleAngle, unsigned int numAngles) inline
Definition at line 76 of file animaGMMT2RelaxometryEstimationImageFilter.h.
SetT2IntegrationStep()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2IntegrationStep (double _arg) virtual
SetUpperT2Bound()
template<class TPixelScalarType > virtual void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetUpperT2Bound (double _arg) virtual
ThreadedGenerateData()
template<class TPixelScalarType > void anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 168 of file animaGMMT2RelaxometryEstimationImageFilter.hxx.
References anima::EPGSignalSimulator::GetValue(), anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), and anima::EPGSignalSimulator::SetNumberOfEchoes().
Referenced by anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >::~GMMT2RelaxometryEstimationImageFilter().
The documentation for this class was generated from the following files:
animaGMMT2RelaxometryEstimationImageFilter.h
animaGMMT2RelaxometryEstimationImageFilter.hxx