ANIMA: anima::dtiTractographyImageFilter Class Reference
anima::dtiTractographyImageFilter Class Reference
#include <animaDTITractographyImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef DTIInterpolatorType::Pointer DTIInterpolatorPointer
typedef itk::LinearInterpolateImageFunction< ModelImageType > DTIInterpolatorType
typedef Superclass::ModelImageType ModelImageType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::PointType PointType
typedef dtiTractographyImageFilter Self
typedef anima::BaseTractographyImageFilter Superclass
typedef Superclass::VectorType VectorType
Public Types inherited from anima::BaseTractographyImageFilter
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, 3 > ContinuousIndexType
typedef std::vector< std::pair< FiberProgressType, FiberType > > FiberProcessVectorType
enum FiberProgressType {
Forward,
Backward,
Both
}
typedef std::vector< PointType > FiberType
typedef MaskImageType::IndexType IndexType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned short, 3 > MaskImageType
typedef ModelImageType::Pointer ModelImagePointer
typedef itk::VectorImage< float, 3 > ModelImageType
typedef itk::SmartPointer< Self > Pointer
typedef MaskImageType::PointType PointType
typedef ModelImageType::RegionType RegionType
typedef BaseTractographyImageFilter Self
typedef itk::ProcessObject Superclass
typedef ModelImageType::PixelType VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetInputImage (ModelImageType *input) ITK_OVERRIDE
void SetStopADCThreshold (double num)
void SetStopFAThreshold (double num)
Public Member Functions inherited from anima::BaseTractographyImageFilter
void createVTKOutput (std::vector< std::vector< PointType > > &filteredFibers)
ModelImageType * GetInputImage ()
double GetMinimalModelWeight ()
vtkPolyData * GetOutput ()
void SetComputeLocalColors (bool flag)
void SetCutMask (MaskImageType *mask)
void SetFilteringMask (MaskImageType *mask)
void SetForbiddenMask (MaskImageType *mask)
void SetMaxFiberAngle (double num)
void SetMaxLengthFiber (double num)
void SetMinimalModelWeight (double num)
void SetMinLengthFiber (double num)
void SetNumberOfFibersPerPixel (unsigned int num)
void SetSeedingMask (MaskImageType *mask)
void SetStepProgression (double num)
void Update () ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual bool CheckIndexInImageBounds (ContinuousIndexType &index) ITK_OVERRIDE
virtual bool CheckModelCompatibility (VectorType &modelValue, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual void ComputeAdditionalScalarMaps () ITK_OVERRIDE
dtiTractographyImageFilter ()
virtual PointType GetModelPrincipalDirection (VectorType &modelValue, bool is2d, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual void GetModelValue (ContinuousIndexType &index, VectorType &modelValue) ITK_OVERRIDE
Computes value of model from data. May use SNR and previous model value to perform smart interpolation. Replaces SNR and modelValue by the outputs.
virtual PointType GetNextDirection (PointType &previousDirection, VectorType &modelValue, bool is2d, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~dtiTractographyImageFilter ()
Protected Member Functions inherited from anima::BaseTractographyImageFilter
BaseTractographyImageFilter ()
bool CheckIndexInImageBounds (IndexType &index, ImageBaseType *testImage)
FiberProcessVectorType ComputeFiber (FiberType &fiber, FiberProgressType ways, itk::ThreadIdType threadId)
std::vector< FiberType > FilterOutputFibers (std::vector< FiberType > &fibers)
bool isZero (VectorType &value)
virtual void PrepareTractography ()
void ThreadedTrackComputer (unsigned int numThread, std::vector< FiberType > &resultFibers, unsigned int startSeedIndex, unsigned int endSeedIndex)
void ThreadTrack (unsigned int numThread, std::vector< FiberType > &resultFibers)
virtual ~BaseTractographyImageFilter ()
Additional Inherited Members
Protected Types inherited from anima::BaseTractographyImageFilter
typedef itk::ImageBase< ModelImageType::ImageDimension > ImageBaseType
Static Protected Member Functions inherited from anima::BaseTractographyImageFilter
static ITK_THREAD_RETURN_TYPE ThreadTracker (void *arg)
Detailed Description
Definition at line 11 of file animaDTITractographyImageFilter.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::dtiTractographyImageFilter::ConstPointer
Definition at line 19 of file animaDTITractographyImageFilter.h.
DTIInterpolatorPointer
typedef DTIInterpolatorType::Pointer anima::dtiTractographyImageFilter::DTIInterpolatorPointer
Definition at line 29 of file animaDTITractographyImageFilter.h.
DTIInterpolatorType
typedef itk::LinearInterpolateImageFunction<ModelImageType> anima::dtiTractographyImageFilter::DTIInterpolatorType
Definition at line 28 of file animaDTITractographyImageFilter.h.
ModelImageType
typedef Superclass::ModelImageType anima::dtiTractographyImageFilter::ModelImageType
Definition at line 25 of file animaDTITractographyImageFilter.h.
Pointer
typedef itk::SmartPointer<Self> anima::dtiTractographyImageFilter::Pointer
Definition at line 18 of file animaDTITractographyImageFilter.h.
PointType
typedef Superclass::PointType anima::dtiTractographyImageFilter::PointType
Definition at line 27 of file animaDTITractographyImageFilter.h.
Self
typedef dtiTractographyImageFilter anima::dtiTractographyImageFilter::Self
SmartPointer typedef support
Definition at line 15 of file animaDTITractographyImageFilter.h.
Superclass
typedef anima::BaseTractographyImageFilter anima::dtiTractographyImageFilter::Superclass
Definition at line 16 of file animaDTITractographyImageFilter.h.
VectorType
typedef Superclass::VectorType anima::dtiTractographyImageFilter::VectorType
Definition at line 26 of file animaDTITractographyImageFilter.h.
Constructor & Destructor Documentation
dtiTractographyImageFilter()
anima::dtiTractographyImageFilter::dtiTractographyImageFilter () protected
Definition at line 12 of file animaDTITractographyImageFilter.cxx.
~dtiTractographyImageFilter()
anima::dtiTractographyImageFilter::~dtiTractographyImageFilter () protected virtual
Definition at line 18 of file animaDTITractographyImageFilter.cxx.
Member Function Documentation
CheckIndexInImageBounds()
bool anima::dtiTractographyImageFilter::CheckIndexInImageBounds (ContinuousIndexType & index) protected virtual
Implements anima::BaseTractographyImageFilter.
Definition at line 70 of file animaDTITractographyImageFilter.cxx.
CheckModelCompatibility()
bool anima::dtiTractographyImageFilter::CheckModelCompatibility (VectorType & modelValue, itk::ThreadIdType threadId) protected virtual
Implements anima::BaseTractographyImageFilter.
Definition at line 30 of file animaDTITractographyImageFilter.cxx.
References anima::GetTensorFromVectorRepresentation().
ComputeAdditionalScalarMaps()
void anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps () protected virtual
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 165 of file animaDTITractographyImageFilter.cxx.
References anima::BaseTractographyImageFilter::GetInputImage(), GetModelValue(), anima::BaseTractographyImageFilter::GetOutput(), anima::GetTensorExponential(), and anima::GetTensorFromVectorRepresentation().
CreateAnother()
virtual::itk::LightObject::Pointer anima::dtiTractographyImageFilter::CreateAnother (void) const
GetModelPrincipalDirection()
dtiTractographyImageFilter::PointType anima::dtiTractographyImageFilter::GetModelPrincipalDirection (VectorType & modelValue, bool is2d, itk::ThreadIdType threadId) protected virtual
Implements anima::BaseTractographyImageFilter.
Definition at line 82 of file animaDTITractographyImageFilter.cxx.
References anima::GetTensorFromVectorRepresentation().
Referenced by GetNextDirection().
GetModelValue()
void anima::dtiTractographyImageFilter::GetModelValue (ContinuousIndexType & index, VectorType & modelValue) protected virtual
Computes value of model from data. May use SNR and previous model value to perform smart interpolation. Replaces SNR and modelValue by the outputs.
Implements anima::BaseTractographyImageFilter.
Definition at line 76 of file animaDTITractographyImageFilter.cxx.
Referenced by ComputeAdditionalScalarMaps().
GetNameOfClass()
virtual const char* anima::dtiTractographyImageFilter::GetNameOfClass () const virtual
Reimplemented from anima::BaseTractographyImageFilter.
GetNextDirection()
dtiTractographyImageFilter::PointType anima::dtiTractographyImageFilter::GetNextDirection (PointType & previousDirection, VectorType & modelValue, bool is2d, itk::ThreadIdType threadId) protected virtual
Implements anima::BaseTractographyImageFilter.
Definition at line 118 of file animaDTITractographyImageFilter.cxx.
References anima::ComputeScalarProduct(), anima::BaseTractographyImageFilter::GetMinimalModelWeight(), GetModelPrincipalDirection(), anima::GetTensorFromVectorRepresentation(), anima::Normalize(), and anima::Revert().
New()
static Pointer anima::dtiTractographyImageFilter::New () static
SetInputImage()
void anima::dtiTractographyImageFilter::SetInputImage (ModelImageType * input) virtual
Reimplemented from anima::BaseTractographyImageFilter.
Definition at line 22 of file animaDTITractographyImageFilter.cxx.
References anima::BaseTractographyImageFilter::GetInputImage(), and anima::BaseTractographyImageFilter::SetInputImage().
SetStopADCThreshold()
void anima::dtiTractographyImageFilter::SetStopADCThreshold (double num) inline
Definition at line 34 of file animaDTITractographyImageFilter.h.
SetStopFAThreshold()
void anima::dtiTractographyImageFilter::SetStopFAThreshold (double num) inline
Definition at line 33 of file animaDTITractographyImageFilter.h.
The documentation for this class was generated from the following files:
animaDTITractographyImageFilter.h
animaDTITractographyImageFilter.cxx