ANIMA: anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <animaT2RelaxometryEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef T2RelaxometryEstimationImageFilter Self
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Types inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TInputImage::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::ImageSource< TOutputImage >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetAverageSignalThreshold (double _arg)
virtual void SetEchoSpacing (double _arg)
virtual void SetMaximumOptimizerIterations (unsigned int _arg)
virtual void SetOptimizerStopCondition (double _arg)
void SetT1Map (OutputImageType *map)
virtual void SetT2UpperBoundValue (double _arg)
virtual void SetTRValue (double _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void CheckComputationMask () ITK_OVERRIDE
T2RelaxometryEstimationImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~T2RelaxometryEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
template<typename ScalarRealType >
void InitializeZeroPixel (TOutputImage *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<typename PixelType >
void InitializeZeroPixel (TOutputImage *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TInputImage, typename TOutputImage>
class anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >
Definition at line 11 of file animaT2RelaxometryEstimationImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInputImage , typename TOutputImage > typedef itk::SmartPointer<const Self> anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 19 of file animaT2RelaxometryEstimationImageFilter.h.
InputImagePointer
template<typename TInputImage , typename TOutputImage > typedef InputImageType::Pointer anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImagePointer
Definition at line 30 of file animaT2RelaxometryEstimationImageFilter.h.
InputImageRegionType
template<typename TInputImage , typename TOutputImage > typedef Superclass::InputImageRegionType anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImageRegionType
Definition at line 35 of file animaT2RelaxometryEstimationImageFilter.h.
InputImageType
template<typename TInputImage , typename TOutputImage > typedef TInputImage anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImageType
Image typedef support
Definition at line 28 of file animaT2RelaxometryEstimationImageFilter.h.
MaskImageType
template<typename TInputImage , typename TOutputImage > typedef Superclass::MaskImageType anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::MaskImageType
Superclass typedefs.
Definition at line 34 of file animaT2RelaxometryEstimationImageFilter.h.
OutputImagePointer
template<typename TInputImage , typename TOutputImage > typedef OutputImageType::Pointer anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImagePointer
Definition at line 31 of file animaT2RelaxometryEstimationImageFilter.h.
OutputImageRegionType
template<typename TInputImage , typename TOutputImage > typedef Superclass::OutputImageRegionType anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImageRegionType
Definition at line 36 of file animaT2RelaxometryEstimationImageFilter.h.
OutputImageType
template<typename TInputImage , typename TOutputImage > typedef TOutputImage anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 29 of file animaT2RelaxometryEstimationImageFilter.h.
Pointer
template<typename TInputImage , typename TOutputImage > typedef itk::SmartPointer<Self> anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 18 of file animaT2RelaxometryEstimationImageFilter.h.
Self
template<typename TInputImage , typename TOutputImage > typedef T2RelaxometryEstimationImageFilter anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 16 of file animaT2RelaxometryEstimationImageFilter.h.
Superclass
template<typename TInputImage , typename TOutputImage > typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 17 of file animaT2RelaxometryEstimationImageFilter.h.
Constructor & Destructor Documentation
T2RelaxometryEstimationImageFilter()
template<typename TInputImage , typename TOutputImage > anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::T2RelaxometryEstimationImageFilter () inline protected
Definition at line 49 of file animaT2RelaxometryEstimationImageFilter.h.
~T2RelaxometryEstimationImageFilter()
template<typename TInputImage , typename TOutputImage > virtual anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T2RelaxometryEstimationImageFilter () inline protected virtual
Definition at line 68 of file animaT2RelaxometryEstimationImageFilter.h.
References anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CheckComputationMask(), and anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
Member Function Documentation
CheckComputationMask()
template<typename TInputImage , typename TOutputImage > void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Definition at line 16 of file animaT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T2RelaxometryEstimationImageFilter().
CreateAnother()
template<typename TInputImage , typename TOutputImage > virtual::itk::LightObject::Pointer anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
GetNameOfClass()
template<typename TInputImage , typename TOutputImage > virtual const char* anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >.
New()
template<typename TInputImage , typename TOutputImage > static Pointer anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
SetAverageSignalThreshold()
template<typename TInputImage , typename TOutputImage > virtual void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetAverageSignalThreshold (double _arg) virtual
SetEchoSpacing()
template<typename TInputImage , typename TOutputImage > virtual void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetEchoSpacing (double _arg) virtual
SetMaximumOptimizerIterations()
template<typename TInputImage , typename TOutputImage > virtual void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetMaximumOptimizerIterations (unsigned int _arg) virtual
SetOptimizerStopCondition()
template<typename TInputImage , typename TOutputImage > virtual void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetOptimizerStopCondition (double _arg) virtual
SetT1Map()
template<typename TInputImage , typename TOutputImage > void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetT1Map (OutputImageType * map) inline
Setter
Definition at line 39 of file animaT2RelaxometryEstimationImageFilter.h.
SetT2UpperBoundValue()
template<typename TInputImage , typename TOutputImage > virtual void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetT2UpperBoundValue (double _arg) virtual
SetTRValue()
template<typename TInputImage , typename TOutputImage > virtual void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetTRValue (double _arg) virtual
ThreadedGenerateData()
template<typename TInputImage , typename TOutputImage > void anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 64 of file animaT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T2RelaxometryEstimationImageFilter().
The documentation for this class was generated from the following files:
animaT2RelaxometryEstimationImageFilter.h
animaT2RelaxometryEstimationImageFilter.hxx