ANIMA: anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension > Class Template Reference
anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension > Class Template Reference
Compute the Jacobian matrix in real coordinates of a displacement field.
#include <animaJacobianMatrixImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Image< TOutputPixelType, Dimension > DeterminantImageType
typedef InputImageType::IndexType IndexType
typedef InputImageType::Pointer InputImagePointer
typedef itk::Image< itk::Vector< TPixelType, Dimension >, Dimension > InputImageType
typedef InputImageType::PixelType InputPixelType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction< InputImageType > InterpolatorType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image< itk::Vector< TOutputPixelType, Dimension *Dimension >, Dimension > OutputImageType
typedef OutputImageType::PixelType OutputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::PointType PointType
typedef InputImageType::RegionType RegionType
typedef JacobianMatrixImageFilter Self
typedef itk::ImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
itkGetObjectMacro (DeterminantImage, DeterminantImageType) void SetNeighborhood(unsigned int val)
virtual void SetComputeDeterminant (bool _arg)
virtual void SetNoIdentity (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
bool CheckFaceConnectivity (const IndexType &internalIndex, const IndexType &currentIndex)
JacobianMatrixImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~JacobianMatrixImageFilter ()
Detailed Description
template<typename TPixelType, typename TOutputPixelType, unsigned int Dimension>
class anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >
Compute the Jacobian matrix in real coordinates of a displacement field.
The Jacobian matrix is computed as a linear least squares problem based on multiple directional derivatives around each pixel The output vector in each voxel is of size Dimension^2 and is stored on rows first, i.e. J[0] = dT_0/dx_0, J[1] = dT_0/dx_1, J[2] = dT_0/dx_2, J[3] = dT_1/dx_0, ...
Definition at line 19 of file animaJacobianMatrixImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef itk::SmartPointer<const Self> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::ConstPointer
Definition at line 30 of file animaJacobianMatrixImageFilter.h.
DeterminantImageType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef itk::Image<TOutputPixelType, Dimension> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::DeterminantImageType
Definition at line 27 of file animaJacobianMatrixImageFilter.h.
IndexType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef InputImageType::IndexType anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::IndexType
Definition at line 36 of file animaJacobianMatrixImageFilter.h.
InputImagePointer
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef InputImageType::Pointer anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::InputImagePointer
Definition at line 42 of file animaJacobianMatrixImageFilter.h.
InputImageType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TPixelType, Dimension>, Dimension> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::InputImageType
Definition at line 25 of file animaJacobianMatrixImageFilter.h.
InputPixelType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef InputImageType::PixelType anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::InputPixelType
Definition at line 39 of file animaJacobianMatrixImageFilter.h.
InterpolatorPointer
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef InterpolatorType::Pointer anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::InterpolatorPointer
Definition at line 48 of file animaJacobianMatrixImageFilter.h.
InterpolatorType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef itk::VectorLinearInterpolateNearestNeighborExtrapolateImageFunction<InputImageType> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::InterpolatorType
Definition at line 47 of file animaJacobianMatrixImageFilter.h.
OutputImagePointer
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef OutputImageType::Pointer anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::OutputImagePointer
Definition at line 43 of file animaJacobianMatrixImageFilter.h.
OutputImageRegionType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef Superclass::OutputImageRegionType anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::OutputImageRegionType
Definition at line 45 of file animaJacobianMatrixImageFilter.h.
OutputImageType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TOutputPixelType, Dimension * Dimension>, Dimension> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::OutputImageType
Definition at line 26 of file animaJacobianMatrixImageFilter.h.
OutputPixelType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef OutputImageType::PixelType anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::OutputPixelType
Definition at line 40 of file animaJacobianMatrixImageFilter.h.
Pointer
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef itk::SmartPointer<Self> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::Pointer
Definition at line 29 of file animaJacobianMatrixImageFilter.h.
PointType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef InputImageType::PointType anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::PointType
Definition at line 38 of file animaJacobianMatrixImageFilter.h.
RegionType
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef InputImageType::RegionType anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::RegionType
Definition at line 37 of file animaJacobianMatrixImageFilter.h.
Self
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef JacobianMatrixImageFilter anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::Self
Definition at line 24 of file animaJacobianMatrixImageFilter.h.
Superclass
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> typedef itk::ImageToImageFilter<InputImageType, OutputImageType> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::Superclass
Definition at line 28 of file animaJacobianMatrixImageFilter.h.
Constructor & Destructor Documentation
JacobianMatrixImageFilter()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::JacobianMatrixImageFilter () inline protected
Definition at line 57 of file animaJacobianMatrixImageFilter.h.
~JacobianMatrixImageFilter()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> virtual anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::~JacobianMatrixImageFilter () inline protected virtual
Definition at line 67 of file animaJacobianMatrixImageFilter.h.
References anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::BeforeThreadedGenerateData(), anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::CheckFaceConnectivity(), and anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> void anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::BeforeThreadedGenerateData () protected
Definition at line 15 of file animaJacobianMatrixImageFilter.hxx.
Referenced by anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::~JacobianMatrixImageFilter().
CheckFaceConnectivity()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> bool anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::CheckFaceConnectivity (const IndexType & internalIndex, const IndexType & currentIndex) protected
Definition at line 225 of file animaJacobianMatrixImageFilter.hxx.
Referenced by anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::~JacobianMatrixImageFilter().
CreateAnother()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> virtual::itk::LightObject::Pointer anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::CreateAnother (void) const
GetNameOfClass()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> virtual const char* anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::GetNameOfClass () const virtual
itkGetObjectMacro()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::itkGetObjectMacro (DeterminantImage , DeterminantImageType)
New()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> static Pointer anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::New () static
SetComputeDeterminant()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> virtual void anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::SetComputeDeterminant (bool _arg) virtual
SetNoIdentity()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> virtual void anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::SetNoIdentity (bool _arg) virtual
ThreadedGenerateData()
template<typename TPixelType , typename TOutputPixelType , unsigned int Dimension> void anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 56 of file animaJacobianMatrixImageFilter.hxx.
Referenced by anima::JacobianMatrixImageFilter< TPixelType, TOutputPixelType, Dimension >::~JacobianMatrixImageFilter().
The documentation for this class was generated from the following files:
animaJacobianMatrixImageFilter.h
animaJacobianMatrixImageFilter.hxx