ANIMA: anima::MCMWeightedAverager Class Reference
anima::MCMWeightedAverager Class Reference
Computes a weighted average of input multi-compartment models. The output model is at the same time giving the number and type of output compartments but also its parameters are erased when performing Update to get the result.
#include <animaMCMWeightedAverager.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef MCMType::BaseCompartmentPointer MCMCompartmentPointer
typedef MCMType::Pointer MCMPointer
typedef anima::MultiCompartmentModel MCMType
typedef itk::SmartPointer< Self > Pointer
typedef MCMWeightedAverager Self
typedef itk::LightObject Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MCMPointer & GetOutputModel ()
unsigned int GetOutputModelSize ()
MCMPointer & GetUntouchedOutputModel ()
void ResetNumberOfOutputDirectionalCompartments ()
void SetInputModels (std::vector< MCMPointer > &models)
void SetInputWeights (std::vector< double > &weights)
void SetNumberOfOutputDirectionalCompartments (unsigned int val)
void SetOutputModel (MCMType *model)
void SetUpToDate (bool val)
void Update ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual void ComputeNonTensorDistanceMatrix ()
virtual void ComputeOutputNonTensorModel ()
void ComputeOutputTensorModel ()
void ComputeTensorDistanceMatrix ()
MCMWeightedAverager ()
~MCMWeightedAverager ()
Protected Attributes
vnl_matrix< double > m_InternalDistanceMatrix
std::vector< itk::VariableLengthVector< double > > m_InternalLogTensors
std::vector< double > m_InternalOutputWeights
std::vector< std::vector< double > > m_InternalSpectralMemberships
std::vector< MCMCompartmentPointer > m_WorkCompartmentsVector
std::vector< double > m_WorkCompartmentWeights
Detailed Description
Computes a weighted average of input multi-compartment models. The output model is at the same time giving the number and type of output compartments but also its parameters are erased when performing Update to get the result.
Definition at line 18 of file animaMCMWeightedAverager.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::MCMWeightedAverager::ConstPointer
Definition at line 24 of file animaMCMWeightedAverager.h.
MCMCompartmentPointer
typedef MCMType::BaseCompartmentPointer anima::MCMWeightedAverager::MCMCompartmentPointer
Definition at line 32 of file animaMCMWeightedAverager.h.
MCMPointer
typedef MCMType::Pointer anima::MCMWeightedAverager::MCMPointer
Definition at line 33 of file animaMCMWeightedAverager.h.
MCMType
typedef anima::MultiCompartmentModel anima::MCMWeightedAverager::MCMType
Definition at line 31 of file animaMCMWeightedAverager.h.
Pointer
typedef itk::SmartPointer<Self> anima::MCMWeightedAverager::Pointer
Definition at line 23 of file animaMCMWeightedAverager.h.
Self
typedef MCMWeightedAverager anima::MCMWeightedAverager::Self
Definition at line 21 of file animaMCMWeightedAverager.h.
Superclass
typedef itk::LightObject anima::MCMWeightedAverager::Superclass
Definition at line 22 of file animaMCMWeightedAverager.h.
Constructor & Destructor Documentation
MCMWeightedAverager()
anima::MCMWeightedAverager::MCMWeightedAverager () protected
Definition at line 8 of file animaMCMWeightedAverager.cxx.
~MCMWeightedAverager()
anima::MCMWeightedAverager::~MCMWeightedAverager () inline protected
Definition at line 53 of file animaMCMWeightedAverager.h.
Member Function Documentation
ComputeNonTensorDistanceMatrix()
void anima::MCMWeightedAverager::ComputeNonTensorDistanceMatrix () protected virtual
Definition at line 202 of file animaMCMWeightedAverager.cxx.
Referenced by Update().
ComputeOutputNonTensorModel()
void anima::MCMWeightedAverager::ComputeOutputNonTensorModel () protected virtual
Definition at line 242 of file animaMCMWeightedAverager.cxx.
Referenced by Update().
ComputeOutputTensorModel()
void anima::MCMWeightedAverager::ComputeOutputTensorModel () protected
Definition at line 207 of file animaMCMWeightedAverager.cxx.
References anima::GetTensorExponential(), anima::GetTensorFromVectorRepresentation(), anima::GetVectorRepresentation(), m_InternalLogTensors, m_InternalOutputWeights, m_InternalSpectralMemberships, m_WorkCompartmentsVector, m_WorkCompartmentWeights, and anima::BaseCompartment::SetCompartmentVector().
Referenced by Update().
ComputeTensorDistanceMatrix()
void anima::MCMWeightedAverager::ComputeTensorDistanceMatrix () protected
Definition at line 174 of file animaMCMWeightedAverager.cxx.
References anima::GetTensorLogarithm(), anima::GetVectorRepresentation(), m_InternalDistanceMatrix, m_InternalLogTensors, and m_WorkCompartmentsVector.
Referenced by Update().
CreateAnother()
virtual::itk::LightObject::Pointer anima::MCMWeightedAverager::CreateAnother (void) const
GetNameOfClass()
virtual const char* anima::MCMWeightedAverager::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetOutputModel()
MCMWeightedAverager::MCMPointer & anima::MCMWeightedAverager::GetOutputModel ()
Definition at line 32 of file animaMCMWeightedAverager.cxx.
References Update().
GetOutputModelSize()
unsigned int anima::MCMWeightedAverager::GetOutputModelSize ()
Definition at line 45 of file animaMCMWeightedAverager.cxx.
GetUntouchedOutputModel()
MCMWeightedAverager::MCMPointer & anima::MCMWeightedAverager::GetUntouchedOutputModel ()
Definition at line 40 of file animaMCMWeightedAverager.cxx.
New()
static Pointer anima::MCMWeightedAverager::New () static
Referenced by anima::MCMAverageImagesImageFilter< TPixelType >::CreateAverager().
ResetNumberOfOutputDirectionalCompartments()
void anima::MCMWeightedAverager::ResetNumberOfOutputDirectionalCompartments ()
Definition at line 26 of file animaMCMWeightedAverager.cxx.
Referenced by SetOutputModel().
SetInputModels()
void anima::MCMWeightedAverager::SetInputModels (std::vector< MCMPointer > & models) inline
Definition at line 35 of file animaMCMWeightedAverager.h.
SetInputWeights()
void anima::MCMWeightedAverager::SetInputWeights (std::vector< double > & weights) inline
Definition at line 36 of file animaMCMWeightedAverager.h.
SetNumberOfOutputDirectionalCompartments()
void anima::MCMWeightedAverager::SetNumberOfOutputDirectionalCompartments (unsigned int val)
Definition at line 20 of file animaMCMWeightedAverager.cxx.
SetOutputModel()
void anima::MCMWeightedAverager::SetOutputModel (MCMType * model)
Definition at line 14 of file animaMCMWeightedAverager.cxx.
References ResetNumberOfOutputDirectionalCompartments().
SetUpToDate()
void anima::MCMWeightedAverager::SetUpToDate (bool val) inline
Definition at line 47 of file animaMCMWeightedAverager.h.
Update()
void anima::MCMWeightedAverager::Update ()
Definition at line 53 of file animaMCMWeightedAverager.cxx.
References ComputeNonTensorDistanceMatrix(), ComputeOutputNonTensorModel(), ComputeOutputTensorModel(), ComputeTensorDistanceMatrix(), m_InternalDistanceMatrix, m_InternalOutputWeights, m_InternalSpectralMemberships, m_WorkCompartmentsVector, m_WorkCompartmentWeights, and anima::SpectralClusteringFilter< ScalarType >::SetNbClass().
Referenced by GetOutputModel().
Member Data Documentation
m_InternalDistanceMatrix
vnl_matrix<double> anima::MCMWeightedAverager::m_InternalDistanceMatrix protected
Definition at line 77 of file animaMCMWeightedAverager.h.
Referenced by ComputeTensorDistanceMatrix(), and Update().
m_InternalLogTensors
std::vector< itk::VariableLengthVector <double> > anima::MCMWeightedAverager::m_InternalLogTensors protected
Definition at line 72 of file animaMCMWeightedAverager.h.
Referenced by ComputeOutputTensorModel(), and ComputeTensorDistanceMatrix().
m_InternalOutputWeights
std::vector<double> anima::MCMWeightedAverager::m_InternalOutputWeights protected
Definition at line 74 of file animaMCMWeightedAverager.h.
Referenced by ComputeOutputTensorModel(), and Update().
m_InternalSpectralMemberships
std::vector< std::vector <double> > anima::MCMWeightedAverager::m_InternalSpectralMemberships protected
Definition at line 78 of file animaMCMWeightedAverager.h.
Referenced by ComputeOutputTensorModel(), and Update().
m_WorkCompartmentsVector
std::vector<MCMCompartmentPointer> anima::MCMWeightedAverager::m_WorkCompartmentsVector protected
Definition at line 75 of file animaMCMWeightedAverager.h.
Referenced by ComputeOutputTensorModel(), ComputeTensorDistanceMatrix(), and Update().
m_WorkCompartmentWeights
std::vector<double> anima::MCMWeightedAverager::m_WorkCompartmentWeights protected
Definition at line 76 of file animaMCMWeightedAverager.h.
Referenced by ComputeOutputTensorModel(), and Update().
The documentation for this class was generated from the following files:
animaMCMWeightedAverager.h
animaMCMWeightedAverager.cxx