ANIMA: anima::SimuBlochIRSE< TImage > Class Template Reference
anima::SimuBlochIRSE< TImage > Class Template Reference
#include <animaSimuBlochIR-SE.h>
Public Types
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef SimuBlochIRSE Self
typedef itk::ImageToImageFilter< TImage, TImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual float GetTE ()
virtual float GetTI ()
virtual float GetTR ()
void SetInputM0 (const TImage *M0)
void SetInputT1 (const TImage *T1)
void SetInputT2 (const TImage *T2)
virtual void SetTE (float _arg)
virtual void SetTI (float _arg)
virtual void SetTR (float _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
SimuBlochIRSE ()
virtual void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~SimuBlochIRSE ()
Detailed Description
template<class TImage>
class anima::SimuBlochIRSE< TImage >
Definition at line 9 of file animaSimuBlochIR-SE.h.
Member Typedef Documentation
OutputImageRegionType
template<class TImage > typedef Superclass::OutputImageRegionType anima::SimuBlochIRSE< TImage >::OutputImageRegionType
Definition at line 17 of file animaSimuBlochIR-SE.h.
Pointer
template<class TImage > typedef itk::SmartPointer<Self> anima::SimuBlochIRSE< TImage >::Pointer
Definition at line 15 of file animaSimuBlochIR-SE.h.
Self
template<class TImage > typedef SimuBlochIRSE anima::SimuBlochIRSE< TImage >::Self
Standard class typedefs.
Definition at line 13 of file animaSimuBlochIR-SE.h.
Superclass
template<class TImage > typedef itk::ImageToImageFilter<TImage, TImage> anima::SimuBlochIRSE< TImage >::Superclass
Definition at line 14 of file animaSimuBlochIR-SE.h.
Constructor & Destructor Documentation
SimuBlochIRSE()
template<class TImage > anima::SimuBlochIRSE< TImage >::SimuBlochIRSE () protected
Definition at line 46 of file animaSimuBlochIR-SE.hxx.
~SimuBlochIRSE()
template<class TImage > virtual anima::SimuBlochIRSE< TImage >::~SimuBlochIRSE () inline protected virtual
Definition at line 45 of file animaSimuBlochIR-SE.h.
References anima::SimuBlochIRSE< TImage >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<class TImage > virtual::itk::LightObject::Pointer anima::SimuBlochIRSE< TImage >::CreateAnother (void) const
GetNameOfClass()
template<class TImage > virtual const char* anima::SimuBlochIRSE< TImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetTE()
template<class TImage > virtual float anima::SimuBlochIRSE< TImage >::GetTE () virtual
GetTI()
template<class TImage > virtual float anima::SimuBlochIRSE< TImage >::GetTI () virtual
GetTR()
template<class TImage > virtual float anima::SimuBlochIRSE< TImage >::GetTR () virtual
New()
template<class TImage > static Pointer anima::SimuBlochIRSE< TImage >::New () static
Method for creation through the object factory.
SetInputM0()
template<class TImage > void anima::SimuBlochIRSE< TImage >::SetInputM0 (const TImage * M0)
M0 image / Rho map
Definition at line 64 of file animaSimuBlochIR-SE.hxx.
References anima::SimuBlochIRSE< TImage >::ThreadedGenerateData().
SetInputT1()
template<class TImage > void anima::SimuBlochIRSE< TImage >::SetInputT1 (const TImage * T1)
T1 map
Definition at line 52 of file animaSimuBlochIR-SE.hxx.
SetInputT2()
template<class TImage > void anima::SimuBlochIRSE< TImage >::SetInputT2 (const TImage * T2)
T2 map
Definition at line 58 of file animaSimuBlochIR-SE.hxx.
SetTE()
template<class TImage > virtual void anima::SimuBlochIRSE< TImage >::SetTE (float _arg) virtual
SetTI()
template<class TImage > virtual void anima::SimuBlochIRSE< TImage >::SetTI (float _arg) virtual
SetTR()
template<class TImage > virtual void anima::SimuBlochIRSE< TImage >::SetTR (float _arg) virtual
ThreadedGenerateData()
template<class TImage > void anima::SimuBlochIRSE< TImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected virtual
Does the real work.
Definition at line 71 of file animaSimuBlochIR-SE.hxx.
Referenced by anima::SimuBlochIRSE< TImage >::SetInputM0(), and anima::SimuBlochIRSE< TImage >::~SimuBlochIRSE().
The documentation for this class was generated from the following files:
animaSimuBlochIR-SE.h
animaSimuBlochIR-SE.hxx