ANIMA: anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <animaT1SERelaxometryEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef T1SERelaxometryEstimationImageFilter Self
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Types inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TInputImage::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::ImageSource< TOutputImage >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetAverageSignalThreshold (double _arg)
virtual void SetM0UpperBound (double _arg)
virtual void SetMaximumOptimizerIterations (unsigned int _arg)
virtual void SetOptimizerInitialStep (double _arg)
virtual void SetOptimizerStopCondition (double _arg)
virtual void SetT1UpperBound (double _arg)
void SetTRValues (std::vector< double > &trValues)
Public Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void CheckComputationMask () ITK_OVERRIDE
T1SERelaxometryEstimationImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~T1SERelaxometryEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
template<typename ScalarRealType >
void InitializeZeroPixel (TOutputImage *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<typename PixelType >
void InitializeZeroPixel (TOutputImage *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TInputImage, typename TOutputImage>
class anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >
Definition at line 10 of file animaT1SERelaxometryEstimationImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInputImage , typename TOutputImage > typedef itk::SmartPointer<const Self> anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 18 of file animaT1SERelaxometryEstimationImageFilter.h.
InputImagePointer
template<typename TInputImage , typename TOutputImage > typedef InputImageType::Pointer anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImagePointer
Definition at line 29 of file animaT1SERelaxometryEstimationImageFilter.h.
InputImageRegionType
template<typename TInputImage , typename TOutputImage > typedef Superclass::InputImageRegionType anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImageRegionType
Definition at line 34 of file animaT1SERelaxometryEstimationImageFilter.h.
InputImageType
template<typename TInputImage , typename TOutputImage > typedef TInputImage anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImageType
Image typedef support
Definition at line 27 of file animaT1SERelaxometryEstimationImageFilter.h.
MaskImageType
template<typename TInputImage , typename TOutputImage > typedef Superclass::MaskImageType anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::MaskImageType
Superclass typedefs.
Definition at line 33 of file animaT1SERelaxometryEstimationImageFilter.h.
OutputImagePointer
template<typename TInputImage , typename TOutputImage > typedef OutputImageType::Pointer anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImagePointer
Definition at line 30 of file animaT1SERelaxometryEstimationImageFilter.h.
OutputImageRegionType
template<typename TInputImage , typename TOutputImage > typedef Superclass::OutputImageRegionType anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImageRegionType
Definition at line 35 of file animaT1SERelaxometryEstimationImageFilter.h.
OutputImageType
template<typename TInputImage , typename TOutputImage > typedef TOutputImage anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 28 of file animaT1SERelaxometryEstimationImageFilter.h.
Pointer
template<typename TInputImage , typename TOutputImage > typedef itk::SmartPointer<Self> anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 17 of file animaT1SERelaxometryEstimationImageFilter.h.
Self
template<typename TInputImage , typename TOutputImage > typedef T1SERelaxometryEstimationImageFilter anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 15 of file animaT1SERelaxometryEstimationImageFilter.h.
Superclass
template<typename TInputImage , typename TOutputImage > typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 16 of file animaT1SERelaxometryEstimationImageFilter.h.
Constructor & Destructor Documentation
T1SERelaxometryEstimationImageFilter()
template<typename TInputImage , typename TOutputImage > anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::T1SERelaxometryEstimationImageFilter () inline protected
Definition at line 48 of file animaT1SERelaxometryEstimationImageFilter.h.
~T1SERelaxometryEstimationImageFilter()
template<typename TInputImage , typename TOutputImage > virtual anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T1SERelaxometryEstimationImageFilter () inline protected virtual
Definition at line 68 of file animaT1SERelaxometryEstimationImageFilter.h.
References anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CheckComputationMask(), and anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
Member Function Documentation
CheckComputationMask()
template<typename TInputImage , typename TOutputImage > void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Definition at line 16 of file animaT1SERelaxometryEstimationImageFilter.hxx.
Referenced by anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T1SERelaxometryEstimationImageFilter().
CreateAnother()
template<typename TInputImage , typename TOutputImage > virtual::itk::LightObject::Pointer anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
GetNameOfClass()
template<typename TInputImage , typename TOutputImage > virtual const char* anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >.
New()
template<typename TInputImage , typename TOutputImage > static Pointer anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
SetAverageSignalThreshold()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetAverageSignalThreshold (double _arg) virtual
SetM0UpperBound()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetM0UpperBound (double _arg) virtual
SetMaximumOptimizerIterations()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetMaximumOptimizerIterations (unsigned int _arg) virtual
SetOptimizerInitialStep()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetOptimizerInitialStep (double _arg) virtual
SetOptimizerStopCondition()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetOptimizerStopCondition (double _arg) virtual
SetT1UpperBound()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetT1UpperBound (double _arg) virtual
SetTRValues()
template<typename TInputImage , typename TOutputImage > void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetTRValues (std::vector< double > & trValues) inline
Definition at line 37 of file animaT1SERelaxometryEstimationImageFilter.h.
ThreadedGenerateData()
template<typename TInputImage , typename TOutputImage > void anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 64 of file animaT1SERelaxometryEstimationImageFilter.hxx.
References anima::T1SERelaxometryCostFunction::New().
Referenced by anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T1SERelaxometryEstimationImageFilter().
The documentation for this class was generated from the following files:
animaT1SERelaxometryEstimationImageFilter.h
animaT1SERelaxometryEstimationImageFilter.hxx