ANIMA: anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension > Class Template Reference
anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension > Class Template Reference
#include <animaPyramidalDistortionCorrectionBlockMatchingBridge.h>
Public Types
typedef AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform< typename BaseAgregatorType::InternalScalarType, ImageDimension > AffineTransformType
typedef anima::BalooSVFTransformAgregator< ImageDimension > BalooAgregatorType
typedef anima::BaseTransformAgregator< ImageDimension > BaseAgregatorType
typedef DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef rpi::DisplacementFieldTransform< typename BaseAgregatorType::ScalarType, ImageDimension > DisplacementFieldTransformType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef itk::Image< float, ImageDimension > InputImageType
typedef InputImageType::IOPixelType InputPixelType
typedef anima::DenseSVFTransformAgregator< ImageDimension > MEstimateAgregatorType
typedef PyramidType::Pointer PyramidPointer
typedef anima::PyramidImageFilter< InputImageType, InputImageType > PyramidType
typedef DisplacementFieldTransformType::VectorFieldType VectorFieldType
Public Member Functions
Agregator GetAgregator ()
unsigned int GetBlockSize ()
unsigned int GetBlockSpacing ()
double GetElasticSigma ()
unsigned int GetExponentiationOrder ()
double GetExtrapolationSigma ()
double GetFinalRadius ()
unsigned int GetLastPyramidLevel ()
unsigned int GetMaximumIterations ()
double GetMEstimateConvergenceThreshold ()
Metric GetMetric ()
double GetNeighborhoodApproximation ()
unsigned int GetNumberOfPyramidLevels ()
unsigned int GetOptimizerMaximumIterations ()
double GetOutlierSigma ()
InputImagePointer GetOutputImage ()
DisplacementFieldTransformPointer GetOutputTransform ()
std::string GetOutputTransformFile ()
double GetPercentageKept ()
std::string GetResultFile ()
double GetScaleUpperBound ()
double GetSearchRadius ()
double GetSearchScaleRadius ()
double GetSearchSkewRadius ()
double GetSkewUpperBound ()
float GetStDevThreshold ()
double GetTranlateUpperBound ()
unsigned int GetTransformDirection ()
TransformKind GetTransformKind ()
bool GetWeightedAgregation ()
PyramidalDistortionCorrectionBlockMatchingBridge ()
void SetAgregator (Agregator agregator)
void SetBackwardImage (InputImageConstPointer backwardImage)
void SetBlockSize (int blockSize)
void SetBlockSpacing (unsigned int blockSpacing)
void SetElasticSigma (double elasticSigma)
void SetExponentiationOrder (unsigned int order)
void SetExtrapolationSigma (double extrapolationSigma)
void SetFinalRadius (double FinalRadius)
void SetForwardImage (InputImageConstPointer forwardImage)
void SetInitialTransformField (VectorFieldType *field)
void SetLastPyramidLevel (unsigned int LastPyramidLevel)
void SetMaximumIterations (unsigned int MaximumIterations)
void SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold)
void SetMetric (Metric metric)
void SetNeighborhoodApproximation (double neighborhoodApproximation)
void SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels)
void SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations)
void SetOutlierSigma (double outlierSigma)
void SetOutputTransformFile (std::string outputTransformFile)
void SetPercentageKept (double PercentageKept)
void SetResultFile (std::string resultFile)
void SetScaleUpperBound (double ScaleUpperBound)
void SetSearchRadius (double SearchRadius)
void SetSearchScaleRadius (double SearchScaleRadius)
void SetSearchSkewRadius (double SearchSkewRadius)
void SetSkewUpperBound (double SkewUpperBound)
void SetStDevThreshold (float StDevThreshold)
void SetTranlateUpperBound (double TranlateUpperBound)
void SetTransformDirection (unsigned int TransformDirection)
void SetTransformKind (TransformKind tr)
void SetWeightedAgregation (bool WeightedAgregation)
void Update ()
void WriteOutputs ()
~PyramidalDistortionCorrectionBlockMatchingBridge ()
Detailed Description
template<unsigned int ImageDimension = 3>
class anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >
Definition at line 34 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
Member Typedef Documentation
AffineTransformPointer
template<unsigned int ImageDimension = 3> typedef AffineTransformType::Pointer anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::AffineTransformPointer
Definition at line 47 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
AffineTransformType
template<unsigned int ImageDimension = 3> typedef itk::AffineTransform<typename BaseAgregatorType::InternalScalarType,ImageDimension> anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::AffineTransformType
Definition at line 46 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
BalooAgregatorType
template<unsigned int ImageDimension = 3> typedef anima::BalooSVFTransformAgregator< ImageDimension > anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::BalooAgregatorType
Definition at line 44 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
BaseAgregatorType
template<unsigned int ImageDimension = 3> typedef anima::BaseTransformAgregator< ImageDimension > anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::BaseAgregatorType
Definition at line 42 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
DisplacementFieldTransformPointer
template<unsigned int ImageDimension = 3> typedef DisplacementFieldTransformType::Pointer anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::DisplacementFieldTransformPointer
Definition at line 50 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
DisplacementFieldTransformType
template<unsigned int ImageDimension = 3> typedef rpi::DisplacementFieldTransform<typename BaseAgregatorType::ScalarType, ImageDimension> anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::DisplacementFieldTransformType
Definition at line 49 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
InputImageConstPointer
template<unsigned int ImageDimension = 3> typedef InputImageType::ConstPointer anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::InputImageConstPointer
Definition at line 40 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
InputImagePointer
template<unsigned int ImageDimension = 3> typedef InputImageType::Pointer anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::InputImagePointer
Definition at line 39 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
InputImageType
template<unsigned int ImageDimension = 3> typedef itk::Image<float,ImageDimension> anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::InputImageType
Definition at line 37 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
InputPixelType
template<unsigned int ImageDimension = 3> typedef InputImageType::IOPixelType anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::InputPixelType
Definition at line 38 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
MEstimateAgregatorType
template<unsigned int ImageDimension = 3> typedef anima::DenseSVFTransformAgregator< ImageDimension > anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::MEstimateAgregatorType
Definition at line 43 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
PyramidPointer
template<unsigned int ImageDimension = 3> typedef PyramidType::Pointer anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::PyramidPointer
Definition at line 54 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
PyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<InputImageType,InputImageType> anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::PyramidType
Definition at line 53 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
VectorFieldType
template<unsigned int ImageDimension = 3> typedef DisplacementFieldTransformType::VectorFieldType anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::VectorFieldType
Definition at line 51 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
Constructor & Destructor Documentation
PyramidalDistortionCorrectionBlockMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::PyramidalDistortionCorrectionBlockMatchingBridge ()
Definition at line 18 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.hxx.
References Baloo, DirectionScaleSkew, anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetInitialTransformField(), and SquaredCorrelation.
~PyramidalDistortionCorrectionBlockMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::~PyramidalDistortionCorrectionBlockMatchingBridge ()
Definition at line 73 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.hxx.
Member Function Documentation
GetAgregator()
template<unsigned int ImageDimension = 3> Agregator anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetAgregator () inline
Definition at line 131 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetBlockSize()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetBlockSize () inline
Definition at line 86 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetBlockSpacing()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetBlockSpacing () inline
Definition at line 89 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetElasticSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetElasticSigma () inline
Definition at line 137 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetExponentiationOrder()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetExponentiationOrder () inline
Definition at line 149 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetExtrapolationSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetExtrapolationSigma () inline
Definition at line 134 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetFinalRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetFinalRadius () inline
Definition at line 113 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetLastPyramidLevel()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetLastPyramidLevel () inline
Definition at line 158 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetMaximumIterations () inline
Definition at line 101 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetMEstimateConvergenceThreshold () inline
Definition at line 143 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetMetric()
template<unsigned int ImageDimension = 3> Metric anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetMetric () inline
Definition at line 125 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetNeighborhoodApproximation () inline
Definition at line 146 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetNumberOfPyramidLevels () inline
Definition at line 155 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetOptimizerMaximumIterations () inline
Definition at line 98 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetOutlierSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetOutlierSigma () inline
Definition at line 140 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetOutputImage()
template<unsigned int ImageDimension = 3> InputImagePointer anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetOutputImage () inline
Definition at line 69 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetOutputTransform()
template<unsigned int ImageDimension = 3> DisplacementFieldTransformPointer anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetOutputTransform () inline
Getter for transform
Definition at line 74 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetOutputTransformFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetOutputTransformFile () inline
Definition at line 83 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetPercentageKept()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetPercentageKept () inline
Definition at line 161 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetResultFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetResultFile () inline
Setter/Getter for parameters
Definition at line 80 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetScaleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetScaleUpperBound () inline
Definition at line 119 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetSearchRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetSearchRadius () inline
Definition at line 104 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetSearchScaleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetSearchScaleRadius () inline
Definition at line 107 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetSearchSkewRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetSearchSkewRadius () inline
Definition at line 110 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetSkewUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetSkewUpperBound () inline
Definition at line 122 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetStDevThreshold()
template<unsigned int ImageDimension = 3> float anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetStDevThreshold () inline
Definition at line 92 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetTranlateUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetTranlateUpperBound () inline
Definition at line 116 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetTransformDirection()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetTransformDirection () inline
Definition at line 95 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetTransformKind()
template<unsigned int ImageDimension = 3> TransformKind anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetTransformKind () inline
Definition at line 128 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
GetWeightedAgregation()
template<unsigned int ImageDimension = 3> bool anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::GetWeightedAgregation () inline
Definition at line 152 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetAgregator()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetAgregator (Agregator agregator) inline
Definition at line 132 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetBackwardImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetBackwardImage (InputImageConstPointer backwardImage) inline
Setter for images
Definition at line 66 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetBlockSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetBlockSize (int blockSize) inline
Definition at line 87 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetBlockSpacing()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetBlockSpacing (unsigned int blockSpacing) inline
Definition at line 90 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetElasticSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetElasticSigma (double elasticSigma) inline
Definition at line 138 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetExponentiationOrder()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetExponentiationOrder (unsigned int order) inline
Definition at line 150 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetExtrapolationSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetExtrapolationSigma (double extrapolationSigma) inline
Definition at line 135 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetFinalRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetFinalRadius (double FinalRadius) inline
Definition at line 114 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetForwardImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetForwardImage (InputImageConstPointer forwardImage) inline
Definition at line 67 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetInitialTransformField()
template<unsigned int ImageDimension> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetInitialTransformField (VectorFieldType * field)
Definition at line 64 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.hxx.
Referenced by anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::PyramidalDistortionCorrectionBlockMatchingBridge(), and anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetPercentageKept().
SetLastPyramidLevel()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetLastPyramidLevel (unsigned int LastPyramidLevel) inline
Definition at line 159 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetMaximumIterations (unsigned int MaximumIterations) inline
Definition at line 102 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold) inline
Definition at line 144 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetMetric()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetMetric (Metric metric) inline
Definition at line 126 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetNeighborhoodApproximation (double neighborhoodApproximation) inline
Definition at line 147 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels) inline
Definition at line 156 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations) inline
Definition at line 99 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetOutlierSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetOutlierSigma (double outlierSigma) inline
Definition at line 141 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetOutputTransformFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetOutputTransformFile (std::string outputTransformFile) inline
Definition at line 84 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetPercentageKept()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetPercentageKept (double PercentageKept) inline
Definition at line 162 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
References anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetInitialTransformField().
SetResultFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetResultFile (std::string resultFile) inline
Definition at line 81 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetScaleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetScaleUpperBound (double ScaleUpperBound) inline
Definition at line 120 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetSearchRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetSearchRadius (double SearchRadius) inline
Definition at line 105 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetSearchScaleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetSearchScaleRadius (double SearchScaleRadius) inline
Definition at line 108 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetSearchSkewRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetSearchSkewRadius (double SearchSkewRadius) inline
Definition at line 111 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetSkewUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetSkewUpperBound (double SkewUpperBound) inline
Definition at line 123 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetStDevThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetStDevThreshold (float StDevThreshold) inline
Definition at line 93 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetTranlateUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetTranlateUpperBound (double TranlateUpperBound) inline
Definition at line 117 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetTransformDirection()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetTransformDirection (unsigned int TransformDirection) inline
Definition at line 96 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetTransformKind()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetTransformKind (TransformKind tr) inline
Definition at line 129 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
SetWeightedAgregation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::SetWeightedAgregation (bool WeightedAgregation) inline
Definition at line 153 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.h.
Update()
template<unsigned int ImageDimension> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::Update ()
Definition at line 79 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.hxx.
References Bobyqa, MSmoother, anima::BaseBlockMatcher< TInputImageType >::SetBlockPercentageKept(), anima::DenseSVFTransformAgregator< NDimensions >::SetDistanceBoundary(), anima::BalooSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::DenseSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::DenseSVFTransformAgregator< NDimensions >::SetMEstimateConvergenceThreshold(), anima::DenseSVFTransformAgregator< NDimensions >::SetNeighborhoodHalfSize(), anima::DenseSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::BalooSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::DenseSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), anima::BalooSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), and anima::BaseTransformAgregator< NDimensions >::SetOutputTransformType().
WriteOutputs()
template<unsigned int ImageDimension> void anima::PyramidalDistortionCorrectionBlockMatchingBridge< ImageDimension >::WriteOutputs ()
Definition at line 358 of file animaPyramidalDistortionCorrectionBlockMatchingBridge.hxx.
The documentation for this class was generated from the following files:
animaPyramidalDistortionCorrectionBlockMatchingBridge.h
animaPyramidalDistortionCorrectionBlockMatchingBridge.hxx