ANIMA: anima::ImageClassifierFilter< TInput, TMask, TOutput > Class Template Reference
anima::ImageClassifierFilter< TInput, TMask, TOutput > Class Template Reference
Classify each voxels into one of the given GMM classes.
#include <animaImageClassifierFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::VariableSizeMatrix< NumericType > DoubleVariableSizeMatrixType
typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > GaussianFunctionType
typedef itk::ImageRegionConstIterator< TInput > InputConstIteratorType
typedef TInput::ConstPointer InputImageConstPointer
typedef itk::ImageRegionConstIterator< TMask > MaskConstIteratorType
typedef itk::VariableLengthVector< double > MeasurementVectorType
typedef double NumericType
typedef TOutput::ConstPointer OutputImageConstPointer
typedef TOutput::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::ImageRegionIterator< TOutput > OutputIteratorType
typedef itk::SmartPointer< Self > Pointer
typedef ImageClassifierFilter Self
typedef itk::ImageToImageFilter< TInput, TOutput > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::vector< GaussianFunctionType::Pointer > GetAlphas ()
std::vector< GaussianFunctionType::Pointer > GetGaussiabModel ()
virtual const char * GetNameOfClass () const
virtual bool GetVerbose ()
void SetAlphas (std::vector< double > &model)
void SetGaussianModel (std::vector< GaussianFunctionType::Pointer > &model)
void SetInputImage1 (const TInput *image)
void SetInputImage2 (const TInput *image)
void SetInputImage3 (const TInput *image)
void SetInputImage4 (const TInput *image)
void SetInputImage5 (const TInput *image)
void SetMask (const TMask *mask)
void SetOutputFilename (std::string filename)
void SetTol (const double tol)
virtual void SetVerbose (bool _arg)
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
TInput::ConstPointer GetInputImage1 ()
TInput::ConstPointer GetInputImage2 ()
TInput::ConstPointer GetInputImage3 ()
TInput::ConstPointer GetInputImage4 ()
TInput::ConstPointer GetInputImage5 ()
TMask::ConstPointer GetMask ()
ImageClassifierFilter ()
double probability (DoubleVariableSizeMatrixType &point, GaussianFunctionType::Pointer model)
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~ImageClassifierFilter ()
Detailed Description
template<typename TInput, typename TMask, typename TOutput = TInput>
class anima::ImageClassifierFilter< TInput, TMask, TOutput >
Classify each voxels into one of the given GMM classes.
Definition at line 15 of file animaImageClassifierFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::SmartPointer<const Self> anima::ImageClassifierFilter< TInput, TMask, TOutput >::ConstPointer
Definition at line 23 of file animaImageClassifierFilter.h.
DoubleVariableSizeMatrixType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::VariableSizeMatrix<NumericType> anima::ImageClassifierFilter< TInput, TMask, TOutput >::DoubleVariableSizeMatrixType
Definition at line 43 of file animaImageClassifierFilter.h.
GaussianFunctionType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::Statistics::GaussianMembershipFunction< MeasurementVectorType > anima::ImageClassifierFilter< TInput, TMask, TOutput >::GaussianFunctionType
Definition at line 46 of file animaImageClassifierFilter.h.
InputConstIteratorType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageRegionConstIterator< TInput > anima::ImageClassifierFilter< TInput, TMask, TOutput >::InputConstIteratorType
Definition at line 33 of file animaImageClassifierFilter.h.
InputImageConstPointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef TInput::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::InputImageConstPointer
Image typedef support
Definition at line 32 of file animaImageClassifierFilter.h.
MaskConstIteratorType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageRegionConstIterator< TMask > anima::ImageClassifierFilter< TInput, TMask, TOutput >::MaskConstIteratorType
Mask typedef support
Definition at line 36 of file animaImageClassifierFilter.h.
MeasurementVectorType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::VariableLengthVector<double> anima::ImageClassifierFilter< TInput, TMask, TOutput >::MeasurementVectorType
Definition at line 45 of file animaImageClassifierFilter.h.
NumericType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef double anima::ImageClassifierFilter< TInput, TMask, TOutput >::NumericType
Definition at line 42 of file animaImageClassifierFilter.h.
OutputImageConstPointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef TOutput::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::OutputImageConstPointer
Definition at line 39 of file animaImageClassifierFilter.h.
OutputImagePointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef TOutput::Pointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::OutputImagePointer
Definition at line 38 of file animaImageClassifierFilter.h.
OutputImageRegionType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef Superclass::OutputImageRegionType anima::ImageClassifierFilter< TInput, TMask, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 66 of file animaImageClassifierFilter.h.
OutputIteratorType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageRegionIterator< TOutput > anima::ImageClassifierFilter< TInput, TMask, TOutput >::OutputIteratorType
Definition at line 40 of file animaImageClassifierFilter.h.
Pointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::SmartPointer<Self> anima::ImageClassifierFilter< TInput, TMask, TOutput >::Pointer
Definition at line 22 of file animaImageClassifierFilter.h.
Self
template<typename TInput , typename TMask , typename TOutput = TInput> typedef ImageClassifierFilter anima::ImageClassifierFilter< TInput, TMask, TOutput >::Self
Standard class typedefs.
Definition at line 20 of file animaImageClassifierFilter.h.
Superclass
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageToImageFilter< TInput , TOutput > anima::ImageClassifierFilter< TInput, TMask, TOutput >::Superclass
Definition at line 21 of file animaImageClassifierFilter.h.
Constructor & Destructor Documentation
ImageClassifierFilter()
template<typename TInput , typename TMask , typename TOutput = TInput> anima::ImageClassifierFilter< TInput, TMask, TOutput >::ImageClassifierFilter () inline protected
Definition at line 79 of file animaImageClassifierFilter.h.
~ImageClassifierFilter()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter () inline protected virtual
Definition at line 91 of file animaImageClassifierFilter.h.
References anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage1(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage2(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage3(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage4(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage5(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetMask(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::probability(), and anima::ImageClassifierFilter< TInput, TMask, TOutput >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual::itk::LightObject::Pointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::CreateAnother (void) const
GetAlphas()
template<typename TInput , typename TMask , typename TOutput = TInput> std::vector<GaussianFunctionType::Pointer> anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetAlphas () inline
Definition at line 76 of file animaImageClassifierFilter.h.
GetGaussiabModel()
template<typename TInput , typename TMask , typename TOutput = TInput> std::vector<GaussianFunctionType::Pointer> anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetGaussiabModel () inline
Definition at line 75 of file animaImageClassifierFilter.h.
GetInputImage1()
template<typename TInput , typename TMask , typename TOutput > TInput::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage1 () protected
Definition at line 59 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
GetInputImage2()
template<typename TInput , typename TMask , typename TOutput > TInput::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage2 () protected
Definition at line 73 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
GetInputImage3()
template<typename TInput , typename TMask , typename TOutput > TInput::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage3 () protected
Definition at line 80 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
GetInputImage4()
template<typename TInput , typename TMask , typename TOutput > TInput::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage4 () protected
Definition at line 87 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
GetInputImage5()
template<typename TInput , typename TMask , typename TOutput > TInput::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetInputImage5 () protected
Definition at line 94 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
GetMask()
template<typename TInput , typename TMask , typename TOutput > TMask::ConstPointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetMask () protected
Definition at line 66 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
GetNameOfClass()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual const char* anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetVerbose()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual bool anima::ImageClassifierFilter< TInput, TMask, TOutput >::GetVerbose () virtual
New()
template<typename TInput , typename TMask , typename TOutput = TInput> static Pointer anima::ImageClassifierFilter< TInput, TMask, TOutput >::New () static
Method for creation through the object factory.
probability()
template<typename TInput , typename TMask , typename TOutput > double anima::ImageClassifierFilter< TInput, TMask, TOutput >::probability (DoubleVariableSizeMatrixType & point, GaussianFunctionType::Pointer model) protected
Definition at line 171 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
SetAlphas()
template<typename TInput , typename TMask , typename TOutput = TInput> void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetAlphas (std::vector< double > & model) inline
Definition at line 73 of file animaImageClassifierFilter.h.
SetGaussianModel()
template<typename TInput , typename TMask , typename TOutput = TInput> void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetGaussianModel (std::vector< GaussianFunctionType::Pointer > & model) inline
Definition at line 72 of file animaImageClassifierFilter.h.
SetInputImage1()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage1 (const TInput * image)
The mri images.
Definition at line 9 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetTol().
SetInputImage2()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage2 (const TInput * image)
Definition at line 22 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetTol().
SetInputImage3()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage3 (const TInput * image)
Definition at line 31 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetTol().
SetInputImage4()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage4 (const TInput * image)
Definition at line 39 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetTol().
SetInputImage5()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage5 (const TInput * image)
Definition at line 48 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetTol().
SetMask()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetMask (const TMask * mask)
mask in which the segmentation will be performed
Definition at line 16 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetTol().
SetOutputFilename()
template<typename TInput , typename TMask , typename TOutput = TInput> void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetOutputFilename (std::string filename) inline
Definition at line 74 of file animaImageClassifierFilter.h.
SetTol()
template<typename TInput , typename TMask , typename TOutput = TInput> void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetTol (const double tol) inline
Definition at line 48 of file animaImageClassifierFilter.h.
References anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage1(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage2(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage3(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage4(), anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetInputImage5(), and anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetMask().
SetVerbose()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual void anima::ImageClassifierFilter< TInput, TMask, TOutput >::SetVerbose (bool _arg) virtual
ThreadedGenerateData()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 114 of file animaImageClassifierFilter.hxx.
Referenced by anima::ImageClassifierFilter< TInput, TMask, TOutput >::WriteOutputs(), and anima::ImageClassifierFilter< TInput, TMask, TOutput >::~ImageClassifierFilter().
WriteOutputs()
template<typename TInput , typename TMask , typename TOutput > void anima::ImageClassifierFilter< TInput, TMask, TOutput >::WriteOutputs ()
Definition at line 102 of file animaImageClassifierFilter.hxx.
References anima::ImageClassifierFilter< TInput, TMask, TOutput >::ThreadedGenerateData().
The documentation for this class was generated from the following files:
animaImageClassifierFilter.h
animaImageClassifierFilter.hxx