ANIMA: anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference
anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference
#include <animaMCMResampleImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageType InputImageType
typedef Superclass::InputPixelType InputPixelType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMResampleImageFilter Self
typedef OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType > Superclass
Public Types inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
typedef itk::SmartPointer< const Self > ConstPointer
typedef InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef TOutputImage::DirectionType DirectionType
typedef GeometryImageType::Pointer GeometryImagePointer
typedef itk::Image< unsigned char, itkGetStaticConstMacro(ImageDimension)> GeometryImageType
typedef InputImageType::Pointer InputImagePointer
typedef TImageType InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::PixelType InputPixelType
typedef InputImageType::PointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< InputImageType, TInterpolatorPrecisionType > InterpolatorType
typedef TOutputImage::PointType OriginPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef TOutputImage::RegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef InterpolatorType::PointType PointType
typedef TOutputImage::RegionType RegionType
typedef OrientedModelBaseResampleImageFilter Self
typedef TOutputImage::SpacingType SpacingType
typedef anima::MaskedImageToImageFilter< TImageType, TImageType > Superclass
typedef TImageType TOutputImage
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> TransformType
Public Types inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TImageType ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< TImageType, TImageType > Superclass
typedef itk::ImageSource< TImageType >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
void SetReferenceOutputModel (const MCModelPointer &model)
Sets reference output MCM model, necessary to determine output organization (and rotate)
Public Member Functions inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
virtual bool GetFiniteStrainReorientation ()
virtual InterpolatorType * GetInterpolator ()
virtual const DirectionType & GetOutputDirection () const
virtual const RegionType & GetOutputLargestPossibleRegion () const
virtual const OriginPointType & GetOutputOrigin () const
virtual const SpacingType & GetOutputSpacing () const
itkGetObjectMacro (Transform, TransformType) virtual void SetInterpolator(InterpolatorPointer _arg)
virtual void SetFiniteStrainReorientation (bool _arg)
virtual void SetOutputDirection (DirectionType _arg)
virtual void SetOutputLargestPossibleRegion (RegionType _arg)
virtual void SetOutputOrigin (OriginPointType _arg)
virtual void SetOutputSpacing (SpacingType _arg)
virtual void SetTransform (TransformType *_arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = InputImageType::ImageDimension
Static Public Attributes inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
static const unsigned int ImageDimension = InputImageType::ImageDimension
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual unsigned int GetOutputVectorLength () ITK_OVERRIDE
virtual void InitializeInterpolator () ITK_OVERRIDE
Initializes the default interpolator, might change in derived classes.
virtual itk::LightObject::Pointer InternalClone () const ITK_OVERRIDE
MCMResampleImageFilter ()
virtual void ReorientInterpolatedModel (const InputPixelType &interpolatedModel, vnl_matrix< double > &modelOrientationMatrix, InputPixelType &orientedModel, itk::ThreadIdType threadId) ITK_OVERRIDE
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
virtual ~MCMResampleImageFilter ()
Protected Member Functions inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
vnl_matrix< double > ComputeLinearJacobianMatrix ()
void ComputeLocalJacobianMatrix (InputIndexType &index, vnl_matrix< double > &reorientationMatrix)
virtual void ComputeRotationParametersFromReorientationMatrix (vnl_matrix< double > &reorientationMatrix, vnl_matrix< double > &modelOrientationMatrix)
virtual void GenerateInputRequestedRegion () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
template<class T >
void InitializeZeroPixel (itk::VariableLengthVector< T > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<class T >
void InitializeZeroPixel (T &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
template<class T >
bool isZero (itk::VariableLengthVector< T > &dataVec)
template<class T >
bool isZero (T &data)
void LinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
void NonLinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
OrientedModelBaseResampleImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~OrientedModelBaseResampleImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (TImageType *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (TImageType *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TImageType, typename TInterpolatorPrecisionType = float>
class anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >
Definition at line 10 of file animaMCMResampleImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<const Self> anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ConstPointer
Definition at line 19 of file animaMCMResampleImageFilter.h.
InputImageType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef Superclass::InputImageType anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputImageType
Definition at line 22 of file animaMCMResampleImageFilter.h.
InputPixelType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef Superclass::InputPixelType anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputPixelType
Definition at line 21 of file animaMCMResampleImageFilter.h.
MCModelPointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef MCModelType::Pointer anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::MCModelPointer
Definition at line 26 of file animaMCMResampleImageFilter.h.
MCModelType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef anima::MultiCompartmentModel anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::MCModelType
Definition at line 25 of file animaMCMResampleImageFilter.h.
Pointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<Self> anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Pointer
Definition at line 18 of file animaMCMResampleImageFilter.h.
Self
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef MCMResampleImageFilter anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Self
Standard class typedefs.
Definition at line 15 of file animaMCMResampleImageFilter.h.
Superclass
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef OrientedModelBaseResampleImageFilter<TImageType,TInterpolatorPrecisionType> anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Superclass
Definition at line 17 of file animaMCMResampleImageFilter.h.
Constructor & Destructor Documentation
MCMResampleImageFilter()
template<typename TImageType , typename TInterpolatorPrecisionType = float> anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::MCMResampleImageFilter () inline protected
Definition at line 38 of file animaMCMResampleImageFilter.h.
~MCMResampleImageFilter()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~MCMResampleImageFilter () inline protected virtual
Definition at line 42 of file animaMCMResampleImageFilter.h.
References anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData(), anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputVectorLength(), anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeInterpolator(), anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InternalClone(), and anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 40 of file animaMCMResampleImageFilter.hxx.
References anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetReferenceOutputModel().
Referenced by anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InternalClone(), and anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~MCMResampleImageFilter().
CreateAnother()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual::itk::LightObject::Pointer anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::CreateAnother (void) const
GetNameOfClass()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const char* anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
GetOutputVectorLength()
template<typename TImageType , typename TInterpolatorPrecisionType > unsigned int anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputVectorLength () protected virtual
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 13 of file animaMCMResampleImageFilter.hxx.
References anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InternalClone().
Referenced by anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~MCMResampleImageFilter().
InitializeInterpolator()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeInterpolator () protected virtual
Initializes the default interpolator, might change in derived classes.
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 64 of file animaMCMResampleImageFilter.hxx.
References anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
Referenced by anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetReferenceOutputModel(), and anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~MCMResampleImageFilter().
InternalClone()
template<typename TImageType , typename TInterpolatorPrecisionType > itk::LightObject::Pointer anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InternalClone () const protected virtual
Returns a class copy with important specific variables set, not the greatest implementation especially in terms of interpolators and other internal pointers copy (not done here). Use with extreme caution
Definition at line 25 of file animaMCMResampleImageFilter.hxx.
References anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData(), and anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetReferenceOutputModel().
Referenced by anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputVectorLength(), and anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~MCMResampleImageFilter().
New()
template<typename TImageType , typename TInterpolatorPrecisionType = float> static Pointer anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::New () static
Method for creation through the object factory.
ReorientInterpolatedModel()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel (const InputPixelType & interpolatedModel, vnl_matrix< double > & modelOrientationMatrix, InputPixelType & orientedModel, itk::ThreadIdType threadId) protected virtual
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
Implements anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 76 of file animaMCMResampleImageFilter.hxx.
Referenced by anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeInterpolator(), and anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~MCMResampleImageFilter().
SetReferenceOutputModel()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetReferenceOutputModel (const MCModelPointer & model)
Sets reference output MCM model, necessary to determine output organization (and rotate)
Definition at line 56 of file animaMCMResampleImageFilter.hxx.
References anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeInterpolator().
Referenced by anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData(), and anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InternalClone().
Member Data Documentation
ImageDimension
template<typename TImageType , typename TInterpolatorPrecisionType = float> const unsigned int anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ImageDimension = InputImageType::ImageDimension static
Definition at line 23 of file animaMCMResampleImageFilter.h.
The documentation for this class was generated from the following files:
animaMCMResampleImageFilter.h
animaMCMResampleImageFilter.hxx