ANIMA: anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
#include <animaMCMPairingMeanSquaresImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, ImageDimension > ContinuousIndexType
typedef Superclass::CoordinateRepresentationType CoordinateRepresentationType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef MCModelType::Vector3DType GradientType
typedef Superclass::InputPointType InputPointType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef TFixedImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMPairingMeanSquaresImageToImageMetric Self
typedef BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > TFixedImage
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > TMovingImage
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ParametersValueType CoordinateRepresentationType
typedef Superclass::DerivativeType DerivativeType
typedef FixedImageType::ConstPointer FixedImageConstPointer
typedef FixedImageMaskType::ConstPointer FixedImageMaskConstPointer
typedef FixedImageMaskType::Pointer FixedImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(FixedImageDimension) > FixedImageMaskType
typedef FixedImageType::RegionType FixedImageRegionType
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > FixedImageType
typedef TransformType::InputPointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< MovingImageType, CoordinateRepresentationType > InterpolatorType
typedef Superclass::MeasureType MeasureType
enum ModelReorientationType
typedef MovingImageType::ConstPointer MovingImageConstPointer
typedef MovingImageMaskType::ConstPointer MovingImageMaskConstPointer
typedef MovingImageMaskType::Pointer MovingImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(MovingImageDimension) > MovingImageMaskType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > ::PixelType MovingImagePixelType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > MovingImageType
typedef TransformType::OutputPointType OutputPointType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef double RealType
typedef BaseOrientedModelImageToImageMetric Self
typedef itk::SingleValuedCostFunction Superclass
typedef TransformType::JacobianType TransformJacobianType
typedef TransformType::ParametersType TransformParametersType
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< CoordinateRepresentationType, itkGetStaticConstMacro(MovingImageDimension), itkGetStaticConstMacro(FixedImageDimension)> TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void PreComputeFixedValues ()
virtual void SetOneToOneMapping (bool _arg)
Public Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
Should not be used.
virtual const FixedImageType * GetFixedImage () const
virtual const FixedImageMaskType * GetFixedImageMask () const
virtual const FixedImageRegionType & GetFixedImageRegion () const
virtual const InterpolatorType * GetInterpolator () const
virtual ModelReorientationType GetModelRotation () const
virtual const MovingImageType * GetMovingImage () const
virtual const MovingImageMaskType * GetMovingImageMask () const
unsigned int GetNumberOfParameters (void) const ITK_OVERRIDE
virtual const unsigned long & GetNumberOfPixelsCounted () const
virtual const TransformType * GetTransform () const
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &value, DerivativeType &derivative) const ITK_OVERRIDE
virtual void Initialize ()
virtual void SetFixedImage (const FixedImageType *_arg)
virtual void SetFixedImageMask (FixedImageMaskType *_arg)
virtual void SetFixedImageMask (const FixedImageMaskType *_arg)
virtual void SetFixedImageRegion (FixedImageRegionType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetModelRotation (ModelReorientationType _arg)
virtual void SetMovingImage (const MovingImageType *_arg)
virtual void SetMovingImageMask (MovingImageMaskType *_arg)
virtual void SetMovingImageMask (const MovingImageMaskType *_arg)
virtual void SetTransform (TransformType *_arg)
void SetTransformParameters (const ParametersType &parameters) const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
bool CheckTensorCompatibility () const
double ComputeNonTensorBasedMetricPart (unsigned int index, const MCModelPointer &movingValue) const
double ComputeTensorBasedMetricPart (unsigned int index, const MCModelPointer &movingValue) const
bool isZero (PixelType &vector) const
MCMPairingMeanSquaresImageToImageMetric ()
virtual ~MCMPairingMeanSquaresImageToImageMetric ()
Protected Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
BaseOrientedModelImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~BaseOrientedModelImageToImageMetric ()
Additional Inherited Members
Static Public Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
static const unsigned int FixedImageDimension
static const unsigned int MovingImageDimension
Protected Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
FixedImageConstPointer m_FixedImage
FixedImageMaskConstPointer m_FixedImageMask
InterpolatorPointer m_Interpolator
MovingImageConstPointer m_MovingImage
MovingImageMaskConstPointer m_MovingImageMask
unsigned long m_NumberOfPixelsCounted
vnl_matrix< double > m_OrientationMatrix
TransformPointer m_Transform
Detailed Description
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension>
class anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >
Definition at line 11 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
Member Typedef Documentation
ConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<const Self> anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ConstPointer
Definition at line 22 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
ContinuousIndexType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::ContinuousIndex<double, ImageDimension> anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ContinuousIndexType
Definition at line 42 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
CoordinateRepresentationType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::CoordinateRepresentationType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CoordinateRepresentationType
Definition at line 44 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
FixedImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageConstPointer anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageConstPointer
Definition at line 49 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
FixedImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageType
Definition at line 47 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
GradientType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Vector3DType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GradientType
Definition at line 26 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
InputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::InputPointType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::InputPointType
Definition at line 41 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
MCModelPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Pointer anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelPointer
Definition at line 25 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
MCModelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MultiCompartmentModel anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelType
Definition at line 24 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
MeasureType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MeasureType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType
Definition at line 46 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
MovingImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageConstPointer anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageConstPointer
Definition at line 50 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
MovingImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageType
Definition at line 48 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
OutputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::OutputPointType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::OutputPointType
Definition at line 40 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
PixelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef TFixedImage::PixelType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PixelType
Types transferred from the base class
Definition at line 35 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
Pointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<Self> anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Pointer
Definition at line 21 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
Self
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCMPairingMeanSquaresImageToImageMetric anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Self
Definition at line 19 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
Superclass
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef BaseOrientedModelImageToImageMetric<TFixedImage, TMovingImage > anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Superclass
Definition at line 20 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
TFixedImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TFixedImage
Standard class typedefs.
Definition at line 16 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
TMovingImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TMovingImage
Definition at line 17 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
TransformParametersType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformParametersType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformParametersType
Definition at line 39 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
TransformPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformPointer anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformPointer
Definition at line 38 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
TransformType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformType
Definition at line 37 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
Constructor & Destructor Documentation
MCMPairingMeanSquaresImageToImageMetric()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMPairingMeanSquaresImageToImageMetric () protected
Definition at line 16 of file animaMCMPairingMeanSquaresImageToImageMetric.hxx.
References anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), and anima::MultiCompartmentModelCreator::SetNumberOfCompartments().
Referenced by anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMPairingMeanSquaresImageToImageMetric().
~MCMPairingMeanSquaresImageToImageMetric()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMPairingMeanSquaresImageToImageMetric () inline protected virtual
Definition at line 61 of file animaMCMPairingMeanSquaresImageToImageMetric.h.
References anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility(), anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart(), anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart(), anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero(), and anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMPairingMeanSquaresImageToImageMetric().
Member Function Documentation
CheckTensorCompatibility()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility () const protected
Definition at line 35 of file animaMCMPairingMeanSquaresImageToImageMetric.hxx.
References anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
Referenced by anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMPairingMeanSquaresImageToImageMetric(), and anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMPairingMeanSquaresImageToImageMetric().
ComputeNonTensorBasedMetricPart()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> double anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart (unsigned int index, const MCModelPointer & movingValue) const protected
Definition at line 304 of file animaMCMPairingMeanSquaresImageToImageMetric.hxx.
References anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
Referenced by anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart(), and anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMPairingMeanSquaresImageToImageMetric().
ComputeTensorBasedMetricPart()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> double anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart (unsigned int index, const MCModelPointer & movingValue) const protected
Definition at line 132 of file animaMCMPairingMeanSquaresImageToImageMetric.hxx.
References anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart(), anima::GetTensorLogarithm(), and anima::GetVectorRepresentation().
Referenced by anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), and anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMPairingMeanSquaresImageToImageMetric().
CreateAnother()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual::itk::LightObject::Pointer anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CreateAnother (void) const
GetNameOfClass()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual const char* anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >.
GetValue()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Definition at line 59 of file animaMCMPairingMeanSquaresImageToImageMetric.hxx.
References anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeTensorBasedMetricPart(), and PPD.
Referenced by anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CheckTensorCompatibility().
isZero()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero (PixelType & vector) const protected
Definition at line 313 of file animaMCMPairingMeanSquaresImageToImageMetric.hxx.
References anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues().
Referenced by anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ComputeNonTensorBasedMetricPart(), and anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMPairingMeanSquaresImageToImageMetric().
New()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> static Pointer anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::New () static
Method for creation through the object factory.
PreComputeFixedValues()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues ()
Definition at line 329 of file animaMCMPairingMeanSquaresImageToImageMetric.hxx.
Referenced by anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero().
SetOneToOneMapping()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual void anima::MCMPairingMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetOneToOneMapping (bool _arg) virtual
The documentation for this class was generated from the following files:
animaMCMPairingMeanSquaresImageToImageMetric.h
animaMCMPairingMeanSquaresImageToImageMetric.hxx