ANIMA: anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType > Class Template Reference
anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType > Class Template Reference
#include <animaLocalPatchCovarianceDistanceImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef vnl_matrix< double > CovarianceType
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::Pointer InputImagePointer
typedef itk::VectorImage< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef LocalPatchCovarianceDistanceImageFilter< PixelScalarType > Self
typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > Superclass
typedef InputImageType::PixelType VectorType
Public Types inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::VectorImage< PixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< PixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetPatchHalfSize (unsigned int _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
LocalPatchCovarianceDistanceImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~LocalPatchCovarianceDistanceImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class PixelScalarType>
class anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >
Definition at line 14 of file animaLocalPatchCovarianceDistanceImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class PixelScalarType> typedef itk::SmartPointer<const Self> anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ConstPointer
Definition at line 21 of file animaLocalPatchCovarianceDistanceImageFilter.h.
CovarianceType
template<class PixelScalarType> typedef vnl_matrix<double> anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::CovarianceType
Definition at line 35 of file animaLocalPatchCovarianceDistanceImageFilter.h.
InputImageIndexType
template<class PixelScalarType> typedef InputImageType::IndexType anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::InputImageIndexType
Definition at line 40 of file animaLocalPatchCovarianceDistanceImageFilter.h.
InputImagePointer
template<class PixelScalarType> typedef InputImageType::Pointer anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::InputImagePointer
Definition at line 39 of file animaLocalPatchCovarianceDistanceImageFilter.h.
InputImageType
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType, 3> anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::InputImageType
Image typedef support
Definition at line 30 of file animaLocalPatchCovarianceDistanceImageFilter.h.
MaskImageType
template<class PixelScalarType> typedef Superclass::MaskImageType anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::MaskImageType
Definition at line 38 of file animaLocalPatchCovarianceDistanceImageFilter.h.
OutputImagePointer
template<class PixelScalarType> typedef OutputImageType::Pointer anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 41 of file animaLocalPatchCovarianceDistanceImageFilter.h.
OutputImageRegionType
template<class PixelScalarType> typedef Superclass::OutputImageRegionType anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::OutputImageRegionType
Superclass typedefs.
Definition at line 44 of file animaLocalPatchCovarianceDistanceImageFilter.h.
OutputImageType
template<class PixelScalarType> typedef itk::Image<PixelScalarType, 3> anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::OutputImageType
Definition at line 31 of file animaLocalPatchCovarianceDistanceImageFilter.h.
Pointer
template<class PixelScalarType> typedef itk::SmartPointer<Self> anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::Pointer
Definition at line 20 of file animaLocalPatchCovarianceDistanceImageFilter.h.
Self
template<class PixelScalarType> typedef LocalPatchCovarianceDistanceImageFilter<PixelScalarType> anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 19 of file animaLocalPatchCovarianceDistanceImageFilter.h.
Superclass
template<class PixelScalarType> typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::Superclass
Definition at line 37 of file animaLocalPatchCovarianceDistanceImageFilter.h.
VectorType
template<class PixelScalarType> typedef InputImageType::PixelType anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::VectorType
Definition at line 33 of file animaLocalPatchCovarianceDistanceImageFilter.h.
Constructor & Destructor Documentation
LocalPatchCovarianceDistanceImageFilter()
template<class PixelScalarType> anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::LocalPatchCovarianceDistanceImageFilter () inline protected
Definition at line 48 of file animaLocalPatchCovarianceDistanceImageFilter.h.
~LocalPatchCovarianceDistanceImageFilter()
template<class PixelScalarType> virtual anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::~LocalPatchCovarianceDistanceImageFilter () inline protected virtual
Definition at line 58 of file animaLocalPatchCovarianceDistanceImageFilter.h.
References anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class PixelScalarType > void anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
Definition at line 15 of file animaLocalPatchCovarianceDistanceImageFilter.hxx.
References anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ThreadedGenerateData().
Referenced by anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::~LocalPatchCovarianceDistanceImageFilter().
CreateAnother()
template<class PixelScalarType> virtual::itk::LightObject::Pointer anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::CreateAnother (void) const
GetNameOfClass()
template<class PixelScalarType> virtual const char* anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
New()
template<class PixelScalarType> static Pointer anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
Referenced by anima::LowMemoryLocalPatchCovarianceDistanceBridge::Update().
SetPatchHalfSize()
template<class PixelScalarType> virtual void anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::SetPatchHalfSize (unsigned int _arg) virtual
ThreadedGenerateData()
template<class PixelScalarType > void anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 29 of file animaLocalPatchCovarianceDistanceImageFilter.hxx.
References anima::computePatchMeanAndCovariance(), and anima::VectorCovarianceTest().
Referenced by anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >::~LocalPatchCovarianceDistanceImageFilter().
The documentation for this class was generated from the following files:
animaLocalPatchCovarianceDistanceImageFilter.h
animaLocalPatchCovarianceDistanceImageFilter.hxx