ANIMA: anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
#include <animaMCMMeanSquaresImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, ImageDimension > ContinuousIndexType
typedef Superclass::CoordinateRepresentationType CoordinateRepresentationType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef MCModelType::Vector3DType GradientType
typedef Superclass::InputPointType InputPointType
typedef anima::MCML2DistanceComputer::Pointer MCML2DistanceComputerPointer
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef TFixedImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMMeanSquaresImageToImageMetric Self
typedef BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > TFixedImage
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > TMovingImage
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ParametersValueType CoordinateRepresentationType
typedef Superclass::DerivativeType DerivativeType
typedef FixedImageType::ConstPointer FixedImageConstPointer
typedef FixedImageMaskType::ConstPointer FixedImageMaskConstPointer
typedef FixedImageMaskType::Pointer FixedImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(FixedImageDimension) > FixedImageMaskType
typedef FixedImageType::RegionType FixedImageRegionType
typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > FixedImageType
typedef TransformType::InputPointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< MovingImageType, CoordinateRepresentationType > InterpolatorType
typedef Superclass::MeasureType MeasureType
enum ModelReorientationType
typedef MovingImageType::ConstPointer MovingImageConstPointer
typedef MovingImageMaskType::ConstPointer MovingImageMaskConstPointer
typedef MovingImageMaskType::Pointer MovingImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(MovingImageDimension) > MovingImageMaskType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > ::PixelType MovingImagePixelType
typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > MovingImageType
typedef TransformType::OutputPointType OutputPointType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef double RealType
typedef BaseOrientedModelImageToImageMetric Self
typedef itk::SingleValuedCostFunction Superclass
typedef TransformType::JacobianType TransformJacobianType
typedef TransformType::ParametersType TransformParametersType
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< CoordinateRepresentationType, itkGetStaticConstMacro(MovingImageDimension), itkGetStaticConstMacro(FixedImageDimension)> TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void PreComputeFixedValues ()
void SetBigDelta (double val)
void SetForceApproximation (bool val)
void SetGradientDirections (std::vector< GradientType > &val)
void SetGradientStrengths (std::vector< double > &val)
void SetLowPassGaussianSigma (double val)
void SetSmallDelta (double val)
Public Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
Should not be used.
virtual const FixedImageType * GetFixedImage () const
virtual const FixedImageMaskType * GetFixedImageMask () const
virtual const FixedImageRegionType & GetFixedImageRegion () const
virtual const InterpolatorType * GetInterpolator () const
virtual ModelReorientationType GetModelRotation () const
virtual const MovingImageType * GetMovingImage () const
virtual const MovingImageMaskType * GetMovingImageMask () const
unsigned int GetNumberOfParameters (void) const ITK_OVERRIDE
virtual const unsigned long & GetNumberOfPixelsCounted () const
virtual const TransformType * GetTransform () const
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &value, DerivativeType &derivative) const ITK_OVERRIDE
virtual void Initialize ()
virtual void SetFixedImage (const FixedImageType *_arg)
virtual void SetFixedImageMask (FixedImageMaskType *_arg)
virtual void SetFixedImageMask (const FixedImageMaskType *_arg)
virtual void SetFixedImageRegion (FixedImageRegionType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetModelRotation (ModelReorientationType _arg)
virtual void SetMovingImage (const MovingImageType *_arg)
virtual void SetMovingImageMask (MovingImageMaskType *_arg)
virtual void SetMovingImageMask (const MovingImageMaskType *_arg)
virtual void SetTransform (TransformType *_arg)
void SetTransformParameters (const ParametersType &parameters) const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
bool isZero (PixelType &vector) const
MCMMeanSquaresImageToImageMetric ()
virtual ~MCMMeanSquaresImageToImageMetric ()
Protected Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
BaseOrientedModelImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~BaseOrientedModelImageToImageMetric ()
Additional Inherited Members
Static Public Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
static const unsigned int FixedImageDimension
static const unsigned int MovingImageDimension
Protected Attributes inherited from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >
FixedImageConstPointer m_FixedImage
FixedImageMaskConstPointer m_FixedImageMask
InterpolatorPointer m_Interpolator
MovingImageConstPointer m_MovingImage
MovingImageMaskConstPointer m_MovingImageMask
unsigned long m_NumberOfPixelsCounted
vnl_matrix< double > m_OrientationMatrix
TransformPointer m_Transform
Detailed Description
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension>
class anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >
Definition at line 12 of file animaMCMMeanSquaresImageToImageMetric.h.
Member Typedef Documentation
ConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<const Self> anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ConstPointer
Definition at line 23 of file animaMCMMeanSquaresImageToImageMetric.h.
ContinuousIndexType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::ContinuousIndex<double, ImageDimension> anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ContinuousIndexType
Definition at line 43 of file animaMCMMeanSquaresImageToImageMetric.h.
CoordinateRepresentationType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::CoordinateRepresentationType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CoordinateRepresentationType
Definition at line 45 of file animaMCMMeanSquaresImageToImageMetric.h.
FixedImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageConstPointer anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageConstPointer
Definition at line 50 of file animaMCMMeanSquaresImageToImageMetric.h.
FixedImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageType
Definition at line 48 of file animaMCMMeanSquaresImageToImageMetric.h.
GradientType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Vector3DType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GradientType
Definition at line 27 of file animaMCMMeanSquaresImageToImageMetric.h.
InputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::InputPointType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::InputPointType
Definition at line 42 of file animaMCMMeanSquaresImageToImageMetric.h.
MCML2DistanceComputerPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCML2DistanceComputer::Pointer anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCML2DistanceComputerPointer
Definition at line 53 of file animaMCMMeanSquaresImageToImageMetric.h.
MCModelPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCModelType::Pointer anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelPointer
Definition at line 26 of file animaMCMMeanSquaresImageToImageMetric.h.
MCModelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MultiCompartmentModel anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCModelType
Definition at line 25 of file animaMCMMeanSquaresImageToImageMetric.h.
MeasureType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MeasureType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType
Definition at line 47 of file animaMCMMeanSquaresImageToImageMetric.h.
MovingImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageConstPointer anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageConstPointer
Definition at line 51 of file animaMCMMeanSquaresImageToImageMetric.h.
MovingImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageType
Definition at line 49 of file animaMCMMeanSquaresImageToImageMetric.h.
OutputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::OutputPointType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::OutputPointType
Definition at line 41 of file animaMCMMeanSquaresImageToImageMetric.h.
PixelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef TFixedImage::PixelType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PixelType
Types transferred from the base class
Definition at line 36 of file animaMCMMeanSquaresImageToImageMetric.h.
Pointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<Self> anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Pointer
Definition at line 22 of file animaMCMMeanSquaresImageToImageMetric.h.
Self
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef MCMMeanSquaresImageToImageMetric anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Self
Definition at line 20 of file animaMCMMeanSquaresImageToImageMetric.h.
Superclass
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef BaseOrientedModelImageToImageMetric<TFixedImage, TMovingImage > anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Superclass
Definition at line 21 of file animaMCMMeanSquaresImageToImageMetric.h.
TFixedImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TFixedImagePixelType, ImageDimension > anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TFixedImage
Standard class typedefs.
Definition at line 17 of file animaMCMMeanSquaresImageToImageMetric.h.
TMovingImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef anima::MCMImage< TMovingImagePixelType, ImageDimension > anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TMovingImage
Definition at line 18 of file animaMCMMeanSquaresImageToImageMetric.h.
TransformParametersType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformParametersType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformParametersType
Definition at line 40 of file animaMCMMeanSquaresImageToImageMetric.h.
TransformPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformPointer anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformPointer
Definition at line 39 of file animaMCMMeanSquaresImageToImageMetric.h.
TransformType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformType
Definition at line 38 of file animaMCMMeanSquaresImageToImageMetric.h.
Constructor & Destructor Documentation
MCMMeanSquaresImageToImageMetric()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric () protected
Definition at line 14 of file animaMCMMeanSquaresImageToImageMetric.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), anima::MCML2DistanceComputer::New(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), and anima::MultiCompartmentModelCreator::SetNumberOfCompartments().
Referenced by anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetLowPassGaussianSigma(), and anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMMeanSquaresImageToImageMetric().
~MCMMeanSquaresImageToImageMetric()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMMeanSquaresImageToImageMetric () inline protected virtual
Definition at line 70 of file animaMCMMeanSquaresImageToImageMetric.h.
References anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero(), and anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric().
Member Function Documentation
CreateAnother()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual::itk::LightObject::Pointer anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CreateAnother (void) const
GetNameOfClass()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual const char* anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseOrientedModelImageToImageMetric< anima::MCMImage< TFixedImagePixelType, ImageDimension >, anima::MCMImage< TMovingImagePixelType, ImageDimension > >.
GetValue()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Definition at line 33 of file animaMCMMeanSquaresImageToImageMetric.hxx.
References anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero(), and PPD.
Referenced by anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric().
isZero()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> bool anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero (PixelType & vector) const protected
Definition at line 88 of file animaMCMMeanSquaresImageToImageMetric.hxx.
References anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues().
Referenced by anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue(), and anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~MCMMeanSquaresImageToImageMetric().
New()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> static Pointer anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::New () static
Method for creation through the object factory.
PreComputeFixedValues()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues ()
Definition at line 104 of file animaMCMMeanSquaresImageToImageMetric.hxx.
Referenced by anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::isZero(), and anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetLowPassGaussianSigma().
SetBigDelta()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> void anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetBigDelta (double val) inline
Definition at line 59 of file animaMCMMeanSquaresImageToImageMetric.h.
SetForceApproximation()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> void anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetForceApproximation (bool val) inline
Definition at line 63 of file animaMCMMeanSquaresImageToImageMetric.h.
SetGradientDirections()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> void anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientDirections (std::vector< GradientType > & val) inline
Definition at line 61 of file animaMCMMeanSquaresImageToImageMetric.h.
SetGradientStrengths()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> void anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetGradientStrengths (std::vector< double > & val) inline
Definition at line 60 of file animaMCMMeanSquaresImageToImageMetric.h.
SetLowPassGaussianSigma()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> void anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetLowPassGaussianSigma (double val) inline
Definition at line 64 of file animaMCMMeanSquaresImageToImageMetric.h.
References anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric(), and anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues().
SetSmallDelta()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> void anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::SetSmallDelta (double val) inline
Definition at line 58 of file animaMCMMeanSquaresImageToImageMetric.h.
The documentation for this class was generated from the following files:
animaMCMMeanSquaresImageToImageMetric.h
animaMCMMeanSquaresImageToImageMetric.hxx