ANIMA: anima::AxisRotationTransform< TScalarType > Class Template Reference
anima::AxisRotationTransform< TScalarType > Class Template Reference
#include <animaAxisRotationTransform.h>
Public Types
typedef Superclass::ScalarType AngleType
typedef Superclass::CenterType CenterType
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Matrix< ScalarType, 4, 4 > HomogeneousMatrixType
typedef Superclass::InputCovariantVectorType InputCovariantVectorType
typedef Superclass::InputPointType InputPointType
typedef Superclass::InputVectorType InputVectorType
typedef Superclass::InputVnlVectorType InputVnlVectorType
typedef Superclass::InverseMatrixType InverseMatrixType
typedef Superclass::JacobianType JacobianType
typedef Superclass::MatrixType MatrixType
typedef Superclass::OffsetType OffsetType
typedef Superclass::OutputCovariantVectorType OutputCovariantVectorType
typedef Superclass::OutputPointType OutputPointType
typedef Superclass::OutputVectorType OutputVectorType
typedef Superclass::OutputVnlVectorType OutputVnlVectorType
typedef Superclass::ParametersType ParametersType
typedef Superclass::ParametersValueType ParametersValueType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::ScalarType ScalarType
typedef AxisRotationTransform Self
typedef itk::MatrixOffsetTransformBase< TScalarType, 3 > Superclass
typedef Superclass::TranslationType TranslationType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
const ParametersType & GetParameters () const ITK_OVERRIDE
virtual void SetIdentity () ITK_OVERRIDE
void SetParameters (const ParametersType &parameters) ITK_OVERRIDE
void SetReferencePlaneNormal (InputVectorType &refPlaneNormal)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int InputSpaceDimension = 3
static const unsigned int OutputSpaceDimension = 3
static const unsigned int ParametersDimension = 3
static const unsigned int SpaceDimension = 3
Protected Member Functions
AxisRotationTransform ()
AxisRotationTransform (unsigned int outputSpaceDims, unsigned int paramsSpaceDims)
void ComputeMatrix () ITK_OVERRIDE
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~AxisRotationTransform ()
Detailed Description
template<class TScalarType = double>
class anima::AxisRotationTransform< TScalarType >
Definition at line 10 of file animaAxisRotationTransform.h.
Member Typedef Documentation
AngleType
template<class TScalarType = double> typedef Superclass::ScalarType anima::AxisRotationTransform< TScalarType >::AngleType
Definition at line 51 of file animaAxisRotationTransform.h.
CenterType
template<class TScalarType = double> typedef Superclass::CenterType anima::AxisRotationTransform< TScalarType >::CenterType
Definition at line 48 of file animaAxisRotationTransform.h.
ConstPointer
template<class TScalarType = double> typedef itk::SmartPointer<const Self> anima::AxisRotationTransform< TScalarType >::ConstPointer
Definition at line 18 of file animaAxisRotationTransform.h.
HomogeneousMatrixType
template<class TScalarType = double> typedef itk::Matrix<ScalarType,4,4> anima::AxisRotationTransform< TScalarType >::HomogeneousMatrixType
Definition at line 46 of file animaAxisRotationTransform.h.
InputCovariantVectorType
template<class TScalarType = double> typedef Superclass::InputCovariantVectorType anima::AxisRotationTransform< TScalarType >::InputCovariantVectorType
Definition at line 39 of file animaAxisRotationTransform.h.
InputPointType
template<class TScalarType = double> typedef Superclass::InputPointType anima::AxisRotationTransform< TScalarType >::InputPointType
Definition at line 43 of file animaAxisRotationTransform.h.
InputVectorType
template<class TScalarType = double> typedef Superclass::InputVectorType anima::AxisRotationTransform< TScalarType >::InputVectorType
Definition at line 37 of file animaAxisRotationTransform.h.
InputVnlVectorType
template<class TScalarType = double> typedef Superclass::InputVnlVectorType anima::AxisRotationTransform< TScalarType >::InputVnlVectorType
Definition at line 41 of file animaAxisRotationTransform.h.
InverseMatrixType
template<class TScalarType = double> typedef Superclass::InverseMatrixType anima::AxisRotationTransform< TScalarType >::InverseMatrixType
Definition at line 47 of file animaAxisRotationTransform.h.
JacobianType
template<class TScalarType = double> typedef Superclass::JacobianType anima::AxisRotationTransform< TScalarType >::JacobianType
Definition at line 35 of file animaAxisRotationTransform.h.
MatrixType
template<class TScalarType = double> typedef Superclass::MatrixType anima::AxisRotationTransform< TScalarType >::MatrixType
Definition at line 45 of file animaAxisRotationTransform.h.
OffsetType
template<class TScalarType = double> typedef Superclass::OffsetType anima::AxisRotationTransform< TScalarType >::OffsetType
Definition at line 50 of file animaAxisRotationTransform.h.
OutputCovariantVectorType
template<class TScalarType = double> typedef Superclass::OutputCovariantVectorType anima::AxisRotationTransform< TScalarType >::OutputCovariantVectorType
Definition at line 40 of file animaAxisRotationTransform.h.
OutputPointType
template<class TScalarType = double> typedef Superclass::OutputPointType anima::AxisRotationTransform< TScalarType >::OutputPointType
Definition at line 44 of file animaAxisRotationTransform.h.
OutputVectorType
template<class TScalarType = double> typedef Superclass::OutputVectorType anima::AxisRotationTransform< TScalarType >::OutputVectorType
Definition at line 38 of file animaAxisRotationTransform.h.
OutputVnlVectorType
template<class TScalarType = double> typedef Superclass::OutputVnlVectorType anima::AxisRotationTransform< TScalarType >::OutputVnlVectorType
Definition at line 42 of file animaAxisRotationTransform.h.
ParametersType
template<class TScalarType = double> typedef Superclass::ParametersType anima::AxisRotationTransform< TScalarType >::ParametersType
Definition at line 33 of file animaAxisRotationTransform.h.
ParametersValueType
template<class TScalarType = double> typedef Superclass::ParametersValueType anima::AxisRotationTransform< TScalarType >::ParametersValueType
Definition at line 34 of file animaAxisRotationTransform.h.
Pointer
template<class TScalarType = double> typedef itk::SmartPointer<Self> anima::AxisRotationTransform< TScalarType >::Pointer
Definition at line 17 of file animaAxisRotationTransform.h.
ScalarType
template<class TScalarType = double> typedef Superclass::ScalarType anima::AxisRotationTransform< TScalarType >::ScalarType
Definition at line 36 of file animaAxisRotationTransform.h.
Self
template<class TScalarType = double> typedef AxisRotationTransform anima::AxisRotationTransform< TScalarType >::Self
Standard class typedefs.
Definition at line 15 of file animaAxisRotationTransform.h.
Superclass
template<class TScalarType = double> typedef itk::MatrixOffsetTransformBase<TScalarType, 3> anima::AxisRotationTransform< TScalarType >::Superclass
Definition at line 16 of file animaAxisRotationTransform.h.
TranslationType
template<class TScalarType = double> typedef Superclass::TranslationType anima::AxisRotationTransform< TScalarType >::TranslationType
Definition at line 49 of file animaAxisRotationTransform.h.
Constructor & Destructor Documentation
AxisRotationTransform() [1/2]
template<class TScalarType > anima::AxisRotationTransform< TScalarType >::AxisRotationTransform () protected
Definition at line 11 of file animaAxisRotationTransform.hxx.
Referenced by anima::AxisRotationTransform< TScalarType >::~AxisRotationTransform().
AxisRotationTransform() [2/2]
template<class TScalarType > anima::AxisRotationTransform< TScalarType >::AxisRotationTransform (unsigned int outputSpaceDims, unsigned int paramsSpaceDims) protected
Definition at line 24 of file animaAxisRotationTransform.hxx.
References anima::AxisRotationTransform< TScalarType >::SetParameters().
~AxisRotationTransform()
template<class TScalarType = double> virtual anima::AxisRotationTransform< TScalarType >::~AxisRotationTransform () inline protected virtual
Definition at line 65 of file animaAxisRotationTransform.h.
References anima::AxisRotationTransform< TScalarType >::AxisRotationTransform(), anima::AxisRotationTransform< TScalarType >::ComputeMatrix(), and anima::AxisRotationTransform< TScalarType >::PrintSelf().
Member Function Documentation
ComputeMatrix()
template<class TScalarType > void anima::AxisRotationTransform< TScalarType >::ComputeMatrix () protected
Definition at line 81 of file animaAxisRotationTransform.hxx.
References anima::AxisRotationTransform< TScalarType >::SetReferencePlaneNormal().
Referenced by anima::AxisRotationTransform< TScalarType >::SetIdentity(), and anima::AxisRotationTransform< TScalarType >::~AxisRotationTransform().
CreateAnother()
template<class TScalarType = double> virtual::itk::LightObject::Pointer anima::AxisRotationTransform< TScalarType >::CreateAnother (void) const
GetNameOfClass()
template<class TScalarType = double> virtual const char* anima::AxisRotationTransform< TScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetParameters()
template<class TScalarType > const AxisRotationTransform< TScalarType >::ParametersType & anima::AxisRotationTransform< TScalarType >::GetParameters () const
Definition at line 56 of file animaAxisRotationTransform.hxx.
References anima::AxisRotationTransform< TScalarType >::SetIdentity().
Referenced by anima::AxisRotationTransform< TScalarType >::SetParameters().
New()
template<class TScalarType = double> static Pointer anima::AxisRotationTransform< TScalarType >::New () static
New macro for creation of through a Smart Pointer.
PrintSelf()
template<class TScalarType > void anima::AxisRotationTransform< TScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
Definition at line 141 of file animaAxisRotationTransform.hxx.
Referenced by anima::AxisRotationTransform< TScalarType >::SetReferencePlaneNormal(), and anima::AxisRotationTransform< TScalarType >::~AxisRotationTransform().
SetIdentity()
template<class TScalarType > void anima::AxisRotationTransform< TScalarType >::SetIdentity () virtual
Definition at line 69 of file animaAxisRotationTransform.hxx.
References anima::AxisRotationTransform< TScalarType >::ComputeMatrix().
Referenced by anima::AxisRotationTransform< TScalarType >::GetParameters().
SetParameters()
template<class TScalarType > void anima::AxisRotationTransform< TScalarType >::SetParameters (const ParametersType & parameters)
Definition at line 39 of file animaAxisRotationTransform.hxx.
References anima::AxisRotationTransform< TScalarType >::GetParameters().
Referenced by anima::AxisRotationTransform< TScalarType >::AxisRotationTransform().
SetReferencePlaneNormal()
template<class TScalarType > void anima::AxisRotationTransform< TScalarType >::SetReferencePlaneNormal (InputVectorType & refPlaneNormal)
Definition at line 122 of file animaAxisRotationTransform.hxx.
References anima::GetRotationMatrixFromVectors(), and anima::AxisRotationTransform< TScalarType >::PrintSelf().
Referenced by anima::AxisRotationTransform< TScalarType >::ComputeMatrix().
Member Data Documentation
InputSpaceDimension
template<class TScalarType = double> const unsigned int anima::AxisRotationTransform< TScalarType >::InputSpaceDimension = 3 static
Definition at line 28 of file animaAxisRotationTransform.h.
OutputSpaceDimension
template<class TScalarType = double> const unsigned int anima::AxisRotationTransform< TScalarType >::OutputSpaceDimension = 3 static
Definition at line 29 of file animaAxisRotationTransform.h.
ParametersDimension
template<class TScalarType = double> const unsigned int anima::AxisRotationTransform< TScalarType >::ParametersDimension = 3 static
Definition at line 30 of file animaAxisRotationTransform.h.
SpaceDimension
template<class TScalarType = double> const unsigned int anima::AxisRotationTransform< TScalarType >::SpaceDimension = 3 static
Dimension of the space.
Definition at line 27 of file animaAxisRotationTransform.h.
The documentation for this class was generated from the following files:
animaAxisRotationTransform.h
animaAxisRotationTransform.hxx