ANIMA: anima::PyramidalDenseSVFMatchingBridge< ImageDimension > Class Template Reference
anima::PyramidalDenseSVFMatchingBridge< ImageDimension > Class Template Reference
#include <animaPyramidalDenseSVFMatchingBridge.h>
Public Types
typedef AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform< typename BaseAgregatorType::InternalScalarType, ImageDimension > AffineTransformType
enum Agregator {
Baloo = 0,
MSmoother
}
typedef BalooSVFTransformAgregator< ImageDimension > BalooAgregatorType
typedef BaseTransformAgregator< ImageDimension > BaseAgregatorType
typedef BaseBlockMatchRegistrationType::Pointer BaseBlockMatchRegistrationPointer
typedef anima::BaseBMRegistrationMethod< InputImageType > BaseBlockMatchRegistrationType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MEstimateAgregatorType::BaseOutputTransformType BaseTransformType
typedef itk::SmartPointer< const Self > ConstPointer
typedef DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef rpi::DisplacementFieldTransform< typename BaseAgregatorType::ScalarType, ImageDimension > DisplacementFieldTransformType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef itk::Image< float, ImageDimension > InputImageType
typedef InputImageType::IOPixelType InputPixelType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, ImageDimension > MaskImageType
typedef MaskPyramidType::Pointer MaskPyramidPointer
typedef anima::PyramidImageFilter< MaskImageType, MaskImageType > MaskPyramidType
typedef DenseSVFTransformAgregator< ImageDimension > MEstimateAgregatorType
enum Metric {
SquaredCorrelation = 0,
Correlation,
MeanSquares
}
enum Optimizer {
Exhaustive = 0,
Bobyqa
}
typedef itk::SmartPointer< Self > Pointer
typedef PyramidType::Pointer PyramidPointer
typedef anima::PyramidImageFilter< InputImageType, InputImageType > PyramidType
typedef PyramidalDenseSVFMatchingBridge Self
typedef itk::ProcessObject Superclass
enum SymmetryType {
Asymmetric = 0,
Symmetric,
Kissing
}
enum Transform {
Translation = 0,
Rigid,
Affine,
Directional_Affine
}
typedef VelocityFieldType::PixelType VectorType
typedef BaseTransformType::VectorFieldType VelocityFieldType
Public Member Functions
void Abort ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetAffineDirection ()
Agregator GetAgregator ()
double GetAngleUpperBound ()
unsigned int GetBCHCompositionOrder ()
unsigned int GetBlockSize ()
unsigned int GetBlockSpacing ()
double GetElasticSigma ()
unsigned int GetExponentiationOrder ()
double GetExtrapolationSigma ()
double GetFinalRadius ()
unsigned int GetLastPyramidLevel ()
unsigned int GetMaximumIterations ()
double GetMEstimateConvergenceThreshold ()
Metric GetMetric ()
float GetMinimalTransformError ()
virtual const char * GetNameOfClass () const
double GetNeighborhoodApproximation ()
unsigned int GetNumberOfPyramidLevels ()
Optimizer GetOptimizer ()
unsigned int GetOptimizerMaximumIterations ()
double GetOutlierSigma ()
DisplacementFieldTransformPointer GetOutputDisplacementFieldTransform ()
InputImagePointer GetOutputImage ()
BaseTransformPointer GetOutputTransform ()
std::string GetOutputTransformFile ()
double GetPercentageKept ()
std::string GetResultFile ()
double GetScaleUpperBound ()
double GetSearchAngleRadius ()
double GetSearchRadius ()
double GetSearchScaleRadius ()
float GetStDevThreshold ()
double GetStepSize ()
SymmetryType GetSymmetryType ()
Transform GetTransform ()
double GetTranslateUpperBound ()
void SetAffineDirection (unsigned int val)
void SetAgregator (Agregator agregator)
void SetAngleUpperBound (double AngleUpperBound)
void SetBCHCompositionOrder (unsigned int order)
void SetBlockGenerationMask (MaskImageType *mask)
void SetBlockSize (int blockSize)
void SetBlockSpacing (unsigned int blockSpacing)
void SetElasticSigma (double elasticSigma)
void SetExponentiationOrder (unsigned int order)
void SetExtrapolationSigma (double extrapolationSigma)
void SetFinalRadius (double FinalRadius)
void SetFloatingImage (InputImageConstPointer floatingImage)
void SetLastPyramidLevel (unsigned int LastPyramidLevel)
void SetMaximumIterations (unsigned int MaximumIterations)
void SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold)
void SetMetric (Metric metric)
void SetMinimalTransformError (float MinimalTransformError)
void SetNeighborhoodApproximation (double neighborhoodApproximation)
void SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels)
void SetOptimizer (Optimizer optimizer)
void SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations)
void SetOutlierSigma (double outlierSigma)
void SetOutputTransformFile (std::string outputTransformFile)
void SetPercentageKept (double PercentageKept)
void SetProgressCallback (itk::CStyleCommand::Pointer callback)
void SetReferenceImage (InputImageConstPointer referenceImage)
void SetResultFile (std::string resultFile)
void SetScaleUpperBound (double ScaleUpperBound)
void SetSearchAngleRadius (double SearchAngleRadius)
void SetSearchRadius (double SearchRadius)
void SetSearchScaleRadius (double SearchScaleRadius)
void SetStDevThreshold (float StDevThreshold)
void SetStepSize (double StepSize)
void SetSymmetryType (SymmetryType sym)
void SetTransform (Transform transform)
void SetTranslateUpperBound (double TranslateUpperBound)
void SetVerbose (bool value)
void Update () ITK_OVERRIDE
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void EmitProgress (int prog)
PyramidalDenseSVFMatchingBridge ()
void SetupPyramids ()
virtual ~PyramidalDenseSVFMatchingBridge ()
Static Protected Member Functions
static void ManageProgress (itk::Object *caller, const itk::EventObject &event, void *clientData)
Detailed Description
template<unsigned int ImageDimension = 3>
class anima::PyramidalDenseSVFMatchingBridge< ImageDimension >
Definition at line 15 of file animaPyramidalDenseSVFMatchingBridge.h.
Member Typedef Documentation
AffineTransformPointer
template<unsigned int ImageDimension = 3> typedef AffineTransformType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::AffineTransformPointer
Definition at line 38 of file animaPyramidalDenseSVFMatchingBridge.h.
AffineTransformType
template<unsigned int ImageDimension = 3> typedef itk::AffineTransform<typename BaseAgregatorType::InternalScalarType,ImageDimension> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::AffineTransformType
Definition at line 37 of file animaPyramidalDenseSVFMatchingBridge.h.
BalooAgregatorType
template<unsigned int ImageDimension = 3> typedef BalooSVFTransformAgregator< ImageDimension > anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::BalooAgregatorType
Definition at line 30 of file animaPyramidalDenseSVFMatchingBridge.h.
BaseAgregatorType
template<unsigned int ImageDimension = 3> typedef BaseTransformAgregator< ImageDimension > anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::BaseAgregatorType
Definition at line 28 of file animaPyramidalDenseSVFMatchingBridge.h.
BaseBlockMatchRegistrationPointer
template<unsigned int ImageDimension = 3> typedef BaseBlockMatchRegistrationType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationPointer
Definition at line 47 of file animaPyramidalDenseSVFMatchingBridge.h.
BaseBlockMatchRegistrationType
template<unsigned int ImageDimension = 3> typedef anima::BaseBMRegistrationMethod<InputImageType> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationType
Definition at line 46 of file animaPyramidalDenseSVFMatchingBridge.h.
BaseTransformPointer
template<unsigned int ImageDimension = 3> typedef BaseTransformType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::BaseTransformPointer
Definition at line 33 of file animaPyramidalDenseSVFMatchingBridge.h.
BaseTransformType
template<unsigned int ImageDimension = 3> typedef MEstimateAgregatorType::BaseOutputTransformType anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::BaseTransformType
Definition at line 32 of file animaPyramidalDenseSVFMatchingBridge.h.
ConstPointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<const Self> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::ConstPointer
Definition at line 54 of file animaPyramidalDenseSVFMatchingBridge.h.
DisplacementFieldTransformPointer
template<unsigned int ImageDimension = 3> typedef DisplacementFieldTransformType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::DisplacementFieldTransformPointer
Definition at line 41 of file animaPyramidalDenseSVFMatchingBridge.h.
DisplacementFieldTransformType
template<unsigned int ImageDimension = 3> typedef rpi::DisplacementFieldTransform<typename BaseAgregatorType::ScalarType, ImageDimension> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::DisplacementFieldTransformType
Definition at line 40 of file animaPyramidalDenseSVFMatchingBridge.h.
InputImageConstPointer
template<unsigned int ImageDimension = 3> typedef InputImageType::ConstPointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::InputImageConstPointer
Definition at line 21 of file animaPyramidalDenseSVFMatchingBridge.h.
InputImagePointer
template<unsigned int ImageDimension = 3> typedef InputImageType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::InputImagePointer
Definition at line 20 of file animaPyramidalDenseSVFMatchingBridge.h.
InputImageType
template<unsigned int ImageDimension = 3> typedef itk::Image<float,ImageDimension> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::InputImageType
Definition at line 18 of file animaPyramidalDenseSVFMatchingBridge.h.
InputPixelType
template<unsigned int ImageDimension = 3> typedef InputImageType::IOPixelType anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::InputPixelType
Definition at line 19 of file animaPyramidalDenseSVFMatchingBridge.h.
MaskImagePointer
template<unsigned int ImageDimension = 3> typedef MaskImageType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::MaskImagePointer
Definition at line 24 of file animaPyramidalDenseSVFMatchingBridge.h.
MaskImageType
template<unsigned int ImageDimension = 3> typedef itk::Image<unsigned char, ImageDimension> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::MaskImageType
Definition at line 23 of file animaPyramidalDenseSVFMatchingBridge.h.
MaskPyramidPointer
template<unsigned int ImageDimension = 3> typedef MaskPyramidType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::MaskPyramidPointer
Definition at line 26 of file animaPyramidalDenseSVFMatchingBridge.h.
MaskPyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<MaskImageType,MaskImageType> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::MaskPyramidType
Definition at line 25 of file animaPyramidalDenseSVFMatchingBridge.h.
MEstimateAgregatorType
template<unsigned int ImageDimension = 3> typedef DenseSVFTransformAgregator< ImageDimension > anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::MEstimateAgregatorType
Definition at line 29 of file animaPyramidalDenseSVFMatchingBridge.h.
Pointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<Self> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Pointer
Definition at line 53 of file animaPyramidalDenseSVFMatchingBridge.h.
PyramidPointer
template<unsigned int ImageDimension = 3> typedef PyramidType::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::PyramidPointer
Definition at line 44 of file animaPyramidalDenseSVFMatchingBridge.h.
PyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<InputImageType,InputImageType> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::PyramidType
Definition at line 43 of file animaPyramidalDenseSVFMatchingBridge.h.
Self
template<unsigned int ImageDimension = 3> typedef PyramidalDenseSVFMatchingBridge anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Self
SmartPointer typedef support
Definition at line 50 of file animaPyramidalDenseSVFMatchingBridge.h.
Superclass
template<unsigned int ImageDimension = 3> typedef itk::ProcessObject anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Superclass
Definition at line 51 of file animaPyramidalDenseSVFMatchingBridge.h.
VectorType
template<unsigned int ImageDimension = 3> typedef VelocityFieldType::PixelType anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::VectorType
Definition at line 35 of file animaPyramidalDenseSVFMatchingBridge.h.
VelocityFieldType
template<unsigned int ImageDimension = 3> typedef BaseTransformType::VectorFieldType anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::VelocityFieldType
Definition at line 34 of file animaPyramidalDenseSVFMatchingBridge.h.
Member Enumeration Documentation
Agregator
template<unsigned int ImageDimension = 3> enum anima::PyramidalDenseSVFMatchingBridge::Agregator
Enumerator
Baloo
MSmoother
Definition at line 87 of file animaPyramidalDenseSVFMatchingBridge.h.
Metric
template<unsigned int ImageDimension = 3> enum anima::PyramidalDenseSVFMatchingBridge::Metric
Enumerator
SquaredCorrelation
Correlation
MeanSquares
Definition at line 74 of file animaPyramidalDenseSVFMatchingBridge.h.
Optimizer
template<unsigned int ImageDimension = 3> enum anima::PyramidalDenseSVFMatchingBridge::Optimizer
Enumerator
Exhaustive
Bobyqa
Definition at line 81 of file animaPyramidalDenseSVFMatchingBridge.h.
SymmetryType
template<unsigned int ImageDimension = 3> enum anima::PyramidalDenseSVFMatchingBridge::SymmetryType
Enumerator
Asymmetric
Symmetric
Kissing
Definition at line 59 of file animaPyramidalDenseSVFMatchingBridge.h.
Transform
template<unsigned int ImageDimension = 3> enum anima::PyramidalDenseSVFMatchingBridge::Transform
Enumerator
Translation
Rigid
Affine
Directional_Affine
Definition at line 66 of file animaPyramidalDenseSVFMatchingBridge.h.
Constructor & Destructor Documentation
PyramidalDenseSVFMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::PyramidalDenseSVFMatchingBridge () protected
Definition at line 20 of file animaPyramidalDenseSVFMatchingBridge.hxx.
References Asymmetric, Baloo, Bobyqa, SquaredCorrelation, and Translation.
Referenced by anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetVerbose().
~PyramidalDenseSVFMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::~PyramidalDenseSVFMatchingBridge () protected virtual
Definition at line 75 of file animaPyramidalDenseSVFMatchingBridge.hxx.
Referenced by anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetVerbose().
Member Function Documentation
Abort()
template<unsigned int ImageDimension> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Abort ()
Definition at line 81 of file animaPyramidalDenseSVFMatchingBridge.hxx.
CreateAnother()
template<unsigned int ImageDimension = 3> virtual::itk::LightObject::Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::CreateAnother (void) const
EmitProgress()
template<unsigned int ImageDimension> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::EmitProgress (int prog) protected
Definition at line 476 of file animaPyramidalDenseSVFMatchingBridge.hxx.
Referenced by anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::ManageProgress(), and anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetVerbose().
GetAffineDirection()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetAffineDirection () inline
Definition at line 144 of file animaPyramidalDenseSVFMatchingBridge.h.
GetAgregator()
template<unsigned int ImageDimension = 3> Agregator anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetAgregator () inline
Definition at line 186 of file animaPyramidalDenseSVFMatchingBridge.h.
GetAngleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetAngleUpperBound () inline
Definition at line 180 of file animaPyramidalDenseSVFMatchingBridge.h.
GetBCHCompositionOrder()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetBCHCompositionOrder () inline
Definition at line 204 of file animaPyramidalDenseSVFMatchingBridge.h.
GetBlockSize()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetBlockSize () inline
Definition at line 129 of file animaPyramidalDenseSVFMatchingBridge.h.
GetBlockSpacing()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetBlockSpacing () inline
Definition at line 132 of file animaPyramidalDenseSVFMatchingBridge.h.
GetElasticSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetElasticSigma () inline
Definition at line 192 of file animaPyramidalDenseSVFMatchingBridge.h.
GetExponentiationOrder()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetExponentiationOrder () inline
Definition at line 207 of file animaPyramidalDenseSVFMatchingBridge.h.
GetExtrapolationSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetExtrapolationSigma () inline
Definition at line 189 of file animaPyramidalDenseSVFMatchingBridge.h.
GetFinalRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetFinalRadius () inline
Definition at line 171 of file animaPyramidalDenseSVFMatchingBridge.h.
GetLastPyramidLevel()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetLastPyramidLevel () inline
Definition at line 213 of file animaPyramidalDenseSVFMatchingBridge.h.
GetMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetMaximumIterations () inline
Definition at line 153 of file animaPyramidalDenseSVFMatchingBridge.h.
GetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetMEstimateConvergenceThreshold () inline
Definition at line 198 of file animaPyramidalDenseSVFMatchingBridge.h.
GetMetric()
template<unsigned int ImageDimension = 3> Metric anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetMetric () inline
Definition at line 147 of file animaPyramidalDenseSVFMatchingBridge.h.
GetMinimalTransformError()
template<unsigned int ImageDimension = 3> float anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetMinimalTransformError () inline
Definition at line 156 of file animaPyramidalDenseSVFMatchingBridge.h.
GetNameOfClass()
template<unsigned int ImageDimension = 3> virtual const char* anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetNameOfClass () const virtual
GetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetNeighborhoodApproximation () inline
Definition at line 201 of file animaPyramidalDenseSVFMatchingBridge.h.
GetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetNumberOfPyramidLevels () inline
Definition at line 210 of file animaPyramidalDenseSVFMatchingBridge.h.
GetOptimizer()
template<unsigned int ImageDimension = 3> Optimizer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOptimizer () inline
Definition at line 150 of file animaPyramidalDenseSVFMatchingBridge.h.
GetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOptimizerMaximumIterations () inline
Definition at line 159 of file animaPyramidalDenseSVFMatchingBridge.h.
GetOutlierSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutlierSigma () inline
Definition at line 195 of file animaPyramidalDenseSVFMatchingBridge.h.
GetOutputDisplacementFieldTransform()
template<unsigned int ImageDimension> PyramidalDenseSVFMatchingBridge< ImageDimension >::DisplacementFieldTransformPointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputDisplacementFieldTransform ()
Getter for transform as displacement field
Definition at line 465 of file animaPyramidalDenseSVFMatchingBridge.hxx.
References anima::GetSVFExponential().
Referenced by anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputTransform().
GetOutputImage()
template<unsigned int ImageDimension = 3> InputImagePointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputImage () inline
Definition at line 105 of file animaPyramidalDenseSVFMatchingBridge.h.
GetOutputTransform()
template<unsigned int ImageDimension = 3> BaseTransformPointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputTransform () inline
Getter for transform
Definition at line 110 of file animaPyramidalDenseSVFMatchingBridge.h.
References anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputDisplacementFieldTransform().
GetOutputTransformFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetOutputTransformFile () inline
Definition at line 126 of file animaPyramidalDenseSVFMatchingBridge.h.
GetPercentageKept()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetPercentageKept () inline
Definition at line 216 of file animaPyramidalDenseSVFMatchingBridge.h.
GetResultFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetResultFile () inline
Setter/Getter for parameters
Definition at line 123 of file animaPyramidalDenseSVFMatchingBridge.h.
GetScaleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetScaleUpperBound () inline
Definition at line 183 of file animaPyramidalDenseSVFMatchingBridge.h.
GetSearchAngleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetSearchAngleRadius () inline
Definition at line 165 of file animaPyramidalDenseSVFMatchingBridge.h.
GetSearchRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetSearchRadius () inline
Definition at line 162 of file animaPyramidalDenseSVFMatchingBridge.h.
GetSearchScaleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetSearchScaleRadius () inline
Definition at line 168 of file animaPyramidalDenseSVFMatchingBridge.h.
GetStDevThreshold()
template<unsigned int ImageDimension = 3> float anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetStDevThreshold () inline
Definition at line 135 of file animaPyramidalDenseSVFMatchingBridge.h.
GetStepSize()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetStepSize () inline
Definition at line 174 of file animaPyramidalDenseSVFMatchingBridge.h.
GetSymmetryType()
template<unsigned int ImageDimension = 3> SymmetryType anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetSymmetryType () inline
Definition at line 138 of file animaPyramidalDenseSVFMatchingBridge.h.
GetTransform()
template<unsigned int ImageDimension = 3> Transform anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetTransform () inline
Definition at line 141 of file animaPyramidalDenseSVFMatchingBridge.h.
GetTranslateUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::GetTranslateUpperBound () inline
Definition at line 177 of file animaPyramidalDenseSVFMatchingBridge.h.
ManageProgress()
template<unsigned int ImageDimension> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::ManageProgress (itk::Object * caller, const itk::EventObject & event, void * clientData) static protected
Definition at line 483 of file animaPyramidalDenseSVFMatchingBridge.hxx.
References anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::EmitProgress().
Referenced by anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetVerbose().
New()
template<unsigned int ImageDimension = 3> static Pointer anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::New () static
SetAffineDirection()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetAffineDirection (unsigned int val) inline
Definition at line 145 of file animaPyramidalDenseSVFMatchingBridge.h.
SetAgregator()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetAgregator (Agregator agregator) inline
Definition at line 187 of file animaPyramidalDenseSVFMatchingBridge.h.
SetAngleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetAngleUpperBound (double AngleUpperBound) inline
Definition at line 181 of file animaPyramidalDenseSVFMatchingBridge.h.
SetBCHCompositionOrder()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetBCHCompositionOrder (unsigned int order) inline
Definition at line 205 of file animaPyramidalDenseSVFMatchingBridge.h.
SetBlockGenerationMask()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetBlockGenerationMask (MaskImageType * mask) inline
Definition at line 219 of file animaPyramidalDenseSVFMatchingBridge.h.
SetBlockSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetBlockSize (int blockSize) inline
Definition at line 130 of file animaPyramidalDenseSVFMatchingBridge.h.
SetBlockSpacing()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetBlockSpacing (unsigned int blockSpacing) inline
Definition at line 133 of file animaPyramidalDenseSVFMatchingBridge.h.
SetElasticSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetElasticSigma (double elasticSigma) inline
Definition at line 193 of file animaPyramidalDenseSVFMatchingBridge.h.
SetExponentiationOrder()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetExponentiationOrder (unsigned int order) inline
Definition at line 208 of file animaPyramidalDenseSVFMatchingBridge.h.
SetExtrapolationSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetExtrapolationSigma (double extrapolationSigma) inline
Definition at line 190 of file animaPyramidalDenseSVFMatchingBridge.h.
SetFinalRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetFinalRadius (double FinalRadius) inline
Definition at line 172 of file animaPyramidalDenseSVFMatchingBridge.h.
SetFloatingImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetFloatingImage (InputImageConstPointer floatingImage) inline
Definition at line 103 of file animaPyramidalDenseSVFMatchingBridge.h.
SetLastPyramidLevel()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetLastPyramidLevel (unsigned int LastPyramidLevel) inline
Definition at line 214 of file animaPyramidalDenseSVFMatchingBridge.h.
SetMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetMaximumIterations (unsigned int MaximumIterations) inline
Definition at line 154 of file animaPyramidalDenseSVFMatchingBridge.h.
SetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold) inline
Definition at line 199 of file animaPyramidalDenseSVFMatchingBridge.h.
SetMetric()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetMetric (Metric metric) inline
Definition at line 148 of file animaPyramidalDenseSVFMatchingBridge.h.
SetMinimalTransformError()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetMinimalTransformError (float MinimalTransformError) inline
Definition at line 157 of file animaPyramidalDenseSVFMatchingBridge.h.
SetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetNeighborhoodApproximation (double neighborhoodApproximation) inline
Definition at line 202 of file animaPyramidalDenseSVFMatchingBridge.h.
SetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels) inline
Definition at line 211 of file animaPyramidalDenseSVFMatchingBridge.h.
SetOptimizer()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetOptimizer (Optimizer optimizer) inline
Definition at line 151 of file animaPyramidalDenseSVFMatchingBridge.h.
SetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations) inline
Definition at line 160 of file animaPyramidalDenseSVFMatchingBridge.h.
SetOutlierSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetOutlierSigma (double outlierSigma) inline
Definition at line 196 of file animaPyramidalDenseSVFMatchingBridge.h.
SetOutputTransformFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetOutputTransformFile (std::string outputTransformFile) inline
Definition at line 127 of file animaPyramidalDenseSVFMatchingBridge.h.
SetPercentageKept()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetPercentageKept (double PercentageKept) inline
Definition at line 217 of file animaPyramidalDenseSVFMatchingBridge.h.
SetProgressCallback()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetProgressCallback (itk::CStyleCommand::Pointer callback) inline
Definition at line 117 of file animaPyramidalDenseSVFMatchingBridge.h.
SetReferenceImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetReferenceImage (InputImageConstPointer referenceImage) inline
Setter for images
Definition at line 102 of file animaPyramidalDenseSVFMatchingBridge.h.
SetResultFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetResultFile (std::string resultFile) inline
Definition at line 124 of file animaPyramidalDenseSVFMatchingBridge.h.
SetScaleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetScaleUpperBound (double ScaleUpperBound) inline
Definition at line 184 of file animaPyramidalDenseSVFMatchingBridge.h.
SetSearchAngleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetSearchAngleRadius (double SearchAngleRadius) inline
Definition at line 166 of file animaPyramidalDenseSVFMatchingBridge.h.
SetSearchRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetSearchRadius (double SearchRadius) inline
Definition at line 163 of file animaPyramidalDenseSVFMatchingBridge.h.
SetSearchScaleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetSearchScaleRadius (double SearchScaleRadius) inline
Definition at line 169 of file animaPyramidalDenseSVFMatchingBridge.h.
SetStDevThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetStDevThreshold (float StDevThreshold) inline
Definition at line 136 of file animaPyramidalDenseSVFMatchingBridge.h.
SetStepSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetStepSize (double StepSize) inline
Definition at line 175 of file animaPyramidalDenseSVFMatchingBridge.h.
SetSymmetryType()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetSymmetryType (SymmetryType sym) inline
Definition at line 139 of file animaPyramidalDenseSVFMatchingBridge.h.
SetTransform()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetTransform (Transform transform) inline
Definition at line 142 of file animaPyramidalDenseSVFMatchingBridge.h.
SetTranslateUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetTranslateUpperBound (double TranslateUpperBound) inline
Definition at line 178 of file animaPyramidalDenseSVFMatchingBridge.h.
SetupPyramids()
template<unsigned int ImageDimension> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetupPyramids () protected
Definition at line 509 of file animaPyramidalDenseSVFMatchingBridge.hxx.
Referenced by anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetVerbose().
SetVerbose()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetVerbose (bool value) inline
Definition at line 221 of file animaPyramidalDenseSVFMatchingBridge.h.
References anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::EmitProgress(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::ManageProgress(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::PyramidalDenseSVFMatchingBridge(), anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::SetupPyramids(), and anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::~PyramidalDenseSVFMatchingBridge().
Update()
template<unsigned int ImageDimension> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::Update ()
Definition at line 91 of file animaPyramidalDenseSVFMatchingBridge.hxx.
References Affine, Asymmetric, Bobyqa, Correlation, Exhaustive, anima::GetSVFExponential(), Kissing, MeanSquares, MSmoother, Rigid, anima::BaseBlockMatcher< TInputImageType >::SetBlockPercentageKept(), anima::DenseSVFTransformAgregator< NDimensions >::SetDistanceBoundary(), anima::BalooSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::DenseSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::DenseSVFTransformAgregator< NDimensions >::SetMEstimateConvergenceThreshold(), anima::DenseSVFTransformAgregator< NDimensions >::SetNeighborhoodHalfSize(), anima::DenseSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::BalooSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::DenseSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), anima::BalooSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), anima::BaseTransformAgregator< NDimensions >::SetOutputTransformType(), anima::BaseTransformAgregator< NDimensions >::SetVerboseAgregation(), SquaredCorrelation, Symmetric, and Translation.
WriteOutputs()
template<unsigned int ImageDimension> void anima::PyramidalDenseSVFMatchingBridge< ImageDimension >::WriteOutputs ()
Definition at line 494 of file animaPyramidalDenseSVFMatchingBridge.hxx.
The documentation for this class was generated from the following files:
animaPyramidalDenseSVFMatchingBridge.h
animaPyramidalDenseSVFMatchingBridge.hxx