ANIMA: anima::ExpTensorImageFilter< TScalarType, NDimensions > Class Template Reference
anima::ExpTensorImageFilter< TScalarType, NDimensions > Class Template Reference
#include <animaExpTensorImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef TInputImage::Pointer InputImagePointer
typedef TInputImage::IndexType InputIndexType
typedef TInputImage::PixelType InputPixelType
typedef TInputImage::PointType InputPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage::PixelType OutputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef ExpTensorImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::VectorImage< TScalarType, NDimensions > TInputImage
typedef itk::VectorImage< TScalarType, NDimensions > TOutputImage
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetScaleNonDiagonal (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
ExpTensorImageFilter ()
void GenerateOutputInformation () ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~ExpTensorImageFilter ()
Detailed Description
template<class TScalarType, unsigned int NDimensions = 3>
class anima::ExpTensorImageFilter< TScalarType, NDimensions >
Definition at line 11 of file animaExpTensorImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TScalarType , unsigned int NDimensions = 3> typedef itk::SmartPointer<const Self> anima::ExpTensorImageFilter< TScalarType, NDimensions >::ConstPointer
Definition at line 22 of file animaExpTensorImageFilter.h.
InputImagePointer
template<class TScalarType , unsigned int NDimensions = 3> typedef TInputImage::Pointer anima::ExpTensorImageFilter< TScalarType, NDimensions >::InputImagePointer
Image typedef support
Definition at line 36 of file animaExpTensorImageFilter.h.
InputIndexType
template<class TScalarType , unsigned int NDimensions = 3> typedef TInputImage::IndexType anima::ExpTensorImageFilter< TScalarType, NDimensions >::InputIndexType
Definition at line 32 of file animaExpTensorImageFilter.h.
InputPixelType
template<class TScalarType , unsigned int NDimensions = 3> typedef TInputImage::PixelType anima::ExpTensorImageFilter< TScalarType, NDimensions >::InputPixelType
Definition at line 31 of file animaExpTensorImageFilter.h.
InputPointType
template<class TScalarType , unsigned int NDimensions = 3> typedef TInputImage::PointType anima::ExpTensorImageFilter< TScalarType, NDimensions >::InputPointType
Definition at line 33 of file animaExpTensorImageFilter.h.
OutputImagePointer
template<class TScalarType , unsigned int NDimensions = 3> typedef TOutputImage::Pointer anima::ExpTensorImageFilter< TScalarType, NDimensions >::OutputImagePointer
Definition at line 37 of file animaExpTensorImageFilter.h.
OutputImageRegionType
template<class TScalarType , unsigned int NDimensions = 3> typedef Superclass::OutputImageRegionType anima::ExpTensorImageFilter< TScalarType, NDimensions >::OutputImageRegionType
Superclass typedefs.
Definition at line 40 of file animaExpTensorImageFilter.h.
OutputPixelType
template<class TScalarType , unsigned int NDimensions = 3> typedef TOutputImage::PixelType anima::ExpTensorImageFilter< TScalarType, NDimensions >::OutputPixelType
Definition at line 30 of file animaExpTensorImageFilter.h.
Pointer
template<class TScalarType , unsigned int NDimensions = 3> typedef itk::SmartPointer<Self> anima::ExpTensorImageFilter< TScalarType, NDimensions >::Pointer
Definition at line 21 of file animaExpTensorImageFilter.h.
Self
template<class TScalarType , unsigned int NDimensions = 3> typedef ExpTensorImageFilter anima::ExpTensorImageFilter< TScalarType, NDimensions >::Self
Standard class typedefs.
Definition at line 16 of file animaExpTensorImageFilter.h.
Superclass
template<class TScalarType , unsigned int NDimensions = 3> typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::ExpTensorImageFilter< TScalarType, NDimensions >::Superclass
Definition at line 20 of file animaExpTensorImageFilter.h.
TInputImage
template<class TScalarType , unsigned int NDimensions = 3> typedef itk::VectorImage<TScalarType, NDimensions> anima::ExpTensorImageFilter< TScalarType, NDimensions >::TInputImage
Definition at line 17 of file animaExpTensorImageFilter.h.
TOutputImage
template<class TScalarType , unsigned int NDimensions = 3> typedef itk::VectorImage<TScalarType, NDimensions> anima::ExpTensorImageFilter< TScalarType, NDimensions >::TOutputImage
Definition at line 18 of file animaExpTensorImageFilter.h.
Constructor & Destructor Documentation
ExpTensorImageFilter()
template<class TScalarType , unsigned int NDimensions = 3> anima::ExpTensorImageFilter< TScalarType, NDimensions >::ExpTensorImageFilter () inline protected
Definition at line 45 of file animaExpTensorImageFilter.h.
~ExpTensorImageFilter()
template<class TScalarType , unsigned int NDimensions = 3> virtual anima::ExpTensorImageFilter< TScalarType, NDimensions >::~ExpTensorImageFilter () inline protected virtual
Definition at line 53 of file animaExpTensorImageFilter.h.
References anima::ExpTensorImageFilter< TScalarType, NDimensions >::BeforeThreadedGenerateData(), anima::ExpTensorImageFilter< TScalarType, NDimensions >::GenerateOutputInformation(), and anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class TScalarType , unsigned int NDimensions> void anima::ExpTensorImageFilter< TScalarType, NDimensions >::BeforeThreadedGenerateData () protected
Definition at line 28 of file animaExpTensorImageFilter.hxx.
References anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData().
Referenced by anima::ExpTensorImageFilter< TScalarType, NDimensions >::GenerateOutputInformation(), and anima::ExpTensorImageFilter< TScalarType, NDimensions >::~ExpTensorImageFilter().
CreateAnother()
template<class TScalarType , unsigned int NDimensions = 3> virtual::itk::LightObject::Pointer anima::ExpTensorImageFilter< TScalarType, NDimensions >::CreateAnother (void) const
GenerateOutputInformation()
template<class TScalarType , unsigned int NDimensions> void anima::ExpTensorImageFilter< TScalarType, NDimensions >::GenerateOutputInformation () protected
Definition at line 13 of file animaExpTensorImageFilter.hxx.
References anima::ExpTensorImageFilter< TScalarType, NDimensions >::BeforeThreadedGenerateData().
Referenced by anima::ExpTensorImageFilter< TScalarType, NDimensions >::~ExpTensorImageFilter().
GetNameOfClass()
template<class TScalarType , unsigned int NDimensions = 3> virtual const char* anima::ExpTensorImageFilter< TScalarType, NDimensions >::GetNameOfClass () const virtual
Run-time type information (and related methods)
New()
template<class TScalarType , unsigned int NDimensions = 3> static Pointer anima::ExpTensorImageFilter< TScalarType, NDimensions >::New () static
Method for creation through the object factory.
SetScaleNonDiagonal()
template<class TScalarType , unsigned int NDimensions = 3> virtual void anima::ExpTensorImageFilter< TScalarType, NDimensions >::SetScaleNonDiagonal (bool _arg) virtual
ThreadedGenerateData()
template<class TScalarType , unsigned int NDimensions> void anima::ExpTensorImageFilter< TScalarType, NDimensions >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 44 of file animaExpTensorImageFilter.hxx.
References anima::GetTensorExponential(), anima::GetTensorFromVectorRepresentation(), and anima::GetVectorRepresentation().
Referenced by anima::ExpTensorImageFilter< TScalarType, NDimensions >::BeforeThreadedGenerateData(), and anima::ExpTensorImageFilter< TScalarType, NDimensions >::~ExpTensorImageFilter().
The documentation for this class was generated from the following files:
animaExpTensorImageFilter.h
animaExpTensorImageFilter.hxx