ANIMA: anima::VoxelExhaustiveOptimizer Class Reference
anima::VoxelExhaustiveOptimizer Class Reference
#include <animaVoxelExhaustiveOptimizer.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef vnl_matrix< double > GeometryType
typedef itk::SmartPointer< Self > Pointer
typedef VoxelExhaustiveOptimizer Self
typedef itk::Array< unsigned long > StepsType
typedef itk::SingleValuedNonLinearOptimizer Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
const MeasureType & GetCurrentCost () const
virtual const ParametersType & GetCurrentIndex () const
virtual const MeasureType & GetCurrentValue () const
virtual const bool & GetMaximize () const
virtual const MeasureType & GetMaximumMetricValue () const
virtual const ParametersType & GetMaximumMetricValuePosition () const
virtual const unsigned long & GetMaximumNumberOfIterations () const
virtual const MeasureType & GetMinimumMetricValue () const
virtual const ParametersType & GetMinimumMetricValuePosition () const
virtual const char * GetNameOfClass () const
virtual const StepsType & GetNumberOfSteps () const
const std::string GetStopConditionDescription () const ITK_OVERRIDE
virtual void MaximizeOff ()
virtual void MaximizeOn ()
void ResumeWalking (void)
virtual void SetGeometry (GeometryType _arg)
virtual void SetMaximize (bool _arg)
virtual void SetNumberOfSteps (StepsType _arg)
virtual void StartOptimization () ITK_OVERRIDE
void StartWalking (void)
void StopWalking (void)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void IncrementIndex (ParametersType &newPosition)
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
VoxelExhaustiveOptimizer ()
virtual ~VoxelExhaustiveOptimizer ()
Protected Attributes
ParametersType m_CurrentIndex
unsigned long m_CurrentIteration
unsigned int m_CurrentParameter
MeasureType m_CurrentValue
GeometryType m_Geometry
MeasureType m_MaximumMetricValue
ParametersType m_MaximumMetricValuePosition
unsigned long m_MaximumNumberOfIterations
MeasureType m_MinimumMetricValue
ParametersType m_MinimumMetricValuePosition
StepsType m_NumberOfSteps
bool m_Stop
Detailed Description
Definition at line 10 of file animaVoxelExhaustiveOptimizer.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::VoxelExhaustiveOptimizer::ConstPointer
Definition at line 18 of file animaVoxelExhaustiveOptimizer.h.
GeometryType
typedef vnl_matrix<double> anima::VoxelExhaustiveOptimizer::GeometryType
Definition at line 19 of file animaVoxelExhaustiveOptimizer.h.
Pointer
typedef itk::SmartPointer<Self> anima::VoxelExhaustiveOptimizer::Pointer
Definition at line 17 of file animaVoxelExhaustiveOptimizer.h.
Self
typedef VoxelExhaustiveOptimizer anima::VoxelExhaustiveOptimizer::Self
Standard "Self" typedef.
Definition at line 15 of file animaVoxelExhaustiveOptimizer.h.
StepsType
typedef itk::Array< unsigned long > anima::VoxelExhaustiveOptimizer::StepsType
Definition at line 21 of file animaVoxelExhaustiveOptimizer.h.
Superclass
typedef itk::SingleValuedNonLinearOptimizer anima::VoxelExhaustiveOptimizer::Superclass
Definition at line 16 of file animaVoxelExhaustiveOptimizer.h.
Constructor & Destructor Documentation
VoxelExhaustiveOptimizer()
anima::VoxelExhaustiveOptimizer::VoxelExhaustiveOptimizer () protected
Constructor
Definition at line 12 of file animaVoxelExhaustiveOptimizer.cxx.
References GetCurrentCost().
~VoxelExhaustiveOptimizer()
virtual anima::VoxelExhaustiveOptimizer::~VoxelExhaustiveOptimizer () inline protected virtual
Definition at line 62 of file animaVoxelExhaustiveOptimizer.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::VoxelExhaustiveOptimizer::CreateAnother (void) const
GetCurrentCost()
const VoxelExhaustiveOptimizer::MeasureType & anima::VoxelExhaustiveOptimizer::GetCurrentCost () const
Return Current Value
Definition at line 29 of file animaVoxelExhaustiveOptimizer.cxx.
Referenced by VoxelExhaustiveOptimizer().
GetCurrentIndex()
virtual const ParametersType& anima::VoxelExhaustiveOptimizer::GetCurrentIndex () const virtual
Referenced by ResumeWalking().
GetCurrentValue()
virtual const MeasureType& anima::VoxelExhaustiveOptimizer::GetCurrentValue () const virtual
Referenced by ResumeWalking().
GetMaximize()
virtual const bool& anima::VoxelExhaustiveOptimizer::GetMaximize () const virtual
GetMaximumMetricValue()
virtual const MeasureType& anima::VoxelExhaustiveOptimizer::GetMaximumMetricValue () const virtual
Referenced by StartOptimization().
GetMaximumMetricValuePosition()
virtual const ParametersType& anima::VoxelExhaustiveOptimizer::GetMaximumMetricValuePosition () const virtual
Referenced by StartOptimization().
GetMaximumNumberOfIterations()
virtual const unsigned long& anima::VoxelExhaustiveOptimizer::GetMaximumNumberOfIterations () const virtual
GetMinimumMetricValue()
virtual const MeasureType& anima::VoxelExhaustiveOptimizer::GetMinimumMetricValue () const virtual
Referenced by StartOptimization().
GetMinimumMetricValuePosition()
virtual const ParametersType& anima::VoxelExhaustiveOptimizer::GetMinimumMetricValuePosition () const virtual
Referenced by StartOptimization().
GetNameOfClass()
virtual const char* anima::VoxelExhaustiveOptimizer::GetNameOfClass () const virtual
Run-time type information (and related methods).
Referenced by IncrementIndex(), ResumeWalking(), and StartWalking().
GetNumberOfSteps()
virtual const StepsType& anima::VoxelExhaustiveOptimizer::GetNumberOfSteps () const virtual
GetStopConditionDescription()
const std::string anima::VoxelExhaustiveOptimizer::GetStopConditionDescription () const
Get the reason for termination
Definition at line 221 of file animaVoxelExhaustiveOptimizer.cxx.
References PrintSelf().
Referenced by IncrementIndex().
IncrementIndex()
void anima::VoxelExhaustiveOptimizer::IncrementIndex (ParametersType & newPosition) protected
Advance to the next grid position.
Definition at line 186 of file animaVoxelExhaustiveOptimizer.cxx.
References GetNameOfClass(), GetStopConditionDescription(), m_CurrentIndex, m_NumberOfSteps, and m_Stop.
Referenced by ResumeWalking(), and StopWalking().
MaximizeOff()
virtual void anima::VoxelExhaustiveOptimizer::MaximizeOff () virtual
MaximizeOn()
virtual void anima::VoxelExhaustiveOptimizer::MaximizeOn () virtual
New()
static Pointer anima::VoxelExhaustiveOptimizer::New () static
Method for creation through the object factory.
PrintSelf()
void anima::VoxelExhaustiveOptimizer::PrintSelf (std::ostream & os, itk::Indent indent) const protected
Definition at line 228 of file animaVoxelExhaustiveOptimizer.cxx.
References m_CurrentIndex, m_CurrentIteration, m_CurrentParameter, m_CurrentValue, m_Geometry, m_MaximumMetricValue, m_MaximumMetricValuePosition, m_MaximumNumberOfIterations, m_MinimumMetricValue, m_MinimumMetricValuePosition, m_NumberOfSteps, and m_Stop.
Referenced by GetStopConditionDescription().
ResumeWalking()
void anima::VoxelExhaustiveOptimizer::ResumeWalking (void)
Resume the optimization
Definition at line 122 of file animaVoxelExhaustiveOptimizer.cxx.
References GetCurrentIndex(), GetCurrentValue(), GetNameOfClass(), IncrementIndex(), m_CurrentIteration, m_CurrentValue, m_Geometry, m_MaximumMetricValue, m_MaximumMetricValuePosition, m_MinimumMetricValue, m_MinimumMetricValuePosition, m_Stop, and StopWalking().
Referenced by StartWalking().
SetGeometry()
virtual void anima::VoxelExhaustiveOptimizer::SetGeometry (GeometryType _arg) virtual
SetMaximize()
virtual void anima::VoxelExhaustiveOptimizer::SetMaximize (bool _arg) virtual
Set if the Optimizer should Maximize the metric
SetNumberOfSteps()
virtual void anima::VoxelExhaustiveOptimizer::SetNumberOfSteps (StepsType _arg) virtual
StartOptimization()
void anima::VoxelExhaustiveOptimizer::StartOptimization () virtual
Start walking
Definition at line 41 of file animaVoxelExhaustiveOptimizer.cxx.
References GetMaximumMetricValue(), GetMaximumMetricValuePosition(), GetMinimumMetricValue(), GetMinimumMetricValuePosition(), m_CurrentValue, and StartWalking().
StartWalking()
void anima::VoxelExhaustiveOptimizer::StartWalking (void)
Definition at line 60 of file animaVoxelExhaustiveOptimizer.cxx.
References GetNameOfClass(), m_CurrentIndex, m_CurrentIteration, m_Geometry, m_MaximumMetricValue, m_MaximumMetricValuePosition, m_MaximumNumberOfIterations, m_MinimumMetricValue, m_MinimumMetricValuePosition, m_NumberOfSteps, and ResumeWalking().
Referenced by StartOptimization().
StopWalking()
void anima::VoxelExhaustiveOptimizer::StopWalking (void)
Definition at line 177 of file animaVoxelExhaustiveOptimizer.cxx.
References IncrementIndex(), and m_Stop.
Referenced by ResumeWalking().
Member Data Documentation
m_CurrentIndex
ParametersType anima::VoxelExhaustiveOptimizer::m_CurrentIndex protected
Definition at line 75 of file animaVoxelExhaustiveOptimizer.h.
Referenced by IncrementIndex(), PrintSelf(), and StartWalking().
m_CurrentIteration
unsigned long anima::VoxelExhaustiveOptimizer::m_CurrentIteration protected
Definition at line 72 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), ResumeWalking(), and StartWalking().
m_CurrentParameter
unsigned int anima::VoxelExhaustiveOptimizer::m_CurrentParameter protected
Definition at line 74 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf().
m_CurrentValue
MeasureType anima::VoxelExhaustiveOptimizer::m_CurrentValue protected
Definition at line 70 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), ResumeWalking(), and StartOptimization().
m_Geometry
GeometryType anima::VoxelExhaustiveOptimizer::m_Geometry protected
Definition at line 82 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), ResumeWalking(), and StartWalking().
m_MaximumMetricValue
MeasureType anima::VoxelExhaustiveOptimizer::m_MaximumMetricValue protected
Definition at line 77 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), ResumeWalking(), and StartWalking().
m_MaximumMetricValuePosition
ParametersType anima::VoxelExhaustiveOptimizer::m_MaximumMetricValuePosition protected
Definition at line 80 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), ResumeWalking(), and StartWalking().
m_MaximumNumberOfIterations
unsigned long anima::VoxelExhaustiveOptimizer::m_MaximumNumberOfIterations protected
Definition at line 76 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), and StartWalking().
m_MinimumMetricValue
MeasureType anima::VoxelExhaustiveOptimizer::m_MinimumMetricValue protected
Definition at line 78 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), ResumeWalking(), and StartWalking().
m_MinimumMetricValuePosition
ParametersType anima::VoxelExhaustiveOptimizer::m_MinimumMetricValuePosition protected
Definition at line 79 of file animaVoxelExhaustiveOptimizer.h.
Referenced by PrintSelf(), ResumeWalking(), and StartWalking().
m_NumberOfSteps
StepsType anima::VoxelExhaustiveOptimizer::m_NumberOfSteps protected
Definition at line 71 of file animaVoxelExhaustiveOptimizer.h.
Referenced by IncrementIndex(), PrintSelf(), and StartWalking().
m_Stop
bool anima::VoxelExhaustiveOptimizer::m_Stop protected
Definition at line 73 of file animaVoxelExhaustiveOptimizer.h.
Referenced by IncrementIndex(), PrintSelf(), ResumeWalking(), and StopWalking().
The documentation for this class was generated from the following files:
animaVoxelExhaustiveOptimizer.h
animaVoxelExhaustiveOptimizer.cxx