ANIMA: anima::ODFSphericalHarmonicBasis Class Reference
anima::ODFSphericalHarmonicBasis Class Reference
#include <animaODFSphericalHarmonicBasis.h>
Public Member Functions
template<class T >
double getCurvatureAtPosition (const T &coefficients, double theta, double phi)
double getNthSHValueAtPosition (int k, int m, double theta, double phi)
template<class T >
double getPhiFirstDerivativeValueAtPosition (const T &coefficients, double theta, double phi)
template<class T >
double getPhiSecondDerivativeValueAtPosition (const T &coefficients, double theta, double phi)
template<class T >
itk::VariableLengthVector< T > GetSampleValues (itk::VariableLengthVector< T > &data, std::vector< std::vector< double > > &m_SampleDirections)
template<class T >
double getThetaFirstDerivativeValueAtPosition (const T &coefficients, double theta, double phi)
template<class T >
double getThetaPhiDerivativeValueAtPosition (const T &coefficients, double theta, double phi)
template<class T >
double getThetaSecondDerivativeValueAtPosition (const T &coefficients, double theta, double phi)
template<class T >
double getValueAtPosition (const T &coefficients, double theta, double phi)
ODFSphericalHarmonicBasis (unsigned int L)
virtual ~ODFSphericalHarmonicBasis ()
Detailed Description
Definition at line 10 of file animaODFSphericalHarmonicBasis.h.
Constructor & Destructor Documentation
ODFSphericalHarmonicBasis()
anima::ODFSphericalHarmonicBasis::ODFSphericalHarmonicBasis (unsigned int L)
Definition at line 6 of file animaODFSphericalHarmonicBasis.cxx.
~ODFSphericalHarmonicBasis()
virtual anima::ODFSphericalHarmonicBasis::~ODFSphericalHarmonicBasis () inline virtual
Definition at line 14 of file animaODFSphericalHarmonicBasis.h.
Member Function Documentation
getCurvatureAtPosition()
template<class T > double anima::ODFSphericalHarmonicBasis::getCurvatureAtPosition (const T & coefficients, double theta, double phi)
Definition at line 168 of file animaODFSphericalHarmonicBasis.hxx.
References getPhiSecondDerivativeValueAtPosition(), getThetaSecondDerivativeValueAtPosition(), and getValueAtPosition().
Referenced by getPhiSecondDerivativeValueAtPosition(), and anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection().
getNthSHValueAtPosition()
double anima::ODFSphericalHarmonicBasis::getNthSHValueAtPosition (int k, int m, double theta, double phi)
Definition at line 19 of file animaODFSphericalHarmonicBasis.cxx.
Referenced by anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::BeforeThreadedGenerateData().
getPhiFirstDerivativeValueAtPosition()
template<class T > double anima::ODFSphericalHarmonicBasis::getPhiFirstDerivativeValueAtPosition (const T & coefficients, double theta, double phi)
Definition at line 72 of file animaODFSphericalHarmonicBasis.hxx.
References getThetaSecondDerivativeValueAtPosition().
Referenced by getThetaFirstDerivativeValueAtPosition().
getPhiSecondDerivativeValueAtPosition()
template<class T > double anima::ODFSphericalHarmonicBasis::getPhiSecondDerivativeValueAtPosition (const T & coefficients, double theta, double phi)
Definition at line 144 of file animaODFSphericalHarmonicBasis.hxx.
References getCurvatureAtPosition().
Referenced by getCurvatureAtPosition(), and getThetaPhiDerivativeValueAtPosition().
GetSampleValues()
template<class T > itk::VariableLengthVector< T > anima::ODFSphericalHarmonicBasis::GetSampleValues (itk::VariableLengthVector< T > & data, std::vector< std::vector< double > > & m_SampleDirections)
Definition at line 34 of file animaODFSphericalHarmonicBasis.hxx.
References getThetaFirstDerivativeValueAtPosition(), and getValueAtPosition().
Referenced by getValueAtPosition().
getThetaFirstDerivativeValueAtPosition()
template<class T > double anima::ODFSphericalHarmonicBasis::getThetaFirstDerivativeValueAtPosition (const T & coefficients, double theta, double phi)
Definition at line 48 of file animaODFSphericalHarmonicBasis.hxx.
References getPhiFirstDerivativeValueAtPosition().
Referenced by GetSampleValues().
getThetaPhiDerivativeValueAtPosition()
template<class T > double anima::ODFSphericalHarmonicBasis::getThetaPhiDerivativeValueAtPosition (const T & coefficients, double theta, double phi)
Definition at line 120 of file animaODFSphericalHarmonicBasis.hxx.
References getPhiSecondDerivativeValueAtPosition().
Referenced by getThetaSecondDerivativeValueAtPosition().
getThetaSecondDerivativeValueAtPosition()
template<class T > double anima::ODFSphericalHarmonicBasis::getThetaSecondDerivativeValueAtPosition (const T & coefficients, double theta, double phi)
Definition at line 96 of file animaODFSphericalHarmonicBasis.hxx.
References getThetaPhiDerivativeValueAtPosition().
Referenced by getCurvatureAtPosition(), and getPhiFirstDerivativeValueAtPosition().
getValueAtPosition()
template<class T > double anima::ODFSphericalHarmonicBasis::getValueAtPosition (const T & coefficients, double theta, double phi)
Definition at line 10 of file animaODFSphericalHarmonicBasis.hxx.
References GetSampleValues().
Referenced by getCurvatureAtPosition(), GetSampleValues(), anima::ODFMaximaCostFunction::GetValue(), and anima::ODFProbabilisticTractographyImageFilter::ProposeNewDirection().
The documentation for this class was generated from the following files:
animaODFSphericalHarmonicBasis.h
animaODFSphericalHarmonicBasis.cxx
animaODFSphericalHarmonicBasis.hxx