ANIMA: anima::PyramidalSymmetryBridge< PixelType, ScalarType > Class Template Reference
anima::PyramidalSymmetryBridge< PixelType, ScalarType > Class Template Reference
#include <animaPyramidalSymmetryBridge.h>
Public Types
typedef BaseTransformType::Pointer BaseTransformPointer
typedef itk::AffineTransform< ScalarType, 3 > BaseTransformType
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef itk::Image< PixelType, 3 > InputImageType
typedef TransformType::MatrixType MatrixType
typedef TransformType::OffsetType OffsetType
typedef OutputImageType::Pointer OutputImagePointer
typedef itk::Image< float, 3 > OutputImageType
typedef TransformType::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef PyramidType::Pointer PyramidPointer
typedef itk::MultiResolutionPyramidImageFilter< InputImageType, OutputImageType > PyramidType
typedef PyramidalSymmetryBridge Self
typedef itk::ProcessObject Superclass
typedef TransformType::Pointer TransformPointer
typedef anima::SymmetryPlaneTransform< ScalarType > TransformType
Public Member Functions
void ComputeRealignTransform (itk::Vector< double, InputImageType::ImageDimension > centralPoint, typename InputImageType::PointType &centerReal, ParametersType &imageParams)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
std::string GetFixedfile ()
int GetHistogramSize ()
Metric GetMetric ()
virtual const char * GetNameOfClass () const
int GetNumberOfPyramidLevels ()
int GetOptimizerMaxIterations ()
OutputImagePointer GetOutputImage ()
BaseTransformPointer GetOutputRealignTransform ()
std::string GetOutputRealignTransformFile ()
TransformPointer GetOutputTransform ()
std::string GetOutputTransformFile ()
std::string GetResultfile ()
double GetUpperBoundAngle ()
double GetUpperBoundDistance ()
void ParseParameters (int argc, const char **argv)
void SaveRealignTransformFile (void)
void SaveResultFile (void)
void SaveTransformFile (void)
void SetFixedfile (std::string fixedfile)
void SetFloatingImage (InputImagePointer floatingImage)
void SetHistogramSize (int histogramSize)
void SetMetric (Metric metric)
void SetNumberOfPyramidLevels (int numberOfPyramidLevels)
void SetOptimizerMaxIterations (int optMaxIterations)
void SetOutputRealignTransformFile (std::string outputRealignTransformFile)
void SetOutputTransformFile (std::string outputTransformFile)
void SetProgressCallback (itk::CStyleCommand::Pointer callback)
void SetReferenceImage (InputImagePointer referenceImage)
void SetResultFile (std::string resultFile)
void SetUpperBoundAngle (double val)
void SetUpperBoundDistance (double val)
void Update () ITK_OVERRIDE
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
PyramidalSymmetryBridge ()
void SetupPyramids ()
virtual ~PyramidalSymmetryBridge ()
Detailed Description
template<class PixelType = float, typename ScalarType = double>
class anima::PyramidalSymmetryBridge< PixelType, ScalarType >
Definition at line 21 of file animaPyramidalSymmetryBridge.h.
Member Typedef Documentation
BaseTransformPointer
template<class PixelType = float, typename ScalarType = double> typedef BaseTransformType::Pointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::BaseTransformPointer
Definition at line 36 of file animaPyramidalSymmetryBridge.h.
BaseTransformType
template<class PixelType = float, typename ScalarType = double> typedef itk::AffineTransform<ScalarType,3> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::BaseTransformType
Definition at line 35 of file animaPyramidalSymmetryBridge.h.
ConstPointer
template<class PixelType = float, typename ScalarType = double> typedef itk::SmartPointer<const Self> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::ConstPointer
Definition at line 46 of file animaPyramidalSymmetryBridge.h.
InputImagePointer
template<class PixelType = float, typename ScalarType = double> typedef InputImageType::Pointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::InputImagePointer
Definition at line 26 of file animaPyramidalSymmetryBridge.h.
InputImageType
template<class PixelType = float, typename ScalarType = double> typedef itk::Image<PixelType,3> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::InputImageType
Definition at line 24 of file animaPyramidalSymmetryBridge.h.
MatrixType
template<class PixelType = float, typename ScalarType = double> typedef TransformType::MatrixType anima::PyramidalSymmetryBridge< PixelType, ScalarType >::MatrixType
Definition at line 32 of file animaPyramidalSymmetryBridge.h.
OffsetType
template<class PixelType = float, typename ScalarType = double> typedef TransformType::OffsetType anima::PyramidalSymmetryBridge< PixelType, ScalarType >::OffsetType
Definition at line 33 of file animaPyramidalSymmetryBridge.h.
OutputImagePointer
template<class PixelType = float, typename ScalarType = double> typedef OutputImageType::Pointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::OutputImagePointer
Definition at line 27 of file animaPyramidalSymmetryBridge.h.
OutputImageType
template<class PixelType = float, typename ScalarType = double> typedef itk::Image<float,3> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::OutputImageType
Definition at line 25 of file animaPyramidalSymmetryBridge.h.
ParametersType
template<class PixelType = float, typename ScalarType = double> typedef TransformType::ParametersType anima::PyramidalSymmetryBridge< PixelType, ScalarType >::ParametersType
Definition at line 31 of file animaPyramidalSymmetryBridge.h.
Pointer
template<class PixelType = float, typename ScalarType = double> typedef itk::SmartPointer<Self> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::Pointer
Definition at line 45 of file animaPyramidalSymmetryBridge.h.
PyramidPointer
template<class PixelType = float, typename ScalarType = double> typedef PyramidType::Pointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::PyramidPointer
Definition at line 39 of file animaPyramidalSymmetryBridge.h.
PyramidType
template<class PixelType = float, typename ScalarType = double> typedef itk::MultiResolutionPyramidImageFilter<InputImageType,OutputImageType> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::PyramidType
Definition at line 38 of file animaPyramidalSymmetryBridge.h.
Self
template<class PixelType = float, typename ScalarType = double> typedef PyramidalSymmetryBridge anima::PyramidalSymmetryBridge< PixelType, ScalarType >::Self
SmartPointer typedef support
Definition at line 42 of file animaPyramidalSymmetryBridge.h.
Superclass
template<class PixelType = float, typename ScalarType = double> typedef itk::ProcessObject anima::PyramidalSymmetryBridge< PixelType, ScalarType >::Superclass
Definition at line 43 of file animaPyramidalSymmetryBridge.h.
TransformPointer
template<class PixelType = float, typename ScalarType = double> typedef TransformType::Pointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::TransformPointer
Definition at line 30 of file animaPyramidalSymmetryBridge.h.
TransformType
template<class PixelType = float, typename ScalarType = double> typedef anima::SymmetryPlaneTransform<ScalarType> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::TransformType
Definition at line 29 of file animaPyramidalSymmetryBridge.h.
Constructor & Destructor Documentation
PyramidalSymmetryBridge()
template<class PixelType = float, typename ScalarType = double> anima::PyramidalSymmetryBridge< PixelType, ScalarType >::PyramidalSymmetryBridge () inline protected
Definition at line 112 of file animaPyramidalSymmetryBridge.h.
References MeanSquares, and anima::SymmetryPlaneTransform< TScalarType >::New().
~PyramidalSymmetryBridge()
template<class PixelType = float, typename ScalarType = double> virtual anima::PyramidalSymmetryBridge< PixelType, ScalarType >::~PyramidalSymmetryBridge () inline protected virtual
Definition at line 139 of file animaPyramidalSymmetryBridge.h.
References anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetupPyramids().
Member Function Documentation
ComputeRealignTransform()
template<class PixelType , typename ScalarType > void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::ComputeRealignTransform (itk::Vector< double, InputImageType::ImageDimension > centralPoint, typename InputImageType::PointType & centerReal, ParametersType & imageParams)
Definition at line 216 of file animaPyramidalSymmetryBridge.hxx.
CreateAnother()
template<class PixelType = float, typename ScalarType = double> virtual::itk::LightObject::Pointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::CreateAnother (void) const
GetFixedfile()
template<class PixelType = float, typename ScalarType = double> std::string anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetFixedfile () inline
Definition at line 88 of file animaPyramidalSymmetryBridge.h.
GetHistogramSize()
template<class PixelType = float, typename ScalarType = double> int anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetHistogramSize () inline
Definition at line 67 of file animaPyramidalSymmetryBridge.h.
GetMetric()
template<class PixelType = float, typename ScalarType = double> Metric anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetMetric () inline
Definition at line 61 of file animaPyramidalSymmetryBridge.h.
GetNameOfClass()
template<class PixelType = float, typename ScalarType = double> virtual const char* anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetNameOfClass () const virtual
GetNumberOfPyramidLevels()
template<class PixelType = float, typename ScalarType = double> int anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetNumberOfPyramidLevels () inline
Definition at line 76 of file animaPyramidalSymmetryBridge.h.
GetOptimizerMaxIterations()
template<class PixelType = float, typename ScalarType = double> int anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetOptimizerMaxIterations () inline
Definition at line 64 of file animaPyramidalSymmetryBridge.h.
GetOutputImage()
template<class PixelType = float, typename ScalarType = double> OutputImagePointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetOutputImage () inline
Definition at line 103 of file animaPyramidalSymmetryBridge.h.
GetOutputRealignTransform()
template<class PixelType = float, typename ScalarType = double> BaseTransformPointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetOutputRealignTransform () inline
Definition at line 109 of file animaPyramidalSymmetryBridge.h.
GetOutputRealignTransformFile()
template<class PixelType = float, typename ScalarType = double> std::string anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetOutputRealignTransformFile () inline
Definition at line 82 of file animaPyramidalSymmetryBridge.h.
GetOutputTransform()
template<class PixelType = float, typename ScalarType = double> TransformPointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetOutputTransform () inline
Definition at line 106 of file animaPyramidalSymmetryBridge.h.
GetOutputTransformFile()
template<class PixelType = float, typename ScalarType = double> std::string anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetOutputTransformFile () inline
Definition at line 85 of file animaPyramidalSymmetryBridge.h.
GetResultfile()
template<class PixelType = float, typename ScalarType = double> std::string anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetResultfile () inline
Definition at line 79 of file animaPyramidalSymmetryBridge.h.
GetUpperBoundAngle()
template<class PixelType = float, typename ScalarType = double> double anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetUpperBoundAngle () inline
Definition at line 73 of file animaPyramidalSymmetryBridge.h.
GetUpperBoundDistance()
template<class PixelType = float, typename ScalarType = double> double anima::PyramidalSymmetryBridge< PixelType, ScalarType >::GetUpperBoundDistance () inline
Definition at line 70 of file animaPyramidalSymmetryBridge.h.
New()
template<class PixelType = float, typename ScalarType = double> static Pointer anima::PyramidalSymmetryBridge< PixelType, ScalarType >::New () static
ParseParameters()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::ParseParameters (int argc, const char ** argv)
SaveRealignTransformFile()
template<class PixelType , typename ScalarType > void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SaveRealignTransformFile (void)
Definition at line 424 of file animaPyramidalSymmetryBridge.hxx.
Referenced by anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetProgressCallback().
SaveResultFile()
template<class PixelType , typename ScalarType > void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SaveResultFile (void)
Definition at line 394 of file animaPyramidalSymmetryBridge.hxx.
Referenced by anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetProgressCallback().
SaveTransformFile()
template<class PixelType , typename ScalarType > void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SaveTransformFile (void)
Definition at line 405 of file animaPyramidalSymmetryBridge.hxx.
Referenced by anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetProgressCallback().
SetFixedfile()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetFixedfile (std::string fixedfile) inline
Definition at line 89 of file animaPyramidalSymmetryBridge.h.
SetFloatingImage()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetFloatingImage (InputImagePointer floatingImage) inline
Definition at line 93 of file animaPyramidalSymmetryBridge.h.
SetHistogramSize()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetHistogramSize (int histogramSize) inline
Definition at line 68 of file animaPyramidalSymmetryBridge.h.
SetMetric()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetMetric (Metric metric) inline
Definition at line 62 of file animaPyramidalSymmetryBridge.h.
SetNumberOfPyramidLevels()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetNumberOfPyramidLevels (int numberOfPyramidLevels) inline
Definition at line 77 of file animaPyramidalSymmetryBridge.h.
SetOptimizerMaxIterations()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetOptimizerMaxIterations (int optMaxIterations) inline
Definition at line 65 of file animaPyramidalSymmetryBridge.h.
SetOutputRealignTransformFile()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetOutputRealignTransformFile (std::string outputRealignTransformFile) inline
Definition at line 83 of file animaPyramidalSymmetryBridge.h.
SetOutputTransformFile()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetOutputTransformFile (std::string outputTransformFile) inline
Definition at line 86 of file animaPyramidalSymmetryBridge.h.
SetProgressCallback()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetProgressCallback (itk::CStyleCommand::Pointer callback) inline
Definition at line 95 of file animaPyramidalSymmetryBridge.h.
References anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SaveRealignTransformFile(), anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SaveResultFile(), and anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SaveTransformFile().
SetReferenceImage()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetReferenceImage (InputImagePointer referenceImage) inline
Definition at line 91 of file animaPyramidalSymmetryBridge.h.
SetResultFile()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetResultFile (std::string resultFile) inline
Definition at line 80 of file animaPyramidalSymmetryBridge.h.
SetUpperBoundAngle()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetUpperBoundAngle (double val) inline
Definition at line 74 of file animaPyramidalSymmetryBridge.h.
SetUpperBoundDistance()
template<class PixelType = float, typename ScalarType = double> void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetUpperBoundDistance (double val) inline
Definition at line 71 of file animaPyramidalSymmetryBridge.h.
SetupPyramids()
template<class PixelType , typename ScalarType > void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::SetupPyramids () protected
Definition at line 437 of file animaPyramidalSymmetryBridge.hxx.
Referenced by anima::PyramidalSymmetryBridge< PixelType, ScalarType >::~PyramidalSymmetryBridge().
Update()
template<class PixelType , typename ScalarType > void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::Update ()
Definition at line 23 of file animaPyramidalSymmetryBridge.hxx.
References MeanSquares, MutualInformation, and anima::TransformCartesianToSphericalCoordinates().
WriteOutputs()
template<class PixelType , typename ScalarType > void anima::PyramidalSymmetryBridge< PixelType, ScalarType >::WriteOutputs ()
Definition at line 383 of file animaPyramidalSymmetryBridge.hxx.
The documentation for this class was generated from the following files:
animaPyramidalSymmetryBridge.h
animaPyramidalSymmetryBridge.hxx