ANIMA: anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage > Class Template Reference
anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage > Class Template Reference
#include <animaFastMeanSquaresImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, TFixedImage::ImageDimension > ContinuousIndexType
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef Superclass::GradientPixelType GradientPixelType
typedef Superclass::InputPointType InputPointType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::RealType RealType
typedef FastMeanSquaresImageToImageMetric Self
typedef itk::ImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef Superclass::TransformJacobianType TransformJacobianType
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void GetDerivative (const TransformParametersType &parameters, DerivativeType &Derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &Value, DerivativeType &Derivative) const ITK_OVERRIDE
void PreComputeFixedValues ()
virtual void SetScaleIntensities (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
FastMeanSquaresImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~FastMeanSquaresImageToImageMetric ()
Detailed Description
template<class TFixedImage, class TMovingImage>
class anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >
Definition at line 10 of file animaFastMeanSquaresImageToImageMetric.h.
Member Typedef Documentation
ConstPointer
template<class TFixedImage, class TMovingImage> typedef itk::SmartPointer<const Self> anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::ConstPointer
Definition at line 19 of file animaFastMeanSquaresImageToImageMetric.h.
ContinuousIndexType
template<class TFixedImage, class TMovingImage> typedef itk::ContinuousIndex<double,TFixedImage::ImageDimension> anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::ContinuousIndexType
Definition at line 37 of file animaFastMeanSquaresImageToImageMetric.h.
DerivativeType
template<class TFixedImage, class TMovingImage> typedef Superclass::DerivativeType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::DerivativeType
Definition at line 40 of file animaFastMeanSquaresImageToImageMetric.h.
FixedImageConstPointer
template<class TFixedImage, class TMovingImage> typedef Superclass::FixedImageConstPointer anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::FixedImageConstPointer
Definition at line 43 of file animaFastMeanSquaresImageToImageMetric.h.
FixedImageType
template<class TFixedImage, class TMovingImage> typedef Superclass::FixedImageType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::FixedImageType
Definition at line 41 of file animaFastMeanSquaresImageToImageMetric.h.
GradientPixelType
template<class TFixedImage, class TMovingImage> typedef Superclass::GradientPixelType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GradientPixelType
Definition at line 34 of file animaFastMeanSquaresImageToImageMetric.h.
InputPointType
template<class TFixedImage, class TMovingImage> typedef Superclass::InputPointType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::InputPointType
Definition at line 36 of file animaFastMeanSquaresImageToImageMetric.h.
MeasureType
template<class TFixedImage, class TMovingImage> typedef Superclass::MeasureType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::MeasureType
Definition at line 39 of file animaFastMeanSquaresImageToImageMetric.h.
MovingImageConstPointer
template<class TFixedImage, class TMovingImage> typedef Superclass::MovingImageConstPointer anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::MovingImageConstPointer
Definition at line 44 of file animaFastMeanSquaresImageToImageMetric.h.
MovingImageType
template<class TFixedImage, class TMovingImage> typedef Superclass::MovingImageType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::MovingImageType
Definition at line 42 of file animaFastMeanSquaresImageToImageMetric.h.
OutputPointType
template<class TFixedImage, class TMovingImage> typedef Superclass::OutputPointType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::OutputPointType
Definition at line 35 of file animaFastMeanSquaresImageToImageMetric.h.
Pointer
template<class TFixedImage, class TMovingImage> typedef itk::SmartPointer<Self> anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::Pointer
Definition at line 18 of file animaFastMeanSquaresImageToImageMetric.h.
RealType
template<class TFixedImage, class TMovingImage> typedef Superclass::RealType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::RealType
Types transferred from the base class
Definition at line 25 of file animaFastMeanSquaresImageToImageMetric.h.
Self
template<class TFixedImage, class TMovingImage> typedef FastMeanSquaresImageToImageMetric anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::Self
Standard class typedefs.
Definition at line 16 of file animaFastMeanSquaresImageToImageMetric.h.
Superclass
template<class TFixedImage, class TMovingImage> typedef itk::ImageToImageMetric<TFixedImage, TMovingImage > anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::Superclass
Definition at line 17 of file animaFastMeanSquaresImageToImageMetric.h.
TransformJacobianType
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformJacobianType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::TransformJacobianType
Definition at line 33 of file animaFastMeanSquaresImageToImageMetric.h.
TransformParametersType
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformParametersType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::TransformParametersType
Definition at line 32 of file animaFastMeanSquaresImageToImageMetric.h.
TransformPointer
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformPointer anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::TransformPointer
Definition at line 31 of file animaFastMeanSquaresImageToImageMetric.h.
TransformType
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::TransformType
Definition at line 30 of file animaFastMeanSquaresImageToImageMetric.h.
Constructor & Destructor Documentation
FastMeanSquaresImageToImageMetric()
template<class TFixedImage , class TMovingImage > anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::FastMeanSquaresImageToImageMetric () protected
Constructor
Definition at line 14 of file animaFastMeanSquaresImageToImageMetric.hxx.
References anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetValue().
Referenced by anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::~FastMeanSquaresImageToImageMetric().
~FastMeanSquaresImageToImageMetric()
template<class TFixedImage, class TMovingImage> virtual anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::~FastMeanSquaresImageToImageMetric () inline protected virtual
Definition at line 64 of file animaFastMeanSquaresImageToImageMetric.h.
References anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::FastMeanSquaresImageToImageMetric(), and anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::PrintSelf().
Member Function Documentation
CreateAnother()
template<class TFixedImage, class TMovingImage> virtual::itk::LightObject::Pointer anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::CreateAnother (void) const
GetDerivative()
template<class TFixedImage , class TMovingImage > void anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetDerivative (const TransformParametersType & parameters, DerivativeType & derivative) const
Get the derivatives of the match measure.
Get the Derivative Measure
Definition at line 80 of file animaFastMeanSquaresImageToImageMetric.hxx.
References anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetValueAndDerivative().
Referenced by anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetValue().
GetNameOfClass()
template<class TFixedImage, class TMovingImage> virtual const char* anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetValue()
template<class TFixedImage , class TMovingImage > FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::MeasureType anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Get the match Measure
Definition at line 25 of file animaFastMeanSquaresImageToImageMetric.hxx.
References anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetDerivative().
Referenced by anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::FastMeanSquaresImageToImageMetric().
GetValueAndDerivative()
template<class TFixedImage , class TMovingImage > void anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetValueAndDerivative (const TransformParametersType & parameters, MeasureType & Value, DerivativeType & Derivative) const
Get value and derivatives for multiple valued optimizers.
Definition at line 92 of file animaFastMeanSquaresImageToImageMetric.hxx.
References anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::PreComputeFixedValues().
Referenced by anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetDerivative().
New()
template<class TFixedImage, class TMovingImage> static Pointer anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::New () static
Method for creation through the object factory.
PreComputeFixedValues()
template<class TFixedImage , class TMovingImage > void anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::PreComputeFixedValues ()
Definition at line 101 of file animaFastMeanSquaresImageToImageMetric.hxx.
References anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::PrintSelf().
Referenced by anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::GetValueAndDerivative().
PrintSelf()
template<class TFixedImage , class TMovingImage > void anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
Definition at line 144 of file animaFastMeanSquaresImageToImageMetric.hxx.
Referenced by anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::PreComputeFixedValues(), and anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::~FastMeanSquaresImageToImageMetric().
SetScaleIntensities()
template<class TFixedImage, class TMovingImage> virtual void anima::FastMeanSquaresImageToImageMetric< TFixedImage, TMovingImage >::SetScaleIntensities (bool _arg) virtual
The documentation for this class was generated from the following files:
animaFastMeanSquaresImageToImageMetric.h
animaFastMeanSquaresImageToImageMetric.hxx