ANIMA: anima::MCMBlockMatcher< TInputImageType > Class Template Reference
anima::MCMBlockMatcher< TInputImageType > Class Template Reference
#include <animaMCMBlockMatcher.h>
Public Types
typedef Superclass::AgregatorType AgregatorType
typedef Superclass::BaseInputTransformPointer BaseInputTransformPointer
typedef Superclass::InputImageType InputImageType
typedef anima::MCMLinearInterpolateImageFunction< InputImageType, double > MCMInterpolatorType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef Superclass::MetricPointer MetricPointer
enum ModelRotationType {
None = 0,
FiniteStrain,
PPD
}
typedef Superclass::OptimizerPointer OptimizerPointer
typedef Superclass::PointType PointType
enum SimilarityDefinition {
MCMBasicMeanSquares = 0,
MCMOneToOneBasicMeanSquares,
MCMMeanSquares,
MTCorrelation,
MCMCorrelation
}
typedef BaseAffineBlockMatcher< TInputImageType > Superclass
Public Types inherited from anima::BaseAffineBlockMatcher< TInputImageType >
typedef Superclass::AgregatorType AgregatorType
typedef Superclass::BaseInputTransformPointer BaseInputTransformPointer
typedef Superclass::InputImageType InputImageType
typedef Superclass::MetricPointer MetricPointer
typedef Superclass::OptimizerPointer OptimizerPointer
typedef Superclass::PointType PointType
typedef BaseBlockMatcher< TInputImageType > Superclass
enum TransformDefinition {
Translation = 0,
Rigid,
Affine,
Directional_Affine
}
Public Types inherited from anima::BaseBlockMatcher< TInputImageType >
typedef anima::BaseTransformAgregator< TInputImageType::ImageDimension > AgregatorType
typedef BaseInputTransformType::Pointer BaseInputTransformPointer
typedef AgregatorType::BaseInputTransformType BaseInputTransformType
typedef InputImageType::RegionType ImageRegionType
typedef InputImageType::Pointer InputImagePointer
typedef TInputImageType InputImageType
typedef AgregatorType::InternalScalarType InternalScalarType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TInputImageType::ImageDimension > MaskImageType
typedef MetricType::Pointer MetricPointer
typedef itk::SingleValuedCostFunction MetricType
enum OptimizerDefinition {
Exhaustive = 0,
Bobyqa
}
typedef OptimizerType::Pointer OptimizerPointer
typedef itk::SingleValuedNonLinearOptimizer OptimizerType
typedef InputImageType::PointType PointType
typedef BaseBlockMatcher Self
Public Member Functions
bool GetMaximizedMetric ()
MCMBlockMatcher ()
void SetBigDelta (double val)
void SetGradientDirections (std::vector< vnl_vector_fixed< double, 3 > > &grads)
void SetGradientStrengths (std::vector< double > &val)
void SetModelRotationType (ModelRotationType val)
void SetSimilarityType (SimilarityDefinition val)
void SetSmallDelta (double val)
virtual ~MCMBlockMatcher ()
Public Member Functions inherited from anima::BaseAffineBlockMatcher< TInputImageType >
BaseAffineBlockMatcher ()
AgregatorType::TRANSFORM_TYPE GetAgregatorInputTransformType ()
TransformDefinition & GetBlockTransformType ()
void SetAffineDirection (unsigned int val)
void SetAngleMax (double val)
void SetBlockTransformType (TransformDefinition val)
void SetScaleMax (double val)
void SetSearchAngleRadius (double val)
void SetSearchScaleRadius (double val)
void SetTranslateMax (double val)
virtual ~BaseAffineBlockMatcher ()
Public Member Functions inherited from anima::BaseBlockMatcher< TInputImageType >
BaseBlockMatcher ()
MaskImagePointer & GetBlockGenerationMask ()
double GetBlockPercentageKept ()
std::vector< PointType > & GetBlockPositions ()
ImageRegionType & GetBlockRegion (unsigned int i)
std::vector< ImageRegionType > & GetBlockRegions ()
unsigned int GetBlockSize ()
unsigned int GetBlockSpacing ()
BaseInputTransformPointer & GetBlockTransformPointer (unsigned int i)
std::vector< BaseInputTransformPointer > & GetBlockTransformPointers ()
double GetBlockVarianceThreshold ()
const std::vector< double > & GetBlockWeights ()
InputImagePointer & GetMovingImage ()
unsigned int GetNumberOfThreads ()
OptimizerDefinition GetOptimizerType ()
InputImagePointer & GetReferenceImage ()
double GetSearchRadius ()
bool GetVerbose ()
void SetBlockGenerationMask (MaskImageType *image)
void SetBlockPercentageKept (double val)
void SetBlockSize (unsigned int val)
void SetBlockSpacing (unsigned int val)
void SetBlockVarianceThreshold (double val)
void SetFinalRadius (double val)
void SetForceComputeBlocks (bool val)
void SetMovingImage (InputImageType *image)
void SetNumberOfThreads (unsigned int val)
void SetOptimizerMaximumIterations (unsigned int val)
void SetOptimizerType (OptimizerDefinition val)
void SetReferenceImage (InputImageType *image)
void SetSearchRadius (double val)
void SetStepSize (double val)
void SetVerbose (bool value)
void Update ()
virtual ~BaseBlockMatcher ()
Protected Member Functions
virtual void BlockMatchingSetup (MetricPointer &metric, unsigned int block)
virtual double ComputeBlockWeight (double val, unsigned int block)
virtual MCMInterpolatorType * CreateInterpolator ()
void InitializeBlocks ()
virtual MetricPointer SetupMetric ()
Protected Member Functions inherited from anima::BaseAffineBlockMatcher< TInputImageType >
virtual void BlockMatchingSetup (MetricPointer &metric, unsigned int block)
virtual BaseInputTransformPointer GetNewBlockTransform (PointType &blockCenter)
virtual void TransformDependantOptimizerSetup (OptimizerPointer &optimizer)
Protected Member Functions inherited from anima::BaseBlockMatcher< TInputImageType >
void BlockMatch (unsigned int startIndex, unsigned int endIndex)
void ProcessBlockMatch ()
void SetBlockPositions (std::vector< PointType > &val)
void SetBlockRegions (std::vector< ImageRegionType > &val)
void SetBlockWeights (std::vector< double > &val)
virtual OptimizerPointer SetupOptimizer ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::BaseBlockMatcher< TInputImageType >
static ITK_THREAD_RETURN_TYPE ThreadedMatching (void *arg)
Detailed Description
template<typename TInputImageType>
class anima::MCMBlockMatcher< TInputImageType >
Definition at line 11 of file animaMCMBlockMatcher.h.
Member Typedef Documentation
AgregatorType
template<typename TInputImageType> typedef Superclass::AgregatorType anima::MCMBlockMatcher< TInputImageType >::AgregatorType
Definition at line 36 of file animaMCMBlockMatcher.h.
BaseInputTransformPointer
template<typename TInputImageType> typedef Superclass::BaseInputTransformPointer anima::MCMBlockMatcher< TInputImageType >::BaseInputTransformPointer
Definition at line 38 of file animaMCMBlockMatcher.h.
InputImageType
template<typename TInputImageType> typedef Superclass::InputImageType anima::MCMBlockMatcher< TInputImageType >::InputImageType
Definition at line 34 of file animaMCMBlockMatcher.h.
MCMInterpolatorType
template<typename TInputImageType> typedef anima::MCMLinearInterpolateImageFunction<InputImageType,double> anima::MCMBlockMatcher< TInputImageType >::MCMInterpolatorType
Definition at line 44 of file animaMCMBlockMatcher.h.
MCModelPointer
template<typename TInputImageType> typedef MCModelType::Pointer anima::MCMBlockMatcher< TInputImageType >::MCModelPointer
Definition at line 42 of file animaMCMBlockMatcher.h.
MCModelType
template<typename TInputImageType> typedef anima::MultiCompartmentModel anima::MCMBlockMatcher< TInputImageType >::MCModelType
Definition at line 41 of file animaMCMBlockMatcher.h.
MetricPointer
template<typename TInputImageType> typedef Superclass::MetricPointer anima::MCMBlockMatcher< TInputImageType >::MetricPointer
Definition at line 37 of file animaMCMBlockMatcher.h.
OptimizerPointer
template<typename TInputImageType> typedef Superclass::OptimizerPointer anima::MCMBlockMatcher< TInputImageType >::OptimizerPointer
Definition at line 39 of file animaMCMBlockMatcher.h.
PointType
template<typename TInputImageType> typedef Superclass::PointType anima::MCMBlockMatcher< TInputImageType >::PointType
Definition at line 35 of file animaMCMBlockMatcher.h.
Superclass
template<typename TInputImageType> typedef BaseAffineBlockMatcher<TInputImageType> anima::MCMBlockMatcher< TInputImageType >::Superclass
Definition at line 33 of file animaMCMBlockMatcher.h.
Member Enumeration Documentation
ModelRotationType
template<typename TInputImageType> enum anima::MCMBlockMatcher::ModelRotationType
Enumerator
None
FiniteStrain
PPD
Definition at line 26 of file animaMCMBlockMatcher.h.
SimilarityDefinition
template<typename TInputImageType> enum anima::MCMBlockMatcher::SimilarityDefinition
Enumerator
MCMBasicMeanSquares
MCMOneToOneBasicMeanSquares
MCMMeanSquares
MTCorrelation
MCMCorrelation
Definition at line 17 of file animaMCMBlockMatcher.h.
Constructor & Destructor Documentation
MCMBlockMatcher()
template<typename TInputImageType > anima::MCMBlockMatcher< TInputImageType >::MCMBlockMatcher ()
Definition at line 19 of file animaMCMBlockMatcher.hxx.
References anima::DiffusionBigDelta, anima::DiffusionSmallDelta, anima::MCMBlockMatcher< TInputImageType >::GetMaximizedMetric(), and MCMMeanSquares.
~MCMBlockMatcher()
template<typename TInputImageType> virtual anima::MCMBlockMatcher< TInputImageType >::~MCMBlockMatcher () inline virtual
Definition at line 15 of file animaMCMBlockMatcher.h.
Member Function Documentation
BlockMatchingSetup()
template<typename TInputImageType > void anima::MCMBlockMatcher< TInputImageType >::BlockMatchingSetup (MetricPointer & metric, unsigned int block) protected virtual
Definition at line 177 of file animaMCMBlockMatcher.hxx.
References MCMBasicMeanSquares, MCMCorrelation, MCMMeanSquares, MCMOneToOneBasicMeanSquares, MTCorrelation, and anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetFixedImageRegion().
Referenced by anima::MCMBlockMatcher< TInputImageType >::ComputeBlockWeight(), and anima::MCMBlockMatcher< TInputImageType >::SetGradientDirections().
ComputeBlockWeight()
template<typename TInputImageType > double anima::MCMBlockMatcher< TInputImageType >::ComputeBlockWeight (double val, unsigned int block) protected virtual
Implements anima::BaseBlockMatcher< TInputImageType >.
Definition at line 169 of file animaMCMBlockMatcher.hxx.
References anima::MCMBlockMatcher< TInputImageType >::BlockMatchingSetup().
Referenced by anima::MCMBlockMatcher< TInputImageType >::SetGradientDirections(), and anima::MCMBlockMatcher< TInputImageType >::SetupMetric().
CreateInterpolator()
template<typename TInputImageType > MCMBlockMatcher< TInputImageType >::MCMInterpolatorType * anima::MCMBlockMatcher< TInputImageType >::CreateInterpolator () protected virtual
Definition at line 38 of file animaMCMBlockMatcher.hxx.
References anima::MCMBlockMatcher< TInputImageType >::InitializeBlocks().
Referenced by anima::MCMBlockMatcher< TInputImageType >::GetMaximizedMetric(), and anima::MCMBlockMatcher< TInputImageType >::SetGradientDirections().
GetMaximizedMetric()
template<typename TInputImageType > bool anima::MCMBlockMatcher< TInputImageType >::GetMaximizedMetric () virtual
Implements anima::BaseBlockMatcher< TInputImageType >.
Definition at line 30 of file animaMCMBlockMatcher.hxx.
References anima::MCMBlockMatcher< TInputImageType >::CreateInterpolator().
Referenced by anima::MCMBlockMatcher< TInputImageType >::MCMBlockMatcher().
InitializeBlocks()
template<typename TInputImageType > void anima::MCMBlockMatcher< TInputImageType >::InitializeBlocks () protected virtual
Reimplemented from anima::BaseBlockMatcher< TInputImageType >.
Definition at line 50 of file animaMCMBlockMatcher.hxx.
References anima::MCMBlockMatcher< TInputImageType >::SetupMetric().
Referenced by anima::MCMBlockMatcher< TInputImageType >::CreateInterpolator(), and anima::MCMBlockMatcher< TInputImageType >::SetGradientDirections().
SetBigDelta()
template<typename TInputImageType> void anima::MCMBlockMatcher< TInputImageType >::SetBigDelta (double val) inline
Definition at line 52 of file animaMCMBlockMatcher.h.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetGradientDirections()
template<typename TInputImageType> void anima::MCMBlockMatcher< TInputImageType >::SetGradientDirections (std::vector< vnl_vector_fixed< double, 3 > > & grads) inline
Definition at line 54 of file animaMCMBlockMatcher.h.
References anima::MCMBlockMatcher< TInputImageType >::BlockMatchingSetup(), anima::MCMBlockMatcher< TInputImageType >::ComputeBlockWeight(), anima::MCMBlockMatcher< TInputImageType >::CreateInterpolator(), anima::MCMBlockMatcher< TInputImageType >::InitializeBlocks(), and anima::MCMBlockMatcher< TInputImageType >::SetupMetric().
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetGradientStrengths()
template<typename TInputImageType> void anima::MCMBlockMatcher< TInputImageType >::SetGradientStrengths (std::vector< double > & val) inline
Definition at line 53 of file animaMCMBlockMatcher.h.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetModelRotationType()
template<typename TInputImageType> void anima::MCMBlockMatcher< TInputImageType >::SetModelRotationType (ModelRotationType val) inline
Definition at line 49 of file animaMCMBlockMatcher.h.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetSimilarityType()
template<typename TInputImageType> void anima::MCMBlockMatcher< TInputImageType >::SetSimilarityType (SimilarityDefinition val) inline
Definition at line 47 of file animaMCMBlockMatcher.h.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetSmallDelta()
template<typename TInputImageType> void anima::MCMBlockMatcher< TInputImageType >::SetSmallDelta (double val) inline
Definition at line 51 of file animaMCMBlockMatcher.h.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update().
SetupMetric()
template<typename TInputImageType > MCMBlockMatcher< TInputImageType >::MetricPointer anima::MCMBlockMatcher< TInputImageType >::SetupMetric () protected virtual
Implements anima::BaseBlockMatcher< TInputImageType >.
Definition at line 84 of file animaMCMBlockMatcher.hxx.
References anima::MCMBlockMatcher< TInputImageType >::ComputeBlockWeight(), MCMBasicMeanSquares, MCMCorrelation, MCMMeanSquares, MCMOneToOneBasicMeanSquares, MTCorrelation, anima::BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage >::SetModelRotation(), and Translation.
Referenced by anima::MCMBlockMatcher< TInputImageType >::InitializeBlocks(), and anima::MCMBlockMatcher< TInputImageType >::SetGradientDirections().
The documentation for this class was generated from the following files:
animaMCMBlockMatcher.h
animaMCMBlockMatcher.hxx