ANIMA: anima::SpectralClusteringFilter< ScalarType > Class Template Reference
anima::SpectralClusteringFilter< ScalarType > Class Template Reference
Provides an implementation of spectral clustering, as proposed in A.Y. Ng, M.I. Jordan and Y. Weiss. "On Spectral Clustering: Analysis and an Algorithm." Advances in Neural Information Processing Systems 14. 2001.
#include <animaSpectralClusteringFilter.h>
Public Types
typedef CMeansFilterType::CentroidAverageType CMeansAverageType
typedef anima::FuzzyCMeansFilter< ScalarType > CMeansFilterType
typedef vnl_matrix< ScalarType > MatrixType
typedef std::vector< ScalarType > VectorType
Public Member Functions
double ComputeClustersSpreading ()
void ComputeSpectralVectors ()
VectorType & GetCentroid (unsigned int i)
VectorType & GetClassesMembership (unsigned int i)
std::vector< unsigned int > GetClassMembers (unsigned int i)
VectorType & GetSpectralVector (unsigned int i)
void InitializeSigmaFromDistances ()
void ResetOutputs ()
void SetCMeansAverageType (CMeansAverageType val)
void SetDataWeights (VectorType &val)
void SetInputData (MatrixType &data)
Input data: matrix of squared distances.
void SetMaxIterations (unsigned int mIt)
void SetMValue (double mV)
void SetNbClass (unsigned int nbC)
void SetRelStopCriterion (double rC)
void SetSigmaWeighting (double sigma)
void SetVerbose (bool verb)
SpectralClusteringFilter ()
void Update ()
virtual ~SpectralClusteringFilter ()
Detailed Description
template<class ScalarType>
class anima::SpectralClusteringFilter< ScalarType >
Provides an implementation of spectral clustering, as proposed in A.Y. Ng, M.I. Jordan and Y. Weiss. "On Spectral Clustering: Analysis and an Algorithm." Advances in Neural Information Processing Systems 14. 2001.
Definition at line 17 of file animaSpectralClusteringFilter.h.
Member Typedef Documentation
CMeansAverageType
template<class ScalarType > typedef CMeansFilterType::CentroidAverageType anima::SpectralClusteringFilter< ScalarType >::CMeansAverageType
Definition at line 24 of file animaSpectralClusteringFilter.h.
CMeansFilterType
template<class ScalarType > typedef anima::FuzzyCMeansFilter<ScalarType> anima::SpectralClusteringFilter< ScalarType >::CMeansFilterType
Definition at line 23 of file animaSpectralClusteringFilter.h.
MatrixType
template<class ScalarType > typedef vnl_matrix<ScalarType> anima::SpectralClusteringFilter< ScalarType >::MatrixType
Definition at line 21 of file animaSpectralClusteringFilter.h.
VectorType
template<class ScalarType > typedef std::vector<ScalarType> anima::SpectralClusteringFilter< ScalarType >::VectorType
Definition at line 20 of file animaSpectralClusteringFilter.h.
Constructor & Destructor Documentation
SpectralClusteringFilter()
template<class ScalarType > anima::SpectralClusteringFilter< ScalarType >::SpectralClusteringFilter ()
Definition at line 12 of file animaSpectralClusteringFilter.hxx.
~SpectralClusteringFilter()
template<class ScalarType > anima::SpectralClusteringFilter< ScalarType >::~SpectralClusteringFilter () virtual
Definition at line 43 of file animaSpectralClusteringFilter.hxx.
Member Function Documentation
ComputeClustersSpreading()
template<class ScalarType > double anima::SpectralClusteringFilter< ScalarType >::ComputeClustersSpreading ()
Definition at line 216 of file animaSpectralClusteringFilter.hxx.
Referenced by anima::SpectralClusteringFilter< ScalarType >::SetCMeansAverageType().
ComputeSpectralVectors()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::ComputeSpectralVectors ()
Definition at line 122 of file animaSpectralClusteringFilter.hxx.
Referenced by anima::SpectralClusteringFilter< ScalarType >::SetCMeansAverageType().
GetCentroid()
template<class ScalarType > VectorType& anima::SpectralClusteringFilter< ScalarType >::GetCentroid (unsigned int i) inline
Definition at line 54 of file animaSpectralClusteringFilter.h.
References anima::SpectralClusteringFilter< ScalarType >::GetClassMembers().
GetClassesMembership()
template<class ScalarType > VectorType& anima::SpectralClusteringFilter< ScalarType >::GetClassesMembership (unsigned int i) inline
Definition at line 53 of file animaSpectralClusteringFilter.h.
GetClassMembers()
template<class ScalarType > std::vector< unsigned int > anima::SpectralClusteringFilter< ScalarType >::GetClassMembers (unsigned int i)
Definition at line 185 of file animaSpectralClusteringFilter.hxx.
Referenced by anima::SpectralClusteringFilter< ScalarType >::GetCentroid().
GetSpectralVector()
template<class ScalarType > VectorType& anima::SpectralClusteringFilter< ScalarType >::GetSpectralVector (unsigned int i) inline
Definition at line 52 of file animaSpectralClusteringFilter.h.
InitializeSigmaFromDistances()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::InitializeSigmaFromDistances ()
Definition at line 103 of file animaSpectralClusteringFilter.hxx.
Referenced by anima::SpectralClusteringFilter< ScalarType >::SetCMeansAverageType().
ResetOutputs()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::ResetOutputs ()
Definition at line 34 of file animaSpectralClusteringFilter.hxx.
Referenced by anima::SpectralClusteringFilter< ScalarType >::SetCMeansAverageType().
SetCMeansAverageType()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetCMeansAverageType (CMeansAverageType val) inline
Definition at line 40 of file animaSpectralClusteringFilter.h.
References anima::SpectralClusteringFilter< ScalarType >::ComputeClustersSpreading(), anima::SpectralClusteringFilter< ScalarType >::ComputeSpectralVectors(), anima::SpectralClusteringFilter< ScalarType >::InitializeSigmaFromDistances(), anima::SpectralClusteringFilter< ScalarType >::ResetOutputs(), and anima::SpectralClusteringFilter< ScalarType >::Update().
SetDataWeights()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetDataWeights (VectorType & val) inline
Definition at line 31 of file animaSpectralClusteringFilter.h.
SetInputData()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetInputData (MatrixType & data)
Input data: matrix of squared distances.
Definition at line 51 of file animaSpectralClusteringFilter.hxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks().
SetMaxIterations()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetMaxIterations (unsigned int mIt) inline
Definition at line 36 of file animaSpectralClusteringFilter.h.
SetMValue()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetMValue (double mV) inline
Definition at line 38 of file animaSpectralClusteringFilter.h.
SetNbClass()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetNbClass (unsigned int nbC) inline
Definition at line 32 of file animaSpectralClusteringFilter.h.
Referenced by anima::MCMWeightedAverager::Update().
SetRelStopCriterion()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetRelStopCriterion (double rC) inline
Definition at line 37 of file animaSpectralClusteringFilter.h.
SetSigmaWeighting()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetSigmaWeighting (double sigma) inline
Definition at line 33 of file animaSpectralClusteringFilter.h.
SetVerbose()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::SetVerbose (bool verb) inline
Definition at line 50 of file animaSpectralClusteringFilter.h.
Update()
template<class ScalarType > void anima::SpectralClusteringFilter< ScalarType >::Update ()
Definition at line 62 of file animaSpectralClusteringFilter.hxx.
References anima::FuzzyCMeansFilter< ScalarType >::GetCentroid(), anima::FuzzyCMeansFilter< ScalarType >::GetClassesMembership(), anima::FuzzyCMeansFilter< ScalarType >::SetDataWeights(), anima::FuzzyCMeansFilter< ScalarType >::SetFlagSpectralClustering(), anima::FuzzyCMeansFilter< ScalarType >::SetInputData(), anima::FuzzyCMeansFilter< ScalarType >::SetMaxIterations(), anima::FuzzyCMeansFilter< ScalarType >::SetMValue(), anima::FuzzyCMeansFilter< ScalarType >::SetNbClass(), anima::FuzzyCMeansFilter< ScalarType >::SetRelStopCriterion(), anima::FuzzyCMeansFilter< ScalarType >::SetSphericalAverageType(), anima::FuzzyCMeansFilter< ScalarType >::SetVerbose(), and anima::FuzzyCMeansFilter< ScalarType >::Update().
Referenced by anima::SpectralClusteringFilter< ScalarType >::SetCMeansAverageType().
The documentation for this class was generated from the following files:
animaSpectralClusteringFilter.h
animaSpectralClusteringFilter.hxx