ANIMA: anima::MCMAverageImagesImageFilter< TPixelType > Class Template Reference
anima::MCMAverageImagesImageFilter< TPixelType > Class Template Reference
#include <animaMCMAverageImagesImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImagePointer
typedef anima::MCMImage< TPixelType, 3 > InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::RegionType InputRegionType
typedef MCMAveragerType::Pointer MCMAveragerPointer
typedef anima::MCMWeightedAverager MCMAveragerType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef OutputImageType::Pointer OutputImagePointer
typedef anima::MCMImage< TPixelType, 3 > OutputImageType
typedef InputImageType::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMAverageImagesImageFilter Self
typedef itk::ImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MCModelType * GetReferenceOutputModel ()
void SetReferenceOutputModel (MCModelPointer &model)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual MCMAveragerPointer CreateAverager ()
bool isZero (const itk::VariableLengthVector< double > &value) const
MCMAverageImagesImageFilter ()
void ThreadedGenerateData (const InputRegionType &region, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~MCMAverageImagesImageFilter ()
Detailed Description
template<class TPixelType>
class anima::MCMAverageImagesImageFilter< TPixelType >
Definition at line 13 of file animaMCMAverageImagesImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TPixelType> typedef itk::SmartPointer<const Self> anima::MCMAverageImagesImageFilter< TPixelType >::ConstPointer
Definition at line 24 of file animaMCMAverageImagesImageFilter.h.
InputImagePointer
template<class TPixelType> typedef InputImageType::ConstPointer anima::MCMAverageImagesImageFilter< TPixelType >::InputImagePointer
Definition at line 32 of file animaMCMAverageImagesImageFilter.h.
InputImageType
template<class TPixelType> typedef anima::MCMImage<TPixelType, 3> anima::MCMAverageImagesImageFilter< TPixelType >::InputImageType
Definition at line 20 of file animaMCMAverageImagesImageFilter.h.
InputIndexType
template<class TPixelType> typedef InputImageType::IndexType anima::MCMAverageImagesImageFilter< TPixelType >::InputIndexType
Definition at line 36 of file animaMCMAverageImagesImageFilter.h.
InputRegionType
template<class TPixelType> typedef InputImageType::RegionType anima::MCMAverageImagesImageFilter< TPixelType >::InputRegionType
Definition at line 35 of file animaMCMAverageImagesImageFilter.h.
MCMAveragerPointer
template<class TPixelType> typedef MCMAveragerType::Pointer anima::MCMAverageImagesImageFilter< TPixelType >::MCMAveragerPointer
Definition at line 44 of file animaMCMAverageImagesImageFilter.h.
MCMAveragerType
template<class TPixelType> typedef anima::MCMWeightedAverager anima::MCMAverageImagesImageFilter< TPixelType >::MCMAveragerType
Definition at line 43 of file animaMCMAverageImagesImageFilter.h.
MCModelPointer
template<class TPixelType> typedef MCModelType::Pointer anima::MCMAverageImagesImageFilter< TPixelType >::MCModelPointer
Definition at line 41 of file animaMCMAverageImagesImageFilter.h.
MCModelType
template<class TPixelType> typedef anima::MultiCompartmentModel anima::MCMAverageImagesImageFilter< TPixelType >::MCModelType
Definition at line 40 of file animaMCMAverageImagesImageFilter.h.
OutputImagePointer
template<class TPixelType> typedef OutputImageType::Pointer anima::MCMAverageImagesImageFilter< TPixelType >::OutputImagePointer
Definition at line 33 of file animaMCMAverageImagesImageFilter.h.
OutputImageType
template<class TPixelType> typedef anima::MCMImage<TPixelType, 3> anima::MCMAverageImagesImageFilter< TPixelType >::OutputImageType
Definition at line 21 of file animaMCMAverageImagesImageFilter.h.
PixelType
template<class TPixelType> typedef InputImageType::PixelType anima::MCMAverageImagesImageFilter< TPixelType >::PixelType
Definition at line 37 of file animaMCMAverageImagesImageFilter.h.
Pointer
template<class TPixelType> typedef itk::SmartPointer<Self> anima::MCMAverageImagesImageFilter< TPixelType >::Pointer
Definition at line 23 of file animaMCMAverageImagesImageFilter.h.
Self
template<class TPixelType> typedef MCMAverageImagesImageFilter anima::MCMAverageImagesImageFilter< TPixelType >::Self
Standard class type def
Definition at line 19 of file animaMCMAverageImagesImageFilter.h.
Superclass
template<class TPixelType> typedef itk::ImageToImageFilter<InputImageType, OutputImageType > anima::MCMAverageImagesImageFilter< TPixelType >::Superclass
Definition at line 22 of file animaMCMAverageImagesImageFilter.h.
Constructor & Destructor Documentation
MCMAverageImagesImageFilter()
template<class TPixelType> anima::MCMAverageImagesImageFilter< TPixelType >::MCMAverageImagesImageFilter () inline protected
Definition at line 50 of file animaMCMAverageImagesImageFilter.h.
~MCMAverageImagesImageFilter()
template<class TPixelType> virtual anima::MCMAverageImagesImageFilter< TPixelType >::~MCMAverageImagesImageFilter () inline protected virtual
Definition at line 54 of file animaMCMAverageImagesImageFilter.h.
Member Function Documentation
BeforeThreadedGenerateData()
template<class TPixelType > void anima::MCMAverageImagesImageFilter< TPixelType >::BeforeThreadedGenerateData () protected
Definition at line 13 of file animaMCMAverageImagesImageFilter.hxx.
References anima::MCMImage< TPixel, VImageDimension >::GetDescriptionModel().
Referenced by anima::MCMAverageImagesImageFilter< TPixelType >::isZero().
CreateAnother()
template<class TPixelType> virtual::itk::LightObject::Pointer anima::MCMAverageImagesImageFilter< TPixelType >::CreateAnother (void) const
CreateAverager()
template<class TPixelType > MCMAverageImagesImageFilter< TPixelType >::MCMAveragerPointer anima::MCMAverageImagesImageFilter< TPixelType >::CreateAverager () protected virtual
Definition at line 58 of file animaMCMAverageImagesImageFilter.hxx.
References anima::MCMWeightedAverager::New().
Referenced by anima::MCMAverageImagesImageFilter< TPixelType >::isZero().
GetNameOfClass()
template<class TPixelType> virtual const char* anima::MCMAverageImagesImageFilter< TPixelType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetReferenceOutputModel()
template<class TPixelType> MCModelType* anima::MCMAverageImagesImageFilter< TPixelType >::GetReferenceOutputModel () inline
Definition at line 47 of file animaMCMAverageImagesImageFilter.h.
isZero()
template<class TPixelType> bool anima::MCMAverageImagesImageFilter< TPixelType >::isZero (const itk::VariableLengthVector< double > & value) const inline protected
Definition at line 56 of file animaMCMAverageImagesImageFilter.h.
References anima::MCMAverageImagesImageFilter< TPixelType >::BeforeThreadedGenerateData(), anima::MCMAverageImagesImageFilter< TPixelType >::CreateAverager(), and anima::MCMAverageImagesImageFilter< TPixelType >::ThreadedGenerateData().
New()
template<class TPixelType> static Pointer anima::MCMAverageImagesImageFilter< TPixelType >::New () static
Method for creation through the object factory.
SetReferenceOutputModel()
template<class TPixelType > void anima::MCMAverageImagesImageFilter< TPixelType >::SetReferenceOutputModel (MCModelPointer & model)
Definition at line 50 of file animaMCMAverageImagesImageFilter.hxx.
Referenced by main().
ThreadedGenerateData()
template<class TPixelType > void anima::MCMAverageImagesImageFilter< TPixelType >::ThreadedGenerateData (const InputRegionType & region, itk::ThreadIdType threadId) protected
Definition at line 69 of file animaMCMAverageImagesImageFilter.hxx.
Referenced by anima::MCMAverageImagesImageFilter< TPixelType >::isZero().
The documentation for this class was generated from the following files:
animaMCMAverageImagesImageFilter.h
animaMCMAverageImagesImageFilter.hxx