ANIMA: anima::SegmentationMeasuresImageFilter< TLabelImage > Class Template Reference
anima::SegmentationMeasuresImageFilter< TLabelImage > Class Template Reference
#include <animaSegmentationMeasuresImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef TLabelImage::IndexType IndexType
typedef TLabelImage::ConstPointer LabelImageConstPointer
typedef TLabelImage::Pointer LabelImagePointer
typedef TLabelImage LabelImageType
typedef TLabelImage::PixelType LabelType
typedef MapType::const_iterator MapConstIterator
typedef MapType::iterator MapIterator
typedef std::map< LabelType, SegPerfLabelSetMeasures > MapType
typedef itk::SmartPointer< Self > Pointer
typedef itk::NumericTraits< LabelType >::RealType RealType
typedef TLabelImage::RegionType RegionType
typedef SegmentationMeasuresImageFilter Self
typedef TLabelImage::SizeType SizeType
typedef itk::ImageToImageFilter< TLabelImage, TLabelImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
RealType GetDiceCoefficient ()
RealType GetDiceCoefficient (LabelType label)
RealType GetJaccardCoefficient ()
RealType GetJaccardCoefficient (LabelType label)
MapType GetLabelSetMeasures ()
RealType getMeanOverlap ()
RealType getMeanOverlap (LabelType)
virtual const char * GetNameOfClass () const
RealType getNPV ()
RealType getNPV (LabelType)
RealType getPPV ()
RealType getPPV (LabelType)
RealType getRelativeVolumeError ()
RealType getRelativeVolumeError (LabelType)
RealType getSensitivity ()
RealType getSensitivity (LabelType)
const LabelImageType * GetSourceImage (void)
RealType getSpecificity ()
RealType getSpecificity (LabelType)
const LabelImageType * GetTargetImage (void)
RealType getUnionOverlap ()
RealType getUnionOverlap (LabelType)
void SetSourceImage (const LabelImageType *image)
void SetTargetImage (const LabelImageType *image)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = TLabelImage::ImageDimension
Protected Member Functions
void AfterThreadedGenerateData () ITK_OVERRIDE
void BeforeThreadedGenerateData () ITK_OVERRIDE
SegmentationMeasuresImageFilter ()
void ThreadedGenerateData (const RegionType &, itk::ThreadIdType) ITK_OVERRIDE
~SegmentationMeasuresImageFilter ()
Detailed Description
template<typename TLabelImage>
class anima::SegmentationMeasuresImageFilter< TLabelImage >
Definition at line 54 of file animaSegmentationMeasuresImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TLabelImage> typedef itk::SmartPointer<const Self> anima::SegmentationMeasuresImageFilter< TLabelImage >::ConstPointer
Definition at line 61 of file animaSegmentationMeasuresImageFilter.h.
IndexType
template<typename TLabelImage> typedef TLabelImage::IndexType anima::SegmentationMeasuresImageFilter< TLabelImage >::IndexType
Definition at line 76 of file animaSegmentationMeasuresImageFilter.h.
LabelImageConstPointer
template<typename TLabelImage> typedef TLabelImage::ConstPointer anima::SegmentationMeasuresImageFilter< TLabelImage >::LabelImageConstPointer
Definition at line 72 of file animaSegmentationMeasuresImageFilter.h.
LabelImagePointer
template<typename TLabelImage> typedef TLabelImage::Pointer anima::SegmentationMeasuresImageFilter< TLabelImage >::LabelImagePointer
Definition at line 71 of file animaSegmentationMeasuresImageFilter.h.
LabelImageType
template<typename TLabelImage> typedef TLabelImage anima::SegmentationMeasuresImageFilter< TLabelImage >::LabelImageType
Image related typedefs.
Definition at line 70 of file animaSegmentationMeasuresImageFilter.h.
LabelType
template<typename TLabelImage> typedef TLabelImage::PixelType anima::SegmentationMeasuresImageFilter< TLabelImage >::LabelType
Definition at line 78 of file animaSegmentationMeasuresImageFilter.h.
MapConstIterator
template<typename TLabelImage> typedef MapType::const_iterator anima::SegmentationMeasuresImageFilter< TLabelImage >::MapConstIterator
Definition at line 86 of file animaSegmentationMeasuresImageFilter.h.
MapIterator
template<typename TLabelImage> typedef MapType::iterator anima::SegmentationMeasuresImageFilter< TLabelImage >::MapIterator
Definition at line 85 of file animaSegmentationMeasuresImageFilter.h.
MapType
template<typename TLabelImage> typedef std::map<LabelType, SegPerfLabelSetMeasures> anima::SegmentationMeasuresImageFilter< TLabelImage >::MapType
Type of the map used to store data per label
Definition at line 84 of file animaSegmentationMeasuresImageFilter.h.
Pointer
template<typename TLabelImage> typedef itk::SmartPointer<Self> anima::SegmentationMeasuresImageFilter< TLabelImage >::Pointer
Definition at line 60 of file animaSegmentationMeasuresImageFilter.h.
RealType
template<typename TLabelImage> typedef itk::NumericTraits<LabelType>::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::RealType
Type to use for computations.
Definition at line 81 of file animaSegmentationMeasuresImageFilter.h.
RegionType
template<typename TLabelImage> typedef TLabelImage::RegionType anima::SegmentationMeasuresImageFilter< TLabelImage >::RegionType
Definition at line 74 of file animaSegmentationMeasuresImageFilter.h.
Self
template<typename TLabelImage> typedef SegmentationMeasuresImageFilter anima::SegmentationMeasuresImageFilter< TLabelImage >::Self
Standard Self typedef
Definition at line 58 of file animaSegmentationMeasuresImageFilter.h.
SizeType
template<typename TLabelImage> typedef TLabelImage::SizeType anima::SegmentationMeasuresImageFilter< TLabelImage >::SizeType
Definition at line 75 of file animaSegmentationMeasuresImageFilter.h.
Superclass
template<typename TLabelImage> typedef itk::ImageToImageFilter<TLabelImage, TLabelImage> anima::SegmentationMeasuresImageFilter< TLabelImage >::Superclass
Definition at line 59 of file animaSegmentationMeasuresImageFilter.h.
Constructor & Destructor Documentation
SegmentationMeasuresImageFilter()
template<typename TLabelImage > anima::SegmentationMeasuresImageFilter< TLabelImage >::SegmentationMeasuresImageFilter () protected
Definition at line 12 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::BeforeThreadedGenerateData().
~SegmentationMeasuresImageFilter()
template<typename TLabelImage> anima::SegmentationMeasuresImageFilter< TLabelImage >::~SegmentationMeasuresImageFilter () inline protected
Definition at line 166 of file animaSegmentationMeasuresImageFilter.h.
Member Function Documentation
AfterThreadedGenerateData()
template<typename TLabelImage > void anima::SegmentationMeasuresImageFilter< TLabelImage >::AfterThreadedGenerateData () protected
Definition at line 47 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegPerfLabelSetMeasures::m_Source, and anima::SegmentationMeasuresImageFilter< TLabelImage >::ThreadedGenerateData().
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::BeforeThreadedGenerateData().
BeforeThreadedGenerateData()
template<typename TLabelImage > void anima::SegmentationMeasuresImageFilter< TLabelImage >::BeforeThreadedGenerateData () protected
Definition at line 21 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::AfterThreadedGenerateData().
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::SegmentationMeasuresImageFilter().
CreateAnother()
template<typename TLabelImage> virtual::itk::LightObject::Pointer anima::SegmentationMeasuresImageFilter< TLabelImage >::CreateAnother (void) const
GetDiceCoefficient() [1/2]
template<typename TLabelImage> RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::GetDiceCoefficient () inline
Definition at line 149 of file animaSegmentationMeasuresImageFilter.h.
GetDiceCoefficient() [2/2]
template<typename TLabelImage> RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::GetDiceCoefficient (LabelType label) inline
Definition at line 154 of file animaSegmentationMeasuresImageFilter.h.
GetJaccardCoefficient() [1/2]
template<typename TLabelImage> RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::GetJaccardCoefficient () inline
alternative names
Definition at line 144 of file animaSegmentationMeasuresImageFilter.h.
GetJaccardCoefficient() [2/2]
template<typename TLabelImage> RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::GetJaccardCoefficient (LabelType label) inline
Definition at line 159 of file animaSegmentationMeasuresImageFilter.h.
GetLabelSetMeasures()
template<typename TLabelImage> MapType anima::SegmentationMeasuresImageFilter< TLabelImage >::GetLabelSetMeasures () inline
Get the label set measures
Definition at line 116 of file animaSegmentationMeasuresImageFilter.h.
getMeanOverlap() [1/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap ()
Definition at line 168 of file animaSegmentationMeasuresImageFilter.hxx.
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap().
getMeanOverlap() [2/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap (LabelType label)
Definition at line 177 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::getSensitivity().
GetNameOfClass()
template<typename TLabelImage> virtual const char* anima::SegmentationMeasuresImageFilter< TLabelImage >::GetNameOfClass () const virtual
Runtime information support.
getNPV() [1/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getNPV ()
Definition at line 328 of file animaSegmentationMeasuresImageFilter.hxx.
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::getPPV().
getNPV() [2/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getNPV (LabelType label)
Definition at line 367 of file animaSegmentationMeasuresImageFilter.hxx.
getPPV() [1/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getPPV ()
Definition at line 288 of file animaSegmentationMeasuresImageFilter.hxx.
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::getSpecificity().
getPPV() [2/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getPPV (LabelType label)
Definition at line 309 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::getNPV().
getRelativeVolumeError() [1/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getRelativeVolumeError ()
Definition at line 385 of file animaSegmentationMeasuresImageFilter.hxx.
getRelativeVolumeError() [2/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getRelativeVolumeError (LabelType label)
Definition at line 407 of file animaSegmentationMeasuresImageFilter.hxx.
getSensitivity() [1/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getSensitivity ()
tric overlap measuresmeasures over all labels
Definition at line 186 of file animaSegmentationMeasuresImageFilter.hxx.
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap().
getSensitivity() [2/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getSensitivity (LabelType label)
measures over individual labels
Definition at line 208 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::getSpecificity().
GetSourceImage()
template<typename TLabelImage> const LabelImageType* anima::SegmentationMeasuresImageFilter< TLabelImage >::GetSourceImage (void) inline
Get the source image.
Definition at line 104 of file animaSegmentationMeasuresImageFilter.h.
getSpecificity() [1/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getSpecificity ()
Definition at line 227 of file animaSegmentationMeasuresImageFilter.hxx.
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::getSensitivity().
getSpecificity() [2/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getSpecificity (LabelType label)
Definition at line 269 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::getPPV().
GetTargetImage()
template<typename TLabelImage> const LabelImageType* anima::SegmentationMeasuresImageFilter< TLabelImage >::GetTargetImage (void) inline
Get the target image.
Definition at line 110 of file animaSegmentationMeasuresImageFilter.h.
getUnionOverlap() [1/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap ()
Definition at line 127 of file animaSegmentationMeasuresImageFilter.hxx.
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::ThreadedGenerateData().
getUnionOverlap() [2/2]
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType anima::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap (LabelType label)
Definition at line 149 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap().
New()
template<typename TLabelImage> static Pointer anima::SegmentationMeasuresImageFilter< TLabelImage >::New () static
Method for creation through the object factory.
Referenced by anima::SegPerfCAnalyzer::computeHausdorffDist(), anima::SegPerfCAnalyzer::computeITKMeasures(), anima::SegPerfCAnalyzer::computeMeanDist(), and anima::SegPerfCAnalyzer::contourDectection().
SetSourceImage()
template<typename TLabelImage> void anima::SegmentationMeasuresImageFilter< TLabelImage >::SetSourceImage (const LabelImageType * image) inline
Set the source image.
Definition at line 92 of file animaSegmentationMeasuresImageFilter.h.
SetTargetImage()
template<typename TLabelImage> void anima::SegmentationMeasuresImageFilter< TLabelImage >::SetTargetImage (const LabelImageType * image) inline
Set the target image.
Definition at line 98 of file animaSegmentationMeasuresImageFilter.h.
ThreadedGenerateData()
template<typename TLabelImage > void anima::SegmentationMeasuresImageFilter< TLabelImage >::ThreadedGenerateData (const RegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Multi-thread version GenerateData.
Definition at line 79 of file animaSegmentationMeasuresImageFilter.hxx.
References anima::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap().
Referenced by anima::SegmentationMeasuresImageFilter< TLabelImage >::AfterThreadedGenerateData().
Member Data Documentation
ImageDimension
template<typename TLabelImage> const unsigned int anima::SegmentationMeasuresImageFilter< TLabelImage >::ImageDimension = TLabelImage::ImageDimension static
Image related typedefs.
Definition at line 89 of file animaSegmentationMeasuresImageFilter.h.
The documentation for this class was generated from the following files:
animaSegmentationMeasuresImageFilter.h
animaSegmentationMeasuresImageFilter.hxx