ANIMA: anima::SimuBlochSPGRE< TImage > Class Template Reference
anima::SimuBlochSPGRE< TImage > Class Template Reference
#include <animaSimuBlochSP-GRE.h>
Public Types
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef SimuBlochSPGRE Self
typedef itk::ImageToImageFilter< TImage, TImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual float GetFA ()
virtual const char * GetNameOfClass () const
virtual float GetTE ()
virtual float GetTR ()
virtual void SetFA (float _arg)
void SetInputB1 (const TImage *B1)
void SetInputM0 (const TImage *M0)
void SetInputT1 (const TImage *T1)
void SetInputT2s (const TImage *T2s)
virtual void SetTE (float _arg)
virtual void SetTR (float _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
SimuBlochSPGRE ()
virtual void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~SimuBlochSPGRE ()
Detailed Description
template<class TImage>
class anima::SimuBlochSPGRE< TImage >
Definition at line 8 of file animaSimuBlochSP-GRE.h.
Member Typedef Documentation
OutputImageRegionType
template<class TImage > typedef Superclass::OutputImageRegionType anima::SimuBlochSPGRE< TImage >::OutputImageRegionType
Definition at line 16 of file animaSimuBlochSP-GRE.h.
Pointer
template<class TImage > typedef itk::SmartPointer<Self> anima::SimuBlochSPGRE< TImage >::Pointer
Definition at line 14 of file animaSimuBlochSP-GRE.h.
Self
template<class TImage > typedef SimuBlochSPGRE anima::SimuBlochSPGRE< TImage >::Self
Standard class typedefs.
Definition at line 12 of file animaSimuBlochSP-GRE.h.
Superclass
template<class TImage > typedef itk::ImageToImageFilter<TImage, TImage> anima::SimuBlochSPGRE< TImage >::Superclass
Definition at line 13 of file animaSimuBlochSP-GRE.h.
Constructor & Destructor Documentation
SimuBlochSPGRE()
template<class TImage > anima::SimuBlochSPGRE< TImage >::SimuBlochSPGRE () protected
Definition at line 46 of file animaSimuBlochSP-GRE.hxx.
~SimuBlochSPGRE()
template<class TImage > virtual anima::SimuBlochSPGRE< TImage >::~SimuBlochSPGRE () inline protected virtual
Definition at line 47 of file animaSimuBlochSP-GRE.h.
References anima::SimuBlochSPGRE< TImage >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<class TImage > virtual::itk::LightObject::Pointer anima::SimuBlochSPGRE< TImage >::CreateAnother (void) const
GetFA()
template<class TImage > virtual float anima::SimuBlochSPGRE< TImage >::GetFA () virtual
GetNameOfClass()
template<class TImage > virtual const char* anima::SimuBlochSPGRE< TImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetTE()
template<class TImage > virtual float anima::SimuBlochSPGRE< TImage >::GetTE () virtual
GetTR()
template<class TImage > virtual float anima::SimuBlochSPGRE< TImage >::GetTR () virtual
New()
template<class TImage > static Pointer anima::SimuBlochSPGRE< TImage >::New () static
Method for creation through the object factory.
SetFA()
template<class TImage > virtual void anima::SimuBlochSPGRE< TImage >::SetFA (float _arg) virtual
SetInputB1()
template<class TImage > void anima::SimuBlochSPGRE< TImage >::SetInputB1 (const TImage * B1)
B1 inhomogeneity image
Definition at line 70 of file animaSimuBlochSP-GRE.hxx.
References anima::SimuBlochSPGRE< TImage >::ThreadedGenerateData().
SetInputM0()
template<class TImage > void anima::SimuBlochSPGRE< TImage >::SetInputM0 (const TImage * M0)
M0 image / Rho map
Definition at line 64 of file animaSimuBlochSP-GRE.hxx.
SetInputT1()
template<class TImage > void anima::SimuBlochSPGRE< TImage >::SetInputT1 (const TImage * T1)
T1 map
Definition at line 52 of file animaSimuBlochSP-GRE.hxx.
SetInputT2s()
template<class TImage > void anima::SimuBlochSPGRE< TImage >::SetInputT2s (const TImage * T2s)
T2s map
Definition at line 58 of file animaSimuBlochSP-GRE.hxx.
SetTE()
template<class TImage > virtual void anima::SimuBlochSPGRE< TImage >::SetTE (float _arg) virtual
SetTR()
template<class TImage > virtual void anima::SimuBlochSPGRE< TImage >::SetTR (float _arg) virtual
ThreadedGenerateData()
template<class TImage > void anima::SimuBlochSPGRE< TImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected virtual
Does the real work.
Definition at line 77 of file animaSimuBlochSP-GRE.hxx.
Referenced by anima::SimuBlochSPGRE< TImage >::SetInputB1(), and anima::SimuBlochSPGRE< TImage >::~SimuBlochSPGRE().
The documentation for this class was generated from the following files:
animaSimuBlochSP-GRE.h
animaSimuBlochSP-GRE.hxx