ANIMA: anima::KMeansFilter< DataType, PointDimension > Class Template Reference
anima::KMeansFilter< DataType, PointDimension > Class Template Reference
#include <animaKMeansFilter.h>
Public Types
typedef std::vector< VectorType > DataHolderType
typedef std::vector< unsigned int > MembershipType
typedef DataType VectorType
Public Member Functions
void ComputeCentroids ()
bool endConditionReached (MembershipType &oldMemberships)
VectorType GetCentroid (unsigned int i)
MembershipType & GetClassesMemberships ()
unsigned int GetClassMembership (unsigned int i)
unsigned int GetNumberPerClass (unsigned int i)
void InitializeClassesMemberships (MembershipType &classM)
void InitializeKMeansFromData ()
KMeansFilter ()
void ResetClassesMemberships ()
void SetInputData (DataHolderType &data)
void SetMaxIterations (unsigned int mIt)
void SetNumberOfClasses (unsigned int nbC)
void SetVerbose (bool verb)
void Update ()
void UpdateMemberships ()
virtual ~KMeansFilter ()
Detailed Description
template<class DataType, unsigned int PointDimension>
class anima::KMeansFilter< DataType, PointDimension >
Definition at line 8 of file animaKMeansFilter.h.
Member Typedef Documentation
DataHolderType
template<class DataType , unsigned int PointDimension> typedef std::vector< VectorType > anima::KMeansFilter< DataType, PointDimension >::DataHolderType
Definition at line 12 of file animaKMeansFilter.h.
MembershipType
template<class DataType , unsigned int PointDimension> typedef std::vector< unsigned int > anima::KMeansFilter< DataType, PointDimension >::MembershipType
Definition at line 13 of file animaKMeansFilter.h.
VectorType
template<class DataType , unsigned int PointDimension> typedef DataType anima::KMeansFilter< DataType, PointDimension >::VectorType
Definition at line 11 of file animaKMeansFilter.h.
Constructor & Destructor Documentation
KMeansFilter()
template<class DataType , unsigned int PointDimension> anima::KMeansFilter< DataType, PointDimension >::KMeansFilter ()
Definition at line 8 of file animaKMeansFilter.hxx.
~KMeansFilter()
template<class DataType , unsigned int PointDimension> anima::KMeansFilter< DataType, PointDimension >::~KMeansFilter () virtual
Definition at line 24 of file animaKMeansFilter.hxx.
Member Function Documentation
ComputeCentroids()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::ComputeCentroids ()
Definition at line 71 of file animaKMeansFilter.hxx.
Referenced by anima::KMeansFilter< DataType, PointDimension >::SetMaxIterations().
endConditionReached()
template<class DataType , unsigned int PointDimension> bool anima::KMeansFilter< DataType, PointDimension >::endConditionReached (MembershipType & oldMemberships)
Definition at line 121 of file animaKMeansFilter.hxx.
Referenced by anima::KMeansFilter< DataType, PointDimension >::ResetClassesMemberships().
GetCentroid()
template<class DataType , unsigned int PointDimension> VectorType anima::KMeansFilter< DataType, PointDimension >::GetCentroid (unsigned int i) inline
Definition at line 39 of file animaKMeansFilter.h.
GetClassesMemberships()
template<class DataType , unsigned int PointDimension> MembershipType& anima::KMeansFilter< DataType, PointDimension >::GetClassesMemberships () inline
Definition at line 41 of file animaKMeansFilter.h.
GetClassMembership()
template<class DataType , unsigned int PointDimension> unsigned int anima::KMeansFilter< DataType, PointDimension >::GetClassMembership (unsigned int i) inline
Definition at line 40 of file animaKMeansFilter.h.
GetNumberPerClass()
template<class DataType , unsigned int PointDimension> unsigned int anima::KMeansFilter< DataType, PointDimension >::GetNumberPerClass (unsigned int i) inline
Definition at line 43 of file animaKMeansFilter.h.
InitializeClassesMemberships()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::InitializeClassesMemberships (MembershipType & classM)
Definition at line 155 of file animaKMeansFilter.hxx.
Referenced by anima::KMeansFilter< DataType, PointDimension >::SetMaxIterations().
InitializeKMeansFromData()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::InitializeKMeansFromData ()
Definition at line 135 of file animaKMeansFilter.hxx.
Referenced by anima::KMeansFilter< DataType, PointDimension >::SetMaxIterations().
ResetClassesMemberships()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::ResetClassesMemberships () inline
Definition at line 32 of file animaKMeansFilter.h.
References anima::KMeansFilter< DataType, PointDimension >::endConditionReached().
SetInputData()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::SetInputData (DataHolderType & data)
Definition at line 31 of file animaKMeansFilter.hxx.
SetMaxIterations()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::SetMaxIterations (unsigned int mIt) inline
Definition at line 25 of file animaKMeansFilter.h.
References anima::KMeansFilter< DataType, PointDimension >::ComputeCentroids(), anima::KMeansFilter< DataType, PointDimension >::InitializeClassesMemberships(), anima::KMeansFilter< DataType, PointDimension >::InitializeKMeansFromData(), and anima::KMeansFilter< DataType, PointDimension >::UpdateMemberships().
SetNumberOfClasses()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::SetNumberOfClasses (unsigned int nbC) inline
Definition at line 19 of file animaKMeansFilter.h.
SetVerbose()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::SetVerbose (bool verb) inline
Definition at line 35 of file animaKMeansFilter.h.
References anima::KMeansFilter< DataType, PointDimension >::Update().
Update()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::Update ()
Definition at line 43 of file animaKMeansFilter.hxx.
Referenced by anima::KMeansFilter< DataType, PointDimension >::SetVerbose().
UpdateMemberships()
template<class DataType , unsigned int PointDimension> void anima::KMeansFilter< DataType, PointDimension >::UpdateMemberships ()
Definition at line 95 of file animaKMeansFilter.hxx.
Referenced by anima::KMeansFilter< DataType, PointDimension >::SetMaxIterations().
The documentation for this class was generated from the following files:
animaKMeansFilter.h
animaKMeansFilter.hxx