ANIMA: anima::NNLSOptimizer Class Reference
anima::NNLSOptimizer Class Reference
Non negative least squares optimizer. Implements Lawson et al method, of squared problem is activated, assumes we pass AtA et AtB and uses Bro and de Jong method.
#include <animaNNLSOptimizer.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef vnl_matrix< double > MatrixType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef NNLSOptimizer Self
typedef itk::Optimizer Superclass
typedef vnl_vector< double > VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
double GetCurrentResidual ()
virtual const char * GetNameOfClass () const
void SetDataMatrix (MatrixType &data)
void SetPoints (ParametersType &data)
virtual void SetSquaredProblem (bool _arg)
void StartOptimization () ITK_OVERRIDE
Static Public Member Functions
static Pointer New ()
Protected Member Functions
NNLSOptimizer ()
virtual ~NNLSOptimizer () ITK_OVERRIDE
Detailed Description
Non negative least squares optimizer. Implements Lawson et al method, of squared problem is activated, assumes we pass AtA et AtB and uses Bro and de Jong method.
Definition at line 19 of file animaNNLSOptimizer.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::NNLSOptimizer::ConstPointer
Definition at line 26 of file animaNNLSOptimizer.h.
MatrixType
typedef vnl_matrix<double> anima::NNLSOptimizer::MatrixType
Type of the input matrix data
Definition at line 37 of file animaNNLSOptimizer.h.
ParametersType
typedef Superclass::ParametersType anima::NNLSOptimizer::ParametersType
Definition at line 28 of file animaNNLSOptimizer.h.
Pointer
typedef itk::SmartPointer<Self> anima::NNLSOptimizer::Pointer
Definition at line 25 of file animaNNLSOptimizer.h.
Self
typedef NNLSOptimizer anima::NNLSOptimizer::Self
Standard class typedefs.
Definition at line 23 of file animaNNLSOptimizer.h.
Superclass
typedef itk::Optimizer anima::NNLSOptimizer::Superclass
Definition at line 24 of file animaNNLSOptimizer.h.
VectorType
typedef vnl_vector<double> anima::NNLSOptimizer::VectorType
Definition at line 38 of file animaNNLSOptimizer.h.
Constructor & Destructor Documentation
NNLSOptimizer()
anima::NNLSOptimizer::NNLSOptimizer () inline protected
Definition at line 51 of file animaNNLSOptimizer.h.
~NNLSOptimizer()
virtual anima::NNLSOptimizer::~NNLSOptimizer () inline protected virtual
Definition at line 56 of file animaNNLSOptimizer.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::NNLSOptimizer::CreateAnother (void) const
GetCurrentResidual()
double anima::NNLSOptimizer::GetCurrentResidual ()
Definition at line 234 of file animaNNLSOptimizer.cxx.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovRegularizedSolution().
GetNameOfClass()
virtual const char* anima::NNLSOptimizer::GetNameOfClass () const virtual
Run-time type information (and related methods).
New()
static Pointer anima::NNLSOptimizer::New () static
Method for creation through the object factory.
Referenced by anima::GaussianMCMVariableProjectionCost::GaussianMCMVariableProjectionCost(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks().
SetDataMatrix()
void anima::NNLSOptimizer::SetDataMatrix (MatrixType & data) inline
Definition at line 43 of file animaNNLSOptimizer.h.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovRegularizedSolution().
SetPoints()
void anima::NNLSOptimizer::SetPoints (ParametersType & data) inline
Definition at line 44 of file animaNNLSOptimizer.h.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovRegularizedSolution().
SetSquaredProblem()
virtual void anima::NNLSOptimizer::SetSquaredProblem (bool _arg) virtual
StartOptimization()
void anima::NNLSOptimizer::StartOptimization ()
Start optimization.
Definition at line 9 of file animaNNLSOptimizer.cxx.
References anima::CholeskyDecomposition::PerformDecomposition(), anima::CholeskyDecomposition::SetInputMatrix(), and anima::CholeskyDecomposition::SolveLinearSystemInPlace().
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovRegularizedSolution().
The documentation for this class was generated from the following files:
animaNNLSOptimizer.h
animaNNLSOptimizer.cxx