ANIMA: anima::ApproximateMCMSmoothingCostFunction Class Reference
anima::ApproximateMCMSmoothingCostFunction Class Reference
#include <animaApproximateMCMSmoothingCostFunction.h>
Public Types
typedef anima::BaseCompartment::Pointer BaseCompartmentPointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef MCModelType::Vector3DType GradientType
typedef anima::MultiCompartmentModel MCModelType
typedef MCModelType::Pointer MCMPointer
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef ApproximateMCMSmoothingCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
typedef anima::BaseCompartment::Vector3DType Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
void SetBigDelta (double val)
void SetBValueWeightIndexes (const std::vector< unsigned int > &val)
void SetGradientDirections (const std::vector< GradientType > &val)
void SetGradientStrengths (const std::vector< double > &val)
void SetMovingModels (const std::vector< MCMPointer > &movingModels, const std::vector< GradientType > &gradients, const double &smallDelta, const double &bigDelta, const std::vector< double > &gradientStrengths)
virtual void SetParameterScale (double _arg)
void SetReferenceModels (const std::vector< MCMPointer > &refModels, const std::vector< GradientType > &gradients, const double &smallDelta, const double &bigDelta, const std::vector< double > &gradientStrengths)
void SetSmallDelta (double val)
void SetSphereWeights (const std::vector< double > &val)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
ApproximateMCMSmoothingCostFunction ()
virtual ~ApproximateMCMSmoothingCostFunction ()
Detailed Description
Definition at line 11 of file animaApproximateMCMSmoothingCostFunction.h.
Member Typedef Documentation
BaseCompartmentPointer
typedef anima::BaseCompartment::Pointer anima::ApproximateMCMSmoothingCostFunction::BaseCompartmentPointer
Definition at line 32 of file animaApproximateMCMSmoothingCostFunction.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::ApproximateMCMSmoothingCostFunction::ConstPointer
Definition at line 18 of file animaApproximateMCMSmoothingCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::ApproximateMCMSmoothingCostFunction::DerivativeType
Definition at line 26 of file animaApproximateMCMSmoothingCostFunction.h.
GradientType
typedef MCModelType::Vector3DType anima::ApproximateMCMSmoothingCostFunction::GradientType
Definition at line 31 of file animaApproximateMCMSmoothingCostFunction.h.
MCModelType
typedef anima::MultiCompartmentModel anima::ApproximateMCMSmoothingCostFunction::MCModelType
Definition at line 29 of file animaApproximateMCMSmoothingCostFunction.h.
MCMPointer
typedef MCModelType::Pointer anima::ApproximateMCMSmoothingCostFunction::MCMPointer
Definition at line 30 of file animaApproximateMCMSmoothingCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::ApproximateMCMSmoothingCostFunction::MeasureType
Definition at line 25 of file animaApproximateMCMSmoothingCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::ApproximateMCMSmoothingCostFunction::ParametersType
Definition at line 27 of file animaApproximateMCMSmoothingCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::ApproximateMCMSmoothingCostFunction::Pointer
Definition at line 17 of file animaApproximateMCMSmoothingCostFunction.h.
Self
typedef ApproximateMCMSmoothingCostFunction anima::ApproximateMCMSmoothingCostFunction::Self
Standard class typedefs.
Definition at line 15 of file animaApproximateMCMSmoothingCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::ApproximateMCMSmoothingCostFunction::Superclass
Definition at line 16 of file animaApproximateMCMSmoothingCostFunction.h.
Vector3DType
typedef anima::BaseCompartment::Vector3DType anima::ApproximateMCMSmoothingCostFunction::Vector3DType
Definition at line 33 of file animaApproximateMCMSmoothingCostFunction.h.
Constructor & Destructor Documentation
ApproximateMCMSmoothingCostFunction()
anima::ApproximateMCMSmoothingCostFunction::ApproximateMCMSmoothingCostFunction () inline protected
Definition at line 56 of file animaApproximateMCMSmoothingCostFunction.h.
References anima::DiffusionBigDelta, and anima::DiffusionSmallDelta.
~ApproximateMCMSmoothingCostFunction()
virtual anima::ApproximateMCMSmoothingCostFunction::~ApproximateMCMSmoothingCostFunction () inline protected virtual
Definition at line 65 of file animaApproximateMCMSmoothingCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::ApproximateMCMSmoothingCostFunction::CreateAnother (void) const
GetDerivative()
void anima::ApproximateMCMSmoothingCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 151 of file animaApproximateMCMSmoothingCostFunction.cxx.
References anima::GetBValueFromAcquisitionParameters().
Referenced by GetValue().
GetNameOfClass()
virtual const char* anima::ApproximateMCMSmoothingCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::ApproximateMCMSmoothingCostFunction::GetNumberOfParameters () const inline
Definition at line 53 of file animaApproximateMCMSmoothingCostFunction.h.
GetValue()
ApproximateMCMSmoothingCostFunction::MeasureType anima::ApproximateMCMSmoothingCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 100 of file animaApproximateMCMSmoothingCostFunction.cxx.
References anima::GetBValueFromAcquisitionParameters(), and GetDerivative().
Referenced by SetSphereWeights().
New()
static Pointer anima::ApproximateMCMSmoothingCostFunction::New () static
SetBigDelta()
void anima::ApproximateMCMSmoothingCostFunction::SetBigDelta (double val)
Definition at line 60 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetGradientStrengths().
Referenced by SetSmallDelta().
SetBValueWeightIndexes()
void anima::ApproximateMCMSmoothingCostFunction::SetBValueWeightIndexes (const std::vector< unsigned int > & val)
Definition at line 84 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetSphereWeights().
Referenced by SetGradientDirections().
SetGradientDirections()
void anima::ApproximateMCMSmoothingCostFunction::SetGradientDirections (const std::vector< GradientType > & val)
Definition at line 76 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetBValueWeightIndexes().
Referenced by SetGradientStrengths().
SetGradientStrengths()
void anima::ApproximateMCMSmoothingCostFunction::SetGradientStrengths (const std::vector< double > & val)
Definition at line 68 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetGradientDirections().
Referenced by SetBigDelta().
SetMovingModels()
void anima::ApproximateMCMSmoothingCostFunction::SetMovingModels (const std::vector< MCMPointer > & movingModels, const std::vector< GradientType > & gradients, const double & smallDelta, const double & bigDelta, const std::vector< double > & gradientStrengths)
Definition at line 30 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetSmallDelta().
Referenced by SetReferenceModels().
SetParameterScale()
virtual void anima::ApproximateMCMSmoothingCostFunction::SetParameterScale (double _arg) virtual
SetReferenceModels()
void anima::ApproximateMCMSmoothingCostFunction::SetReferenceModels (const std::vector< MCMPointer > & refModels, const std::vector< GradientType > & gradients, const double & smallDelta, const double & bigDelta, const std::vector< double > & gradientStrengths)
Definition at line 8 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetMovingModels().
SetSmallDelta()
void anima::ApproximateMCMSmoothingCostFunction::SetSmallDelta (double val)
Definition at line 52 of file animaApproximateMCMSmoothingCostFunction.cxx.
References SetBigDelta().
Referenced by SetMovingModels().
SetSphereWeights()
void anima::ApproximateMCMSmoothingCostFunction::SetSphereWeights (const std::vector< double > & val)
Definition at line 92 of file animaApproximateMCMSmoothingCostFunction.cxx.
References GetValue().
Referenced by SetBValueWeightIndexes().
The documentation for this class was generated from the following files:
animaApproximateMCMSmoothingCostFunction.h
animaApproximateMCMSmoothingCostFunction.cxx