ANIMA: anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage > Class Template Reference
anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage > Class Template Reference
#include <animaFastCorrelationImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, TFixedImage::ImageDimension > ContinuousIndexType
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef Superclass::GradientPixelType GradientPixelType
typedef Superclass::InputPointType InputPointType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::RealType RealType
typedef FastCorrelationImageToImageMetric Self
typedef itk::ImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef Superclass::TransformJacobianType TransformJacobianType
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
void GetDerivative (const TransformParametersType &parameters, DerivativeType &Derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &Value, DerivativeType &Derivative) const ITK_OVERRIDE
void PreComputeFixedValues ()
virtual void SetScaleIntensities (bool _arg)
virtual void SetSquaredCorrelation (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
FastCorrelationImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~FastCorrelationImageToImageMetric ()
Detailed Description
template<class TFixedImage, class TMovingImage>
class anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >
Definition at line 11 of file animaFastCorrelationImageToImageMetric.h.
Member Typedef Documentation
ConstPointer
template<class TFixedImage, class TMovingImage> typedef itk::SmartPointer<const Self> anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::ConstPointer
Definition at line 20 of file animaFastCorrelationImageToImageMetric.h.
ContinuousIndexType
template<class TFixedImage, class TMovingImage> typedef itk::ContinuousIndex<double,TFixedImage::ImageDimension> anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::ContinuousIndexType
Definition at line 38 of file animaFastCorrelationImageToImageMetric.h.
DerivativeType
template<class TFixedImage, class TMovingImage> typedef Superclass::DerivativeType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::DerivativeType
Definition at line 41 of file animaFastCorrelationImageToImageMetric.h.
FixedImageConstPointer
template<class TFixedImage, class TMovingImage> typedef Superclass::FixedImageConstPointer anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::FixedImageConstPointer
Definition at line 44 of file animaFastCorrelationImageToImageMetric.h.
FixedImageType
template<class TFixedImage, class TMovingImage> typedef Superclass::FixedImageType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::FixedImageType
Definition at line 42 of file animaFastCorrelationImageToImageMetric.h.
GradientPixelType
template<class TFixedImage, class TMovingImage> typedef Superclass::GradientPixelType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GradientPixelType
Definition at line 35 of file animaFastCorrelationImageToImageMetric.h.
InputPointType
template<class TFixedImage, class TMovingImage> typedef Superclass::InputPointType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::InputPointType
Definition at line 37 of file animaFastCorrelationImageToImageMetric.h.
MeasureType
template<class TFixedImage, class TMovingImage> typedef Superclass::MeasureType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::MeasureType
Definition at line 40 of file animaFastCorrelationImageToImageMetric.h.
MovingImageConstPointer
template<class TFixedImage, class TMovingImage> typedef Superclass::MovingImageConstPointer anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::MovingImageConstPointer
Definition at line 45 of file animaFastCorrelationImageToImageMetric.h.
MovingImageType
template<class TFixedImage, class TMovingImage> typedef Superclass::MovingImageType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::MovingImageType
Definition at line 43 of file animaFastCorrelationImageToImageMetric.h.
OutputPointType
template<class TFixedImage, class TMovingImage> typedef Superclass::OutputPointType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::OutputPointType
Definition at line 36 of file animaFastCorrelationImageToImageMetric.h.
Pointer
template<class TFixedImage, class TMovingImage> typedef itk::SmartPointer<Self> anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::Pointer
Definition at line 19 of file animaFastCorrelationImageToImageMetric.h.
RealType
template<class TFixedImage, class TMovingImage> typedef Superclass::RealType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::RealType
Types transferred from the base class
Definition at line 26 of file animaFastCorrelationImageToImageMetric.h.
Self
template<class TFixedImage, class TMovingImage> typedef FastCorrelationImageToImageMetric anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::Self
Standard class typedefs.
Definition at line 17 of file animaFastCorrelationImageToImageMetric.h.
Superclass
template<class TFixedImage, class TMovingImage> typedef itk::ImageToImageMetric<TFixedImage, TMovingImage > anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::Superclass
Definition at line 18 of file animaFastCorrelationImageToImageMetric.h.
TransformJacobianType
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformJacobianType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::TransformJacobianType
Definition at line 34 of file animaFastCorrelationImageToImageMetric.h.
TransformParametersType
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformParametersType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::TransformParametersType
Definition at line 33 of file animaFastCorrelationImageToImageMetric.h.
TransformPointer
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformPointer anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::TransformPointer
Definition at line 32 of file animaFastCorrelationImageToImageMetric.h.
TransformType
template<class TFixedImage, class TMovingImage> typedef Superclass::TransformType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::TransformType
Definition at line 31 of file animaFastCorrelationImageToImageMetric.h.
Constructor & Destructor Documentation
FastCorrelationImageToImageMetric()
template<class TFixedImage , class TMovingImage > anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::FastCorrelationImageToImageMetric () protected
Constructor
Definition at line 14 of file animaFastCorrelationImageToImageMetric.hxx.
References anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetValue().
Referenced by anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::~FastCorrelationImageToImageMetric().
~FastCorrelationImageToImageMetric()
template<class TFixedImage, class TMovingImage> virtual anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::~FastCorrelationImageToImageMetric () inline protected virtual
Definition at line 65 of file animaFastCorrelationImageToImageMetric.h.
References anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::FastCorrelationImageToImageMetric(), and anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::PrintSelf().
Member Function Documentation
CreateAnother()
template<class TFixedImage, class TMovingImage> virtual::itk::LightObject::Pointer anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::CreateAnother (void) const
GetDerivative()
template<class TFixedImage , class TMovingImage > void anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetDerivative (const TransformParametersType & parameters, DerivativeType & derivative) const
Get the derivatives of the match measure.
Get the Derivative Measure
Definition at line 157 of file animaFastCorrelationImageToImageMetric.hxx.
References anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetValueAndDerivative().
Referenced by anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::PreComputeFixedValues().
GetNameOfClass()
template<class TFixedImage, class TMovingImage> virtual const char* anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetValue()
template<class TFixedImage , class TMovingImage > FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::MeasureType anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Get the match Measure
Definition at line 30 of file animaFastCorrelationImageToImageMetric.hxx.
References anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::PreComputeFixedValues().
Referenced by anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::FastCorrelationImageToImageMetric().
GetValueAndDerivative()
template<class TFixedImage , class TMovingImage > void anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetValueAndDerivative (const TransformParametersType & parameters, MeasureType & Value, DerivativeType & Derivative) const
Get value and derivatives for multiple valued optimizers.
Definition at line 169 of file animaFastCorrelationImageToImageMetric.hxx.
References anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::PrintSelf().
Referenced by anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetDerivative().
New()
template<class TFixedImage, class TMovingImage> static Pointer anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::New () static
Method for creation through the object factory.
PreComputeFixedValues()
template<class TFixedImage , class TMovingImage > void anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::PreComputeFixedValues ()
Definition at line 105 of file animaFastCorrelationImageToImageMetric.hxx.
References anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetDerivative().
Referenced by anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetValue().
PrintSelf()
template<class TFixedImage , class TMovingImage > void anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
Definition at line 178 of file animaFastCorrelationImageToImageMetric.hxx.
Referenced by anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::GetValueAndDerivative(), and anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::~FastCorrelationImageToImageMetric().
SetScaleIntensities()
template<class TFixedImage, class TMovingImage> virtual void anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::SetScaleIntensities (bool _arg) virtual
SetSquaredCorrelation()
template<class TFixedImage, class TMovingImage> virtual void anima::FastCorrelationImageToImageMetric< TFixedImage, TMovingImage >::SetSquaredCorrelation (bool _arg) virtual
The documentation for this class was generated from the following files:
animaFastCorrelationImageToImageMetric.h
animaFastCorrelationImageToImageMetric.hxx