ANIMA: anima::BaseTractographyImageFilter Class Reference
anima::BaseTractographyImageFilter Class Reference abstract
#include <animaBaseTractographyImageFilter.h>
Classes
struct trackerArguments
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, 3 > ContinuousIndexType
typedef std::vector< std::pair< FiberProgressType, FiberType > > FiberProcessVectorType
enum FiberProgressType {
Forward,
Backward,
Both
}
typedef std::vector< PointType > FiberType
typedef MaskImageType::IndexType IndexType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned short, 3 > MaskImageType
typedef ModelImageType::Pointer ModelImagePointer
typedef itk::VectorImage< float, 3 > ModelImageType
typedef itk::SmartPointer< Self > Pointer
typedef MaskImageType::PointType PointType
typedef ModelImageType::RegionType RegionType
typedef BaseTractographyImageFilter Self
typedef itk::ProcessObject Superclass
typedef ModelImageType::PixelType VectorType
Public Member Functions
void createVTKOutput (std::vector< std::vector< PointType > > &filteredFibers)
ModelImageType * GetInputImage ()
double GetMinimalModelWeight ()
virtual const char * GetNameOfClass () const
vtkPolyData * GetOutput ()
void SetComputeLocalColors (bool flag)
void SetCutMask (MaskImageType *mask)
void SetFilteringMask (MaskImageType *mask)
void SetForbiddenMask (MaskImageType *mask)
virtual void SetInputImage (ModelImageType *input)
void SetMaxFiberAngle (double num)
void SetMaxLengthFiber (double num)
void SetMinimalModelWeight (double num)
void SetMinLengthFiber (double num)
void SetNumberOfFibersPerPixel (unsigned int num)
void SetSeedingMask (MaskImageType *mask)
void SetStepProgression (double num)
void Update () ITK_OVERRIDE
Protected Types
typedef itk::ImageBase< ModelImageType::ImageDimension > ImageBaseType
Protected Member Functions
BaseTractographyImageFilter ()
bool CheckIndexInImageBounds (IndexType &index, ImageBaseType *testImage)
virtual bool CheckIndexInImageBounds (ContinuousIndexType &index)=0
virtual bool CheckModelCompatibility (VectorType &modelValue, itk::ThreadIdType threadId)=0
virtual void ComputeAdditionalScalarMaps ()
FiberProcessVectorType ComputeFiber (FiberType &fiber, FiberProgressType ways, itk::ThreadIdType threadId)
std::vector< FiberType > FilterOutputFibers (std::vector< FiberType > &fibers)
virtual PointType GetModelPrincipalDirection (VectorType &modelValue, bool is2d, itk::ThreadIdType threadId)=0
virtual void GetModelValue (ContinuousIndexType &index, VectorType &modelValue)=0
Computes value of model from data. May use SNR and previous model value to perform smart interpolation. Replaces SNR and modelValue by the outputs.
virtual PointType GetNextDirection (PointType &previousDirection, VectorType &modelValue, bool is2d, itk::ThreadIdType threadId)=0
bool isZero (VectorType &value)
virtual void PrepareTractography ()
void ThreadedTrackComputer (unsigned int numThread, std::vector< FiberType > &resultFibers, unsigned int startSeedIndex, unsigned int endSeedIndex)
void ThreadTrack (unsigned int numThread, std::vector< FiberType > &resultFibers)
virtual ~BaseTractographyImageFilter ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadTracker (void *arg)
Detailed Description
Definition at line 20 of file animaBaseTractographyImageFilter.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::BaseTractographyImageFilter::ConstPointer
Definition at line 28 of file animaBaseTractographyImageFilter.h.
ContinuousIndexType
typedef itk::ContinuousIndex<double, 3> anima::BaseTractographyImageFilter::ContinuousIndexType
Definition at line 42 of file animaBaseTractographyImageFilter.h.
FiberProcessVectorType
typedef std::vector<std::pair < FiberProgressType, FiberType > > anima::BaseTractographyImageFilter::FiberProcessVectorType
Definition at line 50 of file animaBaseTractographyImageFilter.h.
FiberType
typedef std::vector<PointType> anima::BaseTractographyImageFilter::FiberType
Definition at line 49 of file animaBaseTractographyImageFilter.h.
ImageBaseType
typedef itk::ImageBase<ModelImageType::ImageDimension> anima::BaseTractographyImageFilter::ImageBaseType protected
Definition at line 98 of file animaBaseTractographyImageFilter.h.
IndexType
typedef MaskImageType::IndexType anima::BaseTractographyImageFilter::IndexType
Definition at line 47 of file animaBaseTractographyImageFilter.h.
MaskImagePointer
typedef MaskImageType::Pointer anima::BaseTractographyImageFilter::MaskImagePointer
Definition at line 45 of file animaBaseTractographyImageFilter.h.
MaskImageType
typedef itk::Image<unsigned short, 3> anima::BaseTractographyImageFilter::MaskImageType
Definition at line 44 of file animaBaseTractographyImageFilter.h.
ModelImagePointer
typedef ModelImageType::Pointer anima::BaseTractographyImageFilter::ModelImagePointer
Definition at line 39 of file animaBaseTractographyImageFilter.h.
ModelImageType
typedef itk::VectorImage<float, 3> anima::BaseTractographyImageFilter::ModelImageType
Definition at line 38 of file animaBaseTractographyImageFilter.h.
Pointer
typedef itk::SmartPointer<Self> anima::BaseTractographyImageFilter::Pointer
Definition at line 27 of file animaBaseTractographyImageFilter.h.
PointType
typedef MaskImageType::PointType anima::BaseTractographyImageFilter::PointType
Definition at line 46 of file animaBaseTractographyImageFilter.h.
RegionType
typedef ModelImageType::RegionType anima::BaseTractographyImageFilter::RegionType
Definition at line 41 of file animaBaseTractographyImageFilter.h.
Self
typedef BaseTractographyImageFilter anima::BaseTractographyImageFilter::Self
SmartPointer typedef support
Definition at line 24 of file animaBaseTractographyImageFilter.h.
Superclass
typedef itk::ProcessObject anima::BaseTractographyImageFilter::Superclass
Definition at line 25 of file animaBaseTractographyImageFilter.h.
VectorType
typedef ModelImageType::PixelType anima::BaseTractographyImageFilter::VectorType
Definition at line 40 of file animaBaseTractographyImageFilter.h.
Member Enumeration Documentation
FiberProgressType
enum anima::BaseTractographyImageFilter::FiberProgressType
Enumerator
Forward
Backward
Both
Definition at line 32 of file animaBaseTractographyImageFilter.h.
Constructor & Destructor Documentation
BaseTractographyImageFilter()
anima::BaseTractographyImageFilter::BaseTractographyImageFilter () protected
Definition at line 15 of file animaBaseTractographyImageFilter.cxx.
~BaseTractographyImageFilter()
anima::BaseTractographyImageFilter::~BaseTractographyImageFilter () protected virtual
Definition at line 30 of file animaBaseTractographyImageFilter.cxx.
Member Function Documentation
CheckIndexInImageBounds() [1/2]
bool anima::BaseTractographyImageFilter::CheckIndexInImageBounds (IndexType & index, ImageBaseType * testImage) protected
Definition at line 618 of file animaBaseTractographyImageFilter.cxx.
Referenced by ComputeFiber().
CheckIndexInImageBounds() [2/2]
virtual bool anima::BaseTractographyImageFilter::CheckIndexInImageBounds (ContinuousIndexType & index) protected pure virtual
Implemented in anima::dtiTractographyImageFilter.
CheckModelCompatibility()
virtual bool anima::BaseTractographyImageFilter::CheckModelCompatibility (VectorType & modelValue, itk::ThreadIdType threadId) protected pure virtual
Implemented in anima::dtiTractographyImageFilter.
Referenced by ComputeFiber().
ComputeAdditionalScalarMaps()
virtual void anima::BaseTractographyImageFilter::ComputeAdditionalScalarMaps () inline protected virtual
Reimplemented in anima::dtiTractographyImageFilter.
Definition at line 108 of file animaBaseTractographyImageFilter.h.
Referenced by createVTKOutput().
ComputeFiber()
BaseTractographyImageFilter::FiberProcessVectorType anima::BaseTractographyImageFilter::ComputeFiber (BaseTractographyImageFilter::FiberType & fiber, BaseTractographyImageFilter::FiberProgressType ways, itk::ThreadIdType threadId) protected
Definition at line 368 of file animaBaseTractographyImageFilter.cxx.
References Backward, Both, CheckIndexInImageBounds(), CheckModelCompatibility(), anima::ComputeOrientationAngle(), anima::ComputeScalarProduct(), Forward, GetModelPrincipalDirection(), GetModelValue(), GetNextDirection(), isZero(), and anima::Revert().
Referenced by ThreadedTrackComputer().
createVTKOutput()
void anima::BaseTractographyImageFilter::createVTKOutput (std::vector< std::vector< PointType > > & filteredFibers)
Definition at line 288 of file animaBaseTractographyImageFilter.cxx.
References ComputeAdditionalScalarMaps().
Referenced by Update().
FilterOutputFibers()
std::vector< std::vector< BaseTractographyImageFilter::PointType > > anima::BaseTractographyImageFilter::FilterOutputFibers (std::vector< FiberType > & fibers) protected
Definition at line 237 of file animaBaseTractographyImageFilter.cxx.
Referenced by Update().
GetInputImage()
ModelImageType* anima::BaseTractographyImageFilter::GetInputImage () inline
Definition at line 58 of file animaBaseTractographyImageFilter.h.
Referenced by anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps(), and anima::dtiTractographyImageFilter::SetInputImage().
GetMinimalModelWeight()
double anima::BaseTractographyImageFilter::GetMinimalModelWeight () inline
Definition at line 74 of file animaBaseTractographyImageFilter.h.
Referenced by anima::dtiTractographyImageFilter::GetNextDirection().
GetModelPrincipalDirection()
virtual PointType anima::BaseTractographyImageFilter::GetModelPrincipalDirection (VectorType & modelValue, bool is2d, itk::ThreadIdType threadId) protected pure virtual
Implemented in anima::dtiTractographyImageFilter.
Referenced by ComputeFiber().
GetModelValue()
virtual void anima::BaseTractographyImageFilter::GetModelValue (ContinuousIndexType & index, VectorType & modelValue) protected pure virtual
Computes value of model from data. May use SNR and previous model value to perform smart interpolation. Replaces SNR and modelValue by the outputs.
Implemented in anima::dtiTractographyImageFilter.
Referenced by ComputeFiber().
GetNameOfClass()
virtual const char* anima::BaseTractographyImageFilter::GetNameOfClass () const virtual
Reimplemented in anima::dtiTractographyImageFilter.
GetNextDirection()
virtual PointType anima::BaseTractographyImageFilter::GetNextDirection (PointType & previousDirection, VectorType & modelValue, bool is2d, itk::ThreadIdType threadId) protected pure virtual
Implemented in anima::dtiTractographyImageFilter.
Referenced by ComputeFiber().
GetOutput()
vtkPolyData* anima::BaseTractographyImageFilter::GetOutput () inline
Definition at line 80 of file animaBaseTractographyImageFilter.h.
Referenced by anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps().
isZero()
bool anima::BaseTractographyImageFilter::isZero (VectorType & value) protected
Definition at line 631 of file animaBaseTractographyImageFilter.cxx.
Referenced by ComputeFiber().
PrepareTractography()
void anima::BaseTractographyImageFilter::PrepareTractography () protected virtual
Definition at line 77 of file animaBaseTractographyImageFilter.cxx.
References Both.
Referenced by Update().
SetComputeLocalColors()
void anima::BaseTractographyImageFilter::SetComputeLocalColors (bool flag) inline
Definition at line 78 of file animaBaseTractographyImageFilter.h.
SetCutMask()
void anima::BaseTractographyImageFilter::SetCutMask (MaskImageType * mask) inline
Definition at line 63 of file animaBaseTractographyImageFilter.h.
SetFilteringMask()
void anima::BaseTractographyImageFilter::SetFilteringMask (MaskImageType * mask) inline
Definition at line 61 of file animaBaseTractographyImageFilter.h.
SetForbiddenMask()
void anima::BaseTractographyImageFilter::SetForbiddenMask (MaskImageType * mask) inline
Definition at line 62 of file animaBaseTractographyImageFilter.h.
SetInputImage()
virtual void anima::BaseTractographyImageFilter::SetInputImage (ModelImageType * input) inline virtual
Reimplemented in anima::dtiTractographyImageFilter.
Definition at line 57 of file animaBaseTractographyImageFilter.h.
Referenced by anima::dtiTractographyImageFilter::SetInputImage().
SetMaxFiberAngle()
void anima::BaseTractographyImageFilter::SetMaxFiberAngle (double num) inline
Definition at line 69 of file animaBaseTractographyImageFilter.h.
SetMaxLengthFiber()
void anima::BaseTractographyImageFilter::SetMaxLengthFiber (double num) inline
Definition at line 71 of file animaBaseTractographyImageFilter.h.
SetMinimalModelWeight()
void anima::BaseTractographyImageFilter::SetMinimalModelWeight (double num) inline
Definition at line 73 of file animaBaseTractographyImageFilter.h.
SetMinLengthFiber()
void anima::BaseTractographyImageFilter::SetMinLengthFiber (double num) inline
Definition at line 70 of file animaBaseTractographyImageFilter.h.
SetNumberOfFibersPerPixel()
void anima::BaseTractographyImageFilter::SetNumberOfFibersPerPixel (unsigned int num) inline
Definition at line 65 of file animaBaseTractographyImageFilter.h.
SetSeedingMask()
void anima::BaseTractographyImageFilter::SetSeedingMask (MaskImageType * mask) inline
Definition at line 60 of file animaBaseTractographyImageFilter.h.
SetStepProgression()
void anima::BaseTractographyImageFilter::SetStepProgression (double num) inline
Definition at line 67 of file animaBaseTractographyImageFilter.h.
ThreadedTrackComputer()
void anima::BaseTractographyImageFilter::ThreadedTrackComputer (unsigned int numThread, std::vector< FiberType > & resultFibers, unsigned int startSeedIndex, unsigned int endSeedIndex) protected
Definition at line 222 of file animaBaseTractographyImageFilter.cxx.
References ComputeFiber().
Referenced by ThreadTrack().
ThreadTrack()
void anima::BaseTractographyImageFilter::ThreadTrack (unsigned int numThread, std::vector< FiberType > & resultFibers) protected
Definition at line 185 of file animaBaseTractographyImageFilter.cxx.
References ThreadedTrackComputer().
Referenced by ThreadTracker().
ThreadTracker()
ITK_THREAD_RETURN_TYPE anima::BaseTractographyImageFilter::ThreadTracker (void * arg) static protected
Definition at line 174 of file animaBaseTractographyImageFilter.cxx.
References anima::BaseTractographyImageFilter::trackerArguments::resultFibersFromThreads, ThreadTrack(), and anima::BaseTractographyImageFilter::trackerArguments::trackerPtr.
Referenced by Update().
Update()
void anima::BaseTractographyImageFilter::Update ()
Definition at line 36 of file animaBaseTractographyImageFilter.cxx.
References createVTKOutput(), FilterOutputFibers(), PrepareTractography(), anima::BaseTractographyImageFilter::trackerArguments::resultFibersFromThreads, ThreadTracker(), and anima::BaseTractographyImageFilter::trackerArguments::trackerPtr.
The documentation for this class was generated from the following files:
animaBaseTractographyImageFilter.h
animaBaseTractographyImageFilter.cxx