ANIMA: anima::GraphCutFilter< TInput, TOutput > Class Template Reference
anima::GraphCutFilter< TInput, TOutput > Class Template Reference
Class performing grah cut segmentation. First the sources and sinks probabilities maps are computed using the TLinkFilter. Then the Graph3DFilter is called to perform the graph cut.
#include <animaGraphCutFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::VariableSizeMatrix< NumericType > FloatVariableSizeMatrixType
typedef double NumericType
typedef TOutput::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef double PixelTypeD
typedef unsigned char PixelTypeUC
typedef itk::SmartPointer< Self > Pointer
typedef GraphCutFilter Self
typedef itk::ImageToImageFilter< TInput, TOutput > Superclass
typedef itk::Image< PixelTypeUC, 3 > TMask
typedef TMask::Pointer TMaskPointer
typedef itk::Image< PixelTypeD, 3 > TSeedProba
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual float GetAlpha ()
virtual float GetMultiVarSinks ()
virtual float GetMultiVarSources ()
virtual const char * GetNameOfClass () const
OutputImagePointer GetOutput ()
OutputImagePointer GetOutputBackground ()
std::string GetOutputFilename ()
virtual float GetSigma ()
TLinkMode GetTLinkMode ()
virtual bool GetUseSpectralGradient ()
virtual bool GetVerbose ()
virtual void SetAlpha (float _arg)
void SetInputImage (unsigned int i, const TInput *image)
void SetInputSeedSinksMask (const TMask *mask)
void SetInputSeedSinksProba (const TSeedProba *mask)
void SetInputSeedSourcesMask (const TMask *mask)
void SetInputSeedSourcesProba (const TSeedProba *mask)
void SetMask (const TMask *mask)
void SetMatrix (FloatVariableSizeMatrixType mat)
void SetMatrixGradFilename (std::string mat)
virtual void SetMultiVarSinks (float _arg)
virtual void SetMultiVarSources (float _arg)
void SetOutputFilename (std::string filename)
virtual void SetSigma (float _arg)
void SetTLinkMode (TLinkMode m)
void SetTol (const double tol)
virtual void SetUseSpectralGradient (bool _arg)
virtual void SetVerbose (bool _arg)
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Types
typedef Graph3DFilter< TInput, TOutput > Graph3DFilterType
typedef TLinksFilter< TInput, TSeedProba > TLinksFilterType
Protected Member Functions
void GenerateData () ITK_OVERRIDE
TMask::ConstPointer GetInputSeedSinksMask ()
TSeedProba::ConstPointer GetInputSeedSinksProba ()
TMask::ConstPointer GetInputSeedSourcesMask ()
TSeedProba::ConstPointer GetInputSeedSourcesProba ()
TMask::ConstPointer GetMask ()
FloatVariableSizeMatrixType GetMatrix (void)
std::string GetMatrixGradFilename (void)
GraphCutFilter ()
itk::DataObject::Pointer MakeOutput (unsigned int idx)
virtual ~GraphCutFilter ()
Protected Attributes
Graph3DFilterType::Pointer m_Graph3DFilter
TLinksFilterType::Pointer m_TLinksFilter
Detailed Description
template<typename TInput, typename TOutput>
class anima::GraphCutFilter< TInput, TOutput >
Class performing grah cut segmentation. First the sources and sinks probabilities maps are computed using the TLinkFilter. Then the Graph3DFilter is called to perform the graph cut.
Definition at line 17 of file animaGraphCutFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<const Self> anima::GraphCutFilter< TInput, TOutput >::ConstPointer
Definition at line 25 of file animaGraphCutFilter.h.
FloatVariableSizeMatrixType
template<typename TInput , typename TOutput > typedef itk::VariableSizeMatrix<NumericType> anima::GraphCutFilter< TInput, TOutput >::FloatVariableSizeMatrixType
Definition at line 44 of file animaGraphCutFilter.h.
Graph3DFilterType
template<typename TInput , typename TOutput > typedef Graph3DFilter< TInput,TOutput> anima::GraphCutFilter< TInput, TOutput >::Graph3DFilterType protected
Definition at line 104 of file animaGraphCutFilter.h.
NumericType
template<typename TInput , typename TOutput > typedef double anima::GraphCutFilter< TInput, TOutput >::NumericType
Definition at line 43 of file animaGraphCutFilter.h.
OutputImagePointer
template<typename TInput , typename TOutput > typedef TOutput::Pointer anima::GraphCutFilter< TInput, TOutput >::OutputImagePointer
Image typedef support
Definition at line 31 of file animaGraphCutFilter.h.
OutputImageRegionType
template<typename TInput , typename TOutput > typedef Superclass::OutputImageRegionType anima::GraphCutFilter< TInput, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 76 of file animaGraphCutFilter.h.
PixelTypeD
template<typename TInput , typename TOutput > typedef double anima::GraphCutFilter< TInput, TOutput >::PixelTypeD
Definition at line 40 of file animaGraphCutFilter.h.
PixelTypeUC
template<typename TInput , typename TOutput > typedef unsigned char anima::GraphCutFilter< TInput, TOutput >::PixelTypeUC
Definition at line 36 of file animaGraphCutFilter.h.
Pointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<Self> anima::GraphCutFilter< TInput, TOutput >::Pointer
Definition at line 24 of file animaGraphCutFilter.h.
Self
template<typename TInput , typename TOutput > typedef GraphCutFilter anima::GraphCutFilter< TInput, TOutput >::Self
Standard class typedefs.
Definition at line 22 of file animaGraphCutFilter.h.
Superclass
template<typename TInput , typename TOutput > typedef itk::ImageToImageFilter< TInput , TOutput > anima::GraphCutFilter< TInput, TOutput >::Superclass
Definition at line 23 of file animaGraphCutFilter.h.
TLinksFilterType
template<typename TInput , typename TOutput > typedef TLinksFilter<TInput,TSeedProba> anima::GraphCutFilter< TInput, TOutput >::TLinksFilterType protected
Definition at line 105 of file animaGraphCutFilter.h.
TMask
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeUC,3> anima::GraphCutFilter< TInput, TOutput >::TMask
Definition at line 37 of file animaGraphCutFilter.h.
TMaskPointer
template<typename TInput , typename TOutput > typedef TMask::Pointer anima::GraphCutFilter< TInput, TOutput >::TMaskPointer
Definition at line 38 of file animaGraphCutFilter.h.
TSeedProba
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeD,3> anima::GraphCutFilter< TInput, TOutput >::TSeedProba
Definition at line 41 of file animaGraphCutFilter.h.
Constructor & Destructor Documentation
GraphCutFilter()
template<typename TInput , typename TOutput > anima::GraphCutFilter< TInput, TOutput >::GraphCutFilter () inline protected
Definition at line 110 of file animaGraphCutFilter.h.
References anima::GraphCutFilter< TInput, TOutput >::MakeOutput(), anima::TLinksFilter< TInput, TOutput >::New(), anima::Graph3DFilter< TInput, TOutput >::New(), and singleGaussianTLink.
~GraphCutFilter()
template<typename TInput , typename TOutput > virtual anima::GraphCutFilter< TInput, TOutput >::~GraphCutFilter () inline protected virtual
Definition at line 139 of file animaGraphCutFilter.h.
References anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSinksMask(), anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSinksProba(), anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSourcesMask(), anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSourcesProba(), anima::GraphCutFilter< TInput, TOutput >::GetMask(), and anima::GraphCutFilter< TInput, TOutput >::MakeOutput().
Member Function Documentation
CreateAnother()
template<typename TInput , typename TOutput > virtual::itk::LightObject::Pointer anima::GraphCutFilter< TInput, TOutput >::CreateAnother (void) const
GenerateData()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::GenerateData () protected
Definition at line 154 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::GetMatrixGradFilename(), and anima::GraphCutFilter< TInput, TOutput >::WriteOutputs().
GetAlpha()
template<typename TInput , typename TOutput > virtual float anima::GraphCutFilter< TInput, TOutput >::GetAlpha () virtual
GetInputSeedSinksMask()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::ConstPointer anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSinksMask () protected
Definition at line 82 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::~GraphCutFilter().
GetInputSeedSinksProba()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSinksProba () protected
Definition at line 96 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::~GraphCutFilter().
GetInputSeedSourcesMask()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::ConstPointer anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSourcesMask () protected
Definition at line 75 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::~GraphCutFilter().
GetInputSeedSourcesProba()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::GraphCutFilter< TInput, TOutput >::GetInputSeedSourcesProba () protected
Definition at line 89 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::~GraphCutFilter().
GetMask()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::ConstPointer anima::GraphCutFilter< TInput, TOutput >::GetMask () protected
Definition at line 68 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::~GraphCutFilter().
GetMatrix()
template<typename TInput , typename TOutput > FloatVariableSizeMatrixType anima::GraphCutFilter< TInput, TOutput >::GetMatrix (void) inline protected
Definition at line 154 of file animaGraphCutFilter.h.
GetMatrixGradFilename()
template<typename TInput , typename TOutput > std::string anima::GraphCutFilter< TInput, TOutput >::GetMatrixGradFilename (void) inline protected
Definition at line 155 of file animaGraphCutFilter.h.
References anima::GraphCutFilter< TInput, TOutput >::GenerateData().
GetMultiVarSinks()
template<typename TInput , typename TOutput > virtual float anima::GraphCutFilter< TInput, TOutput >::GetMultiVarSinks () virtual
GetMultiVarSources()
template<typename TInput , typename TOutput > virtual float anima::GraphCutFilter< TInput, TOutput >::GetMultiVarSources () virtual
GetNameOfClass()
template<typename TInput , typename TOutput > virtual const char* anima::GraphCutFilter< TInput, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetOutput()
template<typename TInputImage , typename TOutput > TOutput::Pointer anima::GraphCutFilter< TInputImage, TOutput >::GetOutput ()
Definition at line 124 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::SetTLinkMode().
GetOutputBackground()
template<typename TInputImage , typename TOutput > TOutput::Pointer anima::GraphCutFilter< TInputImage, TOutput >::GetOutputBackground ()
Definition at line 129 of file animaGraphCutFilter.hxx.
References anima::GraphCutFilter< TInput, TOutput >::WriteOutputs().
Referenced by anima::GraphCutFilter< TInput, TOutput >::SetTLinkMode().
GetOutputFilename()
template<typename TInput , typename TOutput > std::string anima::GraphCutFilter< TInput, TOutput >::GetOutputFilename () inline
Definition at line 64 of file animaGraphCutFilter.h.
GetSigma()
template<typename TInput , typename TOutput > virtual float anima::GraphCutFilter< TInput, TOutput >::GetSigma () virtual
GetTLinkMode()
template<typename TInput , typename TOutput > TLinkMode anima::GraphCutFilter< TInput, TOutput >::GetTLinkMode () inline
Definition at line 67 of file animaGraphCutFilter.h.
GetUseSpectralGradient()
template<typename TInput , typename TOutput > virtual bool anima::GraphCutFilter< TInput, TOutput >::GetUseSpectralGradient () virtual
GetVerbose()
template<typename TInput , typename TOutput > virtual bool anima::GraphCutFilter< TInput, TOutput >::GetVerbose () virtual
MakeOutput()
template<typename TInputImage , typename TOutput > itk::DataObject::Pointer anima::GraphCutFilter< TInputImage, TOutput >::MakeOutput (unsigned int idx) protected
Create the Output
Definition at line 103 of file animaGraphCutFilter.hxx.
Referenced by anima::GraphCutFilter< TInput, TOutput >::GraphCutFilter(), and anima::GraphCutFilter< TInput, TOutput >::~GraphCutFilter().
New()
template<typename TInput , typename TOutput > static Pointer anima::GraphCutFilter< TInput, TOutput >::New () static
Method for creation through the object factory.
Referenced by anima::GcStremMsLesionsSegmentationFilter< TInputImage >::GcStremMsLesionsSegmentationFilter().
SetAlpha()
template<typename TInput , typename TOutput > virtual void anima::GraphCutFilter< TInput, TOutput >::SetAlpha (float _arg) virtual
SetInputImage()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetInputImage (unsigned int i, const TInput * image)
The MRI images.
Definition at line 9 of file animaGraphCutFilter.hxx.
SetInputSeedSinksMask()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetInputSeedSinksMask (const TMask * mask)
Definition at line 40 of file animaGraphCutFilter.hxx.
SetInputSeedSinksProba()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetInputSeedSinksProba (const TSeedProba * mask)
Definition at line 59 of file animaGraphCutFilter.hxx.
SetInputSeedSourcesMask()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetInputSeedSourcesMask (const TMask * mask)
probabilities of the object and the background, respectively or binary mask of the object and the background, respectively
Definition at line 31 of file animaGraphCutFilter.hxx.
SetInputSeedSourcesProba()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetInputSeedSourcesProba (const TSeedProba * mask)
Definition at line 50 of file animaGraphCutFilter.hxx.
SetMask()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetMask (const TMask * mask)
mask in which the segmentation will be performed
Definition at line 24 of file animaGraphCutFilter.hxx.
SetMatrix()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetMatrix (FloatVariableSizeMatrixType mat) inline
Definition at line 61 of file animaGraphCutFilter.h.
SetMatrixGradFilename()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetMatrixGradFilename (std::string mat) inline
Definition at line 62 of file animaGraphCutFilter.h.
SetMultiVarSinks()
template<typename TInput , typename TOutput > virtual void anima::GraphCutFilter< TInput, TOutput >::SetMultiVarSinks (float _arg) virtual
SetMultiVarSources()
template<typename TInput , typename TOutput > virtual void anima::GraphCutFilter< TInput, TOutput >::SetMultiVarSources (float _arg) virtual
SetOutputFilename()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetOutputFilename (std::string filename) inline
Definition at line 65 of file animaGraphCutFilter.h.
SetSigma()
template<typename TInput , typename TOutput > virtual void anima::GraphCutFilter< TInput, TOutput >::SetSigma (float _arg) virtual
SetTLinkMode()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetTLinkMode (TLinkMode m) inline
Definition at line 68 of file animaGraphCutFilter.h.
References anima::GraphCutFilter< TInput, TOutput >::GetOutput(), anima::GraphCutFilter< TInput, TOutput >::GetOutputBackground(), and anima::GraphCutFilter< TInput, TOutput >::WriteOutputs().
SetTol()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::SetTol (const double tol) inline
Definition at line 78 of file animaGraphCutFilter.h.
SetUseSpectralGradient()
template<typename TInput , typename TOutput > virtual void anima::GraphCutFilter< TInput, TOutput >::SetUseSpectralGradient (bool _arg) virtual
SetVerbose()
template<typename TInput , typename TOutput > virtual void anima::GraphCutFilter< TInput, TOutput >::SetVerbose (bool _arg) virtual
WriteOutputs()
template<typename TInput , typename TOutput > void anima::GraphCutFilter< TInput, TOutput >::WriteOutputs ()
Definition at line 137 of file animaGraphCutFilter.hxx.
References anima::GraphCutFilter< TInput, TOutput >::GenerateData().
Referenced by anima::GraphCutFilter< TInput, TOutput >::GetOutputBackground(), and anima::GraphCutFilter< TInput, TOutput >::SetTLinkMode().
Member Data Documentation
m_Graph3DFilter
template<typename TInput , typename TOutput > Graph3DFilterType::Pointer anima::GraphCutFilter< TInput, TOutput >::m_Graph3DFilter protected
Definition at line 108 of file animaGraphCutFilter.h.
m_TLinksFilter
template<typename TInput , typename TOutput > TLinksFilterType::Pointer anima::GraphCutFilter< TInput, TOutput >::m_TLinksFilter protected
Definition at line 107 of file animaGraphCutFilter.h.
The documentation for this class was generated from the following files:
animaGraphCutFilter.h
animaGraphCutFilter.hxx