ANIMA: anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <animaT1RelaxometryEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef T1RelaxometryEstimationImageFilter Self
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Types inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TInputImage::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::ImageSource< TOutputImage >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetAverageSignalThreshold (double _arg)
virtual void SetB1Map (OutputImagePointer _arg)
void SetFlipAngles (std::vector< double > &flipAngles)
virtual void SetM0UpperBoundValue (double _arg)
virtual void SetT1UpperBoundValue (double _arg)
virtual void SetTRValue (double _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
T1RelaxometryEstimationImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~T1RelaxometryEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
template<typename ScalarRealType >
void InitializeZeroPixel (TOutputImage *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<typename PixelType >
void InitializeZeroPixel (TOutputImage *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TInputImage, typename TOutputImage>
class anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >
Definition at line 10 of file animaT1RelaxometryEstimationImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInputImage , typename TOutputImage > typedef itk::SmartPointer<const Self> anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 18 of file animaT1RelaxometryEstimationImageFilter.h.
InputImagePointer
template<typename TInputImage , typename TOutputImage > typedef InputImageType::Pointer anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImagePointer
Definition at line 29 of file animaT1RelaxometryEstimationImageFilter.h.
InputImageRegionType
template<typename TInputImage , typename TOutputImage > typedef Superclass::InputImageRegionType anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImageRegionType
Definition at line 34 of file animaT1RelaxometryEstimationImageFilter.h.
InputImageType
template<typename TInputImage , typename TOutputImage > typedef TInputImage anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::InputImageType
Image typedef support
Definition at line 27 of file animaT1RelaxometryEstimationImageFilter.h.
MaskImageType
template<typename TInputImage , typename TOutputImage > typedef Superclass::MaskImageType anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::MaskImageType
Superclass typedefs.
Definition at line 33 of file animaT1RelaxometryEstimationImageFilter.h.
OutputImagePointer
template<typename TInputImage , typename TOutputImage > typedef OutputImageType::Pointer anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImagePointer
Definition at line 30 of file animaT1RelaxometryEstimationImageFilter.h.
OutputImageRegionType
template<typename TInputImage , typename TOutputImage > typedef Superclass::OutputImageRegionType anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImageRegionType
Definition at line 35 of file animaT1RelaxometryEstimationImageFilter.h.
OutputImageType
template<typename TInputImage , typename TOutputImage > typedef TOutputImage anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::OutputImageType
Definition at line 28 of file animaT1RelaxometryEstimationImageFilter.h.
Pointer
template<typename TInputImage , typename TOutputImage > typedef itk::SmartPointer<Self> anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 17 of file animaT1RelaxometryEstimationImageFilter.h.
Self
template<typename TInputImage , typename TOutputImage > typedef T1RelaxometryEstimationImageFilter anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 15 of file animaT1RelaxometryEstimationImageFilter.h.
Superclass
template<typename TInputImage , typename TOutputImage > typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 16 of file animaT1RelaxometryEstimationImageFilter.h.
Constructor & Destructor Documentation
T1RelaxometryEstimationImageFilter()
template<typename TInputImage , typename TOutputImage > anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::T1RelaxometryEstimationImageFilter () inline protected
Definition at line 46 of file animaT1RelaxometryEstimationImageFilter.h.
~T1RelaxometryEstimationImageFilter()
template<typename TInputImage , typename TOutputImage > virtual anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T1RelaxometryEstimationImageFilter () inline protected virtual
Definition at line 63 of file animaT1RelaxometryEstimationImageFilter.h.
References anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData(), anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CheckComputationMask(), and anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TInputImage , typename TOutputImage > void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Definition at line 12 of file animaT1RelaxometryEstimationImageFilter.hxx.
Referenced by anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T1RelaxometryEstimationImageFilter().
CheckComputationMask()
template<typename TInputImage , typename TOutputImage > void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >.
Definition at line 26 of file animaT1RelaxometryEstimationImageFilter.hxx.
Referenced by anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T1RelaxometryEstimationImageFilter().
CreateAnother()
template<typename TInputImage , typename TOutputImage > virtual::itk::LightObject::Pointer anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
GetNameOfClass()
template<typename TInputImage , typename TOutputImage > virtual const char* anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< TInputImage, TOutputImage >.
New()
template<typename TInputImage , typename TOutputImage > static Pointer anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
SetAverageSignalThreshold()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetAverageSignalThreshold (double _arg) virtual
SetB1Map()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetB1Map (OutputImagePointer _arg) virtual
SetFlipAngles()
template<typename TInputImage , typename TOutputImage > void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetFlipAngles (std::vector< double > & flipAngles) inline
Definition at line 43 of file animaT1RelaxometryEstimationImageFilter.h.
SetM0UpperBoundValue()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetM0UpperBoundValue (double _arg) virtual
SetT1UpperBoundValue()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetT1UpperBoundValue (double _arg) virtual
SetTRValue()
template<typename TInputImage , typename TOutputImage > virtual void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::SetTRValue (double _arg) virtual
ThreadedGenerateData()
template<typename TInputImage , typename TOutputImage > void anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 74 of file animaT1RelaxometryEstimationImageFilter.hxx.
Referenced by anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >::~T1RelaxometryEstimationImageFilter().
The documentation for this class was generated from the following files:
animaT1RelaxometryEstimationImageFilter.h
animaT1RelaxometryEstimationImageFilter.hxx