ANIMA: anima::NLinksFilter< TInput, TOutput > Class Template Reference
anima::NLinksFilter< TInput, TOutput > Class Template Reference
Class creating a 3D graph in a graph cut framework.
#include <animaNLinksFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::VariableSizeMatrix< NumericType > FloatVariableSizeMatrixType
typedef Graph< double, double, double > GraphType
typedef itk::ImageRegionIterator< ImageTypeInt > ImageIteratorTypeInt
typedef itk::ImageRegionIterator< TSeedProba > ImageIteratorTypeProba
typedef TSeedProba::Pointer ImagePointerProba
typedef itk::Image< PixelTypeInt, 3 > ImageTypeInt
typedef TInput::ConstPointer InputImageConstPointer
typedef TInput::Pointer InputImagePointer
typedef TInput::PixelType InputPixelType
typedef itk::ImageRegionConstIterator< TInput > InRegionConstIteratorType
typedef itk::ImageRegionConstIterator< TMask > MaskRegionConstIteratorType
typedef itk::ImageRegionIterator< TMask > MaskRegionIteratorType
typedef double NumericType
typedef TOutput::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::ImageRegionIterator< TOutput > OutputIteratorType
typedef TOutput::PixelType OutputPixelType
typedef ImageTypeInt::IndexType pixelIndexInt
typedef double PixelTypeD
typedef int PixelTypeInt
typedef unsigned char PixelTypeUC
typedef itk::SmartPointer< Self > Pointer
typedef TSeedProba::PixelType SeedProbaPixelType
typedef NLinksFilter Self
typedef itk::ImageToImageFilter< TInput, TOutput > Superclass
typedef itk::Image< PixelTypeUC, 3 > TMask
typedef TMask::Pointer TMaskPointer
typedef itk::Image< PixelTypeD, 3 > TSeedProba
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual unsigned int GetNbModalities ()
OutputImagePointer GetOutput ()
OutputImagePointer GetOutputBackground ()
virtual float GetSigma ()
virtual bool GetUseSpectralGradient ()
virtual bool GetVerbose ()
void SetInputImage1 (const TInput *image)
void SetInputImage2 (const TInput *image)
void SetInputImage3 (const TInput *image)
void SetInputImage4 (const TInput *image)
void SetInputImage5 (const TInput *image)
void SetInputSeedProbaSinks (const TSeedProba *mask)
void SetInputSeedProbaSources (const TSeedProba *mask)
void SetMask (const TMask *mask)
void SetMatFilename (std::string mat)
void SetMatrix (FloatVariableSizeMatrixType mat)
virtual void SetNbModalities (unsigned int _arg)
virtual void SetSigma (float _arg)
void SetTol (const double tol)
virtual void SetUseSpectralGradient (bool _arg)
virtual void SetVerbose (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void CheckSpectralGradient (void)
double computeNLink (int i1, int j1, int k1, int i2, int j2, int k2)
void CreateGraph ()
void GenerateData () ITK_OVERRIDE
TInput::ConstPointer GetInputImage1 ()
TInput::ConstPointer GetInputImage2 ()
TInput::ConstPointer GetInputImage3 ()
TInput::ConstPointer GetInputImage4 ()
TInput::ConstPointer GetInputImage5 ()
TInput::ConstPointer GetInputImage6 ()
TSeedProba::ConstPointer GetInputSeedProbaSinks ()
TSeedProba::ConstPointer GetInputSeedProbaSources ()
TMask::ConstPointer GetMask ()
std::string GetMatFilename (void)
FloatVariableSizeMatrixType GetMatrix (void)
bool isInside (unsigned int x, unsigned int y, unsigned int z) const
itk::DataObject::Pointer MakeOutput (unsigned int idx)
NLinksFilter ()
bool readMatrixFile ()
void SetGraph ()
virtual ~NLinksFilter ()
Detailed Description
template<typename TInput, typename TOutput>
class anima::NLinksFilter< TInput, TOutput >
Class creating a 3D graph in a graph cut framework.
The nodes correspond to the voxels of the image to segment. Two additional nodes represent the object (SOURCE) and the background (SINK). N-links represent edges between neighboring nodes/voxels. T-links that bind each classical node to both the SOURCE and the SINK represent the probability for the corresponding voxel to belong respectively to the object and to the background.
Definition at line 23 of file animaNLinksFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<const Self> anima::NLinksFilter< TInput, TOutput >::ConstPointer
Definition at line 31 of file animaNLinksFilter.h.
FloatVariableSizeMatrixType
template<typename TInput , typename TOutput > typedef itk::VariableSizeMatrix<NumericType> anima::NLinksFilter< TInput, TOutput >::FloatVariableSizeMatrixType
Definition at line 69 of file animaNLinksFilter.h.
GraphType
template<typename TInput , typename TOutput > typedef Graph<double,double,double> anima::NLinksFilter< TInput, TOutput >::GraphType
Definition at line 66 of file animaNLinksFilter.h.
ImageIteratorTypeInt
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator<ImageTypeInt> anima::NLinksFilter< TInput, TOutput >::ImageIteratorTypeInt
Definition at line 58 of file animaNLinksFilter.h.
ImageIteratorTypeProba
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator<TSeedProba> anima::NLinksFilter< TInput, TOutput >::ImageIteratorTypeProba
Definition at line 52 of file animaNLinksFilter.h.
ImagePointerProba
template<typename TInput , typename TOutput > typedef TSeedProba::Pointer anima::NLinksFilter< TInput, TOutput >::ImagePointerProba
Definition at line 51 of file animaNLinksFilter.h.
ImageTypeInt
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeInt,3> anima::NLinksFilter< TInput, TOutput >::ImageTypeInt
Definition at line 56 of file animaNLinksFilter.h.
InputImageConstPointer
template<typename TInput , typename TOutput > typedef TInput::ConstPointer anima::NLinksFilter< TInput, TOutput >::InputImageConstPointer
Definition at line 41 of file animaNLinksFilter.h.
InputImagePointer
template<typename TInput , typename TOutput > typedef TInput::Pointer anima::NLinksFilter< TInput, TOutput >::InputImagePointer
Image typedef support
Definition at line 40 of file animaNLinksFilter.h.
InputPixelType
template<typename TInput , typename TOutput > typedef TInput::PixelType anima::NLinksFilter< TInput, TOutput >::InputPixelType
Definition at line 43 of file animaNLinksFilter.h.
InRegionConstIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionConstIterator< TInput > anima::NLinksFilter< TInput, TOutput >::InRegionConstIteratorType
Definition at line 42 of file animaNLinksFilter.h.
MaskRegionConstIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionConstIterator< TMask > anima::NLinksFilter< TInput, TOutput >::MaskRegionConstIteratorType
Definition at line 64 of file animaNLinksFilter.h.
MaskRegionIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TMask > anima::NLinksFilter< TInput, TOutput >::MaskRegionIteratorType
Definition at line 63 of file animaNLinksFilter.h.
NumericType
template<typename TInput , typename TOutput > typedef double anima::NLinksFilter< TInput, TOutput >::NumericType
Definition at line 68 of file animaNLinksFilter.h.
OutputImagePointer
template<typename TInput , typename TOutput > typedef TOutput::Pointer anima::NLinksFilter< TInput, TOutput >::OutputImagePointer
Definition at line 45 of file animaNLinksFilter.h.
OutputImageRegionType
template<typename TInput , typename TOutput > typedef Superclass::OutputImageRegionType anima::NLinksFilter< TInput, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 94 of file animaNLinksFilter.h.
OutputIteratorType
template<typename TInput , typename TOutput > typedef itk::ImageRegionIterator< TOutput > anima::NLinksFilter< TInput, TOutput >::OutputIteratorType
Definition at line 47 of file animaNLinksFilter.h.
OutputPixelType
template<typename TInput , typename TOutput > typedef TOutput::PixelType anima::NLinksFilter< TInput, TOutput >::OutputPixelType
Definition at line 46 of file animaNLinksFilter.h.
pixelIndexInt
template<typename TInput , typename TOutput > typedef ImageTypeInt::IndexType anima::NLinksFilter< TInput, TOutput >::pixelIndexInt
Definition at line 57 of file animaNLinksFilter.h.
PixelTypeD
template<typename TInput , typename TOutput > typedef double anima::NLinksFilter< TInput, TOutput >::PixelTypeD
Definition at line 49 of file animaNLinksFilter.h.
PixelTypeInt
template<typename TInput , typename TOutput > typedef int anima::NLinksFilter< TInput, TOutput >::PixelTypeInt
Definition at line 55 of file animaNLinksFilter.h.
PixelTypeUC
template<typename TInput , typename TOutput > typedef unsigned char anima::NLinksFilter< TInput, TOutput >::PixelTypeUC
Definition at line 60 of file animaNLinksFilter.h.
Pointer
template<typename TInput , typename TOutput > typedef itk::SmartPointer<Self> anima::NLinksFilter< TInput, TOutput >::Pointer
Definition at line 30 of file animaNLinksFilter.h.
SeedProbaPixelType
template<typename TInput , typename TOutput > typedef TSeedProba::PixelType anima::NLinksFilter< TInput, TOutput >::SeedProbaPixelType
Definition at line 53 of file animaNLinksFilter.h.
Self
template<typename TInput , typename TOutput > typedef NLinksFilter anima::NLinksFilter< TInput, TOutput >::Self
Standard class typedefs.
Definition at line 28 of file animaNLinksFilter.h.
Superclass
template<typename TInput , typename TOutput > typedef itk::ImageToImageFilter< TInput , TOutput> anima::NLinksFilter< TInput, TOutput >::Superclass
Definition at line 29 of file animaNLinksFilter.h.
TMask
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeUC,3> anima::NLinksFilter< TInput, TOutput >::TMask
Definition at line 61 of file animaNLinksFilter.h.
TMaskPointer
template<typename TInput , typename TOutput > typedef TMask::Pointer anima::NLinksFilter< TInput, TOutput >::TMaskPointer
Definition at line 62 of file animaNLinksFilter.h.
TSeedProba
template<typename TInput , typename TOutput > typedef itk::Image<PixelTypeD,3> anima::NLinksFilter< TInput, TOutput >::TSeedProba
Definition at line 50 of file animaNLinksFilter.h.
Constructor & Destructor Documentation
NLinksFilter()
template<typename TInput , typename TOutput > anima::NLinksFilter< TInput, TOutput >::NLinksFilter () inline protected
Definition at line 116 of file animaNLinksFilter.h.
References anima::NLinksFilter< TInput, TOutput >::MakeOutput().
~NLinksFilter()
template<typename TInput , typename TOutput > virtual anima::NLinksFilter< TInput, TOutput >::~NLinksFilter () inline protected virtual
Definition at line 135 of file animaNLinksFilter.h.
References anima::NLinksFilter< TInput, TOutput >::GetInputImage1(), anima::NLinksFilter< TInput, TOutput >::GetInputImage2(), anima::NLinksFilter< TInput, TOutput >::GetInputImage3(), anima::NLinksFilter< TInput, TOutput >::GetInputImage4(), anima::NLinksFilter< TInput, TOutput >::GetInputImage5(), anima::NLinksFilter< TInput, TOutput >::GetInputImage6(), anima::NLinksFilter< TInput, TOutput >::GetInputSeedProbaSinks(), anima::NLinksFilter< TInput, TOutput >::GetInputSeedProbaSources(), anima::NLinksFilter< TInput, TOutput >::GetMask(), and anima::NLinksFilter< TInput, TOutput >::MakeOutput().
Member Function Documentation
CheckSpectralGradient()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::CheckSpectralGradient (void) protected
Definition at line 201 of file animaNLinksFilter.hxx.
References anima::NLinksFilter< TInput, TOutput >::GenerateData().
Referenced by anima::NLinksFilter< TInput, TOutput >::GetMatFilename(), and anima::NLinksFilter< TInput, TOutput >::readMatrixFile().
computeNLink()
template<typename TInput , typename TOutput > double anima::NLinksFilter< TInput, TOutput >::computeNLink (int i1, int j1, int k1, int i2, int j2, int k2) protected
Definition at line 326 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::GetMatFilename().
CreateAnother()
template<typename TInput , typename TOutput > virtual::itk::LightObject::Pointer anima::NLinksFilter< TInput, TOutput >::CreateAnother (void) const
CreateGraph()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::CreateGraph () protected
Definition at line 358 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::GetMatFilename().
GenerateData()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::GenerateData () protected
Definition at line 274 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::CheckSpectralGradient(), and anima::NLinksFilter< TInput, TOutput >::GetMatFilename().
GetInputImage1()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputImage1 () protected
Definition at line 76 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetInputImage2()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputImage2 () protected
Definition at line 104 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetInputImage3()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputImage3 () protected
Definition at line 111 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetInputImage4()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputImage4 () protected
Definition at line 118 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetInputImage5()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputImage5 () protected
Definition at line 125 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetInputImage6()
template<typename TInput , typename TOutput > TInput::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputImage6 () protected
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetInputSeedProbaSinks()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputSeedProbaSinks () protected
Definition at line 90 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetInputSeedProbaSources()
template<typename TInput , typename TOutput > itk::Image< double, 3 >::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetInputSeedProbaSources () protected
Definition at line 83 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetMask()
template<typename TInput , typename TOutput > itk::Image< unsigned char, 3 >::ConstPointer anima::NLinksFilter< TInput, TOutput >::GetMask () protected
Definition at line 97 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
GetMatFilename()
template<typename TInput , typename TOutput > std::string anima::NLinksFilter< TInput, TOutput >::GetMatFilename (void) inline protected
Definition at line 155 of file animaNLinksFilter.h.
References anima::NLinksFilter< TInput, TOutput >::CheckSpectralGradient(), anima::NLinksFilter< TInput, TOutput >::computeNLink(), anima::NLinksFilter< TInput, TOutput >::CreateGraph(), anima::NLinksFilter< TInput, TOutput >::GenerateData(), anima::NLinksFilter< TInput, TOutput >::isInside(), anima::NLinksFilter< TInput, TOutput >::readMatrixFile(), and anima::NLinksFilter< TInput, TOutput >::SetGraph().
GetMatrix()
template<typename TInput , typename TOutput > FloatVariableSizeMatrixType anima::NLinksFilter< TInput, TOutput >::GetMatrix (void) inline protected
Definition at line 154 of file animaNLinksFilter.h.
GetNameOfClass()
template<typename TInput , typename TOutput > virtual const char* anima::NLinksFilter< TInput, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetNbModalities()
template<typename TInput , typename TOutput > virtual unsigned int anima::NLinksFilter< TInput, TOutput >::GetNbModalities () virtual
GetOutput()
template<typename TInputImage , typename TOutput > TOutput::Pointer anima::NLinksFilter< TInputImage, TOutput >::GetOutput ()
Definition at line 154 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::SetMatrix().
GetOutputBackground()
template<typename TInputImage , typename TOutput > TOutput::Pointer anima::NLinksFilter< TInputImage, TOutput >::GetOutputBackground ()
Definition at line 159 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::SetMatrix().
GetSigma()
template<typename TInput , typename TOutput > virtual float anima::NLinksFilter< TInput, TOutput >::GetSigma () virtual
GetUseSpectralGradient()
template<typename TInput , typename TOutput > virtual bool anima::NLinksFilter< TInput, TOutput >::GetUseSpectralGradient () virtual
GetVerbose()
template<typename TInput , typename TOutput > virtual bool anima::NLinksFilter< TInput, TOutput >::GetVerbose () virtual
isInside()
template<typename TInput , typename TOutput > bool anima::NLinksFilter< TInput, TOutput >::isInside (unsigned int x, unsigned int y, unsigned int z) const protected
Definition at line 414 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::GetMatFilename().
MakeOutput()
template<typename TInputImage , typename TOutput > itk::DataObject::Pointer anima::NLinksFilter< TInputImage, TOutput >::MakeOutput (unsigned int idx) protected
Create the Output
Definition at line 133 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::NLinksFilter(), and anima::NLinksFilter< TInput, TOutput >::~NLinksFilter().
New()
template<typename TInput , typename TOutput > static Pointer anima::NLinksFilter< TInput, TOutput >::New () static
Method for creation through the object factory.
Referenced by anima::Graph3DFilter< TInput, TOutput >::Graph3DFilter().
readMatrixFile()
template<typename TInput , typename TOutput > bool anima::NLinksFilter< TInput, TOutput >::readMatrixFile () protected
Definition at line 165 of file animaNLinksFilter.hxx.
References anima::NLinksFilter< TInput, TOutput >::CheckSpectralGradient().
Referenced by anima::NLinksFilter< TInput, TOutput >::GetMatFilename().
SetGraph()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetGraph () protected
Definition at line 420 of file animaNLinksFilter.hxx.
Referenced by anima::NLinksFilter< TInput, TOutput >::GetMatFilename().
SetInputImage1()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetInputImage1 (const TInput * image)
The mri images.
Definition at line 9 of file animaNLinksFilter.hxx.
SetInputImage2()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetInputImage2 (const TInput * image)
Definition at line 35 of file animaNLinksFilter.hxx.
SetInputImage3()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetInputImage3 (const TInput * image)
Definition at line 45 of file animaNLinksFilter.hxx.
SetInputImage4()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetInputImage4 (const TInput * image)
Definition at line 55 of file animaNLinksFilter.hxx.
SetInputImage5()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetInputImage5 (const TInput * image)
Definition at line 65 of file animaNLinksFilter.hxx.
SetInputSeedProbaSinks()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetInputSeedProbaSinks (const TSeedProba * mask)
Definition at line 23 of file animaNLinksFilter.hxx.
SetInputSeedProbaSources()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetInputSeedProbaSources (const TSeedProba * mask)
probabilities of the object and the background, respectively
Definition at line 17 of file animaNLinksFilter.hxx.
SetMask()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetMask (const TMask * mask)
mask in which the segmentation will be performed
Definition at line 29 of file animaNLinksFilter.hxx.
SetMatFilename()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetMatFilename (std::string mat) inline
Definition at line 87 of file animaNLinksFilter.h.
SetMatrix()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetMatrix (FloatVariableSizeMatrixType mat) inline
Definition at line 88 of file animaNLinksFilter.h.
References anima::NLinksFilter< TInput, TOutput >::GetOutput(), and anima::NLinksFilter< TInput, TOutput >::GetOutputBackground().
SetNbModalities()
template<typename TInput , typename TOutput > virtual void anima::NLinksFilter< TInput, TOutput >::SetNbModalities (unsigned int _arg) virtual
SetSigma()
template<typename TInput , typename TOutput > virtual void anima::NLinksFilter< TInput, TOutput >::SetSigma (float _arg) virtual
SetTol()
template<typename TInput , typename TOutput > void anima::NLinksFilter< TInput, TOutput >::SetTol (const double tol) inline
Definition at line 96 of file animaNLinksFilter.h.
SetUseSpectralGradient()
template<typename TInput , typename TOutput > virtual void anima::NLinksFilter< TInput, TOutput >::SetUseSpectralGradient (bool _arg) virtual
SetVerbose()
template<typename TInput , typename TOutput > virtual void anima::NLinksFilter< TInput, TOutput >::SetVerbose (bool _arg) virtual
The documentation for this class was generated from the following files:
animaNLinksFilter.h
animaNLinksFilter.hxx