ANIMA: anima::PatientToGroupComparisonImageFilter< PixelScalarType > Class Template Reference
anima::PatientToGroupComparisonImageFilter< PixelScalarType > Class Template Reference
Implements patient to group comparison as in http://dx.doi.org/10.1007/978-3-540-85988-8_116.
#include <animaPatientToGroupComparisonImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef vnl_matrix< double > CovMatrixType
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::Pointer InputImagePointer
typedef itk::VectorImage< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef PatientToGroupComparisonImageFilter< PixelScalarType > Self
typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > Superclass
enum TestType {
CHI_SQUARE = 0,
FISHER
}
typedef InputImageType::PixelType VectorType
Public Types inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::VectorImage< PixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< PixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
void AddDatabaseInput (InputImageType *tmpIm)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetExplainedRatio (double _arg)
virtual void SetNumEigenValuesPCA (unsigned int _arg)
virtual void SetStatisticalTestType (TestType _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
PatientToGroupComparisonImageFilter ()
virtual unsigned int SampleFromDiffusionModels (std::vector< VectorType > &databaseValues, VectorType &patientVectorValue)
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~PatientToGroupComparisonImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class PixelScalarType>
class anima::PatientToGroupComparisonImageFilter< PixelScalarType >
Implements patient to group comparison as in http://dx.doi.org/10.1007/978-3-540-85988-8_116.
Provides an ITK implementation of z-score and p-value computation telling how much different a single vector image is from a database of controls. It can virtually process any type of input, however for tensor images, be warned that they should be expressed as log-vectors.
Definition at line 22 of file animaPatientToGroupComparisonImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class PixelScalarType> typedef itk::SmartPointer<const Self> anima::PatientToGroupComparisonImageFilter< PixelScalarType >::ConstPointer
Definition at line 29 of file animaPatientToGroupComparisonImageFilter.h.
CovMatrixType
template<class PixelScalarType> typedef vnl_matrix<double> anima::PatientToGroupComparisonImageFilter< PixelScalarType >::CovMatrixType
Definition at line 58 of file animaPatientToGroupComparisonImageFilter.h.
InputImageIndexType
template<class PixelScalarType> typedef InputImageType::IndexType anima::PatientToGroupComparisonImageFilter< PixelScalarType >::InputImageIndexType
Definition at line 51 of file animaPatientToGroupComparisonImageFilter.h.
InputImagePointer
template<class PixelScalarType> typedef InputImageType::Pointer anima::PatientToGroupComparisonImageFilter< PixelScalarType >::InputImagePointer
Definition at line 50 of file animaPatientToGroupComparisonImageFilter.h.
InputImageType
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType, 3> anima::PatientToGroupComparisonImageFilter< PixelScalarType >::InputImageType
Image typedef support
Definition at line 35 of file animaPatientToGroupComparisonImageFilter.h.
MaskImageType
template<class PixelScalarType> typedef Superclass::MaskImageType anima::PatientToGroupComparisonImageFilter< PixelScalarType >::MaskImageType
Superclass typedefs.
Definition at line 55 of file animaPatientToGroupComparisonImageFilter.h.
OutputImagePointer
template<class PixelScalarType> typedef OutputImageType::Pointer anima::PatientToGroupComparisonImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 52 of file animaPatientToGroupComparisonImageFilter.h.
OutputImageRegionType
template<class PixelScalarType> typedef Superclass::OutputImageRegionType anima::PatientToGroupComparisonImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 56 of file animaPatientToGroupComparisonImageFilter.h.
OutputImageType
template<class PixelScalarType> typedef itk::Image<PixelScalarType, 3> anima::PatientToGroupComparisonImageFilter< PixelScalarType >::OutputImageType
Definition at line 39 of file animaPatientToGroupComparisonImageFilter.h.
Pointer
template<class PixelScalarType> typedef itk::SmartPointer<Self> anima::PatientToGroupComparisonImageFilter< PixelScalarType >::Pointer
Definition at line 28 of file animaPatientToGroupComparisonImageFilter.h.
Self
template<class PixelScalarType> typedef PatientToGroupComparisonImageFilter<PixelScalarType> anima::PatientToGroupComparisonImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 27 of file animaPatientToGroupComparisonImageFilter.h.
Superclass
template<class PixelScalarType> typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::PatientToGroupComparisonImageFilter< PixelScalarType >::Superclass
Definition at line 49 of file animaPatientToGroupComparisonImageFilter.h.
VectorType
template<class PixelScalarType> typedef InputImageType::PixelType anima::PatientToGroupComparisonImageFilter< PixelScalarType >::VectorType
Definition at line 41 of file animaPatientToGroupComparisonImageFilter.h.
Member Enumeration Documentation
TestType
template<class PixelScalarType> enum anima::PatientToGroupComparisonImageFilter::TestType
Enumerator
CHI_SQUARE
FISHER
Definition at line 43 of file animaPatientToGroupComparisonImageFilter.h.
Constructor & Destructor Documentation
PatientToGroupComparisonImageFilter()
template<class PixelScalarType> anima::PatientToGroupComparisonImageFilter< PixelScalarType >::PatientToGroupComparisonImageFilter () inline protected
Definition at line 71 of file animaPatientToGroupComparisonImageFilter.h.
References anima::PatientToGroupComparisonImageFilter< PixelScalarType >::FISHER.
~PatientToGroupComparisonImageFilter()
template<class PixelScalarType> virtual anima::PatientToGroupComparisonImageFilter< PixelScalarType >::~PatientToGroupComparisonImageFilter () inline protected virtual
Definition at line 85 of file animaPatientToGroupComparisonImageFilter.h.
References anima::PatientToGroupComparisonImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::PatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
Member Function Documentation
AddDatabaseInput()
template<class PixelScalarType> void anima::PatientToGroupComparisonImageFilter< PixelScalarType >::AddDatabaseInput (InputImageType * tmpIm) inline
Definition at line 60 of file animaPatientToGroupComparisonImageFilter.h.
BeforeThreadedGenerateData()
template<class PixelScalarType > void anima::PatientToGroupComparisonImageFilter< PixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
Reimplemented in anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >.
Definition at line 21 of file animaPatientToGroupComparisonImageFilter.hxx.
References anima::PatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
Referenced by anima::PatientToGroupComparisonImageFilter< PixelScalarType >::~PatientToGroupComparisonImageFilter().
CreateAnother()
template<class PixelScalarType> virtual::itk::LightObject::Pointer anima::PatientToGroupComparisonImageFilter< PixelScalarType >::CreateAnother (void) const
GetNameOfClass()
template<class PixelScalarType> virtual const char* anima::PatientToGroupComparisonImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
Reimplemented in anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >.
New()
template<class PixelScalarType> static Pointer anima::PatientToGroupComparisonImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
Referenced by anima::LowMemoryPatientToGroupComparisonBridge::Update().
SampleFromDiffusionModels()
template<class PixelScalarType> virtual unsigned int anima::PatientToGroupComparisonImageFilter< PixelScalarType >::SampleFromDiffusionModels (std::vector< VectorType > & databaseValues, VectorType & patientVectorValue) inline protected virtual
Reimplemented in anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >.
Definition at line 90 of file animaPatientToGroupComparisonImageFilter.h.
SetExplainedRatio()
template<class PixelScalarType> virtual void anima::PatientToGroupComparisonImageFilter< PixelScalarType >::SetExplainedRatio (double _arg) virtual
SetNumEigenValuesPCA()
template<class PixelScalarType> virtual void anima::PatientToGroupComparisonImageFilter< PixelScalarType >::SetNumEigenValuesPCA (unsigned int _arg) virtual
SetStatisticalTestType()
template<class PixelScalarType> virtual void anima::PatientToGroupComparisonImageFilter< PixelScalarType >::SetStatisticalTestType (TestType _arg) virtual
ThreadedGenerateData()
template<class PixelScalarType > void anima::PatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 43 of file animaPatientToGroupComparisonImageFilter.hxx.
Referenced by anima::PatientToGroupComparisonImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::PatientToGroupComparisonImageFilter< PixelScalarType >::~PatientToGroupComparisonImageFilter().
The documentation for this class was generated from the following files:
animaPatientToGroupComparisonImageFilter.h
animaPatientToGroupComparisonImageFilter.hxx