ANIMA: anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType > Class Template Reference
anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType > Class Template Reference
#include <animaMCMEstimatorImageFilter.h>
Public Types
typedef anima::BaseCompartment BaseCompartmentType
typedef anima::MultiCompartmentModelCreator::CompartmentType CompartmentType
typedef itk::SmartPointer< const Self > ConstPointer
typedef CostFunctionBaseType::Pointer CostFunctionBasePointer
typedef itk::CostFunction CostFunctionBaseType
typedef vnl_vector_fixed< double, 3 > GradientType
typedef itk::Image< InputPixelType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
enum MaximumLikelihoodEstimationMode {
Marginal = 0,
Profile,
VariableProjection
}
typedef anima::MultiCompartmentModelCreator MCMCreatorType
typedef MCMCreatorType::MCMPointer MCMPointer
typedef MCMCreatorType::MCMType MCMType
typedef MCMType::ListType MCMVectorType
typedef anima::MCMImage< OutputPixelType, 3 > ModelImageType
typedef MoseImageType::Pointer MoseImagePointer
typedef itk::Image< unsigned char, 3 > MoseImageType
typedef OptimizerType::Pointer OptimizerPointer
typedef itk::NonLinearOptimizer OptimizerType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef OutputScalarImageType::Pointer OutputScalarImagePointer
typedef itk::Image< OutputPixelType, 3 > OutputScalarImageType
typedef OptimizerType::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef MCMEstimatorImageFilter< InputPixelType, OutputPixelType > Self
enum SignalNoiseType {
Gaussian = 0,
NCC
}
Denotes noise type on input signal. Based on this, a different cost function should be created.
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::Image< InputPixelType, 3 > TInputImage
typedef anima::MCMImage< OutputPixelType, 3 > TOutputImage
typedef OutputImageType::PixelType VariableLengthVectorType
typedef VectorImageType::Pointer VectorImagePointer
typedef itk::VectorImage< OutputPixelType, 3 > VectorImageType
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::Image< InputPixelType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > > Superclass
typedef itk::ImageSource< anima::MCMImage< OutputPixelType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
void AddGradientDirection (unsigned int i, GradientType &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
OutputScalarImageType * GetAICcVolume ()
OutputScalarImageType * GetB0Volume ()
virtual double GetBigDelta ()
std::vector< GradientType > & GetGradientDirections ()
std::vector< double > & GetGradientStrengths ()
MCMCreatorType * GetMCMCreator (unsigned int i)
virtual MaximumLikelihoodEstimationMode GetMLEstimationStrategy ()
MoseImageType * GetMoseVolume ()
virtual const char * GetNameOfClass () const
virtual MCMCreatorType * GetNewMCMCreatorInstance ()
virtual SignalNoiseType GetNoiseType ()
virtual unsigned int GetNumberOfCoils ()
std::string GetOptimizer ()
OutputScalarImageType * GetSigmaSquareVolume ()
virtual double GetSmallDelta ()
virtual void SetAbsoluteCostChange (double _arg)
virtual void SetAxialDiffusivityValue (double _arg)
virtual void SetB0Threshold (double _arg)
virtual void SetBigDelta (double _arg)
virtual void SetCompartmentType (CompartmentType _arg)
virtual void SetFindOptimalNumberOfCompartments (bool _arg)
void SetGradientStrengths (std::vector< double > &mb)
virtual void SetGTolerance (double _arg)
virtual void SetIRWDiffusivityValue (double _arg)
virtual void SetMaxEval (unsigned int _arg)
virtual void SetMLEstimationStrategy (MaximumLikelihoodEstimationMode _arg)
virtual void SetModelWithFreeWaterComponent (bool _arg)
virtual void SetModelWithRestrictedWaterComponent (bool _arg)
virtual void SetModelWithStaniszComponent (bool _arg)
virtual void SetModelWithStationaryWaterComponent (bool _arg)
void SetMoseVolume (MoseImageType *img)
virtual void SetNoiseType (SignalNoiseType _arg)
virtual void SetNumberOfCoils (unsigned int _arg)
virtual void SetNumberOfCompartments (unsigned int _arg)
void SetOptimizer (std::string &opt)
virtual void SetRadialDiffusivity1Value (double _arg)
virtual void SetRadialDiffusivity2Value (double _arg)
virtual void SetSmallDelta (double _arg)
virtual void SetStaniszDiffusivityValue (double _arg)
virtual void SetUseCommonConcentrations (bool _arg)
virtual void SetUseCommonDiffusivities (bool _arg)
virtual void SetUseCommonExtraAxonalFractions (bool _arg)
virtual void SetUseConstrainedDiffusivity (bool _arg)
virtual void SetUseConstrainedExtraAxonalFraction (bool _arg)
virtual void SetUseConstrainedFreeWaterDiffusivity (bool _arg)
virtual void SetUseConstrainedIRWDiffusivity (bool _arg)
virtual void SetUseConstrainedOrientationConcentration (bool _arg)
virtual void SetUseConstrainedStaniszDiffusivity (bool _arg)
virtual void SetUseConstrainedStaniszRadius (bool _arg)
virtual void SetXTolerance (double _arg)
void WriteMCMOutput (std::string fileName)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
static Pointer New ()
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
double ComputeAICcValue (MCMPointer &mcmValue, double costValue)
Compute AICc value from a cost function value and model.
void ComputeExtraAxonalAndKappaCoarseGrids ()
Computes extra axonal and kappa coarse grids (used for NODDI and DDI initialization)
void ComputeTensorRadialDiffsAndAzimuthCoarseGrids ()
Computes extra axonal and kappa coarse grids (used for tensor final initaialization)
virtual CostFunctionBasePointer CreateCostFunction (std::vector< double > &observedSignals, MCMPointer &mcmModel)
Create a cost function following the noise type and estimation mode.
OptimizerPointer CreateOptimizer (CostFunctionBasePointer &cost, itk::Array< double > &lowerBounds, itk::Array< double > &upperBounds)
Create an optimizer following the optimizer type and estimation mode.
void EstimateFreeWaterModel (MCMPointer &mcmValue, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Specific method for N=0 compartments estimation (only free water)
void ExtraAxonalAndKappaCoarseGridInitialization (MCMPointer &mcmUpdateValue, CostFunctionBasePointer &cost, MCMType::ListType &workVec, ParametersType &p)
Coarse grid initialization of NODDI and DDI models.
void GenerateOutputInformation () ITK_OVERRIDE
double GetCostValue (CostFunctionBasePointer &cost, ParametersType &p)
Utility function to get a value from a cost function.
void GetProfiledInformation (CostFunctionBasePointer &cost, MCMPointer &mcm, double &b0Value, double &sigmaSqValue)
Utility function to get profiled data from the cost function into an MCM model.
virtual void InitializeModelFromSimplifiedOne (MCMPointer &simplifiedModel, MCMPointer &complexModel)
Performs initialization from simplified model with the same number of compartments.
void InitialOrientationsEstimation (MCMPointer &mcmValue, bool authorizedNegativeB0Value, unsigned int currentNumberOfCompartments, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Doing estimation only of multiple orientations.
MCMEstimatorImageFilter ()
void ModelEstimation (MCMPointer &mcmValue, bool authorizedNegativeB0Value, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Doing estimation, calling initialization procedure until ball and zeppelin, returns AICc value.
void OptimizeNonIsotropicCompartments (MCMPointer &mcmValue, unsigned int currentNumberOfCompartments, std::vector< double > &observedSignals, itk::ThreadIdType threadId, double &aiccValue, double &b0Value, double &sigmaSqValue)
Doing estimation of non isotropic compartments (for a given number of anisotropic compartments)
double PerformSingleOptimization (ParametersType &p, CostFunctionBasePointer &cost, itk::Array< double > &lowerBounds, itk::Array< double > &upperBounds)
Performs an optimization of the supplied cost function and parameters using the specified optimizer(s). Returns the optimized parameters.
virtual void SparseInitializeSticks (MCMPointer &complexModel, bool authorizeNegativeB0Value, std::vector< double > &observedSignals, itk::ThreadIdType threadId)
Performs initialization from single DTI.
void TensorCoarseGridInitialization (MCMPointer &mcmUpdateValue, CostFunctionBasePointer &cost, MCMType::ListType &workVec, ParametersType &p)
Coarse grid initialization of tensor model.
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~MCMEstimatorImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (anima::MCMImage< OutputPixelType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (anima::MCMImage< OutputPixelType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class InputPixelType, class OutputPixelType>
class anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >
Definition at line 21 of file animaMCMEstimatorImageFilter.h.
Member Typedef Documentation
BaseCompartmentType
template<class InputPixelType, class OutputPixelType> typedef anima::BaseCompartment anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BaseCompartmentType
Definition at line 45 of file animaMCMEstimatorImageFilter.h.
CompartmentType
template<class InputPixelType, class OutputPixelType> typedef anima::MultiCompartmentModelCreator::CompartmentType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CompartmentType
Definition at line 44 of file animaMCMEstimatorImageFilter.h.
ConstPointer
template<class InputPixelType, class OutputPixelType> typedef itk::SmartPointer<const Self> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ConstPointer
Definition at line 35 of file animaMCMEstimatorImageFilter.h.
CostFunctionBasePointer
template<class InputPixelType, class OutputPixelType> typedef CostFunctionBaseType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CostFunctionBasePointer
Definition at line 54 of file animaMCMEstimatorImageFilter.h.
CostFunctionBaseType
template<class InputPixelType, class OutputPixelType> typedef itk::CostFunction anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CostFunctionBaseType
Definition at line 53 of file animaMCMEstimatorImageFilter.h.
GradientType
template<class InputPixelType, class OutputPixelType> typedef vnl_vector_fixed<double,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GradientType
Definition at line 88 of file animaMCMEstimatorImageFilter.h.
Image4DType
template<class InputPixelType, class OutputPixelType> typedef itk::Image<InputPixelType,4> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Image4DType
Definition at line 29 of file animaMCMEstimatorImageFilter.h.
InputImagePointer
template<class InputPixelType, class OutputPixelType> typedef InputImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InputImagePointer
Definition at line 79 of file animaMCMEstimatorImageFilter.h.
InputImageRegionType
template<class InputPixelType, class OutputPixelType> typedef Superclass::InputImageRegionType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InputImageRegionType
Definition at line 85 of file animaMCMEstimatorImageFilter.h.
InputImageType
template<class InputPixelType, class OutputPixelType> typedef TInputImage anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InputImageType
Image typedef support
Definition at line 77 of file animaMCMEstimatorImageFilter.h.
MaskImageType
template<class InputPixelType, class OutputPixelType> typedef Superclass::MaskImageType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MaskImageType
Superclass typedefs.
Definition at line 84 of file animaMCMEstimatorImageFilter.h.
MCMCreatorType
template<class InputPixelType, class OutputPixelType> typedef anima::MultiCompartmentModelCreator anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMCreatorType
Definition at line 43 of file animaMCMEstimatorImageFilter.h.
MCMPointer
template<class InputPixelType, class OutputPixelType> typedef MCMCreatorType::MCMPointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMPointer
Definition at line 47 of file animaMCMEstimatorImageFilter.h.
MCMType
template<class InputPixelType, class OutputPixelType> typedef MCMCreatorType::MCMType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMType
Definition at line 46 of file animaMCMEstimatorImageFilter.h.
MCMVectorType
template<class InputPixelType, class OutputPixelType> typedef MCMType::ListType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMVectorType
Definition at line 48 of file animaMCMEstimatorImageFilter.h.
ModelImageType
template<class InputPixelType, class OutputPixelType> typedef anima::MCMImage<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelImageType
Definition at line 28 of file animaMCMEstimatorImageFilter.h.
MoseImagePointer
template<class InputPixelType, class OutputPixelType> typedef MoseImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MoseImagePointer
Definition at line 38 of file animaMCMEstimatorImageFilter.h.
MoseImageType
template<class InputPixelType, class OutputPixelType> typedef itk::Image<unsigned char,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MoseImageType
Definition at line 37 of file animaMCMEstimatorImageFilter.h.
OptimizerPointer
template<class InputPixelType, class OutputPixelType> typedef OptimizerType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizerPointer
Definition at line 51 of file animaMCMEstimatorImageFilter.h.
OptimizerType
template<class InputPixelType, class OutputPixelType> typedef itk::NonLinearOptimizer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizerType
Definition at line 50 of file animaMCMEstimatorImageFilter.h.
OutputImagePointer
template<class InputPixelType, class OutputPixelType> typedef OutputImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputImagePointer
Definition at line 81 of file animaMCMEstimatorImageFilter.h.
OutputImageRegionType
template<class InputPixelType, class OutputPixelType> typedef Superclass::OutputImageRegionType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputImageRegionType
Definition at line 86 of file animaMCMEstimatorImageFilter.h.
OutputImageType
template<class InputPixelType, class OutputPixelType> typedef TOutputImage anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputImageType
Definition at line 78 of file animaMCMEstimatorImageFilter.h.
OutputScalarImagePointer
template<class InputPixelType, class OutputPixelType> typedef OutputScalarImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputScalarImagePointer
Definition at line 32 of file animaMCMEstimatorImageFilter.h.
OutputScalarImageType
template<class InputPixelType, class OutputPixelType> typedef itk::Image<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OutputScalarImageType
Definition at line 31 of file animaMCMEstimatorImageFilter.h.
ParametersType
template<class InputPixelType, class OutputPixelType> typedef OptimizerType::ParametersType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ParametersType
Definition at line 52 of file animaMCMEstimatorImageFilter.h.
Pointer
template<class InputPixelType, class OutputPixelType> typedef itk::SmartPointer<Self> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Pointer
Definition at line 34 of file animaMCMEstimatorImageFilter.h.
Self
template<class InputPixelType, class OutputPixelType> typedef MCMEstimatorImageFilter<InputPixelType, OutputPixelType> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Self
Standard class typedefs.
Definition at line 26 of file animaMCMEstimatorImageFilter.h.
Superclass
template<class InputPixelType, class OutputPixelType> typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Superclass
Definition at line 33 of file animaMCMEstimatorImageFilter.h.
TInputImage
template<class InputPixelType, class OutputPixelType> typedef itk::Image<InputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TInputImage
Definition at line 27 of file animaMCMEstimatorImageFilter.h.
TOutputImage
template<class InputPixelType, class OutputPixelType> typedef anima::MCMImage<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TOutputImage
Definition at line 30 of file animaMCMEstimatorImageFilter.h.
VariableLengthVectorType
template<class InputPixelType, class OutputPixelType> typedef OutputImageType::PixelType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::VariableLengthVectorType
Definition at line 80 of file animaMCMEstimatorImageFilter.h.
VectorImagePointer
template<class InputPixelType, class OutputPixelType> typedef VectorImageType::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::VectorImagePointer
Definition at line 41 of file animaMCMEstimatorImageFilter.h.
VectorImageType
template<class InputPixelType, class OutputPixelType> typedef itk::VectorImage<OutputPixelType,3> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::VectorImageType
Definition at line 40 of file animaMCMEstimatorImageFilter.h.
Member Enumeration Documentation
MaximumLikelihoodEstimationMode
template<class InputPixelType, class OutputPixelType> enum anima::MCMEstimatorImageFilter::MaximumLikelihoodEstimationMode
Enumerator
Marginal
Profile
VariableProjection
Definition at line 63 of file animaMCMEstimatorImageFilter.h.
SignalNoiseType
template<class InputPixelType, class OutputPixelType> enum anima::MCMEstimatorImageFilter::SignalNoiseType
Denotes noise type on input signal. Based on this, a different cost function should be created.
Enumerator
Gaussian
NCC
Definition at line 57 of file animaMCMEstimatorImageFilter.h.
Constructor & Destructor Documentation
MCMEstimatorImageFilter()
template<class InputPixelType, class OutputPixelType> anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMEstimatorImageFilter () inline protected
Definition at line 163 of file animaMCMEstimatorImageFilter.h.
References anima::DiffusionBigDelta, anima::DiffusionSmallDelta, anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Gaussian, anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::Marginal, and anima::Tensor.
~MCMEstimatorImageFilter()
template<class InputPixelType, class OutputPixelType> virtual anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter () inline protected virtual
Definition at line 220 of file animaMCMEstimatorImageFilter.h.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CheckComputationMask(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeAICcValue(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeExtraAxonalAndKappaCoarseGrids(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeTensorRadialDiffsAndAzimuthCoarseGrids(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ExtraAxonalAndKappaCoarseGridInitialization(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeModelFromSimplifiedOne(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::PerformSingleOptimization(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TensorCoarseGridInitialization(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ThreadedGenerateData().
Member Function Documentation
AddGradientDirection()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::AddGradientDirection (unsigned int i, GradientType & grad)
Definition at line 33 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNewMCMCreatorInstance().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetGradientStrengths().
BeforeThreadedGenerateData()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >.
Definition at line 132 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeExtraAxonalAndKappaCoarseGrids(), anima::DDI, anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::GetSphereEvenSampling(), anima::NODDI, anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStaniszComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::Stick, anima::Tensor, anima::TransformCartesianToSphericalCoordinates(), and anima::TransformSphericalToCartesianCoordinates().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CheckComputationMask(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
CheckComputationMask()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >.
Definition at line 99 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), and anima::GetBValueFromAcquisitionParameters().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
ComputeAICcValue()
template<class InputPixelType , class OutputPixelType > double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeAICcValue (MCMPointer & mcmValue, double costValue) protected
Compute AICc value from a cost function value and model.
Definition at line 1303 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
ComputeExtraAxonalAndKappaCoarseGrids()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeExtraAxonalAndKappaCoarseGrids () protected
Computes extra axonal and kappa coarse grids (used for NODDI and DDI initialization)
Definition at line 371 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeTensorRadialDiffsAndAzimuthCoarseGrids().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::BeforeThreadedGenerateData(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
ComputeTensorRadialDiffsAndAzimuthCoarseGrids()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeTensorRadialDiffsAndAzimuthCoarseGrids () protected
Computes extra axonal and kappa coarse grids (used for tensor final initaialization)
Definition at line 399 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ThreadedGenerateData().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeExtraAxonalAndKappaCoarseGrids(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
CreateAnother()
template<class InputPixelType, class OutputPixelType> virtual::itk::LightObject::Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateAnother (void) const
CreateCostFunction()
template<class InputPixelType , class OutputPixelType > MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CostFunctionBasePointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction (std::vector< double > & observedSignals, MCMPointer & mcmModel) protected virtual
Create a cost function following the noise type and estimation mode.
Definition at line 711 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), anima::MCMSingleValuedCostFunction::New(), anima::MCMMultipleValuedCostFunction::New(), anima::GaussianMCMCost::New(), and anima::GaussianMCMVariableProjectionCost::New().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
CreateOptimizer()
template<class InputPixelType , class OutputPixelType > MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizerPointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer (CostFunctionBasePointer & cost, itk::Array< double > & lowerBounds, itk::Array< double > & upperBounds) protected
Create an optimizer following the optimizer type and estimation mode.
Definition at line 1142 of file animaMCMEstimatorImageFilter.hxx.
References anima::NLOPTOptimizers::New(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::PerformSingleOptimization().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TensorCoarseGridInitialization(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
EstimateFreeWaterModel()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel (MCMPointer & mcmValue, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Specific method for N=0 compartments estimation (only free water)
Definition at line 609 of file animaMCMEstimatorImageFilter.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStaniszComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MultiCompartmentModelCreator::SetUseConstrainedFreeWaterDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedIRWDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedStaniszDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedStaniszRadius(), and anima::MultiCompartmentModelCreator::SetVariableProjectionEstimationMode().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
ExtraAxonalAndKappaCoarseGridInitialization()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ExtraAxonalAndKappaCoarseGridInitialization (MCMPointer & mcmUpdateValue, CostFunctionBasePointer & cost, MCMType::ListType & workVec, ParametersType & p) protected
Coarse grid initialization of NODDI and DDI models.
Definition at line 993 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TensorCoarseGridInitialization().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
GenerateOutputInformation()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation () protected
Definition at line 54 of file animaMCMEstimatorImageFilter.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MCMImage< TPixel, VImageDimension >::SetDescriptionModel(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStaniszComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNewMCMCreatorInstance(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
GetAICcVolume()
template<class InputPixelType, class OutputPixelType> OutputScalarImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetAICcVolume () inline
Definition at line 143 of file animaMCMEstimatorImageFilter.h.
GetB0Volume()
template<class InputPixelType, class OutputPixelType> OutputScalarImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetB0Volume () inline
Definition at line 144 of file animaMCMEstimatorImageFilter.h.
GetBigDelta()
template<class InputPixelType, class OutputPixelType> virtual double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetBigDelta () virtual
GetCostValue()
template<class InputPixelType , class OutputPixelType > double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue (CostFunctionBasePointer & cost, ParametersType & p) protected
Utility function to get a value from a cost function.
Definition at line 1250 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMMultipleValuedCostFunction::GetInternalCost(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation(), and anima::MCMSingleValuedCostFunction::GetValue().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::PerformSingleOptimization(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
GetGradientDirections()
template<class InputPixelType, class OutputPixelType> std::vector< GradientType >& anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetGradientDirections () inline
Definition at line 137 of file animaMCMEstimatorImageFilter.h.
GetGradientStrengths()
template<class InputPixelType, class OutputPixelType> std::vector<double>& anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetGradientStrengths () inline
Definition at line 134 of file animaMCMEstimatorImageFilter.h.
GetMCMCreator()
template<class InputPixelType, class OutputPixelType> MCMCreatorType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMCMCreator (unsigned int i) inline
Definition at line 139 of file animaMCMEstimatorImageFilter.h.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNewMCMCreatorInstance().
GetMLEstimationStrategy()
template<class InputPixelType, class OutputPixelType> virtual MaximumLikelihoodEstimationMode anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMLEstimationStrategy () virtual
GetMoseVolume()
template<class InputPixelType, class OutputPixelType> MoseImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMoseVolume () inline
Definition at line 148 of file animaMCMEstimatorImageFilter.h.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput().
GetNameOfClass()
template<class InputPixelType, class OutputPixelType> virtual const char* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >.
GetNewMCMCreatorInstance()
template<class InputPixelType , class OutputPixelType > MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::MCMCreatorType * anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNewMCMCreatorInstance () virtual
Definition at line 46 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::AddGradientDirection(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMCMCreator().
GetNoiseType()
template<class InputPixelType, class OutputPixelType> virtual SignalNoiseType anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNoiseType () virtual
GetNumberOfCoils()
template<class InputPixelType, class OutputPixelType> virtual unsigned int anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetNumberOfCoils () virtual
GetOptimizer()
template<class InputPixelType, class OutputPixelType> std::string anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetOptimizer () inline
Definition at line 132 of file animaMCMEstimatorImageFilter.h.
GetProfiledInformation()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation (CostFunctionBasePointer & cost, MCMPointer & mcm, double & b0Value, double & sigmaSqValue) protected
Utility function to get profiled data from the cost function into an MCM model.
Definition at line 1270 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeAICcValue(), anima::MCMSingleValuedCostFunction::GetMCMStructure(), anima::MCMMultipleValuedCostFunction::GetMCMStructure(), anima::MCMSingleValuedCostFunction::GetSigmaSquare(), and anima::MCMMultipleValuedCostFunction::GetSigmaSquare().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
GetSigmaSquareVolume()
template<class InputPixelType, class OutputPixelType> OutputScalarImageType* anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetSigmaSquareVolume () inline
Definition at line 145 of file animaMCMEstimatorImageFilter.h.
GetSmallDelta()
template<class InputPixelType, class OutputPixelType> virtual double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetSmallDelta () virtual
InitializeModelFromSimplifiedOne()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeModelFromSimplifiedOne (MCMPointer & simplifiedModel, MCMPointer & complexModel) protected virtual
Performs initialization from simplified model with the same number of compartments.
Definition at line 1521 of file animaMCMEstimatorImageFilter.hxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
InitialOrientationsEstimation()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation (MCMPointer & mcmValue, bool authorizedNegativeB0Value, unsigned int currentNumberOfCompartments, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Doing estimation only of multiple orientations.
Definition at line 763 of file animaMCMEstimatorImageFilter.hxx.
References anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation(), anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStaniszComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MultiCompartmentModelCreator::SetUseCommonDiffusivities(), anima::MultiCompartmentModelCreator::SetUseConstrainedDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedFreeWaterDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedIRWDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedStaniszDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedStaniszRadius(), anima::MultiCompartmentModelCreator::SetVariableProjectionEstimationMode(), and anima::Stick.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
ModelEstimation()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ModelEstimation (MCMPointer & mcmValue, bool authorizedNegativeB0Value, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Doing estimation, calling initialization procedure until ball and zeppelin, returns AICc value.
Definition at line 833 of file animaMCMEstimatorImageFilter.hxx.
References anima::DDI, anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ExtraAxonalAndKappaCoarseGridInitialization(), anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::NODDI, anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MultiCompartmentModelCreator::SetUseCommonConcentrations(), anima::MultiCompartmentModelCreator::SetUseCommonExtraAxonalFractions(), anima::MultiCompartmentModelCreator::SetUseConstrainedDiffusivity(), anima::MultiCompartmentModelCreator::SetUseConstrainedExtraAxonalFraction(), anima::MultiCompartmentModelCreator::SetUseConstrainedOrientationConcentration(), anima::Stick, anima::Tensor, and anima::Zeppelin.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitialOrientationsEstimation(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
New()
template<class InputPixelType, class OutputPixelType> static Pointer anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::New () static
Method for creation through the object factory.
OptimizeNonIsotropicCompartments()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments (MCMPointer & mcmValue, unsigned int currentNumberOfCompartments, std::vector< double > & observedSignals, itk::ThreadIdType threadId, double & aiccValue, double & b0Value, double & sigmaSqValue) protected
Doing estimation of non isotropic compartments (for a given number of anisotropic compartments)
Definition at line 574 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::EstimateFreeWaterModel().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ThreadedGenerateData(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
PerformSingleOptimization()
template<class InputPixelType , class OutputPixelType > double anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::PerformSingleOptimization (ParametersType & p, CostFunctionBasePointer & cost, itk::Array< double > & lowerBounds, itk::Array< double > & upperBounds) protected
Performs an optimization of the supplied cost function and parameters using the specified optimizer(s). Returns the optimized parameters.
Definition at line 1220 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
SetAbsoluteCostChange()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetAbsoluteCostChange (double _arg) virtual
SetAxialDiffusivityValue()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetAxialDiffusivityValue (double _arg) virtual
SetB0Threshold()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetB0Threshold (double _arg) virtual
SetBigDelta()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetBigDelta (double _arg) virtual
SetCompartmentType()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetCompartmentType (CompartmentType _arg) virtual
SetFindOptimalNumberOfCompartments()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetFindOptimalNumberOfCompartments (bool _arg) virtual
SetGradientStrengths()
template<class InputPixelType, class OutputPixelType> void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetGradientStrengths (std::vector< double > & mb) inline
Definition at line 91 of file animaMCMEstimatorImageFilter.h.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::AddGradientDirection().
SetGTolerance()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetGTolerance (double _arg) virtual
SetIRWDiffusivityValue()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetIRWDiffusivityValue (double _arg) virtual
SetMaxEval()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetMaxEval (unsigned int _arg) virtual
SetMLEstimationStrategy()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetMLEstimationStrategy (MaximumLikelihoodEstimationMode _arg) virtual
SetModelWithFreeWaterComponent()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetModelWithFreeWaterComponent (bool _arg) virtual
SetModelWithRestrictedWaterComponent()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetModelWithRestrictedWaterComponent (bool _arg) virtual
SetModelWithStaniszComponent()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetModelWithStaniszComponent (bool _arg) virtual
SetModelWithStationaryWaterComponent()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetModelWithStationaryWaterComponent (bool _arg) virtual
SetMoseVolume()
template<class InputPixelType, class OutputPixelType> void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetMoseVolume (MoseImageType * img) inline
Definition at line 147 of file animaMCMEstimatorImageFilter.h.
SetNoiseType()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetNoiseType (SignalNoiseType _arg) virtual
SetNumberOfCoils()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetNumberOfCoils (unsigned int _arg) virtual
SetNumberOfCompartments()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetNumberOfCompartments (unsigned int _arg) virtual
SetOptimizer()
template<class InputPixelType, class OutputPixelType> void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetOptimizer (std::string & opt) inline
Definition at line 98 of file animaMCMEstimatorImageFilter.h.
SetRadialDiffusivity1Value()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetRadialDiffusivity1Value (double _arg) virtual
SetRadialDiffusivity2Value()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetRadialDiffusivity2Value (double _arg) virtual
SetSmallDelta()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetSmallDelta (double _arg) virtual
SetStaniszDiffusivityValue()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetStaniszDiffusivityValue (double _arg) virtual
SetUseCommonConcentrations()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseCommonConcentrations (bool _arg) virtual
SetUseCommonDiffusivities()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseCommonDiffusivities (bool _arg) virtual
SetUseCommonExtraAxonalFractions()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseCommonExtraAxonalFractions (bool _arg) virtual
SetUseConstrainedDiffusivity()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedDiffusivity (bool _arg) virtual
SetUseConstrainedExtraAxonalFraction()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedExtraAxonalFraction (bool _arg) virtual
SetUseConstrainedFreeWaterDiffusivity()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedFreeWaterDiffusivity (bool _arg) virtual
SetUseConstrainedIRWDiffusivity()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedIRWDiffusivity (bool _arg) virtual
SetUseConstrainedOrientationConcentration()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedOrientationConcentration (bool _arg) virtual
SetUseConstrainedStaniszDiffusivity()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedStaniszDiffusivity (bool _arg) virtual
SetUseConstrainedStaniszRadius()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetUseConstrainedStaniszRadius (bool _arg) virtual
SetXTolerance()
template<class InputPixelType, class OutputPixelType> virtual void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SetXTolerance (double _arg) virtual
SparseInitializeSticks()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::SparseInitializeSticks (MCMPointer & complexModel, bool authorizeNegativeB0Value, std::vector< double > & observedSignals, itk::ThreadIdType threadId) protected virtual
Performs initialization from single DTI.
Definition at line 1319 of file animaMCMEstimatorImageFilter.hxx.
References anima::ComputeScalarProduct(), anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::InitializeModelFromSimplifiedOne(), anima::NNLSOptimizer::New(), anima::SpectralClusteringFilter< ScalarType >::SetInputData(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::BaseCompartment::SetOrientationPhi(), anima::BaseCompartment::SetOrientationTheta(), and anima::TransformCartesianToSphericalCoordinates().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeAICcValue(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
TensorCoarseGridInitialization()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::TensorCoarseGridInitialization (MCMPointer & mcmUpdateValue, CostFunctionBasePointer & cost, MCMType::ListType & workVec, ParametersType & p) protected
Coarse grid initialization of tensor model.
Definition at line 1043 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateOptimizer(), anima::MCMAxialDiffusivityAddonLowerBound, and anima::MCMDiffusivityLowerBound.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ExtraAxonalAndKappaCoarseGridInitialization(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
ThreadedGenerateData()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 421 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::OptimizeNonIsotropicCompartments().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::ComputeTensorRadialDiffsAndAzimuthCoarseGrids(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::~MCMEstimatorImageFilter().
WriteMCMOutput()
template<class InputPixelType , class OutputPixelType > void anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::WriteMCMOutput (std::string fileName)
Definition at line 83 of file animaMCMEstimatorImageFilter.hxx.
References anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CheckComputationMask(), and anima::MCMFileWriter< PixelType, ImageDimension >::SetInputImage().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetMoseVolume().
The documentation for this class was generated from the following files:
animaMCMEstimatorImageFilter.h
animaMCMEstimatorImageFilter.hxx