ANIMA: anima::SegPerfResults Class Reference
anima::SegPerfResults Class Reference
Class to format and saves results.
#include <animaSegPerfResults.h>
Public Types
enum eMesureName {
eMesureJaccard = 0,
eMesureDice,
eMesureSensibility,
eMesureSpecificity,
eMesurePPV,
eMesureNPV,
eMesureRelativeVolumeError,
eMesureDistHausdorff,
eMesureDistMean,
eMesureDistAverage,
eMesurePPVL,
eMesureSensL,
eMesureF1Test,
eMesureLast
}
Public Member Functions
bool activeMeasurementOutput (eMesureName pi_eVal)
It active the saving of one specific measure. If it set twice time the effect is inverted.
bool save ()
It saves results on text file or xml file in function of class default settings.
SegPerfResults (std::string &pi_pchBaseFileName)
It is the constructor to used.
void setAverageSurfaceDist (float pi_fVal)
Set the result value of average surface distance measure.
void setContourMeanDist (float pi_fVal)
Set the result value of contour mean distance measure.
void setDice (float pi_fVal)
Set the result value of Dice measure.
void setF1test (float pi_fVal)
Set the result value of F1 score of F-test.
void setHausdorffDist (float pi_fVal)
Set the result value of DistHausdorff measure.
void setJaccard (float pi_fVal)
Set the result value of Jaccard measure.
void setNPV (float pi_fVal)
Set the result value of NPV (Negative Predictive Value) measure.
void setPPV (float pi_fVal)
Set the result value of PPV (Positive Predictive Value) measure.
void setPPVL (float pi_fVal)
Set the result value of PPVL measure.
void setRVE (float pi_fVal)
Set the result value of Relative volume error.
void setScreen (bool pi_bEnable=true)
Enable or disable on screen results.
void setSensibility (float pi_fVal)
Set the result value of Sensibility measure.
void setSensL (float pi_fVal)
Set the result value of SensL measure.
void setSpecificity (float pi_fVal)
Set the result value of Specificity measure.
void setTxt (bool pi_bEnable=true)
Enable or disable text file results.
void setXml (bool pi_bEnable=true)
Enable or disable XML file results.
~SegPerfResults ()
Destructor.
Static Public Member Functions
static char const *const *const getMeasureNameTable ()
Get the list of all Measures available.
Detailed Description
Class to format and saves results.
Definition at line 11 of file animaSegPerfResults.h.
Member Enumeration Documentation
eMesureName
enum anima::SegPerfResults::eMesureName
Enumerator
eMesureJaccard
eMesureDice
eMesureSensibility
eMesureSpecificity
eMesurePPV
eMesureNPV
eMesureRelativeVolumeError
eMesureDistHausdorff
eMesureDistMean
eMesureDistAverage
eMesurePPVL
eMesureSensL
eMesureF1Test
eMesureLast
Definition at line 14 of file animaSegPerfResults.h.
Constructor & Destructor Documentation
SegPerfResults()
anima::SegPerfResults::SegPerfResults (std::string & pi_pchBaseFileName)
It is the constructor to used.
Parameters
[in] pi_pchBaseFileName Name of the file to evaluate.
Definition at line 48 of file animaSegPerfResults.cxx.
References eMesureLast.
~SegPerfResults()
anima::SegPerfResults::~SegPerfResults ()
Destructor.
It prints the result on screen if necessary.
Definition at line 68 of file animaSegPerfResults.cxx.
References eMesureLast.
Member Function Documentation
activeMeasurementOutput()
bool anima::SegPerfResults::activeMeasurementOutput (eMesureName pi_eVal)
It active the saving of one specific measure. If it set twice time the effect is inverted.
Returns
True if file(s) recording are success.
Definition at line 170 of file animaSegPerfResults.cxx.
References eMesureLast.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
getMeasureNameTable()
char const *const *const anima::SegPerfResults::getMeasureNameTable () static
Get the list of all Measures available.
Returns
A constant ordered list of measures names.
Definition at line 187 of file animaSegPerfResults.cxx.
Referenced by anima::SegPerfApp::about().
save()
bool anima::SegPerfResults::save ()
It saves results on text file or xml file in function of class default settings.
Returns
True if file(s) recording are success.
Definition at line 97 of file animaSegPerfResults.cxx.
References eMesureLast.
Referenced by anima::SegPerfApp::writeStoredMetricsAndMarks().
setAverageSurfaceDist()
void anima::SegPerfResults::setAverageSurfaceDist (float pi_fVal) inline
Set the result value of average surface distance measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 153 of file animaSegPerfResults.h.
References eMesureDistAverage.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setContourMeanDist()
void anima::SegPerfResults::setContourMeanDist (float pi_fVal) inline
Set the result value of contour mean distance measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 144 of file animaSegPerfResults.h.
References eMesureDistMean.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setDice()
void anima::SegPerfResults::setDice (float pi_fVal) inline
Set the result value of Dice measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 81 of file animaSegPerfResults.h.
References eMesureDice.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setF1test()
void anima::SegPerfResults::setF1test (float pi_fVal) inline
Set the result value of F1 score of F-test.
Parameters
[in] pi_fVal Measure result value.
Definition at line 180 of file animaSegPerfResults.h.
References eMesureF1Test, and eMesureLast.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setHausdorffDist()
void anima::SegPerfResults::setHausdorffDist (float pi_fVal) inline
Set the result value of DistHausdorff measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 135 of file animaSegPerfResults.h.
References eMesureDistHausdorff.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setJaccard()
void anima::SegPerfResults::setJaccard (float pi_fVal) inline
Set the result value of Jaccard measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 72 of file animaSegPerfResults.h.
References eMesureJaccard.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setNPV()
void anima::SegPerfResults::setNPV (float pi_fVal) inline
Set the result value of NPV (Negative Predictive Value) measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 117 of file animaSegPerfResults.h.
References eMesureNPV.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setPPV()
void anima::SegPerfResults::setPPV (float pi_fVal) inline
Set the result value of PPV (Positive Predictive Value) measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 108 of file animaSegPerfResults.h.
References eMesurePPV.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setPPVL()
void anima::SegPerfResults::setPPVL (float pi_fVal) inline
Set the result value of PPVL measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 162 of file animaSegPerfResults.h.
References eMesurePPVL.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setRVE()
void anima::SegPerfResults::setRVE (float pi_fVal) inline
Set the result value of Relative volume error.
Parameters
[in] pi_fVal Measure result value.
Definition at line 126 of file animaSegPerfResults.h.
References eMesureRelativeVolumeError.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setScreen()
void anima::SegPerfResults::setScreen (bool pi_bEnable = true) inline
Enable or disable on screen results.
Parameters
[in] pi_bEnable Enable or disable.
Definition at line 63 of file animaSegPerfResults.h.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setSensibility()
void anima::SegPerfResults::setSensibility (float pi_fVal) inline
Set the result value of Sensibility measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 90 of file animaSegPerfResults.h.
References eMesureSensibility.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setSensL()
void anima::SegPerfResults::setSensL (float pi_fVal) inline
Set the result value of SensL measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 171 of file animaSegPerfResults.h.
References eMesureSensL.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setSpecificity()
void anima::SegPerfResults::setSpecificity (float pi_fVal) inline
Set the result value of Specificity measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 99 of file animaSegPerfResults.h.
References eMesureSpecificity.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setTxt()
void anima::SegPerfResults::setTxt (bool pi_bEnable = true) inline
Enable or disable text file results.
Parameters
[in] pi_bEnable Enable or disable.
Definition at line 45 of file animaSegPerfResults.h.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
setXml()
void anima::SegPerfResults::setXml (bool pi_bEnable = true) inline
Enable or disable XML file results.
Parameters
[in] pi_bEnable Enable or disable.
Definition at line 54 of file animaSegPerfResults.h.
Referenced by anima::SegPerfApp::storeMetricsAndMarks().
The documentation for this class was generated from the following files:
animaSegPerfResults.h
animaSegPerfResults.cxx