ANIMA: anima::MCMSingleValuedCostFunction Class Reference
anima::MCMSingleValuedCostFunction Class Reference
#include <animaMCMSingleValuedCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef InternalCostType::Pointer InternalCostPointer
typedef anima::BaseMCMCost InternalCostType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef MCMSingleValuedCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
InternalCostType::MCMPointer & GetMCMStructure ()
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
double GetSigmaSquare ()
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetInternalCost (InternalCostPointer _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
MCMSingleValuedCostFunction ()
virtual ~MCMSingleValuedCostFunction () ITK_OVERRIDE
Detailed Description
Definition at line 10 of file animaMCMSingleValuedCostFunction.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::MCMSingleValuedCostFunction::ConstPointer
Definition at line 17 of file animaMCMSingleValuedCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::MCMSingleValuedCostFunction::DerivativeType
Definition at line 25 of file animaMCMSingleValuedCostFunction.h.
InternalCostPointer
typedef InternalCostType::Pointer anima::MCMSingleValuedCostFunction::InternalCostPointer
Definition at line 29 of file animaMCMSingleValuedCostFunction.h.
InternalCostType
typedef anima::BaseMCMCost anima::MCMSingleValuedCostFunction::InternalCostType
Definition at line 28 of file animaMCMSingleValuedCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::MCMSingleValuedCostFunction::MeasureType
Definition at line 24 of file animaMCMSingleValuedCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::MCMSingleValuedCostFunction::ParametersType
Definition at line 26 of file animaMCMSingleValuedCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::MCMSingleValuedCostFunction::Pointer
Definition at line 16 of file animaMCMSingleValuedCostFunction.h.
Self
typedef MCMSingleValuedCostFunction anima::MCMSingleValuedCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaMCMSingleValuedCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::MCMSingleValuedCostFunction::Superclass
Definition at line 15 of file animaMCMSingleValuedCostFunction.h.
Constructor & Destructor Documentation
MCMSingleValuedCostFunction()
anima::MCMSingleValuedCostFunction::MCMSingleValuedCostFunction () inline protected
Definition at line 43 of file animaMCMSingleValuedCostFunction.h.
~MCMSingleValuedCostFunction()
virtual anima::MCMSingleValuedCostFunction::~MCMSingleValuedCostFunction () inline protected virtual
Definition at line 48 of file animaMCMSingleValuedCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::MCMSingleValuedCostFunction::CreateAnother (void) const
GetDerivative()
void anima::MCMSingleValuedCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 31 of file animaMCMSingleValuedCostFunction.cxx.
References GetSigmaSquare().
Referenced by GetValue().
GetMCMStructure()
InternalCostType::MCMPointer& anima::MCMSingleValuedCostFunction::GetMCMStructure () inline
Definition at line 38 of file animaMCMSingleValuedCostFunction.h.
References anima::BaseMCMCost::GetMCMStructure().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
GetNameOfClass()
virtual const char* anima::MCMSingleValuedCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::MCMSingleValuedCostFunction::GetNumberOfParameters () const
Definition at line 8 of file animaMCMSingleValuedCostFunction.cxx.
References GetValue().
GetSigmaSquare()
double anima::MCMSingleValuedCostFunction::GetSigmaSquare ()
Definition at line 44 of file animaMCMSingleValuedCostFunction.cxx.
Referenced by GetDerivative(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
GetValue()
MCMSingleValuedCostFunction::MeasureType anima::MCMSingleValuedCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 18 of file animaMCMSingleValuedCostFunction.cxx.
References GetDerivative().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue(), and GetNumberOfParameters().
New()
static Pointer anima::MCMSingleValuedCostFunction::New () static
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction().
SetInternalCost()
virtual void anima::MCMSingleValuedCostFunction::SetInternalCost (InternalCostPointer _arg) virtual
The documentation for this class was generated from the following files:
animaMCMSingleValuedCostFunction.h
animaMCMSingleValuedCostFunction.cxx