ANIMA: anima::SplitAffine3DTransform< TScalarType > Class Template Reference
anima::SplitAffine3DTransform< TScalarType > Class Template Reference
#include <animaSplitAffine3DTransform.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OffsetType OffsetType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::ScalarType ScalarType
typedef SplitAffine3DTransform Self
typedef itk::MatrixOffsetTransformBase< TScalarType, 3, 3 > Superclass
typedef Superclass::TranslationType TranslationType
typedef itk::Vector< TScalarType, 3 > VectorType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const VectorType & GetFirstAngle () const
virtual const VectorType & GetLogScale () const
virtual const char * GetNameOfClass () const
virtual const ParametersType & GetParameters () const ITK_OVERRIDE
virtual const VectorType & GetSecondAngle () const
void SetFirstAngle (const VectorType &angle)
void SetIdentity () ITK_OVERRIDE
void SetLogScale (const VectorType &scale)
virtual void SetParameters (const ParametersType &parameters) ITK_OVERRIDE
void SetSecondAngle (const VectorType &angle)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int InputSpaceDimension = 3
static const unsigned int OutputSpaceDimension = 3
static const unsigned int ParametersDimension = 12
Protected Member Functions
void ComputeMatrix () ITK_OVERRIDE
void ComputeMatrixParameters () ITK_OVERRIDE
MatrixType ComputeRotationMatrix ()
MatrixType ComputeSkewMatrix ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
SplitAffine3DTransform ()
virtual ~SplitAffine3DTransform ()
Detailed Description
template<class TScalarType = double>
class anima::SplitAffine3DTransform< TScalarType >
Definition at line 10 of file animaSplitAffine3DTransform.h.
Member Typedef Documentation
ConstPointer
template<class TScalarType = double> typedef itk::SmartPointer<const Self> anima::SplitAffine3DTransform< TScalarType >::ConstPointer
Definition at line 18 of file animaSplitAffine3DTransform.h.
MatrixType
template<class TScalarType = double> typedef Superclass::MatrixType anima::SplitAffine3DTransform< TScalarType >::MatrixType
Definition at line 34 of file animaSplitAffine3DTransform.h.
OffsetType
template<class TScalarType = double> typedef Superclass::OffsetType anima::SplitAffine3DTransform< TScalarType >::OffsetType
Definition at line 35 of file animaSplitAffine3DTransform.h.
ParametersType
template<class TScalarType = double> typedef Superclass::ParametersType anima::SplitAffine3DTransform< TScalarType >::ParametersType
Parameters Type
Definition at line 32 of file animaSplitAffine3DTransform.h.
Pointer
template<class TScalarType = double> typedef itk::SmartPointer<Self> anima::SplitAffine3DTransform< TScalarType >::Pointer
Definition at line 17 of file animaSplitAffine3DTransform.h.
ScalarType
template<class TScalarType = double> typedef Superclass::ScalarType anima::SplitAffine3DTransform< TScalarType >::ScalarType
Definition at line 33 of file animaSplitAffine3DTransform.h.
Self
template<class TScalarType = double> typedef SplitAffine3DTransform anima::SplitAffine3DTransform< TScalarType >::Self
Standard class typedefs.
Definition at line 15 of file animaSplitAffine3DTransform.h.
Superclass
template<class TScalarType = double> typedef itk::MatrixOffsetTransformBase<TScalarType, 3, 3> anima::SplitAffine3DTransform< TScalarType >::Superclass
Definition at line 16 of file animaSplitAffine3DTransform.h.
TranslationType
template<class TScalarType = double> typedef Superclass::TranslationType anima::SplitAffine3DTransform< TScalarType >::TranslationType
Definition at line 36 of file animaSplitAffine3DTransform.h.
VectorType
template<class TScalarType = double> typedef itk::Vector<TScalarType, 3> anima::SplitAffine3DTransform< TScalarType >::VectorType
Scale & Skew Vector Type.
Definition at line 39 of file animaSplitAffine3DTransform.h.
Constructor & Destructor Documentation
SplitAffine3DTransform()
template<class TScalarType > anima::SplitAffine3DTransform< TScalarType >::SplitAffine3DTransform () protected
Definition at line 12 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::SetParameters().
Referenced by anima::SplitAffine3DTransform< TScalarType >::~SplitAffine3DTransform().
~SplitAffine3DTransform()
template<class TScalarType = double> virtual anima::SplitAffine3DTransform< TScalarType >::~SplitAffine3DTransform () inline protected virtual
Definition at line 65 of file animaSplitAffine3DTransform.h.
References anima::SplitAffine3DTransform< TScalarType >::ComputeMatrix(), anima::SplitAffine3DTransform< TScalarType >::ComputeMatrixParameters(), anima::SplitAffine3DTransform< TScalarType >::ComputeRotationMatrix(), anima::SplitAffine3DTransform< TScalarType >::ComputeSkewMatrix(), anima::SplitAffine3DTransform< TScalarType >::PrintSelf(), and anima::SplitAffine3DTransform< TScalarType >::SplitAffine3DTransform().
Member Function Documentation
ComputeMatrix()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::ComputeMatrix (void) protected
Compute the components of the rotation matrix in the superclass.
Definition at line 134 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::ComputeMatrixParameters(), and anima::Get3DRotationExponential().
Referenced by anima::SplitAffine3DTransform< TScalarType >::SetSecondAngle(), and anima::SplitAffine3DTransform< TScalarType >::~SplitAffine3DTransform().
ComputeMatrixParameters()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::ComputeMatrixParameters () protected
Definition at line 161 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::PrintSelf().
Referenced by anima::SplitAffine3DTransform< TScalarType >::ComputeMatrix(), and anima::SplitAffine3DTransform< TScalarType >::~SplitAffine3DTransform().
ComputeRotationMatrix()
template<class TScalarType = double> MatrixType anima::SplitAffine3DTransform< TScalarType >::ComputeRotationMatrix () protected
Referenced by anima::SplitAffine3DTransform< TScalarType >::~SplitAffine3DTransform().
ComputeSkewMatrix()
template<class TScalarType = double> MatrixType anima::SplitAffine3DTransform< TScalarType >::ComputeSkewMatrix () protected
Referenced by anima::SplitAffine3DTransform< TScalarType >::~SplitAffine3DTransform().
CreateAnother()
template<class TScalarType = double> virtual::itk::LightObject::Pointer anima::SplitAffine3DTransform< TScalarType >::CreateAnother (void) const
GetFirstAngle()
template<class TScalarType = double> virtual const VectorType& anima::SplitAffine3DTransform< TScalarType >::GetFirstAngle () const virtual
GetLogScale()
template<class TScalarType = double> virtual const VectorType& anima::SplitAffine3DTransform< TScalarType >::GetLogScale () const virtual
GetNameOfClass()
template<class TScalarType = double> virtual const char* anima::SplitAffine3DTransform< TScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetParameters()
template<class TScalarType > const SplitAffine3DTransform< TScalarType >::ParametersType & anima::SplitAffine3DTransform< TScalarType >::GetParameters (void) const virtual
Definition at line 61 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::SetIdentity().
Referenced by anima::SplitAffine3DTransform< TScalarType >::SetParameters().
GetSecondAngle()
template<class TScalarType = double> virtual const VectorType& anima::SplitAffine3DTransform< TScalarType >::GetSecondAngle () const virtual
New()
template<class TScalarType = double> static Pointer anima::SplitAffine3DTransform< TScalarType >::New () static
New macro for creation of through a Smart Pointer.
PrintSelf()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const protected
Definition at line 170 of file animaSplitAffine3DTransform.hxx.
Referenced by anima::SplitAffine3DTransform< TScalarType >::ComputeMatrixParameters(), and anima::SplitAffine3DTransform< TScalarType >::~SplitAffine3DTransform().
SetFirstAngle()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::SetFirstAngle (const VectorType & angle)
Definition at line 103 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::SetLogScale().
Referenced by anima::SplitAffine3DTransform< TScalarType >::SetIdentity().
SetIdentity()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::SetIdentity ()
Definition at line 85 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::SetFirstAngle().
Referenced by anima::SplitAffine3DTransform< TScalarType >::GetParameters().
SetLogScale()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::SetLogScale (const VectorType & scale)
Definition at line 113 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::SetSecondAngle().
Referenced by anima::SplitAffine3DTransform< TScalarType >::SetFirstAngle().
SetParameters()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::SetParameters (const ParametersType & parameters) virtual
Set the transformation from a container of parameters This is typically used by optimizers. There are 12 parameters: 0-2 euler angles (first matrix) 3-5 translation 6-8 Scale 9-11 euler angles (second matrix)
Definition at line 24 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::GetParameters().
Referenced by anima::SplitAffine3DTransform< TScalarType >::SplitAffine3DTransform().
SetSecondAngle()
template<class TScalarType > void anima::SplitAffine3DTransform< TScalarType >::SetSecondAngle (const VectorType & angle)
Definition at line 123 of file animaSplitAffine3DTransform.hxx.
References anima::SplitAffine3DTransform< TScalarType >::ComputeMatrix().
Referenced by anima::SplitAffine3DTransform< TScalarType >::SetLogScale().
Member Data Documentation
InputSpaceDimension
template<class TScalarType = double> const unsigned int anima::SplitAffine3DTransform< TScalarType >::InputSpaceDimension = 3 static
Dimension of parameters.
Definition at line 27 of file animaSplitAffine3DTransform.h.
OutputSpaceDimension
template<class TScalarType = double> const unsigned int anima::SplitAffine3DTransform< TScalarType >::OutputSpaceDimension = 3 static
Definition at line 28 of file animaSplitAffine3DTransform.h.
ParametersDimension
template<class TScalarType = double> const unsigned int anima::SplitAffine3DTransform< TScalarType >::ParametersDimension = 12 static
Definition at line 29 of file animaSplitAffine3DTransform.h.
The documentation for this class was generated from the following files:
animaSplitAffine3DTransform.h
animaSplitAffine3DTransform.hxx