ANIMA: anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension > Class Template Reference
anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension > Class Template Reference
#include <animaPyramidalDenseMCMSVFMatchingBridge.h>
Public Types
typedef AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform< typename BaseAgregatorType::InternalScalarType, ImageDimension > AffineTransformType
typedef BalooSVFTransformAgregator< ImageDimension > BalooAgregatorType
typedef BaseTransformAgregator< ImageDimension > BaseAgregatorType
typedef BaseBlockMatchRegistrationType::Pointer BaseBlockMatchRegistrationPointer
typedef anima::BaseBMRegistrationMethod< InputImageType > BaseBlockMatchRegistrationType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef MEstimateAgregatorType::BaseOutputTransformType BaseTransformType
typedef anima::MCMBlockMatcher< InputImageType > BlockMatcherType
typedef itk::SmartPointer< const Self > ConstPointer
typedef DisplacementFieldTransformType::Pointer DisplacementFieldTransformPointer
typedef rpi::DisplacementFieldTransform< typename BaseAgregatorType::ScalarType, ImageDimension > DisplacementFieldTransformType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef anima::MCMImage< float, ImageDimension > InputImageType
typedef InputImageType::InternalPixelType InputInternalPixelType
typedef InputImageType::IOPixelType InputPixelType
typedef anima::MCMLinearInterpolateImageFunction< InputImageType > InterpolatorType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef DenseSVFTransformAgregator< ImageDimension > MEstimateAgregatorType
typedef itk::SmartPointer< Self > Pointer
typedef PyramidType::Pointer PyramidPointer
typedef anima::PyramidImageFilter< InputImageType, InputImageType > PyramidType
typedef PyramidalDenseMCMSVFMatchingBridge Self
typedef itk::ProcessObject Superclass
typedef VelocityFieldType::PixelType VectorType
typedef BaseTransformType::VectorFieldType VelocityFieldType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
Agregator GetAgregator ()
double GetAngleUpperBound ()
unsigned int GetBCHCompositionOrder ()
unsigned int GetBlockSize ()
unsigned int GetBlockSpacing ()
double GetElasticSigma ()
unsigned int GetExponentiationOrder ()
double GetExtrapolationSigma ()
double GetFinalRadius ()
bool GetFiniteStrainImageReorientation ()
unsigned int GetLastPyramidLevel ()
unsigned int GetMaximumIterations ()
double GetMEstimateConvergenceThreshold ()
Metric GetMetric ()
MetricOrientationType GetMetricOrientation ()
float GetMinimalTransformError ()
virtual const char * GetNameOfClass () const
double GetNeighborhoodApproximation ()
unsigned int GetNumberOfPyramidLevels ()
Optimizer GetOptimizer ()
unsigned int GetOptimizerMaximumIterations ()
double GetOutlierSigma ()
InputImagePointer GetOutputImage ()
BaseTransformPointer GetOutputTransform ()
std::string GetOutputTransformFile ()
double GetPercentageKept ()
std::string GetResultFile ()
double GetScaleUpperBound ()
double GetSearchAngleRadius ()
double GetSearchRadius ()
double GetSearchScaleRadius ()
float GetStDevThreshold ()
double GetStepSize ()
SymmetryType GetSymmetryType ()
Transform GetTransform ()
double GetTranslateUpperBound ()
void SetAgregator (Agregator agregator)
void SetAngleUpperBound (double AngleUpperBound)
void SetBCHCompositionOrder (unsigned int order)
void SetBigDelta (double val)
void SetBlockSize (int blockSize)
void SetBlockSpacing (unsigned int blockSpacing)
void SetElasticSigma (double elasticSigma)
void SetExponentiationOrder (unsigned int order)
void SetExtrapolationSigma (double extrapolationSigma)
void SetFinalRadius (double FinalRadius)
void SetFiniteStrainImageReorientation (bool reor)
void SetFloatingImage (InputImagePointer floatingImage)
void SetGradientDirections (std::vector< vnl_vector_fixed< double, 3 > > &grads)
void SetGradientStrengths (std::vector< double > &val)
void SetLastPyramidLevel (unsigned int LastPyramidLevel)
void SetMaximumIterations (unsigned int MaximumIterations)
void SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold)
void SetMetric (Metric metric)
void SetMetricOrientation (MetricOrientationType metricOr)
void SetMinimalTransformError (float MinimalTransformError)
void SetNeighborhoodApproximation (double neighborhoodApproximation)
void SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels)
void SetOptimizer (Optimizer optimizer)
void SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations)
void SetOutlierSigma (double outlierSigma)
void SetOutputTransformFile (std::string outputTransformFile)
void SetPercentageKept (double PercentageKept)
void SetReferenceImage (InputImagePointer referenceImage)
void SetResultFile (std::string resultFile)
void SetScaleUpperBound (double ScaleUpperBound)
void SetSearchAngleRadius (double SearchAngleRadius)
void SetSearchRadius (double SearchRadius)
void SetSearchScaleRadius (double SearchScaleRadius)
void SetSmallDelta (double val)
void SetStDevThreshold (float StDevThreshold)
void SetStepSize (double StepSize)
void SetSymmetryType (SymmetryType sym)
void SetTransform (Transform transform)
void SetTranslateUpperBound (double TranslateUpperBound)
void Update () ITK_OVERRIDE
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual BlockMatcherType * CreateBlockMatcher ()
virtual InterpolatorType * CreateInterpolator (InputImageType *image)
PyramidalDenseMCMSVFMatchingBridge ()
void SetupPyramids ()
virtual ~PyramidalDenseMCMSVFMatchingBridge ()
Detailed Description
template<unsigned int ImageDimension = 3>
class anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >
Definition at line 61 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
Member Typedef Documentation
AffineTransformPointer
template<unsigned int ImageDimension = 3> typedef AffineTransformType::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::AffineTransformPointer
Definition at line 80 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
AffineTransformType
template<unsigned int ImageDimension = 3> typedef itk::AffineTransform<typename BaseAgregatorType::InternalScalarType,ImageDimension> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::AffineTransformType
Definition at line 79 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
BalooAgregatorType
template<unsigned int ImageDimension = 3> typedef BalooSVFTransformAgregator< ImageDimension > anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BalooAgregatorType
Definition at line 72 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
BaseAgregatorType
template<unsigned int ImageDimension = 3> typedef BaseTransformAgregator< ImageDimension > anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BaseAgregatorType
Definition at line 70 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
BaseBlockMatchRegistrationPointer
template<unsigned int ImageDimension = 3> typedef BaseBlockMatchRegistrationType::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationPointer
Definition at line 89 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
BaseBlockMatchRegistrationType
template<unsigned int ImageDimension = 3> typedef anima::BaseBMRegistrationMethod<InputImageType> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationType
Definition at line 88 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
BaseTransformPointer
template<unsigned int ImageDimension = 3> typedef BaseTransformType::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BaseTransformPointer
Definition at line 75 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
BaseTransformType
template<unsigned int ImageDimension = 3> typedef MEstimateAgregatorType::BaseOutputTransformType anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BaseTransformType
Definition at line 74 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
BlockMatcherType
template<unsigned int ImageDimension = 3> typedef anima::MCMBlockMatcher<InputImageType> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BlockMatcherType
Definition at line 92 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
ConstPointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<const Self> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::ConstPointer
Definition at line 102 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
DisplacementFieldTransformPointer
template<unsigned int ImageDimension = 3> typedef DisplacementFieldTransformType::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::DisplacementFieldTransformPointer
Definition at line 83 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
DisplacementFieldTransformType
template<unsigned int ImageDimension = 3> typedef rpi::DisplacementFieldTransform<typename BaseAgregatorType::ScalarType, ImageDimension> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::DisplacementFieldTransformType
Definition at line 82 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
InputImageConstPointer
template<unsigned int ImageDimension = 3> typedef InputImageType::ConstPointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::InputImageConstPointer
Definition at line 67 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
InputImagePointer
template<unsigned int ImageDimension = 3> typedef InputImageType::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::InputImagePointer
Definition at line 66 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
InputImageType
template<unsigned int ImageDimension = 3> typedef anima::MCMImage<float,ImageDimension> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::InputImageType
Definition at line 64 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
InputInternalPixelType
template<unsigned int ImageDimension = 3> typedef InputImageType::InternalPixelType anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::InputInternalPixelType
Definition at line 68 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
InputPixelType
template<unsigned int ImageDimension = 3> typedef InputImageType::IOPixelType anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::InputPixelType
Definition at line 65 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
InterpolatorType
template<unsigned int ImageDimension = 3> typedef anima::MCMLinearInterpolateImageFunction<InputImageType> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::InterpolatorType
Definition at line 91 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
MCModelPointer
template<unsigned int ImageDimension = 3> typedef MCModelType::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::MCModelPointer
Definition at line 95 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
MCModelType
template<unsigned int ImageDimension = 3> typedef anima::MultiCompartmentModel anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::MCModelType
Definition at line 94 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
MEstimateAgregatorType
template<unsigned int ImageDimension = 3> typedef DenseSVFTransformAgregator< ImageDimension > anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::MEstimateAgregatorType
Definition at line 71 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
Pointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<Self> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Pointer
Definition at line 101 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
PyramidPointer
template<unsigned int ImageDimension = 3> typedef PyramidType::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::PyramidPointer
Definition at line 86 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
PyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<InputImageType,InputImageType> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::PyramidType
Definition at line 85 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
Self
template<unsigned int ImageDimension = 3> typedef PyramidalDenseMCMSVFMatchingBridge anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Self
SmartPointer typedef support
Definition at line 98 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
Superclass
template<unsigned int ImageDimension = 3> typedef itk::ProcessObject anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Superclass
Definition at line 99 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
VectorType
template<unsigned int ImageDimension = 3> typedef VelocityFieldType::PixelType anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::VectorType
Definition at line 77 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
VelocityFieldType
template<unsigned int ImageDimension = 3> typedef BaseTransformType::VectorFieldType anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::VelocityFieldType
Definition at line 76 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
Constructor & Destructor Documentation
PyramidalDenseMCMSVFMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::PyramidalDenseMCMSVFMatchingBridge () protected
Definition at line 21 of file animaPyramidalDenseMCMSVFMatchingBridge.hxx.
References Asymmetric, Baloo, Bobyqa, anima::DiffusionBigDelta, anima::DiffusionSmallDelta, FiniteStrain, MCMOneToOneBasicMeanSquares, and Translation.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetGradientDirections().
~PyramidalDenseMCMSVFMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::~PyramidalDenseMCMSVFMatchingBridge () protected virtual
Definition at line 73 of file animaPyramidalDenseMCMSVFMatchingBridge.hxx.
References anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateInterpolator().
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetGradientDirections().
Member Function Documentation
CreateAnother()
template<unsigned int ImageDimension = 3> virtual::itk::LightObject::Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateAnother (void) const
CreateBlockMatcher()
template<unsigned int ImageDimension> PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::BlockMatcherType * anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateBlockMatcher () protected virtual
Definition at line 92 of file animaPyramidalDenseMCMSVFMatchingBridge.hxx.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateInterpolator(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetGradientDirections().
CreateInterpolator()
template<unsigned int ImageDimension> PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::InterpolatorType * anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateInterpolator (InputImageType * image) protected virtual
Definition at line 80 of file animaPyramidalDenseMCMSVFMatchingBridge.hxx.
References anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateBlockMatcher(), and anima::MCMImage< TPixel, VImageDimension >::GetDescriptionModel().
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetGradientDirections(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::~PyramidalDenseMCMSVFMatchingBridge().
GetAgregator()
template<unsigned int ImageDimension = 3> Agregator anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetAgregator () inline
Definition at line 195 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetAngleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetAngleUpperBound () inline
Definition at line 189 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetBCHCompositionOrder()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetBCHCompositionOrder () inline
Definition at line 213 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetBlockSize()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetBlockSize () inline
Definition at line 135 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetBlockSpacing()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetBlockSpacing () inline
Definition at line 138 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetElasticSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetElasticSigma () inline
Definition at line 201 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetExponentiationOrder()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetExponentiationOrder () inline
Definition at line 216 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetExtrapolationSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetExtrapolationSigma () inline
Definition at line 198 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetFinalRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetFinalRadius () inline
Definition at line 180 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetFiniteStrainImageReorientation()
template<unsigned int ImageDimension = 3> bool anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetFiniteStrainImageReorientation () inline
Definition at line 156 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetLastPyramidLevel()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetLastPyramidLevel () inline
Definition at line 222 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetMaximumIterations () inline
Definition at line 162 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetMEstimateConvergenceThreshold () inline
Definition at line 207 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetMetric()
template<unsigned int ImageDimension = 3> Metric anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetMetric () inline
Definition at line 150 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetMetricOrientation()
template<unsigned int ImageDimension = 3> MetricOrientationType anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetMetricOrientation () inline
Definition at line 153 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetMinimalTransformError()
template<unsigned int ImageDimension = 3> float anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetMinimalTransformError () inline
Definition at line 165 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetNameOfClass()
template<unsigned int ImageDimension = 3> virtual const char* anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetNameOfClass () const virtual
GetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetNeighborhoodApproximation () inline
Definition at line 210 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetNumberOfPyramidLevels () inline
Definition at line 219 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetOptimizer()
template<unsigned int ImageDimension = 3> Optimizer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetOptimizer () inline
Definition at line 159 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetOptimizerMaximumIterations () inline
Definition at line 168 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetOutlierSigma()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetOutlierSigma () inline
Definition at line 204 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetOutputImage()
template<unsigned int ImageDimension = 3> InputImagePointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetOutputImage () inline
Definition at line 118 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetOutputTransform()
template<unsigned int ImageDimension = 3> BaseTransformPointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetOutputTransform () inline
Getter for transform
Definition at line 123 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetOutputTransformFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetOutputTransformFile () inline
Definition at line 132 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetPercentageKept()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetPercentageKept () inline
Definition at line 225 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetResultFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetResultFile () inline
Setter/Getter for parameters
Definition at line 129 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetScaleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetScaleUpperBound () inline
Definition at line 192 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetSearchAngleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetSearchAngleRadius () inline
Definition at line 174 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetSearchRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetSearchRadius () inline
Definition at line 171 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetSearchScaleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetSearchScaleRadius () inline
Definition at line 177 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetStDevThreshold()
template<unsigned int ImageDimension = 3> float anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetStDevThreshold () inline
Definition at line 141 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetStepSize()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetStepSize () inline
Definition at line 183 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetSymmetryType()
template<unsigned int ImageDimension = 3> SymmetryType anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetSymmetryType () inline
Definition at line 144 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetTransform()
template<unsigned int ImageDimension = 3> Transform anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetTransform () inline
Definition at line 147 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
GetTranslateUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::GetTranslateUpperBound () inline
Definition at line 186 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
New()
template<unsigned int ImageDimension = 3> static Pointer anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::New () static
SetAgregator()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetAgregator (Agregator agregator) inline
Definition at line 196 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetAngleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetAngleUpperBound (double AngleUpperBound) inline
Definition at line 190 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetBCHCompositionOrder()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetBCHCompositionOrder (unsigned int order) inline
Definition at line 214 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetBigDelta()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetBigDelta (double val) inline
Definition at line 229 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetBlockSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetBlockSize (int blockSize) inline
Definition at line 136 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetBlockSpacing()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetBlockSpacing (unsigned int blockSpacing) inline
Definition at line 139 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetElasticSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetElasticSigma (double elasticSigma) inline
Definition at line 202 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetExponentiationOrder()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetExponentiationOrder (unsigned int order) inline
Definition at line 217 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetExtrapolationSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetExtrapolationSigma (double extrapolationSigma) inline
Definition at line 199 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetFinalRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetFinalRadius (double FinalRadius) inline
Definition at line 181 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetFiniteStrainImageReorientation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetFiniteStrainImageReorientation (bool reor) inline
Definition at line 157 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetFloatingImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetFloatingImage (InputImagePointer floatingImage) inline
Definition at line 116 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetGradientDirections()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetGradientDirections (std::vector< vnl_vector_fixed< double, 3 > > & grads) inline
Definition at line 232 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
References anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateBlockMatcher(), anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateInterpolator(), anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::PyramidalDenseMCMSVFMatchingBridge(), anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetupPyramids(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::~PyramidalDenseMCMSVFMatchingBridge().
SetGradientStrengths()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetGradientStrengths (std::vector< double > & val) inline
Definition at line 230 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetLastPyramidLevel()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetLastPyramidLevel (unsigned int LastPyramidLevel) inline
Definition at line 223 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetMaximumIterations (unsigned int MaximumIterations) inline
Definition at line 163 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetMEstimateConvergenceThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetMEstimateConvergenceThreshold (double mEstimateConvergenceThreshold) inline
Definition at line 208 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetMetric()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetMetric (Metric metric) inline
Definition at line 151 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetMetricOrientation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetMetricOrientation (MetricOrientationType metricOr) inline
Definition at line 154 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetMinimalTransformError()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetMinimalTransformError (float MinimalTransformError) inline
Definition at line 166 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetNeighborhoodApproximation()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetNeighborhoodApproximation (double neighborhoodApproximation) inline
Definition at line 211 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels) inline
Definition at line 220 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetOptimizer()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetOptimizer (Optimizer optimizer) inline
Definition at line 160 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations) inline
Definition at line 169 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetOutlierSigma()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetOutlierSigma (double outlierSigma) inline
Definition at line 205 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetOutputTransformFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetOutputTransformFile (std::string outputTransformFile) inline
Definition at line 133 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetPercentageKept()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetPercentageKept (double PercentageKept) inline
Definition at line 226 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetReferenceImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetReferenceImage (InputImagePointer referenceImage) inline
Setter for images
Definition at line 115 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetResultFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetResultFile (std::string resultFile) inline
Definition at line 130 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetScaleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetScaleUpperBound (double ScaleUpperBound) inline
Definition at line 193 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetSearchAngleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetSearchAngleRadius (double SearchAngleRadius) inline
Definition at line 175 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetSearchRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetSearchRadius (double SearchRadius) inline
Definition at line 172 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetSearchScaleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetSearchScaleRadius (double SearchScaleRadius) inline
Definition at line 178 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetSmallDelta()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetSmallDelta (double val) inline
Definition at line 228 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetStDevThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetStDevThreshold (float StDevThreshold) inline
Definition at line 142 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetStepSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetStepSize (double StepSize) inline
Definition at line 184 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetSymmetryType()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetSymmetryType (SymmetryType sym) inline
Definition at line 145 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetTransform()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetTransform (Transform transform) inline
Definition at line 148 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetTranslateUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetTranslateUpperBound (double TranslateUpperBound) inline
Definition at line 187 of file animaPyramidalDenseMCMSVFMatchingBridge.h.
SetupPyramids()
template<unsigned int ImageDimension> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetupPyramids () protected
Definition at line 492 of file animaPyramidalDenseMCMSVFMatchingBridge.hxx.
Referenced by anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::SetGradientDirections().
Update()
template<unsigned int ImageDimension> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::Update ()
Definition at line 100 of file animaPyramidalDenseMCMSVFMatchingBridge.hxx.
References Affine, Asymmetric, Bobyqa, Exhaustive, FiniteStrain, anima::GetSVFExponential(), Kissing, MCMBasicMeanSquares, MCMCorrelation, MCMMeanSquares, MCMOneToOneBasicMeanSquares, MSmoother, MTCorrelation, None, PPD, Rigid, anima::BaseAffineBlockMatcher< TInputImageType >::SetAngleMax(), anima::MCMBlockMatcher< TInputImageType >::SetBigDelta(), anima::BaseBlockMatcher< TInputImageType >::SetBlockPercentageKept(), anima::BaseBlockMatcher< TInputImageType >::SetBlockSize(), anima::BaseBlockMatcher< TInputImageType >::SetBlockSpacing(), anima::BaseAffineBlockMatcher< TInputImageType >::SetBlockTransformType(), anima::BaseBlockMatcher< TInputImageType >::SetBlockVarianceThreshold(), anima::DenseSVFTransformAgregator< NDimensions >::SetDistanceBoundary(), anima::BalooSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::DenseSVFTransformAgregator< NDimensions >::SetExtrapolationSigma(), anima::BaseBlockMatcher< TInputImageType >::SetFinalRadius(), anima::BalooSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::DenseSVFTransformAgregator< NDimensions >::SetGeometryInformation(), anima::MCMBlockMatcher< TInputImageType >::SetGradientDirections(), anima::MCMBlockMatcher< TInputImageType >::SetGradientStrengths(), anima::DenseSVFTransformAgregator< NDimensions >::SetMEstimateConvergenceThreshold(), anima::MCMBlockMatcher< TInputImageType >::SetModelRotationType(), anima::DenseSVFTransformAgregator< NDimensions >::SetNeighborhoodHalfSize(), anima::DenseSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::BalooSVFTransformAgregator< NDimensions >::SetNumberOfThreads(), anima::BaseBlockMatcher< TInputImageType >::SetNumberOfThreads(), anima::BaseBlockMatcher< TInputImageType >::SetOptimizerMaximumIterations(), anima::BaseBlockMatcher< TInputImageType >::SetOptimizerType(), anima::DenseSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), anima::BalooSVFTransformAgregator< NDimensions >::SetOutlierRejectionSigma(), anima::BaseTransformAgregator< NDimensions >::SetOutputTransformType(), anima::BaseAffineBlockMatcher< TInputImageType >::SetScaleMax(), anima::BaseAffineBlockMatcher< TInputImageType >::SetSearchAngleRadius(), anima::BaseBlockMatcher< TInputImageType >::SetSearchRadius(), anima::BaseAffineBlockMatcher< TInputImageType >::SetSearchScaleRadius(), anima::MCMBlockMatcher< TInputImageType >::SetSimilarityType(), anima::MCMBlockMatcher< TInputImageType >::SetSmallDelta(), anima::BaseBlockMatcher< TInputImageType >::SetStepSize(), anima::BaseAffineBlockMatcher< TInputImageType >::SetTranslateMax(), Symmetric, and Translation.
WriteOutputs()
template<unsigned int ImageDimension> void anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::WriteOutputs ()
Definition at line 473 of file animaPyramidalDenseMCMSVFMatchingBridge.hxx.
References anima::MCMFileWriter< PixelType, ImageDimension >::SetFileName(), anima::MCMFileWriter< PixelType, ImageDimension >::SetInputImage(), and anima::MCMFileWriter< PixelType, ImageDimension >::Update().
The documentation for this class was generated from the following files:
animaPyramidalDenseMCMSVFMatchingBridge.h
animaPyramidalDenseMCMSVFMatchingBridge.hxx