ANIMA: anima::MultiT2EPGRelaxometryCostFunction Class Reference
anima::MultiT2EPGRelaxometryCostFunction Class Reference
Cost function for estimating B1 from T2 relaxometry acquisition, following a multi-T2 EPG decay model.
#include <animaMultiT2EPGRelaxometryCostFunction.h>
Public Types
typedef std::vector< std::complex< double > > ComplexVectorType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef std::vector< ComplexVectorType > MatrixType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef MultiT2EPGRelaxometryCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetB1OnExcitationAngle (bool _arg)
virtual void SetEchoSpacing (double _arg)
virtual void SetExcitationFlipAngle (double _arg)
virtual void SetM0Value (double _arg)
virtual void SetT1Value (double _arg)
void SetT2FlipAngles (std::vector< double > &flipAngles)
void SetT2RelaxometrySignals (ParametersType &relaxoSignals)
void SetT2Values (std::vector< double > &values)
void SetT2Weights (ParametersType &weights)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
MultiT2EPGRelaxometryCostFunction ()
virtual ~MultiT2EPGRelaxometryCostFunction ()
Detailed Description
Cost function for estimating B1 from T2 relaxometry acquisition, following a multi-T2 EPG decay model.
Definition at line 13 of file animaMultiT2EPGRelaxometryCostFunction.h.
Member Typedef Documentation
ComplexVectorType
typedef std::vector< std::complex <double> > anima::MultiT2EPGRelaxometryCostFunction::ComplexVectorType
Definition at line 31 of file animaMultiT2EPGRelaxometryCostFunction.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::MultiT2EPGRelaxometryCostFunction::ConstPointer
Definition at line 21 of file animaMultiT2EPGRelaxometryCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::MultiT2EPGRelaxometryCostFunction::DerivativeType
Definition at line 29 of file animaMultiT2EPGRelaxometryCostFunction.h.
MatrixType
typedef std::vector<ComplexVectorType> anima::MultiT2EPGRelaxometryCostFunction::MatrixType
Definition at line 32 of file animaMultiT2EPGRelaxometryCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::MultiT2EPGRelaxometryCostFunction::MeasureType
Definition at line 26 of file animaMultiT2EPGRelaxometryCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::MultiT2EPGRelaxometryCostFunction::ParametersType
Definition at line 30 of file animaMultiT2EPGRelaxometryCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::MultiT2EPGRelaxometryCostFunction::Pointer
Definition at line 20 of file animaMultiT2EPGRelaxometryCostFunction.h.
Self
typedef MultiT2EPGRelaxometryCostFunction anima::MultiT2EPGRelaxometryCostFunction::Self
Standard class typedefs.
Definition at line 18 of file animaMultiT2EPGRelaxometryCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::MultiT2EPGRelaxometryCostFunction::Superclass
Definition at line 19 of file animaMultiT2EPGRelaxometryCostFunction.h.
Constructor & Destructor Documentation
MultiT2EPGRelaxometryCostFunction()
anima::MultiT2EPGRelaxometryCostFunction::MultiT2EPGRelaxometryCostFunction () inline protected
Definition at line 57 of file animaMultiT2EPGRelaxometryCostFunction.h.
~MultiT2EPGRelaxometryCostFunction()
virtual anima::MultiT2EPGRelaxometryCostFunction::~MultiT2EPGRelaxometryCostFunction () inline protected virtual
Definition at line 67 of file animaMultiT2EPGRelaxometryCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::MultiT2EPGRelaxometryCostFunction::CreateAnother (void) const
GetDerivative()
virtual void anima::MultiT2EPGRelaxometryCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const inline virtual
Definition at line 35 of file animaMultiT2EPGRelaxometryCostFunction.h.
GetNameOfClass()
virtual const char* anima::MultiT2EPGRelaxometryCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::MultiT2EPGRelaxometryCostFunction::GetNumberOfParameters () const inline
Definition at line 51 of file animaMultiT2EPGRelaxometryCostFunction.h.
GetValue()
MultiT2EPGRelaxometryCostFunction::MeasureType anima::MultiT2EPGRelaxometryCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 8 of file animaMultiT2EPGRelaxometryCostFunction.cxx.
References anima::EPGSignalSimulator::GetValue(), anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), and anima::EPGSignalSimulator::SetNumberOfEchoes().
New()
static Pointer anima::MultiT2EPGRelaxometryCostFunction::New () static
SetB1OnExcitationAngle()
virtual void anima::MultiT2EPGRelaxometryCostFunction::SetB1OnExcitationAngle (bool _arg) virtual
SetEchoSpacing()
virtual void anima::MultiT2EPGRelaxometryCostFunction::SetEchoSpacing (double _arg) virtual
SetExcitationFlipAngle()
virtual void anima::MultiT2EPGRelaxometryCostFunction::SetExcitationFlipAngle (double _arg) virtual
SetM0Value()
virtual void anima::MultiT2EPGRelaxometryCostFunction::SetM0Value (double _arg) virtual
SetT1Value()
virtual void anima::MultiT2EPGRelaxometryCostFunction::SetT1Value (double _arg) virtual
SetT2FlipAngles()
void anima::MultiT2EPGRelaxometryCostFunction::SetT2FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 41 of file animaMultiT2EPGRelaxometryCostFunction.h.
SetT2RelaxometrySignals()
void anima::MultiT2EPGRelaxometryCostFunction::SetT2RelaxometrySignals (ParametersType & relaxoSignals) inline
Definition at line 40 of file animaMultiT2EPGRelaxometryCostFunction.h.
SetT2Values()
void anima::MultiT2EPGRelaxometryCostFunction::SetT2Values (std::vector< double > & values) inline
Definition at line 46 of file animaMultiT2EPGRelaxometryCostFunction.h.
SetT2Weights()
void anima::MultiT2EPGRelaxometryCostFunction::SetT2Weights (ParametersType & weights) inline
Definition at line 47 of file animaMultiT2EPGRelaxometryCostFunction.h.
The documentation for this class was generated from the following files:
animaMultiT2EPGRelaxometryCostFunction.h
animaMultiT2EPGRelaxometryCostFunction.cxx