ANIMA: anima::FDRCorrectImageFilter< PixelScalarType > Class Template Reference
anima::FDRCorrectImageFilter< PixelScalarType > Class Template Reference
#include <animaFDRCorrectImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef TInputImage::PixelType InputImagePixel
typedef TInputImage::Pointer InputImagePointer
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, 3 > MaskImageType
typedef TOutputImage::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef FDRCorrectImageFilter< PixelScalarType > Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::Image< PixelScalarType, 3 > TInputImage
typedef itk::Image< unsigned char, 3 > TOutputImage
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetBYCorrection (bool _arg)
virtual void SetMaskImage (MaskImagePointer _arg)
virtual void SetQValue (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
FDRCorrectImageFilter ()
void GenerateData () ITK_OVERRIDE
virtual ~FDRCorrectImageFilter ()
Detailed Description
template<class PixelScalarType>
class anima::FDRCorrectImageFilter< PixelScalarType >
Definition at line 9 of file animaFDRCorrectImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class PixelScalarType > typedef itk::SmartPointer<const Self> anima::FDRCorrectImageFilter< PixelScalarType >::ConstPointer
Definition at line 19 of file animaFDRCorrectImageFilter.h.
InputImagePixel
template<class PixelScalarType > typedef TInputImage::PixelType anima::FDRCorrectImageFilter< PixelScalarType >::InputImagePixel
Definition at line 28 of file animaFDRCorrectImageFilter.h.
InputImagePointer
template<class PixelScalarType > typedef TInputImage::Pointer anima::FDRCorrectImageFilter< PixelScalarType >::InputImagePointer
Definition at line 27 of file animaFDRCorrectImageFilter.h.
MaskImagePointer
template<class PixelScalarType > typedef MaskImageType::Pointer anima::FDRCorrectImageFilter< PixelScalarType >::MaskImagePointer
Definition at line 32 of file animaFDRCorrectImageFilter.h.
MaskImageType
template<class PixelScalarType > typedef itk::Image<unsigned char, 3> anima::FDRCorrectImageFilter< PixelScalarType >::MaskImageType
Definition at line 31 of file animaFDRCorrectImageFilter.h.
OutputImagePointer
template<class PixelScalarType > typedef TOutputImage::Pointer anima::FDRCorrectImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 29 of file animaFDRCorrectImageFilter.h.
OutputImageRegionType
template<class PixelScalarType > typedef Superclass::OutputImageRegionType anima::FDRCorrectImageFilter< PixelScalarType >::OutputImageRegionType
Superclass typedefs.
Definition at line 35 of file animaFDRCorrectImageFilter.h.
Pointer
template<class PixelScalarType > typedef itk::SmartPointer<Self> anima::FDRCorrectImageFilter< PixelScalarType >::Pointer
Definition at line 18 of file animaFDRCorrectImageFilter.h.
Self
template<class PixelScalarType > typedef FDRCorrectImageFilter<PixelScalarType> anima::FDRCorrectImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 14 of file animaFDRCorrectImageFilter.h.
Superclass
template<class PixelScalarType > typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::FDRCorrectImageFilter< PixelScalarType >::Superclass
Definition at line 17 of file animaFDRCorrectImageFilter.h.
TInputImage
template<class PixelScalarType > typedef itk::Image<PixelScalarType, 3> anima::FDRCorrectImageFilter< PixelScalarType >::TInputImage
Definition at line 15 of file animaFDRCorrectImageFilter.h.
TOutputImage
template<class PixelScalarType > typedef itk::Image<unsigned char, 3> anima::FDRCorrectImageFilter< PixelScalarType >::TOutputImage
Definition at line 16 of file animaFDRCorrectImageFilter.h.
Constructor & Destructor Documentation
FDRCorrectImageFilter()
template<class PixelScalarType > anima::FDRCorrectImageFilter< PixelScalarType >::FDRCorrectImageFilter () inline protected
Definition at line 42 of file animaFDRCorrectImageFilter.h.
~FDRCorrectImageFilter()
template<class PixelScalarType > virtual anima::FDRCorrectImageFilter< PixelScalarType >::~FDRCorrectImageFilter () inline protected virtual
Definition at line 49 of file animaFDRCorrectImageFilter.h.
References anima::FDRCorrectImageFilter< PixelScalarType >::GenerateData().
Member Function Documentation
CreateAnother()
template<class PixelScalarType > virtual::itk::LightObject::Pointer anima::FDRCorrectImageFilter< PixelScalarType >::CreateAnother (void) const
GenerateData()
template<class PixelScalarType > void anima::FDRCorrectImageFilter< PixelScalarType >::GenerateData () protected
Definition at line 15 of file animaFDRCorrectImageFilter.hxx.
References anima::BHCorrection(), and anima::BYCorrection().
Referenced by anima::FDRCorrectImageFilter< PixelScalarType >::~FDRCorrectImageFilter().
GetNameOfClass()
template<class PixelScalarType > virtual const char* anima::FDRCorrectImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
New()
template<class PixelScalarType > static Pointer anima::FDRCorrectImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
SetBYCorrection()
template<class PixelScalarType > virtual void anima::FDRCorrectImageFilter< PixelScalarType >::SetBYCorrection (bool _arg) virtual
SetMaskImage()
template<class PixelScalarType > virtual void anima::FDRCorrectImageFilter< PixelScalarType >::SetMaskImage (MaskImagePointer _arg) virtual
SetQValue()
template<class PixelScalarType > virtual void anima::FDRCorrectImageFilter< PixelScalarType >::SetQValue (double _arg) virtual
The documentation for this class was generated from the following files:
animaFDRCorrectImageFilter.h
animaFDRCorrectImageFilter.hxx