ANIMA: anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType > Class Template Reference
anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType > Class Template Reference
#include <animaNonLocalT2DistributionPatchSearcher.h>
Public Types
typedef DataImageType::ConstPointer DataImageConstPointer
typedef DataImageType::Pointer DataImagePointer
typedef Superclass::ImageRegionType ImageRegionType
typedef Superclass::IndexType IndexType
typedef anima::NonLocalPatchBaseSearcher< ImageType > Superclass
Public Types inherited from anima::NonLocalPatchBaseSearcher< ImageType >
typedef ImageType::Pointer ImagePointer
typedef ImageType::RegionType ImageRegionType
typedef ImageType::IndexType IndexType
typedef ImageType::PixelType PixelType
typedef ImageType::SizeType SizeType
Public Member Functions
void AddMeanImage (DataImageType *arg)
void AddPatchTestImage (const DataImageType *arg)
void AddVarImage (DataImageType *arg)
NonLocalT2DistributionPatchSearcher ()
void SetBetaParameter (double arg)
void SetMeanMinThreshold (double arg)
void SetNoiseCovariances (std::vector< double > &arg)
void SetVarMinThreshold (double arg)
virtual ~NonLocalT2DistributionPatchSearcher ()
Public Member Functions inherited from anima::NonLocalPatchBaseSearcher< ImageType >
ImageType * GetComparisonImage (unsigned int index)
virtual const std::vector< PixelType > & GetDatabaseSamples () const
virtual const std::vector< double > & GetDatabaseWeights () const
itkGetObjectMacro (InputImage, ImageType) void AddComparisonImage(ImageType *arg)
NonLocalPatchBaseSearcher ()
void SetInputImage (ImageType *arg)
void SetMaxAbsDisp (unsigned int arg)
void SetPatchHalfSize (unsigned int arg)
void SetSearchStepSize (unsigned int arg)
void SetWeightThreshold (double arg)
void UpdateAtPosition (const IndexType &dataIndex)
virtual ~NonLocalPatchBaseSearcher ()
Protected Member Functions
virtual double ComputeWeightValue (unsigned int index, ImageRegionType &refPatch, ImageRegionType &movingPatch)
virtual bool TestPatchConformity (unsigned int index, const IndexType &refIndex, const IndexType &movingIndex)
Protected Member Functions inherited from anima::NonLocalPatchBaseSearcher< ImageType >
virtual void ComputeComparisonProperties (unsigned int index, ImageRegionType &movingPatch)
virtual void ComputeInputProperties (const IndexType &refIndex, ImageRegionType &refPatch)
Detailed Description
template<class ImageType, class DataImageType>
class anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >
Definition at line 9 of file animaNonLocalT2DistributionPatchSearcher.h.
Member Typedef Documentation
DataImageConstPointer
template<class ImageType , class DataImageType > typedef DataImageType::ConstPointer anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::DataImageConstPointer
Definition at line 13 of file animaNonLocalT2DistributionPatchSearcher.h.
DataImagePointer
template<class ImageType , class DataImageType > typedef DataImageType::Pointer anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::DataImagePointer
Definition at line 12 of file animaNonLocalT2DistributionPatchSearcher.h.
ImageRegionType
template<class ImageType , class DataImageType > typedef Superclass::ImageRegionType anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::ImageRegionType
Definition at line 15 of file animaNonLocalT2DistributionPatchSearcher.h.
IndexType
template<class ImageType , class DataImageType > typedef Superclass::IndexType anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::IndexType
Definition at line 16 of file animaNonLocalT2DistributionPatchSearcher.h.
Superclass
template<class ImageType , class DataImageType > typedef anima::NonLocalPatchBaseSearcher<ImageType> anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::Superclass
Definition at line 14 of file animaNonLocalT2DistributionPatchSearcher.h.
Constructor & Destructor Documentation
NonLocalT2DistributionPatchSearcher()
template<class ImageType , class DataImageType > anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::NonLocalT2DistributionPatchSearcher ()
Definition at line 6 of file animaNonLocalT2DistributionPatchSearcher.hxx.
~NonLocalT2DistributionPatchSearcher()
template<class ImageType , class DataImageType > virtual anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::~NonLocalT2DistributionPatchSearcher () inline virtual
Definition at line 19 of file animaNonLocalT2DistributionPatchSearcher.h.
Member Function Documentation
AddMeanImage()
template<class ImageType , class DataImageType > void anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::AddMeanImage (DataImageType * arg) inline
Definition at line 27 of file animaNonLocalT2DistributionPatchSearcher.h.
AddPatchTestImage()
template<class ImageType , class DataImageType > void anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::AddPatchTestImage (const DataImageType * arg) inline
Definition at line 26 of file animaNonLocalT2DistributionPatchSearcher.h.
AddVarImage()
template<class ImageType , class DataImageType > void anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::AddVarImage (DataImageType * arg) inline
Definition at line 28 of file animaNonLocalT2DistributionPatchSearcher.h.
References anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::ComputeWeightValue(), and anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::TestPatchConformity().
ComputeWeightValue()
template<class ImageType , class DataImageType > double anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::ComputeWeightValue (unsigned int index, ImageRegionType & refPatch, ImageRegionType & movingPatch) protected virtual
Implements anima::NonLocalPatchBaseSearcher< ImageType >.
Definition at line 45 of file animaNonLocalT2DistributionPatchSearcher.hxx.
Referenced by anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::AddVarImage().
SetBetaParameter()
template<class ImageType , class DataImageType > void anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::SetBetaParameter (double arg) inline
Definition at line 21 of file animaNonLocalT2DistributionPatchSearcher.h.
SetMeanMinThreshold()
template<class ImageType , class DataImageType > void anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::SetMeanMinThreshold (double arg) inline
Definition at line 23 of file animaNonLocalT2DistributionPatchSearcher.h.
SetNoiseCovariances()
template<class ImageType , class DataImageType > void anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::SetNoiseCovariances (std::vector< double > & arg) inline
Definition at line 22 of file animaNonLocalT2DistributionPatchSearcher.h.
SetVarMinThreshold()
template<class ImageType , class DataImageType > void anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::SetVarMinThreshold (double arg) inline
Definition at line 24 of file animaNonLocalT2DistributionPatchSearcher.h.
TestPatchConformity()
template<class ImageType , class DataImageType > bool anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::TestPatchConformity (unsigned int index, const IndexType & refIndex, const IndexType & movingIndex) protected virtual
Implements anima::NonLocalPatchBaseSearcher< ImageType >.
Definition at line 17 of file animaNonLocalT2DistributionPatchSearcher.hxx.
Referenced by anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >::AddVarImage().
The documentation for this class was generated from the following files:
animaNonLocalT2DistributionPatchSearcher.h
animaNonLocalT2DistributionPatchSearcher.hxx