ANIMA: anima::LowMemoryNLMeansPatientToGroupComparisonBridge Class Reference
anima::LowMemoryNLMeansPatientToGroupComparisonBridge Class Reference
#include <animaLowMemNLMeansPatientToGroupComparisonBridge.h>
Public Types
typedef anima::ImageDataSplitter< InputImageType > ImageSplitterType
typedef NLMeansPatientToGroupComparisonImageFilter< double >::InputImageType InputImageType
typedef anima::NLMeansPatientToGroupComparisonImageFilter< double > MainFilterType
typedef itk::Image< unsigned char, 3 > MaskImageType
typedef NLMeansPatientToGroupComparisonImageFilter< double >::OutputImageRegionType OutputImageRegionType
typedef NLMeansPatientToGroupComparisonImageFilter< double >::OutputImageType OutputImageType
typedef anima::ImageDataSplitter< OutputImageType > ScalarImageSplitterType
Public Member Functions
void BuildAndWrite (OutputImageType *tmpIm, std::string resName, OutputImageType::RegionType finalROI)
std::string GetNameOfClass ()
LowMemoryNLMeansPatientToGroupComparisonBridge ()
void SetBetaParameter (double beta)
void SetComputationMask (std::string &cMask)
void SetDatabaseCovarianceDistanceAverageFileName (std::string &fileName)
void SetDatabaseCovarianceDistanceStdFileName (std::string &fileName)
void SetDatabaseMeanDistanceAverageFileName (std::string &fileName)
void SetDatabaseMeanDistanceStdFileName (std::string &fileName)
void SetDatabaseNames (std::string &fileList)
void SetMeanThreshold (double weight)
void SetNbSplits (unsigned int nbSplits)
void SetNumberOfThreads (unsigned int nbT)
void SetOutputNPatchesName (std::string &pref)
void SetOutputPValName (std::string &pref)
void SetOutputScoreName (std::string &pref)
void SetPatchHalfSize (unsigned int patchHalf)
void SetSearchNeighborhood (unsigned int searchNeigh)
void SetSearchStepSize (unsigned int searchStep)
void SetTestFileName (std::string &fileName)
void SetVarianceThreshold (double weight)
void SetWeightThreshold (double weight)
void Update (int specificSplitToDo=-1, bool genOutputDescriptionData=false)
~LowMemoryNLMeansPatientToGroupComparisonBridge ()
Detailed Description
Definition at line 9 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
Member Typedef Documentation
ImageSplitterType
typedef anima::ImageDataSplitter< InputImageType > anima::LowMemoryNLMeansPatientToGroupComparisonBridge::ImageSplitterType
Definition at line 16 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
InputImageType
typedef NLMeansPatientToGroupComparisonImageFilter<double>::InputImageType anima::LowMemoryNLMeansPatientToGroupComparisonBridge::InputImageType
Definition at line 12 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
MainFilterType
typedef anima::NLMeansPatientToGroupComparisonImageFilter<double> anima::LowMemoryNLMeansPatientToGroupComparisonBridge::MainFilterType
Definition at line 18 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
MaskImageType
typedef itk::Image<unsigned char,3> anima::LowMemoryNLMeansPatientToGroupComparisonBridge::MaskImageType
Definition at line 19 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
OutputImageRegionType
typedef NLMeansPatientToGroupComparisonImageFilter<double>::OutputImageRegionType anima::LowMemoryNLMeansPatientToGroupComparisonBridge::OutputImageRegionType
Definition at line 14 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
OutputImageType
typedef NLMeansPatientToGroupComparisonImageFilter<double>::OutputImageType anima::LowMemoryNLMeansPatientToGroupComparisonBridge::OutputImageType
Definition at line 13 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
ScalarImageSplitterType
typedef anima::ImageDataSplitter< OutputImageType > anima::LowMemoryNLMeansPatientToGroupComparisonBridge::ScalarImageSplitterType
Definition at line 17 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
Constructor & Destructor Documentation
LowMemoryNLMeansPatientToGroupComparisonBridge()
anima::LowMemoryNLMeansPatientToGroupComparisonBridge::LowMemoryNLMeansPatientToGroupComparisonBridge ()
Definition at line 8 of file animaLowMemNLMeansPatientToGroupComparisonBridge.cxx.
~LowMemoryNLMeansPatientToGroupComparisonBridge()
anima::LowMemoryNLMeansPatientToGroupComparisonBridge::~LowMemoryNLMeansPatientToGroupComparisonBridge ()
Definition at line 32 of file animaLowMemNLMeansPatientToGroupComparisonBridge.cxx.
Member Function Documentation
BuildAndWrite()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::BuildAndWrite (OutputImageType * tmpIm, std::string resName, OutputImageType::RegionType finalROI)
Definition at line 262 of file animaLowMemNLMeansPatientToGroupComparisonBridge.cxx.
References anima::computeAverageLocalCovariance(), anima::ImageDataSplitter< TInputImage >::GetFileName(), and anima::ImageDataSplitter< TInputImage >::GetNbImages().
Referenced by SetSearchNeighborhood(), and Update().
GetNameOfClass()
std::string anima::LowMemoryNLMeansPatientToGroupComparisonBridge::GetNameOfClass () inline
Definition at line 36 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetBetaParameter()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetBetaParameter (double beta) inline
Definition at line 54 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetComputationMask()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetComputationMask (std::string & cMask)
Definition at line 53 of file animaLowMemNLMeansPatientToGroupComparisonBridge.cxx.
References anima::ImageDataSplitter< TInputImage >::SetComputationMask().
Referenced by main().
SetDatabaseCovarianceDistanceAverageFileName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseCovarianceDistanceAverageFileName (std::string & fileName) inline
Definition at line 38 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetUniqueFileName().
SetDatabaseCovarianceDistanceStdFileName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseCovarianceDistanceStdFileName (std::string & fileName) inline
Definition at line 39 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetUniqueFileName().
SetDatabaseMeanDistanceAverageFileName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseMeanDistanceAverageFileName (std::string & fileName) inline
Definition at line 40 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetUniqueFileName().
SetDatabaseMeanDistanceStdFileName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseMeanDistanceStdFileName (std::string & fileName) inline
Definition at line 41 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetUniqueFileName().
SetDatabaseNames()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetDatabaseNames (std::string & fileList) inline
Definition at line 26 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetFileNames().
SetMeanThreshold()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetMeanThreshold (double weight) inline
Definition at line 51 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetNbSplits()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetNbSplits (unsigned int nbSplits) inline
Definition at line 47 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetNumberOfThreads()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetNumberOfThreads (unsigned int nbT) inline
Definition at line 48 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetOutputNPatchesName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetOutputNPatchesName (std::string & pref) inline
Definition at line 45 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetOutputPValName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetOutputPValName (std::string & pref) inline
Definition at line 44 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetOutputScoreName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetOutputScoreName (std::string & pref) inline
Definition at line 43 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetPatchHalfSize()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetPatchHalfSize (unsigned int patchHalf) inline
Definition at line 56 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetSearchNeighborhood()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetSearchNeighborhood (unsigned int searchNeigh) inline
Definition at line 58 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
References BuildAndWrite(), and Update().
SetSearchStepSize()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetSearchStepSize (unsigned int searchStep) inline
Definition at line 57 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetTestFileName()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetTestFileName (std::string & fileName) inline
Definition at line 31 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetUniqueFileName().
SetVarianceThreshold()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetVarianceThreshold (double weight) inline
Definition at line 52 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
SetWeightThreshold()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::SetWeightThreshold (double weight) inline
Definition at line 50 of file animaLowMemNLMeansPatientToGroupComparisonBridge.h.
Update()
void anima::LowMemoryNLMeansPatientToGroupComparisonBridge::Update (int specificSplitToDo = -1, bool genOutputDescriptionData = false)
Definition at line 66 of file animaLowMemNLMeansPatientToGroupComparisonBridge.cxx.
References BuildAndWrite(), anima::ImageDataSplitter< TInputImage >::EmptyMask(), anima::ImageDataSplitter< TInputImage >::GetBlockRegionInsideMargin(), anima::ImageDataSplitter< TInputImage >::GetNbImages(), anima::ImageDataSplitter< TInputImage >::GetOutput(), anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin(), anima::ImageDataSplitter< TInputImage >::GetSpecificBlockRegion(), anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::New(), anima::ImageDataSplitter< TInputImage >::SetBlockIndex(), anima::ImageDataSplitter< TInputImage >::SetBlockMargin(), anima::ImageDataSplitter< TInputImage >::SetNumberOfBlocks(), and anima::ImageDataSplitter< TInputImage >::Update().
Referenced by SetSearchNeighborhood().
The documentation for this class was generated from the following files:
animaLowMemNLMeansPatientToGroupComparisonBridge.h
animaLowMemNLMeansPatientToGroupComparisonBridge.cxx