ANIMA: anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType > Class Template Reference
anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType > Class Template Reference abstract
#include <animaBaseProbabilisticTractographyImageFilter.h>
Classes
struct FiberWorkType
struct pair_comparator
struct trackerArguments
Public Types
enum ColinearityDirectionType {
Center = 0,
Outward,
Top,
Bottom,
Left,
Right,
Front,
Back
}
Which direction should the very first direction point to? (used in conjunction with InitialDirectionMode) Center: towards gravity center Outward: outward from gravity center Top: Image top (z axis) Bottom: Image bottom (reverse z axis) ...
typedef itk::SmartPointer< const Self > ConstPointer
typedef InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef std::vector< Vector3DType > DirectionVectorType
typedef std::vector< FiberType > FiberProcessVectorType
typedef std::vector< PointType > FiberType
typedef float ImageScalarType
typedef MaskImageType::IndexType IndexType
enum InitialDirectionModeType {
Colinear = 0,
Weight
}
Tells how to choose the very first direction of each particle Colinear: Most colinear to colinear direction specified (ColinearityDirectionType) Weight: Model direction with the highest weight.
typedef InputModelImageType::Pointer InputModelImagePointer
typedef TInputModelImageType InputModelImageType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< InputModelImageType > InterpolatorType
typedef std::vector< MathScalarType > ListType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned short, 3 > MaskImageType
typedef double MathScalarType
typedef itk::Matrix< MathScalarType, 3, 3 > Matrix3DType
typedef std::vector< unsigned int > MembershipType
typedef itk::SmartPointer< Self > Pointer
typedef MaskImageType::PointType PointType
typedef ScalarImageType::Pointer ScalarImagePointer
typedef itk::Image< ImageScalarType, 3 > ScalarImageType
typedef ScalarInterpolatorType::Pointer ScalarInterpolatorPointer
typedef itk::LinearInterpolateImageFunction< ScalarImageType > ScalarInterpolatorType
typedef BaseProbabilisticTractographyImageFilter Self
typedef itk::ProcessObject Superclass
typedef itk::Vector< MathScalarType, 3 > Vector3DType
typedef itk::VariableLengthVector< MathScalarType > VectorType
Public Member Functions
void createVTKOutput (FiberProcessVectorType &filteredFibers, ListType &filteredWeights)
virtual InitialDirectionModeType GetInitialDirectionMode ()
InputModelImageType * GetInputModelImage ()
virtual double GetKappaOfPriorDistribution ()
virtual unsigned int GetModelDimension ()
virtual InterpolatorType * GetModelInterpolator ()
virtual const char * GetNameOfClass () const
vtkPolyData * GetOutput ()
virtual void SetB0Image (ScalarImageType *_arg)
virtual void SetClusterDistance (unsigned int _arg)
virtual void SetComputeLocalColors (bool _arg)
virtual void SetCutMask (MaskImageType *_arg)
virtual void SetFiberTrashThreshold (double _arg)
virtual void SetFilterMask (MaskImageType *_arg)
virtual void SetForbiddenMask (MaskImageType *_arg)
void SetInitialColinearityDirection (const ColinearityDirectionType &colDir)
void SetInitialDirectionMode (const InitialDirectionModeType &dir)
virtual void SetInputModelImage (InputModelImageType *inImage)
virtual void SetKappaOfPriorDistribution (double _arg)
virtual void SetKappaSplitThreshold (double _arg)
virtual void SetMAPMergeFibers (bool _arg)
virtual void SetMaxLengthFiber (double _arg)
virtual void SetMinimalNumberOfParticlesPerClass (unsigned int _arg)
virtual void SetMinLengthFiber (double _arg)
virtual void SetModelDimension (unsigned int _arg)
virtual void SetNoiseImage (ScalarImageType *_arg)
virtual void SetNumberOfFibersPerPixel (unsigned int _arg)
virtual void SetNumberOfParticles (unsigned int _arg)
virtual void SetPositionDistanceFuseThreshold (double _arg)
virtual void SetResamplingThreshold (double _arg)
virtual void SetSeedMask (MaskImageType *_arg)
virtual void SetStepProgression (double _arg)
void Update () ITK_OVERRIDE
Protected Member Functions
BaseProbabilisticTractographyImageFilter ()
virtual bool CheckModelProperties (double estimatedB0Value, double estimatedNoiseValue, VectorType &modelValue, unsigned int threadId)=0
Check stopping criterions to stop a particle (model dependent, not implemented here)
virtual void ComputeAdditionalScalarMaps ()
Computes additional scalar maps that are model dependent to add to the output.
FiberProcessVectorType ComputeFiber (FiberType &fiber, InterpolatorPointer &modelInterpolator, unsigned int numThread, ListType &resultWeights)
This little guy is the one handling probabilistic tracking.
virtual double ComputeLogWeightUpdate (double b0Value, double noiseValue, Vector3DType &newDirection, VectorType &modelValue, double &log_prior, double &log_proposal, unsigned int threadId)=0
Update particle weight based on an underlying model and the chosen direction (model dependent, not implemented here)
virtual void ComputeModelValue (InterpolatorPointer &modelInterpolator, ContinuousIndexType &index, VectorType &modelValue)=0
Estimate model from raw diffusion data (model dependent, not implemented here)
FiberProcessVectorType FilterOutputFibers (FiberProcessVectorType &fibers, ListType &weights)
Filter output fibers by ROIs and compute local colors.
virtual Vector3DType InitializeFirstIterationFromModel (Vector3DType &colinearDir, VectorType &modelValue, unsigned int threadId)=0
Initialize first direction from user input (model dependent, not implemented here)
bool MergeParticleClassFibers (FiberWorkType &fiberData, FiberProcessVectorType &outputMerged, unsigned int classNumber)
This guy takes the result of computefiber and merges the classes, each one becomes one fiber.
virtual void PrepareTractography ()
Generate seed points (can be re-implemented but this one has to be called)
virtual Vector3DType ProposeNewDirection (Vector3DType &oldDirection, VectorType &modelValue, Vector3DType &sampling_direction, double &log_prior, double &log_proposal, std::mt19937 &random_generator, unsigned int threadId)=0
Propose new direction for a particle, given the old direction, and a model (model dependent, not implemented here)
void ThreadedTrackComputer (unsigned int numThread, FiberProcessVectorType &resultFibers, ListType &resultWeights, unsigned int startSeedIndex, unsigned int endSeedIndex)
Doing the real tracking by calling ComputeFiber and merging its results.
void ThreadTrack (unsigned int numThread, FiberProcessVectorType &resultFibers, ListType &resultWeights)
Doing the thread work dispatch.
unsigned int UpdateClassesMemberships (FiberWorkType &fiberData, DirectionVectorType &directions, std::mt19937 &random_generator)
This ugly guy is the heart of multi-modal probabilistic tractography, making decisions on split and merges of particles.
virtual ~BaseProbabilisticTractographyImageFilter ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreadTracker (void *arg)
Multithread util function.
Detailed Description
template<class TInputModelImageType>
class anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >
Definition at line 20 of file animaBaseProbabilisticTractographyImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TInputModelImageType> typedef itk::SmartPointer<const Self> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ConstPointer
Definition at line 28 of file animaBaseProbabilisticTractographyImageFilter.h.
ContinuousIndexType
template<class TInputModelImageType> typedef InterpolatorType::ContinuousIndexType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ContinuousIndexType
Definition at line 62 of file animaBaseProbabilisticTractographyImageFilter.h.
DirectionVectorType
template<class TInputModelImageType> typedef std::vector<Vector3DType> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::DirectionVectorType
Definition at line 57 of file animaBaseProbabilisticTractographyImageFilter.h.
FiberProcessVectorType
template<class TInputModelImageType> typedef std::vector<FiberType> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::FiberProcessVectorType
Definition at line 66 of file animaBaseProbabilisticTractographyImageFilter.h.
FiberType
template<class TInputModelImageType> typedef std::vector<PointType> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::FiberType
Definition at line 65 of file animaBaseProbabilisticTractographyImageFilter.h.
ImageScalarType
template<class TInputModelImageType> typedef float anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ImageScalarType
Definition at line 33 of file animaBaseProbabilisticTractographyImageFilter.h.
IndexType
template<class TInputModelImageType> typedef MaskImageType::IndexType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::IndexType
Definition at line 50 of file animaBaseProbabilisticTractographyImageFilter.h.
InputModelImagePointer
template<class TInputModelImageType> typedef InputModelImageType::Pointer anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::InputModelImagePointer
Definition at line 38 of file animaBaseProbabilisticTractographyImageFilter.h.
InputModelImageType
template<class TInputModelImageType> typedef TInputModelImageType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::InputModelImageType
Definition at line 37 of file animaBaseProbabilisticTractographyImageFilter.h.
InterpolatorPointer
template<class TInputModelImageType> typedef InterpolatorType::Pointer anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::InterpolatorPointer
Definition at line 61 of file animaBaseProbabilisticTractographyImageFilter.h.
InterpolatorType
template<class TInputModelImageType> typedef itk::InterpolateImageFunction<InputModelImageType> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::InterpolatorType
Definition at line 60 of file animaBaseProbabilisticTractographyImageFilter.h.
ListType
template<class TInputModelImageType> typedef std::vector<MathScalarType> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ListType
Definition at line 56 of file animaBaseProbabilisticTractographyImageFilter.h.
MaskImagePointer
template<class TInputModelImageType> typedef MaskImageType::Pointer anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::MaskImagePointer
Definition at line 48 of file animaBaseProbabilisticTractographyImageFilter.h.
MaskImageType
template<class TInputModelImageType> typedef itk::Image<unsigned short, 3> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::MaskImageType
Definition at line 47 of file animaBaseProbabilisticTractographyImageFilter.h.
MathScalarType
template<class TInputModelImageType> typedef double anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::MathScalarType
Definition at line 34 of file animaBaseProbabilisticTractographyImageFilter.h.
Matrix3DType
template<class TInputModelImageType> typedef itk::Matrix<MathScalarType,3,3> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::Matrix3DType
Definition at line 53 of file animaBaseProbabilisticTractographyImageFilter.h.
MembershipType
template<class TInputModelImageType> typedef std::vector<unsigned int> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::MembershipType
Definition at line 67 of file animaBaseProbabilisticTractographyImageFilter.h.
Pointer
template<class TInputModelImageType> typedef itk::SmartPointer<Self> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::Pointer
Definition at line 27 of file animaBaseProbabilisticTractographyImageFilter.h.
PointType
template<class TInputModelImageType> typedef MaskImageType::PointType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::PointType
Definition at line 49 of file animaBaseProbabilisticTractographyImageFilter.h.
ScalarImagePointer
template<class TInputModelImageType> typedef ScalarImageType::Pointer anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ScalarImagePointer
Definition at line 42 of file animaBaseProbabilisticTractographyImageFilter.h.
ScalarImageType
template<class TInputModelImageType> typedef itk::Image<ImageScalarType, 3> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ScalarImageType
Definition at line 41 of file animaBaseProbabilisticTractographyImageFilter.h.
ScalarInterpolatorPointer
template<class TInputModelImageType> typedef ScalarInterpolatorType::Pointer anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ScalarInterpolatorPointer
Definition at line 44 of file animaBaseProbabilisticTractographyImageFilter.h.
ScalarInterpolatorType
template<class TInputModelImageType> typedef itk::LinearInterpolateImageFunction<ScalarImageType> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ScalarInterpolatorType
Definition at line 43 of file animaBaseProbabilisticTractographyImageFilter.h.
Self
template<class TInputModelImageType> typedef BaseProbabilisticTractographyImageFilter anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::Self
SmartPointer typedef support
Definition at line 24 of file animaBaseProbabilisticTractographyImageFilter.h.
Superclass
template<class TInputModelImageType> typedef itk::ProcessObject anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::Superclass
Definition at line 25 of file animaBaseProbabilisticTractographyImageFilter.h.
Vector3DType
template<class TInputModelImageType> typedef itk::Vector<MathScalarType,3> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::Vector3DType
Definition at line 54 of file animaBaseProbabilisticTractographyImageFilter.h.
VectorType
template<class TInputModelImageType> typedef itk::VariableLengthVector<MathScalarType> anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::VectorType
Definition at line 55 of file animaBaseProbabilisticTractographyImageFilter.h.
Member Enumeration Documentation
ColinearityDirectionType
template<class TInputModelImageType> enum anima::BaseProbabilisticTractographyImageFilter::ColinearityDirectionType
Which direction should the very first direction point to? (used in conjunction with InitialDirectionMode) Center: towards gravity center Outward: outward from gravity center Top: Image top (z axis) Bottom: Image bottom (reverse z axis) ...
Enumerator
Center
Outward
Top
Bottom
Left
Right
Front
Back
Definition at line 89 of file animaBaseProbabilisticTractographyImageFilter.h.
InitialDirectionModeType
template<class TInputModelImageType> enum anima::BaseProbabilisticTractographyImageFilter::InitialDirectionModeType
Tells how to choose the very first direction of each particle Colinear: Most colinear to colinear direction specified (ColinearityDirectionType) Weight: Model direction with the highest weight.
Enumerator
Colinear
Weight
Definition at line 106 of file animaBaseProbabilisticTractographyImageFilter.h.
Constructor & Destructor Documentation
BaseProbabilisticTractographyImageFilter()
template<class TInputModelImageType > anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::BaseProbabilisticTractographyImageFilter () protected
Definition at line 30 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
~BaseProbabilisticTractographyImageFilter()
template<class TInputModelImageType > anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::~BaseProbabilisticTractographyImageFilter () protected virtual
Definition at line 66 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
Member Function Documentation
CheckModelProperties()
template<class TInputModelImageType> virtual bool anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::CheckModelProperties (double estimatedB0Value, double estimatedNoiseValue, VectorType & modelValue, unsigned int threadId) protected pure virtual
Check stopping criterions to stop a particle (model dependent, not implemented here)
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
ComputeAdditionalScalarMaps()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ComputeAdditionalScalarMaps () inline protected virtual
Computes additional scalar maps that are model dependent to add to the output.
Reimplemented in anima::DTIProbabilisticTractographyImageFilter.
Definition at line 223 of file animaBaseProbabilisticTractographyImageFilter.h.
ComputeFiber()
template<class TInputModelImageType > BaseProbabilisticTractographyImageFilter< TInputModelImageType >::FiberProcessVectorType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ComputeFiber (FiberType & fiber, InterpolatorPointer & modelInterpolator, unsigned int numThread, ListType & resultWeights) protected
This little guy is the one handling probabilistic tracking.
Definition at line 523 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
ComputeLogWeightUpdate()
template<class TInputModelImageType> virtual double anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ComputeLogWeightUpdate (double b0Value, double noiseValue, Vector3DType & newDirection, VectorType & modelValue, double & log_prior, double & log_proposal, unsigned int threadId) protected pure virtual
Update particle weight based on an underlying model and the chosen direction (model dependent, not implemented here)
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
ComputeModelValue()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ComputeModelValue (InterpolatorPointer & modelInterpolator, ContinuousIndexType & index, VectorType & modelValue) protected pure virtual
Estimate model from raw diffusion data (model dependent, not implemented here)
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
createVTKOutput()
template<class TInputModelImageType > void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::createVTKOutput (FiberProcessVectorType & filteredFibers, ListType & filteredWeights)
Definition at line 432 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetInputModelImage().
FilterOutputFibers()
template<class TInputModelImageType > BaseProbabilisticTractographyImageFilter< TInputModelImageType >::FiberProcessVectorType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::FilterOutputFibers (FiberProcessVectorType & fibers, ListType & weights) protected
Filter output fibers by ROIs and compute local colors.
Definition at line 356 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
GetInitialDirectionMode()
template<class TInputModelImageType> virtual InitialDirectionModeType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::GetInitialDirectionMode () virtual
GetInputModelImage()
template<class TInputModelImageType> InputModelImageType* anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::GetInputModelImage () inline
Definition at line 128 of file animaBaseProbabilisticTractographyImageFilter.h.
GetKappaOfPriorDistribution()
template<class TInputModelImageType> virtual double anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::GetKappaOfPriorDistribution () virtual
GetModelDimension()
template<class TInputModelImageType> virtual unsigned int anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::GetModelDimension () virtual
GetModelInterpolator()
template<class TInputModelImageType > BaseProbabilisticTractographyImageFilter< TInputModelImageType >::InterpolatorType * anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::GetModelInterpolator () virtual
Definition at line 256 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetInputModelImage().
GetNameOfClass()
template<class TInputModelImageType> virtual const char* anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::GetNameOfClass () const virtual
Reimplemented in anima::ODFProbabilisticTractographyImageFilter, and anima::DTIProbabilisticTractographyImageFilter.
GetOutput()
template<class TInputModelImageType> vtkPolyData* anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::GetOutput () inline
Definition at line 169 of file animaBaseProbabilisticTractographyImageFilter.h.
InitializeFirstIterationFromModel()
template<class TInputModelImageType> virtual Vector3DType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::InitializeFirstIterationFromModel (Vector3DType & colinearDir, VectorType & modelValue, unsigned int threadId) protected pure virtual
Initialize first direction from user input (model dependent, not implemented here)
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
MergeParticleClassFibers()
template<class TInputModelImageType > bool anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::MergeParticleClassFibers (FiberWorkType & fiberData, FiberProcessVectorType & outputMerged, unsigned int classNumber) protected
This guy takes the result of computefiber and merges the classes, each one becomes one fiber.
Definition at line 1269 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
PrepareTractography()
template<class TInputModelImageType > void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::PrepareTractography () protected virtual
Generate seed points (can be re-implemented but this one has to be called)
Reimplemented in anima::ODFProbabilisticTractographyImageFilter.
Definition at line 124 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput(), and anima::ODFProbabilisticTractographyImageFilter::PrepareTractography().
ProposeNewDirection()
template<class TInputModelImageType> virtual Vector3DType anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ProposeNewDirection (Vector3DType & oldDirection, VectorType & modelValue, Vector3DType & sampling_direction, double & log_prior, double & log_proposal, std::mt19937 & random_generator, unsigned int threadId) protected pure virtual
Propose new direction for a particle, given the old direction, and a model (model dependent, not implemented here)
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
SetB0Image()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetB0Image (ScalarImageType * _arg) virtual
SetClusterDistance()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetClusterDistance (unsigned int _arg) virtual
SetComputeLocalColors()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetComputeLocalColors (bool _arg) virtual
SetCutMask()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetCutMask (MaskImageType * _arg) virtual
SetFiberTrashThreshold()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetFiberTrashThreshold (double _arg) virtual
SetFilterMask()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetFilterMask (MaskImageType * _arg) virtual
SetForbiddenMask()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetForbiddenMask (MaskImageType * _arg) virtual
SetInitialColinearityDirection()
template<class TInputModelImageType> void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetInitialColinearityDirection (const ColinearityDirectionType & colDir) inline
Definition at line 123 of file animaBaseProbabilisticTractographyImageFilter.h.
SetInitialDirectionMode()
template<class TInputModelImageType> void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetInitialDirectionMode (const InitialDirectionModeType & dir) inline
Definition at line 124 of file animaBaseProbabilisticTractographyImageFilter.h.
SetInputModelImage()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetInputModelImage (InputModelImageType * inImage) inline virtual
Definition at line 127 of file animaBaseProbabilisticTractographyImageFilter.h.
SetKappaOfPriorDistribution()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetKappaOfPriorDistribution (double _arg) virtual
SetKappaSplitThreshold()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetKappaSplitThreshold (double _arg) virtual
SetMAPMergeFibers()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetMAPMergeFibers (bool _arg) virtual
SetMaxLengthFiber()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetMaxLengthFiber (double _arg) virtual
SetMinimalNumberOfParticlesPerClass()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetMinimalNumberOfParticlesPerClass (unsigned int _arg) virtual
SetMinLengthFiber()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetMinLengthFiber (double _arg) virtual
SetModelDimension()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetModelDimension (unsigned int _arg) virtual
SetNoiseImage()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetNoiseImage (ScalarImageType * _arg) virtual
SetNumberOfFibersPerPixel()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetNumberOfFibersPerPixel (unsigned int _arg) virtual
SetNumberOfParticles()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetNumberOfParticles (unsigned int _arg) virtual
SetPositionDistanceFuseThreshold()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetPositionDistanceFuseThreshold (double _arg) virtual
SetResamplingThreshold()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetResamplingThreshold (double _arg) virtual
SetSeedMask()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetSeedMask (MaskImageType * _arg) virtual
SetStepProgression()
template<class TInputModelImageType> virtual void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::SetStepProgression (double _arg) virtual
ThreadedTrackComputer()
template<class TInputModelImageType > void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ThreadedTrackComputer (unsigned int numThread, FiberProcessVectorType & resultFibers, ListType & resultWeights, unsigned int startSeedIndex, unsigned int endSeedIndex) protected
Doing the real tracking by calling ComputeFiber and merging its results.
Definition at line 325 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
ThreadTrack()
template<class TInputModelImageType > void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ThreadTrack (unsigned int numThread, FiberProcessVectorType & resultFibers, ListType & resultWeights) protected
Doing the thread work dispatch.
Definition at line 284 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput(), and anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::ThreadTracker().
ThreadTracker()
template<class TInputModelImageType > ITK_THREAD_RETURN_TYPE anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::ThreadTracker (void * arg) static protected
Multithread util function.
Definition at line 270 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
Update()
template<class TInputModelImageType > void anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::Update ()
Definition at line 75 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetInputModelImage().
UpdateClassesMemberships()
template<class TInputModelImageType > unsigned int anima::BaseProbabilisticTractographyImageFilter< TInputModelImageType >::UpdateClassesMemberships (FiberWorkType & fiberData, DirectionVectorType & directions, std::mt19937 & random_generator) protected
This ugly guy is the heart of multi-modal probabilistic tractography, making decisions on split and merges of particles.
Definition at line 900 of file animaBaseProbabilisticTractographyImageFilter.hxx.
Referenced by anima::BaseProbabilisticTractographyImageFilter< itk::VectorImage< float, 3 > >::GetOutput().
The documentation for this class was generated from the following files:
animaBaseProbabilisticTractographyImageFilter.h
animaBaseProbabilisticTractographyImageFilter.hxx