ANIMA: anima::SVFLieBracketImageFilter< TPixelType, Dimension > Class Template Reference
anima::SVFLieBracketImageFilter< TPixelType, Dimension > Class Template Reference
Computes the Lie bracket between two fields u and v as expressed by Bossa et al.
#include <animaSVFLieBracketImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Image< itk::Vector< TPixelType, Dimension >, Dimension > InputImageType
typedef InputImageType::PixelType InputPixelType
typedef JacobianImageType::Pointer JacobianImagePointer
typedef itk::Image< itk::Vector< TPixelType, Dimension *Dimension >, Dimension > JacobianImageType
typedef JacobianImageType::PixelType JacobianPixelType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image< itk::Vector< TPixelType, Dimension >, Dimension > OutputImageType
typedef OutputImageType::PixelType OutputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef SVFLieBracketImageFilter Self
typedef itk::ImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
itkGetObjectMacro (FirstFieldJacobian, JacobianImageType) itkGetObjectMacro(SecondFieldJacobian
virtual void SetFirstFieldJacobian (JacobianImageType *_arg)
virtual void SetSecondFieldJacobian (JacobianImageType *_arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
SVFLieBracketImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~SVFLieBracketImageFilter ()
Detailed Description
template<typename TPixelType, unsigned int Dimension>
class anima::SVFLieBracketImageFilter< TPixelType, Dimension >
Computes the Lie bracket between two fields u and v as expressed by Bossa et al.
There is a discrepancy in between Vercauteren et al. and Bossa et al. formulation. This Lie bracket implements the Vercauteren et al. formulation [u,v](x) = Jac(u)(x).v(x) - Jac(v)(x).u(x) M. Bossa et al. "Contributions to 3D diffeomorphic atlas estimation : application to brain images.", MICCAI 2007, p. 667–674. T. Vercauteren et al. "Symmetric Log-Domain Diffeomorphic Registration: A Demons-based Approach.", MICCAI 2008, p. 754-761.
Definition at line 18 of file animaSVFLieBracketImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TPixelType , unsigned int Dimension> typedef itk::SmartPointer<const Self> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::ConstPointer
Definition at line 29 of file animaSVFLieBracketImageFilter.h.
InputImageType
template<typename TPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TPixelType, Dimension>, Dimension> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::InputImageType
Definition at line 24 of file animaSVFLieBracketImageFilter.h.
InputPixelType
template<typename TPixelType , unsigned int Dimension> typedef InputImageType::PixelType anima::SVFLieBracketImageFilter< TPixelType, Dimension >::InputPixelType
Definition at line 35 of file animaSVFLieBracketImageFilter.h.
JacobianImagePointer
template<typename TPixelType , unsigned int Dimension> typedef JacobianImageType::Pointer anima::SVFLieBracketImageFilter< TPixelType, Dimension >::JacobianImagePointer
Definition at line 37 of file animaSVFLieBracketImageFilter.h.
JacobianImageType
template<typename TPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TPixelType, Dimension * Dimension>, Dimension> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::JacobianImageType
Definition at line 25 of file animaSVFLieBracketImageFilter.h.
JacobianPixelType
template<typename TPixelType , unsigned int Dimension> typedef JacobianImageType::PixelType anima::SVFLieBracketImageFilter< TPixelType, Dimension >::JacobianPixelType
Definition at line 38 of file animaSVFLieBracketImageFilter.h.
OutputImageRegionType
template<typename TPixelType , unsigned int Dimension> typedef Superclass::OutputImageRegionType anima::SVFLieBracketImageFilter< TPixelType, Dimension >::OutputImageRegionType
Definition at line 40 of file animaSVFLieBracketImageFilter.h.
OutputImageType
template<typename TPixelType , unsigned int Dimension> typedef itk::Image<itk::Vector <TPixelType, Dimension>, Dimension> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::OutputImageType
Definition at line 26 of file animaSVFLieBracketImageFilter.h.
OutputPixelType
template<typename TPixelType , unsigned int Dimension> typedef OutputImageType::PixelType anima::SVFLieBracketImageFilter< TPixelType, Dimension >::OutputPixelType
Definition at line 36 of file animaSVFLieBracketImageFilter.h.
Pointer
template<typename TPixelType , unsigned int Dimension> typedef itk::SmartPointer<Self> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::Pointer
Definition at line 28 of file animaSVFLieBracketImageFilter.h.
Self
template<typename TPixelType , unsigned int Dimension> typedef SVFLieBracketImageFilter anima::SVFLieBracketImageFilter< TPixelType, Dimension >::Self
Definition at line 23 of file animaSVFLieBracketImageFilter.h.
Superclass
template<typename TPixelType , unsigned int Dimension> typedef itk::ImageToImageFilter<InputImageType, OutputImageType> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::Superclass
Definition at line 27 of file animaSVFLieBracketImageFilter.h.
Constructor & Destructor Documentation
SVFLieBracketImageFilter()
template<typename TPixelType , unsigned int Dimension> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::SVFLieBracketImageFilter () inline protected
Definition at line 48 of file animaSVFLieBracketImageFilter.h.
~SVFLieBracketImageFilter()
template<typename TPixelType , unsigned int Dimension> virtual anima::SVFLieBracketImageFilter< TPixelType, Dimension >::~SVFLieBracketImageFilter () inline protected virtual
Definition at line 55 of file animaSVFLieBracketImageFilter.h.
References anima::SVFLieBracketImageFilter< TPixelType, Dimension >::BeforeThreadedGenerateData(), and anima::SVFLieBracketImageFilter< TPixelType, Dimension >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TPixelType , unsigned int Dimension> void anima::SVFLieBracketImageFilter< TPixelType, Dimension >::BeforeThreadedGenerateData () protected
Definition at line 14 of file animaSVFLieBracketImageFilter.hxx.
Referenced by anima::SVFLieBracketImageFilter< TPixelType, Dimension >::~SVFLieBracketImageFilter().
CreateAnother()
template<typename TPixelType , unsigned int Dimension> virtual::itk::LightObject::Pointer anima::SVFLieBracketImageFilter< TPixelType, Dimension >::CreateAnother (void) const
GetNameOfClass()
template<typename TPixelType , unsigned int Dimension> virtual const char* anima::SVFLieBracketImageFilter< TPixelType, Dimension >::GetNameOfClass () const virtual
itkGetObjectMacro()
template<typename TPixelType , unsigned int Dimension> anima::SVFLieBracketImageFilter< TPixelType, Dimension >::itkGetObjectMacro (FirstFieldJacobian , JacobianImageType)
New()
template<typename TPixelType , unsigned int Dimension> static Pointer anima::SVFLieBracketImageFilter< TPixelType, Dimension >::New () static
SetFirstFieldJacobian()
template<typename TPixelType , unsigned int Dimension> virtual void anima::SVFLieBracketImageFilter< TPixelType, Dimension >::SetFirstFieldJacobian (JacobianImageType * _arg) virtual
SetSecondFieldJacobian()
template<typename TPixelType , unsigned int Dimension> virtual void anima::SVFLieBracketImageFilter< TPixelType, Dimension >::SetSecondFieldJacobian (JacobianImageType * _arg) virtual
ThreadedGenerateData()
template<typename TPixelType , unsigned int Dimension> void anima::SVFLieBracketImageFilter< TPixelType, Dimension >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 52 of file animaSVFLieBracketImageFilter.hxx.
Referenced by anima::SVFLieBracketImageFilter< TPixelType, Dimension >::~SVFLieBracketImageFilter().
The documentation for this class was generated from the following files:
animaSVFLieBracketImageFilter.h
animaSVFLieBracketImageFilter.hxx