ANIMA: anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType > Class Template Reference
anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType > Class Template Reference
#include <animaDTIEstimationImageFilter.h>
Classes
struct OptimizationDataStructure
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef OutputImageType DTIImageType
typedef itk::Image< InputPixelScalarType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef itk::Image< InputPixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef itk::Image< OutputPixelScalarType, 3 > OutputB0ImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::VectorImage< OutputPixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType > Self
typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::Image< InputPixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::VectorImage< OutputPixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
void AddGradientDirection (unsigned int i, vnl_vector_fixed< double, 3 > &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetB0Threshold ()
virtual OutputB0ImageType * GetEstimatedB0Image ()
virtual OutputB0ImageType * GetEstimatedVarianceImage ()
virtual const char * GetNameOfClass () const
virtual void SetB0Threshold (double _arg)
void SetBValuesList (std::vector< double > bValuesList)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
double ComputeB0AndVarianceFromTensorVector (const vnl_matrix< double > &tensorValue, const std::vector< double > &dwiSignal, double &outVarianceValue)
double ComputeCostAtPosition (const std::vector< double > &x, const std::vector< double > &observedData, std::vector< double > &predictedValues, vnl_matrix< double > &rotationMatrix, vnl_matrix< double > &workTensor, vnl_diag_matrix< double > &workEigenValues)
DTIEstimationImageFilter ()
void GenerateOutputInformation () ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~DTIEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::VectorImage< OutputPixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::VectorImage< OutputPixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Static Protected Member Functions
static double OptimizationFunction (const std::vector< double > &x, std::vector< double > &grad, void *func_data)
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class InputPixelScalarType, class OutputPixelScalarType>
class anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >
Definition at line 11 of file animaDTIEstimationImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::SmartPointer<const Self> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ConstPointer
Definition at line 24 of file animaDTIEstimationImageFilter.h.
DTIImageType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef OutputImageType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::DTIImageType
Definition at line 20 of file animaDTIEstimationImageFilter.h.
Image4DType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::Image<InputPixelScalarType,4> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Image4DType
Definition at line 21 of file animaDTIEstimationImageFilter.h.
InputImagePointer
template<class InputPixelScalarType , class OutputPixelScalarType > typedef InputImageType::Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::InputImagePointer
Image typedef support
Definition at line 33 of file animaDTIEstimationImageFilter.h.
InputImageRegionType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef Superclass::InputImageRegionType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::InputImageRegionType
Definition at line 38 of file animaDTIEstimationImageFilter.h.
InputImageType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::Image<InputPixelScalarType,3> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::InputImageType
Definition at line 17 of file animaDTIEstimationImageFilter.h.
MaskImageType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef Superclass::MaskImageType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::MaskImageType
Superclass typedefs.
Definition at line 37 of file animaDTIEstimationImageFilter.h.
OutputB0ImageType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::Image<OutputPixelScalarType,3> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputB0ImageType
Definition at line 19 of file animaDTIEstimationImageFilter.h.
OutputImagePointer
template<class InputPixelScalarType , class OutputPixelScalarType > typedef OutputImageType::Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputImagePointer
Definition at line 34 of file animaDTIEstimationImageFilter.h.
OutputImageRegionType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef Superclass::OutputImageRegionType anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputImageRegionType
Definition at line 39 of file animaDTIEstimationImageFilter.h.
OutputImageType
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::VectorImage<OutputPixelScalarType,3> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OutputImageType
Definition at line 18 of file animaDTIEstimationImageFilter.h.
Pointer
template<class InputPixelScalarType , class OutputPixelScalarType > typedef itk::SmartPointer<Self> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Pointer
Definition at line 23 of file animaDTIEstimationImageFilter.h.
Self
template<class InputPixelScalarType , class OutputPixelScalarType > typedef DTIEstimationImageFilter<InputPixelScalarType, OutputPixelScalarType> anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Self
Standard class typedefs.
Definition at line 16 of file animaDTIEstimationImageFilter.h.
Superclass
template<class InputPixelScalarType , class OutputPixelScalarType > typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::Superclass
Definition at line 22 of file animaDTIEstimationImageFilter.h.
Constructor & Destructor Documentation
DTIEstimationImageFilter()
template<class InputPixelScalarType , class OutputPixelScalarType > anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::DTIEstimationImageFilter () inline protected
Definition at line 60 of file animaDTIEstimationImageFilter.h.
~DTIEstimationImageFilter()
template<class InputPixelScalarType , class OutputPixelScalarType > virtual anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter () inline protected virtual
Definition at line 70 of file animaDTIEstimationImageFilter.h.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::BeforeThreadedGenerateData(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::CheckComputationMask(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeB0AndVarianceFromTensorVector(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeCostAtPosition(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GenerateOutputInformation(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationFunction(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData().
Member Function Documentation
AddGradientDirection()
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::AddGradientDirection (unsigned int i, vnl_vector_fixed< double, 3 > & grad)
Definition at line 23 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::CheckComputationMask().
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::SetBValuesList().
BeforeThreadedGenerateData()
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 90 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData().
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GenerateOutputInformation(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter().
CheckComputationMask()
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
Definition at line 36 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GenerateOutputInformation().
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::AddGradientDirection(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter().
ComputeB0AndVarianceFromTensorVector()
template<class InputPixelScalarType , class OutputPixelScalarType > double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeB0AndVarianceFromTensorVector (const vnl_matrix< double > & tensorValue, const std::vector< double > & dwiSignal, double & outVarianceValue) protected
Definition at line 340 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationFunction().
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter().
ComputeCostAtPosition()
template<class InputPixelScalarType , class OutputPixelScalarType > double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeCostAtPosition (const std::vector< double > & x, const std::vector< double > & observedData, std::vector< double > & predictedValues, vnl_matrix< double > & rotationMatrix, vnl_matrix< double > & workTensor, vnl_diag_matrix< double > & workEigenValues) protected
Definition at line 390 of file animaDTIEstimationImageFilter.hxx.
References anima::Get3DRotationExponential(), and anima::RecomposeTensor().
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationFunction(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter().
CreateAnother()
template<class InputPixelScalarType , class OutputPixelScalarType > virtual::itk::LightObject::Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::CreateAnother (void) const
GenerateOutputInformation()
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GenerateOutputInformation () protected
Definition at line 76 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::BeforeThreadedGenerateData().
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::CheckComputationMask(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter().
GetB0Threshold()
template<class InputPixelScalarType , class OutputPixelScalarType > virtual double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GetB0Threshold () virtual
GetEstimatedB0Image()
template<class InputPixelScalarType , class OutputPixelScalarType > virtual OutputB0ImageType* anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GetEstimatedB0Image () virtual
GetEstimatedVarianceImage()
template<class InputPixelScalarType , class OutputPixelScalarType > virtual OutputB0ImageType* anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GetEstimatedVarianceImage () virtual
GetNameOfClass()
template<class InputPixelScalarType , class OutputPixelScalarType > virtual const char* anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >.
New()
template<class InputPixelScalarType , class OutputPixelScalarType > static Pointer anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::New () static
Method for creation through the object factory.
OptimizationFunction()
template<class InputPixelScalarType , class OutputPixelScalarType > double anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationFunction (const std::vector< double > & x, std::vector< double > & grad, void * func_data) static protected
Definition at line 380 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeCostAtPosition(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::dwi, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::filter, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::predictedValues, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::rotationMatrix, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::workEigenValues, and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::workTensor.
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeB0AndVarianceFromTensorVector(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter().
SetB0Threshold()
template<class InputPixelScalarType , class OutputPixelScalarType > virtual void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::SetB0Threshold (double _arg) virtual
SetBValuesList()
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::SetBValuesList (std::vector< double > bValuesList) inline
Definition at line 49 of file animaDTIEstimationImageFilter.h.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::AddGradientDirection().
ThreadedGenerateData()
template<class InputPixelScalarType , class OutputPixelScalarType > void anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 160 of file animaDTIEstimationImageFilter.hxx.
References anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::ComputeB0AndVarianceFromTensorVector(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::dwi, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::filter, anima::Get3DRotationExponential(), anima::Get3DRotationLogarithm(), anima::GetTensorFromVectorRepresentation(), anima::GetVectorRepresentation(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::predictedValues, anima::RecomposeTensor(), anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::rotationMatrix, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::workEigenValues, and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::OptimizationDataStructure::workTensor.
Referenced by anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::BeforeThreadedGenerateData(), and anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >::~DTIEstimationImageFilter().
The documentation for this class was generated from the following files:
animaDTIEstimationImageFilter.h
animaDTIEstimationImageFilter.hxx