ANIMA: anima::T1SERelaxometryCostFunction Class Reference
anima::T1SERelaxometryCostFunction Class Reference
#include <animaT1SERelaxometryCostFunction.h>
Public Types
typedef std::vector< std::complex< double > > ComplexVectorType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef std::vector< ComplexVectorType > MatrixType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef T1SERelaxometryCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
void SetRelaxometrySignals (std::vector< double > &relaxoSignals)
void SetTRValues (std::vector< double > &trValues)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
T1SERelaxometryCostFunction ()
virtual ~T1SERelaxometryCostFunction ()
Detailed Description
Definition at line 9 of file animaT1SERelaxometryCostFunction.h.
Member Typedef Documentation
ComplexVectorType
typedef std::vector< std::complex <double> > anima::T1SERelaxometryCostFunction::ComplexVectorType
Definition at line 27 of file animaT1SERelaxometryCostFunction.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::T1SERelaxometryCostFunction::ConstPointer
Definition at line 17 of file animaT1SERelaxometryCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::T1SERelaxometryCostFunction::DerivativeType
Definition at line 25 of file animaT1SERelaxometryCostFunction.h.
MatrixType
typedef std::vector<ComplexVectorType> anima::T1SERelaxometryCostFunction::MatrixType
Definition at line 28 of file animaT1SERelaxometryCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::T1SERelaxometryCostFunction::MeasureType
Definition at line 24 of file animaT1SERelaxometryCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::T1SERelaxometryCostFunction::ParametersType
Definition at line 26 of file animaT1SERelaxometryCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::T1SERelaxometryCostFunction::Pointer
Definition at line 16 of file animaT1SERelaxometryCostFunction.h.
Self
typedef T1SERelaxometryCostFunction anima::T1SERelaxometryCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaT1SERelaxometryCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::T1SERelaxometryCostFunction::Superclass
Definition at line 15 of file animaT1SERelaxometryCostFunction.h.
Constructor & Destructor Documentation
T1SERelaxometryCostFunction()
anima::T1SERelaxometryCostFunction::T1SERelaxometryCostFunction () inline protected
Definition at line 42 of file animaT1SERelaxometryCostFunction.h.
~T1SERelaxometryCostFunction()
virtual anima::T1SERelaxometryCostFunction::~T1SERelaxometryCostFunction () inline protected virtual
Definition at line 46 of file animaT1SERelaxometryCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::T1SERelaxometryCostFunction::CreateAnother (void) const
GetDerivative()
void anima::T1SERelaxometryCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 25 of file animaT1SERelaxometryCostFunction.cxx.
References GetNumberOfParameters().
GetNameOfClass()
virtual const char* anima::T1SERelaxometryCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::T1SERelaxometryCostFunction::GetNumberOfParameters () const inline
Definition at line 36 of file animaT1SERelaxometryCostFunction.h.
Referenced by GetDerivative().
GetValue()
T1SERelaxometryCostFunction::MeasureType anima::T1SERelaxometryCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 7 of file animaT1SERelaxometryCostFunction.cxx.
New()
static Pointer anima::T1SERelaxometryCostFunction::New () static
Referenced by anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >::ThreadedGenerateData().
SetRelaxometrySignals()
void anima::T1SERelaxometryCostFunction::SetRelaxometrySignals (std::vector< double > & relaxoSignals) inline
Definition at line 33 of file animaT1SERelaxometryCostFunction.h.
SetTRValues()
void anima::T1SERelaxometryCostFunction::SetTRValues (std::vector< double > & trValues) inline
Definition at line 34 of file animaT1SERelaxometryCostFunction.h.
The documentation for this class was generated from the following files:
animaT1SERelaxometryCostFunction.h
animaT1SERelaxometryCostFunction.cxx