ANIMA: anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType > Class Template Reference
anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType > Class Template Reference
#include <animaPyramidalSymmetryConstrainedRegistrationBridge.h>
Public Types
typedef BaseTransformType::Pointer BaseTransformPointer
typedef itk::AffineTransform< ScalarType, 3 > BaseTransformType
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef InputImageType::RegionType InputImageRegionType
typedef itk::Image< float, 3 > InputImageType
typedef TransformType::MatrixType MatrixType
typedef TransformType::OffsetType OffsetType
typedef TransformType::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef PyramidType::Pointer PyramidPointer
typedef itk::MultiResolutionPyramidImageFilter< InputImageType, InputImageType > PyramidType
typedef PyramidalSymmetryConstrainedRegistrationBridge Self
typedef itk::ProcessObject Superclass
typedef TransformType::Pointer TransformPointer
typedef anima::AxisRotationTransform< ScalarType > TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
double GetHistogramSize ()
Metric GetMetric ()
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfPyramidLevels ()
unsigned int GetOptimizerMaximumIterations ()
std::string GetOutputTransformFile ()
std::string GetResultFile ()
double GetTranslateUpperBound ()
double GetUpperBoundAngle ()
void SetFastRegistration (bool arg)
void SetFloatingImage (InputImagePointer floatingImage)
void SetFloSymmetryTransform (BaseTransformType *trsf)
void SetHistogramSize (double HistogramSize)
void SetMetric (Metric metric)
void SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels)
void SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations)
void SetOutputTransformFile (std::string outputTransformFile)
void SetReferenceImage (InputImagePointer referenceImage)
void SetRefSymmetryTransform (BaseTransformType *trsf)
void SetResultFile (std::string resultFile)
void SetTranslateUpperBound (double val)
void SetUpperBoundAngle (double val)
void Update () ITK_OVERRIDE
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
PyramidalSymmetryConstrainedRegistrationBridge ()
void SetupPyramids ()
virtual ~PyramidalSymmetryConstrainedRegistrationBridge ()
Detailed Description
template<typename ScalarType = double>
class anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >
Definition at line 21 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
Member Typedef Documentation
BaseTransformPointer
template<typename ScalarType = double> typedef BaseTransformType::Pointer anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::BaseTransformPointer
Definition at line 35 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
BaseTransformType
template<typename ScalarType = double> typedef itk::AffineTransform<ScalarType,3> anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::BaseTransformType
Definition at line 34 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
ConstPointer
template<typename ScalarType = double> typedef itk::SmartPointer<const Self> anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::ConstPointer
Definition at line 45 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
InputImagePointer
template<typename ScalarType = double> typedef InputImageType::Pointer anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::InputImagePointer
Definition at line 25 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
InputImageRegionType
template<typename ScalarType = double> typedef InputImageType::RegionType anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::InputImageRegionType
Definition at line 26 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
InputImageType
template<typename ScalarType = double> typedef itk::Image<float,3> anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::InputImageType
Definition at line 24 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
MatrixType
template<typename ScalarType = double> typedef TransformType::MatrixType anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::MatrixType
Definition at line 31 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
OffsetType
template<typename ScalarType = double> typedef TransformType::OffsetType anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::OffsetType
Definition at line 32 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
ParametersType
template<typename ScalarType = double> typedef TransformType::ParametersType anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::ParametersType
Definition at line 30 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
Pointer
template<typename ScalarType = double> typedef itk::SmartPointer<Self> anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::Pointer
Definition at line 44 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
PyramidPointer
template<typename ScalarType = double> typedef PyramidType::Pointer anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::PyramidPointer
Definition at line 38 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
PyramidType
template<typename ScalarType = double> typedef itk::MultiResolutionPyramidImageFilter<InputImageType,InputImageType> anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::PyramidType
Definition at line 37 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
Self
template<typename ScalarType = double> typedef PyramidalSymmetryConstrainedRegistrationBridge anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::Self
SmartPointer typedef support
Definition at line 41 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
Superclass
template<typename ScalarType = double> typedef itk::ProcessObject anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::Superclass
Definition at line 42 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
TransformPointer
template<typename ScalarType = double> typedef TransformType::Pointer anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::TransformPointer
Definition at line 29 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
TransformType
template<typename ScalarType = double> typedef anima::AxisRotationTransform<ScalarType> anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::TransformType
Definition at line 28 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
Constructor & Destructor Documentation
PyramidalSymmetryConstrainedRegistrationBridge()
template<typename ScalarType > anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::PyramidalSymmetryConstrainedRegistrationBridge () protected
Definition at line 26 of file animaPyramidalSymmetryConstrainedRegistrationBridge.hxx.
References MutualInformation.
Referenced by anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetFloSymmetryTransform().
~PyramidalSymmetryConstrainedRegistrationBridge()
template<typename ScalarType > anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::~PyramidalSymmetryConstrainedRegistrationBridge () protected virtual
Definition at line 54 of file animaPyramidalSymmetryConstrainedRegistrationBridge.hxx.
Referenced by anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetFloSymmetryTransform().
Member Function Documentation
CreateAnother()
template<typename ScalarType = double> virtual::itk::LightObject::Pointer anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::CreateAnother (void) const
GetHistogramSize()
template<typename ScalarType = double> double anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetHistogramSize () inline
Definition at line 79 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
GetMetric()
template<typename ScalarType = double> Metric anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetMetric () inline
Definition at line 67 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
GetNameOfClass()
template<typename ScalarType = double> virtual const char* anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetNameOfClass () const virtual
GetNumberOfPyramidLevels()
template<typename ScalarType = double> unsigned int anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetNumberOfPyramidLevels () inline
Definition at line 82 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
GetOptimizerMaximumIterations()
template<typename ScalarType = double> unsigned int anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetOptimizerMaximumIterations () inline
Definition at line 70 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
GetOutputTransformFile()
template<typename ScalarType = double> std::string anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetOutputTransformFile () inline
Definition at line 64 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
GetResultFile()
template<typename ScalarType = double> std::string anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetResultFile () inline
Definition at line 61 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
GetTranslateUpperBound()
template<typename ScalarType = double> double anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetTranslateUpperBound () inline
Definition at line 76 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
GetUpperBoundAngle()
template<typename ScalarType = double> double anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::GetUpperBoundAngle () inline
Definition at line 73 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
New()
template<typename ScalarType = double> static Pointer anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::New () static
SetFastRegistration()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetFastRegistration (bool arg) inline
Definition at line 85 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetFloatingImage()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetFloatingImage (InputImagePointer floatingImage) inline
Definition at line 59 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetFloSymmetryTransform()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetFloSymmetryTransform (BaseTransformType * trsf) inline
Definition at line 88 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
References anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::PyramidalSymmetryConstrainedRegistrationBridge(), anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetupPyramids(), and anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::~PyramidalSymmetryConstrainedRegistrationBridge().
SetHistogramSize()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetHistogramSize (double HistogramSize) inline
Definition at line 80 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetMetric()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetMetric (Metric metric) inline
Definition at line 68 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetNumberOfPyramidLevels()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels) inline
Definition at line 83 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetOptimizerMaximumIterations()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations) inline
Definition at line 71 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetOutputTransformFile()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetOutputTransformFile (std::string outputTransformFile) inline
Definition at line 65 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetReferenceImage()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetReferenceImage (InputImagePointer referenceImage) inline
Setter for images
Definition at line 58 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetRefSymmetryTransform()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetRefSymmetryTransform (BaseTransformType * trsf) inline
Definition at line 87 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetResultFile()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetResultFile (std::string resultFile) inline
Definition at line 62 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetTranslateUpperBound()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetTranslateUpperBound (double val) inline
Definition at line 77 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetUpperBoundAngle()
template<typename ScalarType = double> void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetUpperBoundAngle (double val) inline
Definition at line 74 of file animaPyramidalSymmetryConstrainedRegistrationBridge.h.
SetupPyramids()
template<typename ScalarType > void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetupPyramids () protected
Definition at line 297 of file animaPyramidalSymmetryConstrainedRegistrationBridge.hxx.
References anima::GetRotationMatrixFromVectors().
Referenced by anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::SetFloSymmetryTransform().
Update()
template<typename ScalarType > void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::Update ()
Definition at line 59 of file animaPyramidalSymmetryConstrainedRegistrationBridge.hxx.
References MeanSquares, MutualInformation, and NormalizedMutualInformation.
WriteOutputs()
template<typename ScalarType > void anima::PyramidalSymmetryConstrainedRegistrationBridge< ScalarType >::WriteOutputs ()
Definition at line 280 of file animaPyramidalSymmetryConstrainedRegistrationBridge.hxx.
The documentation for this class was generated from the following files:
animaPyramidalSymmetryConstrainedRegistrationBridge.h
animaPyramidalSymmetryConstrainedRegistrationBridge.hxx