ANIMA: anima::T2EPGRelaxometryCostFunction Class Reference
anima::T2EPGRelaxometryCostFunction Class Reference
#include <animaT2EPGRelaxometryCostFunction.h>
Public Types
typedef std::vector< std::complex< double > > ComplexVectorType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef std::vector< ComplexVectorType > MatrixType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef T2EPGRelaxometryCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual double GetM0Value ()
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetB1OnExcitationAngle (bool _arg)
virtual void SetB1Value (double _arg)
virtual void SetT1Value (double _arg)
virtual void SetT2EchoSpacing (double _arg)
virtual void SetT2ExcitationFlipAngle (double _arg)
void SetT2FlipAngles (std::vector< double > &flipAngles)
void SetT2RelaxometrySignals (std::vector< double > &relaxoSignals)
virtual void SetT2Value (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
T2EPGRelaxometryCostFunction ()
virtual ~T2EPGRelaxometryCostFunction ()
Detailed Description
Definition at line 9 of file animaT2EPGRelaxometryCostFunction.h.
Member Typedef Documentation
ComplexVectorType
typedef std::vector< std::complex <double> > anima::T2EPGRelaxometryCostFunction::ComplexVectorType
Definition at line 27 of file animaT2EPGRelaxometryCostFunction.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::T2EPGRelaxometryCostFunction::ConstPointer
Definition at line 17 of file animaT2EPGRelaxometryCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::T2EPGRelaxometryCostFunction::DerivativeType
Definition at line 25 of file animaT2EPGRelaxometryCostFunction.h.
MatrixType
typedef std::vector<ComplexVectorType> anima::T2EPGRelaxometryCostFunction::MatrixType
Definition at line 28 of file animaT2EPGRelaxometryCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::T2EPGRelaxometryCostFunction::MeasureType
Definition at line 24 of file animaT2EPGRelaxometryCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::T2EPGRelaxometryCostFunction::ParametersType
Definition at line 26 of file animaT2EPGRelaxometryCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::T2EPGRelaxometryCostFunction::Pointer
Definition at line 16 of file animaT2EPGRelaxometryCostFunction.h.
Self
typedef T2EPGRelaxometryCostFunction anima::T2EPGRelaxometryCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaT2EPGRelaxometryCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::T2EPGRelaxometryCostFunction::Superclass
Definition at line 15 of file animaT2EPGRelaxometryCostFunction.h.
Constructor & Destructor Documentation
T2EPGRelaxometryCostFunction()
anima::T2EPGRelaxometryCostFunction::T2EPGRelaxometryCostFunction () inline protected
Definition at line 53 of file animaT2EPGRelaxometryCostFunction.h.
~T2EPGRelaxometryCostFunction()
virtual anima::T2EPGRelaxometryCostFunction::~T2EPGRelaxometryCostFunction () inline protected virtual
Definition at line 65 of file animaT2EPGRelaxometryCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::T2EPGRelaxometryCostFunction::CreateAnother (void) const
GetDerivative()
virtual void anima::T2EPGRelaxometryCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const inline virtual
Definition at line 31 of file animaT2EPGRelaxometryCostFunction.h.
GetM0Value()
virtual double anima::T2EPGRelaxometryCostFunction::GetM0Value () virtual
GetNameOfClass()
virtual const char* anima::T2EPGRelaxometryCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::T2EPGRelaxometryCostFunction::GetNumberOfParameters () const inline
Definition at line 46 of file animaT2EPGRelaxometryCostFunction.h.
GetValue()
T2EPGRelaxometryCostFunction::MeasureType anima::T2EPGRelaxometryCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 8 of file animaT2EPGRelaxometryCostFunction.cxx.
References anima::EPGSignalSimulator::GetValue(), anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), and anima::EPGSignalSimulator::SetNumberOfEchoes().
New()
static Pointer anima::T2EPGRelaxometryCostFunction::New () static
SetB1OnExcitationAngle()
virtual void anima::T2EPGRelaxometryCostFunction::SetB1OnExcitationAngle (bool _arg) virtual
SetB1Value()
virtual void anima::T2EPGRelaxometryCostFunction::SetB1Value (double _arg) virtual
SetT1Value()
virtual void anima::T2EPGRelaxometryCostFunction::SetT1Value (double _arg) virtual
SetT2EchoSpacing()
virtual void anima::T2EPGRelaxometryCostFunction::SetT2EchoSpacing (double _arg) virtual
SetT2ExcitationFlipAngle()
virtual void anima::T2EPGRelaxometryCostFunction::SetT2ExcitationFlipAngle (double _arg) virtual
SetT2FlipAngles()
void anima::T2EPGRelaxometryCostFunction::SetT2FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 37 of file animaT2EPGRelaxometryCostFunction.h.
SetT2RelaxometrySignals()
void anima::T2EPGRelaxometryCostFunction::SetT2RelaxometrySignals (std::vector< double > & relaxoSignals) inline
Definition at line 36 of file animaT2EPGRelaxometryCostFunction.h.
SetT2Value()
virtual void anima::T2EPGRelaxometryCostFunction::SetT2Value (double _arg) virtual
The documentation for this class was generated from the following files:
animaT2EPGRelaxometryCostFunction.h
animaT2EPGRelaxometryCostFunction.cxx