ANIMA: anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions > Class Template Reference
anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions > Class Template Reference
#include <animaBalooExternalExtrapolateImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef TInputImage::Pointer InputImagePointer
typedef TInputImage::IndexType InputIndexType
typedef TInputImage::PixelType InputPixelType
typedef TInputImage::PointType InputPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage::PixelType OutputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef BalooExternalExtrapolateImageFilter Self
typedef itk::InPlaceImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::Image< itk::Vector< TScalarType, NDegreesOfFreedom >, NDimensions > TInputImage
typedef itk::Image< itk::Vector< TScalarType, NDegreesOfFreedom >, NDimensions > TOutputImage
typedef WeightImageType::Pointer WeightImagePointer
typedef itk::Image< TScalarType, NDimensions > WeightImageType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetExtrapolationSigma (double _arg)
virtual void SetWeightImage (WeightImagePointer _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
BalooExternalExtrapolateImageFilter ()
void BeforeThreadedGenerateData () ITK_OVERRIDE
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~BalooExternalExtrapolateImageFilter ()
Detailed Description
template<class TScalarType, unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3>
class anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >
Definition at line 11 of file animaBalooExternalExtrapolateImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::SmartPointer<const Self> anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ConstPointer
Definition at line 23 of file animaBalooExternalExtrapolateImageFilter.h.
InputImagePointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::Pointer anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputImagePointer
Image typedef support
Definition at line 37 of file animaBalooExternalExtrapolateImageFilter.h.
InputIndexType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::IndexType anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputIndexType
Definition at line 33 of file animaBalooExternalExtrapolateImageFilter.h.
InputPixelType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::PixelType anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputPixelType
Definition at line 32 of file animaBalooExternalExtrapolateImageFilter.h.
InputPointType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::PointType anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputPointType
Definition at line 34 of file animaBalooExternalExtrapolateImageFilter.h.
OutputImagePointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TOutputImage::Pointer anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::OutputImagePointer
Definition at line 38 of file animaBalooExternalExtrapolateImageFilter.h.
OutputImageRegionType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef Superclass::OutputImageRegionType anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::OutputImageRegionType
Superclass typedefs.
Definition at line 41 of file animaBalooExternalExtrapolateImageFilter.h.
OutputPixelType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TOutputImage::PixelType anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::OutputPixelType
Definition at line 31 of file animaBalooExternalExtrapolateImageFilter.h.
Pointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::SmartPointer<Self> anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::Pointer
Definition at line 22 of file animaBalooExternalExtrapolateImageFilter.h.
Self
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef BalooExternalExtrapolateImageFilter anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::Self
Standard class typedefs.
Definition at line 16 of file animaBalooExternalExtrapolateImageFilter.h.
Superclass
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::InPlaceImageFilter<TInputImage, TOutputImage> anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::Superclass
Definition at line 21 of file animaBalooExternalExtrapolateImageFilter.h.
TInputImage
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::Image< itk::Vector <TScalarType,NDegreesOfFreedom>, NDimensions > anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::TInputImage
Definition at line 19 of file animaBalooExternalExtrapolateImageFilter.h.
TOutputImage
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::Image< itk::Vector <TScalarType,NDegreesOfFreedom>, NDimensions > anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::TOutputImage
Definition at line 20 of file animaBalooExternalExtrapolateImageFilter.h.
WeightImagePointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef WeightImageType::Pointer anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::WeightImagePointer
Definition at line 18 of file animaBalooExternalExtrapolateImageFilter.h.
WeightImageType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::Image<TScalarType, NDimensions> anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::WeightImageType
Definition at line 17 of file animaBalooExternalExtrapolateImageFilter.h.
Constructor & Destructor Documentation
BalooExternalExtrapolateImageFilter()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::BalooExternalExtrapolateImageFilter () inline protected
Definition at line 47 of file animaBalooExternalExtrapolateImageFilter.h.
~BalooExternalExtrapolateImageFilter()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::~BalooExternalExtrapolateImageFilter () inline protected virtual
Definition at line 53 of file animaBalooExternalExtrapolateImageFilter.h.
References anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::BeforeThreadedGenerateData(), and anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions> void anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::BeforeThreadedGenerateData () protected
Definition at line 17 of file animaBalooExternalExtrapolateImageFilter.hxx.
References anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ThreadedGenerateData().
Referenced by anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::~BalooExternalExtrapolateImageFilter().
CreateAnother()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual::itk::LightObject::Pointer anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::CreateAnother (void) const
GetNameOfClass()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual const char* anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::GetNameOfClass () const virtual
Run-time type information (and related methods)
New()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> static Pointer anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::New () static
Method for creation through the object factory.
SetExtrapolationSigma()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual void anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetExtrapolationSigma (double _arg) virtual
SetWeightImage()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual void anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetWeightImage (WeightImagePointer _arg) virtual
ThreadedGenerateData()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions> void anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 65 of file animaBalooExternalExtrapolateImageFilter.hxx.
Referenced by anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::BeforeThreadedGenerateData(), and anima::BalooExternalExtrapolateImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::~BalooExternalExtrapolateImageFilter().
The documentation for this class was generated from the following files:
animaBalooExternalExtrapolateImageFilter.h
animaBalooExternalExtrapolateImageFilter.hxx