ANIMA: anima::KummerIntegrand Class Reference
anima::KummerIntegrand Class Reference
#include <animaKummerFunctions.h>
Public Member Functions
double operator() (const double t)
void SetAValue (double val)
void SetBValue (double val)
void SetXValue (double val)
Detailed Description
Definition at line 42 of file animaKummerFunctions.h.
Member Function Documentation
operator()()
double anima::KummerIntegrand::operator() (const double t) inline
Definition at line 49 of file animaKummerFunctions.h.
SetAValue()
void anima::KummerIntegrand::SetAValue (double val) inline
Definition at line 46 of file animaKummerFunctions.h.
Referenced by anima::KummerFunction().
SetBValue()
void anima::KummerIntegrand::SetBValue (double val) inline
Definition at line 47 of file animaKummerFunctions.h.
Referenced by anima::KummerFunction().
SetXValue()
void anima::KummerIntegrand::SetXValue (double val) inline
Definition at line 45 of file animaKummerFunctions.h.
Referenced by anima::KummerFunction().
The documentation for this class was generated from the following file:
animaKummerFunctions.h