ANIMA: anima::CheckStructureNeighborFilter< TInput, TMask, TOutput > Class Template Reference
anima::CheckStructureNeighborFilter< TInput, TMask, TOutput > Class Template Reference
Class removing lesions that are not sufficiently in the white matter. Intensity rules may not be enough to discard false positives, therefore we also use localization information. Considering that MS lesions are typically located in WM, we remove the detected ones that do not sufficiently achieve this condition. This filter take two entries: a lesion mask and a white matter map.
#include <animaCheckStructureNeighborFilter.h>
Public Types
typedef itk::ConnectedComponentImageFilter< InputImageType, ImageTypeInt > ConnectedComponentFilterType
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::GrayscaleDilateImageFilter< ImageTypeInt, ImageTypeInt, StructuringElementType > DilateFilterType
typedef itk::ImageRegionIterator< ImageTypeInt > ImageIteratorTypeInt
typedef itk::Image< PixelTypeInt, 3 > ImageTypeInt
typedef itk::ImageRegionConstIterator< InputImageType > InputConstIteratorType
typedef InputImageType::ConstPointer InputImageConstPointer
typedef TInput InputImageType
typedef InputImageType::PixelType InputPixelType
typedef itk::LabelContourImageFilter< ImageTypeInt, ImageTypeInt > LabelContourFilterType
typedef itk::ImageRegionConstIterator< MaskImageType > MaskConstIteratorType
typedef MaskImageType::ConstPointer MaskImageConstPointer
typedef TMask MaskImageType
typedef MaskImageType::PixelType MaskPixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutput OutputImageType
typedef itk::ImageRegionIterator< OutputImageType > OutputIteratorType
typedef OutputImageType::PixelType OutputPixelType
typedef int PixelTypeInt
typedef itk::SmartPointer< Self > Pointer
typedef CheckStructureNeighborFilter Self
typedef itk::BinaryBallStructuringElement< PixelTypeInt, 3 > StructuringElementType
typedef itk::ImageToImageFilter< TInput, TOutput > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual int GetLabelToCheck ()
virtual const char * GetNameOfClass () const
std::string GetOutputFilename ()
virtual float GetRatio ()
virtual bool GetVerbose ()
void SetInputClassification (const TInput *image)
void SetInputMap (const TMask *image)
virtual void SetLabelToCheck (int _arg)
void SetOutputFilename (std::string filename)
virtual void SetRatio (float _arg)
void SetTol (const double tol)
virtual void SetVerbose (bool _arg)
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
CheckStructureNeighborFilter ()
void GenerateData () ITK_OVERRIDE
TInput::ConstPointer GetInputClassification ()
TMask::ConstPointer GetInputMap ()
virtual ~CheckStructureNeighborFilter ()
Detailed Description
template<typename TInput, typename TMask, typename TOutput = TInput>
class anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >
Class removing lesions that are not sufficiently in the white matter. Intensity rules may not be enough to discard false positives, therefore we also use localization information. Considering that MS lesions are typically located in WM, we remove the detected ones that do not sufficiently achieve this condition. This filter take two entries: a lesion mask and a white matter map.
Definition at line 25 of file animaCheckStructureNeighborFilter.h.
Member Typedef Documentation
ConnectedComponentFilterType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ConnectedComponentImageFilter<InputImageType,ImageTypeInt> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::ConnectedComponentFilterType
Definition at line 65 of file animaCheckStructureNeighborFilter.h.
ConstPointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::SmartPointer<const Self> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::ConstPointer
Definition at line 33 of file animaCheckStructureNeighborFilter.h.
DilateFilterType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::GrayscaleDilateImageFilter<ImageTypeInt,ImageTypeInt,StructuringElementType> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::DilateFilterType
Definition at line 68 of file animaCheckStructureNeighborFilter.h.
ImageIteratorTypeInt
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageRegionIterator<ImageTypeInt> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::ImageIteratorTypeInt
Definition at line 63 of file animaCheckStructureNeighborFilter.h.
ImageTypeInt
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::Image<PixelTypeInt,3> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::ImageTypeInt
Definition at line 62 of file animaCheckStructureNeighborFilter.h.
InputConstIteratorType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageRegionConstIterator< InputImageType > anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::InputConstIteratorType
Definition at line 47 of file animaCheckStructureNeighborFilter.h.
InputImageConstPointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef InputImageType::ConstPointer anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::InputImageConstPointer
Definition at line 45 of file animaCheckStructureNeighborFilter.h.
InputImageType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef TInput anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::InputImageType
Image typedef support Type of the input image.
Definition at line 44 of file animaCheckStructureNeighborFilter.h.
InputPixelType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef InputImageType::PixelType anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::InputPixelType
Definition at line 46 of file animaCheckStructureNeighborFilter.h.
LabelContourFilterType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::LabelContourImageFilter<ImageTypeInt,ImageTypeInt> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::LabelContourFilterType
Definition at line 66 of file animaCheckStructureNeighborFilter.h.
MaskConstIteratorType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageRegionConstIterator< MaskImageType > anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::MaskConstIteratorType
Definition at line 53 of file animaCheckStructureNeighborFilter.h.
MaskImageConstPointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef MaskImageType::ConstPointer anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::MaskImageConstPointer
Definition at line 51 of file animaCheckStructureNeighborFilter.h.
MaskImageType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef TMask anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::MaskImageType
Type of the map image.
Definition at line 50 of file animaCheckStructureNeighborFilter.h.
MaskPixelType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef MaskImageType::PixelType anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::MaskPixelType
Definition at line 52 of file animaCheckStructureNeighborFilter.h.
OutputImagePointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef OutputImageType::Pointer anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::OutputImagePointer
Definition at line 57 of file animaCheckStructureNeighborFilter.h.
OutputImageRegionType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef Superclass::OutputImageRegionType anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 84 of file animaCheckStructureNeighborFilter.h.
OutputImageType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef TOutput anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::OutputImageType
Type of the mask image.
Definition at line 56 of file animaCheckStructureNeighborFilter.h.
OutputIteratorType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageRegionIterator<OutputImageType> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::OutputIteratorType
Definition at line 59 of file animaCheckStructureNeighborFilter.h.
OutputPixelType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef OutputImageType::PixelType anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::OutputPixelType
Definition at line 58 of file animaCheckStructureNeighborFilter.h.
PixelTypeInt
template<typename TInput , typename TMask , typename TOutput = TInput> typedef int anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::PixelTypeInt
Definition at line 61 of file animaCheckStructureNeighborFilter.h.
Pointer
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::SmartPointer<Self> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::Pointer
Definition at line 32 of file animaCheckStructureNeighborFilter.h.
Self
template<typename TInput , typename TMask , typename TOutput = TInput> typedef CheckStructureNeighborFilter anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::Self
Standard class typedefs.
Definition at line 30 of file animaCheckStructureNeighborFilter.h.
StructuringElementType
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::BinaryBallStructuringElement<PixelTypeInt, 3> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::StructuringElementType
Definition at line 67 of file animaCheckStructureNeighborFilter.h.
Superclass
template<typename TInput , typename TMask , typename TOutput = TInput> typedef itk::ImageToImageFilter< TInput , TOutput > anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::Superclass
Definition at line 31 of file animaCheckStructureNeighborFilter.h.
Constructor & Destructor Documentation
CheckStructureNeighborFilter()
template<typename TInput , typename TMask , typename TOutput = TInput> anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::CheckStructureNeighborFilter () inline protected
Definition at line 99 of file animaCheckStructureNeighborFilter.h.
~CheckStructureNeighborFilter()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::~CheckStructureNeighborFilter () inline protected virtual
Definition at line 111 of file animaCheckStructureNeighborFilter.h.
References anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GenerateData(), anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetInputClassification(), and anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetInputMap().
Member Function Documentation
CreateAnother()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual::itk::LightObject::Pointer anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::CreateAnother (void) const
GenerateData()
template<typename TInput , typename TMask , typename TOutput > void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GenerateData () protected
Definition at line 48 of file animaCheckStructureNeighborFilter.hxx.
Referenced by anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::WriteOutputs(), and anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::~CheckStructureNeighborFilter().
GetInputClassification()
template<typename TInput , typename TMask , typename TOutput > TInput::ConstPointer anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetInputClassification () protected
Definition at line 21 of file animaCheckStructureNeighborFilter.hxx.
Referenced by anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::~CheckStructureNeighborFilter().
GetInputMap()
template<typename TInput , typename TMask , typename TOutput > TMask::ConstPointer anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetInputMap () protected
Definition at line 27 of file animaCheckStructureNeighborFilter.hxx.
References anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::WriteOutputs().
Referenced by anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::~CheckStructureNeighborFilter().
GetLabelToCheck()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual int anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetLabelToCheck () virtual
GetNameOfClass()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual const char* anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetOutputFilename()
template<typename TInput , typename TMask , typename TOutput = TInput> std::string anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetOutputFilename () inline
Definition at line 95 of file animaCheckStructureNeighborFilter.h.
GetRatio()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual float anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetRatio () virtual
GetVerbose()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual bool anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetVerbose () virtual
New()
template<typename TInput , typename TMask , typename TOutput = TInput> static Pointer anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::New () static
Method for creation through the object factory.
SetInputClassification()
template<typename TInput , typename TMask , typename TOutput > void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::SetInputClassification (const TInput * image)
The mri images.
Definition at line 9 of file animaCheckStructureNeighborFilter.hxx.
SetInputMap()
template<typename TInput , typename TMask , typename TOutput > void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::SetInputMap (const TMask * image)
Definition at line 15 of file animaCheckStructureNeighborFilter.hxx.
SetLabelToCheck()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::SetLabelToCheck (int _arg) virtual
SetOutputFilename()
template<typename TInput , typename TMask , typename TOutput = TInput> void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::SetOutputFilename (std::string filename) inline
Definition at line 96 of file animaCheckStructureNeighborFilter.h.
SetRatio()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::SetRatio (float _arg) virtual
SetTol()
template<typename TInput , typename TMask , typename TOutput = TInput> void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::SetTol (const double tol) inline
Definition at line 76 of file animaCheckStructureNeighborFilter.h.
SetVerbose()
template<typename TInput , typename TMask , typename TOutput = TInput> virtual void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::SetVerbose (bool _arg) virtual
WriteOutputs()
template<typename TInput , typename TMask , typename TOutput > void anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::WriteOutputs ()
Definition at line 36 of file animaCheckStructureNeighborFilter.hxx.
References anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GenerateData().
Referenced by anima::CheckStructureNeighborFilter< TInput, TMask, TOutput >::GetInputMap().
The documentation for this class was generated from the following files:
animaCheckStructureNeighborFilter.h
animaCheckStructureNeighborFilter.hxx