ANIMA: anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Class Template Reference
#include <animaMaskedImageToImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TInputImage::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::ImageSource< TOutputImage >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual const char * GetNameOfClass () const
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
template<typename ScalarRealType >
void InitializeZeroPixel (TOutputImage *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<typename PixelType >
void InitializeZeroPixel (TOutputImage *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Static Protected Member Functions
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TInputImage, typename TOutputImage>
class anima::MaskedImageToImageFilter< TInputImage, TOutputImage >
Definition at line 14 of file animaMaskedImageToImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInputImage, typename TOutputImage> typedef itk::SmartPointer<const Self> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 22 of file animaMaskedImageToImageFilter.h.
InputImageRegionType
template<typename TInputImage, typename TOutputImage> typedef Superclass::InputImageRegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::InputImageRegionType
Superclass typedefs.
Definition at line 31 of file animaMaskedImageToImageFilter.h.
MaskImagePointer
template<typename TInputImage, typename TOutputImage> typedef MaskImageType::Pointer anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskImagePointer
Definition at line 38 of file animaMaskedImageToImageFilter.h.
MaskImageType
template<typename TInputImage, typename TOutputImage> typedef itk::Image<unsigned char,TInputImage::ImageDimension> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskImageType
Mask typedefs
Definition at line 36 of file animaMaskedImageToImageFilter.h.
MaskIndexType
template<typename TInputImage, typename TOutputImage> typedef MaskImageType::IndexType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskIndexType
Definition at line 39 of file animaMaskedImageToImageFilter.h.
MaskRegionType
template<typename TInputImage, typename TOutputImage> typedef MaskImageType::RegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskRegionType
Definition at line 37 of file animaMaskedImageToImageFilter.h.
MaskSizeType
template<typename TInputImage, typename TOutputImage> typedef MaskImageType::SizeType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskSizeType
Definition at line 40 of file animaMaskedImageToImageFilter.h.
OutputImageRegionType
template<typename TInputImage, typename TOutputImage> typedef Superclass::OutputImageRegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::OutputImageRegionType
Definition at line 32 of file animaMaskedImageToImageFilter.h.
Pointer
template<typename TInputImage, typename TOutputImage> typedef itk::SmartPointer<Self> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 21 of file animaMaskedImageToImageFilter.h.
Self
template<typename TInputImage, typename TOutputImage> typedef MaskedImageToImageFilter anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 19 of file animaMaskedImageToImageFilter.h.
Superclass
template<typename TInputImage, typename TOutputImage> typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 20 of file animaMaskedImageToImageFilter.h.
ThreadStruct
template<typename TInputImage, typename TOutputImage> typedef itk::ImageSource<TOutputImage>::ThreadStruct anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::ThreadStruct
Definition at line 33 of file animaMaskedImageToImageFilter.h.
Constructor & Destructor Documentation
MaskedImageToImageFilter()
template<typename TInputImage, typename TOutputImage> anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::MaskedImageToImageFilter () inline protected
Definition at line 51 of file animaMaskedImageToImageFilter.h.
~MaskedImageToImageFilter()
template<typename TInputImage, typename TOutputImage> virtual anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::~MaskedImageToImageFilter () inline protected virtual
Definition at line 61 of file animaMaskedImageToImageFilter.h.
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected virtual
Reimplemented in anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >, anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >, anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::PatientToGroupComparisonImageFilter< PixelScalarType >, anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >, anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >, anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >, anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >, anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >, and anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 80 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
CheckComputationMask()
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::CheckComputationMask () protected virtual
Reimplemented in anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >, anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >, anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, and anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >.
Definition at line 11 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
CreateAnother()
template<typename TInputImage, typename TOutputImage> virtual::itk::LightObject::Pointer anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
DeleteProgressReporter()
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::DeleteProgressReporter () protected virtual
Definition at line 148 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
GenerateData()
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GenerateData () protected virtual
Definition at line 110 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
GetComputationMask()
template<typename TInputImage, typename TOutputImage> virtual MaskImageType* anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetComputationMask () virtual
GetComputationRegion()
template<typename TInputImage, typename TOutputImage> virtual MaskRegionType anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetComputationRegion () virtual
GetNameOfClass()
template<typename TInputImage, typename TOutputImage> virtual const char* anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented in anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >, anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::PatientToGroupComparisonImageFilter< PixelScalarType >, anima::FlipTensorImageFilter< TPixelType, TImageDimension >, anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >, anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >, anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >, anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >, anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >, anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >, and anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >.
InitializeComputationRegionFromMask()
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::InitializeComputationRegionFromMask () protected
Definition at line 32 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
InitializeSplitParameters()
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::InitializeSplitParameters () protected virtual
Definition at line 133 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
InitializeZeroPixel() [1/2]
template<typename TInputImage, typename TOutputImage> template<typename ScalarRealType > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::InitializeZeroPixel (TOutputImage * image, itk::VariableLengthVector< ScalarRealType > & zeroPixel) inline protected
Utility function to initialize output images pixel to zero for vector images.
Definition at line 84 of file animaMaskedImageToImageFilter.h.
InitializeZeroPixel() [2/2]
template<typename TInputImage, typename TOutputImage> template<typename PixelType > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::InitializeZeroPixel (TOutputImage * , PixelType & zeroPixel) inline protected
Utility function to initialize output images pixel to zero for all images except vector images.
Definition at line 94 of file animaMaskedImageToImageFilter.h.
New()
template<typename TInputImage, typename TOutputImage> static Pointer anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
SetComputationMask()
template<typename TInputImage, typename TOutputImage> virtual void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::SetComputationMask (MaskImagePointer _arg) virtual
Set/Get the mask on which to compute estimates.
SetComputationRegion()
template<typename TInputImage, typename TOutputImage> virtual void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::SetComputationRegion (MaskRegionType _arg) virtual
SetVerboseProgression()
template<typename TInputImage, typename TOutputImage> virtual void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::SetVerboseProgression (bool _arg) virtual
ThreaderMultiSplitCallback()
template<typename TInputImage , typename TOutputImage > ITK_THREAD_RETURN_TYPE anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::ThreaderMultiSplitCallback (void * arg) static protected
Definition at line 160 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
ThreadProcessSlices()
template<typename TInputImage , typename TOutputImage > void anima::MaskedImageToImageFilter< TInputImage, TOutputImage >::ThreadProcessSlices (itk::ThreadIdType threadId) protected virtual
Definition at line 177 of file animaMaskedImageToImageFilter.hxx.
Referenced by anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::ThreaderMultiSplitCallback(), and anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >::~MaskedImageToImageFilter().
The documentation for this class was generated from the following files:
animaMaskedImageToImageFilter.h
animaMaskedImageToImageFilter.hxx