ANIMA: anima::MCMMultipleValuedCostFunction Class Reference
anima::MCMMultipleValuedCostFunction Class Reference
#include <animaMCMMultipleValuedCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef InternalCostType::Pointer InternalCostPointer
typedef anima::BaseMCMCost InternalCostType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef MCMMultipleValuedCostFunction Self
typedef itk::MultipleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const InternalCostPointer & GetInternalCost () const
InternalCostType::MCMPointer & GetMCMStructure ()
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
unsigned int GetNumberOfValues () const ITK_OVERRIDE
double GetSigmaSquare ()
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetInternalCost (InternalCostPointer _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
MCMMultipleValuedCostFunction ()
virtual ~MCMMultipleValuedCostFunction () ITK_OVERRIDE
Detailed Description
Definition at line 10 of file animaMCMMultipleValuedCostFunction.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::MCMMultipleValuedCostFunction::ConstPointer
Definition at line 17 of file animaMCMMultipleValuedCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::MCMMultipleValuedCostFunction::DerivativeType
Definition at line 25 of file animaMCMMultipleValuedCostFunction.h.
InternalCostPointer
typedef InternalCostType::Pointer anima::MCMMultipleValuedCostFunction::InternalCostPointer
Definition at line 29 of file animaMCMMultipleValuedCostFunction.h.
InternalCostType
typedef anima::BaseMCMCost anima::MCMMultipleValuedCostFunction::InternalCostType
Definition at line 28 of file animaMCMMultipleValuedCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::MCMMultipleValuedCostFunction::MeasureType
Definition at line 24 of file animaMCMMultipleValuedCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::MCMMultipleValuedCostFunction::ParametersType
Definition at line 26 of file animaMCMMultipleValuedCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::MCMMultipleValuedCostFunction::Pointer
Definition at line 16 of file animaMCMMultipleValuedCostFunction.h.
Self
typedef MCMMultipleValuedCostFunction anima::MCMMultipleValuedCostFunction::Self
Standard class typedefs.
Definition at line 14 of file animaMCMMultipleValuedCostFunction.h.
Superclass
typedef itk::MultipleValuedCostFunction anima::MCMMultipleValuedCostFunction::Superclass
Definition at line 15 of file animaMCMMultipleValuedCostFunction.h.
Constructor & Destructor Documentation
MCMMultipleValuedCostFunction()
anima::MCMMultipleValuedCostFunction::MCMMultipleValuedCostFunction () inline protected
Definition at line 45 of file animaMCMMultipleValuedCostFunction.h.
~MCMMultipleValuedCostFunction()
virtual anima::MCMMultipleValuedCostFunction::~MCMMultipleValuedCostFunction () inline protected virtual
Definition at line 50 of file animaMCMMultipleValuedCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::MCMMultipleValuedCostFunction::CreateAnother (void) const
GetDerivative()
void anima::MCMMultipleValuedCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 38 of file animaMCMMultipleValuedCostFunction.cxx.
References GetSigmaSquare().
Referenced by GetValue().
GetInternalCost()
virtual const InternalCostPointer& anima::MCMMultipleValuedCostFunction::GetInternalCost () const virtual
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetCostValue().
GetMCMStructure()
InternalCostType::MCMPointer& anima::MCMMultipleValuedCostFunction::GetMCMStructure () inline
Definition at line 39 of file animaMCMMultipleValuedCostFunction.h.
References anima::BaseMCMCost::GetMCMStructure().
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
GetNameOfClass()
virtual const char* anima::MCMMultipleValuedCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::MCMMultipleValuedCostFunction::GetNumberOfParameters () const
Definition at line 8 of file animaMCMMultipleValuedCostFunction.cxx.
References GetNumberOfValues().
GetNumberOfValues()
unsigned int anima::MCMMultipleValuedCostFunction::GetNumberOfValues () const
Definition at line 18 of file animaMCMMultipleValuedCostFunction.cxx.
References GetValue().
Referenced by GetNumberOfParameters().
GetSigmaSquare()
double anima::MCMMultipleValuedCostFunction::GetSigmaSquare ()
Definition at line 48 of file animaMCMMultipleValuedCostFunction.cxx.
Referenced by GetDerivative(), and anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GetProfiledInformation().
GetValue()
MCMMultipleValuedCostFunction::MeasureType anima::MCMMultipleValuedCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 28 of file animaMCMMultipleValuedCostFunction.cxx.
References GetDerivative().
Referenced by GetNumberOfValues().
New()
static Pointer anima::MCMMultipleValuedCostFunction::New () static
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::CreateCostFunction().
SetInternalCost()
virtual void anima::MCMMultipleValuedCostFunction::SetInternalCost (InternalCostPointer _arg) virtual
The documentation for this class was generated from the following files:
animaMCMMultipleValuedCostFunction.h
animaMCMMultipleValuedCostFunction.cxx