ANIMA: anima::NonLocalPatchBaseSearcher< ImageType > Class Template Reference
anima::NonLocalPatchBaseSearcher< ImageType > Class Template Reference abstract
#include <animaNonLocalPatchBaseSearcher.h>
Public Types
typedef ImageType::Pointer ImagePointer
typedef ImageType::RegionType ImageRegionType
typedef ImageType::IndexType IndexType
typedef ImageType::PixelType PixelType
typedef ImageType::SizeType SizeType
Public Member Functions
ImageType * GetComparisonImage (unsigned int index)
virtual const std::vector< PixelType > & GetDatabaseSamples () const
virtual const std::vector< double > & GetDatabaseWeights () const
itkGetObjectMacro (InputImage, ImageType) void AddComparisonImage(ImageType *arg)
NonLocalPatchBaseSearcher ()
void SetInputImage (ImageType *arg)
void SetMaxAbsDisp (unsigned int arg)
void SetPatchHalfSize (unsigned int arg)
void SetSearchStepSize (unsigned int arg)
void SetWeightThreshold (double arg)
void UpdateAtPosition (const IndexType &dataIndex)
virtual ~NonLocalPatchBaseSearcher ()
Protected Member Functions
virtual void ComputeComparisonProperties (unsigned int index, ImageRegionType &movingPatch)
virtual void ComputeInputProperties (const IndexType &refIndex, ImageRegionType &refPatch)
virtual double ComputeWeightValue (unsigned int index, ImageRegionType &refPatch, ImageRegionType &movingPatch)=0
virtual bool TestPatchConformity (unsigned int index, const IndexType &refIndex, const IndexType &movingIndex)=0
Detailed Description
template<class ImageType>
class anima::NonLocalPatchBaseSearcher< ImageType >
Abstract class for non local patch matching. May be used to search in multiple images if the concrete class does support it. Does not compute weights and samples for central voxels as these would always get a weight of 1. Instead, it is the developer task to implement it in his filter
Definition at line 15 of file animaNonLocalPatchBaseSearcher.h.
Member Typedef Documentation
ImagePointer
template<class ImageType> typedef ImageType::Pointer anima::NonLocalPatchBaseSearcher< ImageType >::ImagePointer
Definition at line 21 of file animaNonLocalPatchBaseSearcher.h.
ImageRegionType
template<class ImageType> typedef ImageType::RegionType anima::NonLocalPatchBaseSearcher< ImageType >::ImageRegionType
Definition at line 20 of file animaNonLocalPatchBaseSearcher.h.
IndexType
template<class ImageType> typedef ImageType::IndexType anima::NonLocalPatchBaseSearcher< ImageType >::IndexType
Definition at line 18 of file animaNonLocalPatchBaseSearcher.h.
PixelType
template<class ImageType> typedef ImageType::PixelType anima::NonLocalPatchBaseSearcher< ImageType >::PixelType
Definition at line 22 of file animaNonLocalPatchBaseSearcher.h.
SizeType
template<class ImageType> typedef ImageType::SizeType anima::NonLocalPatchBaseSearcher< ImageType >::SizeType
Definition at line 19 of file animaNonLocalPatchBaseSearcher.h.
Constructor & Destructor Documentation
NonLocalPatchBaseSearcher()
template<class ImageType > anima::NonLocalPatchBaseSearcher< ImageType >::NonLocalPatchBaseSearcher ()
Definition at line 12 of file animaNonLocalPatchBaseSearcher.hxx.
~NonLocalPatchBaseSearcher()
template<class ImageType> virtual anima::NonLocalPatchBaseSearcher< ImageType >::~NonLocalPatchBaseSearcher () inline virtual
Definition at line 25 of file animaNonLocalPatchBaseSearcher.h.
Member Function Documentation
ComputeComparisonProperties()
template<class ImageType> virtual void anima::NonLocalPatchBaseSearcher< ImageType >::ComputeComparisonProperties (unsigned int index, ImageRegionType & movingPatch) inline protected virtual
Definition at line 45 of file animaNonLocalPatchBaseSearcher.h.
ComputeInputProperties()
template<class ImageType> virtual void anima::NonLocalPatchBaseSearcher< ImageType >::ComputeInputProperties (const IndexType & refIndex, ImageRegionType & refPatch) inline protected virtual
Definition at line 44 of file animaNonLocalPatchBaseSearcher.h.
ComputeWeightValue()
template<class ImageType> virtual double anima::NonLocalPatchBaseSearcher< ImageType >::ComputeWeightValue (unsigned int index, ImageRegionType & refPatch, ImageRegionType & movingPatch) protected pure virtual
Implemented in anima::NonLocalMeansPatchSearcher< ImageType, DataImageType >, and anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >.
Referenced by anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >::ComputeComparisonProperties().
GetComparisonImage()
template<class ImageType > ImageType * anima::NonLocalPatchBaseSearcher< ImageType >::GetComparisonImage (unsigned int index)
Definition at line 33 of file animaNonLocalPatchBaseSearcher.hxx.
Referenced by anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >::SetInputImage().
GetDatabaseSamples()
template<class ImageType> virtual const std::vector<PixelType>& anima::NonLocalPatchBaseSearcher< ImageType >::GetDatabaseSamples () const virtual
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovPrior().
GetDatabaseWeights()
template<class ImageType> virtual const std::vector<double>& anima::NonLocalPatchBaseSearcher< ImageType >::GetDatabaseWeights () const virtual
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovPrior().
itkGetObjectMacro()
template<class ImageType> anima::NonLocalPatchBaseSearcher< ImageType >::itkGetObjectMacro (InputImage , ImageType)
Referenced by anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >::SetInputImage().
SetInputImage()
template<class ImageType> void anima::NonLocalPatchBaseSearcher< ImageType >::SetInputImage (ImageType * arg) inline
Definition at line 32 of file animaNonLocalPatchBaseSearcher.h.
SetMaxAbsDisp()
template<class ImageType> void anima::NonLocalPatchBaseSearcher< ImageType >::SetMaxAbsDisp (unsigned int arg) inline
Definition at line 29 of file animaNonLocalPatchBaseSearcher.h.
SetPatchHalfSize()
template<class ImageType> void anima::NonLocalPatchBaseSearcher< ImageType >::SetPatchHalfSize (unsigned int arg) inline
Definition at line 27 of file animaNonLocalPatchBaseSearcher.h.
Referenced by anima::NonLocalMeansImageFilter< TInputImage >::ThreadedGenerateData(), and anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >::ThreadedGenerateData().
SetSearchStepSize()
template<class ImageType> void anima::NonLocalPatchBaseSearcher< ImageType >::SetSearchStepSize (unsigned int arg) inline
Definition at line 28 of file animaNonLocalPatchBaseSearcher.h.
SetWeightThreshold()
template<class ImageType> void anima::NonLocalPatchBaseSearcher< ImageType >::SetWeightThreshold (double arg) inline
Definition at line 30 of file animaNonLocalPatchBaseSearcher.h.
TestPatchConformity()
template<class ImageType> virtual bool anima::NonLocalPatchBaseSearcher< ImageType >::TestPatchConformity (unsigned int index, const IndexType & refIndex, const IndexType & movingIndex) protected pure virtual
Implemented in anima::NonLocalMeansPatchSearcher< ImageType, DataImageType >, and anima::NonLocalT2DistributionPatchSearcher< ImageType, DataImageType >.
Referenced by anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >::ComputeComparisonProperties().
UpdateAtPosition()
template<class ImageType > void anima::NonLocalPatchBaseSearcher< ImageType >::UpdateAtPosition (const IndexType & dataIndex)
Definition at line 44 of file animaNonLocalPatchBaseSearcher.hxx.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovPrior(), and anima::NonLocalPatchBaseSearcher< itk::VectorImage< ImageScalarType, DataImageType::ImageDimension > >::SetInputImage().
The documentation for this class was generated from the following files:
animaNonLocalPatchBaseSearcher.h
animaNonLocalPatchBaseSearcher.hxx