ANIMA: anima::NoiseGeneratorImageFilter< ImageType > Class Template Reference
anima::NoiseGeneratorImageFilter< ImageType > Class Template Reference
#include <animaNoiseGeneratorImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef TInputImage InputImageType
typedef TInputImage::PixelType InputPixelType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef TOutputImage::PixelType OutputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef NoiseGeneratorImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef ImageType TInputImage
typedef ImageType TOutputImage
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfReplicates () const
virtual double GetStandardDeviation () const
virtual bool GetUseGaussianDistribution () const
virtual void SetNumberOfReplicates (unsigned int _arg)
virtual void SetStandardDeviation (double _arg)
virtual void SetUseGaussianDistribution (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
NoiseGeneratorImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~NoiseGeneratorImageFilter ()
Detailed Description
template<class ImageType>
class anima::NoiseGeneratorImageFilter< ImageType >
Definition at line 14 of file animaNoiseGeneratorImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class ImageType > typedef itk::SmartPointer<const Self> anima::NoiseGeneratorImageFilter< ImageType >::ConstPointer
Definition at line 24 of file animaNoiseGeneratorImageFilter.h.
InputImagePointer
template<class ImageType > typedef InputImageType::Pointer anima::NoiseGeneratorImageFilter< ImageType >::InputImagePointer
Definition at line 38 of file animaNoiseGeneratorImageFilter.h.
InputImageType
template<class ImageType > typedef TInputImage anima::NoiseGeneratorImageFilter< ImageType >::InputImageType
Image typedef support
Definition at line 36 of file animaNoiseGeneratorImageFilter.h.
InputPixelType
template<class ImageType > typedef TInputImage::PixelType anima::NoiseGeneratorImageFilter< ImageType >::InputPixelType
Definition at line 33 of file animaNoiseGeneratorImageFilter.h.
OutputImagePointer
template<class ImageType > typedef OutputImageType::Pointer anima::NoiseGeneratorImageFilter< ImageType >::OutputImagePointer
Definition at line 39 of file animaNoiseGeneratorImageFilter.h.
OutputImageRegionType
template<class ImageType > typedef Superclass::OutputImageRegionType anima::NoiseGeneratorImageFilter< ImageType >::OutputImageRegionType
Superclass typedefs.
Definition at line 42 of file animaNoiseGeneratorImageFilter.h.
OutputImageType
template<class ImageType > typedef TOutputImage anima::NoiseGeneratorImageFilter< ImageType >::OutputImageType
Definition at line 37 of file animaNoiseGeneratorImageFilter.h.
OutputPixelType
template<class ImageType > typedef TOutputImage::PixelType anima::NoiseGeneratorImageFilter< ImageType >::OutputPixelType
Definition at line 32 of file animaNoiseGeneratorImageFilter.h.
Pointer
template<class ImageType > typedef itk::SmartPointer<Self> anima::NoiseGeneratorImageFilter< ImageType >::Pointer
Definition at line 23 of file animaNoiseGeneratorImageFilter.h.
Self
template<class ImageType > typedef NoiseGeneratorImageFilter anima::NoiseGeneratorImageFilter< ImageType >::Self
Standard class typedefs.
Definition at line 19 of file animaNoiseGeneratorImageFilter.h.
Superclass
template<class ImageType > typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::NoiseGeneratorImageFilter< ImageType >::Superclass
Definition at line 22 of file animaNoiseGeneratorImageFilter.h.
TInputImage
template<class ImageType > typedef ImageType anima::NoiseGeneratorImageFilter< ImageType >::TInputImage
Definition at line 20 of file animaNoiseGeneratorImageFilter.h.
TOutputImage
template<class ImageType > typedef ImageType anima::NoiseGeneratorImageFilter< ImageType >::TOutputImage
Definition at line 21 of file animaNoiseGeneratorImageFilter.h.
Constructor & Destructor Documentation
NoiseGeneratorImageFilter()
template<class ImageType > anima::NoiseGeneratorImageFilter< ImageType >::NoiseGeneratorImageFilter () inline protected
Definition at line 54 of file animaNoiseGeneratorImageFilter.h.
~NoiseGeneratorImageFilter()
template<class ImageType > virtual anima::NoiseGeneratorImageFilter< ImageType >::~NoiseGeneratorImageFilter () inline protected virtual
Definition at line 61 of file animaNoiseGeneratorImageFilter.h.
References anima::NoiseGeneratorImageFilter< ImageType >::BeforeThreadedGenerateData(), anima::NoiseGeneratorImageFilter< ImageType >::GenerateOutputInformation(), and anima::NoiseGeneratorImageFilter< ImageType >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class ImageType > void anima::NoiseGeneratorImageFilter< ImageType >::BeforeThreadedGenerateData () protected
Definition at line 39 of file animaNoiseGeneratorImageFilter.hxx.
References anima::NoiseGeneratorImageFilter< ImageType >::ThreadedGenerateData().
Referenced by anima::NoiseGeneratorImageFilter< ImageType >::GenerateOutputInformation(), and anima::NoiseGeneratorImageFilter< ImageType >::~NoiseGeneratorImageFilter().
CreateAnother()
template<class ImageType > virtual::itk::LightObject::Pointer anima::NoiseGeneratorImageFilter< ImageType >::CreateAnother (void) const
GenerateOutputInformation()
template<class ImageType > void anima::NoiseGeneratorImageFilter< ImageType >::GenerateOutputInformation () protected
Definition at line 16 of file animaNoiseGeneratorImageFilter.hxx.
References anima::NoiseGeneratorImageFilter< ImageType >::BeforeThreadedGenerateData().
Referenced by anima::NoiseGeneratorImageFilter< ImageType >::~NoiseGeneratorImageFilter().
GetNameOfClass()
template<class ImageType > virtual const char* anima::NoiseGeneratorImageFilter< ImageType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetNumberOfReplicates()
template<class ImageType > virtual unsigned int anima::NoiseGeneratorImageFilter< ImageType >::GetNumberOfReplicates () const virtual
GetStandardDeviation()
template<class ImageType > virtual double anima::NoiseGeneratorImageFilter< ImageType >::GetStandardDeviation () const virtual
GetUseGaussianDistribution()
template<class ImageType > virtual bool anima::NoiseGeneratorImageFilter< ImageType >::GetUseGaussianDistribution () const virtual
New()
template<class ImageType > static Pointer anima::NoiseGeneratorImageFilter< ImageType >::New () static
Method for creation through the object factory.
SetNumberOfReplicates()
template<class ImageType > virtual void anima::NoiseGeneratorImageFilter< ImageType >::SetNumberOfReplicates (unsigned int _arg) virtual
SetStandardDeviation()
template<class ImageType > virtual void anima::NoiseGeneratorImageFilter< ImageType >::SetStandardDeviation (double _arg) virtual
SetUseGaussianDistribution()
template<class ImageType > virtual void anima::NoiseGeneratorImageFilter< ImageType >::SetUseGaussianDistribution (bool _arg) virtual
ThreadedGenerateData()
template<class ImageType > void anima::NoiseGeneratorImageFilter< ImageType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 50 of file animaNoiseGeneratorImageFilter.hxx.
References anima::KummerFunction(), and anima::SampleFromGaussianDistribution().
Referenced by anima::NoiseGeneratorImageFilter< ImageType >::BeforeThreadedGenerateData(), and anima::NoiseGeneratorImageFilter< ImageType >::~NoiseGeneratorImageFilter().
The documentation for this class was generated from the following files:
animaNoiseGeneratorImageFilter.h
animaNoiseGeneratorImageFilter.hxx