ANIMA: anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType > Class Template Reference
anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType > Class Template Reference
Implements multi-peak T2 relaxometry estimation (with or without regularization)
#include <animaMultiT2RelaxometryEstimationImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef NNLSOptimizerType::MatrixType DataMatrixType
typedef InputImageType::IndexType IndexType
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef NNLSOptimizerType::Pointer NNLSOptimizerPointer
typedef anima::NNLSOptimizer NNLSOptimizerType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef VectorOutputImageType::PixelType OutputVectorType
typedef anima::NonLocalT2DistributionPatchSearcher< VectorOutputImageType, InputImageType > PatchSearcherType
typedef itk::SmartPointer< Self > Pointer
typedef MultiT2RelaxometryEstimationImageFilter Self
typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef NNLSOptimizerType::ParametersType T2VectorType
typedef itk::Image< TPixelScalarType, 3 > TInputImage
typedef itk::Image< TPixelScalarType, 3 > TOutputImage
typedef VectorOutputImageType::Pointer VectorOutputImagePointer
typedef itk::VectorImage< TPixelScalarType, 3 > VectorOutputImageType
Public Types inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::Image< TPixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< TPixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
InputImageType * GetB1OutputImage ()
InputImageType * GetCostOutputImage ()
InputImageType * GetM0OutputImage ()
InputImageType * GetMWFOutputImage ()
virtual const char * GetNameOfClass () const
InputImageType * GetT1Map ()
VectorOutputImageType * GetT2OutputImage ()
virtual void SetAverageSignalThreshold (double _arg)
virtual void SetB1MaximumOptimizerIterations (unsigned int _arg)
virtual void SetB1OnExcitationAngle (bool _arg)
virtual void SetB1OptimizerInitialStep (double _arg)
virtual void SetB1OptimizerStopCondition (double _arg)
virtual void SetB1Tolerance (double _arg)
virtual void SetBetaParameter (double _arg)
virtual void SetEchoSpacing (double _arg)
virtual void SetInitialB1Map (InputImageType *_arg)
virtual void SetInitialM0Map (InputImageType *_arg)
virtual void SetInitialT2Map (VectorOutputImageType *_arg)
virtual void SetLowerT2Bound (double _arg)
virtual void SetMeanMinThreshold (double _arg)
virtual void SetMyelinThreshold (double _arg)
virtual void SetNLEstimation (bool _arg)
virtual void SetNumberOfT2Compartments (unsigned int _arg)
virtual void SetPatchHalfSize (unsigned int _arg)
virtual void SetRegularizationIntensity (double _arg)
virtual void SetSearchNeighborhood (unsigned int _arg)
virtual void SetSearchStepSize (unsigned int _arg)
void SetT1Map (InputImageType *map)
virtual void SetT2ExcitationFlipAngle (double _arg)
void SetT2FlipAngles (std::vector< double > &flipAngles)
void SetT2FlipAngles (double singleAngle, unsigned int numAngles)
virtual void SetUpperT2Bound (double _arg)
virtual void SetVarMinThreshold (double _arg)
virtual void SetWeightThreshold (double _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void CheckComputationMask () ITK_OVERRIDE
void ComputeTikhonovPrior (const IndexType &refIndex, OutputVectorType &refDistribution, PatchSearcherType &nlPatchSearcher, T2VectorType &priorDistribution, std::vector< double > &workDataWeights, std::vector< OutputVectorType > &workDataSamples)
double ComputeTikhonovRegularizedSolution (anima::NNLSOptimizer *nnlsOpt, DataMatrixType &AMatrix, T2VectorType &signalValues, double lambdaSq, T2VectorType &priorDistribution, T2VectorType &t2OptimizedWeights)
MultiT2RelaxometryEstimationImageFilter ()
void PrepareNLPatchSearchers ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~MultiT2RelaxometryEstimationImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (itk::Image< TPixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< TPixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class TPixelScalarType>
class anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >
Implements multi-peak T2 relaxometry estimation (with or without regularization)
Multi-peak estimation is performed as discussed in several papers: Layton et al. Modelling and estimation of multicomponent T2 distributions. IEEE TMI, 32(8):1423-1434. 2013. Prasloski et al. Applications of stimulated echo correction to multicomponent T2 analysis. MRM, 67(6):1803-1814. 2012. Yoo et al. Non-local spatial regularization of MRI T2 relaxa- tion images for myelin water quantification. MICCAI, pp 614-621. 2013.
Definition at line 23 of file animaMultiT2RelaxometryEstimationImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TPixelScalarType > typedef itk::SmartPointer<const Self> anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ConstPointer
Definition at line 33 of file animaMultiT2RelaxometryEstimationImageFilter.h.
DataMatrixType
template<class TPixelScalarType > typedef NNLSOptimizerType::MatrixType anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::DataMatrixType
Definition at line 58 of file animaMultiT2RelaxometryEstimationImageFilter.h.
IndexType
template<class TPixelScalarType > typedef InputImageType::IndexType anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::IndexType
Definition at line 43 of file animaMultiT2RelaxometryEstimationImageFilter.h.
InputImagePointer
template<class TPixelScalarType > typedef InputImageType::Pointer anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImagePointer
Definition at line 47 of file animaMultiT2RelaxometryEstimationImageFilter.h.
InputImageRegionType
template<class TPixelScalarType > typedef Superclass::InputImageRegionType anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImageRegionType
Definition at line 53 of file animaMultiT2RelaxometryEstimationImageFilter.h.
InputImageType
template<class TPixelScalarType > typedef TInputImage anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::InputImageType
Image typedef support
Definition at line 39 of file animaMultiT2RelaxometryEstimationImageFilter.h.
MaskImageType
template<class TPixelScalarType > typedef Superclass::MaskImageType anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::MaskImageType
Superclass typedefs.
Definition at line 52 of file animaMultiT2RelaxometryEstimationImageFilter.h.
NNLSOptimizerPointer
template<class TPixelScalarType > typedef NNLSOptimizerType::Pointer anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::NNLSOptimizerPointer
Definition at line 57 of file animaMultiT2RelaxometryEstimationImageFilter.h.
NNLSOptimizerType
template<class TPixelScalarType > typedef anima::NNLSOptimizer anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::NNLSOptimizerType
Definition at line 56 of file animaMultiT2RelaxometryEstimationImageFilter.h.
OutputImagePointer
template<class TPixelScalarType > typedef OutputImageType::Pointer anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImagePointer
Definition at line 48 of file animaMultiT2RelaxometryEstimationImageFilter.h.
OutputImageRegionType
template<class TPixelScalarType > typedef Superclass::OutputImageRegionType anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImageRegionType
Definition at line 54 of file animaMultiT2RelaxometryEstimationImageFilter.h.
OutputImageType
template<class TPixelScalarType > typedef TOutputImage anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputImageType
Definition at line 44 of file animaMultiT2RelaxometryEstimationImageFilter.h.
OutputVectorType
template<class TPixelScalarType > typedef VectorOutputImageType::PixelType anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::OutputVectorType
Definition at line 46 of file animaMultiT2RelaxometryEstimationImageFilter.h.
PatchSearcherType
template<class TPixelScalarType > typedef anima::NonLocalT2DistributionPatchSearcher<VectorOutputImageType,InputImageType> anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::PatchSearcherType
Definition at line 61 of file animaMultiT2RelaxometryEstimationImageFilter.h.
Pointer
template<class TPixelScalarType > typedef itk::SmartPointer<Self> anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::Pointer
Definition at line 32 of file animaMultiT2RelaxometryEstimationImageFilter.h.
Self
template<class TPixelScalarType > typedef MultiT2RelaxometryEstimationImageFilter anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::Self
Standard class typedefs.
Definition at line 28 of file animaMultiT2RelaxometryEstimationImageFilter.h.
Superclass
template<class TPixelScalarType > typedef anima::MaskedImageToImageFilter< TInputImage, TOutputImage > anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::Superclass
Definition at line 31 of file animaMultiT2RelaxometryEstimationImageFilter.h.
T2VectorType
template<class TPixelScalarType > typedef NNLSOptimizerType::ParametersType anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::T2VectorType
Definition at line 59 of file animaMultiT2RelaxometryEstimationImageFilter.h.
TInputImage
template<class TPixelScalarType > typedef itk::Image<TPixelScalarType, 3> anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::TInputImage
Definition at line 29 of file animaMultiT2RelaxometryEstimationImageFilter.h.
TOutputImage
template<class TPixelScalarType > typedef itk::Image<TPixelScalarType, 3> anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::TOutputImage
Definition at line 30 of file animaMultiT2RelaxometryEstimationImageFilter.h.
VectorOutputImagePointer
template<class TPixelScalarType > typedef VectorOutputImageType::Pointer anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::VectorOutputImagePointer
Definition at line 49 of file animaMultiT2RelaxometryEstimationImageFilter.h.
VectorOutputImageType
template<class TPixelScalarType > typedef itk::VectorImage<TPixelScalarType, 3> anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::VectorOutputImageType
Definition at line 45 of file animaMultiT2RelaxometryEstimationImageFilter.h.
Constructor & Destructor Documentation
MultiT2RelaxometryEstimationImageFilter()
template<class TPixelScalarType > anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::MultiT2RelaxometryEstimationImageFilter () inline protected
Definition at line 104 of file animaMultiT2RelaxometryEstimationImageFilter.h.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter().
~MultiT2RelaxometryEstimationImageFilter()
template<class TPixelScalarType > virtual anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter () inline protected virtual
Definition at line 141 of file animaMultiT2RelaxometryEstimationImageFilter.h.
References anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::BeforeThreadedGenerateData(), anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::CheckComputationMask(), anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovPrior(), anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovRegularizedSolution(), anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::MultiT2RelaxometryEstimationImageFilter(), anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::PrepareNLPatchSearchers(), and anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
Definition at line 15 of file animaMultiT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter().
CheckComputationMask()
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::CheckComputationMask () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
Definition at line 79 of file animaMultiT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter().
ComputeTikhonovPrior()
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovPrior (const IndexType & refIndex, OutputVectorType & refDistribution, PatchSearcherType & nlPatchSearcher, T2VectorType & priorDistribution, std::vector< double > & workDataWeights, std::vector< OutputVectorType > & workDataSamples) protected
Definition at line 486 of file animaMultiT2RelaxometryEstimationImageFilter.hxx.
References anima::NonLocalPatchBaseSearcher< ImageType >::GetDatabaseSamples(), anima::NonLocalPatchBaseSearcher< ImageType >::GetDatabaseWeights(), and anima::NonLocalPatchBaseSearcher< ImageType >::UpdateAtPosition().
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter().
ComputeTikhonovRegularizedSolution()
template<class TPixelScalarType > double anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ComputeTikhonovRegularizedSolution (anima::NNLSOptimizer * nnlsOpt, DataMatrixType & AMatrix, T2VectorType & signalValues, double lambdaSq, T2VectorType & priorDistribution, T2VectorType & t2OptimizedWeights) protected
Definition at line 536 of file animaMultiT2RelaxometryEstimationImageFilter.hxx.
References anima::NNLSOptimizer::GetCurrentResidual(), anima::NNLSOptimizer::SetDataMatrix(), anima::NNLSOptimizer::SetPoints(), and anima::NNLSOptimizer::StartOptimization().
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter().
CreateAnother()
template<class TPixelScalarType > virtual::itk::LightObject::Pointer anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::CreateAnother (void) const
GetB1OutputImage()
template<class TPixelScalarType > InputImageType* anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetB1OutputImage () inline
Definition at line 89 of file animaMultiT2RelaxometryEstimationImageFilter.h.
GetCostOutputImage()
template<class TPixelScalarType > InputImageType* anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetCostOutputImage () inline
Definition at line 90 of file animaMultiT2RelaxometryEstimationImageFilter.h.
GetM0OutputImage()
template<class TPixelScalarType > InputImageType* anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetM0OutputImage () inline
Definition at line 87 of file animaMultiT2RelaxometryEstimationImageFilter.h.
GetMWFOutputImage()
template<class TPixelScalarType > InputImageType* anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetMWFOutputImage () inline
Definition at line 88 of file animaMultiT2RelaxometryEstimationImageFilter.h.
GetNameOfClass()
template<class TPixelScalarType > virtual const char* anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >.
GetT1Map()
template<class TPixelScalarType > InputImageType* anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetT1Map () inline
Definition at line 71 of file animaMultiT2RelaxometryEstimationImageFilter.h.
GetT2OutputImage()
template<class TPixelScalarType > VectorOutputImageType* anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::GetT2OutputImage () inline
Definition at line 91 of file animaMultiT2RelaxometryEstimationImageFilter.h.
New()
template<class TPixelScalarType > static Pointer anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::New () static
Method for creation through the object factory.
PrepareNLPatchSearchers()
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::PrepareNLPatchSearchers () protected
Definition at line 381 of file animaMultiT2RelaxometryEstimationImageFilter.hxx.
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter().
SetAverageSignalThreshold()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetAverageSignalThreshold (double _arg) virtual
SetB1MaximumOptimizerIterations()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1MaximumOptimizerIterations (unsigned int _arg) virtual
SetB1OnExcitationAngle()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1OnExcitationAngle (bool _arg) virtual
SetB1OptimizerInitialStep()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1OptimizerInitialStep (double _arg) virtual
SetB1OptimizerStopCondition()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1OptimizerStopCondition (double _arg) virtual
SetB1Tolerance()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetB1Tolerance (double _arg) virtual
SetBetaParameter()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetBetaParameter (double _arg) virtual
SetEchoSpacing()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetEchoSpacing (double _arg) virtual
SetInitialB1Map()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetInitialB1Map (InputImageType * _arg) virtual
SetInitialM0Map()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetInitialM0Map (InputImageType * _arg) virtual
SetInitialT2Map()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetInitialT2Map (VectorOutputImageType * _arg) virtual
SetLowerT2Bound()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetLowerT2Bound (double _arg) virtual
SetMeanMinThreshold()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetMeanMinThreshold (double _arg) virtual
SetMyelinThreshold()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetMyelinThreshold (double _arg) virtual
SetNLEstimation()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetNLEstimation (bool _arg) virtual
SetNumberOfT2Compartments()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetNumberOfT2Compartments (unsigned int _arg) virtual
SetPatchHalfSize()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetPatchHalfSize (unsigned int _arg) virtual
SetRegularizationIntensity()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetRegularizationIntensity (double _arg) virtual
SetSearchNeighborhood()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetSearchNeighborhood (unsigned int _arg) virtual
SetSearchStepSize()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetSearchStepSize (unsigned int _arg) virtual
SetT1Map()
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT1Map (InputImageType * map) inline
Definition at line 70 of file animaMultiT2RelaxometryEstimationImageFilter.h.
SetT2ExcitationFlipAngle()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2ExcitationFlipAngle (double _arg) virtual
SetT2FlipAngles() [1/2]
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2FlipAngles (std::vector< double > & flipAngles) inline
Definition at line 100 of file animaMultiT2RelaxometryEstimationImageFilter.h.
SetT2FlipAngles() [2/2]
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetT2FlipAngles (double singleAngle, unsigned int numAngles) inline
Definition at line 101 of file animaMultiT2RelaxometryEstimationImageFilter.h.
SetUpperT2Bound()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetUpperT2Bound (double _arg) virtual
SetVarMinThreshold()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetVarMinThreshold (double _arg) virtual
SetWeightThreshold()
template<class TPixelScalarType > virtual void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::SetWeightThreshold (double _arg) virtual
ThreadedGenerateData()
template<class TPixelScalarType > void anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 127 of file animaMultiT2RelaxometryEstimationImageFilter.hxx.
References anima::EPGSignalSimulator::GetValue(), anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), and anima::EPGSignalSimulator::SetNumberOfEchoes().
Referenced by anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >::~MultiT2RelaxometryEstimationImageFilter().
The documentation for this class was generated from the following files:
animaMultiT2RelaxometryEstimationImageFilter.h
animaMultiT2RelaxometryEstimationImageFilter.hxx