ANIMA: anima::MCMImage< TPixel, VImageDimension > Class Template Reference
anima::MCMImage< TPixel, VImageDimension > Class Template Reference
#include <animaMCMImage.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef MCMType::Pointer MCMPointer
typedef anima::MultiCompartmentModel MCMType
typedef itk::SmartPointer< Self > Pointer
typedef anima::MCMImage< TPixel, VImageDimension > Self
typedef itk::VectorImage< TPixel, VImageDimension > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
MCMPointer & GetDescriptionModel ()
virtual const char * GetNameOfClass () const
virtual void Graft (const itk::DataObject *data) ITK_OVERRIDE
void SetDescriptionModel (MCMPointer &mcm)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
MCMImage ()
virtual ~MCMImage ()
Detailed Description
template<typename TPixel, unsigned int VImageDimension = 3>
class anima::MCMImage< TPixel, VImageDimension >
Definition at line 10 of file animaMCMImage.h.
Member Typedef Documentation
ConstPointer
template<typename TPixel, unsigned int VImageDimension = 3> typedef itk::SmartPointer< const Self > anima::MCMImage< TPixel, VImageDimension >::ConstPointer
Definition at line 16 of file animaMCMImage.h.
MCMPointer
template<typename TPixel, unsigned int VImageDimension = 3> typedef MCMType::Pointer anima::MCMImage< TPixel, VImageDimension >::MCMPointer
Definition at line 22 of file animaMCMImage.h.
MCMType
template<typename TPixel, unsigned int VImageDimension = 3> typedef anima::MultiCompartmentModel anima::MCMImage< TPixel, VImageDimension >::MCMType
Definition at line 21 of file animaMCMImage.h.
Pointer
template<typename TPixel, unsigned int VImageDimension = 3> typedef itk::SmartPointer< Self > anima::MCMImage< TPixel, VImageDimension >::Pointer
Definition at line 15 of file animaMCMImage.h.
Self
template<typename TPixel, unsigned int VImageDimension = 3> typedef anima::MCMImage<TPixel,VImageDimension> anima::MCMImage< TPixel, VImageDimension >::Self
Definition at line 14 of file animaMCMImage.h.
Superclass
template<typename TPixel, unsigned int VImageDimension = 3> typedef itk::VectorImage<TPixel, VImageDimension> anima::MCMImage< TPixel, VImageDimension >::Superclass
Definition at line 13 of file animaMCMImage.h.
Constructor & Destructor Documentation
MCMImage()
template<typename TPixel , unsigned int VImageDimension> anima::MCMImage< TPixel, VImageDimension >::MCMImage () protected
Definition at line 8 of file animaMCMImage.hxx.
Referenced by anima::MCMImage< TPixel, VImageDimension >::~MCMImage().
~MCMImage()
template<typename TPixel, unsigned int VImageDimension = 3> virtual anima::MCMImage< TPixel, VImageDimension >::~MCMImage () inline protected virtual
Definition at line 31 of file animaMCMImage.h.
References anima::MCMImage< TPixel, VImageDimension >::MCMImage().
Member Function Documentation
CreateAnother()
template<typename TPixel, unsigned int VImageDimension = 3> virtual::itk::LightObject::Pointer anima::MCMImage< TPixel, VImageDimension >::CreateAnother (void) const
GetDescriptionModel()
template<typename TPixel , unsigned int VImageDimension> MCMImage< TPixel, VImageDimension >::MCMPointer & anima::MCMImage< TPixel, VImageDimension >::GetDescriptionModel ()
Definition at line 32 of file animaMCMImage.hxx.
Referenced by anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::AddReferenceImage(), anima::MCMAverageImagesImageFilter< TPixelType >::BeforeThreadedGenerateData(), and anima::PyramidalDenseMCMSVFMatchingBridge< ImageDimension >::CreateInterpolator().
GetNameOfClass()
template<typename TPixel, unsigned int VImageDimension = 3> virtual const char* anima::MCMImage< TPixel, VImageDimension >::GetNameOfClass () const virtual
Graft()
template<typename TPixel , unsigned int VImageDimension> void anima::MCMImage< TPixel, VImageDimension >::Graft (const itk::DataObject * data) virtual
Definition at line 39 of file animaMCMImage.hxx.
New()
template<typename TPixel, unsigned int VImageDimension = 3> static Pointer anima::MCMImage< TPixel, VImageDimension >::New () static
SetDescriptionModel()
template<typename TPixel , unsigned int VImageDimension> void anima::MCMImage< TPixel, VImageDimension >::SetDescriptionModel (MCMPointer & mcm)
Definition at line 15 of file animaMCMImage.hxx.
Referenced by anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >::GenerateOutputInformation().
The documentation for this class was generated from the following files:
animaMCMImage.h
animaMCMImage.hxx