ANIMA: anima::Graph< captype, tcaptype, flowtype > Class Template Reference
anima::Graph< captype, tcaptype, flowtype > Class Template Reference
#include <animaGraph.h>
Classes
struct arc
struct node
struct nodeptr
Public Types
typedef arc * arc_id
typedef int node_id
enum termtype {
SOURCE = 0,
SINK = 1
}
Public Member Functions
void add_edge (node_id i, node_id j, captype cap, captype rev_cap)
node_id add_node (int num=1)
void add_to_changed_list (node *i)
void add_tweights (node_id i, tcaptype cap_source, tcaptype cap_sink)
void augment (arc *middle_arc)
void get_arc_ends (arc_id a, node_id &i, node_id &j)
int get_arc_num ()
arc_id get_first_arc ()
arc_id get_next_arc (arc_id a)
int get_node_num ()
captype get_rcap (arc *a)
tcaptype get_trcap (node_id i)
Graph (int node_num_max, int edge_num_max, void(*err_function)(char *)=NULL)
void mark_node (node_id i)
flowtype maxflow (bool reuse_trees=false, Block< node_id > *changed_list=NULL)
void maxflow_init ()
void maxflow_reuse_trees_init ()
node * next_active ()
void process_sink_orphan (node *i)
void process_source_orphan (node *i)
void reallocate_arcs ()
void reallocate_nodes (int num)
void remove_from_changed_list (node_id i)
void reset ()
void set_active (node *i)
void set_orphan_front (node *i)
void set_orphan_rear (node *i)
void set_rcap (arc *a, captype rcap)
void set_trcap (node_id i, tcaptype trcap)
void test_consistency (node *current_node=NULL)
termtype what_segment (node_id i, termtype default_segm=SOURCE)
~Graph ()
Public Attributes
arc * arc_last
arc * arc_max
arc * arcs
Block< node_id > * changed_list
void(* error_function)(char *)
flowtype flow
int maxflow_iteration
node * node_last
node * node_max
int node_num
DBlock< nodeptr > * nodeptr_block
node * nodes
nodeptr * orphan_first
nodeptr * orphan_last
node * queue_first [2]
node * queue_last [2]
int TIME
Static Public Attributes
static const int NODEPTR_BLOCK_SIZE = 128
Detailed Description
template<typename captype, typename tcaptype, typename flowtype>
class anima::Graph< captype, tcaptype, flowtype >
Definition at line 91 of file animaGraph.h.
Member Typedef Documentation
arc_id
template<typename captype, typename tcaptype, typename flowtype> typedef arc* anima::Graph< captype, tcaptype, flowtype >::arc_id
Definition at line 193 of file animaGraph.h.
node_id
template<typename captype, typename tcaptype, typename flowtype> typedef int anima::Graph< captype, tcaptype, flowtype >::node_id
Definition at line 99 of file animaGraph.h.
Member Enumeration Documentation
termtype
template<typename captype, typename tcaptype, typename flowtype> enum anima::Graph::termtype
Enumerator
SOURCE
SINK
Definition at line 94 of file animaGraph.h.
Constructor & Destructor Documentation
Graph()
template<typename captype , typename tcaptype , typename flowtype > anima::Graph< captype, tcaptype, flowtype >::Graph (int node_num_max, int edge_num_max, void(*)(char *) err_function = NULL) inline
Definition at line 396 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arc_max, anima::Graph< captype, tcaptype, flowtype >::arcs, anima::Graph< captype, tcaptype, flowtype >::flow, anima::Graph< captype, tcaptype, flowtype >::maxflow_iteration, anima::Graph< captype, tcaptype, flowtype >::node_last, anima::Graph< captype, tcaptype, flowtype >::node_max, and anima::Graph< captype, tcaptype, flowtype >::nodes.
~Graph()
template<typename captype , typename tcaptype , typename flowtype > anima::Graph< captype, tcaptype, flowtype >::~Graph () inline
Definition at line 419 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arcs, anima::Graph< captype, tcaptype, flowtype >::nodeptr_block, and anima::Graph< captype, tcaptype, flowtype >::nodes.
Member Function Documentation
add_edge()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::add_edge (node_id i, node_id j, captype cap, captype rev_cap) inline
Definition at line 543 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arc_max, anima::Graph< captype, tcaptype, flowtype >::node_num, anima::Graph< captype, tcaptype, flowtype >::nodes, and anima::Graph< captype, tcaptype, flowtype >::reallocate_arcs().
add_node()
template<typename captype , typename tcaptype , typename flowtype > Graph< captype, tcaptype, flowtype >::node_id anima::Graph< captype, tcaptype, flowtype >::add_node (int num = 1) inline
Definition at line 503 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node_last, anima::Graph< captype, tcaptype, flowtype >::node_max, anima::Graph< captype, tcaptype, flowtype >::node_num, and anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes().
add_to_changed_list()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::add_to_changed_list (node * i) inline
Definition at line 746 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::changed_list, anima::Graph< captype, tcaptype, flowtype >::node::is_in_changed_list, anima::Block< Type >::New(), and anima::Graph< captype, tcaptype, flowtype >::nodes.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::process_sink_orphan(), and anima::Graph< captype, tcaptype, flowtype >::process_source_orphan().
add_tweights()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::add_tweights (node_id i, tcaptype cap_source, tcaptype cap_sink) inline
Definition at line 531 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::flow, anima::Graph< captype, tcaptype, flowtype >::node_num, anima::Graph< captype, tcaptype, flowtype >::nodes, and anima::Graph< captype, tcaptype, flowtype >::node::tr_cap.
augment()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::augment (arc * middle_arc) inline
Definition at line 884 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::flow, anima::Graph< captype, tcaptype, flowtype >::arc::head, anima::Graph< captype, tcaptype, flowtype >::arc::r_cap, anima::Graph< captype, tcaptype, flowtype >::set_orphan_front(), anima::Graph< captype, tcaptype, flowtype >::arc::sister, TERMINAL, and anima::Graph< captype, tcaptype, flowtype >::node::tr_cap.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow().
get_arc_ends()
template<typename captype, typename tcaptype, typename flowtype> void anima::Graph< captype, tcaptype, flowtype >::get_arc_ends (arc_id a, node_id & i, node_id & j) inline
Definition at line 584 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arcs, anima::Graph< captype, tcaptype, flowtype >::arc::head, anima::Graph< captype, tcaptype, flowtype >::nodes, and anima::Graph< captype, tcaptype, flowtype >::arc::sister.
Referenced by anima::Graph< captype, tcaptype, flowtype >::get_arc_num().
get_arc_num()
template<typename captype, typename tcaptype, typename flowtype> int anima::Graph< captype, tcaptype, flowtype >::get_arc_num () inline
Definition at line 199 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arcs, anima::Graph< captype, tcaptype, flowtype >::get_arc_ends(), anima::Graph< captype, tcaptype, flowtype >::get_rcap(), anima::Graph< captype, tcaptype, flowtype >::get_trcap(), anima::Graph< captype, tcaptype, flowtype >::mark_node(), anima::Graph< captype, tcaptype, flowtype >::set_rcap(), and anima::Graph< captype, tcaptype, flowtype >::set_trcap().
get_first_arc()
template<typename captype , typename tcaptype , typename flowtype > Graph< captype, tcaptype, flowtype >::arc * anima::Graph< captype, tcaptype, flowtype >::get_first_arc () inline
Definition at line 572 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arcs.
get_next_arc()
template<typename captype, typename tcaptype, typename flowtype> Graph< captype, tcaptype, flowtype >::arc * anima::Graph< captype, tcaptype, flowtype >::get_next_arc (arc_id a) inline
Definition at line 578 of file animaGraph.h.
get_node_num()
template<typename captype, typename tcaptype, typename flowtype> int anima::Graph< captype, tcaptype, flowtype >::get_node_num () inline
Definition at line 198 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node_num.
get_rcap()
template<typename captype , typename tcaptype , typename flowtype > captype anima::Graph< captype, tcaptype, flowtype >::get_rcap (arc * a) inline
Definition at line 599 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arcs, and anima::Graph< captype, tcaptype, flowtype >::arc::r_cap.
Referenced by anima::Graph< captype, tcaptype, flowtype >::get_arc_num().
get_trcap()
template<typename captype , typename tcaptype , typename flowtype > tcaptype anima::Graph< captype, tcaptype, flowtype >::get_trcap (node_id i) inline
Definition at line 592 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node_num, anima::Graph< captype, tcaptype, flowtype >::nodes, and anima::Graph< captype, tcaptype, flowtype >::node::tr_cap.
Referenced by anima::Graph< captype, tcaptype, flowtype >::get_arc_num().
mark_node()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::mark_node (node_id i) inline
Definition at line 634 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node::is_marked, anima::Graph< captype, tcaptype, flowtype >::node::next, anima::Graph< captype, tcaptype, flowtype >::nodes, anima::Graph< captype, tcaptype, flowtype >::queue_first, and anima::Graph< captype, tcaptype, flowtype >::queue_last.
Referenced by anima::Graph< captype, tcaptype, flowtype >::get_arc_num().
maxflow()
template<typename captype , typename tcaptype , typename flowtype > flowtype anima::Graph< captype, tcaptype, flowtype >::maxflow (bool reuse_trees = false, Block< node_id > * changed_list = NULL) inline
Definition at line 1112 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::add_to_changed_list(), anima::Graph< captype, tcaptype, flowtype >::augment(), anima::Graph< captype, tcaptype, flowtype >::changed_list, anima::Graph< captype, tcaptype, flowtype >::node::DIST, anima::Graph< captype, tcaptype, flowtype >::error_function, anima::Graph< captype, tcaptype, flowtype >::node::first, anima::Graph< captype, tcaptype, flowtype >::flow, anima::Graph< captype, tcaptype, flowtype >::node::is_sink, anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::maxflow_iteration, anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::arc::next, anima::Graph< captype, tcaptype, flowtype >::next_active(), anima::Graph< captype, tcaptype, flowtype >::nodeptr_block, anima::Graph< captype, tcaptype, flowtype >::NODEPTR_BLOCK_SIZE, anima::Graph< captype, tcaptype, flowtype >::orphan_first, anima::Graph< captype, tcaptype, flowtype >::orphan_last, anima::Graph< captype, tcaptype, flowtype >::node::parent, anima::Graph< captype, tcaptype, flowtype >::process_sink_orphan(), anima::Graph< captype, tcaptype, flowtype >::process_source_orphan(), anima::Graph< captype, tcaptype, flowtype >::arc::r_cap, anima::Graph< captype, tcaptype, flowtype >::set_active(), anima::Graph< captype, tcaptype, flowtype >::arc::sister, anima::Graph< captype, tcaptype, flowtype >::TIME, and anima::Graph< captype, tcaptype, flowtype >::node::TS.
maxflow_init()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::maxflow_init () inline
Definition at line 759 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node_last, anima::Graph< captype, tcaptype, flowtype >::nodes, anima::Graph< captype, tcaptype, flowtype >::orphan_first, anima::Graph< captype, tcaptype, flowtype >::queue_first, anima::Graph< captype, tcaptype, flowtype >::queue_last, anima::Graph< captype, tcaptype, flowtype >::set_active(), TERMINAL, anima::Graph< captype, tcaptype, flowtype >::TIME, and anima::Graph< captype, tcaptype, flowtype >::node::tr_cap.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow().
maxflow_reuse_trees_init()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init () inline
Definition at line 799 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::add_to_changed_list(), anima::Graph< captype, tcaptype, flowtype >::node::first, anima::Graph< captype, tcaptype, flowtype >::arc::head, anima::Graph< captype, tcaptype, flowtype >::node::is_marked, anima::Graph< captype, tcaptype, flowtype >::node::is_sink, anima::Graph< captype, tcaptype, flowtype >::node::next, anima::Graph< captype, tcaptype, flowtype >::arc::next, anima::Graph< captype, tcaptype, flowtype >::nodeptr_block, anima::Graph< captype, tcaptype, flowtype >::orphan_first, anima::Graph< captype, tcaptype, flowtype >::orphan_last, anima::Graph< captype, tcaptype, flowtype >::node::parent, anima::Graph< captype, tcaptype, flowtype >::process_sink_orphan(), anima::Graph< captype, tcaptype, flowtype >::process_source_orphan(), anima::Graph< captype, tcaptype, flowtype >::queue_first, anima::Graph< captype, tcaptype, flowtype >::queue_last, anima::Graph< captype, tcaptype, flowtype >::arc::r_cap, anima::Graph< captype, tcaptype, flowtype >::set_active(), anima::Graph< captype, tcaptype, flowtype >::set_orphan_rear(), anima::Graph< captype, tcaptype, flowtype >::arc::sister, TERMINAL, anima::Graph< captype, tcaptype, flowtype >::TIME, and anima::Graph< captype, tcaptype, flowtype >::node::tr_cap.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow().
next_active()
template<typename captype , typename tcaptype , typename flowtype > Graph< captype, tcaptype, flowtype >::node * anima::Graph< captype, tcaptype, flowtype >::next_active () inline
Definition at line 692 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node::next, anima::Graph< captype, tcaptype, flowtype >::node::parent, anima::Graph< captype, tcaptype, flowtype >::queue_first, and anima::Graph< captype, tcaptype, flowtype >::queue_last.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow().
process_sink_orphan()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::process_sink_orphan (node * i) inline
Definition at line 1033 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::add_to_changed_list(), anima::Graph< captype, tcaptype, flowtype >::node::first, anima::Graph< captype, tcaptype, flowtype >::arc::head, INFINITE_D, anima::Graph< captype, tcaptype, flowtype >::node::is_sink, anima::Graph< captype, tcaptype, flowtype >::arc::next, ORPHAN, anima::Graph< captype, tcaptype, flowtype >::node::parent, anima::Graph< captype, tcaptype, flowtype >::arc::r_cap, anima::Graph< captype, tcaptype, flowtype >::set_active(), anima::Graph< captype, tcaptype, flowtype >::set_orphan_rear(), TERMINAL, anima::Graph< captype, tcaptype, flowtype >::TIME, and anima::Graph< captype, tcaptype, flowtype >::node::TS.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), and anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init().
process_source_orphan()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::process_source_orphan (node * i) inline
Definition at line 956 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::add_to_changed_list(), anima::Graph< captype, tcaptype, flowtype >::node::first, anima::Graph< captype, tcaptype, flowtype >::arc::head, INFINITE_D, anima::Graph< captype, tcaptype, flowtype >::node::is_sink, anima::Graph< captype, tcaptype, flowtype >::arc::next, ORPHAN, anima::Graph< captype, tcaptype, flowtype >::node::parent, anima::Graph< captype, tcaptype, flowtype >::arc::r_cap, anima::Graph< captype, tcaptype, flowtype >::set_active(), anima::Graph< captype, tcaptype, flowtype >::set_orphan_rear(), anima::Graph< captype, tcaptype, flowtype >::arc::sister, TERMINAL, anima::Graph< captype, tcaptype, flowtype >::TIME, and anima::Graph< captype, tcaptype, flowtype >::node::TS.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), and anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init().
reallocate_arcs()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::reallocate_arcs () inline
Definition at line 472 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arc_max, anima::Graph< captype, tcaptype, flowtype >::arcs, anima::Graph< captype, tcaptype, flowtype >::node::first, anima::Graph< captype, tcaptype, flowtype >::arc::next, anima::Graph< captype, tcaptype, flowtype >::node_last, anima::Graph< captype, tcaptype, flowtype >::nodes, and anima::Graph< captype, tcaptype, flowtype >::arc::sister.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_edge().
reallocate_nodes()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes (int num) inline
Definition at line 448 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arcs, anima::Graph< captype, tcaptype, flowtype >::arc::head, anima::Graph< captype, tcaptype, flowtype >::node_last, anima::Graph< captype, tcaptype, flowtype >::node_max, anima::Graph< captype, tcaptype, flowtype >::node_num, and anima::Graph< captype, tcaptype, flowtype >::nodes.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_node().
remove_from_changed_list()
template<typename captype, typename tcaptype, typename flowtype> void anima::Graph< captype, tcaptype, flowtype >::remove_from_changed_list (node_id i) inline
Definition at line 281 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node::is_in_changed_list, anima::Graph< captype, tcaptype, flowtype >::node_num, and anima::Graph< captype, tcaptype, flowtype >::nodes.
reset()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::reset () inline
Definition at line 431 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arcs, anima::Graph< captype, tcaptype, flowtype >::flow, anima::Graph< captype, tcaptype, flowtype >::maxflow_iteration, anima::Graph< captype, tcaptype, flowtype >::node_last, anima::Graph< captype, tcaptype, flowtype >::node_num, anima::Graph< captype, tcaptype, flowtype >::nodeptr_block, and anima::Graph< captype, tcaptype, flowtype >::nodes.
set_active()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::set_active (node * i) inline
Definition at line 674 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node::next, anima::Graph< captype, tcaptype, flowtype >::queue_first, and anima::Graph< captype, tcaptype, flowtype >::queue_last.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::process_sink_orphan(), and anima::Graph< captype, tcaptype, flowtype >::process_source_orphan().
set_orphan_front()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::set_orphan_front (node * i) inline
Definition at line 720 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::nodeptr_block, ORPHAN, and anima::Graph< captype, tcaptype, flowtype >::orphan_first.
Referenced by anima::Graph< captype, tcaptype, flowtype >::augment().
set_orphan_rear()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::set_orphan_rear (node * i) inline
Definition at line 731 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::nodeptr_block, ORPHAN, anima::Graph< captype, tcaptype, flowtype >::orphan_first, and anima::Graph< captype, tcaptype, flowtype >::orphan_last.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::process_sink_orphan(), and anima::Graph< captype, tcaptype, flowtype >::process_source_orphan().
set_rcap()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::set_rcap (arc * a, captype rcap) inline
Definition at line 613 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::arc_last, anima::Graph< captype, tcaptype, flowtype >::arcs, and anima::Graph< captype, tcaptype, flowtype >::arc::r_cap.
Referenced by anima::Graph< captype, tcaptype, flowtype >::get_arc_num().
set_trcap()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::set_trcap (node_id i, tcaptype trcap) inline
Definition at line 606 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node_num, anima::Graph< captype, tcaptype, flowtype >::nodes, and anima::Graph< captype, tcaptype, flowtype >::node::tr_cap.
Referenced by anima::Graph< captype, tcaptype, flowtype >::get_arc_num().
test_consistency()
template<typename captype , typename tcaptype , typename flowtype > void anima::Graph< captype, tcaptype, flowtype >::test_consistency (node * current_node = NULL) inline
Definition at line 1250 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::node::DIST, anima::Graph< captype, tcaptype, flowtype >::node::first, anima::Graph< captype, tcaptype, flowtype >::arc::head, anima::Graph< captype, tcaptype, flowtype >::node::is_sink, anima::Graph< captype, tcaptype, flowtype >::node::next, anima::Graph< captype, tcaptype, flowtype >::arc::next, anima::Graph< captype, tcaptype, flowtype >::node_last, anima::Graph< captype, tcaptype, flowtype >::nodes, ORPHAN, anima::Graph< captype, tcaptype, flowtype >::node::parent, anima::Graph< captype, tcaptype, flowtype >::queue_first, anima::Graph< captype, tcaptype, flowtype >::queue_last, anima::Graph< captype, tcaptype, flowtype >::arc::r_cap, anima::Graph< captype, tcaptype, flowtype >::arc::sister, TERMINAL, anima::Graph< captype, tcaptype, flowtype >::node::tr_cap, and anima::Graph< captype, tcaptype, flowtype >::node::TS.
what_segment()
template<typename captype , typename tcaptype , typename flowtype > Graph< captype, tcaptype, flowtype >::termtype anima::Graph< captype, tcaptype, flowtype >::what_segment (node_id i, termtype default_segm = SOURCE) inline
Definition at line 621 of file animaGraph.h.
References anima::Graph< captype, tcaptype, flowtype >::nodes, anima::Graph< captype, tcaptype, flowtype >::SINK, and anima::Graph< captype, tcaptype, flowtype >::SOURCE.
Member Data Documentation
arc_last
template<typename captype, typename tcaptype, typename flowtype> arc * anima::Graph< captype, tcaptype, flowtype >::arc_last
Definition at line 335 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_edge(), anima::Graph< captype, tcaptype, flowtype >::get_arc_ends(), anima::Graph< captype, tcaptype, flowtype >::get_arc_num(), anima::Graph< captype, tcaptype, flowtype >::get_rcap(), anima::Graph< captype, tcaptype, flowtype >::Graph(), anima::Graph< captype, tcaptype, flowtype >::reallocate_arcs(), anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes(), anima::Graph< captype, tcaptype, flowtype >::reset(), and anima::Graph< captype, tcaptype, flowtype >::set_rcap().
arc_max
template<typename captype, typename tcaptype, typename flowtype> arc * anima::Graph< captype, tcaptype, flowtype >::arc_max
Definition at line 335 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_edge(), anima::Graph< captype, tcaptype, flowtype >::Graph(), and anima::Graph< captype, tcaptype, flowtype >::reallocate_arcs().
arcs
template<typename captype, typename tcaptype, typename flowtype> arc* anima::Graph< captype, tcaptype, flowtype >::arcs
Definition at line 335 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::get_arc_ends(), anima::Graph< captype, tcaptype, flowtype >::get_arc_num(), anima::Graph< captype, tcaptype, flowtype >::get_first_arc(), anima::Graph< captype, tcaptype, flowtype >::get_rcap(), anima::Graph< captype, tcaptype, flowtype >::Graph(), anima::Graph< captype, tcaptype, flowtype >::reallocate_arcs(), anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes(), anima::Graph< captype, tcaptype, flowtype >::reset(), anima::Graph< captype, tcaptype, flowtype >::set_rcap(), and anima::Graph< captype, tcaptype, flowtype >::~Graph().
changed_list
template<typename captype, typename tcaptype, typename flowtype> Block<node_id>* anima::Graph< captype, tcaptype, flowtype >::changed_list
Definition at line 349 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_to_changed_list(), and anima::Graph< captype, tcaptype, flowtype >::maxflow().
error_function
template<typename captype, typename tcaptype, typename flowtype> void(* anima::Graph< captype, tcaptype, flowtype >::error_function) (char *)
Definition at line 341 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow().
flow
template<typename captype, typename tcaptype, typename flowtype> flowtype anima::Graph< captype, tcaptype, flowtype >::flow
Definition at line 345 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_tweights(), anima::Graph< captype, tcaptype, flowtype >::augment(), anima::Graph< captype, tcaptype, flowtype >::Graph(), anima::Graph< captype, tcaptype, flowtype >::maxflow(), and anima::Graph< captype, tcaptype, flowtype >::reset().
maxflow_iteration
template<typename captype, typename tcaptype, typename flowtype> int anima::Graph< captype, tcaptype, flowtype >::maxflow_iteration
Definition at line 348 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::Graph(), anima::Graph< captype, tcaptype, flowtype >::maxflow(), and anima::Graph< captype, tcaptype, flowtype >::reset().
node_last
template<typename captype, typename tcaptype, typename flowtype> node * anima::Graph< captype, tcaptype, flowtype >::node_last
Definition at line 334 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_node(), anima::Graph< captype, tcaptype, flowtype >::Graph(), anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::reallocate_arcs(), anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes(), anima::Graph< captype, tcaptype, flowtype >::reset(), and anima::Graph< captype, tcaptype, flowtype >::test_consistency().
node_max
template<typename captype, typename tcaptype, typename flowtype> node * anima::Graph< captype, tcaptype, flowtype >::node_max
Definition at line 334 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_node(), anima::Graph< captype, tcaptype, flowtype >::Graph(), and anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes().
node_num
template<typename captype, typename tcaptype, typename flowtype> int anima::Graph< captype, tcaptype, flowtype >::node_num
Definition at line 337 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_edge(), anima::Graph< captype, tcaptype, flowtype >::add_node(), anima::Graph< captype, tcaptype, flowtype >::add_tweights(), anima::Graph< captype, tcaptype, flowtype >::get_node_num(), anima::Graph< captype, tcaptype, flowtype >::get_trcap(), anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes(), anima::Graph< captype, tcaptype, flowtype >::remove_from_changed_list(), anima::Graph< captype, tcaptype, flowtype >::reset(), and anima::Graph< captype, tcaptype, flowtype >::set_trcap().
nodeptr_block
template<typename captype, typename tcaptype, typename flowtype> DBlock<nodeptr>* anima::Graph< captype, tcaptype, flowtype >::nodeptr_block
Definition at line 339 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::reset(), anima::Graph< captype, tcaptype, flowtype >::set_orphan_front(), anima::Graph< captype, tcaptype, flowtype >::set_orphan_rear(), and anima::Graph< captype, tcaptype, flowtype >::~Graph().
NODEPTR_BLOCK_SIZE
template<typename captype, typename tcaptype, typename flowtype> const int anima::Graph< captype, tcaptype, flowtype >::NODEPTR_BLOCK_SIZE = 128 static
Definition at line 332 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow().
nodes
template<typename captype, typename tcaptype, typename flowtype> node* anima::Graph< captype, tcaptype, flowtype >::nodes
Definition at line 334 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::add_edge(), anima::Graph< captype, tcaptype, flowtype >::add_to_changed_list(), anima::Graph< captype, tcaptype, flowtype >::add_tweights(), anima::Graph< captype, tcaptype, flowtype >::get_arc_ends(), anima::Graph< captype, tcaptype, flowtype >::get_trcap(), anima::Graph< captype, tcaptype, flowtype >::Graph(), anima::Graph< captype, tcaptype, flowtype >::mark_node(), anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::reallocate_arcs(), anima::Graph< captype, tcaptype, flowtype >::reallocate_nodes(), anima::Graph< captype, tcaptype, flowtype >::remove_from_changed_list(), anima::Graph< captype, tcaptype, flowtype >::reset(), anima::Graph< captype, tcaptype, flowtype >::set_trcap(), anima::Graph< captype, tcaptype, flowtype >::test_consistency(), anima::Graph< captype, tcaptype, flowtype >::what_segment(), and anima::Graph< captype, tcaptype, flowtype >::~Graph().
orphan_first
template<typename captype, typename tcaptype, typename flowtype> nodeptr* anima::Graph< captype, tcaptype, flowtype >::orphan_first
Definition at line 354 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::set_orphan_front(), and anima::Graph< captype, tcaptype, flowtype >::set_orphan_rear().
orphan_last
template<typename captype, typename tcaptype, typename flowtype> nodeptr * anima::Graph< captype, tcaptype, flowtype >::orphan_last
Definition at line 354 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), and anima::Graph< captype, tcaptype, flowtype >::set_orphan_rear().
queue_first
template<typename captype, typename tcaptype, typename flowtype> node* anima::Graph< captype, tcaptype, flowtype >::queue_first[2]
Definition at line 353 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::mark_node(), anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::next_active(), anima::Graph< captype, tcaptype, flowtype >::set_active(), and anima::Graph< captype, tcaptype, flowtype >::test_consistency().
queue_last
template<typename captype, typename tcaptype, typename flowtype> node * anima::Graph< captype, tcaptype, flowtype >::queue_last[2]
Definition at line 353 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::mark_node(), anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::next_active(), anima::Graph< captype, tcaptype, flowtype >::set_active(), and anima::Graph< captype, tcaptype, flowtype >::test_consistency().
TIME
template<typename captype, typename tcaptype, typename flowtype> int anima::Graph< captype, tcaptype, flowtype >::TIME
Definition at line 355 of file animaGraph.h.
Referenced by anima::Graph< captype, tcaptype, flowtype >::maxflow(), anima::Graph< captype, tcaptype, flowtype >::maxflow_init(), anima::Graph< captype, tcaptype, flowtype >::maxflow_reuse_trees_init(), anima::Graph< captype, tcaptype, flowtype >::process_sink_orphan(), and anima::Graph< captype, tcaptype, flowtype >::process_source_orphan().
The documentation for this class was generated from the following file:
animaGraph.h