ANIMA: anima::LowMemoryPatientToGroupComparisonBridge Class Reference
anima::LowMemoryPatientToGroupComparisonBridge Class Reference
#include <animaLowMemPatientToGroupComparisonBridge.h>
Public Types
typedef anima::ImageDataSplitter< InputImageType > ImageSplitterLTType
typedef PatientToGroupComparisonImageFilter< double >::InputImageType InputImageType
typedef anima::PatientToGroupComparisonImageFilter< double > MainFilterType
typedef itk::Image< unsigned char, 3 > MaskImageType
typedef PatientToGroupComparisonImageFilter< double >::OutputImageType OutputImageType
typedef MainFilterType::TestType TestType
Public Member Functions
void BuildAndWrite (OutputImageType *tmpIm, std::string resName, OutputImageType::RegionType finalROI)
std::string GetNameOfClass ()
LowMemoryPatientToGroupComparisonBridge ()
void SetComputationMask (std::string &cMask)
void SetDataLTFileNames (std::string &fileList)
void SetExplainedRatio (double eRatio)
void SetNbSplits (unsigned int nbSplits)
void SetNumberOfThreads (unsigned int &nbT)
void SetNumEigenValuesPCA (unsigned int numEigen)
void SetOutputName (std::string &pref)
void SetOutputPValName (std::string &pref)
void SetStatisticalTestType (TestType type)
void SetTestLTFileName (std::string &fileName)
void Update (int specificSplitToDo=-1, bool genOutputDescriptionData=false)
~LowMemoryPatientToGroupComparisonBridge ()
Detailed Description
Definition at line 9 of file animaLowMemPatientToGroupComparisonBridge.h.
Member Typedef Documentation
ImageSplitterLTType
typedef anima::ImageDataSplitter< InputImageType > anima::LowMemoryPatientToGroupComparisonBridge::ImageSplitterLTType
Definition at line 15 of file animaLowMemPatientToGroupComparisonBridge.h.
InputImageType
typedef PatientToGroupComparisonImageFilter<double>::InputImageType anima::LowMemoryPatientToGroupComparisonBridge::InputImageType
Definition at line 12 of file animaLowMemPatientToGroupComparisonBridge.h.
MainFilterType
typedef anima::PatientToGroupComparisonImageFilter<double> anima::LowMemoryPatientToGroupComparisonBridge::MainFilterType
Definition at line 16 of file animaLowMemPatientToGroupComparisonBridge.h.
MaskImageType
typedef itk::Image<unsigned char,3> anima::LowMemoryPatientToGroupComparisonBridge::MaskImageType
Definition at line 18 of file animaLowMemPatientToGroupComparisonBridge.h.
OutputImageType
typedef PatientToGroupComparisonImageFilter<double>::OutputImageType anima::LowMemoryPatientToGroupComparisonBridge::OutputImageType
Definition at line 13 of file animaLowMemPatientToGroupComparisonBridge.h.
TestType
typedef MainFilterType::TestType anima::LowMemoryPatientToGroupComparisonBridge::TestType
Definition at line 17 of file animaLowMemPatientToGroupComparisonBridge.h.
Constructor & Destructor Documentation
LowMemoryPatientToGroupComparisonBridge()
anima::LowMemoryPatientToGroupComparisonBridge::LowMemoryPatientToGroupComparisonBridge ()
Definition at line 7 of file animaLowMemPatientToGroupComparisonBridge.cxx.
References anima::PatientToGroupComparisonImageFilter< PixelScalarType >::FISHER.
~LowMemoryPatientToGroupComparisonBridge()
anima::LowMemoryPatientToGroupComparisonBridge::~LowMemoryPatientToGroupComparisonBridge ()
Definition at line 22 of file animaLowMemPatientToGroupComparisonBridge.cxx.
Member Function Documentation
BuildAndWrite()
void anima::LowMemoryPatientToGroupComparisonBridge::BuildAndWrite (OutputImageType * tmpIm, std::string resName, OutputImageType::RegionType finalROI)
Definition at line 167 of file animaLowMemPatientToGroupComparisonBridge.cxx.
Referenced by SetNumEigenValuesPCA(), and Update().
GetNameOfClass()
std::string anima::LowMemoryPatientToGroupComparisonBridge::GetNameOfClass () inline
Definition at line 23 of file animaLowMemPatientToGroupComparisonBridge.h.
References SetComputationMask().
SetComputationMask()
void anima::LowMemoryPatientToGroupComparisonBridge::SetComputationMask (std::string & cMask)
Definition at line 31 of file animaLowMemPatientToGroupComparisonBridge.cxx.
References anima::ImageDataSplitter< TInputImage >::SetComputationMask().
Referenced by GetNameOfClass(), and main().
SetDataLTFileNames()
void anima::LowMemoryPatientToGroupComparisonBridge::SetDataLTFileNames (std::string & fileList) inline
Definition at line 27 of file animaLowMemPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetFileNames().
SetExplainedRatio()
void anima::LowMemoryPatientToGroupComparisonBridge::SetExplainedRatio (double eRatio) inline
Definition at line 44 of file animaLowMemPatientToGroupComparisonBridge.h.
SetNbSplits()
void anima::LowMemoryPatientToGroupComparisonBridge::SetNbSplits (unsigned int nbSplits) inline
Definition at line 40 of file animaLowMemPatientToGroupComparisonBridge.h.
SetNumberOfThreads()
void anima::LowMemoryPatientToGroupComparisonBridge::SetNumberOfThreads (unsigned int & nbT) inline
Definition at line 41 of file animaLowMemPatientToGroupComparisonBridge.h.
SetNumEigenValuesPCA()
void anima::LowMemoryPatientToGroupComparisonBridge::SetNumEigenValuesPCA (unsigned int numEigen) inline
Definition at line 45 of file animaLowMemPatientToGroupComparisonBridge.h.
References BuildAndWrite(), and Update().
SetOutputName()
void anima::LowMemoryPatientToGroupComparisonBridge::SetOutputName (std::string & pref) inline
Definition at line 37 of file animaLowMemPatientToGroupComparisonBridge.h.
SetOutputPValName()
void anima::LowMemoryPatientToGroupComparisonBridge::SetOutputPValName (std::string & pref) inline
Definition at line 38 of file animaLowMemPatientToGroupComparisonBridge.h.
SetStatisticalTestType()
void anima::LowMemoryPatientToGroupComparisonBridge::SetStatisticalTestType (TestType type) inline
Definition at line 43 of file animaLowMemPatientToGroupComparisonBridge.h.
SetTestLTFileName()
void anima::LowMemoryPatientToGroupComparisonBridge::SetTestLTFileName (std::string & fileName) inline
Definition at line 32 of file animaLowMemPatientToGroupComparisonBridge.h.
References anima::ImageDataSplitter< TInputImage >::SetUniqueFileName().
Update()
void anima::LowMemoryPatientToGroupComparisonBridge::Update (int specificSplitToDo = -1, bool genOutputDescriptionData = false)
Definition at line 39 of file animaLowMemPatientToGroupComparisonBridge.cxx.
References BuildAndWrite(), anima::ImageDataSplitter< TInputImage >::EmptyMask(), anima::ImageDataSplitter< TInputImage >::GetBlockRegionInsideMargin(), anima::ImageDataSplitter< TInputImage >::GetNbImages(), anima::ImageDataSplitter< TInputImage >::GetOutput(), anima::ImageDataSplitter< TInputImage >::GetSmallMaskWithMargin(), anima::ImageDataSplitter< TInputImage >::GetSpecificBlockRegion(), anima::PatientToGroupComparisonImageFilter< PixelScalarType >::New(), anima::ImageDataSplitter< TInputImage >::SetBlockIndex(), anima::ImageDataSplitter< TInputImage >::SetNumberOfBlocks(), and anima::ImageDataSplitter< TInputImage >::Update().
Referenced by SetNumEigenValuesPCA().
The documentation for this class was generated from the following files:
animaLowMemPatientToGroupComparisonBridge.h
animaLowMemPatientToGroupComparisonBridge.cxx