ANIMA: anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage > Class Template Reference
anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage > Class Template Reference
#include <animaStimulatedSpinEchoImageFilter.h>
Public Types
typedef std::vector< std::complex< double > > ComplexVectorType
typedef Image4DType::Pointer Image4DPointer
typedef itk::Image< typename TImage::PixelType, 4 > Image4DType
typedef std::vector< ComplexVectorType > MatrixType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef StimulatedSpinEchoImageFilter Self
typedef itk::ImageToImageFilter< TImage, TOutputImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual double GetEchoSpacing ()
virtual double GetExcitationFlipAngle ()
virtual double GetFlipAngle ()
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfEchoes ()
Image4DType * GetOutputAs4DImage ()
virtual void SetB1OnExcitationAngle (bool _arg)
virtual void SetEchoSpacing (double _arg)
virtual void SetExcitationFlipAngle (double _arg)
virtual void SetFlipAngle (double _arg)
void SetInputB1 (const TImage *B1)
void SetInputM0 (const TImage *M0)
void SetInputT1 (const TImage *T1)
void SetInputT2 (const TImage *T2)
virtual void SetNumberOfEchoes (unsigned int _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void GenerateOutputInformation () ITK_OVERRIDE
StimulatedSpinEchoImageFilter ()
virtual void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~StimulatedSpinEchoImageFilter ()
Detailed Description
template<class TImage, class TOutputImage>
class anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >
Definition at line 11 of file animaStimulatedSpinEchoImageFilter.h.
Member Typedef Documentation
ComplexVectorType
template<class TImage, class TOutputImage> typedef std::vector< std::complex <double> > anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ComplexVectorType
Definition at line 23 of file animaStimulatedSpinEchoImageFilter.h.
Image4DPointer
template<class TImage, class TOutputImage> typedef Image4DType::Pointer anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::Image4DPointer
Definition at line 20 of file animaStimulatedSpinEchoImageFilter.h.
Image4DType
template<class TImage, class TOutputImage> typedef itk::Image<typename TImage::PixelType, 4> anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::Image4DType
Definition at line 19 of file animaStimulatedSpinEchoImageFilter.h.
MatrixType
template<class TImage, class TOutputImage> typedef std::vector<ComplexVectorType> anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::MatrixType
Definition at line 24 of file animaStimulatedSpinEchoImageFilter.h.
OutputImageRegionType
template<class TImage, class TOutputImage> typedef Superclass::OutputImageRegionType anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::OutputImageRegionType
Definition at line 22 of file animaStimulatedSpinEchoImageFilter.h.
OutputImageType
template<class TImage, class TOutputImage> typedef TOutputImage anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::OutputImageType
Definition at line 21 of file animaStimulatedSpinEchoImageFilter.h.
Pointer
template<class TImage, class TOutputImage> typedef itk::SmartPointer<Self> anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::Pointer
Definition at line 17 of file animaStimulatedSpinEchoImageFilter.h.
Self
template<class TImage, class TOutputImage> typedef StimulatedSpinEchoImageFilter anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 15 of file animaStimulatedSpinEchoImageFilter.h.
Superclass
template<class TImage, class TOutputImage> typedef itk::ImageToImageFilter<TImage, TOutputImage> anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::Superclass
Definition at line 16 of file animaStimulatedSpinEchoImageFilter.h.
Constructor & Destructor Documentation
StimulatedSpinEchoImageFilter()
template<class TImage , class TOutputImage > anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::StimulatedSpinEchoImageFilter () protected
Definition at line 24 of file animaStimulatedSpinEchoImageFilter.hxx.
~StimulatedSpinEchoImageFilter()
template<class TImage, class TOutputImage> virtual anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::~StimulatedSpinEchoImageFilter () inline protected virtual
Definition at line 62 of file animaStimulatedSpinEchoImageFilter.h.
References anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GenerateOutputInformation(), and anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<class TImage, class TOutputImage> virtual::itk::LightObject::Pointer anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::CreateAnother (void) const
GenerateOutputInformation()
template<class TImage , class TOutputImage > void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GenerateOutputInformation () protected
Definition at line 14 of file animaStimulatedSpinEchoImageFilter.hxx.
Referenced by anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::~StimulatedSpinEchoImageFilter().
GetEchoSpacing()
template<class TImage, class TOutputImage> virtual double anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GetEchoSpacing () virtual
GetExcitationFlipAngle()
template<class TImage, class TOutputImage> virtual double anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GetExcitationFlipAngle () virtual
GetFlipAngle()
template<class TImage, class TOutputImage> virtual double anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GetFlipAngle () virtual
GetNameOfClass()
template<class TImage, class TOutputImage> virtual const char* anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfEchoes()
template<class TImage, class TOutputImage> virtual unsigned int anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GetNumberOfEchoes () virtual
GetOutputAs4DImage()
template<class TImage , class TOutputImage > StimulatedSpinEchoImageFilter< TImage, TOutputImage >::Image4DType * anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::GetOutputAs4DImage ()
Definition at line 67 of file animaStimulatedSpinEchoImageFilter.hxx.
New()
template<class TImage, class TOutputImage> static Pointer anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::New () static
Method for creation through the object factory.
SetB1OnExcitationAngle()
template<class TImage, class TOutputImage> virtual void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetB1OnExcitationAngle (bool _arg) virtual
SetEchoSpacing()
template<class TImage, class TOutputImage> virtual void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetEchoSpacing (double _arg) virtual
SetExcitationFlipAngle()
template<class TImage, class TOutputImage> virtual void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetExcitationFlipAngle (double _arg) virtual
SetFlipAngle()
template<class TImage, class TOutputImage> virtual void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetFlipAngle (double _arg) virtual
SetInputB1()
template<class TImage , class TOutputImage > void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetInputB1 (const TImage * B1)
B1 inhomogeneity image
Definition at line 59 of file animaStimulatedSpinEchoImageFilter.hxx.
SetInputM0()
template<class TImage , class TOutputImage > void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetInputM0 (const TImage * M0)
M0 image / Rho map
Definition at line 52 of file animaStimulatedSpinEchoImageFilter.hxx.
SetInputT1()
template<class TImage , class TOutputImage > void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetInputT1 (const TImage * T1)
T1 map
Definition at line 38 of file animaStimulatedSpinEchoImageFilter.hxx.
SetInputT2()
template<class TImage , class TOutputImage > void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetInputT2 (const TImage * T2)
T2 map
Definition at line 45 of file animaStimulatedSpinEchoImageFilter.hxx.
SetNumberOfEchoes()
template<class TImage, class TOutputImage> virtual void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::SetNumberOfEchoes (unsigned int _arg) virtual
ThreadedGenerateData()
template<class TImage , class TOutputImage > void anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected virtual
Does the real work.
Definition at line 133 of file animaStimulatedSpinEchoImageFilter.hxx.
References anima::EPGSignalSimulator::GetValue(), anima::EPGSignalSimulator::SetB1OnExcitationAngle(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::EPGSignalSimulator::SetFlipAngle(), and anima::EPGSignalSimulator::SetNumberOfEchoes().
Referenced by anima::StimulatedSpinEchoImageFilter< TImage, TOutputImage >::~StimulatedSpinEchoImageFilter().
The documentation for this class was generated from the following files:
animaStimulatedSpinEchoImageFilter.h
animaStimulatedSpinEchoImageFilter.hxx