ANIMA: anima::StaniszCompartment Class Reference
anima::StaniszCompartment Class Reference
#include <animaStaniszCompartment.h>
Public Types
typedef Superclass::Pointer BasePointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::Matrix3DType Matrix3DType
typedef Superclass::ModelOutputVectorType ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef StaniszCompartment Self
typedef BaseCompartment Superclass
typedef Superclass::Vector3DType Vector3DType
Public Types inherited from anima::BaseCompartment
typedef itk::SmartPointer< const Self > ConstPointer
typedef std::vector< double > ListType
typedef itk::Matrix< double, 3, 3 > Matrix3DType
typedef itk::VariableLengthVector< double > ModelOutputVectorType
typedef itk::SmartPointer< Self > Pointer
typedef BaseCompartment Self
typedef itk::LightObject Superclass
typedef vnl_vector_fixed< double, 3 > Vector3DType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetCompartmentSize () ITK_OVERRIDE
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
DiffusionModelCompartmentType GetCompartmentType () ITK_OVERRIDE
Utility function to return compartment type without needing dynamic casts.
ModelOutputVectorType & GetCompartmentVector () ITK_OVERRIDE
Get compartment overall description vector, mainly for writing, should be self-contained.
virtual double GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
double GetFractionalAnisotropy () ITK_OVERRIDE
virtual double GetLogDiffusionProfile (const Vector3DType &sample) ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () ITK_OVERRIDE
Number of optimized parameters: smaller than total number of parameters.
virtual ListType & GetParameterLowerBounds () ITK_OVERRIDE
virtual ListType & GetParametersAsVector () ITK_OVERRIDE
virtual ListType & GetParameterUpperBounds () ITK_OVERRIDE
virtual ListType & GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient) ITK_OVERRIDE
bool GetTensorCompatible () ITK_OVERRIDE
void SetAxialDiffusivity (double num) ITK_OVERRIDE
void SetCompartmentVector (ModelOutputVectorType &compartmentVector) ITK_OVERRIDE
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
void SetEstimateAxialDiffusivity (bool arg)
void SetEstimateTissueRadius (bool arg)
virtual void SetParametersFromVector (const ListType &params) ITK_OVERRIDE
Various methods for optimization parameters setting and getting.
void SetTissueRadius (double num) ITK_OVERRIDE
Public Member Functions inherited from anima::BaseCompartment
virtual void CopyFromOther (Self *rhs)
Copy internal parameters from another compartment, faster than a set/get compartment vector.
virtual double GetAxialDiffusivity ()
virtual const Matrix3DType & GetDiffusionTensor ()
Get compartment as a 3D tensor (default behavior: throw exception if not supported by the compartment model)
virtual double GetExtraAxonalFraction ()
virtual double GetOrientationConcentration ()
virtual double GetOrientationPhi ()
virtual double GetOrientationTheta ()
virtual double GetPerpendicularAngle ()
double GetPredictedSignal (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType &gradient)
virtual double GetRadialDiffusivity1 ()
virtual double GetRadialDiffusivity2 ()
virtual double GetTissueRadius ()
virtual bool IsEqual (Self *rhs, double tolerance=1.0e-2, double absoluteTolerance=1.0e-8)
Tests equality to another compartment up to a constant (relative and absolute tolerances)
virtual void Reorient (vnl_matrix< double > &orientationMatrix, bool affineTransform)
Reorient the fascicle compartment using a matrix, the flag specifies if the transform is affine or rigid.
virtual void SetExtraAxonalFraction (double num)
virtual void SetOrientationConcentration (double num)
virtual void SetOrientationPhi (double num)
virtual void SetOrientationTheta (double num)
virtual void SetPerpendicularAngle (double num)
virtual void SetRadialDiffusivity1 (double num)
virtual void SetRadialDiffusivity2 (double num)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
StaniszCompartment ()
void UpdateSignals (double smallDelta, double bigDelta, double gradientStrength)
virtual ~StaniszCompartment ()
Protected Member Functions inherited from anima::BaseCompartment
BaseCompartment ()
virtual ~BaseCompartment ()
Additional Inherited Members
Protected Attributes inherited from anima::BaseCompartment
ModelOutputVectorType m_CompartmentVector
Vector to hold working value of compartment vector.
Matrix3DType m_DiffusionTensor
Matrix to hold working value of diffusion tensor approximation to the model.
ListType m_JacobianVector
Vector holding current jacobian value.
ListType m_ParametersLowerBoundsVector
Vector holding current parameters lower bounds.
ListType m_ParametersUpperBoundsVector
Vector holding current parameters upper bounds.
ListType m_ParametersVector
Vector holding current parameters vector.
Static Protected Attributes inherited from anima::BaseCompartment
static const unsigned int m_SpaceDimension = 3
Detailed Description
Definition at line 9 of file animaStaniszCompartment.h.
Member Typedef Documentation
BasePointer
typedef Superclass::Pointer anima::StaniszCompartment::BasePointer
Definition at line 15 of file animaStaniszCompartment.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::StaniszCompartment::ConstPointer
Definition at line 17 of file animaStaniszCompartment.h.
Matrix3DType
typedef Superclass::Matrix3DType anima::StaniszCompartment::Matrix3DType
Definition at line 20 of file animaStaniszCompartment.h.
ModelOutputVectorType
typedef Superclass::ModelOutputVectorType anima::StaniszCompartment::ModelOutputVectorType
Definition at line 18 of file animaStaniszCompartment.h.
Pointer
typedef itk::SmartPointer<Self> anima::StaniszCompartment::Pointer
Definition at line 16 of file animaStaniszCompartment.h.
Self
typedef StaniszCompartment anima::StaniszCompartment::Self
Definition at line 13 of file animaStaniszCompartment.h.
Superclass
typedef BaseCompartment anima::StaniszCompartment::Superclass
Definition at line 14 of file animaStaniszCompartment.h.
Vector3DType
typedef Superclass::Vector3DType anima::StaniszCompartment::Vector3DType
Definition at line 19 of file animaStaniszCompartment.h.
Constructor & Destructor Documentation
StaniszCompartment()
anima::StaniszCompartment::StaniszCompartment () inline protected
Definition at line 56 of file animaStaniszCompartment.h.
~StaniszCompartment()
virtual anima::StaniszCompartment::~StaniszCompartment () inline protected virtual
Definition at line 74 of file animaStaniszCompartment.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::StaniszCompartment::CreateAnother (void) const
GetCompartmentSize()
unsigned int anima::StaniszCompartment::GetCompartmentSize () virtual
Number of parameters to describe the model, these parameters will be self-contained, i.e. include fixed parameters for example.
Implements anima::BaseCompartment.
Definition at line 260 of file animaStaniszCompartment.cxx.
Referenced by GetCompartmentVector(), and SetCompartmentVector().
GetCompartmentType()
DiffusionModelCompartmentType anima::StaniszCompartment::GetCompartmentType () inline virtual
Utility function to return compartment type without needing dynamic casts.
Implements anima::BaseCompartment.
Definition at line 28 of file animaStaniszCompartment.h.
References anima::Stanisz.
GetCompartmentVector()
StaniszCompartment::ModelOutputVectorType & anima::StaniszCompartment::GetCompartmentVector () virtual
Get compartment overall description vector, mainly for writing, should be self-contained.
Implements anima::BaseCompartment.
Definition at line 282 of file animaStaniszCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetCompartmentSize(), anima::BaseCompartment::GetTissueRadius(), and anima::BaseCompartment::m_CompartmentVector.
GetFourierTransformedDiffusionProfile()
double anima::StaniszCompartment::GetFourierTransformedDiffusionProfile (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 66 of file animaStaniszCompartment.cxx.
References anima::DiffusionGyromagneticRatio, anima::BaseCompartment::GetTissueRadius(), and UpdateSignals().
GetFractionalAnisotropy()
double anima::StaniszCompartment::GetFractionalAnisotropy () virtual
Reimplemented from anima::BaseCompartment.
Definition at line 293 of file animaStaniszCompartment.cxx.
GetLogDiffusionProfile()
double anima::StaniszCompartment::GetLogDiffusionProfile (const Vector3DType & sample) virtual
Implements anima::BaseCompartment.
Definition at line 125 of file animaStaniszCompartment.cxx.
References anima::DiffusionBigDelta, anima::DiffusionGyromagneticRatio, anima::DiffusionSmallDelta, anima::GetGradientStrengthFromBValue(), anima::BaseCompartment::GetTissueRadius(), and UpdateSignals().
GetNameOfClass()
virtual const char* anima::StaniszCompartment::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BaseCompartment.
GetNumberOfParameters()
unsigned int anima::StaniszCompartment::GetNumberOfParameters () virtual
Number of optimized parameters: smaller than total number of parameters.
Implements anima::BaseCompartment.
Definition at line 265 of file animaStaniszCompartment.cxx.
Referenced by GetParameterLowerBounds(), GetParametersAsVector(), GetParameterUpperBounds(), GetSignalAttenuationJacobian(), and SetParametersFromVector().
GetParameterLowerBounds()
StaniszCompartment::ListType & anima::StaniszCompartment::GetParameterLowerBounds () virtual
Implements anima::BaseCompartment.
Definition at line 197 of file animaStaniszCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_ParametersLowerBoundsVector, anima::MCMDiffusivityLowerBound, and anima::MCMTissueRadiusLowerBound.
GetParametersAsVector()
StaniszCompartment::ListType & anima::StaniszCompartment::GetParametersAsVector () virtual
Implements anima::BaseCompartment.
Definition at line 180 of file animaStaniszCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), GetNumberOfParameters(), anima::BaseCompartment::GetTissueRadius(), and anima::BaseCompartment::m_ParametersVector.
GetParameterUpperBounds()
StaniszCompartment::ListType & anima::StaniszCompartment::GetParameterUpperBounds () virtual
Implements anima::BaseCompartment.
Definition at line 214 of file animaStaniszCompartment.cxx.
References GetNumberOfParameters(), anima::BaseCompartment::m_ParametersUpperBoundsVector, anima::MCMDiffusivityUpperBound, and anima::MCMTissueRadiusUpperBound.
GetSignalAttenuationJacobian()
StaniszCompartment::ListType & anima::StaniszCompartment::GetSignalAttenuationJacobian (double smallDelta, double bigDelta, double gradientStrength, const Vector3DType & gradient) virtual
Implements anima::BaseCompartment.
Definition at line 84 of file animaStaniszCompartment.cxx.
References anima::DiffusionGyromagneticRatio, anima::BaseCompartment::GetAxialDiffusivity(), anima::GetBValueFromAcquisitionParameters(), GetNumberOfParameters(), anima::BaseCompartment::GetTissueRadius(), anima::BaseCompartment::m_JacobianVector, and UpdateSignals().
GetTensorCompatible()
bool anima::StaniszCompartment::GetTensorCompatible () inline virtual
Reimplemented from anima::BaseCompartment.
Definition at line 52 of file animaStaniszCompartment.h.
New()
static Pointer anima::StaniszCompartment::New () static
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType().
SetAxialDiffusivity()
void anima::StaniszCompartment::SetAxialDiffusivity (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 160 of file animaStaniszCompartment.cxx.
References anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::SetAxialDiffusivity().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
SetCompartmentVector()
void anima::StaniszCompartment::SetCompartmentVector (ModelOutputVectorType & compartmentVector) virtual
Set compartment overall description vector, for setting automatically the individual parameters when reading from disk.
Implements anima::BaseCompartment.
Definition at line 249 of file animaStaniszCompartment.cxx.
References GetCompartmentSize(), SetAxialDiffusivity(), and SetTissueRadius().
SetEstimateAxialDiffusivity()
void anima::StaniszCompartment::SetEstimateAxialDiffusivity (bool arg)
Definition at line 231 of file animaStaniszCompartment.cxx.
SetEstimateTissueRadius()
void anima::StaniszCompartment::SetEstimateTissueRadius (bool arg)
Definition at line 240 of file animaStaniszCompartment.cxx.
SetParametersFromVector()
void anima::StaniszCompartment::SetParametersFromVector (const ListType & params) virtual
Various methods for optimization parameters setting and getting.
Implements anima::BaseCompartment.
Definition at line 169 of file animaStaniszCompartment.cxx.
References GetNumberOfParameters(), SetAxialDiffusivity(), and SetTissueRadius().
SetTissueRadius()
void anima::StaniszCompartment::SetTissueRadius (double num) virtual
Reimplemented from anima::BaseCompartment.
Definition at line 151 of file animaStaniszCompartment.cxx.
References anima::BaseCompartment::GetTissueRadius(), and anima::BaseCompartment::SetTissueRadius().
Referenced by SetCompartmentVector(), and SetParametersFromVector().
UpdateSignals()
void anima::StaniszCompartment::UpdateSignals (double smallDelta, double bigDelta, double gradientStrength) protected
Definition at line 9 of file animaStaniszCompartment.cxx.
References anima::DiffusionGyromagneticRatio, anima::BaseCompartment::GetAxialDiffusivity(), and anima::BaseCompartment::GetTissueRadius().
Referenced by GetFourierTransformedDiffusionProfile(), GetLogDiffusionProfile(), and GetSignalAttenuationJacobian().
The documentation for this class was generated from the following files:
animaStaniszCompartment.h
animaStaniszCompartment.cxx