ANIMA: anima::TransformSeriesReader< TScalarType, NDimensions > Class Template Reference
anima::TransformSeriesReader< TScalarType, NDimensions > Class Template Reference
#include <animaTransformSeriesReader.h>
Classes
struct TransformInformation
Public Types
typedef OutputTransformType::Pointer OutputTransformPointer
typedef itk::CompositeTransform< TScalarType, NDimensions > OutputTransformType
enum TransformationType {
LINEAR,
SVF_FIELD,
DENSE_FIELD
}
Public Member Functions
OutputTransformType * GetOutputTransform ()
void SetExponentiationOrder (unsigned int val)
void SetInput (std::string const &trListName)
void SetInvertTransform (bool val)
void SetNumberOfThreads (unsigned int num)
TransformSeriesReader ()
void Update ()
~TransformSeriesReader ()
Protected Member Functions
void addDenseTransformation (std::string &fileName, bool invert)
void addLinearTransformation (std::string &fileName, bool invert)
void addSVFTransformation (std::string &fileName, bool invert)
Detailed Description
template<class TScalarType = float, unsigned int NDimensions = 3>
class anima::TransformSeriesReader< TScalarType, NDimensions >
Definition at line 9 of file animaTransformSeriesReader.h.
Member Typedef Documentation
OutputTransformPointer
template<class TScalarType = float, unsigned int NDimensions = 3> typedef OutputTransformType::Pointer anima::TransformSeriesReader< TScalarType, NDimensions >::OutputTransformPointer
Definition at line 27 of file animaTransformSeriesReader.h.
OutputTransformType
template<class TScalarType = float, unsigned int NDimensions = 3> typedef itk::CompositeTransform<TScalarType,NDimensions> anima::TransformSeriesReader< TScalarType, NDimensions >::OutputTransformType
Definition at line 26 of file animaTransformSeriesReader.h.
Member Enumeration Documentation
TransformationType
template<class TScalarType = float, unsigned int NDimensions = 3> enum anima::TransformSeriesReader::TransformationType
Enumerator
LINEAR
SVF_FIELD
DENSE_FIELD
Definition at line 12 of file animaTransformSeriesReader.h.
Constructor & Destructor Documentation
TransformSeriesReader()
template<class TScalarType , unsigned int NDimensions> anima::TransformSeriesReader< TScalarType, NDimensions >::TransformSeriesReader ()
Definition at line 19 of file animaTransformSeriesReader.hxx.
References anima::TransformSeriesReader< TScalarType, NDimensions >::~TransformSeriesReader().
~TransformSeriesReader()
template<class TScalarType , unsigned int NDimensions> anima::TransformSeriesReader< TScalarType, NDimensions >::~TransformSeriesReader ()
Definition at line 30 of file animaTransformSeriesReader.hxx.
References anima::TransformSeriesReader< TScalarType, NDimensions >::Update().
Referenced by anima::TransformSeriesReader< TScalarType, NDimensions >::TransformSeriesReader().
Member Function Documentation
addDenseTransformation()
template<class TScalarType , unsigned int NDimensions> void anima::TransformSeriesReader< TScalarType, NDimensions >::addDenseTransformation (std::string & fileName, bool invert) protected
Definition at line 192 of file animaTransformSeriesReader.hxx.
References anima::TransformSeriesReader< TScalarType, NDimensions >::addSVFTransformation().
Referenced by anima::TransformSeriesReader< TScalarType, NDimensions >::addLinearTransformation(), and anima::TransformSeriesReader< TScalarType, NDimensions >::GetOutputTransform().
addLinearTransformation()
template<class TScalarType , unsigned int NDimensions> void anima::TransformSeriesReader< TScalarType, NDimensions >::addLinearTransformation (std::string & fileName, bool invert) protected
Definition at line 164 of file animaTransformSeriesReader.hxx.
References anima::TransformSeriesReader< TScalarType, NDimensions >::addDenseTransformation().
Referenced by anima::TransformSeriesReader< TScalarType, NDimensions >::GetOutputTransform(), and anima::TransformSeriesReader< TScalarType, NDimensions >::Update().
addSVFTransformation()
template<class TScalarType , unsigned int NDimensions> void anima::TransformSeriesReader< TScalarType, NDimensions >::addSVFTransformation (std::string & fileName, bool invert) protected
Definition at line 220 of file animaTransformSeriesReader.hxx.
References anima::GetSVFExponential().
Referenced by anima::TransformSeriesReader< TScalarType, NDimensions >::addDenseTransformation(), and anima::TransformSeriesReader< TScalarType, NDimensions >::GetOutputTransform().
GetOutputTransform()
template<class TScalarType = float, unsigned int NDimensions = 3> OutputTransformType* anima::TransformSeriesReader< TScalarType, NDimensions >::GetOutputTransform () inline
Definition at line 39 of file animaTransformSeriesReader.h.
References anima::TransformSeriesReader< TScalarType, NDimensions >::addDenseTransformation(), anima::TransformSeriesReader< TScalarType, NDimensions >::addLinearTransformation(), anima::TransformSeriesReader< TScalarType, NDimensions >::addSVFTransformation(), anima::TransformSeriesReader< TScalarType, NDimensions >::TransformInformation::fileName, and anima::TransformSeriesReader< TScalarType, NDimensions >::TransformInformation::invert.
SetExponentiationOrder()
template<class TScalarType = float, unsigned int NDimensions = 3> void anima::TransformSeriesReader< TScalarType, NDimensions >::SetExponentiationOrder (unsigned int val) inline
Definition at line 35 of file animaTransformSeriesReader.h.
References anima::TransformSeriesReader< TScalarType, NDimensions >::Update().
SetInput()
template<class TScalarType = float, unsigned int NDimensions = 3> void anima::TransformSeriesReader< TScalarType, NDimensions >::SetInput (std::string const & trListName) inline
Definition at line 32 of file animaTransformSeriesReader.h.
Referenced by applyScalarTransfo(), applyScalarTransfo4D(), applyTransformationToGradients(), applyVectorTransfo(), and main().
SetInvertTransform()
template<class TScalarType = float, unsigned int NDimensions = 3> void anima::TransformSeriesReader< TScalarType, NDimensions >::SetInvertTransform (bool val) inline
Definition at line 33 of file animaTransformSeriesReader.h.
SetNumberOfThreads()
template<class TScalarType = float, unsigned int NDimensions = 3> void anima::TransformSeriesReader< TScalarType, NDimensions >::SetNumberOfThreads (unsigned int num) inline
Definition at line 34 of file animaTransformSeriesReader.h.
Update()
template<class TScalarType , unsigned int NDimensions> void anima::TransformSeriesReader< TScalarType, NDimensions >::Update ()
Definition at line 38 of file animaTransformSeriesReader.hxx.
References anima::TransformSeriesReader< TScalarType, NDimensions >::addLinearTransformation(), anima::TransformSeriesReader< TScalarType, NDimensions >::TransformInformation::fileName, anima::TransformSeriesReader< TScalarType, NDimensions >::TransformInformation::invert, and anima::TransformSeriesReader< TScalarType, NDimensions >::TransformInformation::trType.
Referenced by anima::TransformSeriesReader< TScalarType, NDimensions >::SetExponentiationOrder(), and anima::TransformSeriesReader< TScalarType, NDimensions >::~TransformSeriesReader().
The documentation for this class was generated from the following files:
animaTransformSeriesReader.h
animaTransformSeriesReader.hxx