ANIMA: anima::MCML2DistanceComputer Class Reference
anima::MCML2DistanceComputer Class Reference
Computes a L2 distance between two MCM of any type.
#include <animaMCML2DistanceComputer.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef MCMType::Vector3DType GradientType
typedef MCMType::Pointer MCMPointer
typedef anima::MultiCompartmentModel MCMType
typedef itk::SmartPointer< Self > Pointer
typedef MCML2DistanceComputer Self
typedef itk::LightObject Superclass
Public Member Functions
double ComputeDistance (const MCMPointer &firstModel, const MCMPointer &secondModel) const
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
void SetBigDelta (double val)
void SetForceApproximation (bool val)
void SetGradientDirections (const std::vector< GradientType > &val)
void SetGradientStrengths (const std::vector< double > &val)
void SetLowPassGaussianSigma (double val)
void SetSmallDelta (double val)
void SetSquaredDistance (bool val)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
bool CheckTensorCompatibility (const MCMPointer &firstModel, const MCMPointer &secondModel) const
double ComputeApproximateDistance (const MCMPointer &firstModel, const MCMPointer &secondModel) const
double ComputeTensorDistance (const MCMPointer &firstModel, const MCMPointer &secondModel) const
MCML2DistanceComputer ()
void UpdateSphereWeights ()
~MCML2DistanceComputer ()
Detailed Description
Computes a L2 distance between two MCM of any type.
Definition at line 17 of file animaMCML2DistanceComputer.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::MCML2DistanceComputer::ConstPointer
Definition at line 23 of file animaMCML2DistanceComputer.h.
GradientType
typedef MCMType::Vector3DType anima::MCML2DistanceComputer::GradientType
Definition at line 31 of file animaMCML2DistanceComputer.h.
MCMPointer
typedef MCMType::Pointer anima::MCML2DistanceComputer::MCMPointer
Definition at line 32 of file animaMCML2DistanceComputer.h.
MCMType
typedef anima::MultiCompartmentModel anima::MCML2DistanceComputer::MCMType
Definition at line 30 of file animaMCML2DistanceComputer.h.
Pointer
typedef itk::SmartPointer<Self> anima::MCML2DistanceComputer::Pointer
Definition at line 22 of file animaMCML2DistanceComputer.h.
Self
typedef MCML2DistanceComputer anima::MCML2DistanceComputer::Self
Definition at line 20 of file animaMCML2DistanceComputer.h.
Superclass
typedef itk::LightObject anima::MCML2DistanceComputer::Superclass
Definition at line 21 of file animaMCML2DistanceComputer.h.
Constructor & Destructor Documentation
MCML2DistanceComputer()
anima::MCML2DistanceComputer::MCML2DistanceComputer () protected
Definition at line 9 of file animaMCML2DistanceComputer.cxx.
References anima::DiffusionBigDelta, and anima::DiffusionSmallDelta.
~MCML2DistanceComputer()
anima::MCML2DistanceComputer::~MCML2DistanceComputer () inline protected
Definition at line 48 of file animaMCML2DistanceComputer.h.
Member Function Documentation
CheckTensorCompatibility()
bool anima::MCML2DistanceComputer::CheckTensorCompatibility (const MCMPointer & firstModel, const MCMPointer & secondModel) const protected
Definition at line 134 of file animaMCML2DistanceComputer.cxx.
Referenced by ComputeDistance().
ComputeApproximateDistance()
double anima::MCML2DistanceComputer::ComputeApproximateDistance (const MCMPointer & firstModel, const MCMPointer & secondModel) const protected
Definition at line 295 of file animaMCML2DistanceComputer.cxx.
Referenced by ComputeDistance().
ComputeDistance()
double anima::MCML2DistanceComputer::ComputeDistance (const MCMPointer & firstModel, const MCMPointer & secondModel) const
Definition at line 124 of file animaMCML2DistanceComputer.cxx.
References CheckTensorCompatibility(), ComputeApproximateDistance(), and ComputeTensorDistance().
ComputeTensorDistance()
double anima::MCML2DistanceComputer::ComputeTensorDistance (const MCMPointer & firstModel, const MCMPointer & secondModel) const protected
Definition at line 154 of file animaMCML2DistanceComputer.cxx.
Referenced by ComputeDistance().
CreateAnother()
virtual::itk::LightObject::Pointer anima::MCML2DistanceComputer::CreateAnother (void) const
GetNameOfClass()
virtual const char* anima::MCML2DistanceComputer::GetNameOfClass () const virtual
Run-time type information (and related methods)
New()
static Pointer anima::MCML2DistanceComputer::New () static
Referenced by anima::MCMMeanSquaresImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MCMMeanSquaresImageToImageMetric().
SetBigDelta()
void anima::MCML2DistanceComputer::SetBigDelta (double val)
Definition at line 28 of file animaMCML2DistanceComputer.cxx.
References UpdateSphereWeights().
SetForceApproximation()
void anima::MCML2DistanceComputer::SetForceApproximation (bool val) inline
Definition at line 35 of file animaMCML2DistanceComputer.h.
SetGradientDirections()
void anima::MCML2DistanceComputer::SetGradientDirections (const std::vector< GradientType > & val)
Definition at line 45 of file animaMCML2DistanceComputer.cxx.
References UpdateSphereWeights().
SetGradientStrengths()
void anima::MCML2DistanceComputer::SetGradientStrengths (const std::vector< double > & val)
Definition at line 37 of file animaMCML2DistanceComputer.cxx.
References UpdateSphereWeights().
SetLowPassGaussianSigma()
void anima::MCML2DistanceComputer::SetLowPassGaussianSigma (double val) inline
Definition at line 34 of file animaMCML2DistanceComputer.h.
SetSmallDelta()
void anima::MCML2DistanceComputer::SetSmallDelta (double val)
Definition at line 19 of file animaMCML2DistanceComputer.cxx.
References UpdateSphereWeights().
SetSquaredDistance()
void anima::MCML2DistanceComputer::SetSquaredDistance (bool val) inline
Definition at line 36 of file animaMCML2DistanceComputer.h.
UpdateSphereWeights()
void anima::MCML2DistanceComputer::UpdateSphereWeights () protected
Definition at line 53 of file animaMCML2DistanceComputer.cxx.
References anima::GetBValueFromAcquisitionParameters().
Referenced by SetBigDelta(), SetGradientDirections(), SetGradientStrengths(), and SetSmallDelta().
The documentation for this class was generated from the following files:
animaMCML2DistanceComputer.h
animaMCML2DistanceComputer.cxx