ANIMA: anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType > Class Template Reference
anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType > Class Template Reference
#include <animaODFEstimatorImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Image< TInputPixelType, 4 > Image4DType
typedef TInputImage::Pointer InputImagePointer
typedef TOutputImage::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef ODFEstimatorImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::Image< TInputPixelType, 3 > TInputImage
typedef itk::VectorImage< TOutputPixelType, 3 > TOutputImage
Public Member Functions
void AddGradientDirection (unsigned int i, std::vector< double > &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetDeltaAganjRegularization (double _arg)
virtual void SetFileNameSphereTesselation (std::string _arg)
virtual void SetLambda (double _arg)
virtual void SetLOrder (unsigned int _arg)
virtual void SetNormalize (bool _arg)
virtual void SetSharpen (bool _arg)
virtual void SetSharpnessRatio (double _arg)
virtual void SetUseAganjEstimation (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
ODFEstimatorImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~ODFEstimatorImageFilter ()
Detailed Description
template<typename TInputPixelType, typename TOutputPixelType>
class anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >
Definition at line 13 of file animaODFEstimatorImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInputPixelType , typename TOutputPixelType > typedef itk::SmartPointer<const Self> anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::ConstPointer
Definition at line 24 of file animaODFEstimatorImageFilter.h.
Image4DType
template<typename TInputPixelType , typename TOutputPixelType > typedef itk::Image<TInputPixelType,4> anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::Image4DType
Definition at line 20 of file animaODFEstimatorImageFilter.h.
InputImagePointer
template<typename TInputPixelType , typename TOutputPixelType > typedef TInputImage::Pointer anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::InputImagePointer
Definition at line 30 of file animaODFEstimatorImageFilter.h.
OutputImagePointer
template<typename TInputPixelType , typename TOutputPixelType > typedef TOutputImage::Pointer anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::OutputImagePointer
Definition at line 33 of file animaODFEstimatorImageFilter.h.
OutputImageRegionType
template<typename TInputPixelType , typename TOutputPixelType > typedef Superclass::OutputImageRegionType anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::OutputImageRegionType
Superclass typedefs.
Definition at line 36 of file animaODFEstimatorImageFilter.h.
Pointer
template<typename TInputPixelType , typename TOutputPixelType > typedef itk::SmartPointer<Self> anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::Pointer
Definition at line 23 of file animaODFEstimatorImageFilter.h.
Self
template<typename TInputPixelType , typename TOutputPixelType > typedef ODFEstimatorImageFilter anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::Self
Standard class typedefs.
Definition at line 18 of file animaODFEstimatorImageFilter.h.
Superclass
template<typename TInputPixelType , typename TOutputPixelType > typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::Superclass
Definition at line 22 of file animaODFEstimatorImageFilter.h.
TInputImage
template<typename TInputPixelType , typename TOutputPixelType > typedef itk::Image<TInputPixelType, 3> anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::TInputImage
Definition at line 19 of file animaODFEstimatorImageFilter.h.
TOutputImage
template<typename TInputPixelType , typename TOutputPixelType > typedef itk::VectorImage<TOutputPixelType, 3> anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::TOutputImage
Definition at line 21 of file animaODFEstimatorImageFilter.h.
Constructor & Destructor Documentation
ODFEstimatorImageFilter()
template<typename TInputPixelType , typename TOutputPixelType > anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::ODFEstimatorImageFilter () inline protected
Definition at line 53 of file animaODFEstimatorImageFilter.h.
~ODFEstimatorImageFilter()
template<typename TInputPixelType , typename TOutputPixelType > virtual anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::~ODFEstimatorImageFilter () inline protected virtual
Definition at line 72 of file animaODFEstimatorImageFilter.h.
References anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::BeforeThreadedGenerateData(), anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::GenerateOutputInformation(), and anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::ThreadedGenerateData().
Member Function Documentation
AddGradientDirection()
template<typename TInputPixelType , typename TOutputPixelType > void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::AddGradientDirection (unsigned int i, std::vector< double > & grad)
Definition at line 19 of file animaODFEstimatorImageFilter.hxx.
References anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::GenerateOutputInformation(), and anima::TransformCartesianToSphericalCoordinates().
BeforeThreadedGenerateData()
template<typename TInputPixelType , typename TOutputPixelType > void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::BeforeThreadedGenerateData () protected
Definition at line 52 of file animaODFEstimatorImageFilter.hxx.
References anima::ODFSphericalHarmonicBasis::getNthSHValueAtPosition(), anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::ThreadedGenerateData(), and anima::TransformCartesianToSphericalCoordinates().
Referenced by anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::GenerateOutputInformation(), and anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::~ODFEstimatorImageFilter().
CreateAnother()
template<typename TInputPixelType , typename TOutputPixelType > virtual::itk::LightObject::Pointer anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::CreateAnother (void) const
GenerateOutputInformation()
template<typename TInputPixelType , typename TOutputPixelType > void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::GenerateOutputInformation () protected
Definition at line 37 of file animaODFEstimatorImageFilter.hxx.
References anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::BeforeThreadedGenerateData().
Referenced by anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::AddGradientDirection(), and anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::~ODFEstimatorImageFilter().
GetNameOfClass()
template<typename TInputPixelType , typename TOutputPixelType > virtual const char* anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
New()
template<typename TInputPixelType , typename TOutputPixelType > static Pointer anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::New () static
Method for creation through the object factory.
SetDeltaAganjRegularization()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetDeltaAganjRegularization (double _arg) virtual
SetFileNameSphereTesselation()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetFileNameSphereTesselation (std::string _arg) virtual
SetLambda()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetLambda (double _arg) virtual
SetLOrder()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetLOrder (unsigned int _arg) virtual
SetNormalize()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetNormalize (bool _arg) virtual
SetSharpen()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetSharpen (bool _arg) virtual
SetSharpnessRatio()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetSharpnessRatio (double _arg) virtual
SetUseAganjEstimation()
template<typename TInputPixelType , typename TOutputPixelType > virtual void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::SetUseAganjEstimation (bool _arg) virtual
ThreadedGenerateData()
template<typename TInputPixelType , typename TOutputPixelType > void anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 201 of file animaODFEstimatorImageFilter.hxx.
Referenced by anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::BeforeThreadedGenerateData(), and anima::ODFEstimatorImageFilter< TInputPixelType, TOutputPixelType >::~ODFEstimatorImageFilter().
The documentation for this class was generated from the following files:
animaODFEstimatorImageFilter.h
animaODFEstimatorImageFilter.hxx