ANIMA: anima::GradientFileReader< GradientType, BValueScalarType > Class Template Reference
anima::GradientFileReader< GradientType, BValueScalarType > Class Template Reference
#include <animaGradientFileReader.h>
Public Types
typedef std::vector< BValueScalarType > BValueVectorType
typedef std::vector< GradientType > GradientVectorType
Public Member Functions
std::vector< bool > GetB0Directions ()
BValueVectorType & GetBValues ()
GradientVectorType & GetGradients ()
BValueVectorType & GetGradientStrengths ()
unsigned int GetTotalNumberOfDirections ()
GradientFileReader ()
void SetB0ValueThreshold (double thr)
void SetBigDelta (double val)
void SetBValueBaseString (std::string base)
void SetGradientFileName (std::string fName)
void SetGradientIndependentNormalization (bool normGrads)
void SetModified ()
void SetSmallDelta (double val)
void Update ()
~GradientFileReader ()
Protected Member Functions
template<class T >
void InitializeEmptyGradient (std::vector< T > &vec)
template<class T >
void InitializeEmptyGradient (itk::Point< T, 3 > &vec)
template<class T >
void InitializeEmptyGradient (vnl_vector_fixed< T, 3 > &vec)
template<class T >
void InitializeEmptyGradient (itk::Vector< T, 3 > &vec)
Detailed Description
template<class GradientType = std::vector <double>, class BValueScalarType = double>
class anima::GradientFileReader< GradientType, BValueScalarType >
Definition at line 13 of file animaGradientFileReader.h.
Member Typedef Documentation
BValueVectorType
template<class GradientType = std::vector <double>, class BValueScalarType = double> typedef std::vector<BValueScalarType> anima::GradientFileReader< GradientType, BValueScalarType >::BValueVectorType
Definition at line 18 of file animaGradientFileReader.h.
GradientVectorType
template<class GradientType = std::vector <double>, class BValueScalarType = double> typedef std::vector<GradientType> anima::GradientFileReader< GradientType, BValueScalarType >::GradientVectorType
Definition at line 17 of file animaGradientFileReader.h.
Constructor & Destructor Documentation
GradientFileReader()
template<class GradientType , class BValueScalarType > anima::GradientFileReader< GradientType, BValueScalarType >::GradientFileReader ()
Definition at line 18 of file animaGradientFileReader.hxx.
References anima::DiffusionBigDelta, anima::DiffusionSmallDelta, and anima::GradientFileReader< GradientType, BValueScalarType >::GetB0Directions().
~GradientFileReader()
template<class GradientType = std::vector <double>, class BValueScalarType = double> anima::GradientFileReader< GradientType, BValueScalarType >::~GradientFileReader () inline
Definition at line 21 of file animaGradientFileReader.h.
Member Function Documentation
GetB0Directions()
template<class GradientType , class BValueScalarType > std::vector< bool > anima::GradientFileReader< GradientType, BValueScalarType >::GetB0Directions ()
Definition at line 36 of file animaGradientFileReader.hxx.
References anima::GradientFileReader< GradientType, BValueScalarType >::GetGradients().
Referenced by anima::GradientFileReader< GradientType, BValueScalarType >::GradientFileReader(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
GetBValues()
template<class GradientType , class BValueScalarType > GradientFileReader< GradientType, BValueScalarType >::BValueVectorType & anima::GradientFileReader< GradientType, BValueScalarType >::GetBValues ()
Definition at line 66 of file animaGradientFileReader.hxx.
References anima::GradientFileReader< GradientType, BValueScalarType >::GetGradientStrengths().
Referenced by anima::GradientFileReader< GradientType, BValueScalarType >::GetGradients(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
GetGradients()
template<class GradientType , class BValueScalarType > GradientFileReader< GradientType, BValueScalarType >::GradientVectorType & anima::GradientFileReader< GradientType, BValueScalarType >::GetGradients ()
Definition at line 55 of file animaGradientFileReader.hxx.
References anima::GradientFileReader< GradientType, BValueScalarType >::GetBValues().
Referenced by anima::GradientFileReader< GradientType, BValueScalarType >::GetB0Directions(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
GetGradientStrengths()
template<class GradientType , class BValueScalarType > GradientFileReader< GradientType, BValueScalarType >::BValueVectorType & anima::GradientFileReader< GradientType, BValueScalarType >::GetGradientStrengths ()
Definition at line 77 of file animaGradientFileReader.hxx.
References anima::GradientFileReader< GradientType, BValueScalarType >::GetTotalNumberOfDirections().
Referenced by anima::GradientFileReader< GradientType, BValueScalarType >::GetBValues(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
GetTotalNumberOfDirections()
template<class GradientType , class BValueScalarType > unsigned int anima::GradientFileReader< GradientType, BValueScalarType >::GetTotalNumberOfDirections ()
Definition at line 88 of file animaGradientFileReader.hxx.
References anima::GradientFileReader< GradientType, BValueScalarType >::Update().
Referenced by anima::GradientFileReader< GradientType, BValueScalarType >::GetGradientStrengths(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
InitializeEmptyGradient() [1/4]
template<class GradientType = std::vector <double>, class BValueScalarType = double> template<class T > void anima::GradientFileReader< GradientType, BValueScalarType >::InitializeEmptyGradient (std::vector< T > & vec) inline protected
Definition at line 40 of file animaGradientFileReader.h.
InitializeEmptyGradient() [2/4]
template<class GradientType = std::vector <double>, class BValueScalarType = double> template<class T > void anima::GradientFileReader< GradientType, BValueScalarType >::InitializeEmptyGradient (itk::Point< T, 3 > & vec) inline protected
Definition at line 46 of file animaGradientFileReader.h.
InitializeEmptyGradient() [3/4]
template<class GradientType = std::vector <double>, class BValueScalarType = double> template<class T > void anima::GradientFileReader< GradientType, BValueScalarType >::InitializeEmptyGradient (vnl_vector_fixed< T, 3 > & vec) inline protected
Definition at line 51 of file animaGradientFileReader.h.
InitializeEmptyGradient() [4/4]
template<class GradientType = std::vector <double>, class BValueScalarType = double> template<class T > void anima::GradientFileReader< GradientType, BValueScalarType >::InitializeEmptyGradient (itk::Vector< T, 3 > & vec) inline protected
Definition at line 56 of file animaGradientFileReader.h.
SetB0ValueThreshold()
template<class GradientType = std::vector <double>, class BValueScalarType = double> void anima::GradientFileReader< GradientType, BValueScalarType >::SetB0ValueThreshold (double thr) inline
Definition at line 27 of file animaGradientFileReader.h.
References anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
SetBigDelta()
template<class GradientType = std::vector <double>, class BValueScalarType = double> void anima::GradientFileReader< GradientType, BValueScalarType >::SetBigDelta (double val) inline
Definition at line 26 of file animaGradientFileReader.h.
References anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
SetBValueBaseString()
template<class GradientType = std::vector <double>, class BValueScalarType = double> void anima::GradientFileReader< GradientType, BValueScalarType >::SetBValueBaseString (std::string base) inline
Definition at line 24 of file animaGradientFileReader.h.
References anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
SetGradientFileName()
template<class GradientType = std::vector <double>, class BValueScalarType = double> void anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName (std::string fName) inline
Definition at line 23 of file animaGradientFileReader.h.
References anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
Referenced by applyTransformationToGradients(), convert(), and main().
SetGradientIndependentNormalization()
template<class GradientType = std::vector <double>, class BValueScalarType = double> void anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientIndependentNormalization (bool normGrads) inline
Definition at line 28 of file animaGradientFileReader.h.
References anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
SetModified()
template<class GradientType = std::vector <double>, class BValueScalarType = double> void anima::GradientFileReader< GradientType, BValueScalarType >::SetModified () inline
Definition at line 29 of file animaGradientFileReader.h.
References anima::GradientFileReader< GradientType, BValueScalarType >::GetB0Directions(), anima::GradientFileReader< GradientType, BValueScalarType >::GetBValues(), anima::GradientFileReader< GradientType, BValueScalarType >::GetGradients(), anima::GradientFileReader< GradientType, BValueScalarType >::GetGradientStrengths(), anima::GradientFileReader< GradientType, BValueScalarType >::GetTotalNumberOfDirections(), and anima::GradientFileReader< GradientType, BValueScalarType >::Update().
Referenced by anima::GradientFileReader< GradientType, BValueScalarType >::SetB0ValueThreshold(), anima::GradientFileReader< GradientType, BValueScalarType >::SetBigDelta(), anima::GradientFileReader< GradientType, BValueScalarType >::SetBValueBaseString(), anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientFileName(), anima::GradientFileReader< GradientType, BValueScalarType >::SetGradientIndependentNormalization(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetSmallDelta().
SetSmallDelta()
template<class GradientType = std::vector <double>, class BValueScalarType = double> void anima::GradientFileReader< GradientType, BValueScalarType >::SetSmallDelta (double val) inline
Definition at line 25 of file animaGradientFileReader.h.
References anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
Update()
template<class GradientType , class BValueScalarType > void anima::GradientFileReader< GradientType, BValueScalarType >::Update ()
Definition at line 99 of file animaGradientFileReader.hxx.
References anima::ComputeNorm(), anima::GetGradientStrengthFromBValue(), and anima::Normalize().
Referenced by anima::GradientFileReader< GradientType, BValueScalarType >::GetTotalNumberOfDirections(), and anima::GradientFileReader< GradientType, BValueScalarType >::SetModified().
The documentation for this class was generated from the following files:
animaGradientFileReader.h
animaGradientFileReader.hxx