ANIMA: anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference
anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference abstract
#include <animaOrientedModelBaseResampleImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef TOutputImage::DirectionType DirectionType
typedef GeometryImageType::Pointer GeometryImagePointer
typedef itk::Image< unsigned char, itkGetStaticConstMacro(ImageDimension)> GeometryImageType
typedef InputImageType::Pointer InputImagePointer
typedef TImageType InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::PixelType InputPixelType
typedef InputImageType::PointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< InputImageType, TInterpolatorPrecisionType > InterpolatorType
typedef TOutputImage::PointType OriginPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef TOutputImage::RegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef InterpolatorType::PointType PointType
typedef TOutputImage::RegionType RegionType
typedef OrientedModelBaseResampleImageFilter Self
typedef TOutputImage::SpacingType SpacingType
typedef anima::MaskedImageToImageFilter< TImageType, TImageType > Superclass
typedef TImageType TOutputImage
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> TransformType
Public Types inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, TImageType ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef itk::ImageToImageFilter< TImageType, TImageType > Superclass
typedef itk::ImageSource< TImageType >::ThreadStruct ThreadStruct
Public Member Functions
virtual bool GetFiniteStrainReorientation ()
virtual InterpolatorType * GetInterpolator ()
virtual const char * GetNameOfClass () const
virtual const DirectionType & GetOutputDirection () const
virtual const RegionType & GetOutputLargestPossibleRegion () const
virtual const OriginPointType & GetOutputOrigin () const
virtual const SpacingType & GetOutputSpacing () const
itkGetObjectMacro (Transform, TransformType) virtual void SetInterpolator(InterpolatorPointer _arg)
virtual void SetFiniteStrainReorientation (bool _arg)
virtual void SetOutputDirection (DirectionType _arg)
virtual void SetOutputLargestPossibleRegion (RegionType _arg)
virtual void SetOutputOrigin (OriginPointType _arg)
virtual void SetOutputSpacing (SpacingType _arg)
virtual void SetTransform (TransformType *_arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual MaskRegionType GetComputationRegion ()
virtual void SetComputationMask (MaskImagePointer _arg)
virtual void SetComputationRegion (MaskRegionType _arg)
virtual void SetVerboseProgression (bool _arg)
Static Public Attributes
static const unsigned int ImageDimension = InputImageType::ImageDimension
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
vnl_matrix< double > ComputeLinearJacobianMatrix ()
void ComputeLocalJacobianMatrix (InputIndexType &index, vnl_matrix< double > &reorientationMatrix)
virtual void ComputeRotationParametersFromReorientationMatrix (vnl_matrix< double > &reorientationMatrix, vnl_matrix< double > &modelOrientationMatrix)
virtual void GenerateInputRequestedRegion () ITK_OVERRIDE
virtual void GenerateOutputInformation () ITK_OVERRIDE
virtual unsigned int GetOutputVectorLength ()
virtual void InitializeInterpolator ()
Initializes the default interpolator, might change in derived classes.
template<class T >
void InitializeZeroPixel (itk::VariableLengthVector< T > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<class T >
void InitializeZeroPixel (T &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
template<class T >
bool isZero (itk::VariableLengthVector< T > &dataVec)
template<class T >
bool isZero (T &data)
void LinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
void NonLinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
OrientedModelBaseResampleImageFilter ()
virtual void ReorientInterpolatedModel (const InputPixelType &interpolatedModel, vnl_matrix< double > &modelOrientationMatrix, InputPixelType &orientedModel, itk::ThreadIdType threadId)=0
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~OrientedModelBaseResampleImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
virtual void CheckComputationMask ()
virtual void DeleteProgressReporter ()
virtual void GenerateData () ITK_OVERRIDE
void InitializeComputationRegionFromMask ()
virtual void InitializeSplitParameters ()
void InitializeZeroPixel (TImageType *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (TImageType *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
MaskedImageToImageFilter ()
virtual void ThreadProcessSlices (itk::ThreadIdType threadId)
virtual ~MaskedImageToImageFilter ()
Additional Inherited Members
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
static Pointer New ()
Static Protected Member Functions inherited from anima::MaskedImageToImageFilter< TImageType, TImageType >
static ITK_THREAD_RETURN_TYPE ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TImageType, typename TInterpolatorPrecisionType = float>
class anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
Definition at line 14 of file animaOrientedModelBaseResampleImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<const Self> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ConstPointer
Definition at line 29 of file animaOrientedModelBaseResampleImageFilter.h.
ContinuousIndexType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef InterpolatorType::ContinuousIndexType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ContinuousIndexType
Definition at line 34 of file animaOrientedModelBaseResampleImageFilter.h.
DirectionType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TOutputImage::DirectionType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::DirectionType
Definition at line 66 of file animaOrientedModelBaseResampleImageFilter.h.
GeometryImagePointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef GeometryImageType::Pointer anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GeometryImagePointer
Definition at line 25 of file animaOrientedModelBaseResampleImageFilter.h.
GeometryImageType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::Image<unsigned char, itkGetStaticConstMacro(ImageDimension)> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GeometryImageType
Definition at line 24 of file animaOrientedModelBaseResampleImageFilter.h.
InputImagePointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef InputImageType::Pointer anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputImagePointer
Image typedef support
Definition at line 45 of file animaOrientedModelBaseResampleImageFilter.h.
InputImageType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TImageType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputImageType
Definition at line 20 of file animaOrientedModelBaseResampleImageFilter.h.
InputIndexType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef InputImageType::IndexType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputIndexType
Definition at line 42 of file animaOrientedModelBaseResampleImageFilter.h.
InputPixelType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef InputImageType::PixelType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputPixelType
Definition at line 40 of file animaOrientedModelBaseResampleImageFilter.h.
InputPointType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef InputImageType::PointType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputPointType
Definition at line 41 of file animaOrientedModelBaseResampleImageFilter.h.
InterpolatorPointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef InterpolatorType::Pointer anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InterpolatorPointer
Definition at line 32 of file animaOrientedModelBaseResampleImageFilter.h.
InterpolatorType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::InterpolateImageFunction<InputImageType, TInterpolatorPrecisionType> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InterpolatorType
Definition at line 31 of file animaOrientedModelBaseResampleImageFilter.h.
OriginPointType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TOutputImage::PointType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::OriginPointType
Definition at line 65 of file animaOrientedModelBaseResampleImageFilter.h.
OutputImagePointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TOutputImage::Pointer anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::OutputImagePointer
Definition at line 46 of file animaOrientedModelBaseResampleImageFilter.h.
OutputImageRegionType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TOutputImage::RegionType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::OutputImageRegionType
Definition at line 47 of file animaOrientedModelBaseResampleImageFilter.h.
Pointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<Self> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Pointer
Definition at line 28 of file animaOrientedModelBaseResampleImageFilter.h.
PointType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef InterpolatorType::PointType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::PointType
Definition at line 35 of file animaOrientedModelBaseResampleImageFilter.h.
RegionType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TOutputImage::RegionType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::RegionType
Definition at line 67 of file animaOrientedModelBaseResampleImageFilter.h.
Self
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef OrientedModelBaseResampleImageFilter anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Self
Standard class typedefs.
Definition at line 19 of file animaOrientedModelBaseResampleImageFilter.h.
SpacingType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TOutputImage::SpacingType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SpacingType
Definition at line 64 of file animaOrientedModelBaseResampleImageFilter.h.
Superclass
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef anima::MaskedImageToImageFilter<TImageType, TImageType> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Superclass
Definition at line 27 of file animaOrientedModelBaseResampleImageFilter.h.
TOutputImage
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TImageType anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::TOutputImage
Definition at line 21 of file animaOrientedModelBaseResampleImageFilter.h.
TransformPointer
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TransformType::Pointer anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::TransformPointer
Definition at line 53 of file animaOrientedModelBaseResampleImageFilter.h.
TransformType
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::Transform<TInterpolatorPrecisionType, itkGetStaticConstMacro(ImageDimension), itkGetStaticConstMacro(ImageDimension)> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::TransformType
Definition at line 51 of file animaOrientedModelBaseResampleImageFilter.h.
Constructor & Destructor Documentation
OrientedModelBaseResampleImageFilter()
template<typename TImageType , typename TInterpolatorPrecisionType = float> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::OrientedModelBaseResampleImageFilter () inline protected
Definition at line 82 of file animaOrientedModelBaseResampleImageFilter.h.
~OrientedModelBaseResampleImageFilter()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~OrientedModelBaseResampleImageFilter () inline protected virtual
Definition at line 90 of file animaOrientedModelBaseResampleImageFilter.h.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateInputRequestedRegion(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateOutputInformation(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputVectorLength(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< TImageType, TImageType >.
Reimplemented in anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >, and anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 70 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ThreadedGenerateData().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputVectorLength(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~OrientedModelBaseResampleImageFilter().
ComputeLinearJacobianMatrix()
template<typename TImageType , typename TInterpolatorPrecisionType > vnl_matrix< double > anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLinearJacobianMatrix () protected
Compute local re-orientation transformation matrix from linear transform (rotation if finite strain, Jacobian otherwise)
Definition at line 201 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLocalJacobianMatrix().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::NonLinearThreadedGenerateData().
ComputeLocalJacobianMatrix()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLocalJacobianMatrix (InputIndexType & index, vnl_matrix< double > & reorientationMatrix) protected
Compute local re-orientation transformation matrix from non linear transform (rotation if finite strain, Jacobian otherwise)
Definition at line 236 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeRotationParametersFromReorientationMatrix().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLinearJacobianMatrix(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel().
ComputeRotationParametersFromReorientationMatrix()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeRotationParametersFromReorientationMatrix (vnl_matrix< double > & reorientationMatrix, vnl_matrix< double > & modelOrientationMatrix) protected virtual
For some models / re-orientation schemes, the transform induced Jacobiam matrix needs to be used to get rotation parameters if needed, this method should be overloaded
Definition at line 329 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::ExtractRotationFromJacobianMatrix().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLocalJacobianMatrix(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel().
GenerateInputRequestedRegion()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateInputRequestedRegion () protected virtual
Definition at line 32 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateOutputInformation().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeInterpolator(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~OrientedModelBaseResampleImageFilter().
GenerateOutputInformation()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateOutputInformation (void) protected virtual
Definition at line 45 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputVectorLength().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateInputRequestedRegion(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~OrientedModelBaseResampleImageFilter().
GetFiniteStrainReorientation()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual bool anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetFiniteStrainReorientation () virtual
GetInterpolator()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual InterpolatorType* anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetInterpolator () virtual
GetNameOfClass()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const char* anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< TImageType, TImageType >.
Reimplemented in anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >, and anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
GetOutputDirection()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const DirectionType& anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputDirection () const virtual
GetOutputLargestPossibleRegion()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const RegionType& anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputLargestPossibleRegion () const virtual
GetOutputOrigin()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const OriginPointType& anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputOrigin () const virtual
GetOutputSpacing()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const SpacingType& anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputSpacing () const virtual
GetOutputVectorLength()
template<typename TImageType , typename TInterpolatorPrecisionType > unsigned int anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetOutputVectorLength () protected virtual
Reimplemented in anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 59 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateOutputInformation(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~OrientedModelBaseResampleImageFilter().
InitializeInterpolator()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeInterpolator () protected virtual
Initializes the default interpolator, might change in derived classes.
Reimplemented in anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 20 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GenerateInputRequestedRegion().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel().
InitializeZeroPixel() [1/2]
template<typename TImageType , typename TInterpolatorPrecisionType = float> template<class T > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel (itk::VariableLengthVector< T > & zeroPixel) inline protected
Utility function to initialize output images pixel to zero for vector images.
Definition at line 122 of file animaOrientedModelBaseResampleImageFilter.h.
InitializeZeroPixel() [2/2]
template<typename TImageType , typename TInterpolatorPrecisionType = float> template<class T > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel (T & zeroPixel) inline protected
Utility function to initialize output images pixel to zero for all images except vector images.
Definition at line 128 of file animaOrientedModelBaseResampleImageFilter.h.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLinearJacobianMatrix(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLocalJacobianMatrix(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeRotationParametersFromReorientationMatrix(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeInterpolator(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::LinearThreadedGenerateData(), anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::NonLinearThreadedGenerateData(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel().
isZero() [1/2]
template<typename TImageType , typename TInterpolatorPrecisionType = float> template<class T > bool anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::isZero (itk::VariableLengthVector< T > & dataVec) inline protected
Definition at line 101 of file animaOrientedModelBaseResampleImageFilter.h.
isZero() [2/2]
template<typename TImageType , typename TInterpolatorPrecisionType = float> template<class T > bool anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::isZero (T & data) inline protected
Definition at line 115 of file animaOrientedModelBaseResampleImageFilter.h.
itkGetObjectMacro()
template<typename TImageType , typename TInterpolatorPrecisionType = float> anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::itkGetObjectMacro (Transform , TransformType)
LinearThreadedGenerateData()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::LinearThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 103 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::NonLinearThreadedGenerateData().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ThreadedGenerateData().
NonLinearThreadedGenerateData()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::NonLinearThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 155 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ComputeLinearJacobianMatrix().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::LinearThreadedGenerateData().
ReorientInterpolatedModel()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel (const InputPixelType & interpolatedModel, vnl_matrix< double > & modelOrientationMatrix, InputPixelType & orientedModel, itk::ThreadIdType threadId) protected pure virtual
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
Implemented in anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >, and anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InitializeZeroPixel().
SetFiniteStrainReorientation()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetFiniteStrainReorientation (bool _arg) virtual
SetOutputDirection()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetOutputDirection (DirectionType _arg) virtual
SetOutputLargestPossibleRegion()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetOutputLargestPossibleRegion (RegionType _arg) virtual
SetOutputOrigin()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetOutputOrigin (OriginPointType _arg) virtual
Referenced by anima::PyramidImageFilter< TInputImage, TOutputImage >::CreateLevelVectorImage().
SetOutputSpacing()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetOutputSpacing (SpacingType _arg) virtual
SetTransform()
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::SetTransform (TransformType * _arg) virtual
ThreadedGenerateData()
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 92 of file animaOrientedModelBaseResampleImageFilter.hxx.
References anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::LinearThreadedGenerateData().
Referenced by anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData(), and anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~OrientedModelBaseResampleImageFilter().
Member Data Documentation
ImageDimension
template<typename TImageType , typename TInterpolatorPrecisionType = float> const unsigned int anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ImageDimension = InputImageType::ImageDimension static
Definition at line 22 of file animaOrientedModelBaseResampleImageFilter.h.
The documentation for this class was generated from the following files:
animaOrientedModelBaseResampleImageFilter.h
animaOrientedModelBaseResampleImageFilter.hxx