ANIMA: anima::ShapesWriter Class Reference
anima::ShapesWriter Class Reference
#include <animaShapesWriter.h>
Public Member Functions
void SetFileName (std::string &name)
void SetInputData (vtkPolyData *data)
ShapesWriter ()
void Update ()
~ShapesWriter ()
Protected Member Functions
void WriteFileAsCSV ()
void WriteFileAsMedinriaFibers ()
void WriteFileAsVTKAscii ()
void WriteFileAsVTKXML ()
Detailed Description
Definition at line 11 of file animaShapesWriter.h.
Constructor & Destructor Documentation
ShapesWriter()
anima::ShapesWriter::ShapesWriter () inline
Definition at line 14 of file animaShapesWriter.h.
~ShapesWriter()
anima::ShapesWriter::~ShapesWriter () inline
Definition at line 20 of file animaShapesWriter.h.
Member Function Documentation
SetFileName()
void anima::ShapesWriter::SetFileName (std::string & name) inline
Definition at line 23 of file animaShapesWriter.h.
Referenced by main().
SetInputData()
void anima::ShapesWriter::SetInputData (vtkPolyData * data) inline
Definition at line 22 of file animaShapesWriter.h.
Referenced by main().
Update()
void anima::ShapesWriter::Update ()
Definition at line 15 of file animaShapesWriter.cxx.
References WriteFileAsCSV(), WriteFileAsMedinriaFibers(), WriteFileAsVTKAscii(), and WriteFileAsVTKXML().
Referenced by main().
WriteFileAsCSV()
void anima::ShapesWriter::WriteFileAsCSV () protected
Definition at line 99 of file animaShapesWriter.cxx.
Referenced by Update().
WriteFileAsMedinriaFibers()
void anima::ShapesWriter::WriteFileAsMedinriaFibers () protected
Definition at line 53 of file animaShapesWriter.cxx.
Referenced by Update().
WriteFileAsVTKAscii()
void anima::ShapesWriter::WriteFileAsVTKAscii () protected
Definition at line 34 of file animaShapesWriter.cxx.
Referenced by Update().
WriteFileAsVTKXML()
void anima::ShapesWriter::WriteFileAsVTKXML () protected
Definition at line 42 of file animaShapesWriter.cxx.
Referenced by Update().
The documentation for this class was generated from the following files:
animaShapesWriter.h
animaShapesWriter.cxx