ANIMA: anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput > Class Template Reference
anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput > Class Template Reference
Class selecting the connected components touching a given mask border. In MRI, external CSF may contain artifacts due to fluid flow. These effects can cause voxels in the cortex or external CSF to have intensities similar to MS lesions. In order to reduce the number of false positives due to these effects, we remove all candidate lesions that are contiguous to the brain mask border.
#include <animaRemoveTouchingBorderFilter.h>
Public Types
typedef itk::ConnectedComponentImageFilter< InputImageType, ImageTypeInt > ConnectedComponentImageFilterType
typedef itk::ConnectedComponentImageFilter< TMask, ImageTypeInt > ConnectedComponentImageFilterType2
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ImageRegionIterator< ImageTypeInt > ImageIteratorTypeInt
typedef itk::Image< PixelTypeInt, 3 > ImageTypeInt
typedef itk::ImageRegionConstIterator< InputImageType > InputConstIteratorType
typedef InputImageType::Pointer InputImagePointer
typedef TInput InputImageType
typedef itk::ImageRegionIterator< InputImageType > InputIteratorType
typedef itk::LabelContourImageFilter< ImageTypeInt, ImageTypeInt > LabelContourImageFilterType
typedef itk::LabelImageToLabelMapFilter< ImageTypeInt > LabelImageToLabelMapFilterType
typedef itk::LabelImageToLabelMapFilter< TInput, TOutputMap > LabelImageToLabelMapFilterType2
typedef itk::LabelMapToLabelImageFilter< TOutputMap, ImageTypeInt > LabelMapToLabelImageFilterType
typedef itk::ImageRegionConstIterator< MaskImageType > MaskConstIteratorType
typedef MaskImageType::Pointer MaskImagePointer
typedef TMask MaskImageType
typedef itk::ImageRegionIterator< MaskImageType > MaskIteratorType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutput OutputImageType
typedef itk::ImageRegionIterator< OutputImageType > OutputIteratorType
typedef unsigned int PixelTypeInt
typedef itk::SmartPointer< Self > Pointer
typedef RemoveTouchingBorderFilter Self
typedef itk::ImageToImageFilter< TInput, TOutput > Superclass
typedef LabelImageToLabelMapFilterType::OutputImageType TOutputMap
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual bool GetLabeledImage ()
virtual const char * GetNameOfClass () const
virtual bool GetNoContour ()
TOutput * GetOutputNonTouchingBorder ()
TOutput * GetOutputTouchingBorder ()
virtual bool GetVerbose ()
void SetInputImageSeg (const TInput *image)
virtual void SetLabeledImage (bool _arg)
void SetMask (const TMask *mask)
virtual void SetNoContour (bool _arg)
void SetOutputNonTouchingBorderFilename (std::string fn)
void SetOutputTouchingBorderFilename (std::string fn)
void SetTol (const double tol)
virtual void SetVerbose (bool _arg)
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
virtual void GenerateData () ITK_OVERRIDE
TInput::ConstPointer GetInputImageSeg ()
TMask::ConstPointer GetMask ()
itk::DataObject::Pointer MakeOutput (unsigned int idx)
RemoveTouchingBorderFilter ()
virtual ~RemoveTouchingBorderFilter ()
Detailed Description
template<typename TInput, typename TMask, typename TOutput>
class anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >
Class selecting the connected components touching a given mask border. In MRI, external CSF may contain artifacts due to fluid flow. These effects can cause voxels in the cortex or external CSF to have intensities similar to MS lesions. In order to reduce the number of false positives due to these effects, we remove all candidate lesions that are contiguous to the brain mask border.
Definition at line 21 of file animaRemoveTouchingBorderFilter.h.
Member Typedef Documentation
ConnectedComponentImageFilterType
template<typename TInput , typename TMask , typename TOutput > typedef itk::ConnectedComponentImageFilter<InputImageType,ImageTypeInt> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::ConnectedComponentImageFilterType
Definition at line 66 of file animaRemoveTouchingBorderFilter.h.
ConnectedComponentImageFilterType2
template<typename TInput , typename TMask , typename TOutput > typedef itk::ConnectedComponentImageFilter<TMask, ImageTypeInt > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::ConnectedComponentImageFilterType2
Definition at line 67 of file animaRemoveTouchingBorderFilter.h.
ConstPointer
template<typename TInput , typename TMask , typename TOutput > typedef itk::SmartPointer<const Self> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::ConstPointer
Definition at line 29 of file animaRemoveTouchingBorderFilter.h.
ImageIteratorTypeInt
template<typename TInput , typename TMask , typename TOutput > typedef itk::ImageRegionIterator< ImageTypeInt > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::ImageIteratorTypeInt
Definition at line 58 of file animaRemoveTouchingBorderFilter.h.
ImageTypeInt
template<typename TInput , typename TMask , typename TOutput > typedef itk::Image<PixelTypeInt,3> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::ImageTypeInt
Definition at line 57 of file animaRemoveTouchingBorderFilter.h.
InputConstIteratorType
template<typename TInput , typename TMask , typename TOutput > typedef itk::ImageRegionConstIterator< InputImageType > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::InputConstIteratorType
Definition at line 43 of file animaRemoveTouchingBorderFilter.h.
InputImagePointer
template<typename TInput , typename TMask , typename TOutput > typedef InputImageType::Pointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::InputImagePointer
Definition at line 41 of file animaRemoveTouchingBorderFilter.h.
InputImageType
template<typename TInput , typename TMask , typename TOutput > typedef TInput anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::InputImageType
Image typedef support Type of the input image.
Definition at line 40 of file animaRemoveTouchingBorderFilter.h.
InputIteratorType
template<typename TInput , typename TMask , typename TOutput > typedef itk::ImageRegionIterator< InputImageType > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::InputIteratorType
Definition at line 42 of file animaRemoveTouchingBorderFilter.h.
LabelContourImageFilterType
template<typename TInput , typename TMask , typename TOutput > typedef itk::LabelContourImageFilter<ImageTypeInt, ImageTypeInt> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::LabelContourImageFilterType
Definition at line 69 of file animaRemoveTouchingBorderFilter.h.
LabelImageToLabelMapFilterType
template<typename TInput , typename TMask , typename TOutput > typedef itk::LabelImageToLabelMapFilter<ImageTypeInt> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::LabelImageToLabelMapFilterType
Definition at line 60 of file animaRemoveTouchingBorderFilter.h.
LabelImageToLabelMapFilterType2
template<typename TInput , typename TMask , typename TOutput > typedef itk::LabelImageToLabelMapFilter<TInput,TOutputMap> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::LabelImageToLabelMapFilterType2
Definition at line 62 of file animaRemoveTouchingBorderFilter.h.
LabelMapToLabelImageFilterType
template<typename TInput , typename TMask , typename TOutput > typedef itk::LabelMapToLabelImageFilter<TOutputMap, ImageTypeInt> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::LabelMapToLabelImageFilterType
Definition at line 64 of file animaRemoveTouchingBorderFilter.h.
MaskConstIteratorType
template<typename TInput , typename TMask , typename TOutput > typedef itk::ImageRegionConstIterator< MaskImageType > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::MaskConstIteratorType
Definition at line 49 of file animaRemoveTouchingBorderFilter.h.
MaskImagePointer
template<typename TInput , typename TMask , typename TOutput > typedef MaskImageType::Pointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::MaskImagePointer
Definition at line 47 of file animaRemoveTouchingBorderFilter.h.
MaskImageType
template<typename TInput , typename TMask , typename TOutput > typedef TMask anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::MaskImageType
Type of the mask image.
Definition at line 46 of file animaRemoveTouchingBorderFilter.h.
MaskIteratorType
template<typename TInput , typename TMask , typename TOutput > typedef itk::ImageRegionIterator< MaskImageType > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::MaskIteratorType
Definition at line 48 of file animaRemoveTouchingBorderFilter.h.
OutputImagePointer
template<typename TInput , typename TMask , typename TOutput > typedef OutputImageType::Pointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::OutputImagePointer
Definition at line 53 of file animaRemoveTouchingBorderFilter.h.
OutputImageRegionType
template<typename TInput , typename TMask , typename TOutput > typedef Superclass::OutputImageRegionType anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::OutputImageRegionType
Superclass typedefs.
Definition at line 93 of file animaRemoveTouchingBorderFilter.h.
OutputImageType
template<typename TInput , typename TMask , typename TOutput > typedef TOutput anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::OutputImageType
Type of the output image.
Definition at line 52 of file animaRemoveTouchingBorderFilter.h.
OutputIteratorType
template<typename TInput , typename TMask , typename TOutput > typedef itk::ImageRegionIterator< OutputImageType > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::OutputIteratorType
Definition at line 54 of file animaRemoveTouchingBorderFilter.h.
PixelTypeInt
template<typename TInput , typename TMask , typename TOutput > typedef unsigned int anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::PixelTypeInt
Definition at line 56 of file animaRemoveTouchingBorderFilter.h.
Pointer
template<typename TInput , typename TMask , typename TOutput > typedef itk::SmartPointer<Self> anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::Pointer
Definition at line 28 of file animaRemoveTouchingBorderFilter.h.
Self
template<typename TInput , typename TMask , typename TOutput > typedef RemoveTouchingBorderFilter anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::Self
Standard class typedefs.
Definition at line 26 of file animaRemoveTouchingBorderFilter.h.
Superclass
template<typename TInput , typename TMask , typename TOutput > typedef itk::ImageToImageFilter< TInput , TOutput > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::Superclass
Definition at line 27 of file animaRemoveTouchingBorderFilter.h.
TOutputMap
template<typename TInput , typename TMask , typename TOutput > typedef LabelImageToLabelMapFilterType::OutputImageType anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::TOutputMap
Definition at line 61 of file animaRemoveTouchingBorderFilter.h.
Constructor & Destructor Documentation
RemoveTouchingBorderFilter()
template<typename TInput , typename TMask , typename TOutput > anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::RemoveTouchingBorderFilter () inline protected
Definition at line 105 of file animaRemoveTouchingBorderFilter.h.
References anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::MakeOutput().
~RemoveTouchingBorderFilter()
template<typename TInput , typename TMask , typename TOutput > virtual anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::~RemoveTouchingBorderFilter () inline protected virtual
Definition at line 120 of file animaRemoveTouchingBorderFilter.h.
References anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GenerateData(), anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetInputImageSeg(), anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetMask(), and anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::MakeOutput().
Member Function Documentation
CreateAnother()
template<typename TInput , typename TMask , typename TOutput > virtual::itk::LightObject::Pointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::CreateAnother (void) const
GenerateData()
template<typename TInput , typename TMask , typename TOutput > void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GenerateData () protected virtual
Does the real work.
Definition at line 89 of file animaRemoveTouchingBorderFilter.hxx.
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::WriteOutputs(), and anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::~RemoveTouchingBorderFilter().
GetInputImageSeg()
template<typename TInput , typename TMask , typename TOutput > TInput::ConstPointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetInputImageSeg () protected
Definition at line 22 of file animaRemoveTouchingBorderFilter.hxx.
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::~RemoveTouchingBorderFilter().
GetLabeledImage()
template<typename TInput , typename TMask , typename TOutput > virtual bool anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetLabeledImage () virtual
GetMask()
template<typename TInput , typename TMask , typename TOutput > TMask::ConstPointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetMask () protected
Definition at line 28 of file animaRemoveTouchingBorderFilter.hxx.
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::~RemoveTouchingBorderFilter().
GetNameOfClass()
template<typename TInput , typename TMask , typename TOutput > virtual const char* anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetNoContour()
template<typename TInput , typename TMask , typename TOutput > virtual bool anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetNoContour () virtual
GetOutputNonTouchingBorder()
template<typename TInput , typename TMask , typename TOutput > TOutput * anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetOutputNonTouchingBorder ()
Definition at line 57 of file animaRemoveTouchingBorderFilter.hxx.
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetOutputTouchingBorderFilename().
GetOutputTouchingBorder()
template<typename TInput , typename TMask , typename TOutput > TOutput * anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetOutputTouchingBorder ()
Definition at line 63 of file animaRemoveTouchingBorderFilter.hxx.
References anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::WriteOutputs().
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetOutputTouchingBorderFilename().
GetVerbose()
template<typename TInput , typename TMask , typename TOutput > virtual bool anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetVerbose () virtual
MakeOutput()
template<typename TInput , typename TMask , typename TOutput > itk::DataObject::Pointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::MakeOutput (unsigned int idx) protected
Create the Output
Definition at line 36 of file animaRemoveTouchingBorderFilter.hxx.
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::RemoveTouchingBorderFilter(), and anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::~RemoveTouchingBorderFilter().
New()
template<typename TInput , typename TMask , typename TOutput > static Pointer anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::New () static
Method for creation through the object factory.
SetInputImageSeg()
template<typename TInput , typename TMask , typename TOutput > void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetInputImageSeg (const TInput * image)
The mri images.
Definition at line 9 of file animaRemoveTouchingBorderFilter.hxx.
SetLabeledImage()
template<typename TInput , typename TMask , typename TOutput > virtual void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetLabeledImage (bool _arg) virtual
SetMask()
template<typename TInput , typename TMask , typename TOutput > void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetMask (const TMask * mask)
mask in which the segmentation will be performed
Definition at line 15 of file animaRemoveTouchingBorderFilter.hxx.
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetOutputTouchingBorderFilename().
SetNoContour()
template<typename TInput , typename TMask , typename TOutput > virtual void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetNoContour (bool _arg) virtual
SetOutputNonTouchingBorderFilename()
template<typename TInput , typename TMask , typename TOutput > void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetOutputNonTouchingBorderFilename (std::string fn) inline
Definition at line 74 of file animaRemoveTouchingBorderFilter.h.
SetOutputTouchingBorderFilename()
template<typename TInput , typename TMask , typename TOutput > void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetOutputTouchingBorderFilename (std::string fn) inline
Definition at line 75 of file animaRemoveTouchingBorderFilter.h.
References anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetOutputNonTouchingBorder(), anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetOutputTouchingBorder(), anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetMask(), and anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::WriteOutputs().
SetTol()
template<typename TInput , typename TMask , typename TOutput > void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetTol (const double tol) inline
Definition at line 85 of file animaRemoveTouchingBorderFilter.h.
SetVerbose()
template<typename TInput , typename TMask , typename TOutput > virtual void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetVerbose (bool _arg) virtual
WriteOutputs()
template<typename TInput , typename TMask , typename TOutput > void anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::WriteOutputs ()
Definition at line 71 of file animaRemoveTouchingBorderFilter.hxx.
References anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GenerateData().
Referenced by anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::GetOutputTouchingBorder(), and anima::RemoveTouchingBorderFilter< TInput, TMask, TOutput >::SetOutputTouchingBorderFilename().
The documentation for this class was generated from the following files:
animaRemoveTouchingBorderFilter.h
animaRemoveTouchingBorderFilter.hxx