ANIMA: anima::MCMBlockMatchingInitializer< PixelType, NDimensions > Class Template Reference
anima::MCMBlockMatchingInitializer< PixelType, NDimensions > Class Template Reference
#include <animaMCMBlockMatchInitializer.h>
Classes
struct MCMBlockGeneratorThreadStruct
Public Types
typedef Superclass::BlockGeneratorThreadStruct BlockGeneratorThreadStruct
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ImageRegionType ImageRegionType
typedef anima::MCMImage< PixelType, NDimensions > MCMImageType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMBlockMatchingInitializer< PixelType, NDimensions > Self
typedef anima::BlockMatchingInitializer< PixelType, NDimensions > Superclass
Public Types inherited from anima::BlockMatchingInitializer< PixelType, NDimensions >
typedef itk::SmartPointer< const Self > ConstPointer
typedef ScalarImageType::RegionType ImageRegionType
typedef ScalarImageType::IndexType IndexType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, NDimensions > MaskImageType
typedef itk::SmartPointer< Self > Pointer
typedef ScalarImageType::PointType PointType
typedef ScalarImageType::Pointer ScalarImagePointer
typedef itk::Image< PixelType, NDimensions > ScalarImageType
typedef BlockMatchingInitializer< PixelType, NDimensions > Self
typedef itk::Object Superclass
typedef VectorImageType::Pointer VectorImagePointer
typedef itk::VectorImage< PixelType, NDimensions > VectorImageType
typedef WeightImageType::Pointer WeightImagePointer
typedef itk::Image< double, NDimensions > WeightImageType
Public Member Functions
void AddReferenceImage (itk::ImageBase< NDimensions > *refImage) ITK_OVERRIDE
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Public Member Functions inherited from anima::BlockMatchingInitializer< PixelType, NDimensions >
void AddGenerationMask (MaskImageType *mask)
void clearGenerationMasks ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual unsigned int GetBlockSize ()
virtual unsigned int GetBlockSpacing ()
itk::ImageBase< NDimensions > * GetFirstReferenceImage ()
std::vector< unsigned int > & GetMaskStartingIndexes ()
virtual unsigned int GetNumberOfThreads ()
virtual double GetOrientedModelVarianceThreshold ()
std::vector< ImageRegionType > & GetOutput ()
std::vector< PointType > & GetOutputPositions ()
virtual double GetPercentageKept ()
ScalarImageType * GetReferenceScalarImage (unsigned int i)
VectorImageType * GetReferenceVectorImage (unsigned int i)
virtual ImageRegionType GetRequestedRegion ()
virtual double GetScalarVarianceThreshold ()
void RegionBlockGenerator (BlockGeneratorThreadStruct *workStr, unsigned int threadId)
void SetBlockSize (unsigned int val)
void SetBlockSpacing (unsigned int val)
virtual void SetNumberOfThreads (unsigned int _arg)
void SetOrientedModelVarianceThreshold (double val)
void SetPercentageKept (double val)
void SetRequestedRegion (const ImageRegionType &val)
void SetScalarVarianceThreshold (double val)
void Update ()
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::BlockMatchingInitializer< PixelType, NDimensions >
static Pointer New ()
static ITK_THREAD_RETURN_TYPE ThreadBlockGenerator (void *arg)
Protected Member Functions
bool CheckOrientedModelVariance (unsigned int imageIndex, ImageRegionType &region, double &blockVariance, BlockGeneratorThreadStruct *workStr, unsigned int threadId) ITK_OVERRIDE
void InitializeThreading (unsigned int maskIndex, BlockGeneratorThreadStruct *&workStr) ITK_OVERRIDE
MCMBlockMatchingInitializer ()
virtual ~MCMBlockMatchingInitializer ()
Protected Member Functions inherited from anima::BlockMatchingInitializer< PixelType, NDimensions >
BlockMatchingInitializer ()
bool CheckBlockConditions (ImageRegionType &region, double &blockVariance, BlockGeneratorThreadStruct *workStr, unsigned int threadId)
bool CheckScalarVariance (ScalarImageType *refImage, ImageRegionType &region, double &blockVariance)
void ComputeBlocksOnGenerationMask (unsigned int maskIndex)
bool ProgressCounter (std::vector< unsigned int > &counter, std::vector< unsigned int > &bounds)
virtual ~BlockMatchingInitializer ()
Detailed Description
template<class PixelType, unsigned int NDimensions = 3>
class anima::MCMBlockMatchingInitializer< PixelType, NDimensions >
Definition at line 11 of file animaMCMBlockMatchInitializer.h.
Member Typedef Documentation
BlockGeneratorThreadStruct
template<class PixelType , unsigned int NDimensions = 3> typedef Superclass::BlockGeneratorThreadStruct anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::BlockGeneratorThreadStruct
Definition at line 31 of file animaMCMBlockMatchInitializer.h.
ConstPointer
template<class PixelType , unsigned int NDimensions = 3> typedef itk::SmartPointer<const Self> anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::ConstPointer
Definition at line 18 of file animaMCMBlockMatchInitializer.h.
ImageRegionType
template<class PixelType , unsigned int NDimensions = 3> typedef Superclass::ImageRegionType anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::ImageRegionType
Definition at line 32 of file animaMCMBlockMatchInitializer.h.
MCMImageType
template<class PixelType , unsigned int NDimensions = 3> typedef anima::MCMImage<PixelType, NDimensions> anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::MCMImageType
Definition at line 20 of file animaMCMBlockMatchInitializer.h.
MCModelPointer
template<class PixelType , unsigned int NDimensions = 3> typedef MCModelType::Pointer anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::MCModelPointer
Definition at line 29 of file animaMCMBlockMatchInitializer.h.
MCModelType
template<class PixelType , unsigned int NDimensions = 3> typedef anima::MultiCompartmentModel anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::MCModelType
Definition at line 28 of file animaMCMBlockMatchInitializer.h.
Pointer
template<class PixelType , unsigned int NDimensions = 3> typedef itk::SmartPointer<Self> anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::Pointer
Definition at line 17 of file animaMCMBlockMatchInitializer.h.
Self
template<class PixelType , unsigned int NDimensions = 3> typedef MCMBlockMatchingInitializer<PixelType,NDimensions> anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::Self
Definition at line 16 of file animaMCMBlockMatchInitializer.h.
Superclass
template<class PixelType , unsigned int NDimensions = 3> typedef anima::BlockMatchingInitializer<PixelType, NDimensions> anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::Superclass
Definition at line 15 of file animaMCMBlockMatchInitializer.h.
Constructor & Destructor Documentation
MCMBlockMatchingInitializer()
template<class PixelType , unsigned int NDimensions = 3> anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::MCMBlockMatchingInitializer () inline protected
Definition at line 42 of file animaMCMBlockMatchInitializer.h.
Referenced by anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::~MCMBlockMatchingInitializer().
~MCMBlockMatchingInitializer()
template<class PixelType , unsigned int NDimensions = 3> virtual anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::~MCMBlockMatchingInitializer () inline protected virtual
Definition at line 46 of file animaMCMBlockMatchInitializer.h.
References anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::CheckOrientedModelVariance(), anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading(), and anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::MCMBlockMatchingInitializer().
Member Function Documentation
AddReferenceImage()
template<class PixelType , unsigned int NDimensions> void anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::AddReferenceImage (itk::ImageBase< NDimensions > * refImage) virtual
Reimplemented from anima::BlockMatchingInitializer< PixelType, NDimensions >.
Definition at line 18 of file animaMCMBlockMatchInitializer.hxx.
References anima::MCMImage< TPixel, VImageDimension >::GetDescriptionModel(), and anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading().
CheckOrientedModelVariance()
template<class PixelType , unsigned int NDimensions> bool anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::CheckOrientedModelVariance (unsigned int imageIndex, ImageRegionType & region, double & blockVariance, BlockGeneratorThreadStruct * workStr, unsigned int threadId) protected virtual
Reimplemented from anima::BlockMatchingInitializer< PixelType, NDimensions >.
Definition at line 49 of file animaMCMBlockMatchInitializer.hxx.
Referenced by anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading(), and anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::~MCMBlockMatchingInitializer().
CreateAnother()
template<class PixelType , unsigned int NDimensions = 3> virtual::itk::LightObject::Pointer anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::CreateAnother (void) const
GetNameOfClass()
template<class PixelType , unsigned int NDimensions = 3> virtual const char* anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::BlockMatchingInitializer< PixelType, NDimensions >.
InitializeThreading()
template<class PixelType , unsigned int NDimensions> void anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::InitializeThreading (unsigned int maskIndex, BlockGeneratorThreadStruct *& workStr) protected virtual
Reimplemented from anima::BlockMatchingInitializer< PixelType, NDimensions >.
Definition at line 30 of file animaMCMBlockMatchInitializer.hxx.
References anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::CheckOrientedModelVariance(), and anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::MCMBlockGeneratorThreadStruct::ref_models.
Referenced by anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::AddReferenceImage(), and anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::~MCMBlockMatchingInitializer().
New()
template<class PixelType , unsigned int NDimensions = 3> static Pointer anima::MCMBlockMatchingInitializer< PixelType, NDimensions >::New () static
Method for creation through the object factory.
The documentation for this class was generated from the following files:
animaMCMBlockMatchInitializer.h
animaMCMBlockMatchInitializer.hxx