ANIMA: anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions > Class Template Reference
anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions > Class Template Reference
#include <animaMEstimateSVFImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef TInputImage::Pointer InputImagePointer
typedef TInputImage::IndexType InputIndexType
typedef TInputImage::PixelType InputPixelType
typedef TInputImage::PointType InputPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage::PixelType OutputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef MEstimateSVFImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::Image< itk::Vector< TScalarType, NDegreesOfFreedom >, NDimensions > TInputImage
typedef itk::Image< itk::Vector< TScalarType, NDegreesOfFreedom >, NDimensions > TOutputImage
typedef WeightImageType::Pointer WeightImagePointer
typedef itk::Image< TScalarType, NDimensions > WeightImageType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetConvergenceThreshold (double _arg)
void SetDistanceBoundary (double num)
virtual void SetFluidSigma (double _arg)
virtual void SetMaxNumIterations (unsigned int _arg)
virtual void SetMEstimateFactor (double _arg)
virtual void SetWeightImage (WeightImagePointer _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
MEstimateSVFImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~MEstimateSVFImageFilter ()
Detailed Description
template<class TScalarType, unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3>
class anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >
Definition at line 11 of file animaMEstimateSVFImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::SmartPointer<const Self> anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ConstPointer
Definition at line 23 of file animaMEstimateSVFImageFilter.h.
InputImagePointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::Pointer anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputImagePointer
Image typedef support
Definition at line 37 of file animaMEstimateSVFImageFilter.h.
InputIndexType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::IndexType anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputIndexType
Definition at line 33 of file animaMEstimateSVFImageFilter.h.
InputPixelType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::PixelType anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputPixelType
Definition at line 32 of file animaMEstimateSVFImageFilter.h.
InputPointType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TInputImage::PointType anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::InputPointType
Definition at line 34 of file animaMEstimateSVFImageFilter.h.
OutputImagePointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TOutputImage::Pointer anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::OutputImagePointer
Definition at line 38 of file animaMEstimateSVFImageFilter.h.
OutputImageRegionType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef Superclass::OutputImageRegionType anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::OutputImageRegionType
Superclass typedefs.
Definition at line 41 of file animaMEstimateSVFImageFilter.h.
OutputPixelType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef TOutputImage::PixelType anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::OutputPixelType
Definition at line 31 of file animaMEstimateSVFImageFilter.h.
Pointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::SmartPointer<Self> anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::Pointer
Definition at line 22 of file animaMEstimateSVFImageFilter.h.
Self
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef MEstimateSVFImageFilter anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::Self
Standard class typedefs.
Definition at line 16 of file animaMEstimateSVFImageFilter.h.
Superclass
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::ImageToImageFilter<TInputImage, TOutputImage> anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::Superclass
Definition at line 21 of file animaMEstimateSVFImageFilter.h.
TInputImage
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::Image< itk::Vector <TScalarType,NDegreesOfFreedom>, NDimensions > anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::TInputImage
Definition at line 19 of file animaMEstimateSVFImageFilter.h.
TOutputImage
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::Image< itk::Vector <TScalarType,NDegreesOfFreedom>, NDimensions > anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::TOutputImage
Definition at line 20 of file animaMEstimateSVFImageFilter.h.
WeightImagePointer
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef WeightImageType::Pointer anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::WeightImagePointer
Definition at line 18 of file animaMEstimateSVFImageFilter.h.
WeightImageType
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> typedef itk::Image<TScalarType, NDimensions> anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::WeightImageType
Definition at line 17 of file animaMEstimateSVFImageFilter.h.
Constructor & Destructor Documentation
MEstimateSVFImageFilter()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::MEstimateSVFImageFilter () inline protected
Definition at line 53 of file animaMEstimateSVFImageFilter.h.
~MEstimateSVFImageFilter()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::~MEstimateSVFImageFilter () inline protected virtual
Definition at line 61 of file animaMEstimateSVFImageFilter.h.
References anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::BeforeThreadedGenerateData(), and anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions> void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::BeforeThreadedGenerateData () protected
Definition at line 15 of file animaMEstimateSVFImageFilter.hxx.
References anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ThreadedGenerateData().
Referenced by anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::~MEstimateSVFImageFilter().
CreateAnother()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual::itk::LightObject::Pointer anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::CreateAnother (void) const
GetNameOfClass()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual const char* anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::GetNameOfClass () const virtual
Run-time type information (and related methods)
New()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> static Pointer anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::New () static
Method for creation through the object factory.
SetConvergenceThreshold()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetConvergenceThreshold (double _arg) virtual
SetDistanceBoundary()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetDistanceBoundary (double num) inline
Definition at line 47 of file animaMEstimateSVFImageFilter.h.
SetFluidSigma()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetFluidSigma (double _arg) virtual
SetMaxNumIterations()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetMaxNumIterations (unsigned int _arg) virtual
SetMEstimateFactor()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetMEstimateFactor (double _arg) virtual
SetWeightImage()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions = 3> virtual void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::SetWeightImage (WeightImagePointer _arg) virtual
ThreadedGenerateData()
template<class TScalarType , unsigned int NDegreesOfFreedom, unsigned int NDimensions> void anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected
Definition at line 168 of file animaMEstimateSVFImageFilter.hxx.
Referenced by anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::BeforeThreadedGenerateData(), and anima::MEstimateSVFImageFilter< TScalarType, NDegreesOfFreedom, NDimensions >::~MEstimateSVFImageFilter().
The documentation for this class was generated from the following files:
animaMEstimateSVFImageFilter.h
animaMEstimateSVFImageFilter.hxx