ANIMA: anima::MCMFileReader< PixelType, ImageDimension > Class Template Reference
anima::MCMFileReader< PixelType, ImageDimension > Class Template Reference
#include <animaMCMFileReader.h>
Public Types
typedef BaseInputImageType::Pointer BaseInputImagePointer
typedef itk::VectorImage< PixelType, ImageDimension > BaseInputImageType
typedef ModelType::Pointer ModelPointer
typedef anima::MultiCompartmentModel ModelType
typedef OutputImageType::Pointer OutputImagePointer
typedef anima::MCMImage< PixelType, ImageDimension > OutputImageType
Public Member Functions
virtual anima::BaseCompartment::Pointer CreateCompartmentForType (std::string &compartmentType)
OutputImagePointer & GetModelVectorImage ()
MCMFileReader ()
void SetFileName (std::string fileName)
void Update ()
~MCMFileReader ()
Detailed Description
template<class PixelType, unsigned int ImageDimension>
class anima::MCMFileReader< PixelType, ImageDimension >
Definition at line 19 of file animaMCMFileReader.h.
Member Typedef Documentation
BaseInputImagePointer
template<class PixelType, unsigned int ImageDimension> typedef BaseInputImageType::Pointer anima::MCMFileReader< PixelType, ImageDimension >::BaseInputImagePointer
Definition at line 27 of file animaMCMFileReader.h.
BaseInputImageType
template<class PixelType, unsigned int ImageDimension> typedef itk::VectorImage<PixelType, ImageDimension> anima::MCMFileReader< PixelType, ImageDimension >::BaseInputImageType
Definition at line 26 of file animaMCMFileReader.h.
ModelPointer
template<class PixelType, unsigned int ImageDimension> typedef ModelType::Pointer anima::MCMFileReader< PixelType, ImageDimension >::ModelPointer
Definition at line 23 of file animaMCMFileReader.h.
ModelType
template<class PixelType, unsigned int ImageDimension> typedef anima::MultiCompartmentModel anima::MCMFileReader< PixelType, ImageDimension >::ModelType
Definition at line 22 of file animaMCMFileReader.h.
OutputImagePointer
template<class PixelType, unsigned int ImageDimension> typedef OutputImageType::Pointer anima::MCMFileReader< PixelType, ImageDimension >::OutputImagePointer
Definition at line 25 of file animaMCMFileReader.h.
OutputImageType
template<class PixelType, unsigned int ImageDimension> typedef anima::MCMImage<PixelType, ImageDimension> anima::MCMFileReader< PixelType, ImageDimension >::OutputImageType
Definition at line 24 of file animaMCMFileReader.h.
Constructor & Destructor Documentation
MCMFileReader()
template<class PixelType , unsigned int ImageDimension> anima::MCMFileReader< PixelType, ImageDimension >::MCMFileReader ()
Definition at line 23 of file animaMCMFileReader.hxx.
~MCMFileReader()
template<class PixelType , unsigned int ImageDimension> anima::MCMFileReader< PixelType, ImageDimension >::~MCMFileReader ()
Definition at line 30 of file animaMCMFileReader.hxx.
Member Function Documentation
CreateCompartmentForType()
template<class PixelType , unsigned int ImageDimension> anima::BaseCompartment::Pointer anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType (std::string & compartmentType) virtual
Definition at line 164 of file animaMCMFileReader.hxx.
References anima::FreeWaterCompartment::New(), anima::StationaryWaterCompartment::New(), anima::IsotropicRestrictedWaterCompartment::New(), anima::NODDICompartment::New(), anima::StickCompartment::New(), anima::StaniszCompartment::New(), anima::TensorCompartment::New(), and anima::ZeppelinCompartment::New().
Referenced by anima::MCMFileReader< PixelType, ImageDimension >::SetFileName().
GetModelVectorImage()
template<class PixelType, unsigned int ImageDimension> OutputImagePointer& anima::MCMFileReader< PixelType, ImageDimension >::GetModelVectorImage () inline
Definition at line 32 of file animaMCMFileReader.h.
Referenced by main().
SetFileName()
template<class PixelType, unsigned int ImageDimension> void anima::MCMFileReader< PixelType, ImageDimension >::SetFileName (std::string fileName) inline
Definition at line 33 of file animaMCMFileReader.h.
References anima::MCMFileReader< PixelType, ImageDimension >::CreateCompartmentForType(), and anima::MCMFileReader< PixelType, ImageDimension >::Update().
Referenced by main().
Update()
template<class PixelType , unsigned int ImageDimension> void anima::MCMFileReader< PixelType, ImageDimension >::Update ()
Definition at line 37 of file animaMCMFileReader.hxx.
Referenced by main(), and anima::MCMFileReader< PixelType, ImageDimension >::SetFileName().
The documentation for this class was generated from the following files:
animaMCMFileReader.h
animaMCMFileReader.hxx