ANIMA: anima::SimuBlochIRGRE< TImage > Class Template Reference
anima::SimuBlochIRGRE< TImage > Class Template Reference
#include <animaSimuBlochIR-GRE.h>
Public Types
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef SimuBlochIRGRE Self
typedef itk::ImageToImageFilter< TImage, TImage > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual float GetTE ()
virtual float GetTI ()
virtual float GetTR ()
void SetInputM0 (const TImage *M0)
void SetInputT1 (const TImage *T1)
void SetInputT2s (const TImage *T2s)
virtual void SetTE (float _arg)
virtual void SetTI (float _arg)
virtual void SetTR (float _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
SimuBlochIRGRE ()
virtual void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~SimuBlochIRGRE ()
Detailed Description
template<class TImage>
class anima::SimuBlochIRGRE< TImage >
Definition at line 9 of file animaSimuBlochIR-GRE.h.
Member Typedef Documentation
OutputImageRegionType
template<class TImage > typedef Superclass::OutputImageRegionType anima::SimuBlochIRGRE< TImage >::OutputImageRegionType
Definition at line 17 of file animaSimuBlochIR-GRE.h.
Pointer
template<class TImage > typedef itk::SmartPointer<Self> anima::SimuBlochIRGRE< TImage >::Pointer
Definition at line 15 of file animaSimuBlochIR-GRE.h.
Self
template<class TImage > typedef SimuBlochIRGRE anima::SimuBlochIRGRE< TImage >::Self
Standard class typedefs.
Definition at line 13 of file animaSimuBlochIR-GRE.h.
Superclass
template<class TImage > typedef itk::ImageToImageFilter<TImage, TImage> anima::SimuBlochIRGRE< TImage >::Superclass
Definition at line 14 of file animaSimuBlochIR-GRE.h.
Constructor & Destructor Documentation
SimuBlochIRGRE()
template<class TImage > anima::SimuBlochIRGRE< TImage >::SimuBlochIRGRE () protected
Definition at line 46 of file animaSimuBlochIR-GRE.hxx.
~SimuBlochIRGRE()
template<class TImage > virtual anima::SimuBlochIRGRE< TImage >::~SimuBlochIRGRE () inline protected virtual
Definition at line 45 of file animaSimuBlochIR-GRE.h.
References anima::SimuBlochIRGRE< TImage >::ThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<class TImage > virtual::itk::LightObject::Pointer anima::SimuBlochIRGRE< TImage >::CreateAnother (void) const
GetNameOfClass()
template<class TImage > virtual const char* anima::SimuBlochIRGRE< TImage >::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetTE()
template<class TImage > virtual float anima::SimuBlochIRGRE< TImage >::GetTE () virtual
GetTI()
template<class TImage > virtual float anima::SimuBlochIRGRE< TImage >::GetTI () virtual
GetTR()
template<class TImage > virtual float anima::SimuBlochIRGRE< TImage >::GetTR () virtual
New()
template<class TImage > static Pointer anima::SimuBlochIRGRE< TImage >::New () static
Method for creation through the object factory.
SetInputM0()
template<class TImage > void anima::SimuBlochIRGRE< TImage >::SetInputM0 (const TImage * M0)
M0 image / Rho map
Definition at line 64 of file animaSimuBlochIR-GRE.hxx.
References anima::SimuBlochIRGRE< TImage >::ThreadedGenerateData().
SetInputT1()
template<class TImage > void anima::SimuBlochIRGRE< TImage >::SetInputT1 (const TImage * T1)
T1 map
Definition at line 52 of file animaSimuBlochIR-GRE.hxx.
SetInputT2s()
template<class TImage > void anima::SimuBlochIRGRE< TImage >::SetInputT2s (const TImage * T2s)
T2s map
Definition at line 58 of file animaSimuBlochIR-GRE.hxx.
SetTE()
template<class TImage > virtual void anima::SimuBlochIRGRE< TImage >::SetTE (float _arg) virtual
SetTI()
template<class TImage > virtual void anima::SimuBlochIRGRE< TImage >::SetTI (float _arg) virtual
SetTR()
template<class TImage > virtual void anima::SimuBlochIRGRE< TImage >::SetTR (float _arg) virtual
ThreadedGenerateData()
template<class TImage > void anima::SimuBlochIRGRE< TImage >::ThreadedGenerateData (const OutputImageRegionType & outputRegionForThread, itk::ThreadIdType threadId) protected virtual
Does the real work.
Definition at line 71 of file animaSimuBlochIR-GRE.hxx.
Referenced by anima::SimuBlochIRGRE< TImage >::SetInputM0(), and anima::SimuBlochIRGRE< TImage >::~SimuBlochIRGRE().
The documentation for this class was generated from the following files:
animaSimuBlochIR-GRE.h
animaSimuBlochIR-GRE.hxx