ANIMA: anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension > Class Template Reference
Tensor correlation similarity measure as defined by Taquet et al.
#include <animaTensorCorrelationImageToImageMetric.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::ContinuousIndex< double, ImageDimension > ContinuousIndexType
typedef Superclass::CoordinateRepresentationType CoordinateRepresentationType
typedef Superclass::FixedImageConstPointer FixedImageConstPointer
typedef Superclass::FixedImageType FixedImageType
typedef Superclass::InputPointType InputPointType
typedef Superclass::MeasureType MeasureType
typedef Superclass::MovingImageConstPointer MovingImageConstPointer
typedef Superclass::MovingImageType MovingImageType
typedef Superclass::OutputPointType OutputPointType
typedef TFixedImage::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef TensorCorrelationImageToImageMetric Self
typedef BaseOrientedModelImageToImageMetric< TFixedImage, TMovingImage > Superclass
typedef itk::VectorImage< TFixedImagePixelType, ImageDimension > TFixedImage
typedef itk::VectorImage< TMovingImagePixelType, ImageDimension > TMovingImage
typedef Superclass::TransformParametersType TransformParametersType
typedef Superclass::TransformPointer TransformPointer
typedef Superclass::TransformType TransformType
Public Types inherited from anima::BaseOrientedModelImageToImageMetric< itk::VectorImage< TFixedImagePixelType, ImageDimension >, itk::VectorImage< TMovingImagePixelType, ImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::ParametersValueType CoordinateRepresentationType
typedef Superclass::DerivativeType DerivativeType
typedef FixedImageType::ConstPointer FixedImageConstPointer
typedef FixedImageMaskType::ConstPointer FixedImageMaskConstPointer
typedef FixedImageMaskType::Pointer FixedImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(FixedImageDimension) > FixedImageMaskType
typedef FixedImageType::RegionType FixedImageRegionType
typedef itk::VectorImage< TFixedImagePixelType, ImageDimension > FixedImageType
typedef TransformType::InputPointType InputPointType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef itk::InterpolateImageFunction< MovingImageType, CoordinateRepresentationType > InterpolatorType
typedef Superclass::MeasureType MeasureType
enum ModelReorientationType
typedef MovingImageType::ConstPointer MovingImageConstPointer
typedef MovingImageMaskType::ConstPointer MovingImageMaskConstPointer
typedef MovingImageMaskType::Pointer MovingImageMaskPointer
typedef itk::SpatialObject< itkGetStaticConstMacro(MovingImageDimension) > MovingImageMaskType
typedef itk::VectorImage< TMovingImagePixelType, ImageDimension > ::PixelType MovingImagePixelType
typedef itk::VectorImage< TMovingImagePixelType, ImageDimension > MovingImageType
typedef TransformType::OutputPointType OutputPointType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef double RealType
typedef BaseOrientedModelImageToImageMetric Self
typedef itk::SingleValuedCostFunction Superclass
typedef TransformType::JacobianType TransformJacobianType
typedef TransformType::ParametersType TransformParametersType
typedef TransformType::Pointer TransformPointer
typedef itk::Transform< CoordinateRepresentationType, itkGetStaticConstMacro(MovingImageDimension), itkGetStaticConstMacro(FixedImageDimension)> TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
MeasureType GetValue (const TransformParametersType &parameters) const ITK_OVERRIDE
void PreComputeFixedValues ()
Public Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< itk::VectorImage< TFixedImagePixelType, ImageDimension >, itk::VectorImage< TMovingImagePixelType, ImageDimension > >
void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
Should not be used.
virtual const FixedImageType * GetFixedImage () const
virtual const FixedImageMaskType * GetFixedImageMask () const
virtual const FixedImageRegionType & GetFixedImageRegion () const
virtual const InterpolatorType * GetInterpolator () const
virtual ModelReorientationType GetModelRotation () const
virtual const MovingImageType * GetMovingImage () const
virtual const MovingImageMaskType * GetMovingImageMask () const
unsigned int GetNumberOfParameters (void) const ITK_OVERRIDE
virtual const unsigned long & GetNumberOfPixelsCounted () const
virtual const TransformType * GetTransform () const
void GetValueAndDerivative (const TransformParametersType &parameters, MeasureType &value, DerivativeType &derivative) const ITK_OVERRIDE
virtual void Initialize ()
virtual void SetFixedImage (const FixedImageType *_arg)
virtual void SetFixedImageMask (FixedImageMaskType *_arg)
virtual void SetFixedImageMask (const FixedImageMaskType *_arg)
virtual void SetFixedImageRegion (FixedImageRegionType _arg)
virtual void SetInterpolator (InterpolatorType *_arg)
virtual void SetModelRotation (ModelReorientationType _arg)
virtual void SetMovingImage (const MovingImageType *_arg)
virtual void SetMovingImageMask (MovingImageMaskType *_arg)
virtual void SetMovingImageMask (const MovingImageMaskType *_arg)
virtual void SetTransform (TransformType *_arg)
void SetTransformParameters (const ParametersType &parameters) const
Static Public Member Functions
static Pointer New ()
Protected Member Functions
TensorCorrelationImageToImageMetric ()
virtual ~TensorCorrelationImageToImageMetric ()
Protected Member Functions inherited from anima::BaseOrientedModelImageToImageMetric< itk::VectorImage< TFixedImagePixelType, ImageDimension >, itk::VectorImage< TMovingImagePixelType, ImageDimension > >
BaseOrientedModelImageToImageMetric ()
void PrintSelf (std::ostream &os, itk::Indent indent) const ITK_OVERRIDE
virtual ~BaseOrientedModelImageToImageMetric ()
Additional Inherited Members
Static Public Attributes inherited from anima::BaseOrientedModelImageToImageMetric< itk::VectorImage< TFixedImagePixelType, ImageDimension >, itk::VectorImage< TMovingImagePixelType, ImageDimension > >
static const unsigned int FixedImageDimension
static const unsigned int MovingImageDimension
Protected Attributes inherited from anima::BaseOrientedModelImageToImageMetric< itk::VectorImage< TFixedImagePixelType, ImageDimension >, itk::VectorImage< TMovingImagePixelType, ImageDimension > >
FixedImageConstPointer m_FixedImage
FixedImageMaskConstPointer m_FixedImageMask
InterpolatorPointer m_Interpolator
MovingImageConstPointer m_MovingImage
MovingImageMaskConstPointer m_MovingImageMask
unsigned long m_NumberOfPixelsCounted
vnl_matrix< double > m_OrientationMatrix
TransformPointer m_Transform
Detailed Description
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension>
class anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >
Tensor correlation similarity measure as defined by Taquet et al.
M. Taquet et al. "A Mathematical Framework for the Registration and Analysis of Multi-Fascicle Models for Population Studies of the Brain Microstructure". IEEE TMI 2014.
Definition at line 18 of file animaTensorCorrelationImageToImageMetric.h.
Member Typedef Documentation
ConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<const Self> anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ConstPointer
Definition at line 30 of file animaTensorCorrelationImageToImageMetric.h.
ContinuousIndexType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::ContinuousIndex<double, ImageDimension> anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::ContinuousIndexType
Definition at line 46 of file animaTensorCorrelationImageToImageMetric.h.
CoordinateRepresentationType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::CoordinateRepresentationType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CoordinateRepresentationType
Definition at line 48 of file animaTensorCorrelationImageToImageMetric.h.
FixedImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageConstPointer anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageConstPointer
Definition at line 53 of file animaTensorCorrelationImageToImageMetric.h.
FixedImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::FixedImageType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::FixedImageType
Definition at line 51 of file animaTensorCorrelationImageToImageMetric.h.
InputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::InputPointType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::InputPointType
Definition at line 45 of file animaTensorCorrelationImageToImageMetric.h.
MeasureType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MeasureType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType
Definition at line 50 of file animaTensorCorrelationImageToImageMetric.h.
MovingImageConstPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageConstPointer anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageConstPointer
Definition at line 54 of file animaTensorCorrelationImageToImageMetric.h.
MovingImageType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::MovingImageType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MovingImageType
Definition at line 52 of file animaTensorCorrelationImageToImageMetric.h.
OutputPointType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::OutputPointType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::OutputPointType
Definition at line 44 of file animaTensorCorrelationImageToImageMetric.h.
PixelType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef TFixedImage::PixelType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PixelType
Types transferred from the base class
Definition at line 39 of file animaTensorCorrelationImageToImageMetric.h.
Pointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::SmartPointer<Self> anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Pointer
Definition at line 29 of file animaTensorCorrelationImageToImageMetric.h.
Self
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef TensorCorrelationImageToImageMetric anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Self
Definition at line 27 of file animaTensorCorrelationImageToImageMetric.h.
Superclass
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef BaseOrientedModelImageToImageMetric<TFixedImage, TMovingImage > anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::Superclass
Definition at line 28 of file animaTensorCorrelationImageToImageMetric.h.
TFixedImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::VectorImage<TFixedImagePixelType, ImageDimension> anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TFixedImage
Standard class typedefs.
Definition at line 24 of file animaTensorCorrelationImageToImageMetric.h.
TMovingImage
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef itk::VectorImage<TMovingImagePixelType, ImageDimension> anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TMovingImage
Definition at line 25 of file animaTensorCorrelationImageToImageMetric.h.
TransformParametersType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformParametersType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformParametersType
Definition at line 43 of file animaTensorCorrelationImageToImageMetric.h.
TransformPointer
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformPointer anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformPointer
Definition at line 42 of file animaTensorCorrelationImageToImageMetric.h.
TransformType
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> typedef Superclass::TransformType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TransformType
Definition at line 41 of file animaTensorCorrelationImageToImageMetric.h.
Constructor & Destructor Documentation
TensorCorrelationImageToImageMetric()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TensorCorrelationImageToImageMetric () protected
Constructor
Definition at line 16 of file animaTensorCorrelationImageToImageMetric.hxx.
References anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
Referenced by anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~TensorCorrelationImageToImageMetric().
~TensorCorrelationImageToImageMetric()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::~TensorCorrelationImageToImageMetric () inline protected virtual
Definition at line 63 of file animaTensorCorrelationImageToImageMetric.h.
References anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TensorCorrelationImageToImageMetric().
Member Function Documentation
CreateAnother()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual::itk::LightObject::Pointer anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::CreateAnother (void) const
GetNameOfClass()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> virtual const char* anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::BaseOrientedModelImageToImageMetric< itk::VectorImage< TFixedImagePixelType, ImageDimension >, itk::VectorImage< TMovingImagePixelType, ImageDimension > >.
GetValue()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::MeasureType anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue (const TransformParametersType & parameters) const
Get the value for single valued optimizers.
Get the match Measure
Definition at line 33 of file animaTensorCorrelationImageToImageMetric.hxx.
References anima::ExtractPPDRotationFromJacobianMatrix(), anima::GetTensorFromVectorRepresentation(), anima::GetVectorRepresentation(), anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues(), and anima::RotateSymmetricMatrix().
Referenced by anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::TensorCorrelationImageToImageMetric().
New()
template<class TFixedImagePixelType, class TMovingImagePixelType, unsigned int ImageDimension> static Pointer anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::New () static
Method for creation through the object factory.
PreComputeFixedValues()
template<class TFixedImagePixelType , class TMovingImagePixelType , unsigned int ImageDimension> void anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::PreComputeFixedValues ()
Definition at line 136 of file animaTensorCorrelationImageToImageMetric.hxx.
Referenced by anima::TensorCorrelationImageToImageMetric< TFixedImagePixelType, TMovingImagePixelType, ImageDimension >::GetValue().
The documentation for this class was generated from the following files:
animaTensorCorrelationImageToImageMetric.h
animaTensorCorrelationImageToImageMetric.hxx