ANIMA: anima::PyramidalBlockMatchingBridge< ImageDimension > Class Template Reference
anima::PyramidalBlockMatchingBridge< ImageDimension > Class Template Reference
#include <animaPyramidalBlockMatchingBridge.h>
Public Types
typedef AffineTransformType::Pointer AffineTransformPointer
typedef itk::AffineTransform< typename AgregatorType::ScalarType, ImageDimension > AffineTransformType
enum Agregator {
MEstimation = 0,
LeastSquares,
LeastTrimmedSquares
}
typedef anima::BaseTransformAgregator< ImageDimension > AgregatorType
typedef BaseBlockMatchRegistrationType::Pointer BaseBlockMatchRegistrationPointer
typedef anima::BaseBMRegistrationMethod< InputImageType > BaseBlockMatchRegistrationType
typedef BaseTransformType::Pointer BaseTransformPointer
typedef AgregatorType::BaseOutputTransformType BaseTransformType
typedef itk::SmartPointer< const Self > ConstPointer
enum InitializationType {
Identity = 0,
GravityCenters,
ClosestTransform
}
typedef InputImageType::ConstPointer InputImageConstPointer
typedef InputImageType::Pointer InputImagePointer
typedef itk::Image< float, ImageDimension > InputImageType
typedef InputImageType::IOPixelType InputPixelType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, ImageDimension > MaskImageType
typedef MaskPyramidType::Pointer MaskPyramidPointer
typedef anima::PyramidImageFilter< MaskImageType, MaskImageType > MaskPyramidType
enum Metric {
SquaredCorrelation = 0,
Correlation,
MeanSquares
}
enum Optimizer {
Exhaustive = 0,
Bobyqa
}
enum OutputTransform {
outRigid = 0,
outTranslation,
outAffine,
outAnisotropic_Sim
}
typedef itk::SmartPointer< Self > Pointer
typedef InputImageType::PointType PointType
typedef PyramidType::Pointer PyramidPointer
typedef anima::PyramidImageFilter< InputImageType, InputImageType > PyramidType
typedef PyramidalBlockMatchingBridge Self
typedef itk::ProcessObject Superclass
enum SymmetryType {
Asymmetric = 0,
Symmetric,
Kissing
}
enum Transform {
Translation = 0,
Rigid,
Affine,
Directional_Affine
}
Public Member Functions
void Abort ()
virtual ::itk::LightObject::Pointer CreateAnother (void) const
unsigned int GetAffineDirection ()
Agregator GetAgregator ()
float GetAgregThreshold ()
double GetAngleUpperBound ()
unsigned int GetBlockSize ()
unsigned int GetBlockSpacing ()
double GetFinalRadius ()
unsigned int GetLastPyramidLevel ()
unsigned int GetMaximumIterations ()
Metric GetMetric ()
float GetMinimalTransformError ()
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfPyramidLevels ()
Optimizer GetOptimizer ()
unsigned int GetOptimizerMaximumIterations ()
InputImagePointer GetOutputImage ()
std::string GetOutputNearestRigidTransformFile ()
std::string GetOutputNearestSimilarityTransformFile ()
BaseTransformPointer GetOutputTransform ()
std::string GetOutputTransformFile ()
OutputTransform GetOutputTransformType ()
double GetPercentageKept ()
std::string GetResultFile ()
double GetScaleUpperBound ()
double GetSearchAngleRadius ()
double GetSearchRadius ()
double GetSearchScaleRadius ()
float GetSeStoppingThreshold ()
float GetStDevThreshold ()
double GetStepSize ()
SymmetryType GetSymmetryType ()
Transform GetTransform ()
InitializationType GetTransformInitializationType ()
double GetTranslateUpperBound ()
void SetAffineDirection (unsigned int val)
void SetAgregator (Agregator agregator)
void SetAgregThreshold (float AgregThreshold)
void SetAngleUpperBound (double AngleUpperBound)
void SetBlockGenerationMask (MaskImageType *mask)
void SetBlockSize (int blockSize)
void SetBlockSpacing (unsigned int blockSpacing)
void SetDirectionTransform (AffineTransformPointer directionTransform)
void SetDirectionTransform (std::string directionTransformFile)
void SetFinalRadius (double FinalRadius)
void SetFloatingImage (InputImageConstPointer floatingImage)
void SetInitialTransform (AffineTransformPointer initialTransform)
void SetInitialTransform (std::string initialTransformFile)
void SetLastPyramidLevel (unsigned int LastPyramidLevel)
void SetMaximumIterations (unsigned int MaximumIterations)
void SetMetric (Metric metric)
void SetMinimalTransformError (float MinimalTransformError)
void SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels)
void SetOptimizer (Optimizer optimizer)
void SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations)
void SetOutputNearestRigidTransformFile (std::string outputNRTransformFile)
void SetOutputNearestSimilarityTransformFile (std::string outputNearestSimilarityTransformFile)
void SetOutputTransform (BaseTransformPointer outputTransform)
void SetOutputTransformFile (std::string outputTransformFile)
void SetOutputTransformType (OutputTransform outputTransform)
void SetPercentageKept (double PercentageKept)
void SetProgressCallback (itk::CStyleCommand::Pointer callback)
void SetReferenceImage (InputImageConstPointer referenceImage)
void SetResultFile (std::string resultFile)
void SetScaleUpperBound (double ScaleUpperBound)
void SetSearchAngleRadius (double SearchAngleRadius)
void SetSearchRadius (double SearchRadius)
void SetSearchScaleRadius (double SearchScaleRadius)
void SetSeStoppingThreshold (float SeStoppingThreshold)
void SetStDevThreshold (float StDevThreshold)
void SetStepSize (double StepSize)
void SetSymmetryType (SymmetryType sym)
void SetTransform (Transform transform)
void SetTransformInitializationType (InitializationType transformInitializationType)
void SetTranslateUpperBound (double TranslateUpperBound)
void SetVerbose (bool value)
void Update () ITK_OVERRIDE
void WriteOutputs ()
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void EmitProgress (int prog)
PyramidalBlockMatchingBridge ()
void SetupPyramids ()
virtual ~PyramidalBlockMatchingBridge ()
Static Protected Member Functions
static void ManageProgress (itk::Object *caller, const itk::EventObject &event, void *clientData)
Detailed Description
template<unsigned int ImageDimension = 3>
class anima::PyramidalBlockMatchingBridge< ImageDimension >
Definition at line 15 of file animaPyramidalBlockMatchingBridge.h.
Member Typedef Documentation
AffineTransformPointer
template<unsigned int ImageDimension = 3> typedef AffineTransformType::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::AffineTransformPointer
Definition at line 35 of file animaPyramidalBlockMatchingBridge.h.
AffineTransformType
template<unsigned int ImageDimension = 3> typedef itk::AffineTransform<typename AgregatorType::ScalarType,ImageDimension> anima::PyramidalBlockMatchingBridge< ImageDimension >::AffineTransformType
Definition at line 34 of file animaPyramidalBlockMatchingBridge.h.
AgregatorType
template<unsigned int ImageDimension = 3> typedef anima::BaseTransformAgregator< ImageDimension > anima::PyramidalBlockMatchingBridge< ImageDimension >::AgregatorType
Definition at line 30 of file animaPyramidalBlockMatchingBridge.h.
BaseBlockMatchRegistrationPointer
template<unsigned int ImageDimension = 3> typedef BaseBlockMatchRegistrationType::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationPointer
Definition at line 41 of file animaPyramidalBlockMatchingBridge.h.
BaseBlockMatchRegistrationType
template<unsigned int ImageDimension = 3> typedef anima::BaseBMRegistrationMethod<InputImageType> anima::PyramidalBlockMatchingBridge< ImageDimension >::BaseBlockMatchRegistrationType
Definition at line 40 of file animaPyramidalBlockMatchingBridge.h.
BaseTransformPointer
template<unsigned int ImageDimension = 3> typedef BaseTransformType::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::BaseTransformPointer
Definition at line 32 of file animaPyramidalBlockMatchingBridge.h.
BaseTransformType
template<unsigned int ImageDimension = 3> typedef AgregatorType::BaseOutputTransformType anima::PyramidalBlockMatchingBridge< ImageDimension >::BaseTransformType
Definition at line 31 of file animaPyramidalBlockMatchingBridge.h.
ConstPointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<const Self> anima::PyramidalBlockMatchingBridge< ImageDimension >::ConstPointer
Definition at line 48 of file animaPyramidalBlockMatchingBridge.h.
InputImageConstPointer
template<unsigned int ImageDimension = 3> typedef InputImageType::ConstPointer anima::PyramidalBlockMatchingBridge< ImageDimension >::InputImageConstPointer
Definition at line 21 of file animaPyramidalBlockMatchingBridge.h.
InputImagePointer
template<unsigned int ImageDimension = 3> typedef InputImageType::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::InputImagePointer
Definition at line 20 of file animaPyramidalBlockMatchingBridge.h.
InputImageType
template<unsigned int ImageDimension = 3> typedef itk::Image<float,ImageDimension> anima::PyramidalBlockMatchingBridge< ImageDimension >::InputImageType
Definition at line 18 of file animaPyramidalBlockMatchingBridge.h.
InputPixelType
template<unsigned int ImageDimension = 3> typedef InputImageType::IOPixelType anima::PyramidalBlockMatchingBridge< ImageDimension >::InputPixelType
Definition at line 19 of file animaPyramidalBlockMatchingBridge.h.
MaskImagePointer
template<unsigned int ImageDimension = 3> typedef MaskImageType::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::MaskImagePointer
Definition at line 26 of file animaPyramidalBlockMatchingBridge.h.
MaskImageType
template<unsigned int ImageDimension = 3> typedef itk::Image<unsigned char, ImageDimension> anima::PyramidalBlockMatchingBridge< ImageDimension >::MaskImageType
Definition at line 25 of file animaPyramidalBlockMatchingBridge.h.
MaskPyramidPointer
template<unsigned int ImageDimension = 3> typedef MaskPyramidType::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::MaskPyramidPointer
Definition at line 28 of file animaPyramidalBlockMatchingBridge.h.
MaskPyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<MaskImageType,MaskImageType> anima::PyramidalBlockMatchingBridge< ImageDimension >::MaskPyramidType
Definition at line 27 of file animaPyramidalBlockMatchingBridge.h.
Pointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<Self> anima::PyramidalBlockMatchingBridge< ImageDimension >::Pointer
Definition at line 47 of file animaPyramidalBlockMatchingBridge.h.
PointType
template<unsigned int ImageDimension = 3> typedef InputImageType::PointType anima::PyramidalBlockMatchingBridge< ImageDimension >::PointType
Definition at line 23 of file animaPyramidalBlockMatchingBridge.h.
PyramidPointer
template<unsigned int ImageDimension = 3> typedef PyramidType::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::PyramidPointer
Definition at line 38 of file animaPyramidalBlockMatchingBridge.h.
PyramidType
template<unsigned int ImageDimension = 3> typedef anima::PyramidImageFilter<InputImageType,InputImageType> anima::PyramidalBlockMatchingBridge< ImageDimension >::PyramidType
Definition at line 37 of file animaPyramidalBlockMatchingBridge.h.
Self
template<unsigned int ImageDimension = 3> typedef PyramidalBlockMatchingBridge anima::PyramidalBlockMatchingBridge< ImageDimension >::Self
SmartPointer typedef support
Definition at line 44 of file animaPyramidalBlockMatchingBridge.h.
Superclass
template<unsigned int ImageDimension = 3> typedef itk::ProcessObject anima::PyramidalBlockMatchingBridge< ImageDimension >::Superclass
Definition at line 45 of file animaPyramidalBlockMatchingBridge.h.
Member Enumeration Documentation
Agregator
template<unsigned int ImageDimension = 3> enum anima::PyramidalBlockMatchingBridge::Agregator
Enumerator
MEstimation
LeastSquares
LeastTrimmedSquares
Definition at line 88 of file animaPyramidalBlockMatchingBridge.h.
InitializationType
template<unsigned int ImageDimension = 3> enum anima::PyramidalBlockMatchingBridge::InitializationType
Enumerator
Identity
GravityCenters
ClosestTransform
Definition at line 53 of file animaPyramidalBlockMatchingBridge.h.
Metric
template<unsigned int ImageDimension = 3> enum anima::PyramidalBlockMatchingBridge::Metric
Enumerator
SquaredCorrelation
Correlation
MeanSquares
Definition at line 75 of file animaPyramidalBlockMatchingBridge.h.
Optimizer
template<unsigned int ImageDimension = 3> enum anima::PyramidalBlockMatchingBridge::Optimizer
Enumerator
Exhaustive
Bobyqa
Definition at line 82 of file animaPyramidalBlockMatchingBridge.h.
OutputTransform
template<unsigned int ImageDimension = 3> enum anima::PyramidalBlockMatchingBridge::OutputTransform
Enumerator
outRigid
outTranslation
outAffine
outAnisotropic_Sim
Definition at line 95 of file animaPyramidalBlockMatchingBridge.h.
SymmetryType
template<unsigned int ImageDimension = 3> enum anima::PyramidalBlockMatchingBridge::SymmetryType
Enumerator
Asymmetric
Symmetric
Kissing
Definition at line 60 of file animaPyramidalBlockMatchingBridge.h.
Transform
template<unsigned int ImageDimension = 3> enum anima::PyramidalBlockMatchingBridge::Transform
Enumerator
Translation
Rigid
Affine
Directional_Affine
Definition at line 67 of file animaPyramidalBlockMatchingBridge.h.
Constructor & Destructor Documentation
PyramidalBlockMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalBlockMatchingBridge< ImageDimension >::PyramidalBlockMatchingBridge () protected
Definition at line 24 of file animaPyramidalBlockMatchingBridge.hxx.
References Asymmetric, Bobyqa, SquaredCorrelation, and Translation.
Referenced by anima::PyramidalBlockMatchingBridge< ImageDimension >::SetVerbose().
~PyramidalBlockMatchingBridge()
template<unsigned int ImageDimension> anima::PyramidalBlockMatchingBridge< ImageDimension >::~PyramidalBlockMatchingBridge () protected virtual
Definition at line 79 of file animaPyramidalBlockMatchingBridge.hxx.
Referenced by anima::PyramidalBlockMatchingBridge< ImageDimension >::SetVerbose().
Member Function Documentation
Abort()
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::Abort ()
Definition at line 84 of file animaPyramidalBlockMatchingBridge.hxx.
CreateAnother()
template<unsigned int ImageDimension = 3> virtual::itk::LightObject::Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::CreateAnother (void) const
EmitProgress()
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::EmitProgress (int prog) protected
Definition at line 497 of file animaPyramidalBlockMatchingBridge.hxx.
Referenced by anima::PyramidalBlockMatchingBridge< ImageDimension >::ManageProgress(), and anima::PyramidalBlockMatchingBridge< ImageDimension >::SetVerbose().
GetAffineDirection()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalBlockMatchingBridge< ImageDimension >::GetAffineDirection () inline
Definition at line 160 of file animaPyramidalBlockMatchingBridge.h.
GetAgregator()
template<unsigned int ImageDimension = 3> Agregator anima::PyramidalBlockMatchingBridge< ImageDimension >::GetAgregator () inline
Definition at line 202 of file animaPyramidalBlockMatchingBridge.h.
GetAgregThreshold()
template<unsigned int ImageDimension = 3> float anima::PyramidalBlockMatchingBridge< ImageDimension >::GetAgregThreshold () inline
Definition at line 208 of file animaPyramidalBlockMatchingBridge.h.
GetAngleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetAngleUpperBound () inline
Definition at line 196 of file animaPyramidalBlockMatchingBridge.h.
GetBlockSize()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalBlockMatchingBridge< ImageDimension >::GetBlockSize () inline
Definition at line 145 of file animaPyramidalBlockMatchingBridge.h.
GetBlockSpacing()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalBlockMatchingBridge< ImageDimension >::GetBlockSpacing () inline
Definition at line 148 of file animaPyramidalBlockMatchingBridge.h.
GetFinalRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetFinalRadius () inline
Definition at line 187 of file animaPyramidalBlockMatchingBridge.h.
GetLastPyramidLevel()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalBlockMatchingBridge< ImageDimension >::GetLastPyramidLevel () inline
Definition at line 217 of file animaPyramidalBlockMatchingBridge.h.
GetMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalBlockMatchingBridge< ImageDimension >::GetMaximumIterations () inline
Definition at line 169 of file animaPyramidalBlockMatchingBridge.h.
GetMetric()
template<unsigned int ImageDimension = 3> Metric anima::PyramidalBlockMatchingBridge< ImageDimension >::GetMetric () inline
Definition at line 163 of file animaPyramidalBlockMatchingBridge.h.
GetMinimalTransformError()
template<unsigned int ImageDimension = 3> float anima::PyramidalBlockMatchingBridge< ImageDimension >::GetMinimalTransformError () inline
Definition at line 172 of file animaPyramidalBlockMatchingBridge.h.
GetNameOfClass()
template<unsigned int ImageDimension = 3> virtual const char* anima::PyramidalBlockMatchingBridge< ImageDimension >::GetNameOfClass () const virtual
GetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalBlockMatchingBridge< ImageDimension >::GetNumberOfPyramidLevels () inline
Definition at line 214 of file animaPyramidalBlockMatchingBridge.h.
GetOptimizer()
template<unsigned int ImageDimension = 3> Optimizer anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOptimizer () inline
Definition at line 166 of file animaPyramidalBlockMatchingBridge.h.
GetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> unsigned int anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOptimizerMaximumIterations () inline
Definition at line 175 of file animaPyramidalBlockMatchingBridge.h.
GetOutputImage()
template<unsigned int ImageDimension = 3> InputImagePointer anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOutputImage () inline
Definition at line 113 of file animaPyramidalBlockMatchingBridge.h.
GetOutputNearestRigidTransformFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOutputNearestRigidTransformFile () inline
Definition at line 139 of file animaPyramidalBlockMatchingBridge.h.
GetOutputNearestSimilarityTransformFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOutputNearestSimilarityTransformFile () inline
Definition at line 142 of file animaPyramidalBlockMatchingBridge.h.
GetOutputTransform()
template<unsigned int ImageDimension = 3> BaseTransformPointer anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOutputTransform () inline
Definition at line 124 of file animaPyramidalBlockMatchingBridge.h.
GetOutputTransformFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOutputTransformFile () inline
Definition at line 136 of file animaPyramidalBlockMatchingBridge.h.
GetOutputTransformType()
template<unsigned int ImageDimension = 3> OutputTransform anima::PyramidalBlockMatchingBridge< ImageDimension >::GetOutputTransformType () inline
Definition at line 205 of file animaPyramidalBlockMatchingBridge.h.
GetPercentageKept()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetPercentageKept () inline
Definition at line 220 of file animaPyramidalBlockMatchingBridge.h.
GetResultFile()
template<unsigned int ImageDimension = 3> std::string anima::PyramidalBlockMatchingBridge< ImageDimension >::GetResultFile () inline
Setter/Getter for parameters
Definition at line 133 of file animaPyramidalBlockMatchingBridge.h.
GetScaleUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetScaleUpperBound () inline
Definition at line 199 of file animaPyramidalBlockMatchingBridge.h.
GetSearchAngleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetSearchAngleRadius () inline
Definition at line 181 of file animaPyramidalBlockMatchingBridge.h.
GetSearchRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetSearchRadius () inline
Definition at line 178 of file animaPyramidalBlockMatchingBridge.h.
GetSearchScaleRadius()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetSearchScaleRadius () inline
Definition at line 184 of file animaPyramidalBlockMatchingBridge.h.
GetSeStoppingThreshold()
template<unsigned int ImageDimension = 3> float anima::PyramidalBlockMatchingBridge< ImageDimension >::GetSeStoppingThreshold () inline
Definition at line 211 of file animaPyramidalBlockMatchingBridge.h.
GetStDevThreshold()
template<unsigned int ImageDimension = 3> float anima::PyramidalBlockMatchingBridge< ImageDimension >::GetStDevThreshold () inline
Definition at line 151 of file animaPyramidalBlockMatchingBridge.h.
GetStepSize()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetStepSize () inline
Definition at line 190 of file animaPyramidalBlockMatchingBridge.h.
GetSymmetryType()
template<unsigned int ImageDimension = 3> SymmetryType anima::PyramidalBlockMatchingBridge< ImageDimension >::GetSymmetryType () inline
Definition at line 154 of file animaPyramidalBlockMatchingBridge.h.
GetTransform()
template<unsigned int ImageDimension = 3> Transform anima::PyramidalBlockMatchingBridge< ImageDimension >::GetTransform () inline
Definition at line 157 of file animaPyramidalBlockMatchingBridge.h.
GetTransformInitializationType()
template<unsigned int ImageDimension = 3> InitializationType anima::PyramidalBlockMatchingBridge< ImageDimension >::GetTransformInitializationType () inline
Definition at line 223 of file animaPyramidalBlockMatchingBridge.h.
GetTranslateUpperBound()
template<unsigned int ImageDimension = 3> double anima::PyramidalBlockMatchingBridge< ImageDimension >::GetTranslateUpperBound () inline
Definition at line 193 of file animaPyramidalBlockMatchingBridge.h.
ManageProgress()
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::ManageProgress (itk::Object * caller, const itk::EventObject & event, void * clientData) static protected
Definition at line 504 of file animaPyramidalBlockMatchingBridge.hxx.
References anima::PyramidalBlockMatchingBridge< ImageDimension >::EmitProgress().
Referenced by anima::PyramidalBlockMatchingBridge< ImageDimension >::SetVerbose().
New()
template<unsigned int ImageDimension = 3> static Pointer anima::PyramidalBlockMatchingBridge< ImageDimension >::New () static
SetAffineDirection()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetAffineDirection (unsigned int val) inline
Definition at line 161 of file animaPyramidalBlockMatchingBridge.h.
SetAgregator()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetAgregator (Agregator agregator) inline
Definition at line 203 of file animaPyramidalBlockMatchingBridge.h.
SetAgregThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetAgregThreshold (float AgregThreshold) inline
Definition at line 209 of file animaPyramidalBlockMatchingBridge.h.
SetAngleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetAngleUpperBound (double AngleUpperBound) inline
Definition at line 197 of file animaPyramidalBlockMatchingBridge.h.
SetBlockGenerationMask()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetBlockGenerationMask (MaskImageType * mask) inline
Definition at line 226 of file animaPyramidalBlockMatchingBridge.h.
SetBlockSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetBlockSize (int blockSize) inline
Definition at line 146 of file animaPyramidalBlockMatchingBridge.h.
SetBlockSpacing()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetBlockSpacing (unsigned int blockSpacing) inline
Definition at line 149 of file animaPyramidalBlockMatchingBridge.h.
SetDirectionTransform() [1/2]
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetDirectionTransform (AffineTransformPointer directionTransform) inline
Definition at line 121 of file animaPyramidalBlockMatchingBridge.h.
SetDirectionTransform() [2/2]
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetDirectionTransform (std::string directionTransformFile)
Definition at line 118 of file animaPyramidalBlockMatchingBridge.hxx.
SetFinalRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetFinalRadius (double FinalRadius) inline
Definition at line 188 of file animaPyramidalBlockMatchingBridge.h.
SetFloatingImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetFloatingImage (InputImageConstPointer floatingImage) inline
Definition at line 111 of file animaPyramidalBlockMatchingBridge.h.
SetInitialTransform() [1/2]
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetInitialTransform (AffineTransformPointer initialTransform) inline
Setter for transform
Definition at line 118 of file animaPyramidalBlockMatchingBridge.h.
SetInitialTransform() [2/2]
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetInitialTransform (std::string initialTransformFile)
Definition at line 93 of file animaPyramidalBlockMatchingBridge.hxx.
SetLastPyramidLevel()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetLastPyramidLevel (unsigned int LastPyramidLevel) inline
Definition at line 218 of file animaPyramidalBlockMatchingBridge.h.
SetMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetMaximumIterations (unsigned int MaximumIterations) inline
Definition at line 170 of file animaPyramidalBlockMatchingBridge.h.
SetMetric()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetMetric (Metric metric) inline
Definition at line 164 of file animaPyramidalBlockMatchingBridge.h.
SetMinimalTransformError()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetMinimalTransformError (float MinimalTransformError) inline
Definition at line 173 of file animaPyramidalBlockMatchingBridge.h.
SetNumberOfPyramidLevels()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetNumberOfPyramidLevels (unsigned int NumberOfPyramidLevels) inline
Definition at line 215 of file animaPyramidalBlockMatchingBridge.h.
SetOptimizer()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetOptimizer (Optimizer optimizer) inline
Definition at line 167 of file animaPyramidalBlockMatchingBridge.h.
SetOptimizerMaximumIterations()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetOptimizerMaximumIterations (unsigned int OptimizerMaximumIterations) inline
Definition at line 176 of file animaPyramidalBlockMatchingBridge.h.
SetOutputNearestRigidTransformFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetOutputNearestRigidTransformFile (std::string outputNRTransformFile) inline
Definition at line 140 of file animaPyramidalBlockMatchingBridge.h.
SetOutputNearestSimilarityTransformFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetOutputNearestSimilarityTransformFile (std::string outputNearestSimilarityTransformFile) inline
Definition at line 143 of file animaPyramidalBlockMatchingBridge.h.
SetOutputTransform()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetOutputTransform (BaseTransformPointer outputTransform) inline
Definition at line 125 of file animaPyramidalBlockMatchingBridge.h.
SetOutputTransformFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetOutputTransformFile (std::string outputTransformFile) inline
Definition at line 137 of file animaPyramidalBlockMatchingBridge.h.
SetOutputTransformType()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetOutputTransformType (OutputTransform outputTransform) inline
Definition at line 206 of file animaPyramidalBlockMatchingBridge.h.
SetPercentageKept()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetPercentageKept (double PercentageKept) inline
Definition at line 221 of file animaPyramidalBlockMatchingBridge.h.
SetProgressCallback()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetProgressCallback (itk::CStyleCommand::Pointer callback) inline
Definition at line 127 of file animaPyramidalBlockMatchingBridge.h.
SetReferenceImage()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetReferenceImage (InputImageConstPointer referenceImage) inline
Setter for images
Definition at line 110 of file animaPyramidalBlockMatchingBridge.h.
SetResultFile()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetResultFile (std::string resultFile) inline
Definition at line 134 of file animaPyramidalBlockMatchingBridge.h.
SetScaleUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetScaleUpperBound (double ScaleUpperBound) inline
Definition at line 200 of file animaPyramidalBlockMatchingBridge.h.
SetSearchAngleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetSearchAngleRadius (double SearchAngleRadius) inline
Definition at line 182 of file animaPyramidalBlockMatchingBridge.h.
SetSearchRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetSearchRadius (double SearchRadius) inline
Definition at line 179 of file animaPyramidalBlockMatchingBridge.h.
SetSearchScaleRadius()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetSearchScaleRadius (double SearchScaleRadius) inline
Definition at line 185 of file animaPyramidalBlockMatchingBridge.h.
SetSeStoppingThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetSeStoppingThreshold (float SeStoppingThreshold) inline
Definition at line 212 of file animaPyramidalBlockMatchingBridge.h.
SetStDevThreshold()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetStDevThreshold (float StDevThreshold) inline
Definition at line 152 of file animaPyramidalBlockMatchingBridge.h.
SetStepSize()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetStepSize (double StepSize) inline
Definition at line 191 of file animaPyramidalBlockMatchingBridge.h.
SetSymmetryType()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetSymmetryType (SymmetryType sym) inline
Definition at line 155 of file animaPyramidalBlockMatchingBridge.h.
SetTransform()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetTransform (Transform transform) inline
Definition at line 158 of file animaPyramidalBlockMatchingBridge.h.
SetTransformInitializationType()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetTransformInitializationType (InitializationType transformInitializationType) inline
Definition at line 224 of file animaPyramidalBlockMatchingBridge.h.
SetTranslateUpperBound()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetTranslateUpperBound (double TranslateUpperBound) inline
Definition at line 194 of file animaPyramidalBlockMatchingBridge.h.
SetupPyramids()
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetupPyramids () protected
Definition at line 603 of file animaPyramidalBlockMatchingBridge.hxx.
Referenced by anima::PyramidalBlockMatchingBridge< ImageDimension >::SetVerbose().
SetVerbose()
template<unsigned int ImageDimension = 3> void anima::PyramidalBlockMatchingBridge< ImageDimension >::SetVerbose (bool value) inline
Definition at line 228 of file animaPyramidalBlockMatchingBridge.h.
References anima::PyramidalBlockMatchingBridge< ImageDimension >::EmitProgress(), anima::PyramidalBlockMatchingBridge< ImageDimension >::ManageProgress(), anima::PyramidalBlockMatchingBridge< ImageDimension >::PyramidalBlockMatchingBridge(), anima::PyramidalBlockMatchingBridge< ImageDimension >::SetupPyramids(), and anima::PyramidalBlockMatchingBridge< ImageDimension >::~PyramidalBlockMatchingBridge().
Update()
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::Update ()
Definition at line 143 of file animaPyramidalBlockMatchingBridge.hxx.
References Affine, Asymmetric, Bobyqa, Correlation, Exhaustive, Kissing, MeanSquares, Rigid, anima::BaseBlockMatcher< TInputImageType >::SetBlockPercentageKept(), anima::LTSWTransformAgregator< NDimensions >::SetLTSCut(), anima::MEstTransformAgregator< NDimensions >::SetMEstimateFactor(), SquaredCorrelation, Symmetric, and Translation.
WriteOutputs()
template<unsigned int ImageDimension> void anima::PyramidalBlockMatchingBridge< ImageDimension >::WriteOutputs ()
Definition at line 514 of file animaPyramidalBlockMatchingBridge.hxx.
The documentation for this class was generated from the following files:
animaPyramidalBlockMatchingBridge.h
animaPyramidalBlockMatchingBridge.hxx